packages/blocks/src/page-block/utils/container-operations.ts, tests/hotkey.spec.ts
=> fix: tranform undo error

packages/blocks/src/__internal__/utils/gesture.ts, packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, tests/selection.spec.ts
repaire context menu selection actions
=> feat: add double click choose word

packages/store/src/store.spec.ts, packages/store/src/store.ts, packages/store/src/utils/jsx.spec.ts, packages/store/src/utils/jsx.ts, tests/link.spec.ts, tests/list.spec.ts, tests/utils/actions/misc.ts, tests/utils/asserts.ts
- parse text with format
- update snapshot
- throw an error at console error
=> Test: jsx snapshot parse text format

packages/store/src/base.ts
fix that  if has multi attributes text node export would not be wright
=> fix: export attr

packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/store/src/text-adapter.ts
- edit link text will cancel link
It is a workaround, it broke format skip by paste
=> fix: edit link broken

.github/workflows/release.yml
closes https://github.com/toeverything/blocksuite/issues/170
=> chore: disable changesets create github release

packages/blocks/src/list-block/list-block.ts, packages/blocks/src/page-block/default/selection-manager.ts
Clicking on the list symbol could select the whole block
=> feat:add list selection

packages/blocks/src/__internal__/debug-menu.ts
=> fix: missing debug icon in safari

packages/blocks/src/__internal__/debug-menu.ts, packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/editor/src/components/editor-container/editor-container.ts, packages/editor/src/index.ts, packages/playground/src/main.ts, packages/playground/src/style.css, packages/store/src/__tests__/space.spec.ts, packages/store/src/store.ts, tests/basic.spec.ts, tests/clipboard.spec.ts, tests/link.spec.ts, tests/paragraph.spec.ts, tests/utils/actions/keyboard.ts, tests/utils/actions/misc.ts, tests/utils/declare-test-window.ts
Unbind block from store, block only depend on Space
=> feat: unbind block from store

packages/blocks/src/page-block/default/selection-manager.ts
Fix error when selecting nothing
=> Bugfix: format quick bar (cursor part)

packages/blocks/src/__internal__/utils/selection.ts, tests/selection.spec.ts, tests/utils/actions/drag.ts
=> bugfix: After drag horizontally beyond the editor-container and detele with backspace, typing one character will appear two

packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/components/link-popover/link-popover.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/editor/src/components/editor-container/editor-container.ts
=> chore: add super call in all lit lifecycle callbacks

packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/style.css
Fix the rectangle of the selection is in the wrong position.
There are two smol issues here 🤔: 
1. Is there a better-named alternative to `affine-default-viewport`? What do you think.
2. I am trying to understand your design's original intention, but I am confused. In your original design, if both `selectionRect` and `selectedRects` need to be positioned relative to the viewport, why does one use position absolute and the other use position fixed? Or do you want the selectionRect to scroll with the page?
Closes: #194
=> fix(blocks): rectangle of the selection in wrong position

packages/blocks/src/__internal__/utils/hotkey.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
Did some opinionated optimizations.
=> fix(blocks): remove listeners

packages/blocks/src/components/link-popover/link-popover.ts, packages/blocks/src/components/link-popover/styles.ts
In order to make the style of the link editing popover more beautiful, I made adjustments.
=> chore: adjust popover style

packages/blocks/src/components/button.ts
For aesthetics, the border radius of the popover icon is adjusted.
=> chore:update popover icon style

packages/blocks/src/image-block/image-block.ts, packages/blocks/src/image-block/style.css, packages/blocks/src/page-block/default/selection-manager.ts, packages/playground/src/main.ts, tests/embed.spec.ts, tests/utils/actions/click.ts, tests/utils/actions/drag.ts, tests/utils/actions/misc.ts, tests/utils/asserts.ts
=> add image test

packages/blocks/src/components/format-quick-bar/config.ts, packages/blocks/src/components/format-quick-bar/index.ts, tests/format-quick-bar.spec.ts
- Fix can not convert list to heading
- Add test
=> fix: paragraph convert

packages/blocks/src/page-block/edgeless/utils.ts, packages/blocks/src/page-block/utils/container-operations.ts
Fixes: #250 
https://user-images.githubusercontent.com/14026360/205466227-4c12767d-003b-4d97-b36b-59d9311cef6f.mov
=> feat: blocks arrangement in edgeless mode

packages/playground/src/main.ts, packages/store/src/space.ts, packages/store/src/workspace.ts
=> feat: BlockSchema type in space class

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
=> fix: selectively join deleted rich text

packages/blocks/src/page-block/default/default-page-block.ts, packages/playground/src/main.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/workspace/__tests__/test-app.ts, packages/store/src/workspace/__tests__/test-entry.ts, packages/store/src/workspace/page.ts, packages/store/src/workspace/workspace.ts, tests/basic.spec.ts, tests/utils/asserts.ts
=> fix: respond to newly added space & trigger pageUpdates

packages/store/src/workspace/workspace.ts
When use `setPageMeta` to update value, it just the value which want to be updated. So in `setPage`, it should assign the original value and update
=> fix: assign original value in setPage

packages/blocks/src/__internal__/utils/std.ts
Fixes: https://github.com/toeverything/blocksuite/issues/274
=> fix: type on `throttle` function

packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/workspace/search.ts, packages/store/src/workspace/workspace.ts
~~add a util function help search bar find page space by block id~~
preprocess the search results and return them in the form of Map<BlockId, SpaceId>
=> feat: return clearer search results

packages/blocks/src/__internal__/utils/types.ts, packages/editor/src/components/debug-menu/debug-menu.ts, packages/editor/src/components/editor-container/editor-container.ts
Change editor mode from state to property, editor's mode should be controled by it container, no mater its initial value or changes
=> feat: change editor mode from state to property

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/editor/src/components/editor-container/editor-container.ts
Mouse mode should be a global state in a editor component
=> fix: move mouse mode to top

packages/playground/src/main.ts
=> fix: init with empty payload

packages/blocks/src/page-block/default/style.css
=> fix: shake title when dragging

packages/store/src/workspace/search.ts
This pr will improve the tokenize quality of the existing word segmenter with latin words:
case insensitive
latin character normalizations
literal normalizations
morpheme normalizations
=> feat: improve tokenize result quality

packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/components/format-quick-bar/index.ts, packages/blocks/src/page-block/default/selection-manager.ts, tests/format-quick-bar.spec.ts
https://user-images.githubusercontent.com/18554747/208491970-57ed4412-c30e-40ad-9440-692fdfa5db17.mov
=> feat: show format bar when dbclick text

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, tests/paragraph.spec.ts
=> fix: start backspace after list

package.json, packages/blocks/package.json, packages/blocks/src/std.ts, packages/blocks/vite.config.ts, pnpm-lock.yaml
Refs: https://github.com/toeverything/blocksuite/pull/354#issuecomment-1357000681
=> build: export `__internal__` as std

packages/blocks/package.json, packages/blocks/src/shape-block/utils/polygon-utils.ts, packages/blocks/src/shape-block/utils/rectangle-helpers.ts, packages/blocks/src/shape-block/utils/shape-style.ts, packages/blocks/src/shape-block/utils/triangle-helpers.ts, packages/blocks/src/shape-block/utils/utils.ts, packages/blocks/src/shape-block/utils/vec.ts, pnpm-lock.yaml
Related to #387, this PR makes the `blocks` package compatible with Next.js.
=> refactor: remove cjs vec deps

packages/blocks/src/components/link-popover/styles.ts
=> Fix: link overflow

tests/paragraph.spec.ts
=> test: merge test for optimization

packages/editor/src/managers/clipboard/paste-manager.ts
=> fix: paste in title

packages/editor/src/components/editor-container/editor-container.ts, packages/editor/src/managers/clipboard/content-parser/index.ts, packages/editor/src/managers/file-exporter/file-exporter.ts, packages/store/src/utils/disposable.ts, packages/store/src/utils/signal.ts
Please review commit by commit.
<a href="https://www.loom.com/share/6aa846367d73451d9c4f41048ad8ca87"><img width="996" alt="Cole's screen capture of 2022-11 Various refactor ideas while learning by colelawrence · Pull Request #205 · toeverythingblocksuite - 10 November 2022 2022-11-10 at 08 14 19@2x" src="https://user-images.githubusercontent.com/2925395/201101096-7559ec9a-d29c-4371-bddb-42b0f18872f5.png">
<b>Loom: Pull Request #205 · toeverything/blocksuite - 10 November 2022</b>
</a>
=> refactor: improving signal typing & various cleanups

packages/editor/src/managers/clipboard/paste-manager.ts
=> fix: paste image occur twice

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/components/format-quick-bar/format-bar-node.ts, tests/format-quick-bar.spec.ts, tests/paragraph.spec.ts, tests/utils/asserts.ts
=> fix: the unusual behaviour of line break preceding indented line

packages/blocks/src/__internal__/utils/selection.ts
fix get scroll container of block suit
=> fix: scroll container

packages/blocks/src/code-block/code-block.ts, packages/blocks/src/code-block/components/syntax-code-block.ts, tests/code.spec.ts
fix https://github.com/toeverything/blocksuite/issues/334
before
after
=> feat: add lazy loading for highlight

packages/blocks/src/code-block/code-block.ts, packages/blocks/src/code-block/components/index.ts, packages/blocks/src/code-block/components/loader.ts, packages/blocks/src/code-block/components/syntax-code-block.ts, packages/blocks/src/code-block/style.css, packages/blocks/src/page-block/default/components.ts, packages/playground/src/style.css, tests/code.spec.ts, tests/utils/actions/click.ts, tests/utils/actions/misc.ts
1. Code block now has loading icon
https://user-images.githubusercontent.com/20554850/209768871-ecca8977-552b-4e00-9556-4aea3e4d762a.mov
3. Language will disappear unless hovering on code block
=> feat: adding loading icon, improving unit test

packages/blocks/src/components/format-quick-bar/index.ts, tests/format-quick-bar.spec.ts
https://user-images.githubusercontent.com/18554747/209855823-edc7c90a-3074-4b09-a104-17356d12624a.mov
=> fix: format quick bar should only display one at a time

packages/blocks/src/__internal__/utils/selection.ts
=> fix: double click range error on blank area

packages/editor/src/managers/clipboard/copy-cut-manager.ts
variable checked at line 108-109
=> fix: double check nullable

.github/workflows/test.yaml
=> feat: run store testing if package change

.github/workflows/test.yaml, packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/__internal__/utils/common-operations.ts, packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/__internal__/utils/selection.ts, packages/store/playwright.config.ts, packages/store/src/workspace/page.ts, tests/list.spec.ts, tests/paragraph.spec.ts, tests/selection.spec.ts, tests/utils/actions/keyboard.ts
=> refactor: flatten line start backspace

packages/react/examples/next/.eslintrc.cjs, packages/react/examples/next/.eslintrc.json
=> style: fix eslint issue

packages/store/package.json, pnpm-lock.yaml
Related: https://github.com/yjs/yjs/issues/438
=> chore: bump version

packages/playground/src/components/debug-menu.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/store.ts, packages/store/src/utils/jsx.ts, packages/store/src/workspace/workspace.ts, tests/utils/asserts.ts
This will also be used for dumping file binaries in AFFiNE.
=> feat: support ydoc binary export

packages/blocks/src/components/link-popover/styles.ts, packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/default/default-page-block.ts
- link preview should not wrap
- should not do side effect at render
- clean code
=> chore: clean code

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, tests/list.spec.ts, tests/paragraph.spec.ts
fix #507
Modify indent-related logic and update the corresponding tests.
=> fix: indent operation in rich text

tests/utils/actions/misc.ts
Related to https://github.com/toeverything/blocksuite/issues/285 https://github.com/toeverything/blocksuite/issues/286
=> chore: re-enable console error

packages/blocks/src/components/toast.ts
=> fix: toast dom not removed

packages/blocks/package.json, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/surface-block/surface-block.ts, packages/phasor/src/debug-utils.ts, packages/phasor/src/index.ts, packages/playground/examples/canvas/main.ts, pnpm-lock.yaml
=> feat: add phasor edgeless wheel event binding

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/__internal__/utils/std.ts
indent should not work under embed/divider/code
https://user-images.githubusercontent.com/18554747/210851836-7745c8b9-4e76-4656-a2d3-6996e8c532ac.mov
Related to https://github.com/toeverything/blocksuite/issues/445
=> fix: indent should not work under some block

packages/blocks/src/__internal__/utils/common-operations.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/default/utils.ts, packages/editor/src/managers/clipboard/content-parser/index.ts
Fixes #536 
https://user-images.githubusercontent.com/102217452/210751029-1edfd527-8257-46a0-be6e-f859bff28d46.mov
=> fix: export HTML or Markdown format lost

scripts/publish-to-github.sh
=> build: nightly version

packages/playground/src/utils.ts, packages/playground/vite.config.ts
For now, the old version playground will affect the new version playground
=> fix(playground): split room in different version

packages/blocks/src/components/drag-handle.ts, packages/blocks/src/page-block/default/selection-manager.ts
=> fix: block shouldn't highlighted when not dragging

packages/blocks/src/page-block/default/default-page-block.ts
=> fix: multi-line title size after undo/redo

packages/blocks/src/__internal__/utils/components.ts, packages/blocks/src/page-block/default/selection-manager.ts, tests/format-quick-bar.spec.ts, tests/hotkey.spec.ts, tests/link.spec.ts, tests/list.spec.ts, tests/paragraph.spec.ts, tests/utils/asserts.ts
Fixes: https://github.com/toeverything/blocksuite/issues/582
=> fix: use flex in children container

packages/blocks/src/page-block/page-model.ts, tests/utils/asserts.ts
=> refactor: revert page@2

packages/blocks/src/components/drag-handle.ts
Fixes: https://github.com/toeverything/blocksuite/issues/616
=> fix: move drag handle when resize window

packages/playground/src/data/index.ts, packages/playground/src/env.d.ts, packages/playground/src/utils.ts
=> refactor: simplify playground params detection

packages/blocks/src/page-block/default/selection-manager.ts
=> fix: dispose quill keyboard handler before block selection

packages/blocks/src/page-block/default/utils.ts
=> fix: use manual shallow copy on `DOMRect`

packages/store/src/text-adapter.ts
=> fix: return the correct delta result in `sliceToDelta`

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
Fixes: https://github.com/toeverything/blocksuite/issues/644
=> refactor: partially switch to `addBlockByFlavour` equivalent

packages/editor/src/managers/clipboard/content-parser/parse-html.ts
=> fix: parse inline html into single paragraph

tests/clipboard.spec.ts
=> test: add test case for pasting html

packages/blocks/package.json, packages/blocks/src/__internal__/rich-text/link-node/create-link.ts, packages/blocks/src/__internal__/rich-text/link-node/link-node.ts, packages/blocks/src/__internal__/rich-text/link-node/mock-select-node.ts, packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/format-quick-bar/format-bar-node.ts, pnpm-lock.yaml
- Fix blot types
- Add parchment for types
=> fix: blot types

packages/blocks/src/page-block/default/selection-manager.ts
=> fix: collect wrong BaseBlockModel[] at _block()

packages/blocks/src/page-block/default/default-page-block.ts, packages/global/src/index.d.ts, packages/playground/src/utils.ts, packages/store/src/workspace/page.ts, packages/store/src/workspace/workspace.ts
Upstream: #689 
Co-authored-by: Whitewater <me@waterwater.moe>
=> feat: support `readonly` flag in store

packages/phasor/src/container.ts, packages/phasor/src/debug-utils.ts, packages/phasor/src/elements.ts, packages/phasor/src/grid.ts, packages/phasor/src/index.ts, packages/phasor/src/renderer.ts, packages/playground/examples/canvas/main.ts
Should use new PRs for: 
* Shape element types
* DOM-based selection box
* Testing
=> feat: init ymap-based surface elements

packages/blocks/src/page-block/utils/bind-hotkey.ts
Fixes: https://github.com/toeverything/blocksuite/issues/682
=> fix: undo/redo is unavailable in title

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/store/src/text-adapter.ts, packages/store/src/utils/utils.ts, tests/code.spec.ts, tests/paragraph.spec.ts
Lo|**ngT**|ext <- Enter
Lo
|ngText
Lo|**ngT**|ext <- Enter
Lo
|ext
=> fix: delete selected text on enter

packages/phasor/package.json, packages/phasor/src/container.ts, packages/phasor/src/debug-utils.ts, packages/phasor/src/elements.ts, packages/phasor/src/grid.ts, packages/phasor/src/utils.ts, packages/playground/examples/canvas/main.ts, pnpm-lock.yaml
=> feat: init fractional indexing on surface elements

tests/clipboard.spec.ts, tests/code.spec.ts, tests/list.spec.ts, tests/selection.spec.ts, tests/utils/actions/keyboard.ts
Flaky test case founded in https://github.com/toeverything/blocksuite/pull/729/files
=> fix: flaky test case with raw enter press

packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/edgeless/mode-controllers/shape.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/editor/src/components/editor-container.ts, packages/playground/src/components/debug-menu.ts, packages/playground/src/utils.ts, packages/store/src/awareness.ts, packages/store/src/space.ts, packages/store/src/store.ts, packages/store/src/text-adapter.ts, packages/store/src/workspace/page.ts, packages/store/src/workspace/workspace.ts, tests/utils/actions/misc.ts
`AwarenessStore` reflects the definition of this module better. It's our data model API built on top of `YAwareness` (that produces `RawAwarenessState`).
=> refactor: `AwarenessAdapter` -> `AwarenessStore`

packages/blocks/src/page-block/edgeless/components.ts
=> fix: edgeless selection rect index over block hub

packages/blocks/src/__internal__/rich-text/rich-text.ts
Fixes: https://github.com/toeverything/blocksuite/issues/684
=> fix: try to re-attach the quill when connected

packages/store/src/text-adapter.ts, tests/clipboard.spec.ts
=> fix: parse partially select text in `sliceToDelta`

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/components/slash-menu/index.ts, tests/slash-menu.spec.ts
https://user-images.githubusercontent.com/18554747/213876956-74eccc03-3a4d-4e7f-ac8b-2d17269ff5f7.mov
=> fix: slash menu position at line start

README.md, packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts, packages/playground/src/utils.ts, packages/store/src/store.ts
=> feat: enable surface by default

.github/workflows/browser-compatibility.yml, .github/workflows/comment-trigger.yml
implement the rest of #335, use `/tier1` comment to trigger the workflow.
=> ci: trigger browser compatibility by comment

packages/playground/src/data/index.ts, packages/playground/src/main.ts, packages/playground/src/utils.ts
https://blocksuite-git-20230123-import-markdown-toeverything.vercel.app/?init=https://raw.githubusercontent.com/toeverything/blocksuite/master/README.md
=> feat(playground): import markdown from url

README.md
Closes: https://github.com/toeverything/blocksuite/issues/816
=> docs: add codesandbox template link

packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/playground/src/data/index.ts
=> fix(edgeless): surface structure with `?init=empty`

.github/workflows/build.yaml
a workaround for https://github.com/toeverything/blocksuite/issues/818
=> ci: build next.js example

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, tests/code.spec.ts, tests/hotkey.spec.ts
=> feat: support ctrl+enter shortcut

packages/blocks/src/components/blockhub.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/default/utils.ts
Fixes: https://github.com/toeverything/blocksuite/issues/853
=> refactor(blocks): move drag handle into default page block

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/code-block/code-model.ts, packages/editor/src/managers/clipboard/content-parser/parse-html.ts, packages/editor/src/managers/clipboard/types.ts
=> refactor(blocks): remove redundant `type` field in code block

packages/react/package.json, packages/react/src/store/index.tsx, pnpm-lock.yaml
Related: https://github.com/pmndrs/zustand/discussions/1180
=> refactor(react): drop deprecated function in zustand

packages/blocks/src/database-block/database-block.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/utils/utils.ts, packages/store/src/workspace/page.ts, packages/store/src/workspace/workspace.ts, tests/blockhub.spec.ts, tests/clipboard.spec.ts, tests/drag.spec.ts, tests/link.spec.ts, tests/list.spec.ts, tests/utils/asserts.ts
Related: https://github.com/toeverything/blocksuite/issues/151
=> refactor(store): use schema in `syncBlockProps`

packages/blocks/src/components/format-quick-bar/button.ts, packages/blocks/src/components/format-quick-bar/format-bar-node.ts, packages/blocks/src/components/slash-menu/slash-menu-node.ts, packages/blocks/src/page-block/utils/container-operations.ts, packages/global/index.d.ts, packages/global/src/config/consts/blockhub.ts, packages/store/src/base.ts, tests/format-quick-bar.spec.ts
Fix https://github.com/toeverything/blocksuite/pull/860#discussion_r1088186641
=> fix: update code type

packages/blocks/src/code-block/code-model.ts, packages/blocks/src/list-block/list-model.ts, packages/blocks/src/paragraph-block/paragraph-model.ts, packages/global/src/utils.ts, packages/store/src/base.ts, packages/store/src/utils/utils.ts, packages/store/src/workspace/page.ts, packages/store/src/workspace/workspace.ts
Related: https://github.com/toeverything/blocksuite/issues/151
=> refactor: yText enable by `textValue`

packages/blocks/src/__internal__/utils/selection.ts, tests/selection.spec.ts, tests/utils/actions/misc.ts
1. Add new frame to page
2. Select texts on cross-frame
https://user-images.githubusercontent.com/27926/215264597-a8bb0bcb-2dc4-4842-9ad6-bbb2b99e71fa.mov
=> fix: keep native range on cross-frame dragging

.github/workflows/test.yaml, packages/playground/src/data/index.ts, packages/react/examples/next/src/components/PageManger.tsx, packages/react/package.json, packages/react/src/components/Editor/index.tsx, packages/react/src/editor.ts, packages/react/src/index.ts, packages/react/src/store/index.tsx
Refs: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
=> feat(react,next-example): add `onInit` props

packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/page-block/default/selection-manager.ts
Related: https://github.com/toeverything/blocksuite/pull/876#issuecomment-1407446494
=> fix: should select text in title after selecting text in frame

packages/phasor/src/elements/base-element.ts, packages/phasor/src/elements/debug/debug-element.ts, packages/phasor/src/elements/shape/shape-element.ts, packages/phasor/src/grid.ts, packages/phasor/src/utils/hit-utils.ts
=> feat(phasor): add hit test utils

packages/store/src/workspace/page.ts
Fixes: https://github.com/toeverything/blocksuite/issues/893
=> fix: delete children by default

tests/paragraph.spec.ts
Related: https://github.com/toeverything/blocksuite/issues/893
=> test: press tab in paragraph children

packages/blocks/package.json, packages/blocks/src/__internal__/utils/gesture.ts, packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/database-block/components/column-type/database-number-type.ts, packages/blocks/src/database-block/components/column-type/database-select-type.ts, packages/blocks/src/database-block/components/database-edit-column.ts, packages/blocks/src/database-block/database-block.ts, packages/blocks/src/database-block/utils/index.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/global/src/config/consts/database-block.ts, packages/playground/src/data/index.ts, packages/store/src/workspace/page.ts, pnpm-lock.yaml
Upstream: #899 
- Support number type and option type
- Support edit column title
=> feat(blocks): improve database block

packages/playground/examples/virgo/test-page.ts, packages/virgo/src/components/base-text.ts, packages/virgo/src/index.ts, packages/virgo/src/utils/convert.ts, packages/virgo/src/utils/render.ts, packages/virgo/src/virgo.ts
TextEditor -> Virgo
RangeStatic -> VirgoRange
=> chore: rename Virgo entities

packages/blocks/src/components/blockhub.ts
Keep the same behaviour as that introduced in  #911
=> chore(blocks): hide hover tip after dragging

packages/blocks/src/page-block/default/selection-manager.ts, packages/store/src/workspace/page.ts
https://user-images.githubusercontent.com/20554850/215693082-7e4db235-2838-41b8-824f-d2b0160a0e21.mov
=> feat(blocks): autofocus new block inserted from block hub

packages/virgo/src/__tests__/input.spec.ts, packages/virgo/src/virgo.ts
=> feat(virgo): support readonly mode

packages/virgo/src/virgo.ts
=> feat(virgo): add unmount

packages/blocks/src/page-block/default/default-page-block.ts, packages/playground/src/data/index.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/text-adapter.ts, packages/store/src/utils/utils.ts, packages/store/src/workspace/page.ts, tests/basic.spec.ts, tests/link.spec.ts
There're side effect when creating Text
=> refactor(store): remove `page` field in Text

.github/workflows/label-check.yml
=> ci: disallow blocked PR to merge

packages/blocks/src/components/drag-handle.ts, packages/blocks/src/page-block/default/utils.ts
=> fix: drag handle can not escape database block when moving mouse

.github/workflows/cancel.yml
https://api.github.com/repos/toeverything/blocksuite/actions/workflows
=> ci: cancel previous GitHub action in PR

packages/virgo/src/components/base-text.ts
=> fix(virgo): fix unexpected space

packages/blocks/src/components/drag-handle.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/default/utils.ts, tests/drag.spec.ts
=> fix: sync selected blocks to selection-manager when clicking draghandle

packages/blocks/src/__internal__/utils/selection.ts, tests/selection.spec.ts, tests/utils/actions/drag.ts, tests/utils/actions/misc.ts
1
https://user-images.githubusercontent.com/9910706/215287497-e56ab134-7011-4b63-a74d-e6823f2d5196.mp4
2
https://user-images.githubusercontent.com/9910706/215287581-eea12e6c-8b4f-4619-a970-2f226c8428bd.mp4
3
https://user-images.githubusercontent.com/9910706/215287702-eef57a05-2506-450e-aa62-ab3c5c60a195.mp4
1
https://user-images.githubusercontent.com/9910706/215287505-e6bba371-7372-4647-b1cf-cf0fc50edb57.mp4
2
https://user-images.githubusercontent.com/9910706/215287603-36d699bb-5817-4c7a-9634-421491d6be07.mp4
3
https://user-images.githubusercontent.com/9910706/215287713-43e96a9b-9e77-47b2-bbb4-05f6aa9a4d89.mp4
=> fix: handle native range on dragging out of frame

packages/blocks/src/page-block/utils/position.ts, tests/format-quick-bar.spec.ts, tests/paragraph.spec.ts
=> fix: format bar position at line edge

packages/playground/index.html
=> fix: should set overflow to hidden on body

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/global/src/utils/web.ts, tests/paragraph.spec.ts
Fix the following problem
- Keydown does not work on multiple lines
https://user-images.githubusercontent.com/18554747/216780319-6133707a-5902-4223-a7f7-0acad0d5c551.mov
- Unexpected behavior when pressing ArrowUp from empty lines to multiple lines
https://user-images.githubusercontent.com/18554747/216780398-49b6e90d-d89c-4aaa-ad8e-72e0d5fa3359.mov
- Weird behavior when selecting multiple lines and pressing ArrowUp (fixed partial)
=> refactor: keydown and keyup

packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/default/default-page-block.ts
Upstream: https://github.com/toeverything/blocksuite/pull/988
=> fix(blocks): frame selection rect

packages/blocks/src/page-block/default/utils.ts, tests/selection.spec.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1004
=> fix: click title when divider block on the first

packages/blocks/src/page-block/default/default-page-block.ts, tests/paragraph.spec.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1007
=> fix(blocks): press enter on title

packages/blocks/src/page-block/default/selection-manager.ts
=> fix: unable to select embed block #994

package.json, packages/blocks/package.json, packages/editor/package.json, packages/global/package.json, packages/phasor/package.json, packages/playground/package.json, packages/react/package.json, packages/store/package.json, packages/virgo/package.json
```sh
pnpm version prerelease -ws --no-git-tag-version --no-commit-hooks --no-workspaces-update --include-workspace-root
```
=> 0.4.0-alpha.2

tests/basic.spec.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1033
=> test: fix flaky on collaborative editing

packages/playground/vite.config.ts
fix https://github.com/toeverything/blocksuite/issues/1046
=> fix: local dev sourcemap issue

packages/blocks/src/paragraph-block/paragraph-block.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1059
=> fix(blocks): paragraph font weight on children

packages/blocks/src/__internal__/utils/selection.ts
https://user-images.githubusercontent.com/27926/217404784-f3d31c8a-85fc-430e-afea-2e83e0bcfe7d.mov
=> fix: unstable text selection in edgeless mode

packages/playground/src/components/debug-menu.ts
=> fix: edgeless-toolbar style

packages/blocks/src/__internal__/rich-text/shortcuts.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, tests/paragraph.spec.ts
Fix caret position when pressing key down at line edge 
https://user-images.githubusercontent.com/18554747/217185250-9f3760fc-8a29-4916-a7c3-3310df4f99ae.mov
=> fix: keydown at line edge

packages/blocks/src/components/format-quick-bar/index.ts
Fix https://github.com/toeverything/AFFiNE/issues/855
=> fix: abort format bar when popstate

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/page-block/default/default-page-block.ts, tests/selection.spec.ts
Fixes: https://github.com/toeverything/blocksuite/issues/976
Upstream: https://github.com/toeverything/blocksuite/pull/1064 https://github.com/toeverything/blocksuite/pull/1056
Co-authored-by: Innei <tukon479@gmail.com>
=> feat(blocks): support multi line indent

packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/global/src/config/consts.ts
Upstream https://github.com/toeverything/blocksuite/pull/1075
=> refactor: move native tab to hotkey

packages/editor/src/components/editor-container.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1079
=> fix: try register code block service

packages/editor/src/managers/clipboard/content-parser/parse-html.ts
=> fix(editor): do not parse redundant divs in HtmlParser

packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/default/default-page-block.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1078
=> fix(blocks): correct rect positions

.github/CLA.md, packages/blocks/src/page-block/default/selection-manager.ts
=> feat: expose `setSelectedBlocks` with selection type detection

packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/code-block/code-block.ts, packages/blocks/src/code-block/code-service.ts, packages/blocks/src/code-block/components/syntax-code-block.ts, tests/code.spec.ts
=> fix: ensure change code block language can work

packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/default/default-page-block.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1094
=> fix: drag block selection area is mismatch when page scroll down

.github/workflows/label-check.yml, .github/workflows/pull-request-title-lint.yml
Comment: https://github.com/orgs/community/discussions/46757#discussioncomment-4918697
=> ci: fix merge group

packages/blocks/src/components/blockhub.ts
Provide ability to let the consumer of blockHub knows when it's expanded and ability to control whether to expand it
=> feat: exposing expanding signal and toggling expanding method for blockHub

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, tests/selection.spec.ts
=> feat: indent multi-block

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, tests/edgeless.spec.ts
=> fix: arrow up and down in edgeless page

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts
Refactor https://github.com/toeverything/blocksuite/pull/1122
/cc @Innei
=> refactor: arrow up and down in edgeless page

packages/blocks/src/__internal__/rich-text/link-node/create-link.ts, packages/blocks/src/__internal__/rich-text/link-node/index.ts, packages/blocks/src/components/format-quick-bar/format-bar-node.ts, packages/blocks/src/components/link-popover/index.ts, packages/blocks/src/index.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
Storybook will failed because of this
=> build: import ending with '.js'

packages/global/package.json
Refs: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
=> build(global): side effect

packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
Fixes: https://github.com/toeverything/AFFiNE/issues/926
=> fix: should use clientX/clientY to create startRange in edgeless mode

packages/blocks/src/page-block/edgeless/components.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/phasor/src/elements/debug/debug-element.ts, packages/phasor/src/elements/shape/shape-element.ts, packages/phasor/src/index.ts, packages/phasor/src/surface.ts, packages/phasor/src/utils/xywh.ts, tests/edgeless.spec.ts, tests/selection.spec.ts, tests/utils/actions/click.ts, tests/utils/actions/misc.ts
https://user-images.githubusercontent.com/21084335/217969591-20069250-b873-4088-b850-eddb48aa40e9.mov
=> feat(blocks): select and drag shape

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/components/slash-menu/index.ts, packages/blocks/src/page-block/default/utils.ts, packages/global/index.d.ts, packages/store/package.json, packages/store/src/base.ts, packages/store/src/text-adapter.ts, packages/store/src/utils/utils.ts, packages/store/src/workspace/page.ts, pnpm-lock.yaml
=> refactor(store): remove PrelimText

packages/blocks/src/page-block/default/selection-manager.ts, tests/code.spec.ts
=> fix: unable to close popup widget on code block

packages/blocks/src/components/slash-menu/index.ts, packages/blocks/src/components/slash-menu/slash-menu-node.ts, packages/blocks/src/components/slash-menu/styles.ts
fix https://github.com/toeverything/AFFiNE/issues/956, https://github.com/toeverything/AFFiNE/issues/957
=> fix: update slash menu styles

packages/blocks/src/page-block/edgeless/toolbar.ts
=> fix: uppercase in words

packages/blocks/src/components/slash-menu/config.ts, packages/blocks/src/components/slash-menu/slash-menu-node.ts, packages/blocks/src/components/slash-menu/styles.ts, tests/slash-menu.spec.ts
fix https://github.com/toeverything/AFFiNE/issues/957
=> chore: update slash menu

packages/blocks/src/components/slash-menu/slash-menu-node.ts, tests/slash-menu.spec.ts
=> feat: press `Tab` to move up/down slash

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/rich-text/markdown-convert.ts, packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/editor/src/managers/clipboard/paste-manager.ts, packages/store/src/text-adapter.ts, tests/clipboard.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/1115, fix https://github.com/toeverything/blocksuite/issues/1198
=> chore: throw error when text operation out of bounds

packages/playground/src/components/example-list.ts, packages/playground/src/main.ts
- Allow back to example list
- Fix flashed example list
=> chore: update playground

packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager.ts, tests/selection.spec.ts
https://user-images.githubusercontent.com/27926/218980543-e41c24fe-bb5e-40eb-b40f-4722f220af34.mp4
=> fix: keep native range selection when scrolling with scroll wheel

.github/workflows/add-to-project.yml
Closes #1182 
See https://github.com/marketplace/actions/add-to-github-projects
=> ci: add to project setup

packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/default/default-page-block.ts
Fixes https://github.com/toeverything/blocksuite/issues/1213
=> fix: hide editing popup in readonly mode

packages/blocks/src/__internal__/utils/filesys.ts, packages/blocks/src/__internal__/utils/index.ts, packages/blocks/src/components/blockhub.ts, packages/blocks/src/index.ts, packages/editor/src/index.ts, packages/editor/src/utils/editor.ts, packages/editor/src/utils/index.ts, packages/global/src/config/consts/blockhub.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/workspace/page.ts
This PR:
- added image support for blockHub
- exposed `async uploadImageFromLocal(editor: EditorContainer)` util for image uploading from local file system 
close https://github.com/toeverything/blocksuite/issues/1186.
=> feat: support image upload from local file system

packages/blocks/src/components/format-quick-bar/format-bar-node.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/page-block/utils/const.ts, packages/virgo/src/components/base-text.ts, packages/virgo/src/types.ts, packages/virgo/src/utils/render.ts, packages/virgo/src/virgo.ts, tests/format-quick-bar.spec.ts
- upstream https://github.com/toeverything/blocksuite/pull/1199
- tweak `TextAttributes`
=> chore: tweak format bar action status

packages/blocks/src/components/slash-menu/config.ts, packages/editor/src/utils/editor.ts, packages/store/src/workspace/page.ts, tests/slash-menu.spec.ts
Upstream https://github.com/toeverything/blocksuite/pull/1188
=> feat: support image in slash menu

packages/react/README.md
=> docs: update package import

packages/phasor/src/renderer.ts
=> fix(phasor): dpr offset

packages/blocks/src/components/format-quick-bar/format-bar-node.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/page-block/utils/container-operations.ts, packages/playground/examples/virgo/test-page.ts, packages/store/src/text-adapter.ts, packages/virgo/src/components/base-text.ts
Fix https://github.com/toeverything/blocksuite/issues/1236
=> fix: incorrect `mergeCodeBlocks` text operation

packages/blocks/src/components/slash-menu/slash-menu-node.ts, packages/blocks/src/components/slash-menu/styles.ts, packages/editor/src/components/editor-container.ts
Fix https://github.com/toeverything/AFFiNE/issues/1055
=> chore: update slash menu style

packages/blocks/src/__internal__/rich-text/rich-text.ts
=> fix: revert cursor flag

packages/blocks/src/components/format-quick-bar/format-bar-node.ts, tests/format-quick-bar.spec.ts
Fix #1197 
See https://github.com/toeverything/blocksuite/pull/1199#issuecomment-1432480274
=> fix: update format bar action status when node mution

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/slash-menu/index.ts, tests/knwon_issues.spec.ts, tests/slash-menu.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/1126
=> fix: clean slash menu after soft enter

.github/CLA.md, packages/react/src/store/index.tsx, packages/virgo/src/virgo.ts
The default value should remain the same type as the actual value
=> fix: update the default value of `@blocksuite/react`

packages/virgo/src/tests/virgo.spec.ts, packages/virgo/src/virgo.ts
=> fix(virgo): select from the start of line using shift+arrow

packages/blocks/src/__internal__/rich-text/keyboard.ts
Fix https://github.com/toeverything/blocksuite/issues/1264
=> fix: slash with shift key

packages/store/src/workspace/page.ts
Fixes: https://github.com/toeverything/AFFiNE/issues/1104
=> fix: `page.root` broken

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/index.ts, packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts
=> fix: edgeless selection rect doesn't follow viewport update

packages/blocks/src/__internal__/rich-text/link-node/link-node.ts
=> fix: link icon should not wrap

packages/blocks/src/page-block/edgeless/components.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
=> feat: support hover state on shape elements

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/phasor/src/renderer.ts, packages/phasor/src/surface.ts
Fixes #1220 
Fixes #874 
https://user-images.githubusercontent.com/21084335/220062787-a8816ba9-3213-4168-b877-b9e9f8d8a154.mov
=> fix(phasor): adapt to resized canvas

packages/playground/package.json, packages/playground/src/components/start-panel.ts, packages/playground/src/main.ts, packages/playground/src/utils.ts, pnpm-lock.yaml
https://user-images.githubusercontent.com/14026360/220202050-2546158b-97bc-433f-9423-5daca6a5bdc7.mp4
=> feat(playground): support debug ydoc file

README.md
=> feat: add stackblitz badge

.eslintrc.cjs, .github/workflows/nightly-release.yml, .github/workflows/release.yml, .npmrc, package.json, scripts/publish.sh, scripts/release.sh, scripts/replace-nightly-version.sh
This PR:
* Switch to manual per-package publish due to https://github.com/pnpm/pnpm/issues/4937
* Add `ALL_PACKAGES` literal for finding out where to update when adding new package
=> ci: switch to per-package release script

package.json, scripts/clean.sh, scripts/publish.sh
This removes an ad-hoc place for adding new package.
=> chore: switch to `ALL_PACKAGES` based clean

package.json, packages/playground/package.json, packages/playground/scripts/hmr-plugin/fine-tune.ts, pnpm-lock.yaml
fix https://github.com/toeverything/blocksuite/issues/1328
=> fix: fineTuneHmr sourcemap

tests/edgeless.spec.ts, tests/utils/actions/misc.ts
=> test: support hover state for shape element

packages/blocks/src/page-block/utils/container-operations.ts, packages/blocks/src/paragraph-block/paragraph-service.ts
=> fix(blocks): move h1-h6 paragraph children into parent

packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/utils/container-operations.ts, tests/format-quick-bar.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/1183
=> fix: format bar should follow selection block

packages/virgo/src/virgo.ts
In this PR:
- Fix some typos.
- Extract repeated logic into `getTextAndOffset`.
=> refactor: optimize some code in virgo

packages/blocks/src/__internal__/rich-text/rich-text.ts, tests/markdown.spec.ts, tests/utils/actions/keyboard.ts
=> fix: inline code break when pressing Enter followed by Backspace twice

packages/blocks/src/__internal__/utils/selection.ts
Fix https://github.com/toeverything/blocksuite/issues/1364
=> fix: update selection state

packages/blocks/src/page-block/default/default-page-block.ts
=> fix: composing enter at title should not wrap

packages/blocks/src/page-block/default/selection-manager.ts
Ref: [Node.compareDocumentPosition()](https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition)
Example:
```
?init=AAC3AZm9wsgW5Kejtw0A2b3CyBYGpKejtw3ZvcLIFgakp6O3Ddm9wsgWBqSno7cN2b3CyBYGpKejtw3ZvcLIFgakp6O3Ddm9wsgWkgGkp6O3Ddm9wsgWAOSno7cNANm9wsgWEqTkyscR2b3CyBYBpOTKxxGZvcLIFuTkyscRAZm9wsgW5OTKxxEBmb3CyBbk5MrHEQGZvcLIFuTkyscRAZm9wsgW5OTKxxEBmb3CyBak5MrHEeSno7cNIdoBjgHOARQBA0QOCAEDRA4IAQNEDggBA0QOCAEDRA4IAQNMFggBA0QOCAEDRA4IAQNMFggBA1YgCAEDCggBAwoIAQMKCAEDCggBAwoIAQMKCAEDCggBAwoIAQMKCAED5gKwAuIFCKYFAQEISADeBZoFGAEDQu4FhAYBAk4YThIMAQJOzga4BTTsBgCSBggMGBYBAmw2ajAUAQJYIlzuAuIC%2BAKKA8wDBgywA%2FIDCgiyA%2FQDBgi4A%2FoDBgi%2BA8AEBgiEBMAEzAECAQAIAQYUAQMOAQAIAQFMEgIQEwIGjAEBA1hkhQWhAAAAIQAAAEEAoQAnACgBIQAoACcAKADIAAEAJwAoAScAKAAnACgAyAAEACcAKAEnACgAJwAoAMgABAAnACgBJwAoACcAKADIAA …
```
=> refactor: detect elements with Node.compareDocumentPosition in block selection

packages/editor/src/components/editor-container.ts
=> fix: remove redundant scrollbars

packages/blocks/src/__internal__/utils/block-range.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/default/utils.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts
* add `refreshSelectedBlocksRectsByModels`
* change `filterSelectedBlockByIndex`
* add `filterSelectedBlockByIndexAndBound`
=> chore: improve selection manager

.github/CLA.md
=> docs: sign CLA

packages/blocks/src/__internal__/utils/check-line.ts, packages/store/src/store.ts, tests/format-quick-bar.spec.ts
Fix https://github.com/toeverything/AFFiNE/issues/874
=> chore: enable selection format bar by default

packages/blocks/src/components/drag-handle.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/default/utils.ts, tests/drag.spec.ts, tests/selection.spec.ts
=> fix: unfocus rich-text on starting block selection

packages/blocks/src/__internal__/service/index.ts, packages/blocks/src/models.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1398
=> fix(blocks,react,next-example): next.js cannot read window during SSR

.github/workflows/build-and-test.yaml, .github/workflows/release.yml, packages/blocks/src/page-block/edgeless/components.ts, packages/playground/src/components/debug-menu.ts, tests/edgeless.spec.ts, tests/utils/actions/click.ts, tests/utils/actions/edgeless.ts, tests/utils/actions/index.ts
Note that hover rect was supported in #1333, here fixes the regression.
=> fix(edgeless): enable shape hover rect & add test actions

packages/virgo/src/virgo.ts, playwright.config.ts, tests/basic.spec.ts, tests/blockhub.spec.ts, tests/code.spec.ts, tests/edgeless.spec.ts, tests/paragraph.spec.ts, tests/utils/actions/misc.ts
- update virgo
- reduce playwright worker number
=> test: improve test stability

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/blocks/src/page-block/utils/container-operations.ts, packages/store/src/text-adapter.ts, tests/hotkey.spec.ts, tests/selection.spec.ts, tests/utils/actions/misc.ts
=> feat: pressing enter with multiple blocks should create block

packages/blocks/src/page-block/default/default-page-block.ts
=> fix(blocks): prevent propagation when pressing Enter in title

packages/blocks/src/code-block/code-block.ts
=> feat: update code block style

packages/store/src/workspace/migrations.ts
Fixes https://github.com/toeverything/AFFiNE/issues/1240
=> fix: missing title migration on multipe pages

packages/blocks/src/__internal__/utils/hotkey.ts, packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/pan-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, tests/edgeless.spec.ts, tests/utils/actions/edgeless.ts
https://user-images.githubusercontent.com/21084335/222356822-fc983d3b-73a1-48da-bfec-5994c71425e5.mov
=> feat(edgeless): pan tool

packages/blocks/src/__internal__/rich-text/link-node/create-link.ts, packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/editor/src/managers/clipboard/paste-manager.ts, packages/global/src/utils.ts
Fix https://github.com/toeverything/AFFiNE/issues/1262
=> fix: unsafe type cast in getStartModelBySelection

packages/blocks/src/page-block/default/default-page-block.ts
Fix https://github.com/toeverything/AFFiNE/issues/1272
=> fix: title with ime

packages/playground/src/components/debug-menu.ts, tests/utils/actions/misc.ts
https://user-images.githubusercontent.com/21084335/222624960-c7865cc6-91d0-45e7-863f-1c531bd35f7e.mov
=> fix(playground): edgeless blank

packages/blocks/src/__internal__/utils/block-range.ts, packages/blocks/src/components/format-quick-bar/format-bar-node.ts, packages/blocks/src/components/format-quick-bar/index.ts, packages/blocks/src/page-block/default/selection-manager.ts, packages/blocks/src/page-block/utils/container-operations.ts, tests/embed.spec.ts
format bar can not handle image block
=> fix: skip image block when show format bar

packages/blocks/src/__internal__/utils/hotkey.ts, packages/blocks/src/page-block/default/default-page-block.ts, tests/paragraph.spec.ts
Fixes https://github.com/toeverything/AFFiNE/issues/1271
Fixes https://github.com/toeverything/AFFiNE/issues/1273
=> fix: filter hotkey on title

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/global/src/utils.ts, tests/utils/actions/misc.ts
Upstream https://github.com/toeverything/blocksuite/pull/1451 https://github.com/toeverything/blocksuite/pull/1457 https://github.com/toeverything/blocksuite/pull/1464 https://github.com/toeverything/blocksuite/pull/1466 https://github.com/toeverything/blocksuite/pull/1475 https://github.com/toeverything/blocksuite/pull/1476
=> fix: should throw error when page error

packages/blocks/src/__internal__/utils/components.ts, packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/code-block/code-block.ts, packages/blocks/src/code-block/components/lang-list.ts, packages/blocks/src/components/button.ts, packages/blocks/src/database-block/database-block.ts, packages/blocks/src/divider-block/divider-block.ts, packages/blocks/src/embed-block/image/image-block.ts, packages/blocks/src/frame-block/frame-block.ts, packages/blocks/src/list-block/list-block.ts, packages/blocks/src/paragraph-block/paragraph-block.ts
Fix https://github.com/toeverything/blocksuite/issues/1363
=> refactor: simplify code block language list logic

packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/default/selection-manager/embed-resize-manager.ts, packages/blocks/src/page-block/default/selection-manager/index.ts, packages/blocks/src/page-block/default/selection-manager/selection-state.ts, packages/blocks/src/page-block/default/selection-manager/utils.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/blocks/src/page-block/utils/container-operations.ts, packages/blocks/src/page-block/utils/position.ts
=> refactor: split basic `DefaultSelectionManager` modules

packages/blocks/src/__internal__/utils/block-range.ts, packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/default/selection-manager/selection-state.ts, packages/blocks/src/page-block/default/selection-manager/utils.ts, packages/blocks/src/page-block/edgeless/components.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/brush-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/index.ts, packages/blocks/src/page-block/edgeless/mode-controllers/pan-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts
part of #1480
* `SelectionRect` -> `DraggingArea`
* Optimize page block `components` typing
=> refactor: `SelectionRect` -> `DraggingArea`

packages/blocks/src/list-block/list-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
=> refactor: remove `resetSelectedBlockByRect`

packages/blocks/src/components/format-quick-bar/index.ts, packages/blocks/src/components/link-popover/create-link-popover.ts, packages/blocks/src/components/remote-selection/remote-selection.ts, packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/block-drag-handlers.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/default/selection-manager/selection-state.ts
=> refactor: switch to `selection.viewport`

packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/default/selection-manager/embed-resize-manager.ts, packages/blocks/src/page-block/default/selection-manager/native-drag-handlers.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/playground/src/components/debug-menu.ts
=> refactor: remove redundant selection manager fields

packages/blocks/src/__internal__/rich-text/link-node/link-node.ts, packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/embed-block/embed-block.ts, packages/blocks/src/embed-block/image/image-block.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/edgeless/components.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/editor/src/components/editor-container.ts, packages/store/src/workspace/page.ts, packages/virgo/src/tests/virgo.spec.ts, packages/virgo/src/virgo.ts
=> refactor: switch to `page.readonly`

packages/blocks/src/code-block/code-block.ts
=> fix: hide code block horizontal scrollbar

packages/blocks/src/page-block/default/utils.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1514
=> fix: download image

packages/blocks/src/components/link-popover/link-popover.ts, packages/blocks/src/components/link-popover/styles.ts
=> fix: tooltip not appeat due to overflow

packages/blocks/src/code-block/code-block.ts, packages/blocks/src/code-block/components/code-option.ts, packages/blocks/src/components/portal.ts, tests/code.spec.ts
- code option will follow page scroll
- the wrap option will active after click
=> fix: code option follow scroll

packages/blocks/src/code-block/code-block.ts, packages/blocks/src/components/block-hub.ts, packages/blocks/src/components/format-quick-bar/format-bar-node.ts, packages/blocks/src/components/slash-menu/slash-menu-node.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/editor/src/components/editor-container.ts, packages/global/src/utils/disposable.ts, packages/global/src/utils/slot.ts
=> feat(store): add `DisposableGroup.addFromEvent`

packages/store/src/__tests__/yjs.unit.spec.ts, packages/store/src/space.ts, packages/store/src/workspace/workspace.ts, packages/store/src/yjs/proxy.ts
This bug will cause AFFiNE pages lost when refresh tab
=> fix(store): lazy initialize yjs models

packages/virgo/src/virgo.ts
Close https://github.com/toeverything/AFFiNE/issues/1283
=> fix(virgo): support `deleteWordBackward` input type

packages/blocks/src/components/slash-menu/slash-menu-node.ts, tests/slash-menu.spec.ts
related to: https://github.com/toeverything/AFFiNE/issues/1387
=> feat: slash menu supports fuzzy query

packages/blocks/src/paragraph-block/paragraph-block.ts, tests/paragraph.spec.ts
=> fix(blocks): update placeholder precisely

packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/blocks/src/page-block/edgeless/view-control-bar.ts
=> fix(edgeless): redundant side effect on clicking edgeless toolbar

packages/blocks/src/database-block/database-block.ts, packages/blocks/src/database-block/register.ts, packages/blocks/src/divider-block/divider-block.ts, packages/blocks/src/embed-block/image/image-block.ts, packages/blocks/src/frame-block/frame-block.ts, packages/blocks/src/list-block/list-block.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/paragraph-block/paragraph-block.ts
=> perf: remove redundant `hasChanged`

packages/blocks/src/page-block/default/default-page-block.ts
=> fix(blocks): placeholder in title still displayed when using IME

README.md, packages/editor/src/components/simple-affine-editor.ts, packages/playground/src/main.ts, packages/playground/src/utils.ts, packages/react/README.md, packages/react/examples/next/src/components/WorkspacesDropdown.tsx, packages/react/examples/next/src/pages/index.tsx, packages/react/examples/next/src/pages/suspense.tsx, packages/react/src/store/index.tsx, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/persistence/doc/debug-provider.ts, packages/store/src/persistence/doc/idb-provider.ts, packages/store/src/persistence/doc/index.ts, packages/store/src/store.ts, packages/store/src/workspace/__tests__/test-entry.ts, packages/store/src/workspace/workspace.ts
Closes #1351
This PR replaces the optional field `workspace.room` with a required field `workspace.id`.
/cc @Himself65
=> feat: add `workspace.id`

packages/blocks/src/components/remote-selection/remote-selection.ts
=> fix(blocks): fix remote-selection offset

packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/paragraph-block/paragraph-block.ts
https://github.com/toeverything/blocksuite/pull/1482
Revert https://github.com/toeverything/blocksuite/pull/1556
=> fix: placeholder with IME

packages/blocks/src/code-block/code-block.ts
=> fix(blocks): line number in code-block not updated in time

packages/blocks/src/__internal__/rich-text/link-node/create-link.ts
=> fix(blocks): fix link mock selection offset

packages/blocks/src/page-block/utils/container-operations.ts, tests/format-quick-bar.spec.ts, tests/hotkey.spec.ts
=> fix(blocks): set attribute to be null when un-format

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/code-block/code-block.ts
- listen `wheel` cannot handle all scrolling cases
=> refactor: code option use viewport element

packages/blocks/src/__internal__/utils/common-operations.ts
=> fix(blocks): update paragraph type with new vRange

packages/blocks/src/components/slash-menu/slash-menu-node.ts
=> fix: invalid regex error of slash menu

packages/blocks/src/list-block/list-block.ts
=> feat: symbols at the same level is the same

packages/blocks/src/__internal__/rich-text/bracket-complete.ts, tests/code.spec.ts
=> fix(blocks): pointer lost when formatting with backticks

packages/blocks/src/paragraph-block/paragraph-block.ts
=> feat: remove redundant button word

packages/blocks/src/page-block/utils/container-operations.ts, packages/virgo/src/virgo.ts, tests/format-quick-bar.spec.ts
=> fix: format button should not be activated If only part of the text has styles

packages/blocks/src/components/drag-handle.ts
=> fix: long duration of drag handle transition

packages/phasor/src/elements/shape/shapes/rect.ts
=> fix(phasor): use consistent rounded rect radius

packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/code-block/code-block.ts, packages/virgo/src/virgo.ts, tests/selection.spec.ts
=> fix: fix selection sync error

packages/blocks/src/page-block/default/utils.ts
=> fix(blocks): click copy option in code block

packages/blocks/src/paragraph-block/paragraph-block.ts, tests/paragraph.spec.ts
=> fix(blocks): add placeholder for heading

packages/blocks/src/__internal__/rich-text/virgo/types.ts, packages/blocks/src/page-block/utils/container-operations.ts, packages/virgo/src/utils/base-attributes.ts, packages/virgo/src/virgo.ts, tests/format-quick-bar.spec.ts, tests/hotkey.spec.ts, tests/link.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/1571
=> fix: update the calculation method of format

packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/__internal__/utils/std.ts, packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/frame-resize-observer.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/index.ts, packages/blocks/src/page-block/edgeless/mode-controllers/text-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, tests/edgeless.spec.ts, tests/utils/actions/edgeless.ts, tests/utils/asserts.ts
https://user-images.githubusercontent.com/21084335/223681033-a44b8de6-4b24-4c4c-b0ea-7f9ce508c77b.mov
=> feat(edgeless): text tool

packages/blocks/src/page-block/edgeless/toolbar/brush-tool/color-panel.ts, tests/utils/actions/edgeless.ts
=> fix(edgeless): update brush color

packages/blocks/src/components/drag-handle.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, tests/drag.spec.ts
=> fix: hide drag handle when mouse hovering over title

packages/blocks/src/components/block-hub.ts
https://user-images.githubusercontent.com/27926/224001635-2967921a-e4f7-48ca-abd7-f0e32d8eaa4d.mov
=> fix: mouse hovering flickering on blockhub

packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/page-block/edgeless/components/block-children-container.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/pan-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/text-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, packages/blocks/src/page-block/edgeless/toolbar/shape-tool/shape-menu.ts, packages/blocks/src/page-block/edgeless/utils.ts, tests/edgeless.spec.ts, tests/selection.spec.ts, tests/utils/actions/edgeless.ts, tests/utils/actions/misc.ts
Closes https://github.com/toeverything/AFFiNE/issues/1416
Using mask cover non-active frame.
https://user-images.githubusercontent.com/21084335/224002446-ab6ee6aa-e2ac-4c98-ad5b-8668da852c1c.mov
=> fix(edgeless): cursor in different mouse mode

packages/virgo/src/virgo.ts
before:
https://user-images.githubusercontent.com/15389209/224062279-05d84022-d975-40db-ba91-665d9afedb32.mov
after:
https://user-images.githubusercontent.com/15389209/224062332-5d99fdc4-a793-4a8b-9ee4-9773bacf07da.mov
=> fix: cursor position on click in code block

packages/blocks/src/paragraph-block/paragraph-block.ts, tests/paragraph.spec.ts
- Update text block placeholder design
- Now heading placeholder will always show if no text
https://user-images.githubusercontent.com/18554747/223977782-e79123ca-7d6b-4856-a348-32c68bb4551d.mov
=> feat: support triggering block hub by placeholder

packages/blocks/src/code-block/code-block.ts
=> fix(blocks): workaround for cursor hidden

packages/blocks/src/components/drag-handle.ts, packages/store/src/workspace/page.ts
fix https://github.com/toeverything/blocksuite/issues/1620
=> fix(editor): should hide drag handle when target model props changed

packages/blocks/src/__internal__/rich-text/keyboard.ts
=> fix(blocks): fix keyboard handler when in edgeless mode

packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts, packages/global/src/config/icons.ts
Fix https://github.com/toeverything/blocksuite/issues/1631
=> fix: link not work in editableable content

packages/virgo/src/tests/virgo.spec.ts, packages/virgo/src/virgo.ts
=> fix(virgo): support `deleteContentForward` input type

packages/blocks/src/__internal__/rich-text/rich-text.ts
close: #1553
also related to:  https://github.com/toeverything/blocksuite/pull/1636#issuecomment-1463442683
=> fix: inconsistent input states between using and not using IME

packages/blocks/src/page-block/edgeless/mode-controllers/pan-mode.ts
=> fix: edgeless panning with zoom

packages/blocks/src/code-block/code-block.ts
Fix https://github.com/toeverything/blocksuite/issues/1617
=> fix: cursor hidden in code block empty line

packages/blocks/src/page-block/default/default-page-block.ts, packages/virgo/src/virgo.ts
=> fix(blocks): paste not work in title

packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts, packages/blocks/src/page-block/edgeless/components/resize-manager.ts, packages/blocks/src/page-block/edgeless/components/utils.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/frame-resize-observer.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/phasor/src/elements/brush/brush-element.ts, tests/edgeless.spec.ts, tests/utils/actions/edgeless.ts, tests/utils/asserts.ts
fixes #1592 #1650 
https://user-images.githubusercontent.com/21084335/224292927-bd2d62a4-404c-4371-bba5-6fd277e5a4ab.mov
=> fix(edgeless): selection resize

packages/blocks/src/code-block/affine-code-line.ts, packages/virgo/src/components/virgo-text.ts
https://user-images.githubusercontent.com/18554747/224322557-4829c80e-7a0c-4a71-b3e7-dbd46d905394.mov
=> fix: code block wrap not work

packages/virgo/src/virgo.ts, tests/hotkey.spec.ts
=> feat: title supports cutting to the clipboard

packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts
Fix https://github.com/toeverything/AFFiNE/issues/1540
=> fix: open two tabs in readonly

packages/blocks/src/__internal__/utils/block-range.ts, packages/blocks/src/__internal__/utils/selection.ts
part of https://github.com/toeverything/blocksuite/issues/1569
=> feat(selection): add `ExtendBlockRange` API

packages/virgo/package.json, packages/virgo/src/virgo.ts, pnpm-lock.yaml, tests/edgeless.spec.ts, tests/selection.spec.ts, tests/utils/actions/misc.ts
Closes: #1655
Auto scroll when focus is out of viewport.
https://user-images.githubusercontent.com/10047788/224636680-b9ddbd34-b288-4163-8c5c-8f509f433087.mov
=> fix(virgo): auto scroll to the focus text

packages/virgo/src/utils/attributes-renderer.ts, tests/slash-menu.spec.ts
=> fix(virgo): render error in title when first charaster is space

packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/__internal__/utils/std.ts, packages/virgo/src/virgo.ts
=> fix(virgo): arrow up and down will lose focus

packages/blocks/src/page-block/utils/container-operations.ts, packages/virgo/src/tests/editor.unit.spec.ts, packages/virgo/src/tests/virgo.spec.ts, packages/virgo/src/virgo.ts, tests/hotkey.spec.ts
=> feat(virgo): support marks

packages/blocks/src/components/block-hub.ts, tests/block-hub.spec.ts
If this behavior feels OK, add test later. 
https://user-images.githubusercontent.com/27926/225242810-a86a8713-0753-4a12-944b-0e76871ae2c6.mov
=> chore: auto hide card list when dragging a card

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
=> fix(edgeless): background linear-gradient -> radial-gradient

packages/virgo/src/virgo.ts
=> feat: support delete line backward

packages/blocks/src/code-block/code-block.ts
https://user-images.githubusercontent.com/18554747/225282857-b1ec842a-0219-4c0f-894f-d9ce83a57b4f.mov
=> fix: code option covered by header

packages/blocks/src/code-block/code-block.ts
=> fix(blocks): resize observer not work as expected

packages/blocks/src/__internal__/rich-text/virgo/types.ts, packages/virgo/src/tests/editor.unit.spec.ts, packages/virgo/src/utils/base-attributes.ts, packages/virgo/src/virgo.ts
Related to https://github.com/toeverything/blocksuite/pull/1646
=> refactor: strict text attributes check

packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts, packages/blocks/src/page-block/edgeless/utils.ts
Fix #1288 since this is a CSS issue
=> fix(edgeless): adjust frame min width

packages/blocks/src/components/slash-menu/config.ts, packages/blocks/src/components/slash-menu/index.ts, tests/hotkey.spec.ts, tests/slash-menu.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/1127 https://github.com/toeverything/blocksuite/issues/1184
=> feat(slash-menu): add ability to adjust block styles in slash menu

tests/paragraph.spec.ts, tests/selection.spec.ts, tests/slash-menu.spec.ts
=> test(blocks): fix flaky test

packages/blocks/src/database-block/components/cell-container.ts, packages/blocks/src/database-block/components/column-type/number.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/database-block/components/column-type/select.ts, packages/blocks/src/database-block/register.ts, packages/global/src/database.ts, packages/store/src/index.ts
=> feat: enhance type in database block

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/components/block-hub.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/default/utils.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/text-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/global/src/config/consts.ts, packages/store/src/workspace/page.ts, tests/edgeless.spec.ts, tests/utils/actions/drag.ts
Related to: #1704
https://user-images.githubusercontent.com/27926/226121102-f48a4a98-f4c4-4239-97ba-c764743255cd.mov
=> feat(drag-handle): support in edgeless mode

tests/edgeless.spec.ts
=> test(edgeless): flaky add empty Text test case

packages/blocks/src/__internal__/clipboard/page-clipboard.ts, packages/blocks/src/__internal__/service/components.ts, packages/blocks/src/database-block/database-block.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/paragraph-block/paragraph-block.ts, tests/database.spec.ts
=> feat(database): hide placeholder of paragraph in database

.github/workflows/test.yaml, packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts, packages/blocks/src/__internal__/clipboard/page-clipboard.ts, packages/blocks/src/__internal__/clipboard/type.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- ci: skip correct changes
- style: optimize naming
=> ci: skip correct files

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/editor/src/components/editor-container.ts
https://user-images.githubusercontent.com/27926/226408158-dec9f2c3-2690-4b38-aeab-a8e7161b674a.mov
https://user-images.githubusercontent.com/27926/226409445-60a4dbbe-22e0-40ca-8af6-0809ebf63060.mov
=> fix(drag-handle): improve indicator offset in edgeless mode

packages/blocks/src/page-block/edgeless/components/component-toolbar/change-brush-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
fix https://github.com/toeverything/AFFiNE/issues/1617
=> fix: button-text-color

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/blocks/src/page-block/edgeless/utils.ts, tests/edgeless.spec.ts
fix #1812 
https://user-images.githubusercontent.com/21084335/226877115-0a9dd59e-5f20-4b4f-9aaf-1030f155b5d8.mov
=> fix(edgeless): drag handle should only appear in actived frame block

packages/blocks/src/code-block/code-block.ts
=> fix: lang-button without line break

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/utils/gesture.ts, packages/blocks/src/__internal__/utils/shortcut.ts, packages/blocks/src/__internal__/utils/std.ts, packages/blocks/src/page-block/edgeless/utils.ts
=> fix(edgeless): pinch event compatible

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/block-hub.ts, packages/blocks/src/page-block/edgeless/components/block-children-container.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/text-mode.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/blocks/src/page-block/utils/container-operations.ts, packages/editor/src/components/editor-container.ts, packages/editor/src/utils/editor.ts, tests/edgeless.spec.ts
=> feat(block-hub): support in edgeless mode

packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/__internal__/utils/virgo.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/database-block/database-block.ts, packages/virgo/src/virgo.ts, tests/utils/actions/misc.ts
related to https://github.com/toeverything/blocksuite/pull/1829#pullrequestreview-1353820943
=> refactor(blocks): prevent auto scroll in edgeless mode

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, tests/edgeless.spec.ts, tests/utils/actions/keyboard.ts
fix #1814 
https://user-images.githubusercontent.com/21084335/227150069-07c447c6-3d02-4080-aab5-b958c1553424.mov
=> feat(edgeless): pressing the ESC key will return to the default state

packages/blocks/src/page-block/edgeless/components/block-children-container.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, tests/edgeless.spec.ts, tests/utils/asserts.ts
fix #1809 
https://user-images.githubusercontent.com/21084335/227196715-5671a761-56f7-487c-83d0-51e1f78de4e5.mov
=> feat(edgeless): keep active state between clicking frames

packages/blocks/src/components/block-hub.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/components/format-quick-bar/button.ts, packages/blocks/src/components/format-quick-bar/styles.ts, packages/blocks/src/components/link-popover/styles.ts, packages/blocks/src/components/slash-menu/styles.ts, packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts, packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts
=> fix: do not allow text in button to be selected

packages/blocks/src/__internal__/utils/gesture.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, tests/drag.spec.ts, tests/embed.spec.ts, tests/selection.spec.ts, tests/utils/actions/misc.ts
https://user-images.githubusercontent.com/27926/227482051-af614b89-e0f4-410b-b679-dcd6bfa30043.mov
=> fix(embed): don't show image option menu on selecting

packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts, packages/virgo/src/virgo.ts
=> chore(virgo): add comments about render refactor

packages/docs/editor-example.md
Fixes: https://github.com/toeverything/blocksuite/issues/1858
=> fix(docs): multiple editors in doc

packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts, packages/blocks/src/__internal__/utils/block-range.ts, packages/blocks/src/__internal__/utils/query.ts, packages/store/src/text-adapter.ts, tests/paragraph.spec.ts, tests/quote.spec.ts, tests/selection.spec.ts, tests/slash-menu.spec.ts
- Fix https://github.com/toeverything/blocksuite/pull/1286
- Sunseting Text.meta
- Disable `getVirgoByModel` in database model
- Use `test.info().annotations`
=> chore: clean misc code

packages/blocks/src/__internal__/service/json2block.ts, tests/clipboard.spec.ts
=> fix: paste into list error

packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/__internal__/utils/virgo.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/database-block/database-block.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/editor/src/components/editor-container.ts, packages/playground/src/main.ts, packages/virgo/src/virgo.ts, tests/basic.spec.ts, tests/paragraph.spec.ts, tests/utils/actions/misc.ts
=> chore: add property to config editor focus

packages/blocks/src/database-block/database-block.ts
=> fix(database): hide text that exceeds column width

packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts, packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/blocks/src/__internal__/utils/virgo.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/database-block/database-block.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/virgo/src/virgo.ts, tests/hotkey.spec.ts, tests/list.spec.ts, tests/markdown.spec.ts
fix blur problem in virgo editor
=> fix(virgo): remove autofocus

packages/blocks/src/__internal__/rich-text/rich-text.ts
=> fix(virgo): unexpected cursor position when inputting Chinese in mobild phone

packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
=> fix(blocks): remote selection should be updated when switch to default mode from edgeless mode

packages/blocks/src/components/block-hub.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/embed-block/image/image-block.ts, tests/drag.spec.ts, tests/utils/actions/drag.ts
Related to #1888.
https://user-images.githubusercontent.com/27926/227682252-a32aca3f-c8f5-4a9f-9900-8f9e2a1ecee1.mov
https://user-images.githubusercontent.com/27926/227955146-b3a739fd-7ffe-45c4-8820-6753c7cea496.mov
=> feat(selection): support dragged content preview

packages/blocks/src/__internal__/rich-text/link-node/create-link.ts, tests/link.spec.ts, tests/utils/actions/misc.ts
=> fix(blocks): prevent link bar appeared when range is collapsed

.github/workflows/test.yaml, packages/global/src/utils.ts, packages/playground/examples/virgo/test-page.ts, packages/store/src/persistence/blob/__tests__/blob.spec.ts, packages/virgo/package.json, packages/virgo/playwright.config.ts, packages/virgo/src/components/virgo-text.ts, packages/virgo/src/services/range.ts, packages/virgo/src/tests/utils/misc.ts, packages/virgo/src/utils/attributes-renderer.ts, packages/virgo/src/utils/to-virgo-range.ts, packages/virgo/src/virgo.ts, pnpm-lock.yaml, tests/utils/actions/misc.ts
1. Add range service
2. Refactor `toVRange` function to small pieces
3. Enable virgo unit test and e2e test to ci
4. Fix e2e error for virgo
=> refactor(virgo): code optimization

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
=> refactor: split `handleLineStartBackspace`

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/store/src/workspace/page.ts, tests/list.spec.ts
=> fix: indent correctly when deleting list item

packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/utils/container-operations.ts, tests/edgeless.spec.ts
=> fix(selection): select text by double-clicking in edgeless mode

packages/virgo/src/virgo.ts
https://user-images.githubusercontent.com/15389209/229332400-5f6b6a33-ac54-46be-aa81-69be11d6e1a7.mov
=> feat: unobserve when vEditor unmount

packages/blocks/src/database-block/components/cell-container.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/database-block/components/column-type/select.ts, packages/blocks/src/database-block/components/edit-column-popup.ts, packages/blocks/src/database-block/database-block.ts, packages/blocks/src/database-block/database-service.ts, packages/playground/src/data/index.ts, packages/store/src/workspace/database.ts, packages/store/src/workspace/page.ts
Moving `page.updateColumn` -> `page.db.updateColumn`, this helps managing all the database-specific methods.
/cc @zqran @Himself65
=> refactor(database): add `DatabaseManager` and `page.db` entity

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/workspace/page.ts
Also `addBlocksByFlavour` -> `addBlocks` for better consistency
=> refactor(store): remove `deleteBlockById` and `updateBlockById`

packages/blocks/src/components/slash-menu/config.ts, packages/blocks/src/divider-block/divider-block.ts
=> fix: add paragraph when insert divider

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/block-hub.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/database-block/components/cell-container.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/page-block/default/utils.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/editor/src/utils/editor.ts, packages/store/src/base.ts, packages/store/src/workspace/page.ts
https://user-images.githubusercontent.com/27926/226604094-2ce7d9f6-eebb-45be-b0b7-d49d59211604.mov
=> feat(database, selection): improve DnD for database block

packages/blocks/src/components/slash-menu/config.ts, packages/blocks/src/page-block/utils/container-operations.ts, packages/global/src/config/consts/block-hub.ts, tests/hotkey.spec.ts
=> feat(blocks): add shortcuts support for adding a divider

packages/blocks/src/page-block/edgeless/mode-controllers/brush-mode.ts, tests/edgeless.spec.ts
=> fix(edgeless): brush offset when drawing

packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts, packages/phasor/src/grid.ts, packages/phasor/src/surface.ts, tests/edgeless.spec.ts, tests/utils/actions/edgeless.ts
https://user-images.githubusercontent.com/21084335/229749829-b92ea63b-0998-4eed-b96b-6e524ae62447.mov
=> feat(edgeless): support bringToFront and sendToBack

packages/blocks/src/database-block/components/edit-column-popup.ts, tests/database.spec.ts, tests/utils/actions/database.ts
fix: #1949
related to: #1919, #1950 /cc @Flrande 
---
part of: #629
=> fix(database): remove property from columns data structure

packages/store/src/store.ts
=> refactor(store): set doc.guid to workspace id

packages/blocks/src/__internal__/rich-text/reference-node.ts, packages/editor/src/components/editor-container.ts, packages/global/src/config/icons.ts, packages/playground/src/components/debug-menu.ts, tests/linkedpage.spec.ts, tests/utils/actions/misc.ts
=> test: add tests for linked page

packages/blocks/src/__internal__/service/index.ts
Fixes: https://github.com/toeverything/blocksuite/issues/1968
=> fix(blocks): copy behavior

packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts, packages/blocks/src/page-block/edgeless/components/single-connector-handles.ts, packages/blocks/src/page-block/edgeless/mode-controllers/connector-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/blocks/src/page-block/edgeless/utils.unit.spec.ts, packages/connector/src/rectangle.ts, packages/phasor/src/elements/connector/types.ts, packages/phasor/src/index.ts, tests/edgeless.spec.ts
https://user-images.githubusercontent.com/21084335/230367434-68a943d6-6e2e-45c1-b457-44db25d20e51.mov
=> feat(edgeless): connectors can be attached to elements at any position

packages/blocks/src/__internal__/utils/gesture.ts, packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/embed-block/image/image-block.ts, packages/blocks/src/list-block/utils/get-list-icon.ts, packages/blocks/src/page-block/default/components.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, packages/blocks/src/page-block/default/selection-manager/index.ts, packages/blocks/src/page-block/default/selection-manager/selected-rects.ts, packages/blocks/src/page-block/default/selection-manager/selection-state.ts, packages/blocks/src/page-block/default/selection-manager/utils.ts, packages/blocks/src/page-block/default/utils.ts, packages/blocks/src/page-block/edgeless/create-drag-handle.ts, packages/blocks/src/page-block/index.ts, packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/editor/src/components/editor-container.ts, packages/global/src/config/consts.ts, tests/code.spec.ts, tests/drag.spec.ts, tests/embed.spec.ts, tests/format-quick-bar.spec.ts, tests/selection.spec.ts, tests/utils/actions/misc.ts
Related to: #1888
https://user-images.githubusercontent.com/27926/230043752-e9085930-bab7-4e0b-9a46-5c437baadb81.mov
=> feat(selection): support dragging blocks under block-level selection

packages/blocks/src/__internal__/utils/std.ts, packages/blocks/src/components/linked-page/linked-page-popover.ts, packages/blocks/src/components/linked-page/styles.ts, packages/blocks/src/components/slash-menu/slash-menu-node.ts
=> feat: query and filter linked items

packages/playground/index.html
Add a temporary dark mode solution for playground.
=> feat(playground): add dark mode for playground

packages/blocks/src/components/drag-handle.ts
https://user-images.githubusercontent.com/27926/230583914-49ba4ebd-5580-4077-ae0a-d0dff2db1662.mov
=> fix(selection): dragging blocks scale in edgeless mode

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/format-quick-bar/index.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
https://user-images.githubusercontent.com/27926/230602430-b2e54bb4-96ce-4ca9-b79a-6dd7bd9a4f17.mov
=> fix: throw error when switching mode under block-level selection

packages/blocks/src/page-block/edgeless/create-drag-handle.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/text-mode.ts, packages/editor/src/utils/editor.ts
https://user-images.githubusercontent.com/27926/230705665-7d31c00d-7920-4b73-9dc5-0e8b1c9bbc7c.mov
=> fix: position of creating frame when using block-hub

packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts, packages/blocks/src/__internal__/rich-text/reference-node.ts, packages/blocks/src/__internal__/rich-text/virgo/affine-text.ts, packages/blocks/src/code-block/code-block.ts
=> fix(blocks): `pre-wrap` -> `break-spaces`

packages/blocks/src/database-block/components/row-container.ts, packages/blocks/src/database-block/components/toolbar/toolbar-action-popup.ts, packages/blocks/src/database-block/components/toolbar/toolbar.ts, packages/blocks/src/database-block/database-block.ts, packages/blocks/src/database-block/types.ts
=> refactor(database): toolbar and row container

tests/database.spec.ts, tests/utils/actions/database.ts, tests/utils/actions/misc.ts
=> test: improve and fix flaky

packages/blocks/src/components/drag-handle.ts, tests/drag.spec.ts
https://user-images.githubusercontent.com/27926/230720416-8c1908bc-b54b-48b2-9b57-2f3dfce437b7.mov
=> fix(drag-handle): selected block cant be reached

packages/blocks/src/database-block/components/database-title.ts, packages/blocks/src/database-block/database-block.ts
=> refactor(database): separate title

packages/blocks/src/database-block/database-block.ts, tests/database.spec.ts
=> feat(database): column names support incrementing by index

packages/blocks/src/code-block/components/lang-list.ts
=> feat: add up and down keys to select language in code block

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/rich-text/reference-node.ts, packages/blocks/src/__internal__/rich-text/virgo/affine-text.ts, packages/blocks/src/components/linked-page/linked-page-popover.ts, packages/blocks/src/components/slash-menu/slash-menu-node.ts, tests/linked-page.spec.ts
part of https://github.com/toeverything/AFFiNE/issues/1332
=> test: add additional testing for linked page

tests/database.spec.ts, tests/utils/actions/database.ts, tests/utils/asserts.ts
=> test(database): optimize cell text asserters

packages/blocks/src/database-block/components/toolbar/toolbar.ts
=> fix(database): missing import custom lit component path

packages/blocks/src/__internal__/utils/std.ts, packages/blocks/src/__internal__/utils/std.unit.spec.ts, packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/frame-block/frame-model.ts, packages/blocks/src/page-block/edgeless/components/block-children-container.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-frame-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts, packages/blocks/src/page-block/edgeless/hotkey.ts, packages/blocks/src/page-block/edgeless/toolbar/brush-tool/color-panel.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, tests/block-hub.spec.ts, tests/clipboard.spec.ts, tests/code.spec.ts, tests/drag.spec.ts, tests/edgeless.spec.ts, tests/format-quick-bar.spec.ts, tests/hotkey.spec.ts, tests/link.spec.ts, tests/linked-page.spec.ts, tests/list.spec.ts, tests/paragraph.spec.ts, tests/selection.spec.ts, tests/slash-menu.spec.ts, tests/utils/actions/edgeless.ts, tests/utils/asserts.ts
https://user-images.githubusercontent.com/21084335/231183748-6b969189-d311-458a-8069-260f0f09aa05.mov
=> feat(edgeless): edgeless frame background

packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/page-block/edgeless/components/color-panel.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-brush-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-frame-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts, packages/blocks/src/page-block/edgeless/hotkey.ts, packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts, packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-menu.ts, packages/blocks/src/page-block/edgeless/toolbar/connector-tool/connector-menu.ts, packages/blocks/src/page-block/edgeless/toolbar/shape-tool/shape-tool-button.ts, tests/edgeless.spec.ts, tests/utils/actions/edgeless.ts
https://user-images.githubusercontent.com/21084335/231437842-655afb5d-3fba-4356-ad34-70d09af55f27.mov
=> feat(edgeless): support shape fill and stroke color

packages/blocks/src/database-block/components/column-header/column-move/column-drag-preview.ts, packages/blocks/src/database-block/components/column-header/column-move/index.ts, packages/blocks/src/database-block/components/toolbar/index.ts, packages/blocks/src/database-block/components/toolbar/toolbar.ts, packages/blocks/src/database-block/database-block.ts, tests/database.spec.ts, tests/utils/actions/database.ts
https://user-images.githubusercontent.com/15389209/231501437-e65ef057-11d9-4e44-bbe8-120f49ba39ec.mov
---
part of: #629
=> feat(database): support drag and drop the add button to insert row

packages/blocks/src/page-block/utils/const.ts, packages/global/src/config/consts.ts, packages/global/src/config/consts/block-hub.ts, packages/global/src/config/consts/short-key.ts
=> feat: selective cmd or ctrl

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/utils/gesture.ts, packages/blocks/src/__internal__/utils/std.ts, packages/global/src/config/consts.ts, packages/global/src/config/consts/block-hub.ts, packages/global/src/config/consts/platform.ts, packages/global/src/config/consts/short-key.ts
Related to https://github.com/toeverything/blocksuite/pull/2045
=> refactor: clean short key

packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/workspace/page.ts
=> fix: do not assumed that the page block must appear before the surface block in ymap

packages/blocks/src/components/link-popover/link-popover.ts, packages/blocks/src/components/linked-page/linked-page-popover.ts, packages/blocks/src/components/slash-menu/slash-menu-popover.ts, packages/blocks/src/components/utils.ts
Also related to https://github.com/toeverything/blocksuite/issues/2052
=> refactor: extract keydown observer

packages/blocks/src/page-block/edgeless/selection-manager.ts, tests/edgeless.spec.ts
=> fix: hide hover rect on active frame

packages/blocks/src/database-block/components/toolbar/toolbar.ts
https://user-images.githubusercontent.com/48149577/231768109-41f0934e-62b7-4cb1-bb57-9b14e814bf23.mov
=> fix: avoid clicking on the icon to close

packages/blocks/src/code-block/code-service.ts
=> fix: retain line break for pasting into code block

packages/blocks/src/page-block/edgeless/components/block-children-container.ts
before:
https://user-images.githubusercontent.com/21084335/231927906-74d3f2bd-2de1-4996-b3ff-d6d83056a4fc.mov
after:
https://user-images.githubusercontent.com/21084335/231927634-6073f0d4-34d1-4536-aaf2-35a4e487ff74.mov
=> fix(edgeless): add text frame mask z-index

.github/CLA.md
=> docs: update CLA

packages/blocks/src/components/slash-menu/config.ts, packages/blocks/src/components/slash-menu/slash-menu-popover.ts, tests/slash-menu.spec.ts
=> feat: slash menu supports alias search

tests/database.spec.ts, tests/utils/actions/database.ts
related to: #2078
---
part of: #629
=> test(database): add tests for search input display

packages/blocks/src/components/drag-handle.ts
https://user-images.githubusercontent.com/27926/232210584-3f3ef56a-a39b-49fa-8aa0-75b74fd52f7d.mov
https://user-images.githubusercontent.com/27926/232210625-13e1c619-278a-44bd-8182-a4d46b3d442f.mov
=> fix(selection): improve position of indicator in nested list

packages/docs/.vitepress/theme/style.css
fix: 
https://user-images.githubusercontent.com/15389209/232272024-8e5181d9-1c10-45dc-9a15-07bfe90d82b6.mov
=> docs: update dark mode priority

packages/blocks/src/components/slash-menu/slash-menu-popover.ts
=> fix: enabel database flag

packages/blocks/src/database-block/components/column-type/select/select-cell-editing.ts
before:
https://user-images.githubusercontent.com/15389209/232371906-fec3f5c6-e88c-4987-a770-a7b3244cece7.mov
after:
https://user-images.githubusercontent.com/15389209/232371786-d38120fc-fab1-41e2-a29c-e4a553b9a32c.mov
---
part of: #629
=> fix(database): select instead of add when select option is exsit

packages/blocks/src/code-block/affine-code-line.ts
=> fix(virgo): no-wrap style for code block

packages/blocks/src/__internal__/utils/virgo.ts, packages/virgo/src/services/range.ts, packages/virgo/src/virgo.ts
=> fix(virgo): auto scroll to cursor when inputting

packages/blocks/src/database-block/components/column-header/column-header.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/database-block/register.ts
=> fix(database): viewportElement does not exsit

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/phasor/src/renderer.ts, packages/phasor/src/surface.ts
=> fix(selection): should add offset to selected blocks in edgeless

packages/blocks/src/components/slash-menu/config.ts
Fix https://github.com/toeverything/AFFiNE/issues/1993
=> fix: date incorrect

packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts
=> fix: `affine-link` shouldn't leak style

packages/blocks/src/database-block/components/toolbar/index.ts
=> feat(database): update drag preview style

packages/blocks/src/__internal__/rich-text/rich-text.ts
=> fix(blocks): overwrite the default behavior when consecutive spaces

packages/blocks/src/page-block/edgeless/utils.ts, packages/blocks/src/page-block/edgeless/utils.unit.spec.ts
=> fix(edgeless):  storage of corrected connector attached points

packages/blocks/src/database-block/components/cell-container.ts, packages/blocks/src/database-block/components/column-header/column-header.ts, packages/blocks/src/database-block/components/column-type/index.ts, packages/blocks/src/database-block/components/edit-column-popup/edit-column-popup.ts, packages/blocks/src/database-block/components/edit-column-popup/utils.ts, packages/blocks/src/database-block/components/row-container.ts, packages/blocks/src/database-block/database-block.ts, packages/blocks/src/database-block/register.ts
fix: #2115
fix: #2116 
---
part of: #629
=> fix(database): `registerColumnHeader` follows database block life cycle

packages/blocks/src/database-block/components/database-title.ts
=> feat(database): temporarily use HTML native title as tooltip

packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts, packages/blocks/src/page-block/edgeless/components/resize-manager.ts
before:
https://user-images.githubusercontent.com/50226652/232549652-f7042c49-2f97-4e66-8269-e346405af5d4.mp4
after:
https://user-images.githubusercontent.com/50226652/232549677-5d5769fe-0697-4813-be39-e830703de06d.mp4
=> fix(edgeless): resize-Manager not consider zoom

packages/blocks/src/database-block/components/cell-container.ts, packages/blocks/src/database-block/components/column-header/column-header.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/database-block/components/toolbar/toolbar.ts, packages/blocks/src/database-block/database-block.ts
close: #2125
---
part of: #629
=> feat(database): support readonly mode

packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/mode-controllers/text-mode.ts, packages/blocks/src/page-block/edgeless/utils.ts, tests/edgeless.spec.ts
fix #2010
https://user-images.githubusercontent.com/21084335/233028021-cae00ad6-39f1-4eb0-8d8d-2e27c062f4d1.mov
=> feat(edgeless): double click the blank space to add text

packages/virgo/src/utils/transform-input.ts, tests/basic.spec.ts
=> fix: delete emoji in the middle of text

packages/blocks/src/__internal__/rich-text/reference-node.ts, packages/global/src/utils.ts, packages/playground/src/components/debug-menu.ts, packages/store/src/workspace/indexer/backlink.ts, packages/store/src/workspace/indexer/base.ts, packages/store/src/workspace/indexer/normalize-subpage.ts, packages/store/src/workspace/indexer/revise-subpage.ts, packages/store/src/workspace/workspace.ts
https://user-images.githubusercontent.com/18554747/233179035-c3d72569-db08-4e35-b701-7e671697803c.mov
=> feat(store): normalize subpage in meta

packages/editor/src/utils/editor.ts, tests/selection/block.spec.ts, tests/selection/native.spec.ts, tests/utils/actions/misc.ts
https://user-images.githubusercontent.com/27926/233139990-f67875ca-25f4-44cf-80fe-37c96b031b3d.mov
=> fix(selection): should be cleared when dragging block card from the BlockHub

packages/blocks/src/page-block/edgeless/frame-resize-observer.ts
https://user-images.githubusercontent.com/27926/233363336-b0fdca21-837e-46fb-b568-aecc1b817c1a.mov
=> chore: increase frame resize refresh frequency

packages/blocks/src/database-block/components/column-header/column-width/index.ts
Replace mouse event to `pointer` event.
---
part of: #629
=> feat(database): mobile compatible

packages/blocks/src/__internal__/service/index.ts, packages/blocks/src/__internal__/utils/block-range.ts, packages/blocks/src/components/linked-page/linked-page-popover.ts, packages/store/src/__tests__/indexer.unit.spec.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/space.ts, packages/store/src/text-adapter.ts, packages/store/src/workspace/indexer/backlink.ts, packages/store/src/workspace/indexer/base.ts, packages/store/src/workspace/indexer/normalize-subpage.ts, packages/store/src/workspace/meta.ts, packages/store/src/workspace/page.ts, packages/store/src/workspace/workspace.ts, tests/basic.spec.ts
Redesign `subpageIds` about https://github.com/toeverything/blocksuite/pull/1716
=> refactor: subpage meta sync

packages/blocks/src/page-block/edgeless/components/single-connector-handles.ts, tests/edgeless.spec.ts, tests/utils/actions/edgeless.ts
=> fix(edgeless): offset when resizing connector

packages/virgo/src/utils/transform-input.ts, tests/basic.spec.ts, tests/utils/actions/keyboard.ts
=> fix: delete emoji forward

packages/docs/framework-integration.md
While enjoying the article, just two possible typos were found :)
=> docs: fix typos

packages/blocks/src/__internal__/clipboard/page-clipboard.ts, packages/blocks/src/__internal__/clipboard/utils/commons.ts, packages/blocks/src/__internal__/rich-text/inline-suggestion.ts, packages/blocks/src/__internal__/utils/block-range.ts, packages/blocks/src/page-block/utils/container-operations.ts, packages/virgo/src/virgo.ts
Upstrem of https://github.com/toeverything/blocksuite/issues/2184
=> refactor: use virgo element as the ref node when obtaining the vRange

packages/blocks/src/__internal__/rich-text/reference-node.ts, packages/blocks/src/__internal__/rich-text/rich-text.ts
before:
https://user-images.githubusercontent.com/24316656/233796234-94b3da3b-4ce5-4294-a2a4-15a7234d3e21.mp4
after:
https://user-images.githubusercontent.com/24316656/233796036-ba466119-3bfe-4878-b36a-e6093a919ca9.mp4
=> fix: reference node ime compatibility

packages/blocks/src/page-block/edgeless/components/component-toolbar/change-brush-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-frame-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts, packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-menu.ts, packages/blocks/src/page-block/edgeless/toolbar/connector-tool/connector-menu.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, packages/blocks/src/page-block/edgeless/toolbar/shape-tool/shape-menu.ts
=> fix(edgeless): popover color

packages/blocks/src/__internal__/rich-text/reference-node.ts, packages/blocks/src/__internal__/rich-text/rich-text.ts, packages/virgo/src/services/event.ts
Related to https://github.com/toeverything/blocksuite/pull/2232
=> refactor(virgo): support forged v-text node

packages/blocks/src/__internal__/clipboard/page-clipboard.ts, packages/blocks/src/page-block/utils/container-operations.ts, tests/clipboard.spec.ts
fix https://github.com/toeverything/blocksuite/issues/2265
=> fix: return new model after delete selection

packages/blocks/src/components/linked-page/linked-page-popover.ts, tests/linked-page.spec.ts
=> chore: hide the subpage tempoarily

packages/blocks/src/components/linked-page/linked-page-popover.ts, packages/docs/attaching-editor.md, packages/docs/data-persistence.md, packages/docs/workspaces-and-pages.md, packages/editor/src/components/simple-affine-editor.ts, packages/playground/examples/store/main.ts, packages/playground/src/components/debug-menu.ts, packages/playground/src/data/index.ts, packages/store/src/__tests__/database.unit.spec.ts, packages/store/src/__tests__/indexer.unit.spec.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/workspace/__tests__/test-app.ts, packages/store/src/workspace/__tests__/test-entry.ts, packages/store/src/workspace/workspace.ts, tests/linked-page.spec.ts, tests/utils/actions/misc.ts
Rework of https://github.com/toeverything/blocksuite/pull/1959
- new API
```ts
createPage(
options: { pageId?: string; init?: true | { title: string } } = {}
)
```
=> refactor(store)!: simplify `createPage` API

packages/global/src/config/consts.ts
Reference error occurred in Next.js.
=> fix(global): resolve SHORT_KEY reference issue

packages/blocks/src/__internal__/utils/gesture.ts, packages/blocks/src/components/selected-blocks.ts, packages/blocks/src/page-block/default/default-page-block.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, tests/selection/block.spec.ts, tests/selection/native.spec.ts
Related to: https://github.com/toeverything/blocksuite/issues/1453
=> feat(selection): support shift-click

packages/virgo/src/services/range.ts
=> fix: codeblock scroll behaviour when enter or backspce

packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts, packages/blocks/src/page-block/edgeless/components/line-styles-panel.ts, packages/blocks/src/page-block/edgeless/components/single-connector-handles.ts, packages/phasor/src/elements/connector/connector-element.ts, packages/phasor/src/elements/connector/draw-arrow.ts, packages/phasor/src/elements/connector/types.ts, tests/edgeless/connector.spec.ts, tests/edgeless/shape.spec.ts, tests/utils/actions/edgeless.ts
In this version, the connector bound couldn't cover the real shape. It will be fixed in #2318 .
https://user-images.githubusercontent.com/21084335/234508615-0fb905ee-bd18-4cf5-8c13-97c953720ddf.mov
=> feat(edgeless): connector line style

.github/CLA.md, packages/blocks/src/components/link-popover/link-popover.ts, tests/link.spec.ts
=> fix: requires double enter to input a link

packages/blocks/src/database-block/components/row-container.ts
=> feat(database): block-level selection match the width of title column

packages/blocks/src/database-block/components/cell-container.ts, packages/blocks/src/database-block/components/database-title.ts, packages/blocks/src/database-block/index.ts, tests/utils/actions/database.ts
=> fix(database): prevent multi select-edit popup

packages/blocks/src/database-block/components/column-type/select/select-cell-editing.ts
=> fix(database): press backspace to delete selected select tag

packages/blocks/src/database-block/database-service.ts
=> fix(database): autofocus on the first child

packages/blocks/src/database-block/components/column-type/select/select-cell-editing.ts
=> fix(database): select tag name cannot be repeated

packages/blocks/src/database-block/components/column-type/select/select-cell-editing.ts, packages/store/src/workspace/page.ts
=> fix(database): select tag cannot be selected repeatedly

packages/blocks/src/__internal__/utils/query.ts
=> fix(database): number/text cells support undo/redo

packages/blocks/src/page-block/edgeless/components/utils.ts
=> chore: optimize edgeless tooltip content

packages/blocks/src/database-block/components/toolbar/toolbar.ts, packages/blocks/src/database-block/database-block.ts
before:
https://user-images.githubusercontent.com/15389209/234878560-45c0be3d-ffc5-4b37-a6d5-195f879ac9ce.mov
after:
https://user-images.githubusercontent.com/15389209/234878634-0cb8c486-6318-4f0e-9c7a-d1f8a3c7651d.mov
=> fix(database): title column cannot be selected by block-level selection

packages/blocks/src/page-block/utils/bind-hotkey.ts, tests/selection/native.spec.ts, tests/utils/actions/misc.ts
=> fix: press arrow-right works incorrect with multi-line selection

packages/blocks/src/database-block/components/column-header/column-header.ts, packages/blocks/src/database-block/database-block.ts
before:
https://user-images.githubusercontent.com/15389209/235140202-8501dd29-0e9e-4e74-9c1c-64f92d2a59bb.mov
after:
https://user-images.githubusercontent.com/15389209/235140011-9d5a41f9-b6d3-4c7c-ac1a-e398dd3df15d.mov
=> fix(database): sets the height of the indicator for the column width

packages/blocks/src/database-block/components/cell-container.ts, packages/blocks/src/database-block/components/column-type/number.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts
before:
https://user-images.githubusercontent.com/15389209/235136259-a7975c1a-96e0-48c9-834f-8c07699fdaf8.mov
after:
https://user-images.githubusercontent.com/15389209/235135868-e349609c-3112-4a38-ad2d-7ec25517cbd9.mov
=> fix(database): expand tag cell click area

packages/playground/src/components/debug-menu.ts, packages/playground/src/data/index.ts, packages/playground/src/main.ts, packages/playground/src/utils.ts, packages/store/src/workspace/workspace.ts, tests/list.spec.ts
=> feat: support import from file

packages/blocks/src/__internal__/utils/gesture/recognizer.ts, packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts, tests/selection/block.spec.ts
https://user-images.githubusercontent.com/27926/235269585-b1758c49-bf78-4d96-9f11-36295eec2e3e.mov
=> fix(selection): dont show toolbar on selection

packages/blocks/src/components/slash-menu/config.ts, packages/blocks/src/components/slash-menu/slash-menu-popover.ts, packages/blocks/src/components/slash-menu/styles.ts
Ignore the following items when calling the slash menu in the database.
- Database
- Image or file 
- Quote
- Code Block
- Divider
=> feat: filter slash menu in database

packages/blocks/src/database-block/components/cell-container.ts, packages/editor/src/components/editor-container.ts, packages/editor/themes/affine.css
Make sure the style is correct when using BlockSuite through a third-party package.
=> chore: update editor style

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/block-hub.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/database-block/components/column-header/column-header.ts, packages/blocks/src/database-block/components/row-container.ts
https://user-images.githubusercontent.com/27926/233495956-7e36dfd3-7578-4414-8428-f0f76fa01a95.mov
=> fix(drag-handle): optimize position of indicator in database

packages/blocks/src/database-block/components/column-type/index.ts, packages/blocks/src/database-block/components/column-type/progress.ts, packages/blocks/src/database-block/components/edit-column-popup/column-type-popup.ts, tests/database.spec.ts
Headless version of `progress`.
close: #2384
https://user-images.githubusercontent.com/15389209/236100315-2e73a259-ede5-4650-979c-dee0bc17b234.mov
=> feat(database): support column type `progress`

packages/blocks/src/embed-block/embed-block.ts
=> chore(blocks): fix css in embed block

packages/blocks/src/database-block/components/cell-container.ts, packages/blocks/src/database-block/components/column-type/checkbox.ts, packages/blocks/src/database-block/components/column-type/multi-select.ts, packages/blocks/src/database-block/components/column-type/number.ts, packages/blocks/src/database-block/components/column-type/progress.ts, packages/blocks/src/database-block/components/column-type/rich-text.ts, packages/blocks/src/database-block/components/column-type/select/select.ts, packages/blocks/src/database-block/register.ts
related to: https://github.com/toeverything/blocksuite/pull/2383#discussion_r1184489329
=> refactor(database): optimize nullable columns types

packages/blocks/src/code-block/components/lang-list.ts, tests/code.spec.ts
https://user-images.githubusercontent.com/18554747/235989664-69ac4f2c-9647-4180-bfff-87408bbd0a23.mov
=> feat: code block supports fuzzy search

packages/blocks/src/code-block/code-service.ts, tests/code.spec.ts
=> fix: multi-line indentation does not work

packages/blocks/src/__internal__/rich-text/reference-node.ts, packages/blocks/src/__internal__/utils/std.ts, packages/blocks/src/__internal__/utils/std.unit.spec.ts, packages/blocks/src/components/linked-page/linked-page-popover.ts, packages/blocks/src/components/slash-menu/slash-menu-popover.ts, packages/blocks/src/components/utils.ts, tests/slash-menu.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/2385
https://user-images.githubusercontent.com/18554747/236381412-67bb6e0e-3087-4a1e-98cb-38106a29cd62.mov
=> fix: linked page popover supports CJK

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/database-block/table/components/toolbar/toolbar-action-popup.ts
before:
https://user-images.githubusercontent.com/15389209/236383787-91d2a60d-9990-4011-bf51-990d175d356f.mov
=> feat(drag-handle): support non-table view database

.github/CLA.md
=> chore: add signature in CLA.md

.github/CLA.md, packages/blocks/src/database-block/table/components/column-type/select/select-cell-editing.ts, packages/blocks/src/database-block/table/components/column-type/select/select-option.ts, packages/blocks/src/database-block/table/types.ts, packages/playground/src/data/index.ts
=> feat(database): add id to the tag of select column

.github/CLA.md
=> docs: update CLA.md

packages/blocks/src/__internal__/rich-text/reference-node.ts, packages/blocks/src/__internal__/utils/types.ts, packages/editor/src/components/editor-container.ts, packages/store/src/__tests__/workspace.unit.spec.ts, packages/store/src/workspace/workspace.ts
Upstream of https://github.com/toeverything/blocksuite/pull/2446
=>  feat: support `pageModeSwitched` slot

packages/blocks/src/__internal__/service/index.ts
Fix https://github.com/toeverything/blocksuite/issues/2453
=> fix: replace unsafe characters

packages/blocks/src/components/database-modal/database-modal.ts, packages/blocks/src/components/database-modal/styles.ts
=> feat(database): update `To Database` modal style

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/__internal__/utils/query.ts
close: #2457 
https://user-images.githubusercontent.com/15389209/236977213-251e0321-36dc-40ab-9f37-c1cc040c97a2.mov
=> feat(database): support `Backspace` key in title column

packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, packages/blocks/src/page-block/edgeless/utils.ts
Part of: https://github.com/toeverything/blocksuite/issues/2196
=> chore(edgeless): add zoom max

packages/blocks/src/database-block/table/table-view.ts
=> feat(database): update scrollbar style

packages/blocks/src/page-block/edgeless/create-drag-handle.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/utils/container-operations.ts
Close https://github.com/toeverything/blocksuite/issues/2460
=> feat: split original block after drag out a block in edgeless mode

packages/blocks/src/__internal__/content-parser/parse-html.ts, tests/clipboard.case.ts
=> fix: redundant list item line breaks on pasting rich content

packages/blocks/src/page-block/utils/const.ts
=> feat(database): update hover text

packages/blocks/src/__internal__/utils/gesture/recognizer.ts, packages/blocks/src/__internal__/utils/gesture/selection-event.ts, packages/blocks/src/page-block/edgeless/hotkey.ts, packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts
Related to: #2432
https://github.com/toeverything/blocksuite/assets/27926/458fd002-53ff-47a1-b4cd-3de941f4be8a
=> feat(edgeless): switch to pan mode when holding right-key

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
related to: https://github.com/toeverything/blocksuite/pull/2458#issuecomment-1541300534
When press `Backspace` key to delete row, preserve at least 1 blank row.
https://github.com/toeverything/blocksuite/assets/15389209/b383a2f2-2fe5-4cc3-8f0a-c5235b2de625
=> feat(database): preserve at least 1 blank row

packages/blocks/src/page-block/edgeless/hotkey.ts, packages/global/src/config/consts.ts
=> feat(edgeless): use delete shortcut to delete content

packages/blocks/src/components/format-quick-bar/styles.ts, packages/blocks/src/database-block/table/components/column-header/column-header.ts, packages/blocks/src/database-block/table/components/edit-column-popup/column-type-popup.ts
=> feat(database): update icon style

packages/blocks/src/components/linked-page/linked-page-popover.ts, packages/blocks/src/components/slash-menu/slash-menu-popover.ts, packages/blocks/src/components/utils.ts
Fix https://github.com/toeverything/blocksuite/issues/2416
=> fix: remove unreliable delimiter

packages/blocks/src/database-block/table/components/toolbar/toolbar.ts
=> feat(database): hide clear icon when no search content

packages/blocks/src/database-block/table/components/column-header/styles.ts
=> fix(database): style in edgeless mode

packages/blocks/src/database-block/table/components/column-header/column-move/index.ts
=> feat(database): enable auto scroll for dragging column

packages/blocks/src/page-block/edgeless/create-drag-handle.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/utils.ts, tests/edgeless/frame.spec.ts
Fixed: https://github.com/toeverything/blocksuite/issues/2559
=> fix: wrong position in page mode after drag out a block in edgeless mode

packages/phasor/src/elements/brush/brush-element.ts, tests/edgeless/brush.spec.ts
before:
https://github.com/toeverything/blocksuite/assets/50035259/c213b5a4-48e3-4e5d-987a-f670bfe627a8
after:
https://github.com/toeverything/blocksuite/assets/50035259/d494c8e1-38d7-4a2a-bdb9-ab471f5d8606
=> feat(phasor): simulate pressure in brush

packages/blocks/src/page-block/utils/bind-hotkey.ts, packages/blocks/src/page-block/utils/container-operations.ts
Close https://github.com/toeverything/blocksuite/issues/2433
=> feat: support input under block-level selection

packages/blocks/src/components/slash-menu/config.ts
Fix https://github.com/toeverything/blocksuite/issues/2582
Due to https://github.com/toeverything/blocksuite/pull/2545
=> fix: slash menu insert image

packages/phasor/package.json, packages/phasor/src/elements/shape/shape-element.ts, packages/phasor/src/elements/shape/shapes/diamond.ts, packages/phasor/src/elements/shape/shapes/ellipse.ts, packages/phasor/src/elements/shape/shapes/rect.ts, packages/phasor/src/elements/shape/shapes/triangle.ts, packages/phasor/src/elements/shape/types.ts, packages/phasor/src/elements/surface-element.ts, packages/phasor/src/renderer.ts, pnpm-lock.yaml, tests/edgeless/shape.spec.ts
=> feat(phasor): support hand-drawn-like style

packages/blocks/src/database-block/table/components/toolbar/toolbar.ts
=> feat(database): update toolbar style

packages/blocks/src/page-block/edgeless/components/tool-icon-button.ts
=> fix(edgeless): zIndex on tooltip

packages/global/src/config/consts/block-hub.ts, tests/hotkey.spec.ts
=> chore: hide divider menu entries

packages/blocks/src/database-block/table/components/column-header/styles.ts, packages/blocks/src/database-block/table/components/column-type/select/select-cell-editing.ts, packages/blocks/src/database-block/table/components/column-type/select/select-option.ts, packages/blocks/src/database-block/table/components/column-type/select/select.ts
close: #2603 
https://github.com/toeverything/blocksuite/assets/15389209/8b65a076-debe-4840-9ded-d1059266733e
=> feat(database): update cursor style

packages/blocks/src/database-block/table/components/edit-column-popup/column-type-popup.ts
=> feat(database): update column-type-popup font

packages/blocks/src/__internal__/utils/filesys.ts, packages/blocks/src/page-block/edgeless/components/tool-icon-button.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, packages/phasor/src/renderer.ts
Close #2523
https://github.com/toeverything/blocksuite/assets/27926/ca1ad478-d50e-428f-8925-a07158120993
=> feat(edgeless): image uploads

packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/components/drag-handle.ts, packages/blocks/src/database-block/database-service.ts, packages/blocks/src/database-block/table/components/row-container.ts, packages/blocks/src/database-block/table/components/selection.ts, packages/blocks/src/database-block/table/table-view.ts, packages/blocks/src/page-block/default/selection-manager/database-selection-manager/table-view.ts, packages/blocks/src/page-block/default/selection-manager/database-selection-manager/utils.ts, packages/blocks/src/page-block/default/utils.ts
https://github.com/toeverything/blocksuite/assets/15389209/02ca5689-d8f4-42ce-b139-18dde72de62a
=> feat(database): update row-selection style

packages/blocks/src/__internal__/content-parser/index.ts, packages/blocks/src/code-block/code-service.ts
=> fix: codeblock export markdown and html

packages/blocks/src/__internal__/utils/gesture/recognizer.ts, packages/blocks/src/__internal__/utils/query.ts
=> fix(database): prevent processing of native input selections

packages/blocks/src/components/block-hub.ts, packages/blocks/src/paragraph-block/paragraph-block.ts
Fixed #2644 
https://github.com/toeverything/blocksuite/assets/50652358/9cafa6f0-61fe-442d-9b60-bf4227568c03
=> fix(block-hub): fix the block-hub toggle

packages/blocks/src/components/slash-menu/config.ts, tests/slash-menu.spec.ts
https://github.com/toeverything/blocksuite/assets/18554747/75ebfe5f-46f6-4a58-a2f6-af0d6ba5bc3a
=> feat: add page command to the slash menu

.github/CLA.md, packages/blocks/src/code-block/code-block.ts
close: #2641 
https://github.com/toeverything/blocksuite/assets/33057454/33feae63-5cd5-471a-8fe2-96e217b1f71e
=> fix: scrollbar not visible for codeblocks issue

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
This fixes #2151, https://github.com/toeverything/AFFiNE/issues/2021
=> fix: inline code or strikethrough error when hard enter

packages/blocks/src/__internal__/utils/query.ts
before:
https://github.com/toeverything/blocksuite/assets/27926/082ef346-f033-461a-8e52-93eb8d3bffcc
after:
https://github.com/toeverything/blocksuite/assets/27926/cd98cb1a-f34b-4171-857e-9fda7cef4311
=> fix(drag-handle): position when hovering over border of database

packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts
=> fix(edgeless): color of icon on toolbar when it is activated

packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts
=> fix(edgeless): fit to screen

packages/blocks/src/database-block/database-service.ts, packages/blocks/src/database-block/table/components/column-type/select/select-cell-editing.ts
close: #2681
https://github.com/toeverything/blocksuite/assets/15389209/f01a3f4f-e91f-41cf-b6b6-1134d801b32d
=> feat(database): select-column supports keyboard operation

packages/playground/src/data/database.ts, packages/playground/src/data/empty.ts, packages/playground/src/data/preset.ts
=> fix(playground): should not use native Text

packages/blocks/src/page-block/edgeless/components/block-children-container.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/utils.ts
https://github.com/toeverything/blocksuite/assets/27926/bfddc8ca-04d5-41eb-9002-a6379607ed2f
https://github.com/toeverything/blocksuite/assets/27926/c555f22d-2dfd-4f3a-91a8-831db5d5bce3
=> perf(edgeless): use page-level layer to replace block-level transform

packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/database-block/database-service.ts, packages/blocks/src/database-block/table/components/selection/row-selection.ts, packages/blocks/src/database-block/table/table-view.ts
close: #2704
https://github.com/toeverything/blocksuite/assets/15389209/6998a61d-dc86-4db0-98c5-cbdcc37edd34
=> feat(database): support delete row-level selection

packages/blocks/src/code-block/code-block.ts
Close #2491
https://github.com/toeverything/blocksuite/assets/27926/b7654b61-6348-4139-8c13-fab8f3e80ff5
=> fix(edgeless): position of line number on code-block when zooming view

packages/blocks/src/__internal__/content-parser/file-exporter/exporter-style.ts, packages/blocks/src/__internal__/content-parser/file-exporter/file-exporter.ts, packages/blocks/src/frame-block/frame-model.ts, packages/editor/themes/affine.css, packages/global/src/config/consts.ts, packages/playground/src/components/debug-menu.ts, packages/store/src/__tests__/workspace.unit.spec.ts, tests/clipboard.spec.ts, tests/database.spec.ts, tests/drag.spec.ts, tests/edgeless/basic.spec.ts, tests/edgeless/frame.spec.ts, tests/embed.spec.ts, tests/slash-menu.spec.ts, tests/utils/asserts.ts
related to: https://github.com/toeverything/AFFiNE/issues/2486
close: https://github.com/toeverything/blocksuite/issues/2579
=> feat: update editor width

packages/blocks/src/database-block/table/components/row-container.ts
=> feat(database): update title column content style

packages/blocks/src/__internal__/rich-text/keyboard.ts, tests/linked-page.spec.ts
Related to https://github.com/toeverything/blocksuite/issues/2730
=> fix: linked page trigger should not break bracket completion

packages/blocks/src/database-block/table/selection-manager/selection-manager.ts
before:
https://github.com/toeverything/blocksuite/assets/15389209/29e58137-356a-44b9-b81d-3cb6fbab877a
after:
https://github.com/toeverything/blocksuite/assets/15389209/4cf71cef-b05d-411f-8853-f81c3c9af65f
=> fix(database): unable to select row from outside

packages/blocks/src/__internal__/content-parser/index.ts, packages/blocks/src/components/block-hub.ts, packages/blocks/src/components/drag-handle.ts, packages/editor/src/components/editor-container.ts, packages/playground/index.html, packages/playground/src/components/debug-menu.ts
=> feat: add basic support for pdf export

packages/blocks/src/__internal__/utils/selection.ts, packages/blocks/src/database-block/table/selection-manager/selection-manager.ts
=> fix(database): unable to use row-level selection in edgeless mode

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
=> feat(database): keep row type when pressing enter to create new row

packages/blocks/src/page-block/edgeless/components/surface-text-editor.ts
=> fix(edgeless): text keep focus on zooming

packages/blocks/src/page-block/edgeless/components/surface-text-editor.ts
=> feat(edgeless): auto removing empty canvas text

packages/phasor/src/surface.ts
=> fix(edgeless): paste text element

packages/blocks/src/database-block/table/components/selection/cell-selection.ts, packages/blocks/src/database-block/table/components/selection/row-selection.ts
=> feat(database): support selections scaling in edgeless mode

packages/blocks/src/page-block/edgeless/components/surface-text-editor.ts
=> fix(edgeless): text size become zero after zoom or move

packages/blocks/src/database-block/table/selection-manager/row.ts, packages/blocks/src/page-block/default/selection-manager/utils.ts
https://github.com/toeverything/blocksuite/assets/15389209/6a385e4a-4e9c-462c-aa17-2b786f55a8ab
=> feat(database): select database itself when selecting database from outside

packages/blocks/src/database-block/table/components/selection/utils.ts
before:
https://github.com/toeverything/blocksuite/assets/15389209/c1f38468-c6d8-4925-8fee-d704ef471068
after:
https://github.com/toeverything/blocksuite/assets/15389209/58603d0f-9a03-4d1b-939d-af26dbd1d16e
=> fix(database): page scrolling when cell selection is selected

packages/blocks/src/database-block/table/selection-manager/cell.ts
before:
https://github.com/toeverything/blocksuite/assets/15389209/c5490d77-ba1f-47a9-93ba-1392c3e4214e
after:
https://github.com/toeverything/blocksuite/assets/15389209/4855a9ff-b576-4db1-a23f-7105faa4335d
=> fix(database): reset native selection when cell-level selection is selected

packages/blocks/src/__internal__/utils/hotkey.ts, packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts, packages/blocks/src/page-block/edgeless/components/surface-text-editor.ts, packages/blocks/src/page-block/edgeless/selection-manager.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/phasor/src/elements/surface-element.ts, packages/phasor/src/renderer.ts
=> fix(edgeless): remove blank area on editing canvas text

packages/blocks/src/page-block/edgeless/components/surface-text-editor.ts, packages/blocks/src/page-block/edgeless/utils.ts
=> fix(edgeless): keep text size when zooming

packages/phasor/src/elements/text/text-element.ts, packages/phasor/src/elements/text/utils.ts
=> fix(phasor): text render offset

packages/virgo/src/services/delta.ts, packages/virgo/src/services/event.ts
=> fix(virgo): lit may be crashed by IME

packages/blocks/src/components/import-page/import-page.ts, packages/playground/src/components/debug-menu.ts
=> style: fix typo "Html"

packages/blocks/src/page-block/default/default-page-block.ts
To close #2807 
https://github.com/toeverything/blocksuite/assets/99816898/f5fc6a92-7961-4848-8876-89e45e5757ca
It seems that the first paragraph block is the second child of the page block. So I check the second element of the model's children.
=> fix(blocks): in title line, press key arrowdown will create a new line

packages/blocks/src/__internal__/utils/selection.ts, scripts/node-import-test.ts
Fixes: https://github.com/toeverything/blocksuite/issues/2826
=> fix: the document is not defined

packages/blocks/package.json, packages/blocks/src/__internal__/content-parser/file-exporter/file-exporter.ts, packages/blocks/src/__internal__/content-parser/index.ts, packages/blocks/src/components/drag-handle.ts, packages/playground/src/components/debug-menu.ts, pnpm-lock.yaml
=> feat: add basic support for png export

packages/blocks/src/__internal__/utils/query.ts, packages/blocks/src/components/format-quick-bar/format-bar-node.ts, packages/blocks/src/components/format-quick-bar/index.ts, packages/blocks/src/page-block/utils/const.ts
https://github.com/toeverything/blocksuite/assets/15389209/f534f992-ebee-4cc2-9a8c-c9436d12cf71
=> feat(database): optimize format-bar position for block selection

packages/blocks/src/components/import-page/import-page.ts, packages/blocks/src/components/import-page/styles.ts, packages/blocks/src/page-block/page-service.ts
=> fix: import Notion exported file to AFFiNE

packages/blocks/src/paragraph-block/paragraph-block.ts
=> fix: incorrect placeholder position for empty list parent

packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, packages/playground/src/data/preset.ts, tests/edgeless/basic.spec.ts, tests/utils/actions/click.ts, tests/utils/actions/edgeless.ts
=> feat(edgeless): option key mouse drag duplicate element

packages/store/src/workspace/page.ts, tests/drag.spec.ts
Try [heavy-whiteboard](https://blocksuite-toeverything.vercel.app/?init=heavy-whiteboard) example in page mode.
=> fix(store): support moving blocks in multiple frames

packages/blocks/src/__internal__/content-parser/parse-html.ts, packages/blocks/src/components/import-page/import-page.ts
=> fix: the failing of uploading image when importing file

packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts, packages/blocks/src/__internal__/utils/types.ts, packages/blocks/src/frame-block/frame-service.ts, tests/clipboard.spec.ts, tests/utils/actions/edgeless.ts
=> fix(edgeless): paste frame block with background

packages/blocks/src/__internal__/rich-text/markdown-convert.ts
To fix #2836 
https://github.com/toeverything/blocksuite/assets/99816898/55a84247-5c33-4da2-abcb-352c1928975a
=> fix(blocks): do not convert markdown in quote block

packages/blocks/src/page-block/default/selection-manager/selection-manager.ts, packages/global/src/utils/disposable.ts, packages/lit/src/event/dispatcher.ts, packages/virgo/src/services/range.ts
=> fix: fix cursor position when using cmd+z hotkey

packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts, packages/blocks/src/page-block/edgeless/components/resize-handles.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, tests/edgeless/selection.spec.ts, tests/utils/actions/misc.ts, tests/utils/actions/selection.ts
https://github.com/toeverything/blocksuite/assets/27926/d396f349-9401-484e-9ad1-53f82b0b9134
=> fix(edgeless): should update rect of selection when resizing viewport

packages/blocks/src/database-block/table/components/column-type/select/select-cell-editing.ts, packages/global/src/config/icons/database.ts
To fix #2887 
https://github.com/toeverything/blocksuite/assets/99816898/c612b368-6e55-4d86-9b82-ec501b8d4599
=> fix(blocks): database multi-select tab close icon invisible

packages/blocks/src/components/virgo-input/utils.ts, packages/blocks/src/components/virgo-input/virgo-input.ts
=> fix(blocks): number mode in virgo-input

packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts, packages/blocks/src/page-block/edgeless/components/hover-rect.ts, packages/blocks/src/page-block/edgeless/components/resize-handles.ts, packages/blocks/src/page-block/edgeless/components/utils.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
Closes #2465
1. refactor html structure
2. support edge dragging on frame
https://github.com/toeverything/blocksuite/assets/27926/283d5e23-edc7-4a8b-b15f-f62584e7632d
=> feat(edgeless): support edge dragging on frame

packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-button.ts, packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts, packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/utils.ts, packages/phasor/src/elements/text/text-element.ts, packages/phasor/src/renderer.ts, packages/phasor/src/surface.ts
=> feat(edgeless): add basic text toolbar

packages/blocks/src/__internal__/content-parser/parse-html.ts, packages/blocks/src/components/linked-page/linked-page-popover.ts
=> fix: affine shows duplicate data when importing Notion subpage

packages/blocks/src/database-block/table/components/column-header/column-width/index.ts
=> fix(database): unexpected row-level selection

packages/blocks/src/bookmark-block/bookmark-block.ts
fixed: https://github.com/toeverything/AFFiNE/issues/2586
=> feat: modify bookmark style

packages/blocks/src/page-block/edgeless/hotkey.ts, packages/phasor/src/surface.ts
closes https://github.com/toeverything/blocksuite/issues/2706
=> feat(edgeless): support select all

packages/blocks/src/bookmark-block/bookmark-block.ts, packages/blocks/src/bookmark-block/images/icons.ts, packages/blocks/src/bookmark-block/utils.ts
fixed: https://github.com/toeverything/blocksuite/issues/2909
=> fix: abort update bookmark block if it is not exist

packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts, tests/edgeless/basic.spec.ts, tests/utils/actions/edgeless.ts, tests/utils/actions/keyboard.ts
=> feat(edgeless): shift click multi-select

packages/blocks/src/__internal__/rich-text/keyboard.ts, packages/blocks/src/__internal__/rich-text/rich-text.ts
=> feat(database): prevent the default behavior of tabs in the title column

packages/blocks/src/database-block/table/components/column-type/select/select-cell-editing.ts, packages/blocks/src/database-block/table/selection-manager/cell.ts
=> fix(database): close the select popup when pressing the Tab key

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts, packages/blocks/src/page-block/edgeless/hotkey.ts, packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts, tests/edgeless/shortcut.spec.ts, tests/utils/actions/edgeless.ts
=> feat(edgeless): support shortcuts for zooming

packages/blocks/src/database-block/table/components/selection/row-selection.ts
=> fix(database): incorrect row selection when changing row order

packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts, packages/store/src/workspace/page.ts, tests/list.spec.ts
To fix #2899 
To fix #2966 
https://github.com/toeverything/blocksuite/assets/99816898/f5213a19-f463-4331-8ce0-b4fb22f1229b
=> fix: delete parent lost nested children

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts, packages/blocks/src/__internal__/service/keymap.ts
=> feat(database): optimize the behavior of the Enter key for the title column
