packages/playground/src/main.ts
packages/store/package.json
packages/store/src/providers.ts
packages/store/src/space.ts
packages/store/src/store.ts
packages/store/src/text-adapter.ts
pnpm-lock.yaml

Please don't squash. Please use "rebase and merge" if you like the commit messages.
We refactor a couple more places with TypeScript types.
We have also added a wrapper around `yjs`'s `IndexeddbPersistence` as `IndexedDBProvider` for store.

Add IndexDBProvider

---

playwright.config.ts
tests/link.spec.ts
tests/utils/actions/misc.ts
tests/utils/asserts.ts

- Add `actionTimeout` for playwright test
- `initEmptyState` now will return block id
- `assertStoreMatchJSX` now support specify id so that simplify snapshot size

test: add some link test

---

tests/selection.spec.ts

In the original code, the clicked area on windows is the gap in the middle of the list, and the list is not clicked.
Now,I update click area of test to pass the test.

fix:selection test fails on windows

---

packages/blocks/src/__internal__/index.ts
packages/blocks/src/index.ts
packages/editor/src/components/debug-menu/debug-menu.ts
packages/editor/src/components/editor-container/editor-container.ts
packages/editor/src/components/index.ts
packages/editor/src/index.ts
packages/playground/src/main.ts
tests/paragraph.spec.ts
tests/utils/actions/click.ts
tests/utils/actions/misc.ts

Remove debug-menu from @blocksuite/blocks to @blocksuite/editor
1. @blocksuite/blocks should just purely contain by blocks 
2. Debug-menu depend on Store model, is not exist in block any more

feat: remove debug-menu from @blocksuite/blocks to @blocksuite/editor

---

packages/blocks/src/page-block/utils/container-operations.ts
tests/hotkey.spec.ts

Reserve selection after formatting
https://user-images.githubusercontent.com/18554747/204356593-37629a9d-c65d-4b6a-bf88-ef92e1552839.mov
Note: multiple line format not updated due to weird selection behavior
https://user-images.githubusercontent.com/18554747/204356986-8c9ceba0-a3bd-4439-9a3a-12abc9e8025e.mp4

fix: reserve selection after format

---

packages/store/package.json
packages/store/src/__tests__/space.spec.ts
packages/store/src/search.ts
packages/store/src/store.ts
pnpm-lock.yaml

this pr add basic indexing quality local search feature into @blocksuite/store
the indexing service will refresh index all prop:text and prop:title in a block when they add/update/remove, at this time indexing feature support ascii words and cjk tokenize, if user use non-chromium core, tokenize function will fallback to char based tokenize
in future we will implement a native version in rust with same apis, and must allow add more custom props from outside

search feature

---

packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/page-block/utils/cursor.ts

`comparePoint()` is unstable when dragging across HTMLELement. During native dragging, wrong `isForward` derived by it will cause [failure of focuing TextNode ](https://github.com/toeverything/blocksuite/blob/3a07c6f540f5dd9c8bc1ae2bf5f05cca7dcbf196/packages/blocks/src/__internal__/utils/selection.ts#L74).  Use `getDragDirection()` to cover this case. 
https://user-images.githubusercontent.com/20554850/204439699-db0a36f2-3821-4651-a75e-b56785b7b3c2.mov
https://user-images.githubusercontent.com/20554850/204439704-305efdf8-87bf-4467-90e0-8327efee514c.mov

Fix: Boundary case of native dragging between block components

---

packages/blocks/src/page-block/default/default-page-block.ts

fix: match `removeHotKeys` in divider

---

packages/editor/src/managers/clipboard/paste-manager.ts

When dragging and selecting, if the first block is a divider, copying and pasting will miss the first line

fix: clipboard state when first block is divider

---

packages/playground/vite.config.ts
packages/store/src/blob/__tests__/test-entry.ts
packages/store/src/blob/index.ts
packages/store/src/blob/providers.ts
packages/store/src/blob/utils.ts

Match blob sync api to newest affine cloud apis
Note1: Now we can access cloud api in same host based on vite proxy config, default disabled.
Note2: In the current backend design, the workspace id is a randomly generated int64 number, so if you need to test or enable blob synchronization, the provided workspace needs to be a number
Note3: current api server run at 100.77.180.48:11001

feat: adjust blob api with affine cloud

---

packages/playground/src/main.ts
packages/playground/src/utils.ts
packages/store/src/__tests__/workspace.unit.spec.ts
packages/store/src/store.ts
packages/store/src/utils/id-generator.ts

I had a meeting with @doodlewind, and the conclusion is the error that the reason caused the collaborative mode and URL paste crash is the **default generator** in the playground. This will let all clients create a block starting from 0, and the editor will crash.
Fixes: https://github.com/toeverything/blocksuite/issues/217, https://github.com/toeverything/blocksuite/issues/287

refactor: id generator

---

packages/blocks/src/page-block/utils/container-operations.ts

Fix format will fail if there has an empty line
https://user-images.githubusercontent.com/18554747/208399223-c28c3b53-d2fe-4a71-8bff-6c1971e238e2.mov
This issue is also be mentioned at https://github.com/toeverything/blocksuite/pull/358

fix: skip empty line when merge multiple lines format

---

packages/blocks/src/__internal__/rich-text/rich-text.ts
tests/link.spec.ts
tests/utils/actions/click.ts

Fix when editing the link text, it will split into pieces.
See more details:
https://user-images.githubusercontent.com/18554747/208391062-26c4450d-ec33-438e-b5e4-eff3a3d25266.mov
Related to https://github.com/toeverything/blocksuite/pull/148
Due to https://github.com/toeverything/blocksuite/pull/162

Fix: typo on format replace

---

packages/blocks/src/shape-block/utils/utils.ts
packages/playground/src/utils.ts
packages/store/package.json
packages/store/src/doc-providers.ts
packages/store/src/index.ts
packages/store/src/workspace/page.ts
packages/store/src/workspace/search.ts
packages/store/src/workspace/workspace.ts
pnpm-lock.yaml

TLDR:
* All the BlockSuite packages are now ESM compatible.
* Only the `store` package is ready for the SSR environment.
* The WebSocket provider is removed and should be maintained outside of BlockSuite.
---
Previously, only the `blocks` package was released as ESM (with `"type": "module"` enabled) package, whose ESM entry is a standalone bundled one built by Vite. Although the `store` and `editor` packages are publishing the `tsc` transpiled ESM modules as source-only releases, they are not marked as `"type": "module"` because they are using the `import "./foo"` statement instead of `import "./foo.js"`, this violates the standard and is not compatible with Next.
In 31106f728cc07d7b006aae02adccc5ac9358e87e we have added the `.js` suffix to *almost* all import statements (using the …

feat: esm-compatible store

---

packages/blocks/src/__internal__/rich-text/rich-text.ts
packages/blocks/src/__internal__/utils/common-operations.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/format-quick-bar/index.ts
packages/blocks/src/page-block/default/selection-manager.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/edgeless/selection-manager/default.ts
packages/blocks/src/page-block/utils/container-operations.ts
packages/blocks/src/page-block/utils/cursor.ts
tests/format-quick-bar.spec.ts

- Restore selection after transform block
https://user-images.githubusercontent.com/18554747/209319944-db96fe6c-4350-4d10-84de-fe45e84dc6cc.mov
- Format bar will following current range always now.
Also mentioned at https://github.com/toeverything/blocksuite/pull/358

Fix: restore selection after transform block

---

packages/blocks/src/components/format-quick-bar/format-bar-node.ts
tests/format-quick-bar.spec.ts

This pull request fixes the issue with selecting losing when a user clicks the edge of the format bar.

fix: prevent click event from making selection lost

---

packages/blocks/src/code-block/style.css
packages/blocks/src/paragraph-block/style.css

Fix #502
This is ligatures in the `Space Mono`, maybe space mono is not suitable as a code font

fix: incorrect code block short ligatures

---

packages/blocks/src/__internal__/rich-text/shortcuts.ts
tests/code.spec.ts

Now following markdown can create code block
> \`\`\`
> \`\`\`javascript
> \`\`\`kkkk
> \`\`\`122k1212
Following markdown will create an inline code
> \`\`\`\`\`

fix: unexpected behaviour of markdown shortcut when creating code block and inline code

---

packages/blocks/src/page-block/default/selection-manager.ts

fix bug: CMD-A loses the cursor when the cursor is at the beginning of the line

fix: select all with hot key at the start of the line

---

packages/editor/src/managers/clipboard/paste-manager.ts

fix: The text will be inserted from the end of the line when pasting at the start of a line

fix: paste at the start of line

---

packages/blocks/src/__internal__/utils/gesture.ts
tests/utils/actions/drag.ts

fix: Cursor lost when clicking on the blank position on the left and right side of the page

fix: cursor lose outside container

---

package.json

Set node version's lower limit to `16.9.0` as `corepack` is added since then.

build: restrict node version and add packageManager to force agent

---

tests/hotkey.spec.ts
tests/link.spec.ts
tests/utils/actions/keyboard.ts

- simplify keyboard operation
- add test for mock selection node
- it should not be stored to y doc

test: simplify keyboard operation

---

tests/code.spec.ts

Update: Press ArrowUp after code block now should select code block, rather than jumping into it

chore: update code block unit test

---

packages/blocks/src/__internal__/rich-text/rich-text.ts
packages/blocks/src/code-block/components/syntax-code-block.ts

When AFFiNE stored code blocks and refresh, code block will unexpectedly get focus, now this behavior is fixed by distinguishing whether the code block is empty. It's not ideal as AFFiNE  may store empty code block, still causing code block getting focus, better solution in the future maybe  tracking the `source` of a code block.

fix: code block unexpectedly get focus, clean redundant code

---

packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/selection.ts

1. Related to #588, in #588, multiple lines of one content block was not considered, which will cause back select failure
2. Fix: When BlockSuite is embedded in other container, can't get correct start container by `SelectionEvent.start.x`, `SelectionEvent.start.y`,

fix: optimize `isForward` detection in `SelectionManager`

---

packages/blocks/src/__internal__/rich-text/rich-text.ts

clean blocking for https://github.com/toeverything/blocksuite/pull/621, stop the re-registry warning when performing HMR. And, all the other quill registry has set `supressWarning` to `true` so I guess this is not an exception. I tested the official example of quill-curosrs https://github.com/reedsy/quill-cursors/tree/main/example and tweaked it with many re-register, seems like everything is fine.

fix(blocks): set supressWarning to true of quill-cursors

---

packages/blocks/src/__internal__/utils/components.ts
packages/blocks/src/page-block/default/selection-manager.ts
tests/format-quick-bar.spec.ts
tests/hotkey.spec.ts
tests/link.spec.ts
tests/list.spec.ts
tests/paragraph.spec.ts
tests/utils/asserts.ts

Fixes: https://github.com/toeverything/blocksuite/issues/671
This reverts commit e4483a0447977394294a61c53efaedc9e7c4df84.

Revert "fix: use flex in children container (#586)"

---

packages/store/src/text-adapter.ts

See the bug in the demo video:
https://user-images.githubusercontent.com/584378/212094208-835d253c-0743-41fa-a755-c80aba3260c6.mp4
The cursor indicator on the right pane does not being updated when the peer user is typing in the left pane.
Root cause:
- When typing on the left, we will set cursor to local state as `Y.RelativePosition`. This value will NOT change when typing due to RelativePosition's internal implementation. 
- We have `AwarenessAdapter` in blocksuite that listens to `change` events emitted by awareness. On receiving the update on the right pane, it will deep-compare the updated state with the previous value. Since the relative position is still the same, the `change` event will not be emitted.
The proposed solution in this pr appends a hidden `_rawSelection` to the cursor …

fix: peer cursor updates sometimes does not emit "change" event

---

packages/blocks/src/components/drag-handle.ts
packages/blocks/src/page-block/default/selection-manager.ts
packages/blocks/src/page-block/default/utils.ts
packages/store/src/base.ts

If we want to move A after B, but not a child of B. The current move can only be a child of B, if B is the last block.
May not be very good in user experience
https://user-images.githubusercontent.com/27926/212127387-83f54f4e-44f7-4b52-8aa8-9f4f68f2b6a2.mov

fix: cant reach the last block in nesting

---

packages/blocks/src/code-block/components/syntax-code-block.ts

Before change, the code block line number is calculated by number of `\n`, when there are long lines, and when they are wrapped, the line number will be more than number of `\n`, it causes line number less than actual lines, as shown below.
After, line numbers only cares how much start lines there are, exceeding part are filled up by calculating
https://user-images.githubusercontent.com/20554850/212226891-11c8075d-5a54-4bb5-be89-3197a6979493.mov

fix: line number for wrapped lines

---

packages/blocks/src/page-block/default/selection-manager.ts

After #681 in which #669 is fixed, the parent index of each block are 1 larger, which is used in `binarySearchBlockEditingState`, causing horizontal dragging fails. This PR is to restore the behavior in #677, ie, supporting dragging in nested level

fix: adapting parent index of blocks to binarySearchBlockEditingState

---

packages/blocks/src/page-block/default/utils.ts

When the mouse moves out of the container, an error is reported

fix: should check that parentIndex is not undefined

---

packages/blocks/src/page-block/default/default-page-block.ts
packages/editor/src/components/editor-container.ts
packages/global/src/index.d.ts
packages/playground/src/components/debug-menu.ts
packages/playground/src/utils.ts
packages/store/src/awareness.ts
packages/store/src/workspace/workspace.ts

Fixes: https://github.com/toeverything/blocksuite/issues/694
Since modifying awareness source code is harder than I thought, I implemented a version that uses `local state` to update others flags

feat: support set remote flag

---

packages/blocks/src/code-block/components/syntax-code-block.ts

- When calculating text width with fake DOM, it is appended to the page and hidden on side of screen. Before this change, it's hidden on the left, when the line is long, it will be visible before it's removed from page. Now it's moved to the right to prevent this problem.
- A  minor change to reduce frequency of creating fake DOM, optimize performance

fix: hide mock line element properly

---

packages/blocks/src/page-block/default/selection-manager.ts
packages/editor/src/managers/clipboard/paste-manager.ts
tests/clipboard.spec.ts
tests/utils/actions/keyboard.ts

Related: #197 
`insertBlocks` method may need to be refactored.

fix: should keep first line format when pasted into a new line

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/surface-block/surface-block.ts
packages/global/index.d.ts
packages/phasor/src/container.ts
packages/playground/src/main.ts
packages/playground/src/utils.ts
packages/store/src/workspace/page.ts
packages/store/src/workspace/workspace.ts

Previously the contents in the canvas context were not attached to YDoc. For now, these elements could be collaboratively updated.

feat: attach surface elements to page ydoc

---

packages/blocks/src/__internal__/rich-text/link-node/create-link.ts
packages/blocks/src/__internal__/rich-text/link-node/link-node.ts
packages/blocks/src/__internal__/utils/gesture.ts
packages/blocks/src/__internal__/utils/hotkey.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/link-popover/link-popover.ts
packages/blocks/src/components/link-popover/styles.ts
packages/blocks/src/page-block/default/selection-manager.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
packages/blocks/src/page-block/utils/container-operations.ts
packages/editor/src/managers/clipboard/event-dispatcher.ts
tests/basic.spec.ts
tests/clipboard.spec.ts
tests/code.spec.ts
tests/embed.spec.ts
tests/link.spec.ts
tests/paragraph.spec.ts
tests/utils/actions/misc.ts
tests/utils/asserts.ts

fix https://github.com/toeverything/blocksuite/issues/619 https://github.com/toeverything/blocksuite/issues/682
- Filter most of the events whose target is non-rich-text from hotkey (fix most of the keyboard issues in non rich text input)
- Clear workaround for input and title in event hander
- Add test for #682 
- Add test for non-rich-text input, including
- create/edit link input
- code block language search input
- image caption input

fix: uniform event handler outside of rich text

---

playwright.config.ts

#TIL 
but the flaky test is also annotated.
see https://playwright.dev/docs/test-reporters#github-actions-annotations

test: use github reporter

---

packages/blocks/src/components/drag-handle.ts
packages/blocks/src/page-block/default/default-page-block.ts

Now drag indicator lifecycle is created and and removed in Drag handler, as we have may have more drag scenarios using drag indicator, as blockHub so far, and there will be only one dragging at a time. So how about making it globally exists, and after a component finished using it, hide it rather than removing it. In this way any components with dragging behavior can share one indicator

refactor: move drag indicator to a global singleton pattern

---

BUILDING.md
playwright.config.ts

I found that I can't make the `pnpm test` pass following the `BUILDING.md` tutorial, even on a clean Codespaces on GitHub. 🫠 Guessing some details are missing in the documentation so I tweak the playwright config file. And now, I can pass the `pnpm test` on my mac.
why remove `actionTimeout`?
I found when running on my mac (6 core, 12 workers), playwright will be failed on `actionTimeout` timeout. I think maybe too many workers are running concurrently so it stuck.

test: make test pass in local

---

packages/blocks/src/__internal__/utils/selection.ts

Fixes #697 
The problem of `comparePoint()` is when the cursor is not in the text area, its behavior is not stable. But when the cursor is in the text area, it seems very ideal
https://user-images.githubusercontent.com/20554850/213331852-fbb3f174-f49f-424b-97e0-9aef442c524a.mov
https://user-images.githubusercontent.com/20554850/213332527-944909b6-b8e0-4838-8427-c39e33cc9270.mov

fix: reuse comparePoint to decide dragging direction during native selection

---

packages/blocks/src/components/blockhub.ts

1. Assign font-family for blockHub
2. fix menu padding
Before:
After:
Known issues: blockHub should adapt dark mode

fix: add font family for blockHub & fix menu padding

---

packages/blocks/src/embed-block/embed-block.ts
packages/blocks/src/embed-block/image/image-block.ts

Fixes #285 
Console warning message:
> reactive-element.ts:76 Element **affine-embed** scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.
/cc @DiamondThree

fix: embed component lifecycle warning

---

.github/workflows/browser-compatibility.yml
packages/store/playwright.config.ts
playwright.config.ts

The first step for #335 .
The naming is a bit ugly somehow. The prefix `TEST_` is to avoid collision with playwright's official environment naming convention(in the future). Any good naming ideas are welcomed.

ci: add browser compatibility cron job test

---

packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/slash-menu/index.ts
packages/blocks/src/components/slash-menu/slash-menu-node.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
packages/blocks/src/page-block/utils/container-operations.ts
packages/global/index.d.ts
packages/global/src/config/consts.ts
packages/playground/src/components/debug-menu.ts
packages/playground/src/utils.ts
packages/store/src/store.ts

This PR:
- Enabled the slash menu in the playground by default.
- Adds append-flavor slash flag (with URL param `?slash=1`). In this mode, pressing enter will create a new block.
- Simplifies `updateBlockType`.

feat: add append-flavor slash menu behavior

---

.github/workflows/browser-compatibility.yml

fix the wrong target name which made https://github.com/toeverything/blocksuite/actions/runs/3972260634/jobs/6809980658 fail.
```ts
type BrowserName = 'chromium' | 'firefox' | 'webkit';
```
---
And also add `fail-fast: false` to see all matrix results as some jobs will constantly fail at the moment.

ci: correct browser name

---

.github/workflows/browser-compatibility.yml

no `inputs` for cron type job, use the default value.

ci: add params for cron job

---

.github/workflows/browser-compatibility.yml
.npmrc
packages/store/package.json
pnpm-lock.yaml

1. use pnpm's shell-emulator to replace usage of `cross-env` for Windows. https://pnpm.io/cli/run#shell-emulator
2. add missing process env for CI by using `environment` property.

refactor: clean usage for cross-env

---

packages/global/src/debug.ts
tests/utils/actions/misc.ts

Fix safari doesn't support lookbehind
breaks in Safari: Invalid regular expression: invalid group specifier name
See https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group
---
Suppress firefox warning
see https://github.com/quilljs/quill/issues/2030

fix: browser compatibility issues

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/surface-block/surface-model.ts
packages/phasor/src/surface.ts
packages/playground/examples/canvas/main.ts

This avoids the conflict between the `surface` entity and the `ySurfaceContainer` that holds the elements.
We don't do
``` ts
const container = new SurfaceContainer();
```
Instead, we do
``` ts
const surface = new SurfaceManager();
```

refactor(phasor): `SurfaceContainer` -> `SurfaceManager`

---

packages/blocks/src/components/format-quick-bar/index.ts

Just realized that it's part of the error mentioned in #749
~~I will try to fix both errors in this PR. Draft first~~ 😄 
The selection is so complex that I have to move it to another PR.
---
closes #829 
In Edgeless mode, blurring the frame will cause the selection type to be `None`.
This PR handled the case.
Another way is to only allow showing the quick bar when the selection type is `Range`.
Let me know if you want it to be this way.
```js
if(selection?.type !== 'Range') {
```

fix: handle None selection in format quick bar

---

packages/blocks/src/components/slash-menu/slash-menu-node.ts

With `slash_append_flavor` flag, the content after slash symbol should be insert to next block

fix: update append behavior

---

packages/store/src/base.ts
packages/store/src/utils/utils.ts
packages/store/src/workspace/page.ts
packages/store/src/workspace/workspace.ts

In #859 we removed the class-based model, calling the new model instances "state"s. Compared to `props`, This introduces a new concept in BlockSuite:
``` ts
// Here the { title: 'hello' } is *props* in our API definition
page.updateBlock(pageModel, { title: 'hello' })
pageModel // model state
```
We were hoping to replace "props" with "state", making the concepts in our system more consistent. However, after some quick experiments, I found it hard to rename "props" since we have already used it in YBlock fields (.e.g., `"prop:title"`).
So the other option is to rename the `State` concept with `Props`, ensuring they are essentially the same thing.
/cc @Himself65

refactor(store): `model.state` -> `model.props`

---

.github/workflows/browser-compatibility.yml
BUILDING.md
packages/store/playwright.config.ts
playwright.config.ts

This PR brings the `BROWSER` config to non-CI environment, with documentation helping new contributors deal with compatibility issues.
/cc @fi3ework

test: add BROWSER env config to local environment

---

packages/blocks/src/__internal__/utils/selection.ts
tests/selection.spec.ts

Fixes:
* should select full text of the first block
* missing `pageBlock.selection`
https://user-images.githubusercontent.com/27926/215281809-af62eb30-b39f-4732-949a-cd713ffbe7b1.mov

fix: should select full text of the first block in edgeless mode

---

packages/blocks/src/components/blockhub.ts

1. Make card list disappear when hovering on close button
https://user-images.githubusercontent.com/20554850/215694186-bac5ce5e-7b9f-46be-ae11-4c9cd362bf6f.mov
2.  Make hover tips disappear when after starting dragging from blank line button
https://user-images.githubusercontent.com/20554850/215694590-80796b3e-b50e-4531-90a0-4a05d2bfcdaf.mov

fix: block hub card list hover state & hovertip style

---

packages/blocks/src/__internal__/utils/gesture.ts
packages/blocks/src/__internal__/utils/hotkey.ts
packages/blocks/src/code-block/code-block.ts

1. disabled the mouse handlers in `HTMLInputElement`, (It seems ok for the moment
, as we don't deal with complex mouse events in input tag). This can make mouse event in language select input and image caption correct
https://user-images.githubusercontent.com/20554850/215765803-56e88869-f98a-4889-9529-36ce07a9282a.mov
2. a bug fix, now can close language select list when clicking lang button

refactor(blocks): disable custom gesture handler on `HTMLInputElement`

---

packages/blocks/src/components/slash-menu/slash-menu-node.ts
packages/global/index.d.ts
tests/slash-menu.spec.ts

When the search item is empty, the slash menu will be hidden temporarily, and if the following key is the backspace key, the slash menu will be reopen

feat: tweak slash menu show behavior

---

packages/blocks/src/__internal__/rich-text/keyboard.ts
packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/utils.ts
tests/paragraph.spec.ts
tests/selection.spec.ts

- Refactor `getNextBlock` and `getPreviousBlock`
- Skip `affine:frame`/`affine:page`
- Sunset `getSiblingsById`/`getNextSiblingById`/`getPreviousSiblingById`
- Add new utility function `focusTitle(offset)`
- Other misc changes
https://user-images.githubusercontent.com/18554747/215123880-295c82db-35db-4a03-a495-3d1a21108dce.mov

feat: support `focusTitle` & skip container in `getNextBlock`

---

package.json
patches/quill@1.3.7.patch
pnpm-lock.yaml

In quill 1.3.7, keyboard bindings cannot get the event, this has led to us having to handle the event on quill and hotkey at the same time. Using `event.stopPropagation()` in quill bindings to skip the hotkey handler will reduce the mental overhead of development
See also https://github.com/quilljs/quill/commit/90269c7af9fc03e46be257490b2b0aec85d9ecc7

fix: add event to quill keyboard context

---

.github/workflows/cancel.yml

> Error: .github#L1
> the `uses' attribute must be a path, a Docker image, or owner/repo@ref
Related to https://github.com/styfle/cancel-workflow-action/pull/184
But I still think that using the native [concurrency](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/) property to cancel workflows is enough
Ref https://github.com/toeverything/blocksuite/pull/962#issuecomment-1414732803

fix: add version to cancel workflow

---

packages/global/src/utils/signal.ts

> Warning: If a listener is registered twice, one with the capture flag set and one without, you must remove each one separately. Removal of a capturing listener does not affect a non-capturing version of the same listener, and vice versa.
See https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

fix: remove event listener with options

---

packages/blocks/src/components/blockhub.ts
packages/editor/src/components/editor-container.ts
packages/global/src/utils/signal.ts

- Add `Signal.disposableListener`
- Remove incorrect `Signal.fromEvent` usage
ref https://github.com/toeverything/blocksuite/pull/1025#issuecomment-1418852914

refactor: `Signal.fromEvent` -> `Singal.disposableListener`

---

packages/blocks/src/code-block/code-block.ts
packages/blocks/src/components/blockhub.ts
packages/editor/src/utils/editor.ts
packages/global/src/utils/signal.ts

1. Use `Signal.disposableListener`. Upstream PR: #1114
2. Use `EditorContainer` as `mouseRoot` in place of `document`, on which to listen `dragover`, `drop` event

refactor: use disposable style event listener in blockHub

---

packages/blocks/src/__internal__/rich-text/keyboard.ts
packages/blocks/src/__internal__/rich-text/quill-keyboard.ts

Upstream of https://github.com/toeverything/blocksuite/pull/630
Workaround for https://github.com/quilljs/quill/issues/1975 in quill v1.3.7

refactor: use keyboard event key instead of keyCode

---

packages/blocks/src/__internal__/rich-text/bracket-complete.ts
packages/blocks/src/__internal__/rich-text/keyboard.ts
tests/hotkey.spec.ts

fix https://github.com/toeverything/AFFiNE/issues/632
~~but incorrect in CJK input method.~~
~~It may also fail on other keyboard layouts.~~
~~Block by https://github.com/quilljs/quill/issues/1975~~
It does not work with multiple block selection now

feat: support bracket autocomplete for native range selected text

---

packages/blocks/src/components/link-popover/link-popover.ts
packages/blocks/src/components/slash-menu/config.ts
packages/blocks/src/components/slash-menu/slash-menu-node.ts
packages/blocks/src/page-block/default/utils.ts
tests/slash-menu.spec.ts

Fix #1123 #1125 
- Add divider to slash menu
- Support uses ArrowLeft to select the category
- Filter Code/Link from slash menu
- Use disposable group

fix: update slash menu

---

packages/blocks/src/__internal__/utils/types.ts
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/page-block/default/utils.ts
packages/editor/src/managers/clipboard/copy-cut-manager.ts
packages/editor/src/managers/clipboard/paste-manager.ts
tests/code.spec.ts
tests/utils/actions/misc.ts

This PR updates the clipboard support for code block:
* Use menu copy button
* When paste inside the code block, perceptually copying only the text
* When paste outside the block, perceptually copying the block and inserting a new block after the current block
* Use cv shortcut keys
* Behavior inside and outside the code block are the same, only copy the text
close #1128
https://user-images.githubusercontent.com/20554850/218432617-b4683a0f-078d-472b-a610-3531e144cc4c.mov

feat(blocks): optimize clipboard support for code block

---

packages/editor/src/managers/clipboard/copy-cut-manager.ts

Need to use `select()` to focus on the temp element, so that the copy event can fire on it, trigging corresponding event handler
Upstream PR: #1153

fix: focus temp element during copy

---

packages/playground/src/components/debug-menu.ts

close: #1227
reference: https://github.com/dataarts/dat.gui/blob/master/API.md#:~:text=If%20true%2C%20GUI,keypress.

fix: disable shortcut "h" to shown/hidden dat.gui css debug menu

---

packages/blocks/src/components/blockhub.ts

https://user-images.githubusercontent.com/20554850/219600665-4fae13b1-5828-4561-b305-f1d9ff3a43d4.mov
https://user-images.githubusercontent.com/20554850/219600680-ac7a1095-32b1-4529-9c78-89ed4450b771.mov

fix: cannot locate insert position through dragging from block hub when page has very many blocks

---

packages/store/src/text-adapter.ts

The `insertList` alway marks `_yText` as `{ split: true }` even if not any update.
https://user-images.githubusercontent.com/18554747/219933347-f5b67471-f462-4c67-a3e5-0a7dba90b64c.mov

fix: extra characters when paste

---

.github/CLA.md
packages/blocks/src/page-block/utils/bind-hotkey.ts
tests/selection.spec.ts

https://user-images.githubusercontent.com/24316656/220421819-ac69eacb-1807-4d46-ac10-903658e4c0e4.mp4
try to fix the above problem, the subtree's blocks are also drawn rects, which is a wrong behavior.

fix: sub selected blocks should not be drawn when pressing tab key

---

packages/blocks/src/components/blockhub.ts

close https://github.com/toeverything/blocksuite/issues/1298

fix: text overflow when font-family fallback fails until "Hiragino Sans GB"

---

.github/workflows/browser-compatibility.yml

In broswer-compatibilty workflow all tests failed because of not running build command and playwright use vite preview in CI.
And ubuntu webkit environment seems need to add —install-deps options to install OS dep.
But still a lot of test failed.

ci: add build command & OS dependencies options

---

packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/components/drag-handle.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/selection-manager.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
packages/editor/src/components/editor-container.ts
packages/playground/src/components/debug-menu.ts
packages/store/src/utils/utils.ts
packages/store/src/workspace/page.ts
tests/drag.spec.ts
tests/utils/actions/drag.ts

Root cause: the handle was be attached to the parent of `<editor-container />`. However, unless we wrap `<editor-container />` into a relative container without padding, there will be offset issue for handles.
The solution in this pr moves the handle as a child of `<editor-container />` and make `<editor-container />` a relative container. As a result, there are some event issues this time, mainly `mousedown` & `mousemove` events conflicts defined in `initMouseEventHandlers`. Solution here is to stop event propagation in `dragHandle` event handlers accordingly. 
https://user-images.githubusercontent.com/584378/220875092-640c9f75-cc23-46a9-9778-8c53ef116e47.mp4

feat(blocks): drag & drop multiple blocks

---

packages/blocks/src/__internal__/rich-text/bracket-complete.ts
packages/blocks/src/__internal__/rich-text/keyboard.ts
packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
packages/blocks/src/__internal__/utils/block-range.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/__internal__/utils/types.ts
packages/blocks/src/components/button.ts
packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/format-quick-bar/index.ts
packages/blocks/src/components/remote-selection/remote-selection.ts
packages/blocks/src/components/slash-menu/config.ts
packages/blocks/src/index.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/selection-manager.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/edgeless/selection-manager.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
packages/blocks/src/page-block/utils/container-operations.ts
packages/blocks/src/page-block/utils/position.ts
packages/editor/src/managers/clipboard/copy-cut-manager.ts
packages/editor/src/managers/clipboard/utils.ts
packages/playground/src/components/debug-menu.ts
packages/store/src/awareness.ts
tests/code.spec.ts
tests/knwon_issues.spec.ts
tests/selection.spec.ts

- Rename `getCurrentRange` to `getCurrentNativeRange`
- Simpify `BlockRange`
```ts
export type BlockRange = {
/**
* 'Native' for native selection, 'Block' for block selection
*/
type: 'Native' | 'Block';
/**
* Promise the length of models is greater than 0
*/
models: BaseBlockModel[];
startOffset: number;
endOffset: number;
};
```

refactor: reorganize range structure

---

packages/blocks/src/__internal__/utils/block-range.ts
packages/blocks/src/page-block/default/selection-manager.ts
tests/code.spec.ts
tests/selection.spec.ts

Use
```ts
const rects = page.locator('.affine-page-selected-rects-container > *');
await expect(rects).toHaveCount(1);
```

refactor: simplify test

---

package.json
packages/blocks/src/__internal__/rich-text/keyboard.ts
packages/blocks/src/__internal__/rich-text/markdown-convert.ts
packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
packages/blocks/src/__internal__/utils/common-operations.ts
packages/blocks/src/__internal__/utils/components.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/__internal__/utils/std.ts
packages/blocks/src/page-block/default/selection-manager.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
packages/editor/src/managers/clipboard/copy-cut-manager.ts
packages/editor/src/managers/clipboard/paste-manager.ts
packages/global/index.d.ts
packages/global/package.json
packages/global/src/types.ts
packages/global/src/utils.ts
packages/playground/examples/virgo/test-page.ts
packages/store/src/base.ts
packages/store/src/utils/utils.ts
pnpm-lock.yaml

Before:
```ts
// we have a model here
declare const model: BaseBlockModel;
if (matchFlavours(mode, ['affine:page']) {
model.title // 💥  Error! The type of model is still BaseBlockModel. 
}
```
After:
```ts
if (matchFlavours(model, ['affine:page'] as const) {
//                        ^ trade off here, we have to use `as const` to generate the tuple
model.title // 🚀 Works! The type of model is PageBlockModel
}
// What will happen for multiple flavours?
if (matchFlavours(model, ['affine:code', 'affine:paragraph'] as const) {
model // 🔮 CodeBlockModel | ParagraphModel
}
```

feat: typed `matchFlavours` utility function

---

packages/blocks/src/__internal__/utils/block-range.ts
packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/format-quick-bar/index.ts
packages/blocks/src/page-block/default/selection-manager.ts
packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
packages/blocks/src/page-block/utils/position.ts
tests/format-quick-bar.spec.ts

When selection convert from native range to block selection, the format bar should not throw error

fix: format bar should follow selection convert

---

packages/blocks/src/__internal__/rich-text/markdown-convert.ts
packages/blocks/src/code-block/utils/code-laguages.ts

Optimize the behavior of creating code block in BlockSuite with markdown shortcut.
The problem:
😱 
```markdown
|'''typescript | -> JavaScript
|'''TypeScript| -> JavaScript
|'''java | -> JavaScript
|'''html | -> JavaScript
|'''cpp | -> JavaScript
```

feat: case-insensitive matching in code block language shortcut

---

packages/blocks/src/__internal__/utils/components.ts
packages/editor/src/components/editor-container.ts
packages/playground/src/data/index.ts
tests/utils/actions/misc.ts

Fix https://github.com/toeverything/blocksuite/issues/1225
When creating an editor without adding a page block immediately, the `affine-default-page` component may not receive a model, which is unexpected.

fix: should render nothing when no page model

---

packages/blocks/src/__internal__/rich-text/rich-text.ts

Related to #1258
Mouse move before (using http://localhost:5173/?init=preset):
Mouse move after:

perf: reduce rich text re-render

---

packages/blocks/src/components/blockhub.ts
packages/blocks/src/page-block/default/selection-manager.ts
packages/blocks/src/page-block/default/utils.ts

The  `top` value of Rect calculated by `Element.getBoundingClientRect()`  is neither the same as `PageY` nor `ClientY` in `MouseEvent`.  [It represent the distance from the element top to the top of viewport](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect#scrolling), when the element is upside of the viewport, it's negative, and When the element is downside of the viewport, it's bigger than `window.innerHeight`.
**But when the Element is in the viewPort, the `top` can be compared with `clientY`**. This PR used this point, to first filter only the blocks in the viewPort. Then we can always use `clientY` in `MouseEvent` when comparing.
Currently our binary search uses `y >= detectRect.top && y <= detectRect.bottom` to decide current cursor falls into a block. …

fix(blocks): missing target when mouse fall into between two blocks and Y axis wrongly calculated

---

.github/workflows/build-and-test.yaml
packages/global/src/utils.ts
playwright.config.ts

Make testing fast again
Code coverage is normal
> `<job_id>.strategy.fail-fast` is set to true, GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails. This property defaults to true.
References
https://timdeschryver.dev/blog/using-playwright-test-shards-in-combination-with-a-job-matrix-to-improve-your-ci-speed#github-workflow-caching

ci: run tests in parallel

---

packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
tests/edgeless.spec.ts

Fix the following problem(when we select the first elipse, move to the second eplise, and try to drag on the second eplise, the first elipse is dragged):
https://user-images.githubusercontent.com/24316656/222884616-767a90c4-ed39-457f-8567-83ecc00738bd.mp4

fix: should cancel when select selected point outside the selected element

---

packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
tests/edgeless.spec.ts

Related to #1485
fix:
> The shape element should not move when the selected state is inactive.

feat: shape element should not move when the selected state is inactive

---

packages/blocks/src/__internal__/utils/gesture.ts
packages/blocks/src/__internal__/utils/types.ts
packages/blocks/src/page-block/default/components.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
packages/blocks/src/page-block/default/selection-manager/embed-resize-manager.ts
packages/blocks/src/page-block/default/selection-manager/utils.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
tests/selection.spec.ts

part of #1480
* Extract some methods that doesn't depend heavily on `this` as utils
* Naming: `frameSelectionRect` -> `draggingArea`
* Naming: `slots.nativeSelection` -> `slots.toggleNativeSelection`
* Fix typos

refactor: remove redundant selection manager fields

---

packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/components/blockhub.ts
packages/blocks/src/list-block/list-block.ts
packages/blocks/src/page-block/default/components.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
packages/blocks/src/page-block/default/selection-manager/embed-resize-manager.ts
packages/blocks/src/page-block/default/selection-manager/utils.ts
packages/editor/src/utils/editor.ts

part of #1480
* Unify `slots` pattern (used for subscribe effects)
* Expose clarified `setSelectedBlocks` API
* Extract class methods as utils

refactor: extract `setSelectedBlocks` and slot effects

---

packages/blocks/src/page-block/default/default-page-block.ts
packages/virgo/src/virgo.ts

Try to fix #1498 but not sure if it work well in AFFiNE.
cc @Himself65

fix(virgo): container should be non-editable when in read-only mode

---

packages/blocks/src/components/block-hub.ts
packages/editor/src/utils/editor.ts

This PR:
* Extracts methods as function components.
* Lifts some constants.
* Switches to using `slots` property.
* Removes unused signal.
* Removes unused template.
/cc @thorseraq @lawvs

refactor: extract block hub templates

---

packages/blocks/src/code-block/code-block.ts
packages/blocks/src/code-block/components/code-block-option.ts
packages/blocks/src/code-block/components/code-option.ts
packages/blocks/src/components/button.ts
packages/blocks/src/components/format-quick-bar/index.ts
packages/blocks/src/components/portal.ts
packages/blocks/src/page-block/default/components.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/index.ts
tests/code.spec.ts

Fix https://github.com/toeverything/blocksuite/issues/1513
Part of https://github.com/toeverything/blocksuite/issues/1480
CodeOption should be maintained by the code block itself

refactor: move `codeBlockOption` to code block

---

packages/blocks/src/code-block/code-block.ts
packages/blocks/src/components/block-hub.ts
packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/slash-menu/slash-menu-node.ts
packages/editor/src/components/editor-container.ts
packages/global/src/utils.ts
packages/global/src/utils/disposable.ts
packages/global/src/utils/slot.ts

This is not reverting #1114, but using the `Slot.fromEvent` the right way:
``` ts
// Wrong
disposables.add(
Slot.fromEvent(document, 'click').on(myHandler)
)
// Correct
disposables.add(
Slot.fromEvent(document, 'click', myHandler)
)
```
So that we don't have to introduce the `disposableListener` concept, which is hard to comprehend IMO.
This also refactors the implementation, removes the ambiguous `DisposeLogic` type.
Let's make this happen and see what's the next step for #1518.

refactor: `Slot.disposableListener` -> `Slot.fromEvent`

---

packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-tool-button.ts
tests/edgeless.spec.ts

fix(edgeless): brush menu cannot be closed after switch editor mode

---

packages/blocks/src/components/drag-handle.ts
packages/blocks/src/page-block/default/default-page-block.ts

- transform is faster than left/top because it does not trigger layout shift
- set `state` value will trigger update and thus `requestUpdate` should not be needed (fix some issues in https://github.com/toeverything/blocksuite/issues/1258)
After the changes above, heavy example should be much smoother.
I also found that block updating rendering in master branch is dependent on mousemove event, which seems not right.
See the video recording I did in the latest master branch. By calling `page.addBlockByFlavour('affine:frame', {})`, the new `affine-frame` will not be added to DOM immediately, but will after I move my cursor in the page.
https://user-images.githubusercontent.com/584378/223318539-1e07e67e-43f5-4434-89f8-8042d3ad627c.mp4 …

perf: use transform-based layout & remove redundant `requestUpdate`

---

packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-menu.ts
packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts

fix: drawing content should not cover the brush menu

---

packages/blocks/src/components/slash-menu/slash-menu-node.ts

close: #1574
`ele.scrollIntoViewIfNeeded()`: the element will be aligned so it is **centered** within the visible area of the scrollable ancestor.
/cc @lawvs

fix: remove redundant `scrollIntoViewIfNeeded`

---

packages/blocks/src/__internal__/utils/common-operations.ts

error message:
The dividing line does not contain text content by default.

fix: fix the console error when dragging the dividing line

---

packages/blocks/src/components/slash-menu/index.ts
tests/slash-menu.spec.ts

The issue is that vEditor does not synchronize its state vRange when deleting search string.
https://user-images.githubusercontent.com/24316656/224102751-1d580025-d50c-450d-b43f-a51b9b71f7e0.mp4

fix: date & time string can not be inserted using the slash menu

---

packages/blocks/src/__internal__/rich-text/markdown-convert.ts
packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
packages/blocks/src/__internal__/utils/common-operations.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/list-block/utils/get-list-icon.ts

This PR adds async version of query functions to avoid the ambiguity `requestAnimationFrame` call when updating dom.

refactor: add async query for dom mutation scenario

---

packages/blocks/src/__internal__/rich-text/keyboard.ts
packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/code-block/components/lang-list.ts
packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/format-quick-bar/index.ts
packages/blocks/src/components/slash-menu/config.ts
packages/blocks/src/components/slash-menu/index.ts
packages/blocks/src/embed-block/embed-block.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/utils/container-operations.ts
packages/virgo/src/components/virgo-line.ts
packages/virgo/src/virgo.ts
tests/paragraph.spec.ts

This PR add two slots for virgo:
1. `updated`: this slot will be emitted when dom updated.
2. `rangeUpdated`: this slot will be emited when vRange is applied to dom as range.
And two API introduces:
1. `onModelElementUpdated`: Run a callback after the element of model is updated. This is useful when you want to get the updated DOM after changing a model. For example, calculate the dom boundary rect.
2. `onModelTextUpdated`: Run a callback after the text of model is updated. This is useful when you want to make some dom changes after changing the yText. For example, restore the selection.

feat: add slots for virgo to inspect update

---

packages/blocks/src/code-block/code-block.ts

When highlighter is loaded slowly, the cursor will jump to start of the code block and cannot continue typing.
Before:
https://user-images.githubusercontent.com/10047788/224532332-910c25d1-f698-4039-b1e5-b625683da0a8.mov
<br />
<br />
After:
https://user-images.githubusercontent.com/10047788/224532334-1a64e716-3b2b-4e01-b25b-29a6bb69a9f4.mov

fix(blocks): cursor in codeblock moves to start

---

packages/blocks/src/components/format-quick-bar/button.ts

fix https://github.com/toeverything/blocksuite/issues/1639
Root cause is that on Safari without preventDefault the browser still change selection on click, even if the mousedown event is stopped.

fix(format-bar): safari compatibility

---

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
tests/list.spec.ts
tests/utils/actions/misc.ts
tests/utils/asserts.ts

Before: 
https://user-images.githubusercontent.com/10047788/224622011-b87bbd9f-6e86-4403-998a-82f284ff9868.mov
<br />
<br />
After:
https://user-images.githubusercontent.com/10047788/224622033-ca29b095-57f7-4008-9496-ac24a1b53ef4.mov

fix(blocks): numbered list prefix won't update when previous sibling changed

---

packages/blocks/src/__internal__/rich-text/keyboard.ts
tests/code.spec.ts

The unexpected behavior occurs when trying to use `Tab` to indent a line between two lines of texts.
https://user-images.githubusercontent.com/10047788/224629844-23f17395-d655-4c37-9364-5959ec693bcd.mov

fix(blocks): code block indent incorrectly

---

packages/blocks/src/__internal__/rich-text/keyboard.ts
packages/blocks/src/__internal__/rich-text/link-node/create-link.ts
packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
packages/blocks/src/__internal__/utils/common-operations.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/components/slash-menu/config.ts
packages/blocks/src/components/slash-menu/index.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/utils/container-operations.ts
packages/editor/src/managers/clipboard/paste-manager.ts

Replace `getRichTextByModel` with `getVirgoByModel`.
Update the following pattern
```ts
// Before
const richText = getRichTextByModel(model);
assertExists(richText);
const { vEditor } = richText;
assertExists(vEditor);
// After
const vEditor = getVirgoByModel(model);
assertExists(vEditor);
```

refactor: replace `getRichTextByModel` with `getVirgoByModel`

---

packages/blocks/src/__internal__/utils/components.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/playground/examples/virgo/test-page.ts
tests/utils/actions/misc.ts

This PR fix a few Safari compatibility issues found in Safari test, mainly related to `prop:xywh` inconsistency when comparing yDoc json and make sure the virgo tests can work in Safari.

fix(editor): some safari compatibility issues

---

packages/blocks/src/page-block/default/selection-manager/utils.ts
packages/blocks/src/page-block/default/utils.ts

1. click a image, `selection.state.type` switch to `embed`
2. drag-and-drop image block, `selection.state.type` switch to `block`
The following methods are all for `block`:
https://github.com/toeverything/blocksuite/blob/9df30f433795a314367a271526c66b106b149d00/packages/blocks/src/page-block/default/selection-manager/utils.ts#L144-L148
I think we can set the state after the drag and drop to block first to avoid confusion.

refactor(selection): keep setSelectedBlocks logic simple

---

packages/blocks/src/__internal__/content-parser/index.ts
packages/blocks/src/__internal__/rich-text/keyboard.ts
packages/blocks/src/__internal__/rich-text/rich-text.ts
packages/blocks/src/__internal__/service.ts
packages/blocks/src/__internal__/service/index.ts
packages/blocks/src/__internal__/service/keymap.ts
packages/blocks/src/__internal__/utils/types.ts
packages/blocks/src/code-block/code-service.ts
packages/blocks/src/divider-block/divider-service.ts
packages/blocks/src/embed-block/embed-service.ts
packages/blocks/src/frame-block/frame-service.ts
packages/blocks/src/list-block/list-service.ts
packages/blocks/src/models.ts
packages/blocks/src/page-block/page-service.ts
packages/blocks/src/paragraph-block/paragraph-service.ts
packages/global/src/config/consts.ts
packages/global/src/types.ts
tests/utils/actions/keyboard.ts

Currently, we handle key map all in one file. However, when we have more and more blocks, they have some custom behavior of key map. For example, for code block, the `Tab` and `Shift+Tab` won't be split the whole block. They should indent or unindent the text in block.
Since we already have block level services which can provide methods for blocks. Why don't we just move key map into the services? A block can define it's own key map to override the default block level key map or add new key map.
```ts
class CodeBlockService extends BaseService {
override defineKeymap(block, virgo) {
const defaultKeymap = super.defineKeymap(block, virgo);
return {
...defaultKeymap,
...myOverrideKeymap,
}
}
}
```

feat: add support for block level key map

---

packages/blocks/src/__internal__/utils/gesture.ts
tests/format-quick-bar.spec.ts

Double click format button should not hide format bar (Blame to https://github.com/toeverything/blocksuite/pull/1530)
Co-authored-by: Mirone <Saul-Mirone@outlook.com>

fix: dbclick format bar should not hide

---

packages/blocks/src/__internal__/rich-text/keyboard.ts
packages/blocks/src/__internal__/utils/std.ts
packages/blocks/src/components/slash-menu/slash-menu-node.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
packages/global/src/config/consts.ts
tests/slash-menu.spec.ts

- Remove unused code from `keyboard`
- Migrate `_handlenativeKeydown` from `default-page-block` to `bind-hotkey`
- Filter out the controlled events from the slash menu listener

refactor: migrate nativeKeydown to hotkey

---

packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
packages/playground/src/components/debug-menu.ts

fix the following problem of the playground debug menu
https://user-images.githubusercontent.com/24316656/225934558-a5714fd3-64fe-4f70-9533-66f6bb707438.mp4
The behavior do not consist with the handler of undo/redo key
https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/page-block/utils/bind-hotkey.ts#L69
```ts
hotkey.addListener(HOTKEYS.UNDO, e => {
if (page.canUndo) clearSelection(page);
page.undo();
});
hotkey.addListener(HOTKEYS.REDO, e => {
if (page.canRedo) clearSelection(page);
page.redo();
});
```

fix(playground): clear selection on clicking undo/redo buttons

---

packages/blocks/src/code-block/affine-code-line.ts
packages/blocks/src/code-block/utils/highlight-cache.ts

refactor(blocks): add cache for highlight in code-block

---

packages/store/src/__tests__/workspace.unit.spec.ts
packages/store/src/workspace/page.ts
packages/store/src/workspace/workspace.ts
tests/utils/asserts.ts

We use the term "subpage" instead of "sub-page". Naming suggestion from GPT:
> Both "subpage" and "sub-page" are commonly used and accepted spellings, and both convey the same meaning.
> However, if you are using either of these terms in the context of website design or development, it is worth noting that the convention in web design is to use "subpage" without a hyphen. This is because hyphens are typically reserved for separating words in URLs and can cause confusion or errors in some web programming languages.
/cc @QiShaoXuan @lawvs @joebeijing

style: unify subpage and slot naming

---

packages/blocks/src/components/drag-handle.ts

fix(drag-handle): height of drag handle line when zooming in/out in edgeless mode

---

packages/playground/examples/canvas/main.ts

Before (by only enabling `'examples/canvas': resolve(__dirname, 'examples/canvas/index.html')` in playground vite config):
```
dist/examples/canvas/index.html            0.73 kB
dist/assets/examples/canvas-9351325d.js  310.65 kB │ gzip: 87.04 kB
```
After
```
dist/examples/canvas/index.html           0.73 kB
dist/assets/examples/canvas-2d7e18b7.js  89.47 kB │ gzip: 28.21 kB
```
70% smaller for phasor-only build.

perf(phasor,playground): optimize phasor example build size

---

packages/blocks/src/page-block/edgeless/toolbar/shape-tool/shape-tool-button.ts

fix #1808 
When clicking the shape button, we should set the default shape mode. Using click away to control the shape panel's visibility.
https://user-images.githubusercontent.com/21084335/226867497-be7cda4e-0d33-434c-b9b5-5608eaabbc8d.mov

fix(edgeless): the edgeless toolbar should not be able to display two submenus

---

packages/blocks/src/__internal__/utils/hotkey.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/hotkey.ts
packages/blocks/src/page-block/edgeless/utils.ts

fix #1827 
When rendering a page or an edgeless view, `setScope` is called to set a unique scope for each view. All hotkeys are then bound to this scope. When a page or an edgeless view is disconnected, all hotkeys registered during the view's lifetime are destroyed.

refactor(edgeless): hotkeys

---

packages/blocks/src/code-block/code-block.ts

fix(blocks): drop-down arrow for code language switching should not be displayed

---

packages/blocks/src/page-block/edgeless/utils.ts
tests/edgeless.spec.ts
tests/utils/actions/edgeless.ts

fix #1862 
* should get baseX and basxY before zooming
* zoom fastly when use mouse

fix(edgeless): when zooming with the mouse, the behavior is not as expected

---

packages/virgo/src/services/event.ts
packages/virgo/src/virgo.ts

This pr make users reuse `defaultHandlers` easily.

refactor(virgo): expose event service

---

packages/blocks/src/__internal__/rich-text/reference-node.ts
packages/blocks/src/__internal__/service/index.ts
packages/blocks/src/components/linked-page/index.ts
packages/blocks/src/components/linked-page/linked-page-popover.ts
packages/blocks/src/components/slash-menu/index.ts
packages/blocks/src/components/slash-menu/slash-menu-node.ts
packages/blocks/src/page-block/utils/const.ts
packages/blocks/src/page-block/utils/container-operations.ts
packages/blocks/src/page-block/utils/position.ts
packages/global/src/config/icons.ts
packages/virgo/src/constant.ts
packages/virgo/src/virgo.ts
tests/slash-menu.spec.ts

- The `getFormat` supports a new `loose` mode
- Hide link action on the balloon bar when selection included reference node
- Remove extra whitespace after reference node
- Make consistent on `updatePosition` between slash menu and liked page popper over

fix: remove extra whitespace after reference node

---

packages/blocks/src/database-block/components/cell-container.ts
packages/blocks/src/database-block/components/column-type/rich-text.ts
packages/blocks/src/database-block/components/edit-column-popup.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/database-block/database-service.ts
packages/global/src/database.ts
packages/playground/src/data/index.ts
packages/store/src/workspace/page.ts

* `updateBlockColumn` -> `updateColumn`
* `setColumnSchema` -> `updateColumnSchema`
* `getBlockColumnBySchema` -> `getColumn`
* `updateColumnValue` -> `convertColumn`
* `deleteBlockColumns` -> `deleteColumn`
* `copyBlockColumnById` -> `copyColumn`
* `schemaId` -> `columnId`
This brings following API surface:
* `ColumnSchema` related:
* `getColumnSchema`
* `updateColumnSchema`
* `deleteColumnSchema`
* `Column` related:
* `getColumn`
* `updateColumn`
* `deleteColumn`
* `copyColumn`
* `convertColumn`
/cc @zqran @Himself65

refactor(database): optimize column related naming

---

packages/blocks/src/database-block/database-block.ts
packages/blocks/src/database-block/database-model.ts

@Himself65 @zqran I suggest we should not writing the `mode` into database block model, it's redundant and changing it will create unnecessary undo/redo actions.

refactor(database): remove `mode` in crdt model

---

packages/blocks/src/__internal__/rich-text/reference-node.ts
packages/blocks/src/__internal__/rich-text/rich-text.ts
packages/blocks/src/__internal__/rich-text/virgo/attribute-renderer.ts
packages/blocks/src/__internal__/rich-text/virgo/types.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/std.ts
packages/blocks/src/__internal__/utils/types.ts
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/list-block/list-block.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/paragraph-block/paragraph-block.ts
packages/editor/src/components/editor-container.ts
packages/playground/src/main.ts
packages/playground/src/utils.ts
packages/store/src/store.ts
packages/store/src/workspace/index.ts
packages/store/src/workspace/workspace.ts

- New `CommonSlots` API
```ts
export type CommonSlots = {
/**
* Emit when the subpage is linked to the current page.
* We show restore subpage from the trash in AFFiNE
*/
onLinkPage: Slot<{ pageId: string }>;
/**
* Emit when the subpage is unlinked from the current page.
* We need to move the subpage to the trash in AFFiNE
*/
onUnlinkPage: Slot<{ pageId: string }>;
// Emit when click reference node
onJumpToPage: Slot<{ pageId: string }>;
};
```
- Add `Slots<T>` to the `BlockHost`
- Implement `CommonSlots` in the `DefaultPageBlockComponent` and `EdgelessPageBlockComponent`
- Forward the `CommonSlots` to the `EditorConintainer` from `DefaultPageBlockComponent` and `EdgelessPageBlockComponent`
- Add `WorkspaceOptions` types
Usages …

feat: expose public slots from editor container

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/change-brush-button.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
packages/blocks/src/page-block/edgeless/components/tool-icon-button.ts
packages/blocks/src/page-block/edgeless/components/utils.ts
packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-tool-button.ts
packages/blocks/src/page-block/edgeless/toolbar/shape-tool/shape-tool-button.ts
tests/edgeless.spec.ts
tests/utils/actions/edgeless.ts

Close https://github.com/toeverything/blocksuite/issues/1845
I had two considerations in fixing this issue:
1. It seems that I can either create a new prop to control whether a tooltip should be displayed or just clear tooltip. I choose the latter because I think the value of tooltip can potentially represent whether it should be displayed. Just like the code written in file:
```ts
${tooltip
? html`<tool-tip inert role="tooltip" tip-position="top" arrow
>${tooltip}</tool-tip
>`
: nothing}
```
2. I create a state to track the state of the popper so that I can request a render when the state changes reactively.

fix: tooltip should be hidden when the submenu list is opened

---

packages/blocks/src/database-block/database-block.ts
tests/database.spec.ts
tests/utils/actions/database.ts
tests/utils/actions/misc.ts

https://user-images.githubusercontent.com/15389209/230251472-77e26da2-9b36-4253-89c2-b5db52e319b4.mov
Database has two buttons to add column:
1. in the last column of the header
2. on the right side of database
When button 1 is shown, button 2 should be hidden.

fix(database): show the add column button on the right side of database correctly

---

packages/playground/src/components/debug-menu.ts

The icon display in dark/light mode is reversed, so fix it.
And add a tooltip like other buttons.

fix: reverse dark mode icon and add tooltip

---

packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/components/block-hub.ts
packages/blocks/src/components/drag-handle.ts
packages/blocks/src/database-block/components/column-header/column-header.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/selection-manager/block-drag-handlers.ts
packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts
packages/blocks/src/page-block/default/selection-manager/native-drag-handlers.ts
packages/blocks/src/page-block/default/selection-manager/preview-drag-handlers.ts
packages/blocks/src/page-block/default/selection-manager/selection-state.ts
packages/blocks/src/page-block/default/selection-manager/utils.ts
packages/blocks/src/page-block/default/utils.ts
packages/blocks/src/page-block/edgeless/create-drag-handle.ts
packages/blocks/src/page-block/edgeless/hotkey.ts
packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
packages/editor/src/utils/editor.ts
tests/selection.spec.ts

https://user-images.githubusercontent.com/27926/230816412-4d19fa98-e633-4966-b5f5-544329351104.mov

feat(selection): support scroll wheel to move dragging blocks

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/utils.ts
packages/editor/src/components/editor-container.ts
packages/phasor/src/renderer.ts
packages/playground/src/components/debug-menu.ts

https://user-images.githubusercontent.com/21084335/231506153-71ad5765-2f4a-4a30-95a1-e57bdd36f0d5.mov

feat(edgeless): optimize background grid

---

packages/blocks/src/page-block/edgeless/components/resize-manager.ts
packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts

A small improvement, like Miro, is that when the shift key is held down:
1. When creating a shape, the shape created is a regular polygon
2. When resizing, keep the aspect ratio

feat: keep ratio when press shift to create shape

---

packages/react/examples/next/src/components/PageManger.tsx

This PR removes the usage of the deprecated `onClick` and replaces it with `onPress`.
See [`nextui/Button` document](https://nextui.org/docs/components/button#apis).

fix: use `onPress` rather than deprecated `onClick` for nextui components

---

packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/format-quick-bar/index.ts
tests/format-quick-bar.spec.ts

Close https://github.com/toeverything/blocksuite/issues/2005
And fix the incorrect test. 
In the following picture, you can see the correct left position for quick format bar should be 377 instead of 395. It is wrong before I fix this problem.
The key point is "convert-to-database" button is shown when range type is block(https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/page-block/utils/const.ts#L143). 
But the range type is changed asynchronous after the render, and before the next render which is caused by update position there is no another render. The following picture shows that the quick bar has already been changed but the database button is not shown.
So when the update position function is called, it used the incorret dom to calculate. …

fix(format-bar): update state on change in keyboard selection

---

packages/blocks/src/components/slash-menu/slash-menu-popover.ts
packages/blocks/src/components/utils.ts
tests/slash-menu.spec.ts

closes #2052 
This PR added support for using `Ctrl/Cmd+P` and `Ctrl/Cmd+N` to move in the slash menu
And it also fixed the usage of `Shift+←→` when the slash menu is presented.
These changes will improve the fluency of user input as it allows other hotkeys to pass through and fixed a few edge cases.

feat: support Ctrl+P/N to move in slash menu popover

---

packages/virgo/src/utils/transform-input.ts
tests/basic.spec.ts

Fix #2138 , but there is a small problem, `Intl.Segmenter` is not compatible with Firefox, one solution to use [polyfill](https://github.com/surferseo/intl-segmenter-polyfill), another solution is to use lodash directly, which one do you prefer?

fix: delete emoji completely

---

packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
tests/edgeless.spec.ts

In this pr, skip the test for auto-remove empty text frames. The current test does not match the previous design and is causing issues.
https://github.com/toeverything/blocksuite/pull/1712/files

fix(edgeless): auto remove empty text frame

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts

Two fingers on the trackpad.
https://user-images.githubusercontent.com/27926/232663272-e1119b5f-fe54-444e-a3f8-8313beedcf47.mov
https://user-images.githubusercontent.com/27926/232663404-c7e031bc-1bcd-4bab-9ce1-692dd9f7dd16.mov

fix(drag-handle): should be hidden when moving canvas in edgeless

---

packages/virgo/src/services/event.ts

Fixes: https://github.com/toeverything/blocksuite/issues/1901
This PR recompute vRange before each 'beforeinput' trigger
If the problem can be resolved. Then we can consider how to optimize the performance of this code.

fix: the vRange is wrong in some cases

---

packages/blocks/src/__internal__/content-parser/parse-html.ts

Fixes: https://github.com/toeverything/blocksuite/issues/2143
Nodes that do not match will be treated as plain text.

fix: incorrect behavior when paste code from GitHub

---

packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts
tests/edgeless/frame.spec.ts

fix(edgeless): should not add text when double click toolbar button

---

packages/store/src/__tests__/indexer.unit.spec.ts
packages/store/src/workspace/indexer/base.ts
packages/store/src/workspace/meta.ts

- Remove warn when page observer duplicated
- Deprecated subpageIds
- Clean test import

fix: test flaky

---

packages/virgo/src/utils/guard.ts
packages/virgo/src/utils/point-conversion.ts

https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition
The code
```ts
a.compareDocumentPosition(b) === Node.DOCUMENT_POSITION_CONTAINED_BY
```
means that `a` is an ancestor of `b`, so `a` inside `b` may need implemented by 
```ts
b.compareDocumentPosition(a) === Node. DOCUMENT_POSITION_CONTAINED_BY
```
---
btw:
The magic number 20 should be refactored to 
```ts
Node.DOCUMENT_POSITION_CONTAINED_BY | Node.DOCUMENT_POSITION_FOLLOWING
```
I'm not sure what this code does, it just improves readability

fix: `compareDocumentPosition` usage

---

packages/blocks/src/page-block/utils/bind-hotkey.ts

For some browsers, such as Arc. `<Mod+z>` will trigger the browser shortcuts.

fix(blocks): prevent default browser behavior for undo/redo

---

packages/blocks/src/__internal__/rich-text/virgo/attribute-renderer.ts
tests/linked-page.spec.ts

Close https://github.com/toeverything/blocksuite/issues/2136
Problem is that same attribute text nodes will be merged in yjs in delta mode(https://github.com/toeverything/blocksuite/blob/master/packages/virgo/src/services/delta.ts#L159). We should handle this case.
```js
yText.insert(0, ' ', { type: 'LinkedPage', pageId: 'page0' });
yText.insert(0, ' ', { type: 'LinkedPage', pageId: 'page0' });
console.log(yText.toDelta())
/**
[
{ insert: '  ', attributes: { type: 'LinkedPage', pageId: 'page0' } }
]
*/
```

fix(link): consecutive identical reference nodes should not be merged

---

packages/blocks/src/__internal__/content-parser/file-exporter/exporter-style.ts

fix[#2228 ](https://github.com/toeverything/blocksuite/issues/2228)

fix: exported html content color

---

packages/blocks/src/__internal__/utils/gesture/gesture.ts
packages/blocks/src/__internal__/utils/gesture/index.ts
packages/blocks/src/__internal__/utils/gesture/recognizer.ts
packages/blocks/src/__internal__/utils/gesture/selection-event.ts
packages/blocks/src/__internal__/utils/gesture/utils.ts
packages/blocks/src/__internal__/utils/index.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/database-block/components/column-header/column-move/index.ts
packages/blocks/src/database-block/components/toolbar/index.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/page-block/default/components.ts
packages/blocks/src/page-block/default/selection-manager/utils.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts
packages/blocks/src/page-block/edgeless/components/resize-handles.ts
packages/blocks/src/page-block/edgeless/components/resize-manager.ts
packages/blocks/src/page-block/edgeless/components/single-connector-handles.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts
packages/blocks/src/page-block/edgeless/utils.ts
packages/blocks/src/paragraph-block/paragraph-block.ts

Using pointer events instead of mouse events for mobile development to achieve better compatibility

feat(edgeless): switch to `PointerEvent` for mobile compatibility

---

packages/blocks/src/__internal__/service/json2block.ts

Closes #2334 
Before:
After:
`focusedBlockModel` has been deleted.

fix(blocks): paste issue causing empty single-line block to not focus

---

packages/blocks/src/__internal__/rich-text/keyboard.ts

On German keyboards, you have to press "Option" + "L" in order to get "@". This PR fixes it, by setting "altKey" (this seems to be the option key on Mac) to null there

fix: linked page keyboard shortcut not working on German keyboards

---

packages/blocks/src/__internal__/theme/theme-observer.ts

this pr will fix:
https://github.com/toeverything/AFFiNE/issues/2141
previously `_cssVariables` won't have a value until theme changed

fix: init _cssVariables

---

packages/blocks/src/database-block/table/components/toolbar/toolbar.ts

Wrong style, should be hidden here:

fix(database): style of search input

---

packages/editor/src/components/editor-container.ts

When creating multiple editors dynamically, the content could be missing
Upstream: https://github.com/toeverything/blocksuite/pull/2406

fix: cleanup active editor when disconnected

---

packages/blocks/src/__internal__/content-parser/index.ts
packages/playground/src/components/debug-menu.ts

We are writing documentation for export API, so this would better fit our convention.
/cc @Himself65 for bump in AFFiNE (`onExportHtml` -> `exportHtml`) next time.

refactor: switch to `exportHtml` and `exportMarkdown`

---

packages/blocks/src/__internal__/content-parser/parse-html.ts
packages/blocks/src/__internal__/rich-text/markdown-convert.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/code-block/code-model.ts
packages/blocks/src/code-block/code-service.ts
packages/blocks/src/code-block/components/lang-list.ts
packages/blocks/src/code-block/utils/code-languages.ts
packages/blocks/src/code-block/utils/consts.ts
tests/block-hub.spec.ts
tests/code.spec.ts

Fix https://github.com/toeverything/blocksuite/issues/2430
- Sort language by popularity
- Use `BUNDLED_LANGUAGES` from the `shiki`
- Query language alias from the `BUNDLED_LANGUAGES`
https://github.com/toeverything/blocksuite/assets/18554747/4b813e16-3739-47dc-adbb-7437eae5279e

refactor: code language search

---

packages/blocks/src/__internal__/utils/hotkey.ts
packages/blocks/src/page-block/default/selection-manager/default-selection-manager.ts

Fix https://github.com/toeverything/blocksuite/issues/2459

fix: ignore input event in code language filter

---

packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/blocks/src/components/slash-menu/config.ts
packages/blocks/src/components/slash-menu/slash-menu-popover.ts

Fix https://github.com/toeverything/blocksuite/issues/2528
- Hide unregister flavour in the slash menu and the format bar

fix: hide unregister flavour

---

packages/blocks/src/components/format-quick-bar/format-bar-node.ts
packages/global/src/config/consts/block-hub.ts
tests/hotkey.spec.ts

Fix https://github.com/toeverything/blocksuite/issues/2577

fix: hide divider in balloon toolbar

---

packages/blocks/src/page-block/edgeless/components/single-connector-handles.ts

before
https://github.com/toeverything/blocksuite/assets/50226652/cd889b83-c381-4cd6-b0d7-202c383ca655
after
https://github.com/toeverything/blocksuite/assets/50226652/659feda8-4626-495c-8998-51f318a2a624

fix(edgeless): connector's start/end handler not consider zoom

---

packages/blocks/src/__internal__/utils/query.ts

Closes: https://github.com/toeverything/blocksuite/issues/2757

fix: batch selection contains surface element

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts

Probably the first time the cache was used, `affine-edgeless-page` has been deleted.
https://github.com/toeverything/blocksuite/assets/27926/5c8df067-7b87-4bfe-8633-9e0ce545a979
https://github.com/toeverything/blocksuite/blob/eb880a7f1f05e9e0b6765bb53ec090a458bcea30/packages/blocks/src/page-block/edgeless/edgeless-page-block.ts#L250-L252
```ts
this.surface = new SurfaceManager(yContainer, value => {
if (isCssVariable(value)) {
console.log(this.checkVisibility(), this.parentElement);
const cssValue = getThemePropertyValue(this, value as CssVariableName);
if (cssValue === undefined) {
console.error(
new Error(
`All variables should have a value. Please check for any dirty data or variable renaming.Variable: ${value}`
)
);
}
return cssValue ?? value;
}
return value;
});
```

fix(edgeless): unable to get computed value after switching mode

---

packages/blocks/src/bookmark-block/bookmark-block.ts

fix: bookmark block title style if overflow

---

packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts
packages/blocks/src/page-block/edgeless/components/resize-handles.ts
packages/blocks/src/page-block/edgeless/components/resize-manager.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/hotkey.ts
packages/blocks/src/page-block/edgeless/mode-controllers/brush-mode.ts
packages/blocks/src/page-block/edgeless/mode-controllers/connector-mode.ts
packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
packages/blocks/src/page-block/edgeless/mode-controllers/index.ts
packages/blocks/src/page-block/edgeless/mode-controllers/note-mode.ts
packages/blocks/src/page-block/edgeless/mode-controllers/pan-mode.ts
packages/blocks/src/page-block/edgeless/mode-controllers/shape-mode.ts
packages/blocks/src/page-block/edgeless/mode-controllers/text-mode.ts
packages/blocks/src/page-block/edgeless/selection-manager.ts
packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts
packages/blocks/src/page-block/utils/bind-hotkey.ts
tests/edgeless/frame.spec.ts
tests/edgeless/selection.spec.ts
tests/edgeless/shape.spec.ts

Closes #1873
https://github.com/toeverything/blocksuite/assets/27926/d2b3e686-bfb8-48d3-b815-fc25dddd9159

feat(edgeless): support proportional scaling with shift key

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/frame-resize-observer.ts
tests/edgeless/frame.spec.ts
tests/utils/actions/edgeless.ts

Closes #2715 
after redo, will trigger once resizeObserver event which cause the history stack chaotic. 
So If there is no change in size, then there is no need to update the size of frame block

fix(edgeless): fix continuous undo redo lost frame

---

packages/virgo/src/services/range.ts
tests/hotkey.spec.ts

Fix https://github.com/toeverything/blocksuite/issues/2982
Co-authored-by: @Flrande 
---
Event flow
```
press key
⬇️
hotkey.addListener(HOTKEYS.ANY_KEY)
deleteModelsByRange
vEditor.setVRange
this._editor.slots.vRangeUpdated.emit([vRange, 'other'])
onVRangeUpdated
requestAnimationFrame
_applyVRange  <- apply an expired range at the next tick
⬇️
_onBeforeInput
transformInput
handleInsertText
editor.slots.vRangeUpdated.emit([correctRange, 'input'])
onVRangeUpdated
_applyVRange
// ^ The correct range has been applied synchronously
```

fix: cursor pos when select multiple blocks and input

---

packages/blocks/src/embed-block/embed-block.ts
tests/embed.spec.ts

Fix https://github.com/toeverything/blocksuite/issues/2495
Event flows
```
DefaultSelectionManager
_onContainerClick
allCaptions.blur()
clickBlockInfo && matchFlavours(clickBlockInfo.model, ['affine:embed', 'affine:divider'])
window.getSelection()?.removeAllRanges();
// ^ Remove range when clicking `affine:embed` block
```

fix: unable to focus on image caption

---

packages/phasor/src/utils/math-utils.ts
packages/phasor/src/utils/math-utils.unit.spec.ts

before I used the Point.lerp method.
after I used the Vec.lrp method.
they actually don't have same parameter definition.
but the test still passed. What a coincidence.

fix(edgeless): fix intersects method

---

packages/blocks/src/page-block/edgeless/components/single-connector-handles.ts

The originController in closure is not updated, then it casued the incorrect calculation of connector path (especially `customized start/end`).
before:
https://github.com/toeverything/blocksuite/assets/50226652/3761d779-43d0-4ec7-b3d6-c6ac35446088
after:
https://github.com/toeverything/blocksuite/assets/50226652/b35eeda2-0f0b-41bb-8d92-6ca47db25a44

fix(edgeless): correct the connecotor's handle behavior

---

packages/blocks/src/__internal__/utils/selection.ts
packages/global/src/utils.ts
tests/selection/block.spec.ts

1. if click bottom of page and the end block is embed, editor should insert a new editable block
2. if click bottom of page and the end block is editable, the last editable block should be focused

feat: add block on clicking page bottom when necessary

---

packages/blocks/src/__internal__/utils/filesys.ts
packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts

To fix #3022 
I am not sure what the effect this feature is expected to achieve, give a simple try.
Currently, the logic is to add all the images embed blocks to a single frame.
Does this feature need to add each image embed block to a separate frame ?
The effect is as below now.
https://github.com/toeverything/blocksuite/assets/99816898/4ea22fc5-c756-4f4d-9fc9-0c41b3bd7b4a

feat: edgeless mode upload multiple images

---

packages/playground/examples/virgo/test-page.ts
packages/virgo/src/components/virgo-element.ts
packages/virgo/src/services/delta.ts
packages/virgo/src/services/event.ts
packages/virgo/src/services/range.ts
packages/virgo/src/tests/utils/misc.ts
packages/virgo/src/tests/v-range.unit.spec.ts
packages/virgo/src/tests/virgo.spec.ts
packages/virgo/src/utils/renderer.ts
packages/virgo/src/utils/v-range.ts
packages/virgo/src/virgo.ts

Make Virgo support making a specific `v-element` only selectable as a whole, by passing a function to Virgo when initing it.
For example, if you want to make a `v-element` of type `code` only selectable as a whole, you can pass a function to Virgo like this.
```ts
const vEditor = new VEditor(yText, {
embed: delta => !!delta.attributes?.code,
});
```
The effect is as follows.
https://github.com/toeverything/blocksuite/assets/50035259/95f6323a-48ab-4d9f-a0de-bb0466aae596

feat(virgo): support embed

---

packages/blocks/src/__internal__/rich-text/rich-text-operations.ts

To fix #2801 
https://github.com/toeverything/blocksuite/assets/99816898/d7651f80-e0f2-4709-85aa-4dd4104903a4

fix: press enter in the middle of parent also indent children list

---

packages/blocks/src/bookmark-block/bookmark-service.ts

To fix #2938 
https://github.com/toeverything/blocksuite/assets/99816898/1f94bb5f-fba3-401f-b8c1-c4f66d19dee1
The previous Bookmark block2html service just return the url of bookmark block.
Can bookmarks be considered as links and return the link in bookmark service?

fix: export two adjacent bookmarks produce one invalid url

---

packages/blocks/src/page-block/utils/bind-hotkey.ts
tests/selection/block.spec.ts

To close #2893 
Feat:
1. Press esc to select single block.
2. Press esc to select multiple blocks when having multiple native range block selection.
3. Press esc to unselect blocks when block is selected.
https://github.com/toeverything/blocksuite/assets/99816898/1aa54e69-6d0c-4d77-859f-c497ae0fa7ed

feat: support pressing esc to select blocks

---

packages/blocks/src/components/utils.ts

Fix https://github.com/toeverything/blocksuite/issues/2673

fix: ignore arrow key when select is composing

---

packages/blocks/src/page-block/edgeless/hotkey.ts
tests/edgeless/shortcut.spec.ts

To fix #3085 
https://github.com/toeverything/blocksuite/assets/99816898/741c573d-beeb-4e1a-8c69-0d4073906a5d

fix(edgeless): connectors cannot be activated using letter shortcuts

---

packages/blocks/src/components/linked-page/linked-page-popover.ts
tests/linked-page.spec.ts

Fix part of https://github.com/toeverything/blocksuite/issues/3059

fix: exclude the current page from linked page popover

---

packages/blocks/src/database-block/table/selection-manager/row.ts

Unexpected situation:
1. Click the first cell
2. Move the mouse to select column
3. Press mouse and drag
https://github.com/toeverything/blocksuite/assets/15389209/7daba71a-20ea-4c6e-b606-871e35a90084

fix(database): accidentally triggered row selection

---

packages/blocks/src/__internal__/utils/event.ts
packages/blocks/src/page-block/edgeless/selection-manager.ts
packages/global/src/config/consts.ts
packages/global/src/config/consts/event.ts

Closes #3033 
There're two things worth sharing:
1. Unlike pressing the primary mouse button, when the middle button is pressed and the mouse moves outside the document, it does not trigger the `pointermove` event.
2. After switching back to the current tab, the `pointermove` event won't be triggered if the middle button is pressed without first clicking on the page.

feat(edgeless): support drag canvas with middle button of mouse

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
packages/phasor/src/elements/index.ts
packages/phasor/src/surface.ts

Prevent `SurfaceElement` export in phasor to avoid confusion between `SurfaceElement` and `PhasorElement`outside the phasor.

refactor(phasor): prevent `SurfaceElement` export

---

.github/CLA.md
packages/blocks/src/__internal__/rich-text/rich-text-operations.ts
packages/blocks/src/__internal__/utils/query.ts
tests/paragraph.spec.ts

Fix #2976, about the delete action. (For forward-delete fixed by https://github.com/toeverything/blocksuite/pull/2552)

fix: handling backspace key press for cursor transition from paragraph to page title

---

packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/selection.ts
packages/blocks/src/bookmark-block/components/bookmark-create-modal.ts
packages/blocks/src/image-block/image-block.ts
packages/blocks/src/image-block/image/image-options.ts
packages/blocks/src/image-block/image/image-selected-rects.ts
packages/blocks/src/page-block/default/components.ts
packages/blocks/src/page-block/default/default-page-block.ts
packages/blocks/src/page-block/default/selection-manager/embed-resize-manager.ts
packages/blocks/src/page-block/default/selection-manager/selection-manager.ts
packages/blocks/src/page-block/default/selection-manager/utils.ts
packages/lit/src/element/block-element.ts
tests/embed.spec.ts

- Remove `EmbedSelectedRectsContainer` from `defaultPageBlock`
- Add new API in `BlockElement`(WIP)
```ts
export type FocusContext = (
| {
multi?: false;
}
| {
/**
* Please note that this parameter only suggests that the operation is a multi-select operation,
* and does not mean that multiple blocks will be selected every time.
*
* For example, select all blocks by pressing `Ctrl+A` or clicking the drag handler.
*/
multi: true;
/**
* Please check the length of the array before using it.
*/
blocks: BlockElement<BaseBlockModel>;
}
) &
(
| {
type: 'pointer';
event: PointerEvent;
}
| {
type: 'keyboard';
event: KeyboardEvent;
}
| {
// Please update the type name
// for example, 'api' or 'others'
type: 'UNKNOWN';
// TODO: add more information
}
);
class BlockElement<Model extends …
```

refactor: switch to block level image selection

---

packages/store/src/providers/broadcast-channel.ts

```
(node:24310) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/himself65/Code/AFFiNE/node_modules/async-call-rpc/utils/web/broadcast.channel.js:6
export class BroadcastMessageChannel extends BroadcastChannel {
^^^^^^
SyntaxError: Unexpected token 'export'
at internalCompileFunction (node:internal/vm:73:18)
at wrapSafe (node:internal/modules/cjs/loader:1176:20)
at Module._compile (node:internal/modules/cjs/loader:1218:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at ModuleWrap.<anonymous> …
```

fix(store): broadcast channel

---

packages/phasor/src/elements/shape/shapes/ellipse.ts

fix(phasor): curveFitting should be enabled on ellipse

---

packages/blocks/src/__internal__/content-parser/index.ts
packages/blocks/src/__internal__/content-parser/parse-html.ts
packages/blocks/src/__internal__/rich-text/rich-text.ts
packages/blocks/src/components/import-page/import-page.ts
packages/blocks/src/database-block/common/column-manager.ts

feat: support import notion database

---

packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/bookmark-block/bookmark-model.ts
packages/blocks/src/bookmark-block/bookmark-service.ts
packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
packages/blocks/src/bookmark-block/utils.ts
tests/bookmark.spec.ts

In `importPageSnapshot` function, when importing external json data, property "props:title" is the key world that will convert to the `yText` data. but in bookmark, title is string type, so change "title" to "bookmarkTitle" to avoid to convert automatically

feat: rename bookmark property title to bookmarkTitle

---

packages/store/src/persistence/blob/indexeddb-storage.ts

fix: missing blob mime types in IndexedDB

---

packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts

feat: hide toolbar when drag element move(#3271)

---

packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
packages/blocks/src/image-block/image/image-options.ts
packages/blocks/src/image-block/image/utils.ts
packages/blocks/src/page-block/default/utils.ts

feat: supports copying images and cross app pasting

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts

closes: #3329
When running `toast` multiple times, an exception will be reported
```
toast.ts:80 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'animate')
at toast (toast.ts:80:11)
toast @ toast.ts:80
await in toast (async)
(anonymous) @ edgeless-page-block.ts:606
Promise.finally (async)
(anonymous) @ edgeless-page-block.ts:604
(anonymous) @ slot.ts:106
emit @ slot.ts:104
EdgelessMoreButton._runAction @ more-button.ts:170
(anonymous) @ more-button.ts:46
handleEvent @ lit-html.ts:2010
Show 1 more frame
toast.ts:80 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'animate')
at toast (toast.ts:80:11)
```

feat(edgeless): toast message after copying to clipboard

---

packages/blocks/src/__internal__/rich-text/rich-text.ts
packages/blocks/src/__internal__/utils/hotkey.ts
packages/blocks/src/__internal__/utils/query.ts
packages/blocks/src/__internal__/utils/virgo.ts
packages/blocks/src/database-block/database-service.ts
packages/blocks/src/database-block/table/components/cell-container.ts
packages/blocks/src/database-block/table/components/column-type/checkbox.ts
packages/blocks/src/database-block/table/components/column-type/link.ts
packages/blocks/src/database-block/table/components/column-type/multi-select.ts
packages/blocks/src/database-block/table/components/column-type/number.ts
packages/blocks/src/database-block/table/components/column-type/rich-text.ts
packages/blocks/src/database-block/table/components/column-type/select.ts
packages/blocks/src/database-block/table/components/column-type/title.ts
packages/blocks/src/database-block/table/components/database-title.ts
packages/blocks/src/database-block/table/components/row-container.ts
packages/blocks/src/database-block/table/components/selection/selection.ts
packages/blocks/src/database-block/table/register.ts
packages/blocks/src/database-block/table/table-view-manager.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
tests/clipboard.spec.ts
tests/database/actions.ts
tests/database/database.spec.ts
tests/database/selection.spec.ts
tests/utils/actions/misc.ts

1. Add `tabindex` for `affine-database-cell-container`.
2. When the cell is selected but not in the editing state, the focus on `affine-database-cell-container`.
3. Call `focusCell` when a cell is selected and enters the edit state.
4. Provide `beforeEnterEditMode` to prevent entering edit mode or to do something before entering edit mode.
5. Remove the deprecated `page` method from `ColumnManager`

fix(database): hotkeys do not work

---

packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts

fix(edgeless): edgeless toolbar note-menu rounded border

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/utils/note-resize-observer.ts
tests/edgeless/note.spec.ts
tests/utils/actions/edgeless.ts
tests/utils/asserts.ts

close #3385
Note height is updated every time its related DOM element's rect changes. However, we cannot tell what triggers the change in the DOM rect (it could be triggered by local updates or undo/redo operations). Therefore, I have decided to make the undoManager not track updates to the note height.
If you think this solution is feasible, then I'll add some unit tests in the next days. Please let me know if you have any suggestions, thanks.

fix(edgeless): unexpected history record added when updating note height

---

packages/blocks/src/code-block/code-block.ts
packages/blocks/src/code-block/components/lang-list.ts
packages/blocks/src/code-block/utils/code-languages.ts

revert https://github.com/toeverything/blocksuite/pull/3419
The old PR has several problems:
- It lacks the prioritization of popular languages.
- There are still instances of language mismatch after switching the language.

fix: display current lang first

---

packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts

closes: #3447
It's a workaround.

fix(edgeless): missing images when copying as png

---

packages/blocks/src/page-block/edgeless/components/note-cut/cut-button.ts

https://github.com/toeverything/blocksuite/assets/9301743/04382761-3825-4c36-bde3-7ad5dad81443

fix(edgeless): scissors z-index bug after bump into AFFiNE

---

packages/blocks/src/__internal__/utils/types.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-brush-button.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
packages/blocks/src/page-block/edgeless/components/panel/line-styles-panel.ts
packages/blocks/src/page-block/edgeless/components/panel/line-width-panel.ts
tests/edgeless/brush.spec.ts
tests/edgeless/connector.spec.ts
tests/edgeless/shape.spec.ts
tests/utils/actions/edgeless.ts

feat(edgeless): migrate to lineWidthPanel for shape and connector

---

packages/blocks/src/image-block/image-block.ts

fix(edgeless): change image caption background to transparent

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts

To close #3499 
https://github.com/toeverything/blocksuite/assets/99816898/656cc898-cf54-4406-8376-16f57684ece2

fix(edgeless): inserted image size should be consistent in different viewport zoom level

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-menu.ts

fix(edgeless): connector tooltips inconsistency

---

packages/blocks/src/__internal__/rich-text/markdown-convert.ts
tests/markdown.spec.ts

Close #3505 
If there are whitespace characters immediately before or after the formatting symbols (including `*`, `**`, `***`, `~`, and `~~`), they shouldn't be converted, just like how this page's comment box works.
https://github.com/toeverything/blocksuite/assets/17249775/ffc82b7e-d3f2-43f7-a686-d9eb6c4bba54
https://github.com/toeverything/blocksuite/assets/17249775/47d1edf5-1690-4de8-9362-558b10c204fe

fix: inaccurate markdown convert patterns

---

packages/editor/src/components/simple-affine-editor.ts

Fixes #2971 
Upon investigation, it appears that the issue originated from this [commit](https://github.com/toeverything/blocksuite/commit/1ad53ccbae9e08a294694204b8fcc5719f7b1d10) - [File -packages/blocks/src/models.ts]
The `DatabaseBlockModelSchema` was separated from `builtInSchemas` and introduced as `__unstableSchemas`. Although its registration was managed in other references, it appears to have been missed in `simple-affine-editor.ts`.
I've included some screenshots of the issue prior to the fix. You can observe the error "Val doesn't exist" being thrown, and the drop target not appearing. I've also attached a screenshot showing the state after the fix.
Before fix - 
After Fix - 
Please let me know if there are any adjustments or improvements that need to be made. Thank you!

fix: register database in simple affine editor

---

packages/blocks/src/components/index.ts
packages/blocks/src/components/linked-page/config.ts
packages/blocks/src/components/linked-page/index.ts
packages/blocks/src/components/linked-page/linked-page-popover.ts
packages/blocks/src/components/slash-menu/config.ts
packages/blocks/src/components/slash-menu/index.ts
packages/blocks/src/components/slash-menu/slash-menu-popover.ts
packages/blocks/src/components/utils.ts
tests/linked-page.spec.ts

Upstream of https://github.com/toeverything/blocksuite/issues/3316
```ts
type LinkedPageOptions = {
triggerKeys: string[];
ignoreBlockTypes: string[];
convertTriggerKey: boolean;
getMenus: (ctx: {
query: string;
page: Page;
pageMetas: PageMeta[];
model: BaseBlockModel;
}) => LinkedPageGroup[];
};
@customElement('affine-linked-page-widget')
export class LinkedPageWidget {
static DEFAULT_OPTIONS: LinkedPageOptions = {
/**
* The first item of the trigger keys will be the primary key
*/
triggerKeys: ['@', '[[', '【【'],
ignoreBlockTypes: ['affine:code'],
/**
* Convert trigger key to primary key (the first item of the trigger keys)
*/
convertTriggerKey: true,
getMenus,
};
options = LinkedPageWidget.DEFAULT_OPTIONS;
public showLinkedPage(model: BaseBlockModel): void
}
```

refactor: support customize linked page

---

packages/blocks/src/image-block/image-block.ts

fix #2663 
"I attempted to add test cases, but I encountered some difficulties when it came to triggering the paste event on the input. Can you please provide some guidance on how to proceed?"

fix(page):  paste in image caption

---

packages/blocks/src/__internal__/content-parser/parse-notion-html.ts

fix(page): keep the figcaption when pasting

---

packages/phasor/src/elements/text/text-element.ts

fix(phasor): text element rendered not as expected when changed align

---

packages/block-std/src/event/dispatcher.ts
packages/block-std/src/selection/base.ts
packages/block-std/src/selection/variants/block.ts
packages/block-std/src/selection/variants/text.ts
packages/block-std/src/service/index.ts
packages/block-std/src/store/index.ts
packages/blocks/src/page-block/default/default-page-service.ts
packages/blocks/src/widgets/doc-dragging-area/index.ts
packages/blocks/src/widgets/linked-page/index.ts
packages/blocks/src/widgets/slash-menu/index.ts
packages/lit/src/element/lit-root.ts
packages/lit/src/element/widget-element.ts

Previously, developers can only add global event handlers on event dispatcher. Since we have selection model for now, we can now which block should be involved when handling events.
For example, if current selection is on a `paragraph block`, it may have a path like `page -> note -> paragraph`. The event handlers will be called in a sequence like: `paragraph -> note -> page -> global`. In this chain, you can always `return true` to prevent later handlers if you want.
```ts
// in service
// this event will only be called if selection path contains current block's flavour
this.handleEvent('click', fn)
// this event will be added as global handler
this.handleEvent('click', fn, { global: true })
```

feat(block-std): add scoped event

---

packages/blocks/src/widgets/slash-menu/config.ts

Furthermore, we can dynamically register slash menu items by traverse the widget items from `pageBlock.widgets` or block schemas in the future.

refactor(page): query other widget from `widgetElements`

---

packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/components/block-selection.ts
packages/blocks/src/components/index.ts
packages/blocks/src/divider-block/divider-block.ts
packages/blocks/src/widgets/slash-menu/config.ts

```ts
@customElement('affine-block-selection')
export class BlockSelection extends LitElement
```
```ts
class Block extends LitElement {
state override styles = css`
:host {
position: relative;
}
`
render() {
return html`${this.selected?.is('block')
? html`<affine-block-selection></affine-block-selection>`
: null}`;
};
}
```
https://github.com/toeverything/blocksuite/assets/18554747/2751fed3-c611-4eaa-8ec9-32aaa18d82dc

fix(page): add selection indicator for embed block

---

packages/phasor/src/path-data-parser/parser.ts

Refs: https://github.com/endojs/endo/blob/master/packages/ses/docs/lockdown.md#regexptaming-options

refactor: remove deprecated browser API

---

packages/blocks/src/image-block/image-block.ts

Same change with https://github.com/toeverything/blocksuite/pull/3741
I revert the spacing changed for the image since it is necessary for image selection, related to https://github.com/toeverything/blocksuite/pull/3675
cc @hwangdev97

fix(page): image selection spacing

---

packages/editor/package.json
pnpm-lock.yaml

Fix the issue with possibly inconsistent theme versions of the blocksuite and affine.

chore: move @toeverything/theme to peer dependency

---

packages/playground/apps/default/utils.ts

related to https://github.com/toeverything/AFFiNE/issues/3494
The issue of `DOMException: IDBDatabase.transaction: 'workspace' is not a known object store name` error is that in Firefox the `testIDBExistence` function will create an empty DB that will result in skipping upgrading the DB that is defined in affine.
I have checked the new implementation of `testIDBExistence` and it shall not create a new DB in both Chrome and Firefox on calling `testIDBExistence`. However I think you may need to remove the local `PLAYGROUND_DB` one in Firefox, or passing `?init` in the query params to make it work.

fix: playground not working on firefox

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts

Closes #3513
The edgeless mode are likely to experience lag on zooming and moving  when there's a massive amount of notes in the page. We could use css property `will-change` during the viewport's update and remove it after update has complete. This could bring us siginificant renering performance boost. See the comparison below:
Before use `will-change`:
https://github.com/toeverything/blocksuite/assets/9301743/52c186e4-2f7c-4059-9931-1fc30783f8fb
After use `will-change`:
https://github.com/toeverything/blocksuite/assets/9301743/910762e2-bab1-4cbf-a865-5dc5bdd2370c

perf(edgeless): optimize viewport zooming and moving performance

---

packages/blocks/src/database-block/database-model.ts
packages/blocks/src/surface-block/surface-model.ts
packages/docs/attaching-editor.md
packages/docs/data-persistence.md
packages/docs/workspaces-and-pages.md
packages/editor/src/components/simple-affine-editor.ts
packages/playground/apps/default/main.ts
packages/playground/apps/default/utils.ts
packages/playground/apps/starter/main.ts
packages/playground/apps/starter/utils.ts
packages/playground/examples/store/main.ts
packages/store/src/__tests__/database.unit.spec.ts
packages/store/src/__tests__/indexer.unit.spec.ts
packages/store/src/__tests__/schema.unit.spec.ts
packages/store/src/__tests__/workspace.unit.spec.ts
packages/store/src/base.ts
packages/store/src/utils/utils.ts
packages/store/src/workspace/index.ts
packages/store/src/workspace/migration/__tests__/migration.unit.spec.ts
packages/store/src/workspace/page.ts
packages/store/src/workspace/schema.ts
packages/store/src/workspace/workspace.ts

```ts
import { schema, workspace } from '@blocksuite/store';
const schema = new Schema();
schema.register(AffineBlocks);
// Migration can run without workspace
schema.upgradePage(oldBlockVersions, oldYDoc);
// create workspace with schema
const workspace = new Workspace({ schema });
```
---
```ts
const migration = {
toV4: (data, previousVersion, latestVersion) => {
const { elements } = data;
Object.keys(elements).forEach(key => {
const element = elements[key] as Record<string, unknown>;
const type = element.type;
if (type === 'shape' || type === 'text') {
const isBold = element.isBold;
const isItalic = element.isItalic;
delete element.isBold;
delete element.isItalic;
if (isBold) {
element.bold = true;
}
if (isItalic) {
element.italic = true;
}
}
});
},
} satisfies Record<string, (typeof …
```

feat(store): support block level upgrade on schema

---

tests/clipboard.spec.ts
tests/utils/actions/edgeless.ts

- `page.evaluate()` returns a serializable value or undefined, in this case, `Array.from(notes)` will be `[]`
- loop promises mistakenly

test: cleanup invalid test cases

---

packages/blocks/src/database-block/table/clipboard.ts
packages/blocks/src/database-block/table/components/selection.ts

1. Prevent native selection from being selected while dragging.
2. Execute the default copy function of the browser when editing columns such as `number/date/link/select`.

feat(database): optimize native selection

---

packages/blocks/src/__internal__/rich-text/markdown-convert.ts

fix: headings should not match the space hotkey

---

packages/blocks/src/widgets/linked-page/index.ts
packages/blocks/src/widgets/linked-page/linked-page-popover.ts
packages/blocks/src/widgets/slash-menu/config.ts
packages/blocks/src/widgets/slash-menu/index.ts
packages/blocks/src/widgets/slash-menu/slash-menu-popover.ts
packages/blocks/src/widgets/slash-menu/utils.ts

Fix https://github.com/toeverything/blocksuite/issues/3871
See also https://github.com/toeverything/blocksuite/pull/3872, grateful to @yuusheng as well

fix: clean custom trigger key in widgets

---

packages/blocks/src/attachment-block/components/moreMenu.ts
packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/attachment-block/components/renameModel.ts
packages/blocks/src/attachment-block/components/styles.ts

After hovering out, the rename popover should not hide.

feat(page): add overlay mask to attachment rename popover

---

packages/blocks/src/page-block/doc/meta-data/meta-data.ts

fixed: #3883 
If you need any changes then let me know.
Thank you so much for your assistance.

fix: align arrow icon in page info

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts

fixed: #3781 
@xell check this out

fix: added base UI font family to the Menu of edgeless

---

packages/blocks/src/components/tags/styles.ts

fix: added border radius to page tag selector

---

packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/attachment-block/components/styles.ts

chore: hide unimplemented attachment options

---

packages/blocks/src/list-block/styles.ts

The list prefix should not align center when there are multiple lines.

fix: typography when multiple line in list

---

packages/blocks/src/code-block/code-block.ts
packages/blocks/src/database-block/common/columns/title/cell-renderer.ts
packages/blocks/src/page-block/doc/doc-page-block.ts
packages/lit/src/element/block-element.ts
packages/lit/src/element/lit-root.ts

The `widgets` and `content` will cause a block re-render even if nothing has changed.
https://github.com/toeverything/blocksuite/blob/3bbe6d9ebd36e8e230ed72c47233cb4b72ffca8f/packages/lit/src/element/lit-root.ts#L143-L150
The pointless re-render is the root cause of the issue at https://github.com/toeverything/blocksuite/issues/4013
> In child expressions, `undefined`, `null`, `''`, and `nothing` all behave the same and render no nodes.
> hasChanged: A function that indicates if a property should be considered changed when it is set. The function should take the `newValue` and `oldValue` and return true if an update should be requested.

fix: optimize hasChanged for block element

---

packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-card.ts
packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-panel.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts

- synchronize toc card selection with edgeless selection state
- zoom out to fit all content when expand the toc panel and resume after collapsing
- card and be drag directly
- some naming convention

feat(edgeless): toc ux optimization

---

packages/blocks/src/components/import-page/import-page.ts
packages/blocks/src/widgets/linked-page/config.ts

close #4238 
fix: can not run blocksuite's toast function when not open a page in affine
fix: ignore quotes when parsing table

fix: can not run blocksuite's toast function when not open a page in affine

---

packages/blocks/src/page-block/doc/doc-page-block.ts

Before: every time click blank area to add a tail paragraph will reverse the page model.children
https://github.com/toeverything/blocksuite/assets/99816898/8b5599dc-2386-463c-af2f-869ff3ce8a91
After:
https://github.com/toeverything/blocksuite/assets/99816898/5fc4413a-54e0-4a05-83e4-2eba6db86ff1

fix(page): click at blank area should not change note sequence

---

package.json
pnpm-lock.yaml

reference: https://github.com/toeverything/blocksuite/issues/4286
I tested `build`, `circular` ok.
also `lit-lint`

chore: lock typescript version 

---

packages/blocks/src/database-block/common/header/views.ts

fix(page): added delete-item hover color 

---

packages/blocks/src/__internal__/rich-text/keymap/container.ts
tests/clipboard.spec.ts
tests/selection/block.spec.ts
tests/selection/native.spec.ts

fix: select all for rich text

---

packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts

Related to https://github.com/toeverything/blocksuite/pull/4333

fix(edgeless): typo in component naming

---

packages/blocks/src/page-block/edgeless/services/selection-manager.ts

Surface elements did not exist before the yEvent was triggered.
https://github.com/toeverything/blocksuite/assets/9301743/229a74cc-5a86-41bc-b3b4-dd8319e839a5

fix(edgeless): edgeless selection update error after undo

---

packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
packages/blocks/src/code-block/components/lang-list.ts
packages/blocks/src/components/block-hub.ts
packages/blocks/src/components/button.ts
packages/blocks/src/components/link-popover/styles.ts

- Remove deprecated `--affine-popover-color`
- Fix lit lint error for the disabled property in `icon-button`
- Update styles

fix(page): update popover styles

---

packages/blocks/src/page-block/edgeless/services/tools-manager.ts
packages/blocks/src/widgets/drag-handle/index.ts
packages/blocks/src/widgets/drag-handle/styles.ts

Before:
When using shape or note tool in edgeless page, the overlay will follow pointer even the pointer move on toolbar, it is wired.
https://github.com/toeverything/blocksuite/assets/99816898/7a2e5c9a-4b0d-42f2-b9a0-0ebb07fd4b7a
After:
Hide overlay when pointer move on toolbar.
https://github.com/toeverything/blocksuite/assets/99816898/16e6736f-8fbe-44d5-a3b2-ebc5e8fa0581

fix(edgeless): hide overlay when pointer move on toolbar

---

packages/blocks/src/attachment-block/components/styles.ts
packages/blocks/src/components/button.ts

Related to https://github.com/toeverything/blocksuite/pull/4345
There are still some issues when hovering the danger button

fix: icon button active styles

---

packages/blocks/src/page-block/utils/operations/model.ts

Sometimes the new block can not be added due to some reason, e.g. invalid schema check.
So we need to try to add the new block first, and if it fails, we will not delete the old block.

fix: try add new block first when transform block

---

packages/blocks/src/__internal__/utils/query.ts

To close #3684 #3924 
This issue caused by legacy doc page check api.
Now the page tagName change to 'AFFINE-DOC-PAGE', but the code still check 'AFFINE-DEFAULT-PAGE', this would let  function findBlockElement() return pageBlockElement too, and cause calculate drop target position out of page and jilter, this is incorrect, the findBlockElement() function should only return blockElement.
Now we can insert blank lines without jilter:
https://github.com/toeverything/blocksuite/assets/99816898/a0042a7c-87de-48f0-a8f6-f853d9d8e675

fix(page): viewport jilter when drag to left-bottom and cannot insert to page bottom from block-hub

---

packages/blocks/src/attachment-block/components/rename-model.ts
packages/blocks/src/image-block/image-block.ts

Fix https://github.com/toeverything/blocksuite/issues/4534
- Should not delete blob after image deleted
Revert part of https://github.com/toeverything/blocksuite/pull/4504
- Fix autofocus rename input
https://github.com/toeverything/blocksuite/assets/18554747/6db93791-1752-4d6a-bbaa-49f73056e34e

fix: attachment extension parsing error

---

packages/blocks/src/__internal__/service/legacy-services/note-service.ts
packages/blocks/src/__internal__/service/service.ts
tests/edgeless/note.spec.ts
tests/utils/actions/edgeless.ts
tests/utils/actions/misc.ts

fix: #4521.
The `getService` import statement was deleted in [pr-4316 service.ts](https://github.com/toeverything/blocksuite/pull/4316/files#diff-ea130923a45d52986ac100629b83b0e49c6661ff6bf6e9718807b24655f08c3d) and [pr-4316 note-service.ts](https://github.com/toeverything/blocksuite/pull/4316/files#diff-4418768de534fcccdd14733aba3a21e49a6d879c8d0d9af87b45e0779211560c).
It was used but deleted. is this a mistake? And i add a unit test for this case.

fix(edgeless): lost content with duplicate note action in edgeless #4521

---

packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-button.ts
packages/blocks/src/page-block/edgeless/components/note-slicer/slicer-indicator.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
tests/edgeless/note.spec.ts
tests/utils/actions/edgeless.ts

Change
- Slicer should be put into `affine-edgeless-layer` otherwise it will be covered by other note
- Add more tests

fix(edgeless): slicer should be put into `affine-edgeless-layer`

---

packages/blocks/src/icons/edgeless.ts
packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/common/slide-menu.ts
packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/note/note-tool-button.ts
tests/utils/actions/edgeless.ts

feat: edgeless toolbar update

---

packages/blocks/src/page-block/edgeless/components/panel/font-size-panel.ts

To close #4702 
https://github.com/toeverything/blocksuite/assets/99816898/bbc4d82e-d5ca-4087-8a75-4d2ee4839d73

fix(edgeless): press backspace should not delete text or shape element when changing text font size

---

packages/blocks/src/components/when-hover.ts
packages/blocks/src/image-block/image-block.ts
packages/blocks/src/page-block/types.ts
packages/blocks/src/preset/index.ts
packages/blocks/src/widgets/image-toolbar/image-options.ts
packages/blocks/src/widgets/image-toolbar/index.ts
tests/image.spec.ts

Related to https://github.com/toeverything/blocksuite/pull/4589 https://github.com/toeverything/blocksuite/pull/4635
- Fix the issue where the image toolbar remains even after deleting the image block.
- Move image toolbar widget to the image block
- Using the new whenHoverController

refactor: move image toolbar widget to image block

---

packages/blocks/src/page-block/edgeless/components/toolbar/common/slide-menu.ts
packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-menu.ts

Part of #4538 
Secondary menus support scrolling, and the left and right buttons enlarge on hover.

feat: edgeless toolbar secondary menu scrollable

---

.commitlintrc.json
packages/blocks/package.json
packages/blocks/src/bookmark-block/components/config.ts
packages/blocks/src/components/rich-text/markdown/inline.ts
packages/blocks/src/components/rich-text/rich-text.ts
packages/blocks/src/components/virgo-input/virgo-input.ts
packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
packages/blocks/src/database-block/common/header-area/text.ts
packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-preview.ts
packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-menu.ts
packages/blocks/src/page-block/edgeless/frame-manager.ts
packages/blocks/src/page-block/edgeless/tool-controllers/frame-tool.ts
packages/blocks/src/page-block/edgeless/utils/text.ts
packages/blocks/src/surface-block/elements/frame/constants.ts
packages/blocks/src/surface-block/elements/frame/types.ts
packages/blocks/src/surface-block/elements/shape/types.ts
packages/blocks/src/surface-block/elements/surface-element.ts
packages/blocks/src/surface-block/elements/text/constants.ts
packages/blocks/src/surface-block/elements/text/types.ts
packages/blocks/src/surface-block/surface-block.ts
packages/global/package.json
pnpm-lock.yaml

We expose Yjs in `@blocksuite/store` so there's no need to install it dependently.

refactor: remove yjs as dependency in blocks package

---

packages/blocks/src/page-block/edgeless/components/rects/edgeless-hover-rect.ts
packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
packages/blocks/src/page-block/edgeless/edgeless-blocks-container.ts
packages/blocks/src/widgets/drag-handle/styles.ts

fix(edgeless): isolate the impact of widgets on the layout

---

packages/store/src/__tests__/workspace.unit.spec.ts
packages/store/src/workspace/store.ts

The reason is since https://github.com/toeverything/blocksuite/pull/4747, there is a breaking change from the id, we should bring a new id generator on the AFFiNE side so that we can distinguish the old and new page/workspace
Upstream: https://github.com/toeverything/blocksuite/pull/342, https://github.com/toeverything/blocksuite/issues/287

refactor(store): bring custom id generator back

---

packages/blocks/src/components/when-hover.ts
packages/blocks/src/image-block/image-block.ts
packages/blocks/src/widgets/image-toolbar/index.ts

The `affine-drag-preview` will create a preview block when dragging, it is a little different from the actual image block

fix: error when drag image

---

packages/blocks/src/components/button.ts

Fix unexpected empty placeholder

fix(page): remove redundant entry in image popup

---

packages/blocks/src/components/block-hub.ts

close: #4564
before:
https://github.com/toeverything/blocksuite/assets/15389209/f285b9bf-876e-4808-9fca-389889ecbc96
after:
https://github.com/toeverything/blocksuite/assets/15389209/c8e9ce07-99ec-48e8-9c66-4e3db3bb2c2d

fix: add page bottom drop area for block hub

---

packages/blocks/src/components/rich-text/keymap/container.ts
packages/virgo/src/services/event.ts
packages/virgo/src/tests/virgo.spec.ts
packages/virgo/src/utils/transform-input.ts
tests/paragraph.spec.ts

Close #4785
Delete some `delete` input type handlers because we use target range before we handle them.
https://github.com/toeverything/blocksuite/blob/a13290617fcc9fa56207b9be7029bb3d80e57a2a/packages/virgo/src/services/event.ts#L270-L283

fix: wrong behavior in `option + delete`

---

packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
packages/blocks/src/page-block/edgeless/components/edgeless-notes-container.ts
packages/blocks/src/page-block/edgeless/edgeless-blocks-container.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/surface-block/surface-block.ts

close #4697
The `BlockSuiteRoot` component has built a rerender mechanism inside. But, it does not work for edgeless mode cause edgeless wraps everything inside `SurfaceBlock` which stops the notes that are deep inside the components tree from updating.
I added an extra slot listener to track notes' updates individually.

fix(edgeless): note does not update when other peers modified note

---

packages/blocks/package.json
packages/blocks/src/__internal__/consts.ts
packages/blocks/src/components/rich-text/rich-text-operations.ts
packages/blocks/src/list-block/list-block.ts
packages/blocks/src/list-block/styles.ts
packages/blocks/src/list-block/utils/get-list-icon.ts
packages/blocks/src/list-block/utils/icons.ts
packages/blocks/src/page-block/doc/doc-page-block.ts
packages/blocks/src/widgets/drag-handle/config.ts
packages/blocks/src/widgets/drag-handle/index.ts
packages/blocks/src/widgets/drag-handle/utils.ts
packages/editor/package.json
packages/editor/themes/affine.css
playwright.config.ts
pnpm-lock.yaml
tests/clipboard.spec.ts
tests/edgeless/basic.spec.ts
tests/edgeless/block-hub.spec.ts
tests/edgeless/brush.spec.ts
tests/edgeless/note.spec.ts
tests/edgeless/reordering.spec.ts
tests/edgeless/resizing.spec.ts
tests/edgeless/selection.spec.ts
tests/edgeless/shape.spec.ts
tests/edgeless/shortcut.spec.ts
tests/edgeless/text.spec.ts
tests/format-bar.spec.ts
tests/list.spec.ts
tests/utils/actions/edgeless.ts
tests/utils/asserts.ts

Fix https://github.com/toeverything/blocksuite/issues/2945
- See https://github.com/toeverything/design/pull/90
- `@media screen and (max-width: 640px)`
Credits to https://github.com/toeverything/blocksuite/pull/1139
- Now a new class `with-drag-handle` will be added to block elements when the drag handle hovering
- Update `--affine-editor-width` from 800px to 944px
- Update `affine-doc-page-block-container` padding from 24px to 96px
- Update playwright viewport from 900px to 960px
---
https://github.com/toeverything/blocksuite/assets/18554747/868a95d6-5102-41ed-8618-bc8e2c5785fa

feat(page): support universal list toggle

---

packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
tests/edgeless/selection.spec.ts

Now we can simultaneously use the mouse scroll wheel or touchpad to update the dragging area when we drag with the mouse.
https://github.com/toeverything/blocksuite/assets/99816898/08d02fb4-2d21-4a0c-8b6a-3af53db2d7dc

feat(edgeless): support updating dragging area when viewport updates

---

packages/blocks/src/image-block/image-block.ts

Fix https://github.com/toeverything/blocksuite/issues/4743
https://github.com/toeverything/blocksuite/assets/18554747/b86a45b9-dc73-42ac-97ed-3fced9fbcd6f
The new image toolbar widget broke the render diff
https://github.com/toeverything/blocksuite/blob/29c4afbe6309e3b32d9ca58cca34910f6941fe2c/packages/lit/src/element/lit-root.ts#L110-L121
See https://github.com/toeverything/blocksuite/pull/4187

fix: image flashing when resizing in edgeless

---

packages/blocks/src/components/rich-text/rich-text-operations.ts
packages/blocks/src/list-block/list-block.ts
packages/blocks/src/list-block/list-model.ts
tests/block-hub.spec.ts
tests/clipboard.spec.ts
tests/drag.spec.ts
tests/format-bar.spec.ts
tests/hotkey.spec.ts
tests/list.spec.ts
tests/slash-menu.spec.ts

Fix https://github.com/toeverything/blocksuite/issues/4857
- Add `collapsed` to the list model and default to `false`
---

fix(page): keeping list toggle state

---

packages/blocks/src/code-block/code-block.ts
packages/blocks/src/code-block/components/lang-list.ts

Supplement to https://github.com/toeverything/blocksuite/pull/4884
- Remove redundant `padding-bottom`
- The transparent background should not prevent the user from clicking
- The active item should not follow when using the keyboard navigator
https://github.com/toeverything/blocksuite/assets/18554747/351574b6-14a7-4628-8cf2-7486a4fed0b6

chore(page): tweak lang menu styles in code block

---

packages/blocks/src/components/rich-text/virgo/nodes/reference-node.ts
packages/virgo/src/components/embed-gap.ts
packages/virgo/src/components/virgo-line.ts
tests/edgeless/text.spec.ts
tests/selection/native.spec.ts

fix: improve embed related style

---

packages/blocks/src/image-block/image-block.ts
tests/image.spec.ts

close: #4904
https://github.com/toeverything/blocksuite/assets/15389209/4cf6e1f5-eef2-4f42-aa0d-e93a1bc1a709

feat(page): supports the `enter` key for image caption

---

packages/blocks/src/database-block/kanban/group.ts

Fixed #4917
without hover:
with hover:

fix(page): updated color of the "+ Add" 

---

packages/blocks/src/page-block/doc/doc-page-block.ts
tests/clipboard.spec.ts

fix(page): stop propagation on pasting to the title editor

---

packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
packages/blocks/src/page-block/edgeless/components/toolbar/note/note-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/text/text-tool-button.ts
tests/utils/actions/edgeless.ts

Part of #4925 
When using the shortcut key S to evoke Shape, the secondary panel must also appear at the same time.

feat(edgeless): open secondary menu when evoke shape tool

---

packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts

To close #5017 
https://github.com/toeverything/blocksuite/assets/99816898/2c7e2e35-70f5-48a1-ad7b-034bbff91833

fix(edgeless): content shifts when mounting shape text editor

---

packages/blocks/src/components/hover/middlewares/safe-area.ts

The debug option should be disabled by default
Related to https://github.com/toeverything/blocksuite/pull/4965

fix: unexpected bridge display

---

packages/blocks/src/page-block/edgeless/components/zoom/zoom-tool-bar.ts

fix: edgeless font family

---

packages/store/src/__tests__/indexer.unit.spec.ts
packages/store/src/__tests__/workspace.unit.spec.ts
packages/store/src/indexer/search.ts

The search results now include the content of the matched blocks.

feat(store): add content to search results

---

packages/blocks/src/components/rich-text/rich-text.ts
tests/format-bar.spec.ts
tests/image.spec.ts
tests/selection/native.spec.ts
tests/utils/actions/misc.ts

Fix https://github.com/toeverything/blocksuite/issues/5034
When the block is long, the scrolling behavior using the native `scrollIntoView` API still appears unnatural.

fix(page): incorrect cursor position when click slowly

---

packages/blocks/src/list-block/list-block.ts
tests/list.spec.ts

Users should be able to expand the toggle list even in readonly mode.
Blame to https://github.com/toeverything/blocksuite/pull/4865

fix(page): user should be able to expand toggle list in readonly mode

---

.vscode/settings.template.json

- After vscode 1.83.0, Code Actions' behavior on save in the editor has been modified from Booleans to an enum
- See https://github.com/microsoft/vscode/pull/190516 https://github.com/microsoft/vscode/issues/163920#issuecomment-1721561959
> Code Actions' behavior on save in the editor has been modified from Booleans to an enum with the following options:
>
> `always`: Code Actions with always be run on any kind of save (autosave when exiting or changing focus, explicit save, etc).
> `explicit`: Code Actions will be run only when explicitly saving.
> `never`: Code Actions will never be run on save.

chore: update vscode settings

---

packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/surface-block/elements/group/group-element.ts

1. preventDefault for cmd+g and cmd+shift+g
2. showtitle at init

fix(edgeless): group hotkey and show title at init

---

packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-menu.ts
packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu-config.ts
packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-menu.ts

Edgeless toolbar submenu tooltips are no longer affected by overflow since affine-tooltip is a portal currently with pr #4950.
So we can set all the submenu tooltip position as  default ('top').

fix(edgeless): edgeless toolbar submenu tooltip position

---

packages/blocks/src/_common/components/portal.ts

Fix https://github.com/toeverything/blocksuite/issues/5112
When the `edgeless-tool-icon-button` is clicked, the container of the edgeless button is hidden by the following styles. However, it is still present in the DOM, which causes the tooltip not to hide correctly.
https://github.com/toeverything/blocksuite/blob/6ba0419a97e5977093cf22e985aa47a332de6047/packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts#L210-L226

fix(edgeless): label flickering when switching shape style

---

packages/blocks/src/_common/widgets/surface-ref-toolbar/index.ts

Related to #5013
- Remove redundant div container
- Tweak class naming
I recommend enabling the `hide whitespace` option when reviewing

chore: remove unused wrapper

---

packages/blocks/src/page-block/edgeless/utils/text.ts
packages/blocks/src/surface-block/elements/text/consts.ts
tests/edgeless/text.spec.ts

To close #5165 
https://github.com/toeverything/blocksuite/assets/99816898/98da7b2c-c432-41a3-8564-9af47c589647

feat(edgeless): use sans font family as default when adding canvas text

---

packages/blocks/src/page-block/edgeless/utils/text.ts
tests/edgeless/shape.spec.ts

To close #5206 
https://github.com/toeverything/blocksuite/assets/99816898/8cca744e-7df2-4e49-a49b-d975d663ae6c

fix(edgeless): shape text init font family should be consistent with shape style

---

packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts

before:
https://github.com/toeverything/blocksuite/assets/99816898/2005d4f4-0687-4ed3-97b3-ae8f860471fc
after:
https://github.com/toeverything/blocksuite/assets/99816898/de578e81-d7d5-4069-ab9d-581d338897e6

fix(edgeless): text editor should not have minWidth without adjusting width

---

packages/store/src/workspace/meta.ts
tests/utils/asserts.ts

should not init tags based on local state, because tags may exist on remote

fix(page): sometimes page tags disappear

---

tests/image.spec.ts
tests/import.spec.ts
tests/utils/actions/misc.ts

Sunsetting the `shamefullyIgnoreConsoleMessage`.
Now, all console messages need to be explicitly declared by the new test API `expectConsoleMessage`.
NOTE: `expectConsoleMessage` **should** be called before the `enterPlaygroundRoom` function!
> ## Soft Assertions
> By default, failed assertion will terminate test execution. Playwright also supports soft assertions: failed soft assertions do not terminate test execution, but mark the test as failed.
>
> https://playwright.dev/docs/test-assertions#soft-assertions

test: switch to `expectConsoleMessage`

---

packages/playground/apps/default/components/quick-edgeless-menu.ts
packages/playground/apps/starter/components/debug-menu.ts

Close #4381 (not perfectly closed, but should be adequate FTM)
Before:
After:

perf(playground): lazy load style debug menu

---

packages/blocks/src/_common/components/rich-text/rich-text.ts

Closes: #5042 
https://github.com/toeverything/blocksuite/assets/54364088/86591e48-d302-4135-9b2a-e6dcc7c938ff

feat(page): enter key also triggers inline style formatting

---

packages/editor/src/components/editor-container.ts
packages/lit/src/element/lit-root.ts

In some scenarios, the outside needs to wait for the block element to finish rendering. This PR allows the outside to precisely know this moment through `editor.updateComplete` instead of using `setTimeout`.
related:
https://github.com/toeverything/AFFiNE/pull/4858/files#diff-3de211b8fe52fc353dfb51cc44c0f91272ffdeb8bc31481d69e1dfd8068c2da1R137-R142

feat: override `getUpdateComplete` of `editor-container` and `lit-root`

---

packages/blocks/src/_common/components/rich-text/virgo/nodes/link-node/link-popup/link-popup.ts

Closes: #5014 
Changes:
* Mulitple mock selection divs, derived using `getClientRects`, for representing text selection accurately.
* Check for `isValidUrl` in the `_onConfirm` method before `normalizeUrl`. Previously, an invalid URL was getting accepted on pressing the Enter key as this check was after normalizeUrl.
https://github.com/toeverything/blocksuite/assets/54364088/2a39ac1d-923e-4f7c-ba00-1b0fc3a49545

fix(page): mock selection of multiline text on create/edit link

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
packages/blocks/src/page-block/edgeless/utils/consts.ts
packages/blocks/src/page-block/edgeless/utils/text.ts

By design:
[shape text](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%93%8C-AFFiNE-2023?type=design&node-id=12712-188780&mode=design&t=smZ2k380zorFPnx9-0)
When shape fillColor is black, the shape text color is white, otherwise the shape text color is black no matter what theme is.
But I think maybe we should consider theme mode when shape is transparent to make it easy to read.

fix(edgeless): optimize shape text color when shape is transparent

---

packages/blocks/src/_common/components/rich-text/virgo/nodes/link-node/link-popup/link-popup.ts

https://github.com/toeverything/blocksuite/pull/5241#issuecomment-1798213417
* Switched to `mode: 'replace'` in `formatText` method while creating new link, to clear all text attributes in selection.
https://github.com/toeverything/blocksuite/assets/54364088/aeb8e2fa-7a21-4959-bf49-e869cad05cd7

fix(page): multiple link elements when part of selection has attributes

---

packages/docs/event-api.md
packages/store/src/workspace/page.ts

close #5249
Not using `_synced` to avoid misunderstanding with the concept of "synced with server" during collaboration.

feat(store): add `page.slots.ready`

---

packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts

Fix https://github.com/toeverything/blocksuite/issues/5273

fix(edgeless): remove shape overlay when element disconnect

---

packages/block-std/src/__tests__/command.unit.spec.ts
packages/block-std/src/command/index.ts
packages/docs/command-api.md

`tryAll` is used to attempt to execute an array of commands within a chain. Unlike `try`, which stops executing the list of commands as soon as one of them succeeds, `tryAll` will execute every command in the array, regardless of the individual outcomes of each command.
This means that even if one of the commands succeeds, `tryAll` will still continue to execute the remaining commands in the array. The chain will only proceed to the next command after `tryAll` if at least one command in the array succeeds. If all commands fail, the chain will be interrupted.
```ts
std.command
.pipe()
.tryAll(cmd => [cmd.command1(), cmd.command2(), cmd.command3()])
.command4()
.run();
```
If `command1`, `command2`, or `command3` succeeds, `command4` will be executed. If all commands in `tryAll` fail, the …

feat(std): add tryAll in command manager

---

packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/attachment-block/components/more-menu.ts
packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/attachment-block/utils.ts
packages/blocks/src/bookmark-block/embed.ts

Since the attachment size becomes configurable in https://github.com/toeverything/blocksuite/pull/5158, the size of attachement may be very large.
This pr optimize large file download experience.  It includes the following improvements:
- Showing a toast when clicking download
- Showing a loading state when downloading
- Fixing the issue of multiple simultaneous downloads of attachments

feat(page): optimize large file download experience

---

packages/blocks/src/_legacy/content-parser/index.ts

Fixes #5296. Thank @lawvs for guidance.

fix: sync `PageMeta.title` with `PageBlockModel.title` while importing markdown files

---

packages/blocks/src/paragraph-block/paragraph-block.ts

close: #5204
before:
https://github.com/toeverything/blocksuite/assets/15389209/dfbdc1ff-a42d-4d4f-a989-04044547921d
after:
https://github.com/toeverything/blocksuite/assets/15389209/623685ae-beed-4276-b37e-dcfc3dc3d427

fix(page): unexpected placeholder

---

packages/blocks/src/_common/components/rich-text/keymap/container.ts
packages/blocks/src/note-block/keymap.ts
packages/blocks/src/note-block/utils.ts
tests/edgeless/note.spec.ts
tests/paragraph.spec.ts
tests/quote.spec.ts

Closes: #5281 (duplicate of #5155)
Closes: #5155 
Closes: #2834 
Currently, the app only handles inter-block up/down navigation. Within the same block is handled by the browser. After many iterations, it felt to have consistent behavior and handle all edge cases either app or browser should completely handle the navigation.
This may be removed when migration to a single root content editable container is complete and the browser is able to handle navigation completely.

fix(page): arrow up/down navigation

---

packages/global/src/env/index.ts
packages/store/src/__tests__/indexer.unit.spec.ts
packages/store/src/__tests__/workspace.unit.spec.ts
packages/store/src/indexer/search.ts

improve the performance for large content in single block:
before:
after:

perf(store): support lazy reindex

---

packages/blocks/src/code-block/utils/highlight-cache.ts

Improve the severe performance issues of the code-block in long texts.
before:
after:

perf(page): increase code highlight cache size

---

packages/block-std/src/selection/variants/text.ts
packages/blocks/src/_common/components/rich-text/keymap/container.ts
packages/blocks/src/note-block/keymap.ts
packages/blocks/src/note-block/utils.ts
packages/blocks/src/page-block/text-selection/utils.ts
packages/lit/src/utils/range-manager.ts
packages/lit/src/utils/range-synchronizer.ts
tests/format-bar.spec.ts

Closes: #2684 
Closes: #4435 
Closes: #1290
Changes:
- Text Selection: Implemented app logic for changing text selection using arrow keys inside the note block.
- Reverse Text Selection: If text selction has been made using mouse and user continues to modify the selection using keyboard, the selection should change from the last cursor position. For this to work for reverse text selection (right to left / bottom to top) I had to modify:
- `_mergeRanges` to calculate if reverse selection is made.
- `_renderRange` to render reverse selection correctly.
- add `isReverse` property to `TextSelection` to store reverse selection state and calculate the start / end of selection.
- Format Bar: Format bar appears on text selection and hide the text, blocking it from caret position calculation. To …

fix(page): shift + arrow text selection

---

packages/blocks/src/_common/components/file-drop-manager.ts
packages/blocks/src/_common/components/index.ts
packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/attachment-block/attachment-model.ts
packages/blocks/src/attachment-block/index.ts
packages/blocks/src/attachment-block/utils.ts
packages/editor/src/components/editor-container.ts
packages/store/src/workspace/page.ts
tests/attachment.spec.ts

Fix https://github.com/toeverything/blocksuite/issues/4622
Now the attachment can correctly show a loading state when inserted via drag and drop.
https://github.com/toeverything/blocksuite/assets/18554747/00c04e29-77b7-40cd-8ae9-1103eb159b78
This PR also sunsetting the `loadingKey` since I found the `page.addBlock` function supports the `id` parameter which is a better alternative to identify the block.
No need to perform the migration action because all legacy `loadingKey` will be ignored.
Note: other collaborators will see an error attachment block when the blob has not finished uploading. This issue can be resolve by sync the upload status through the awareness system in the future.

fix(page): delay when inserting attachments via dnd

---

packages/blocks/src/database-block/kanban/group.ts

to fix error I made in #5336 
In browsers where :has css pseudo-class is not supported, no hover animation will be shown on add button.
Changes:
- Keep both independent and linked css hover animation.

fix(database): kanban add button hover animation where :has is not supported

---

packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/attachment-block/styles.ts

- Fix icon styles when the name of the attachment exceeds one line
- Fix line break when the name of the attachment is lengthy
- Fix the height of the banner layer incorrectly

fix(page): tweak attachment styles

---

packages/block-std/src/selection/manager.ts
packages/block-std/src/selection/variants/text.ts

Fix the error log in https://github.com/toeverything/AFFiNE/issues/4980
```
slot.js:99 [
{
"code": "invalid_type",
"expected": "boolean",
"received": "undefined",
"path": [
"isReverse"
],
"message": "Required"
}
]
```
Since the remote data is unreliable, we should ignore the error when parsing failure.

fix: backwards compatible with remote selection

---

packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
packages/blocks/src/divider-block/divider-block.ts
tests/paragraph.spec.ts
tests/selection/native.spec.ts

closes #4547
Changes:
- Clicking on the divider selects the divider block, which can then be deleted using backspace / delete
- Deleting divider using keyboard
- Pressing backspace after a divider deletes the divider
- Pressing delete before a divided deletes the divider
https://github.com/toeverything/blocksuite/assets/54364088/ce920eed-9eef-4345-95ac-49cd42e2389f

fix(page): divider selection and deletion

---

.eslintrc.cjs

I opened the project on Windows,  After every line  I got:
```
[eslint] Delete `CR` [prettier/prettier]
```
So I added settings in `eslint.cjs`. It works fine

chore: solve `delete CR`

---

packages/blocks/src/_legacy/service/json2block.ts
packages/blocks/src/_legacy/service/legacy-services/code-service.ts
tests/code.spec.ts

closes #5055 
before:
https://github.com/toeverything/blocksuite/assets/54364088/c0a845aa-704f-46d8-90ce-849fe66c628c
after:
https://github.com/toeverything/blocksuite/assets/54364088/b803e16b-e526-480a-b3b2-e75904624ef9
Changes:
- Text paste in code block: 
1. corrected index calculation in overridden json2Block.
2. modified existing copy/paste test to check for VRange after paste.
- Text paste in paragraph: `asyncSetVRange` is flaky and sets wrong cursor position at random. Switched to `getVirgoByModel` for focusedBlockModel.

fix(page): incorrect cursor position on pasting text

---

packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts

Fixing the cursor style will not restore when the shape is deleted.
https://github.com/toeverything/blocksuite/assets/18554747/fb64bb06-3fb8-4f6c-9fa8-b6188b57d5a0

fix(edgeless): reset cursor when the selection changes

---

packages/blocks/src/_common/utils/query.ts

closes #5386 
Changes:
- `affine-frame` should not be returned by getPreviousBlock. getPreviousBlock is used in text operations where `affine-frame` causes an exception.

fix(page): console error on deleting at the start of first paragraph

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts

closes #5373 
before:
https://github.com/toeverything/blocksuite/assets/54364088/6cb2d47f-c9ae-45c0-be32-a195d0ee4208
after: 
https://github.com/toeverything/blocksuite/assets/54364088/0bc6efd6-4c92-4c4f-b91b-3130106a1f05
Changes:
- Group element update needs to be applied to all the child elements, recursively.

fix(edgeless): for group element, apply local record update recursively

---

packages/blocks/src/_common/components/rich-text/virgo/hooks.ts
tests/basic.spec.ts
tests/bookmark.spec.ts
tests/link.spec.ts

closes #4371 
Current Behavior: autoIdentifyLink executes on every key press. On typing inside the link triggers autoIdentifyLink, changing the link text and url
Changes:
- autoIdentifyLink executes only on pressing space after a non-link element.
- typing within the link element only changes the link text.
p.s.: popup on pasting a link is handled in affine, ref https://github.com/toeverything/blocksuite/issues/4371#issuecomment-1820821749

fix(page): autoIdentityLink behavior

---

packages/blocks/src/_legacy/clipboard/page-clipboard.ts
packages/store/src/__tests__/block-tree.unit.spec.ts
packages/store/src/schema/base.ts
packages/store/src/workspace/block/block-tree.ts
packages/store/src/workspace/block/block.ts
packages/store/src/workspace/page.ts

```ts
model.slots.propsUpdated.on(({ key }) => {
if (key === 'someProp') {
doSomething();
}
})
```

feat(store): add `key` field for props updated slot

---

packages/blocks/src/list-block/utils/get-number-prefix.ts
tests/list.spec.ts

fix(page): extra space between dot and ordinals

---

packages/blocks/src/_common/components/tags/multi-tag-select.ts

With the screen enlarged, click the '+' plus button to cut the modal window at the top.
At that time, the value of the phase (==y) is negative.
So, when the y value is negative, I specified it as 240 to solve the truncation phenomenon.
Now, you can add tags without any inconvenience.
Thank you for giving me the opportunity to contribute.

fix(database): incorrect tag modal position

---

packages/blocks/src/_common/components/rich-text/rich-text.ts
packages/lit/src/utils/v-range-provider.ts
packages/virgo/src/services/range.ts
packages/virgo/src/utils/transform-input.ts
packages/virgo/src/virgo.ts

closes #4988 
Bug happens only when selection and page scroll happens together.
`rich-text` has auto scrolling which tries to keep the entire selection in view, hence preventing selected text to scroll out of view.
Changes:
- autoscroll only when vrange is updated in `sync` mode.
- added slot event on v-range-provider for setVRange to trigger `sync`.
- native selection events will update vrange in `async` mode i.e. `sync = false`

fix(page): autoscroll during native selection

---

packages/blocks/src/page-block/edgeless/utils/panning-utils.ts

To close #5486 
https://github.com/toeverything/blocksuite/assets/99816898/995450ca-d2cd-46df-a500-176b792388ce

fix(edgeless): consider containerOffset when auto-panning

---

packages/blocks/src/_common/widgets/image-toolbar/image-options.ts
packages/blocks/src/image-block/image-block.ts

The assignment of `blob` is done asynchronously, which means that the non-null assertion in this case is incorrect.
https://github.com/toeverything/blocksuite/blob/8ea9348556299c1e1247023515cfca5354713d2e/packages/blocks/src/image-block/image-block.ts#L113-L117

fix(page): error when quickly clicking actions in image block

---

packages/blocks/src/_legacy/content-parser/index.ts
packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/attachment-block/attachment-model.ts
packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/attachment-block/embed.ts
packages/blocks/src/attachment-block/styles.ts
packages/blocks/src/attachment-block/utils.ts
packages/docs/block-schema.md
packages/editor/src/components/editor-container.ts
tests/attachment.spec.ts

Fix https://github.com/toeverything/blocksuite/issues/3641 https://github.com/toeverything/blocksuite/issues/5033
This PR may need to undergo UI review.
There is a new property that has been added to the attachment model.
```ts
export type AttachmentBlockProps = {
/**
* Whether to show the attachment as an embed view.
*/
embed: boolean | BackwardCompatibleUndefined;
}
```
https://github.com/toeverything/blocksuite/assets/18554747/2a9aaf43-85fa-417f-995d-73b0c89d338d
- The selection can not go through the iframe. The embed bookmark also has the same problem.
This issue can be resolved by applying a transparent layer over the iframe.
https://github.com/toeverything/blocksuite/assets/18554747/2b601be2-688d-4aef-a450-1e190d48d759
- The PDF will reset to page 0 when the page reloads. I think …

feat(page): support embed view for certain attachment types

---

packages/store/src/indexer/backlink.ts

Used to remove `PageReferencesAtom` Atom in AFFiNE.
https://github.com/toeverything/AFFiNE/blob/canary/packages/frontend/hooks/src/use-block-suite-page-references.ts#L16-L40

chore(store): expose the `linkIndexMap` in `BacklinkIndexer`

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/frame-manager.ts
packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
packages/blocks/src/surface-block/surface-block.ts
packages/blocks/src/surface-block/surface-service.ts

1. Fix note duplicate without edgeless props.
2. Add `edgelessToolUpdated ` slot to `SurfaceService`.
3. Place `fitToViewport` to seperate area instead of subscribing slot.

fix(edgeless): note duplicate issue & expose service api

---

packages/blocks/src/surface-block/surface-block.ts

Before:
https://github.com/toeverything/blocksuite/assets/58546692/cacf9eb7-4528-4ef7-a337-714b3b3954ea
After: 
https://github.com/toeverything/blocksuite/assets/58546692/61f2d2ab-8476-4b70-9321-e05ebb2df317

fix(edgeless): move grouped content together on dragging

---

packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/attachment-block/styles.ts
packages/blocks/src/bookmark-block/components/bookmark-card.ts

Fix https://github.com/toeverything/blocksuite/issues/5579 by adding an overlay mask when the mouse is clicked down.

fix(page): selection should be able to go through iframe

---

packages/global/index.d.ts
packages/store/src/workspace/meta.ts
packages/store/src/workspace/page.ts
packages/store/src/workspace/store.ts

We are working towards a non-breaking block tree structure, so the validation process will be handled in application level (rather than on loading editor). This is made into an opt-in preset option for now. Please set the flag before `page.load`.
cc @joooye34 @Saul-Mirone

refactor(store): deprecate legacy validation

---

packages/blocks/src/_common/edgeless/mixin/edgeless-selectable.ts
packages/blocks/src/_common/edgeless/mixin/index.ts
packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/_common/embed-block-helper/embed-block-model.ts
packages/blocks/src/_common/embed-block-helper/types.ts
packages/blocks/src/embed-github-block/embed-github-model.ts
packages/blocks/src/embed-html-block/embed-html-model.ts
packages/blocks/src/frame-block/frame-model.ts
packages/blocks/src/image-block/image-model.ts
packages/blocks/src/note-block/note-model.ts
packages/blocks/src/surface-block/elements/text/text-element.ts
packages/global/src/utils/index.ts
packages/global/src/utils/types.ts
packages/lit/src/with-disposable.ts

Before:
```ts
@EdgelessSelectableMixin
export class NoteBlockModel
extends BaseBlockModel<NoteProps>
implements IEdgelessElement
{
override flavour!: EdgelessBlockType.NOTE;
elementBound!: Bound;
get connectable() {
return true;
}
get batch() {
return BLOCK_BATCH;
}
get rotate() {
return 0;
}
containedByBounds!: (_: Bound) => boolean;
getNearestPoint!: (_: IVec) => IVec;
intersectWithLine!: (_: IVec, _1: IVec) => PointLocation[] | null;
getRelativePointLocation!: (_: IVec) => PointLocation;
boxSelect!: (bound: Bound) => boolean;
hitTest(x: number, y: number, _: HitTestOptions): boolean {
const bound = Bound.deserialize(this.xywh);
return bound.isPointInBound([x, y], 0);
}
}
```
After:
```ts
export class NoteBlockModel
extends selectable<NoteProps>(BaseBlockModel) {
}
```

refactor: remove extra props for edgeless selectable mixin

---

packages/inline/src/utils/guard.ts

Current implementation will cause warning that is `The "??" operator here will always return the left operand`.

refactor:  optimize the implementation of isNativeTextInVText

---

packages/docs/.vitepress/config.ts
packages/inline/src/services/range.ts

This reverts 2be59aa30320d9ef1817af1dacfc261047da5396
https://github.com/toeverything/blocksuite/pull/5683

revert: fix DOMException on encountering {} in markdown

---

packages/blocks/src/_common/adapters/markdown.ts
packages/blocks/src/_common/adapters/markdown.unit.spec.ts
packages/blocks/src/database-block/database-model.ts

A workaround for incorrect exported markdown table format, relate to #4632, inline blocks have not been implemented.

fix: markdown table view format workaround

---

.commitlintrc.json
packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
packages/inline/src/components/v-line.ts
tests/bookmark.spec.ts
tests/export.spec.ts

Close #5723
before:
https://github.com/toeverything/blocksuite/assets/50035259/2d37f6f6-3a75-4881-aefa-967c712f67af
after:
https://github.com/toeverything/blocksuite/assets/50035259/d9f4a8cd-7cb0-4eb1-8a9b-cc19726b882d

fix(edgeless): wrong display in canvas editor when setting text-align to right

---

packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
tests/edgeless/shape.spec.ts

To close #5731 
https://github.com/toeverything/blocksuite/assets/99816898/0cbcef5b-387b-400a-a494-1a30fe413820

fix(edgeless): wrong size display when dragging after changing the font size

---

packages/docs/.vitepress/config.ts

I was assigned this [issue](https://github.com/toeverything/blocksuite/issues/5751).
On the doc website under navbar section the twitter logo was still the old one.
I have updated it to new icon.
Closes #5751.

feat: updated-twitter-icon

---

packages/blocks/src/page-block/edgeless/components/toolbar/frame/navigator-setting-button.ts
packages/presets/src/fragments/frame-panel/header/frames-setting-menu.ts

The "Dark background" switch - when turned on, a black box is displayed - by default, it is not displayed. 
The "Hide toolbar" switch - when turned on, the toolbar is hidden - by default, it is displayed.

feat(edgeless): update presentation setting labels

---

packages/blocks/src/_common/components/rich-text/inline/nodes/reference-node.ts
packages/blocks/src/_common/utils/query.ts

`getBlockComponentByModal` was removed in PR 5765 and was replaced by corresponding util fn. In this case `getDocPageByElement` as the element was originally type casted as `DocPageBlockComponenet`.
As `AffineReference` is used both in doc & edgeless. It is corrected to `getPageByElement` returning `PageBlockComponent`.

fix: element handling with `getPageByElement` in doc & edgeless

---

packages/blocks/src/page-block/edgeless/components/rects/edgeless-hover-rect.ts
packages/blocks/src/page-block/widgets/doc-remote-selection/doc-remote-selection.ts
packages/blocks/src/page-block/widgets/edgeless-remote-selection/index.ts
packages/blocks/src/page-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts

close #5662
The remote cursor can be hidden through `AffineDocRemoteSelectionWidget.enable = false` and `EdgelessRemoteSelectionWidget.enable = false`;

fix(edgeless): share page should be able to hide remote cursor

---

packages/lit/src/element/lit-host.ts
packages/presets/src/editors/editor-container.ts

Related to https://github.com/toeverything/blocksuite/pull/5158#issuecomment-1865840827 https://github.com/toeverything/blocksuite/pull/5657
This pull request fixes an issue with forwarding specs in the editor container.
Previously, the specs were not being properly forwarded to the doc-editor and edgeless-editor components.

fix: forward specs to editor

---

packages/inline/src/inline-editor.ts
packages/inline/src/services/event.ts
packages/playground/examples/inline/test-page.ts

The nesting of contenteditable elements can cause the lower-level contenteditable elements to be unable to listen to the events necessary for content synchronization (beforeinput, composition, keydown). Therefore, the inline editor needs to support listening to related events in elements outside of the rootElement.

feat(inline): support nested contenteditable

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
packages/blocks/src/page-block/widgets/drag-handle/components/drag-preview.ts
packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
packages/blocks/src/page-block/widgets/drag-handle/utils.ts
tests/drag.spec.ts

Bugs fixed:
- drag handle showing after block is deleted
- drag handle showing over pop-up menu
- drag handle disappears on failed drop. need to deselect and select again to show drag handle.
added throttle to limit too many update

fix: drag handle ui bugs

---

packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/note-block/note-block.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts

Due to the change in rendering style of edgeless block portal items in #5791, overlay position calculation needs to be updated.
Affected items:
- drag preview of top-level blocks in edgeless
- note slicer (on zoom in/out)
- more menu (on edgeless surface pan)
https://github.com/toeverything/blocksuite/assets/54364088/e1b75899-7e4a-401b-8963-c7ed95f25e3d

fix(edgeless): correct overlay position after #5791

---

packages/blocks/src/page-block/doc/doc-page-block.ts

before:
https://github.com/toeverything/blocksuite/assets/15389209/e12764bd-5a73-4101-bb50-025daf1b4602
after:
https://github.com/toeverything/blocksuite/assets/15389209/403dce25-9bcc-4737-be2f-f3d4a5207452

fix(page): unable to add trailing paragraph on click in windows

---

packages/presets/src/editors/affine-doc-editor.ts

Using `noop(DocTitle)` should be adequate for prevent tree-shaking. cc @AyushAgrawal-A2

chore: remove redundant import

---

packages/blocks/src/database-block/common/columns/date/cell-renderer.ts

part of: #5798
> It is hard to edit the field after it has a value. It seems the element with the value doesn't have an action to select a new date, so I need to click around it on the element "below" it.

fix(database): date cell cannot display date picker again

---

packages/playground/apps/starter/components/custom-outline-panel.ts
packages/playground/apps/starter/components/debug-menu.ts
packages/playground/apps/starter/main.ts
packages/presets/src/fragments/toc-panel/toc-panel-body.ts
packages/presets/src/fragments/toc-panel/toc-panel.ts

1. Support double click at blank area to disable note sorting option.
2. Fix highlight mask disappeared after mode switched.
3. Fix typo.

feat(presets): support double click to disable note sorting and fix typo

---

README.md
packages/blocks/src/bookmark-block/doc-bookmark-block.ts
packages/docs/blocksuite-overview.md
packages/playground/apps/starter/components/debug-menu.ts
packages/presets/src/__tests__/utils/edgeless.ts
packages/presets/src/editors/doc-editor.ts
packages/presets/src/editors/edgeless-editor.ts
packages/presets/src/editors/editor-container.ts
packages/presets/src/fragments/copilot-panel/copilot-panel.ts
packages/presets/src/fragments/copilot-panel/edgeless/api.ts
packages/presets/src/fragments/frame-panel/frame-panel.ts
packages/presets/src/fragments/toc-panel/toc-panel.ts

* For `DocEditor` and `EdgelessEditor`, `editor.host.value` -> `editor.host`.
* Also renames `editor.root` -> `editor.host` for `AffineEditorContainer`.

refactor: simplify `editor.host` getter without `.value`

---

packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
packages/blocks/src/surface-block/grid.ts

to fix console error from:
1. note-slicer on deleting top level note block
2. GridManager on deleting image/bookmark block inside top level note
https://github.com/toeverything/blocksuite/assets/54364088/a9c8aaa2-a2c6-460e-a8fb-688902e9b851

fix(edgeless): console error on block delete

---

packages/playground/apps/starter/env.d.ts
packages/playground/apps/starter/utils.ts

The block model is wrapped in a proxy which makes it difficult to print useful information in the console. The [Custom Formatters](https://firefox-source-docs.mozilla.org/devtools-user/custom_formatters/index.html) allow us to config how a variable can be printed in the console which can help us solve this problem. 
I wrote a small print formatter that can print all the props of the given block model. It should be sufficient in most cases.
Before:
After:
**Note**: You need to check the `Enable custom formatters` in the Devtools preference to make it work.

feat: add print formatter for the block model

---

packages/blocks/src/page-block/edgeless/controllers/clipboard.ts

To close #5520 
https://github.com/toeverything/blocksuite/assets/99816898/d5c652d9-b830-45ab-815e-97339483ca93

fix(edgeless): note background lost when copy as png

---

packages/playground/apps/default/main.ts
packages/playground/apps/starter/main.ts

Before converting contentParser to page service, make sure that the playground can work normally for the time being.
Note: ContentParser and its related usage will be removed later.

fix(playground): editor host undefined

---

packages/blocks/src/page-block/commands/text-crud/delete-text.ts

Fix text cut: didn't filter out and delete the blocks between fromElement and toElement.
before:
https://github.com/toeverything/blocksuite/assets/99816898/2c9c2ba0-e2f9-4048-87cd-aeacef6aaf4f
after:
https://github.com/toeverything/blocksuite/assets/99816898/f8adcfe8-b1ab-47eb-aa00-d98ebefae200

fix(page): onCut should delete blocks between fromElement and toElement

---

tests/image.spec.ts
tests/list.spec.ts
tests/markdown.spec.ts
tests/slash-menu.spec.ts
tests/utils/actions/keyboard.ts
tests/utils/actions/misc.ts

It is a reliability test for the `InlineEditor`
This pull request reduces the typing delay in the test from `50` milliseconds to `20` milliseconds.
If set to `10ms`, it may cause random test failures. Most failures occur due to insufficient delay after `pressEnter`.

chore: reduce delay of user input behavior in test

---

packages/blocks/src/bookmark-block/bookmark-service.ts
packages/blocks/src/bookmark-block/utils.ts

``` js
const bookmarkService = editorRoot.spec.getService('affine:bookmark') as ImageService;
bookmarkService.setLinkPreviewEndpoint('https://example.com/link-preview');
```

feat: allow change link preview endpoint

---

packages/blocks/src/page-block/doc/doc-page-block.ts
tests/edgeless/group.spec.ts
tests/edgeless/note.spec.ts
tests/hotkey.spec.ts
tests/paragraph.spec.ts

fix(page): enter in title move cursor

---

packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/bookmark-block/components/bookmark-card.ts
packages/blocks/src/bookmark-block/doc-bookmark-block.ts
packages/blocks/src/bookmark-block/styles.ts
packages/blocks/src/bookmark-block/utils.ts

[TOV-383](https://linear.app/affine-design/issue/TOV-383/the-display-of-links-for-which-no-information-was-fetched-does-not)

fix: title & description on generic link card when fetch failed

---

packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/image-block/image-block.ts
packages/blocks/src/note-block/note-block.ts
packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts

bug: 
https://github.com/toeverything/blocksuite/assets/54364088/cfaa3dc6-bd12-4847-bbc8-01406acbdba3

fix(page): dragStart for bookmark / embed / image block

---

packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
packages/blocks/src/embed-github-block/embed-github-service.ts
packages/blocks/src/embed-github-block/styles.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-youtube-block/embed-youtube-service.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
packages/blocks/src/page-block/page-service.ts

[TOV-380](https://linear.app/affine-design/issue/TOV-380/github-links-should-not-have-an-embed-view)

fix: treat embed-* blocks without iframe as card view

---

packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
packages/store/src/indexer/backlink.ts

adding backlink support for `affine:embed-linked-doc`

fix(page): show backlink for `affine:embed-linked-doc`

---

packages/blocks/src/_common/inline/presets/affine-inline-specs.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-config.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/database-block/database-service.ts
packages/blocks/src/list-block/list-service.ts
packages/blocks/src/paragraph-block/paragraph-service.ts

In some situations, we need to pass certain configurations from the outside to the `reference-node`. This PR enables us to convey these configurations through the service.
```ts
// support affine:paragraph, affine:list and affine:database now
const service = block.service;
const referenceNodeConfig = service.referenceNodeConfig;
// setup `Page`
this.referenceNodeConfig.setPage(page);
// config custom icon and title
this.referenceNodeConfig.setCustomIcon(customIcon);
this.referenceNodeConfig.setCustomTitle(customTitle);
// fully customized content (interactions of click and hover will still be retained)
this.referenceNodeConfig.setCustomContent(customContent);
```

feat: support config `reference-node` externally

---

packages/blocks/src/_common/configs/quick-action/config.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-service.ts
tests/format-bar.spec.ts
tests/hotkey.spec.ts

Changes:
- Implemented logic for creating new linked page with block selections in doc editor
- Format-bar widget will show an icon to create linked page, when only blocks are selected.
- Linked page can be created using toolbar or shortcut (mod+shift+L).
- If the first selection is a heading(h1-h6), it will be used as the linked-page title.
- `embedLinkedDocService.slots.linkedDocCreated` will emit pageId on linked page creation, toast to be implemented in affine.

feat(page): create linked doc from block selection

---

packages/blocks/src/bookmark-block/components/bookmark-card.ts
packages/blocks/src/embed-figma-block/embed-figma-block.ts
packages/blocks/src/embed-github-block/embed-github-block.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-youtube-block/embed-youtube-block.ts

[AFF-540](https://linear.app/affine-design/issue/AFF-540/double-clicking-on-the-linked-doc-does-not-open-the-corresponding-doc)

fix(edgeless): enable double click on cards in surface

---

packages/blocks/src/_common/adapters/markdown.ts
packages/store/src/adapter/context.ts

This pull request adds support for parsing bookmark blocks as links in Markdown.

feat(page): support for parsing bookmarks as links in Markdown

---

packages/blocks/src/note-block/note-model.ts
packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/widgets/drag-handle/config.ts
packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
packages/blocks/src/page-block/widgets/drag-handle/utils.ts

[TOV-372](https://linear.app/affine-design/issue/TOV-372/note-%E7%9A%84%E7%BC%A9%E6%94%BE)
Changes:
- Added scaling support for note by adding new prop `scale` to `NoteBlockModel`.
- Shift + corner resize will update scale & xywh in model.
- Normal resize will update just xywh in model.
- Updated calculations for collapsed content and collapse arrow.
- Disabled edge resize on note when shift key is pressed.
Should be non-breaking

feat(edgeless): support note scaling on shift + corner resize

---

packages/block-std/src/index.ts
packages/blocks/src/_common/adapters/index.ts
packages/blocks/src/_common/adapters/mix-text.ts
packages/blocks/src/code-block/clipboard/index.ts
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/page-block/clipboard/index.ts

Codes like yaml, which starts with -, still cannot properly handled by MixTextAdapter.
In this PR, we adopt a temporary measure which adds new clipboards instance to code blocks.
This closes #6004.

feat(page): code clipboard

---

packages/blocks/src/_common/adapters/html.ts
packages/blocks/src/_common/adapters/image.ts
packages/blocks/src/_common/adapters/markdown.ts
packages/blocks/src/_common/adapters/mix-text.ts
packages/blocks/src/_common/adapters/notion-html.ts
packages/blocks/src/_common/adapters/plain-text.ts
packages/blocks/src/_common/transformers/markdown.ts
packages/blocks/src/_common/transformers/zip.ts
packages/blocks/src/surface-block/service/template.ts
packages/store/src/__tests__/__snapshots__/transformer.unit.spec.ts.snap
packages/store/src/transformer/base.ts
packages/store/src/transformer/job.ts
packages/store/src/transformer/slice.ts
packages/store/src/transformer/type.ts
tests/snapshots/clipboard.spec.ts-snapshots/clipboard.json

In favor of https://github.com/toeverything/blocksuite/pull/6065

chore: remove `blockVversions` in snapshot

---

packages/blocks/src/_common/export-manager/export-manager.ts

To fix [TOV-401](https://linear.app/affine-design/issue/TOV-401/png导出大小有问题（右边多出很多空格，且长内容会被截断）)
https://github.com/toeverything/blocksuite/assets/99816898/af136d50-9e22-445f-af27-befbcd854860
https://github.com/toeverything/blocksuite/assets/99816898/db1e2b74-a478-4cb5-b677-d3c1e0f8d04a

fix(page): export png position shift

---

packages/blocks/src/paragraph-block/paragraph-block.ts

fix: should not show placeholder when composing

---

packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
packages/blocks/src/surface-block/element-model/base.ts
packages/blocks/src/surface-block/element-model/connector.ts
packages/blocks/src/surface-block/element-model/decorators.ts
packages/blocks/src/surface-block/element-model/index.ts
packages/blocks/src/surface-block/managers/connector-manager.ts
packages/blocks/src/surface-block/middlewares/connector.ts
packages/blocks/src/surface-block/surface-model.ts
packages/playground/apps/starter/components/pages-panel.ts
packages/store/src/workspace/block/block.ts
packages/store/src/workspace/page.ts
tests/edgeless/clipboard.spec.ts

- Defer the connectors' path updating to avoid double calculation
- Call mount after creating models
- Connectors' path should be updated when the xywh prop gets updated.
- Prevent `pop` from writing value to the ymap when the property is a local one
- Emit event in block observeDeep

fix(edgeless): bugs of connector and block

---

packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
packages/blocks/src/code-block/code-block.ts
tests/attachment.spec.ts
tests/bookmark.spec.ts
tests/code.spec.ts
tests/image.spec.ts
tests/utils/asserts.ts

In order to fix a certain test, incidentally improved the experience when pressing the backspace key after certain blocks.
https://github.com/toeverything/blocksuite/assets/50035259/c44ff633-e0cc-4f64-a306-6ffcf1c9ec91

fix: line number container in code-block should not contenteditable

---

packages/blocks/src/page-block/edgeless/utils/note.ts
tests/edgeless/selection.spec.ts

To fix [TOV-454](https://linear.app/affine-design/issue/TOV-454/新-note-通过选区创建后-无法使用-auto-size-custom-size-的切换)
https://github.com/toeverything/blocksuite/assets/99816898/12cb198c-368b-4f39-8d2c-e8e032745fa8

fix(edgeless): drag to add note should support collapse

---

packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts

closes #6034 
Changes:
- For Note - will show curve icon on hover if shift is pressed
- For Image / Attachment / Bookmark / Embed-* - show curve icon on hover
Curve icon and scale percent will always show while scaling.

fix(edgeless): show curve icon on resize handle hover before scaling starts

---

packages/blocks/src/page-block/widgets/slash-menu/config.ts
packages/blocks/src/page-block/widgets/slash-menu/utils.ts

Fix https://github.com/toeverything/blocksuite/issues/6092
In the previous logic, empty lines were removed by some slash actions regardless of the outcome. Now, only successful actions will remove the empty lines.

fix(page): should not remove empty lines when canceling an action

---

packages/blocks/src/embed-github-block/utils.ts

fix: show github status on update

---

packages/blocks/src/page-block/edgeless/controllers/tools/index.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/edgeless-page-service.ts
packages/blocks/src/page-block/edgeless/services/tools-manager.ts

- Move the tools manager to the service
- Tool can be registered dynamically through `tool.register` method

refactor(edgeless): move edgeless tool to service

---

packages/blocks/src/_common/components/file-drop-manager.ts
packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
packages/blocks/src/page-block/page-service.ts

[TOV-426](https://linear.app/affine-design/issue/TOV-426/图片拖入后，卡住-insert-的-ui，并且添加图片不生效。)

fix(edgeless): prevent file drop indicator on block elements in surface

---

packages/blocks/src/list-block/list-block.ts
packages/blocks/src/list-block/utils/get-list-icon.ts

fix: list number should not be contenteditable

---

packages/blocks/src/surface-block/managers/edit-session.ts

Fix [AFF-237](https://linear.app/affine-design/issue/AFF-237/confirm-the-modified-scope-of-shapenotesconnector-toolbar)

fix(edgeless): don't record last props in session

---

packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts

[TOV-509](https://linear.app/affine-design/issue/TOV-509/linked-pageweb-toolbar-should-not-be-displayed-when-the-page-is-in)
closes #6137

fix(page): linked page/web toolbar should not be displayed when the page is in read-only mode

---

packages/blocks/src/_common/components/embed-card/embed-card-caption.ts
packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
packages/blocks/src/_common/components/embed-card/embed-card-style-popper.ts
packages/blocks/src/_common/consts.ts
packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/_common/types.ts
packages/blocks/src/_common/utils/model.ts
packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/embed-figma-block/embed-figma-block.ts
packages/blocks/src/embed-html-block/embed-html-block.ts
packages/blocks/src/embed-html-block/embed-html-model.ts
packages/blocks/src/embed-html-block/embed-html-spec.ts
packages/blocks/src/embed-html-block/index.ts
packages/blocks/src/embed-html-block/styles.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
packages/blocks/src/image-block/image-block.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
packages/blocks/src/page-block/edgeless/utils/query.ts
packages/blocks/src/surface-block/edgeless-types.ts

[Figma](https://www.figma.com/file/JbC1cSHY4tDerKhpSjOXa6/%F0%9F%8F%A1-2024-S1?type=design&node-id=961%3A19305&mode=dev)
Changes:
- Updated embed-html card style (doc & edgeless)
- Added support for caption (doc & edgeless)
- Added support for resize - horizontal, vertical & diagonal (edgeless only)
- Added support for full screen view
- Added toolbar button in edgeless
- Added clipboard support
- Added drag & drop support - surface to note & vice-versa
Pending:
- Toolbar in doc mode (design needed)

feat(edgeless): embed-html style update

---

packages/blocks/src/_common/export-manager/export-manager.ts
packages/blocks/src/page-block/edgeless/controllers/clipboard.ts

To fix #5552 
This issue is due to the fact that when the svg does not set the width and height, but only sets the viewBox, it will adaptively change the size, causing only a small part of the rendering result to be displayed. If the width and height of an svg are set correctly, the exported svg will be complete. 
In order to solve this problem, special processing needs to be done when the img src is svg, and the width and height of svg need to be set.
Since there is no way to directly determine whether the img is of svg type from the url suffix of the img src, we need to fetch the blob first and then determine the blob type, which may cause the export time to become longer.
https://github.com/toeverything/blocksuite/assets/99816898/8f6137fa-8079-4966-b008-46cf45f6dc87

fix: export png incorrectly when svg without width and height

---

packages/blocks/src/_common/adapters/markdown.ts

This pull request removes the duplicated title when exporting markdown.

fix: remove duplicated title when exporting markdown

---

packages/blocks/src/frame-block/frame-block.ts
packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-frame-button.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
packages/blocks/src/page-block/edgeless/components/presentation/edgeless-navigator-black-background.ts
packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-order-menu.ts
packages/blocks/src/page-block/edgeless/components/toolbar/frame/navigator-setting-button.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts

[TOV-499](https://linear.app/affine-design/issue/TOV-499/frame-title-disappear-after-reordering-frames)
closes #6125

fix(edgeless): frame title disappear after reordering frames

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/change-frame-button.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-group-button.ts

When insert frame or group into page, should insert into the last doc visible note. If there is no doc visible note, should create a new one then insert the frame or group into it.
To fix [TOV-527](https://linear.app/affine-design/issue/TOV-527/unable-to-insert-frame-into-page)

fix(edgeless): insert frame/group into page

---

packages/blocks/src/page-block/widgets/linked-doc/config.ts
packages/blocks/src/page-block/widgets/slash-menu/config.ts
tests/linked-page.spec.ts
tests/slash-menu.spec.ts

In order to distinguish between `doc` and `page mode` [TOV-532](https://linear.app/affine-design/issue/TOV-532/affine-侧-page-名称更改为-doc)

chore: replace ambiguous "page" with "doc"

---

packages/blocks/src/database-block/database-block.ts

Fix https://github.com/toeverything/blocksuite/issues/6071
This pull request fixes an issue where the last database view was not being deleted properly. 
Before
https://github.com/toeverything/blocksuite/assets/18554747/891a4c92-095b-4be6-aad8-9feeb1e7eaae

fix(page): delete block when deleting the last database view

---

packages/blocks/src/_common/transformers/html.ts
packages/blocks/src/_common/transformers/index.ts
packages/blocks/src/_common/transformers/markdown.ts
packages/blocks/src/_common/transformers/zip.ts
packages/blocks/src/page-block/page-service.ts
packages/playground/apps/default/components/quick-edgeless-menu.ts

This allows importing and exporting page(s) easily in AFFiNE.
``` ts
const pageService = host.spec.getService('affine:page') as PageService;
const htmlTransformer = pageService.transformers.html;
htmlTransformer.exportPage(page);
const markdownTransformer = pageService.transformers.markdown;
markdownTransformer.exportPage(page);
const zipTransformer = pageService.transformers.zip;
zipTransformer.exportPages(workspace, [page]);
```

refactor: expose transformers on page service

---

packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
packages/blocks/src/page-block/edgeless/components/toolbar/note/note-tool-button.ts
packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-button.ts
packages/blocks/src/page-block/edgeless/components/zoom/zoom-toolbar.ts
packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
packages/blocks/src/page-block/edgeless/controllers/tools/note-tool.ts
packages/blocks/src/page-block/edgeless/controllers/tools/pan-tool.ts
packages/blocks/src/page-block/edgeless/controllers/tools/shape-tool.ts
packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/page-block/edgeless/edgeless-page-service.ts
packages/blocks/src/page-block/edgeless/services/tools-manager.ts
packages/blocks/src/page-block/edgeless/utils/note.ts
packages/blocks/src/page-block/widgets/block-hub/config.ts
packages/presets/src/fragments/outline-panel/header/outline-panel-header.ts

- Move edgeless page slots to edgeless page service and remove some slots.
- Move zoom related actions to service.
- Uniformly use toolManager.setEdgelessTool when changing tool types.

refactor: move edgeless page slots to edgeless page service

---

packages/blocks/src/_common/components/block-selection.ts
packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/bookmark-block/components/bookmark-card.ts
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/divider-block/divider-block.ts
packages/blocks/src/embed-figma-block/embed-figma-block.ts
packages/blocks/src/embed-github-block/embed-github-block.ts
packages/blocks/src/embed-html-block/embed-html-block.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
packages/blocks/src/image-block/image-block.ts
packages/blocks/src/list-block/list-block.ts
packages/blocks/src/paragraph-block/paragraph-block.ts
tests/attachment.spec.ts
tests/bookmark.spec.ts
tests/code.spec.ts
tests/drag.spec.ts
tests/format-bar.spec.ts
tests/image.spec.ts
tests/selection/block.spec.ts
tests/selection/native.spec.ts

Changes:
- simplify the usage of `affine-block-selection`
i.e. replace
```ts 
${this.selected?.is('block')
? html`<affine-block-selection></affine-block-selection>`
: nothing}
```
with 
```ts 
<affine-block-selection .block=${this}></affine-block-selection>
```

refactor: simplify the usage of `affine-block-selection`

---

packages/blocks/src/page-block/doc/doc-page-block.ts
packages/blocks/src/page-block/doc/doc-page-service.ts

refactor: move doc page block slots to service

---

packages/blocks/src/page-block/edgeless/components/toolbar/common/slide-menu.ts

https://caniuse.com/css-overscroll-behavior
https://github.com/toeverything/blocksuite/assets/27926/b23608a9-5c0f-4da7-9162-6818fd59955e

fix: disable two fingers back/forward swipe in chrome

---

packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts

Subject: Feature Enhancement: Spacebar Toggle for Pan Mode in EdgelessMode
I've observed that using the middle mouse button is quite handy for switching to hand mode during drawing in EdgelessMode, as a dedicated Photoshop user, I believe it is more ergonomic to use the spacebar with the LMB to switch to the pan mode while drawing. To enhance the user experience, I've refactored to enable the use of the spacebar to toggle between pan mode and brush/eraser mode seamlessly.
Pull Request Changes:
- Use the spacebar to switch to pan mode while in brush | eraser mode

feat: use spacebar to switch to pan in brush and eraser mode

---

packages/blocks/src/_common/components/hover/when-hover.ts

Fix https://github.com/toeverything/blocksuite/issues/6202
This pull request adds the `capture` option to the `mouseover` and `mouseleave` event listeners, ensuring that the listeners can correctly capture the events.

fix: format bar popup disappears on edgeless

---

packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts

bug: 
https://github.com/toeverything/blocksuite/assets/54364088/a2b2091b-4126-4f0d-9dcf-0ee5138812cf

fix(page): synced block placeholder should not appear after adding content

---

packages/blocks/src/page-block/edgeless/edgeless-page-service.ts

Active event dispatcher when edgeless tool updated if current event dispatcher is inactive, otherwise some tool controller event like pointerMove would not be dispatched and the tool overlay would not be displayed when first time switch to edgeless mode.
before:
https://github.com/toeverything/blocksuite/assets/99816898/90c1d639-9e1b-4de8-95a6-4cf246b6ce74
after:
https://github.com/toeverything/blocksuite/assets/99816898/a3e8d772-1010-4845-8c6f-3ca5c17e3821

fix(edgeless): active eventDispatcher when edgeless tool updated

---

packages/blocks/src/_common/components/rich-text/rich-text.ts
packages/blocks/src/note-block/note-block.ts
packages/framework/inline/src/inline-editor.ts
packages/framework/inline/src/services/range.ts
packages/framework/lit/src/utils/range-binding.ts
packages/framework/lit/src/utils/range-manager.ts

Test 600+ lines code:
before:
after:
For further optimization, we may need to refactor the rendering mechanism of the inline editor.

fix: improve code block performance

---

packages/blocks/src/_common/adapters/utils.ts

Changes:
- Added response.ok check for image fetch via proxy, as fetch does not throw error for non-200 statuses.
Linked with https://github.com/toeverything/AFFiNE/pull/5849

fix(page): correct image fetch via proxy with response.ok check

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts

To fix:
[TOV-453](https://linear.app/affine-design/issue/TOV-453/新-note-通过选区创建的-note，点击后-more-后，直接关闭了-toolbar)
[TOV-471](https://linear.app/affine-design/issue/TOV-471/group-toolbar-点more无法激活)
Should not select edgeless component toolbar text and should not trigger selectionchange event when click toolbar button.
https://github.com/toeverything/blocksuite/assets/99816898/1e4701d6-e71b-491f-ade8-7a1bc6b112ce

fix(edgeless): cannot click more button in AFFiNE

---

.github/CLA.md
packages/blocks/src/database-block/kanban/controller/hotkeys.ts

fix: arrow buttons are disabled when kanban exists in page

---

packages/playground/apps/default/utils/editor.ts
packages/playground/apps/starter/data/multiple-editor.ts
packages/playground/apps/starter/utils/editor.ts

Step to reproduce bug:
1. new a link page
2. refresh page
3. click page
What is actually happening:
page have not redirect but console log root model miss.

fix(playground): missing root model after refresh page

---

packages/blocks/src/page-block/edgeless/components/toolbar/common/slide-menu.ts

`slide-menu-content` should be the same height as `menu-container`

fix(edgeless): slide menu content height

---

packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
packages/blocks/src/surface-block/managers/edit-session.ts
packages/blocks/src/surface-ref-block/surface-ref-block.ts
packages/blocks/src/surface-ref-block/surface-ref-service.ts
packages/playground/apps/components/debug-menu.ts
packages/playground/apps/starter/utils/editor.ts
packages/presets/src/editors/editor-container.ts

Related to [TOV-536](https://linear.app/affine-design/issue/TOV-536/view-in-edgeless-%E6%8C%89%E9%92%AE%E4%B8%8D%E7%94%9F%E6%95%88%E4%BA%86)
The previous implementation always assumed the `AffineEditorContainer` existed while the latest version of AFFiNE replaced the `AffineEditorContainer` with its own implementation.
The solution is to add a new slot to tell the app to switch the mode. The blocksuite user needs to listen to that slot and switch the mode on their own.

fix: view in edgeless mode

---

packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts

[AFF-625](https://linear.app/affine-design/issue/AFF-625/handle-drop-outside-nested-editor-gracefully-without-stuck-ui)
part of [AFF-621](https://linear.app/affine-design/issue/AFF-621/unable-to-drag-the-blocks-out-from-the-synced-doc)
Changes:
- prevent stuck ui & dragPreview when dropped outside nested editor.

fix: handle drag and drop outside nested editor gracefully

---

packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
packages/blocks/src/_common/components/embed-card/embed-card-style-popper.ts
packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup-more-menu-popup.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup-more-menu-popup.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
packages/blocks/src/attachment-block/components/more-menu.ts
packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/attachment-block/components/styles.ts

Bug: due to 4px offset b/w toolbar and popup menu, if the gap is over another block which shows toolbar on hover, then current toolbar will close on moving mouse from toolbar through the gap to the popup.
https://github.com/toeverything/blocksuite/assets/54364088/ecbba892-902b-446c-abb9-edf1abe4cb0f

fix(page): popup menu should not close, when on top of hoverable block

---

packages/blocks/src/page-block/edgeless/services/tools-manager.ts

- The viewport no longer pans when right-clicking with tools other than the pan tool.
- Eliminated the creation of a custom PointerDownEvent in the ContextMenuEvent. Now, the actual PointerEvent is utilized, 
Addressed an issue where the default tool loaded from local storage was set in the toolbar but not activated for use. For instance, if the pan tool was set and the browser was reloaded, the toolbar displayed the pan tool, but the active tool was defaulted to default. 
https://github.com/toeverything/blocksuite/assets/123532141/e5dcf9e4-ad9b-4a6b-9f79-4f9f82bed97f

fix(edgeless): switching to hand tool while right clicking affine#5664

---

packages/blocks/src/attachment-block/styles.ts
packages/blocks/src/bookmark-block/styles.ts
packages/blocks/src/embed-figma-block/styles.ts
packages/blocks/src/embed-github-block/styles.ts
packages/blocks/src/embed-linked-doc-block/styles.ts
packages/blocks/src/embed-loom-block/styles.ts
packages/blocks/src/embed-synced-doc-block/styles.ts
packages/blocks/src/embed-youtube-block/styles.ts

[AFF-615](https://linear.app/affine-design/issue/AFF-615/once-the-card-exceeds-752px-it-will-not-adapt-to-the-width)
Changes:
- allow all block card to expand horizontally on note resize, affected blocks :

fix(page): allow block cards to expand horizontally on note resize

---

packages/blocks/src/page-block/edgeless/components/utils.ts

fix(edgeless): shift panel-wrapper to keep it in view

---

packages/blocks/src/_common/components/rich-text/rich-text-operations.ts

我看notion的行为就是在表格和image等block前的paragraph block按下delete键，会被直接忽略

fix:  console error when pressing delete key in the paragraph before a database

---

packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts

fix(edgeless): no need to adjust position of component-toolbar when more-actions-container is opened

---

packages/blocks/src/surface-block/elements/shape/consts.ts
packages/blocks/src/surface-block/managers/edit-session.ts

fix(edgeless): add default text color of shape-element

---

packages/blocks/src/embed-github-block/styles.ts

fix(edgeless): github icon size on note-menu

---

packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
tests/edgeless/reordering.spec.ts

fix(edgeless): redo for reordering

---

packages/blocks/src/schemas.ts
packages/playground/apps/default/utils/editor.ts
packages/playground/apps/default/utils/workspace.ts
packages/playground/apps/dev-format.ts
packages/playground/apps/starter/utils/editor.ts
packages/playground/apps/starter/utils/workspace.ts
packages/presets/src/__tests__/utils/setup.ts

Close #6317
This removes the legacy `__unstableSchemas`. For internal testing, we should switch to feature flags instead.
Note that this list of block schemas could be override as show in https://blocksuite.io/guide/working-with-block-tree.html#defining-new-blocks

refactor: remove the split of internal schemas

---

.github/CLA.md
packages/blocks/src/root-block/page/page-root-block.ts

When affine-page-root is used as a direct child element of editor-host, the style of editor-host does not take effect.
https://github.com/toeverything/blocksuite/assets/47590453/e71a18dd-300e-4fdd-a19c-c8853cf014e2

fix(page): the style of editor-host does not take effect

---

packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts

To close [AFF-626](https://linear.app/affine-design/issue/AFF-626/should-hide-the-embed-view-toolbar-entry-in-nested-synced-doc)
https://github.com/toeverything/blocksuite/assets/99816898/fb469f03-6a4e-4e33-8b2d-4b010e685a13

feat: disable embed view button when linked doc inside another embed synced doc

---

packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts

To support #6063 , add `assets` param to `toDocSnapshot` func.
Btw when the time of import is too long , it should add some operation like loading animate to make ensure the page link are inserted.

feat(page): support import external images

---

packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
packages/blocks/src/root-block/edgeless/utils/tool-overlay.ts
packages/blocks/src/surface-block/element-model/utils/shape/diamond.ts
packages/blocks/src/surface-block/element-model/utils/shape/ellipse.ts
packages/blocks/src/surface-block/element-model/utils/shape/rect.ts
packages/blocks/src/surface-block/element-model/utils/shape/triangle.ts

Fix https://github.com/toeverything/blocksuite/issues/6322
This pull request adds a draw function to the shape utils.
This allows the `AutoCompleteOverlay` to render different shapes.

fix(edgeless): auto-complete displays incorrect shape

---

packages/blocks/src/root-block/edgeless/components/toolbar/common/slide-menu.ts

https://github.com/toeverything/blocksuite/blob/0beb354f4bead57a2cc4fe7b42db71db6641c600/packages/blocks/src/root-block/edgeless/components/toolbar/common/slide-menu.ts#L132
here should use `event.deltaX`

fix(edgeless): menu-container scrolling in safari

---

packages/blocks/src/_common/transformers/zip.ts
packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/brush/index.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/text/index.ts
packages/blocks/src/surface-block/canvas-renderer/renderer.ts
packages/blocks/src/surface-block/element-model/base.ts
packages/blocks/src/surface-block/element-model/brush.ts
packages/blocks/src/surface-block/element-model/decorators.ts
packages/blocks/src/surface-block/element-model/index.ts
packages/blocks/src/surface-block/element-model/shape.ts
packages/blocks/src/surface-block/element-model/text.ts
packages/blocks/src/surface-block/surface-block.ts
packages/framework/store/src/transformer/job.ts

- Add new method `walk` into transformer `Job` to traverse a template (use to modify the snapshot content before importing start)
- Add property fallback to fix legacy template rendering
- Add `watch` decorator to watch element property change
- Add new local property `commands` to brush to avoid double computation
- Fix laggy multi-selection

fix(edgeless): fix laggy selection & legacy template rendering

---

packages/blocks/src/root-block/edgeless/components/component-toolbar/change-text-menu.ts
packages/blocks/src/root-block/edgeless/components/panel/font-family-panel.ts
packages/blocks/src/root-block/edgeless/components/panel/font-weight-and-style-panel.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/root-block/font-loader/font-loader.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/text/utils.ts
packages/blocks/src/surface-block/elements/text/utils.ts
packages/blocks/src/surface-block/utils/font.ts

The font family name should wrap in quotes. [CSS ident-tokens](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram)

fix(edgeless): fonts load and render in firefox

---

packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
packages/blocks/src/_common/consts.ts

To close #6327 
Forward delete before embed block will be ignored. 
Pressing backspace when adjacent to an embed block will select the embed block.

fix(page): handle delete or backspace align with embed block

---

packages/blocks/src/root-block/edgeless/components/component-toolbar/component-toolbar.ts

https://github.com/toeverything/blocksuite/assets/27926/3d8c4d7c-26d3-45ac-bd69-fc9fab58a9e7
https://github.com/toeverything/blocksuite/assets/27926/b7805c12-bc39-4ed9-b841-7fbad365d5f3

fix(edgeless): position should be calculated after the update is complete

---

packages/blocks/src/root-block/widgets/linked-doc/config.ts
packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts

This commit will break AFFiNE as `showImportModal` is referenced in AFFiNE.
```diff
export type OnSuccessHandler = (
pageIds: string[],
-  isWorkspaceFile: boolean
+  options: { isWorkspaceFile: boolean; importedCount: number }
) => void;
```
A fix will be introduced to AFFiNE later.

fix(page): skip adding reference node when importing notion zip

---

packages/blocks/src/surface-block/surface-model.ts
packages/presets/src/__tests__/main/snapshot.spec.ts

I uploaded two onboarding template snapshots from AFFiNE and used them as a legacy template rendering test. The test checks the properties of every surface element to ensure they are not nullish values. Additionally, the xywh property should match the correct pattern, and the counts of surface elements should also match the snapshot JSON. And, of course, there should be no error during the render process.

test: add test for legacy template

---

packages/blocks/src/_common/configs/quick-action/config.ts
packages/blocks/src/_common/configs/text-format/config.ts
packages/blocks/src/_common/configs/text-format/utils.ts
packages/blocks/src/_common/utils/command.ts
packages/blocks/src/code-block/clipboard/index.ts
packages/blocks/src/note-block/commands/utils.ts
packages/blocks/src/note-block/keymap-controller.ts
packages/blocks/src/root-block/clipboard/index.ts
packages/blocks/src/root-block/commands/model-crud/get-selected-models.ts
packages/blocks/src/root-block/commands/text-crud/format-block.ts
packages/blocks/src/root-block/commands/text-crud/format-text.ts
packages/blocks/src/root-block/root-service.ts
packages/blocks/src/root-block/widgets/format-bar/components/highlight/highlight-button.ts
packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
packages/blocks/src/root-block/widgets/slash-menu/config.ts
packages/docs/guide/command.md
packages/docs/guide/working-with-block-tree.md
packages/framework/block-std/src/__tests__/command.unit.spec.ts
packages/framework/block-std/src/command/manager.ts
packages/playground/apps/_common/components/debug-menu.ts
packages/presets/src/fragments/comment/comment-manager.ts
tests/utils/actions/block.ts

The `pipe` naming is so obscure that we even don't need to modify AFFiNE for the bump.

refactor: command.pipe -> command.chain

---

packages/blocks/src/note-block/commands/text-style.ts
packages/blocks/src/note-block/commands/utils.ts
packages/blocks/src/root-block/widgets/format-bar/components/config-renderer.ts
packages/blocks/src/root-block/widgets/format-bar/components/paragraph-button.ts
packages/blocks/src/root-block/widgets/format-bar/config.ts
packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
packages/blocks/src/root-block/widgets/format-bar/index.ts

```ts
// In root spec:
const defaultSetup = rootSpec.setup;
const mySpec = {
...rootSpec,
setup: (slots, disposableGroup) => {
defaultSetup(slots, disposableGroup);
const onFormatBarConnected = slots.widgetConnected.on(view => {
if (view.component instanceof AffineFormatBarWidget) {
configureFormatBar(view.component);
}
});
disposableGroup.add(onFormatBarConnected);
}
}
function configureFormatBar(formatBar: AffineFormatBarWidget) {
formatBar
.clearConfig()
.addParagraphDropdown()
.addDivider()
.addTextStyleToggle({
key: 'bold',
action: chain => chain.toggleBold().run(),
icon: BoldIcon,
})
.addTextStyleToggle({
key: 'italic',
action: chain => chain.toggleItalic().run(),
icon: ItalicIcon,
})
.addDivider()
.addHighlighterDropdown()
.addDivider()
.addBlockTypeSwitch({
flavour: …
```

feat: add format bar config api

---

packages/blocks/src/note-block/keymap-controller.ts

Closes #6411 
CC @Flrande 
The `page-image-block` also uses this wrapper.
https://github.com/toeverything/blocksuite/blob/047acfd2cb4e2305fba524be47ea67555ed1224e/packages/blocks/src/image-block/components/page-image-block.ts#L103-L118

fix(blocks): use requestAnimationFrame to update selection

---

packages/blocks/src/root-block/edgeless/components/panel/line-width-panel.ts
tests/edgeless/brush.spec.ts
tests/utils/actions/edgeless.ts

1. `flex-direction` does not need to be `row-reverse`
2. filter icons in a single loop

perf(edgeless): filter icons in line-width-panel

---

packages/framework/store/src/persistence/blob/utils.ts

fix https://github.com/toeverything/AFFiNE/issues/6049

fix(store): use lib0 sha256 when api not available

---

packages/blocks/src/root-block/page/page-root-block.ts
tests/selection/block.spec.ts
tests/utils/actions/misc.ts

Closes: [BS-55](https://linear.app/affine-design/issue/BS-55/note-分割后，全选功能在文档模式下也只对-page-note-生效了)

fix: select all in page mode
