toeverything/blocksuite

- packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts
- packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
- packages/playground/src/utils.ts
- tests/basic.spec.ts
- tests/bookmark.spec.ts
Bookmark maybe migrate to Affine soon, so just add a few test case
> test: add bookmark test case

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- packages/blocks/src/page-block/edgeless/components/surface-text-editor.ts
- tests/edgeless/text.spec.ts
> fix(edgeless): copy surface text

- packages/blocks/src/bookmark-block/utils.ts
- packages/store/src/space.ts
- packages/store/src/workspace/page.ts
fixed: https://github.com/toeverything/blocksuite/issues/2946
> fix: redo/undo should not affect bookmark internal update

- packages/blocks/src/__internal__/utils/rect.ts
- packages/blocks/src/__internal__/utils/rect.unit.spec.ts
- packages/blocks/src/__internal__/utils/std.ts
- packages/blocks/src/index.ts
- packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts
- packages/phasor/package.json
- packages/phasor/src/index.ts
- packages/phasor/src/utils/bound.ts
- packages/phasor/src/utils/bound.unit.spec.ts
- packages/phasor/src/utils/line.ts
- packages/phasor/src/utils/line.unit.spec.ts
- packages/phasor/src/utils/numerical.ts
- packages/phasor/src/utils/vec.ts
- packages/phasor/vitest.config.ts
- pnpm-lock.yaml
add some methods in  Point, Bound class
and add Line.intersect method
> feat: complement and add some edgeless utilies

- packages/blocks/src/__internal__/utils/block-range.ts
fixed: https://github.com/toeverything/blocksuite/issues/2489
> fix: toolbar do not trigger in edgeless mode in some case

- packages/blocks/src/__internal__/content-parser/index.ts
To fix #2991 
https://github.com/toeverything/blocksuite/assets/99816898/dca3ae85-8d0e-4646-98a0-3d2590e2ba9c
> fix: pasting code is not as expected

- packages/blocks/src/page-block/utils/container-operations.ts
fixed: https://github.com/toeverything/blocksuite/issues/2611
> fix: can not show slash menu if insert "/" before select block

- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-button.ts
- packages/blocks/src/page-block/edgeless/utils.ts
https://github.com/toeverything/blocksuite/assets/50035259/29d0f630-3c7b-44cd-9e01-676daa0015be
> feat(edgeless): change text default color between themes

- packages/playground/src/data/preset.ts
- packages/playground/src/main.ts
- packages/store/src/workspace/workspace.ts
To fix #3002 
https://github.com/toeverything/blocksuite/assets/99816898/ccfff4f9-c1d6-47af-a1bc-8541485f7c3e
> fix(playground): press cmd+z loss content when first time enter playground

- packages/blocks/package.json
- packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts
- packages/blocks/src/database-block/table/components/column-header/column-header.ts
- packages/blocks/src/database-block/table/components/edit-column-popup/column-type-popup.ts
- packages/blocks/src/database-block/table/components/edit-column-popup/edit-column-popup.ts
- packages/blocks/src/database-block/table/components/edit-column-popup/styles.ts
- packages/blocks/src/database-block/table/components/toolbar/toolbar-action-popup.ts
- packages/blocks/src/database-block/table/components/toolbar/toolbar.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
- packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/components/utils.ts
- packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-menu.ts
- packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-tool-button.ts
- packages/blocks/src/page-block/edgeless/toolbar/connector-tool/connector-menu.ts
- packages/blocks/src/page-block/edgeless/toolbar/connector-tool/connector-tool-button.ts
- pnpm-lock.yaml
> refactor: replace `@popperjs/core` with `@floating-ui/dom`

- packages/phasor/src/index.ts
- packages/phasor/src/utils/bound.ts
- packages/phasor/src/utils/math-utils.ts
- packages/phasor/src/utils/math-utils.unit.spec.ts
> feat(edgeless): add some utilies

- packages/blocks/src/components/linked-page/linked-page-popover.ts
Fix https://github.com/toeverything/AFFiNE/issues/2750
https://github.com/toeverything/blocksuite/assets/18554747/01ba8147-6098-4071-a515-cca09f03d9c0
Related to https://github.com/toeverything/blocksuite/pull/2767
> fix: link page menu active state

- packages/blocks/src/database-block/table/components/cell-container.ts
- packages/blocks/src/database-block/table/components/column-type/multi-select.ts
- packages/blocks/src/database-block/table/components/column-type/select/multi-tag-view.ts
- packages/blocks/src/database-block/table/components/edit-column-popup/column-type-popup.ts
before:
https://github.com/toeverything/blocksuite/assets/15389209/42afa95f-8813-4ed5-b427-54bef1c70e11
after:
https://github.com/toeverything/blocksuite/assets/15389209/f551609d-05a1-44f2-8164-4a9baf660f2f
> refactor(database): set the cell height after selecting select

- packages/blocks/src/page-block/default/selection-manager/utils.ts
before:
https://github.com/toeverything/blocksuite/assets/15389209/d31c9adf-447f-4df2-ae6e-d629f7dedc7e
after:
https://github.com/toeverything/blocksuite/assets/15389209/067bc24c-b736-4a60-b9aa-8a3784ec0735
> feat(database): drag inside the database without selecting the block

- packages/blocks/src/page-block/utils/const.ts
> chore: update database tooltip content

- packages/blocks/src/database-block/table/components/column-type/select/multi-tag-select.ts
> fix(database): select option icon color

- packages/blocks/src/page-block/edgeless/components/block-children-container.ts
> fix(database): wrong "+ new record" button position

- packages/blocks/src/components/slash-menu/config.ts
> feat(slash-menu): insert database after the current block

- packages/blocks/src/page-block/edgeless/consts.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/page-block/edgeless/toolbar/edgeless-toolbar.ts
- packages/editor/src/components/editor-container.ts
- tests/edgeless/basic.spec.ts
- tests/utils/asserts.ts
> feat(edgeless): keep viewport state between mode switch

- packages/blocks/src/__internal__/utils/std.ts
- packages/editor/src/utils/editor.ts
- tests/edgeless/block-hub.spec.ts
> fix(edgeless): click not remove database

- packages/blocks/src/database-block/table/components/column-header/column-header.ts
- tests/database/database.spec.ts
close: #3069
before:
https://github.com/toeverything/blocksuite/assets/15389209/4d88245e-9d6b-4de3-a012-b34222e27496
after:
https://github.com/toeverything/blocksuite/assets/15389209/3bb73fb2-2109-422f-b7ab-c3e00fe54c64
> feat(database): save the last title being edited

- packages/blocks/src/database-block/table/components/toolbar/toolbar.ts
> feat(database): hide the tooltip of "+ New Record" button in edgeless mode

- packages/editor/src/utils/editor.ts
> feat(database): set default width when dragging to create a database in edgeless mode

- packages/blocks/src/database-block/table/components/column-header/column-header.ts
- tests/database/database.spec.ts
> feat(database): save the last title being edited when add new column

- packages/blocks/src/__internal__/utils/common-operations.ts
- packages/blocks/src/__internal__/utils/filesys.ts
- packages/blocks/src/__internal__/utils/std.ts
- packages/blocks/src/bookmark-block/components/bookmark-create-modal.ts
- packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
- packages/blocks/src/components/slash-menu/config.ts
- packages/editor/src/utils/editor.ts
fixed: https://github.com/toeverything/blocksuite/issues/3093
> fix: can not drop bookmark with new frame in edgeless from block-hub

- packages/blocks/src/__internal__/content-parser/parse-html.ts
- tests/import.spec.ts
> fix: notion import error on todo

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/surface-block/surface-model.ts
- packages/playground/src/data/heavy-whiteboard.ts
- packages/playground/src/data/preset.ts
- packages/playground/src/data/utils.ts
- packages/store/src/base.ts
- packages/store/src/utils/jsx.ts
- packages/store/src/utils/utils.ts
- packages/store/src/workspace/workspace.ts
Closes: https://github.com/toeverything/blocksuite/issues/2939
> refactor(blocks): make elements as prop of surface block

- packages/blocks/src/__internal__/service/keymap.ts
- packages/playground/examples/virgo/test-page.ts
- packages/virgo/src/tests/virgo.spec.ts
- packages/virgo/src/utils/transform-input.ts
> fix(virgo): handle the deletion of selected text

- packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
> feat: the mouse pointer can become a gesture when dragging

- packages/blocks/src/page-block/edgeless/components/block-children-container.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
- packages/blocks/src/page-block/edgeless/components/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/components/hover-rect.ts
- packages/blocks/src/page-block/edgeless/components/utils.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- tests/edgeless/note.spec.ts
> feat(edgeless): update note ui

- packages/blocks/src/components/toast.ts
Refact toast because of update in  https://github.com/toeverything/blocksuite/pull/3168
> refactor: refact toast

- packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
- packages/blocks/src/page-block/edgeless/utils.ts
- tests/edgeless/note.spec.ts
Only check if the note is empty when adding note.
> refactor(edgeless): empty note

- packages/blocks/src/__internal__/rich-text/reference-node.ts
- packages/playground/src/components/debug-menu.ts
- packages/store/src/__tests__/workspace.unit.spec.ts
- packages/store/src/space.ts
- packages/store/src/workspace/page.ts
- packages/store/src/workspace/workspace.ts
Closes: https://github.com/toeverything/blocksuite/issues/3189
> fix(store): bring back remove page for subdoc

- packages/blocks/src/__internal__/content-parser/index.ts
This fixes the error introduced in #3205.
> fix: the incorrect import path

- packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
> feat(database): title column hide `Move Right`

- packages/blocks/src/page-block/edgeless/components/text/surface-text-editor.ts
> fix(edgeless): make cursor visible in empty text

- packages/blocks/src/components/drag-handle.ts
- packages/blocks/src/components/format-quick-bar/index.ts
- packages/blocks/src/page-block/default/utils.ts
- tests/format-quick-bar.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/2576
> feat: show format-bar when click drag handler

- packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
- packages/blocks/src/page-block/edgeless/components/edgeless-notes-container.ts
- packages/blocks/src/page-block/edgeless/components/text/surface-text-editor.ts
> feat(edgeless): update toolbar ui

- packages/blocks/src/page-block/edgeless/components/buttons/tool-icon-button.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
- tests/edgeless/shape.spec.ts
> feat(edgeless): improve toolbar ui

- packages/blocks/src/database-block/table/components/toolbar/toolbar.ts
related to: #3251
depends on `selection` and `eventDispatcher`
> feat(database): temporarily close the modal popup display

- packages/blocks/src/components/drag-handle.ts
- packages/blocks/src/page-block/default/selection-manager/selection-manager.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
- tests/edgeless/note.spec.ts
> fix(edgeless): click in page mode will add a new note automatically when no visible note

- packages/blocks/src/database-block/table/table-view.ts
closes: https://github.com/toeverything/blocksuite/issues/3250
> fix(database): scrollbar is missing

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/__internal__/clipboard/utils/pure.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- tests/edgeless/selection.spec.ts
- tests/utils/actions/edgeless.ts
Closes #2442
https://github.com/toeverything/blocksuite/assets/27926/42060d7d-5b07-42a2-8015-458e9fdea804
> feat(edgeless): support copy as PNG

- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
fixed: https://github.com/toeverything/blocksuite/issues/3246
> fix: bookmark toolbar hidden by the frame in edgeless mode

- packages/blocks/src/database-block/table/components/selection/selection.ts
- packages/blocks/src/database-block/table/components/toolbar/index.ts
1. The style of cell when editting
2. The style of `New Record` of the toolbar when dragging
/cc @zzj3720
> feat(database): update UI style

- packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
Fixes: https://github.com/toeverything/blocksuite/issues/3268
> fix: bookmark block z index 

- packages/blocks/src/bookmark-block/bookmark-block.ts
fixed: https://github.com/toeverything/blocksuite/issues/2601
> fix: prepend "https" if url without protocol when bookmark click to open

- packages/blocks/src/page-block/edgeless/components/buttons/toolbar-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/note/note-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/zoom/zoom-bar-toggle-button.ts
- packages/blocks/src/page-block/edgeless/components/zoom/zoom-tool-bar.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/global/src/config/icons/edgeless.ts
- tests/utils/actions/edgeless.ts
update edgeless toolbar ui and zoom bar position
> feat: update edgeless toolbar ui and zoom bar position

- packages/blocks/src/__internal__/rich-text/reference-node.ts
- packages/blocks/src/page-block/default/default-page-block.ts
- tests/format-quick-bar.spec.ts
> style: adjust link page style and add padding for title

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
> fix(edgeless): edgeless toolbar position not updated when viewport changed

- packages/blocks/src/__internal__/content-parser/parse-html.ts
> fix: notion import error on bookmark

- packages/blocks/src/page-block/edgeless/connector-manager.ts
- packages/phasor/src/index.ts
- packages/phasor/src/utils/a-star.ts
- packages/phasor/src/utils/graph.ts
- packages/phasor/src/utils/graph.unit.spec.ts
- packages/phasor/src/utils/math-utils.ts
- packages/phasor/src/utils/math-utils.unit.spec.ts
- packages/phasor/src/utils/priority-queue.ts
- packages/phasor/src/utils/priority-queue.unit.spec.ts
- packages/playground/src/data/preset.ts
- tests/edgeless/connector.spec.ts
- tests/utils/actions/edgeless.ts
Optimize some elbow path
before
after
before
after
> fix(edgeless): optimize elbow connector path structure

- packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
> fix(edgeless): the selected rect follow snap

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/__internal__/utils/common.ts
- tests/edgeless/clipboard.spec.ts
- tests/edgeless/connector.spec.ts
- tests/utils/actions/edgeless.ts
- tests/utils/asserts.ts
closes #3295 
The expectd behaviour:
> fix(edgeless): fix connector paste bugs

- packages/blocks/src/database-block/table/components/column-header/column-width-drag-bar.ts
> fix(database): width adjust preview has wrong position

- packages/blocks/src/code-block/components/code-option.ts
- packages/blocks/src/image-block/image/image-options.ts
Fix https://github.com/toeverything/blocksuite/issues/3292
> fix: switch to popover z index variable

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/image-block/image/utils.ts
closes: #3320
related to: https://github.com/toeverything/AFFiNE/pull/3005
> fix: console error when copying as image

- packages/editor/src/utils/editor.ts
fixed: https://github.com/toeverything/blocksuite/issues/3323
> fix: can not insert bookmark in correct position from block hub

- packages/blocks/src/components/tags/multi-tag-select.ts
- packages/blocks/src/page-block/default/meta-data/meta-data.ts
close: #3332
https://github.com/toeverything/blocksuite/assets/15389209/cee35cba-5d0c-48ec-90b0-62252f3d84a5
> fix(database): prevent tag from being selected when compsing

- packages/blocks/src/page-block/default/meta-data/backlink/backlink-popover.ts
related: [#3013](https://github.com/toeverything/AFFiNE/issues/3013)
> fix: backlink jump does not work

- packages/blocks/src/components/toast.ts
Revert https://github.com/toeverything/blocksuite/pull/3183
Fix https://github.com/toeverything/blocksuite/issues/3339
> fix: toast unstable

- packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
- packages/blocks/src/database-block/table/table-view-manager.ts
> feat(database): hide the `Move Left` of the first normal column

- packages/blocks/src/__internal__/rich-text/rich-text.ts
- tests/basic.spec.ts
fixed: https://github.com/toeverything/blocksuite/issues/3347
> fix: text before the link incorrectly automatically recognized as part of the link

- packages/phasor/src/elements/brush/brush-element.ts
- packages/phasor/src/elements/shape/shape-element.ts
- packages/phasor/src/elements/shape/shapes/diamond.ts
- packages/phasor/src/elements/shape/shapes/ellipse.ts
- packages/phasor/src/elements/shape/shapes/rect.ts
- packages/phasor/src/elements/shape/shapes/triangle.ts
- packages/phasor/src/elements/shape/types.ts
> fix(edgeless): multi-selection of shape elements

- packages/blocks/src/page-block/edgeless/components/note-cut/cut-button.ts
- packages/blocks/src/page-block/edgeless/components/note-cut/cut-indicator.ts
- packages/blocks/src/page-block/edgeless/components/note-cut/index.ts
- dark mode for scissors button
- add transition for cut indicator
- add transition for scissors movement under the same note
- reduce duration of button popup transition
- hide the scissors button when not using cursor or when dragging
> feat(edgeless): optimize note cut interaction details

- packages/blocks/src/__internal__/service/json2block.ts
> fix: cursor jump when pasting text

- packages/blocks/src/components/link-popover/link-popover.ts
- packages/blocks/src/database-block/table/components/column-type/link.ts
close: #3351
https://github.com/toeverything/blocksuite/assets/15389209/e65a6254-9f1a-4c39-9f7a-f140de8d50d0
> fix(database): normalize url of link column

- packages/blocks/src/database-block/table/components/selection/selection.ts
close: #3330
https://github.com/toeverything/blocksuite/assets/15389209/e184da9e-e1f4-421a-b503-0f45d907ab06
> fix(database): enter row level selection on click drag handle

- packages/blocks/src/__internal__/utils/types.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/note/note-tool-button.ts
- packages/blocks/src/page-block/edgeless/tool-controllers/note-tool.ts
- packages/blocks/src/page-block/edgeless/tool-controllers/shape-tool.ts
- packages/blocks/src/page-block/edgeless/utils/consts.ts
- packages/blocks/src/page-block/edgeless/utils/hotkey.ts
- packages/phasor/src/index.ts
- packages/phasor/src/renderer.ts
> feat(edgeless): add overlay for note and shape tool

- packages/blocks/src/page-block/edgeless/tool-controllers/note-tool.ts
> fix(edgeless): note overlay padding issue

- packages/blocks/src/database-block/table/components/selection/selection.ts
related to: #3363
https://github.com/toeverything/blocksuite/assets/15389209/7c11679a-cdc6-421e-a281-e99095ca7dfc
> feat(database): optimize row selection

- packages/blocks/src/page-block/edgeless/components/text/surface-text-editor.ts
> fix(edgeless): add z-index in canvas text editor

- packages/blocks/src/page-block/edgeless/tool-controllers/shape-tool.ts
- packages/blocks/src/page-block/edgeless/utils/consts.ts
- tests/edgeless/shape.spec.ts
> feat(edgeless): click to add shape with shape tool

- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts
- packages/blocks/src/page-block/edgeless/components/panel/color-panel.ts
> fix(edgeless): fix incorrect connector color state

- packages/blocks/src/page-block/edgeless/components/note-cut/index.ts
> fix(edgeless): reset selected blocks after clipping note

- packages/blocks/src/__internal__/rich-text/link-node/affine-link.ts
- packages/blocks/src/__internal__/rich-text/link-node/create-link.ts
- packages/blocks/src/__internal__/rich-text/link-node/index.ts
- packages/blocks/src/components/link-popover/create-link-popover.ts
- packages/blocks/src/components/link-popover/create-link.ts
- packages/blocks/src/page-block/utils/format-config.ts
Fix https://github.com/toeverything/blocksuite/issues/3346
> fix: hide turn card btn when the link inside database

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- tests/bookmark.spec.ts
fixed: https://github.com/toeverything/AFFiNE/issues/2845
> fix: can not paste url to create bookmark

- package.json
- pnpm-lock.yaml
- tests/utils/playwright.ts
From 1.33.0 to 1.35.1
Release notes https://github.com/microsoft/playwright/releases
> chore: bump playwright

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/components/resize/resize-handles.ts
- packages/blocks/src/page-block/edgeless/components/utils.ts
closes: #3369
https://github.com/toeverything/blocksuite/assets/27926/22612a71-946c-4a3e-a4ed-7a86f08cce37
> fix(edgeless): cursor when resizing

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
close #3385
The bug demands a more comprehensive approach to resolve. This PR is only a (quick) stopgap solution
> fix(edgeless): lower the note height updating threshold

- packages/blocks/src/page-block/edgeless/components/buttons/tool-icon-button.ts
- packages/blocks/src/page-block/edgeless/components/zoom/zoom-bar-toggle-button.ts
- packages/blocks/src/page-block/edgeless/components/zoom/zoom-tool-bar.ts
> fix: adaptation vertical edgeless-zoom-toolbar

- packages/blocks/src/page-block/edgeless/utils/query.ts
- packages/phasor/src/consts.ts
- packages/phasor/src/index.ts
Closes #2651 
Add `GRID_GAP_MIN` and `GRID_GAP_MAX` to limit the value of grid gap
> fix(edgeless): add size limit for grid gap

- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-connector-button.ts
> fix(edgeless): connector toolbar stroke border

- packages/blocks/src/__internal__/rich-text/keyboard.ts
- packages/blocks/src/components/linked-page/index.ts
- packages/blocks/src/components/linked-page/linked-page-popover.ts
- packages/blocks/src/components/slash-menu/index.ts
- packages/blocks/src/components/utils.ts
- packages/blocks/src/page-block/index.ts
- packages/global/src/config/icons/import-export.ts
Part of https://github.com/toeverything/blocksuite/issues/3316
> refactor: migrate linked page to widget

- packages/blocks/src/components/format-quick-bar/index.ts
- packages/blocks/src/components/index.ts
- packages/blocks/src/page-block/default/selection-manager/selection-manager.ts
- packages/blocks/src/page-block/default/utils.ts
- packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
- packages/blocks/src/page-block/utils/container-operations.ts
Reduce two circular references.
Related: https://github.com/toeverything/blocksuite/issues/2689
> fix: circular import

- packages/blocks/src/__internal__/clipboard/utils/markdown.ts
- packages/blocks/src/__internal__/content-parser/index.ts
> fix: paste multi lines in windows

- packages/blocks/src/__internal__/clipboard/utils/commons.ts
> fix: remove windows html format clipboard fragment

- packages/blocks/src/code-block/code-block.ts
- tests/code.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/3456
> fix: code block lagging

- packages/blocks/src/page-block/edgeless/components/panel/color-panel.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/global/src/config/icons/edgeless.ts
Wait to close issue: 
https://github.com/toeverything/blocksuite/assets/99816898/889425f6-ae2d-4fc2-987e-b03aa7c4f3ed
> fix: brush icon color should be consistent with selected color

- packages/phasor/src/elements/shape/shapes/diamond.ts
- packages/phasor/src/elements/shape/shapes/ellipse.ts
- packages/phasor/src/elements/shape/shapes/rect.ts
- packages/phasor/src/elements/shape/shapes/triangle.ts
- tests/edgeless/shape.spec.ts
- tests/utils/actions/edgeless.ts
To close #3473 
https://github.com/toeverything/blocksuite/assets/99816898/9d18f509-3378-477b-b2d3-0f2984b05cb6
> fix(edgeless): change shape stroke style to none does not work

- packages/store/src/utils/utils.ts
> fix(edgeless): convert surface element to Y data structure only on first level

- packages/blocks/src/code-block/components/lang-list.ts
> fix: lang list z-index in code block

- packages/blocks/src/__internal__/content-parser/index.ts
- packages/blocks/src/components/tags/styles.ts
- packages/blocks/src/page-block/default/meta-data/meta-data.ts
> fix: redundant editing button on the exported file

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
FIXME: if multiple notes are selected, the image in the second note is lost.
> fix(edgeless): copy-as-png at different zoom levels

- packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts
- packages/blocks/src/code-block/components/code-option.ts
- packages/blocks/src/components/menu/menu.ts
- packages/blocks/src/components/slash-menu/slash-menu-popover.ts
- packages/blocks/src/components/slash-menu/styles.ts
- packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
- packages/blocks/src/database-block/table/components/toolbar/toolbar.ts
- packages/blocks/src/image-block/image/image-options.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
Close https://github.com/toeverything/AFFiNE/issues/3153
> chore: adjust delete item color

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/__internal__/content-parser/index.ts
- packages/phasor/src/renderer.ts
close #3490 #3492 #3489 #3496 #3497 #3498
> fix: copy as png

- packages/blocks/src/__internal__/rich-text/rich-text.ts
fixed: https://github.com/toeverything/blocksuite/issues/3481
> fix: fail to inteligent identify link string

- packages/blocks/src/database-block/table/table-view-manager.ts
> fix(database): search is too strict

- packages/blocks/src/database-block/table/components/column-type/title.ts
> fix(database): selection will flash when selecting text in title column

- packages/blocks/src/__internal__/content-parser/index.ts
We will use a better solution in the future https://github.com/toeverything/blocksuite/issues/3506
> fix: add default image proxy url

- packages/blocks/src/__internal__/utils/common-operations.ts
- tests/list.spec.ts
fix #3468
Thanks for your review ：）
> fix: don't forcefully change list type

- packages/blocks/src/database-block/table/components/column-type/title.ts
> fix(database): unable to `blur` from cell of title column

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
> fix: copy as PNG paste location is impacted by zoom

- packages/blocks/src/__internal__/service/json2block.ts
> fix(database): support pasting code block content

- packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
fixed https://github.com/toeverything/blocksuite/issues/3542
> fix: bookmark modal style error

- packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
> fix(edgeless): z-index of shape text editor

- packages/blocks/package.json
- packages/blocks/src/image-block/image/utils.ts
- pnpm-lock.yaml
> fix: the image in the page mode can not be copied and downloaded

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
> fix: filter connectors when rotating with multiselect

- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-button.ts
- packages/phasor/src/elements/index.ts
- packages/phasor/src/elements/text/utils.ts
- tests/edgeless/text.spec.ts
> fix(edgeless): text rect should be updated after changed font

- packages/blocks/src/components/slash-menu/config.ts
- packages/blocks/src/components/slash-menu/index.ts
- packages/blocks/src/components/slash-menu/utils.ts
Fix https://github.com/toeverything/blocksuite/issues/3485
> fix: ad-hoc the process key with ime

- packages/blocks/src/database-block/table/components/column-header/column-width-drag-bar.ts
close: #3572
https://github.com/toeverything/blocksuite/assets/15389209/9e0b37b0-f9f2-44bb-92bb-bf26b15d2001
> feat(database): show indicator when changing column width

- packages/blocks/src/page-block/edgeless/components/note-cut/index.ts
> fix(edgeless): the newly created block should retain its formatting

- packages/blocks/src/__internal__/utils/filesys.ts
- packages/blocks/src/components/import-page/import-page.ts
- packages/blocks/src/components/import-page/index.ts
- packages/blocks/src/components/index.ts
- packages/blocks/src/components/linked-page/config.ts
Related to https://github.com/toeverything/blocksuite/issues/3316
```ts
async function importMarkDown(workspace: Workspace, text: string)
async function importHtml(workspace: Workspace, text: string)
async function importNotion(workspace: Workspace, file: File)
```
> refactor: export import md/html/notion API

- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- packages/blocks/src/__internal__/service/index.ts
- tests/clipboard.spec.ts
> fix(page): fix copy and paste on parent blocks

- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- packages/blocks/src/__internal__/content-parser/parse-base.ts
- tests/import.spec.ts
> fix(page): missing space and new line in the code block pasting

- packages/virgo/src/services/event.ts
- packages/virgo/src/tests/virgo.spec.ts
- packages/virgo/src/virgo.ts
before:
https://github.com/toeverything/blocksuite/assets/50035259/21eefe55-4b98-42b4-8fa2-68e4da3956dc
after:
https://github.com/toeverything/blocksuite/assets/50035259/48c3319e-3fd1-42b7-a5d2-b93506b5302f
> fix(virgo): unexpected range when press arrow in the edge of embed

- packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
- packages/blocks/src/page-block/edgeless/utils/text.ts
- packages/phasor/src/consts.ts
- packages/phasor/src/elements/text/text-element.ts
- packages/phasor/src/index.ts
- packages/virgo/src/virgo.ts
- tests/edgeless/text.spec.ts
> fix: cursor position based on triggered location

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/components/utils.ts
> fix(edgeless):  correctly display shape resizing cursor

- packages/blocks/src/page-block/default/default-page-block.ts
- tests/selection/block.spec.ts
- tests/utils/actions/drag.ts
> fix(page): insert block to page and select it make page not scroll properly

- packages/store/src/__tests__/workspace.unit.spec.ts
- packages/store/src/workspace/page.ts
> fix(store): issue on removing non-loaded page

- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- packages/blocks/src/__internal__/service/index.ts
- packages/blocks/src/bookmark-block/bookmark-service.ts
- packages/blocks/src/database-block/database-service.ts
- packages/blocks/src/image-block/image-service.ts
- packages/blocks/src/note-block/note-service.ts
- tests/clipboard.spec.ts
> fix(page): maintain the children block structure when pasting

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- tests/edgeless/rotation.spec.ts
> fix(edgeless): resize incorrectly after rotating multiple shapes

- packages/blocks/src/__internal__/content-parser/index.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
> fix(edgeless): add checking when transforming to canvas

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
> fix(edgeless): fix incorrect selected rects for multi-selection

- packages/blocks/src/page-block/edgeless/components/zoom/zoom-tool-bar.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/page-block/edgeless/tool-controllers/pan-tool.ts
- packages/blocks/src/page-block/edgeless/utils/selection-manager.ts
- packages/phasor/src/renderer.ts
- packages/phasor/src/surface.ts
add new method ```setViewport```,```setViewportByBound``` to viewport.
slot ```viewportUpdated``` should emitted by viewport instead of upper layer.
> refactor(edgeless): migrate zoom method to viewport

- packages/blocks/src/page-block/default/utils.ts
> fix(page): paste using the code block option

- packages/blocks/src/database-block/table/components/selection/selection.ts
- packages/blocks/src/database-block/table/components/toolbar/toolbar.ts
- packages/blocks/src/database-block/table/table-view.ts
- packages/blocks/src/page-block/default/default-page-block.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
> fix(page): clear selection state in exported PDF

- packages/blocks/src/__internal__/content-parser/index.ts
> fix(store): paste image twice

- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/attachment-block/attachment-model.ts
- packages/blocks/src/attachment-block/styles.ts
- packages/blocks/src/attachment-block/utils.ts
- packages/blocks/src/widgets/slash-menu/config.ts
https://github.com/toeverything/blocksuite/assets/18554747/4541ea23-9d17-4e9d-8b49-60bd3a887ce0
> feat: add loading state for attachment

- packages/blocks/src/page-block/default/default-page-block.ts
- packages/editor/src/utils/editor.ts
- packages/playground/apps/default/components/quick-edgeless-menu.ts
close #3681
Try to add block to a non-note page will automatically create a default note block.
> fix(edgeless): ensure presence of note block

- packages/blocks/src/__internal__/service/json2block.ts
> fix: remove focus after paste

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/page-block/edgeless/utils/note-resize-observer.ts
- tests/edgeless/note.spec.ts
> fix(edgeless): undo not work after resizing note block width

- packages/blocks/src/code-block/code-service.ts
- tests/code.spec.ts
- tests/utils/actions/misc.ts
> fix(page): code block lang will lost on paste

- packages/blocks/src/database-block/common/columns/title/cell-renderer.ts
- packages/blocks/src/database-block/database-block.ts
> fix(database): title columns selection wrong

- packages/blocks/src/__internal__/content-parser/parse-base.ts
> fix(page): remove the newline charactor when importing from markdown

- packages/blocks/src/__internal__/utils/query.ts
- packages/blocks/src/components/file-drop-manager.ts
- packages/blocks/src/image-block/image-model.ts
- packages/blocks/src/image-block/image-service.ts
- packages/editor/src/components/editor-container.ts
I believe DND should be refactored into a widget.
> feat(page): support adding attachment by drag and drop

- packages/blocks/src/code-block/affine-code-line.ts
- packages/virgo/src/components/virgo-text.ts
> fix(virgo): fix the style map which is not applied to span element but the parent v-text

- packages/blocks/src/code-block/affine-code-line.ts
> fix(page): code wrap issue on plain text

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/__internal__/clipboard/page-clipboard.ts
- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- packages/blocks/src/__internal__/content-parser/file-exporter/file-exporter.ts
- packages/blocks/src/__internal__/content-parser/index.ts
- packages/blocks/src/__internal__/content-parser/parse-notion-html.ts
- packages/blocks/src/__internal__/service/index.ts
- packages/blocks/src/attachment-block/attachment-service.ts
- packages/blocks/src/bookmark-block/bookmark-service.ts
- packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts
- packages/blocks/src/code-block/code-service.ts
- packages/blocks/src/divider-block/divider-service.ts
- packages/blocks/src/image-block/image-service.ts
- packages/blocks/src/list-block/list-service.ts
- packages/blocks/src/page-block/default/utils.ts
- packages/blocks/src/page-block/page-service.ts
- packages/blocks/src/page-block/utils/const.ts
- packages/blocks/src/paragraph-block/paragraph-service.ts
> feat: the exported html/markdown should include images

- packages/blocks/src/__internal__/utils/selection.ts
> fix(edgeless): fix incorrect note size

- packages/blocks/src/components/button.ts
- packages/blocks/src/components/import-page/import-page.ts
Revert part of https://github.com/toeverything/blocksuite/pull/3786
> fix(page): disabled button not work

- packages/blocks/src/components/import-page/import-page.ts
- packages/blocks/src/components/import-page/styles.ts
> fix(page): import dialog style

- packages/store/tsconfig.json
> chore: fix bundle

- packages/virgo/src/tests/virgo.spec.ts
Test: https://w3c.github.io/uievents/tools/key-event-viewer.html
Refs: https://github.com/microsoft/playwright/issues/5777#issuecomment-1651784399
> test: add chinese input test

- packages/blocks/src/__internal__/content-parser/file-exporter/exporter-style.ts
- packages/blocks/src/__internal__/content-parser/file-exporter/file-exporter.ts
- packages/blocks/src/bookmark-block/bookmark-service.ts
> feat(page): support bookmark block in exporting html/markdown

- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/zoom/zoom-tool-bar.ts
Modify the background style of the whiteboard pen in the selected state.
Closes #3780
> fix(edgeless): tweak toolbar ui

- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/bookmark-block/components/bookmark-create-modal.ts
- packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/image-block/image-block.ts
- packages/lit/src/portal.ts
Related to https://github.com/toeverything/blocksuite/pull/3830#discussion_r1284248140
> refactor: rename affine-portal to blocksuite-portal

- packages/blocks/src/attachment-block/components/options.ts
- packages/blocks/src/attachment-block/components/styles.ts
https://github.com/toeverything/blocksuite/assets/18554747/9a3f48c1-96a4-4d24-a0f5-6f9a121d7dbe
> feat(page): supports renaming attachment

- packages/block-std/src/event/control/range.ts
https://github.com/toeverything/blocksuite/assets/15389209/6257d563-6cbb-4863-aabe-288a818be84b
> fix(database): cannot find view when closing select popup

- packages/blocks/src/attachment-block/components/options.ts
- packages/blocks/src/attachment-block/components/styles.ts
Part of https://github.com/toeverything/blocksuite/issues/2952
https://github.com/toeverything/blocksuite/assets/18554747/e6798956-988c-4b61-b949-412a6bbf1511
> feat(page): fixed extension when rename attachment

- packages/blocks/src/database-block/common/header/consts.ts
- packages/blocks/src/database-block/common/header/title.ts
- packages/blocks/src/database-block/database-model.ts
https://github.com/toeverything/blocksuite/assets/17165520/6e554716-3fb0-4be3-a170-0e1fe0f05b2e
> chore(database): change title placeholder to Untitled from Database

- packages/blocks/src/__internal__/rich-text/virgo/affine-text.ts
> fix(virgo): code font size in headings

- packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/page-block/keyborad/keyboard-manager.ts
- tests/edgeless/frame.spec.ts
> fix(edgeless): add some missing key binding

- packages/blocks/src/widgets/format-bar/format-bar.ts
> fix(page): format bar render error when switch to other page

- packages/blocks/src/widgets/database-convert/database-convert.ts
> fix(page): database-convert can not be closed

- tests/slash-menu.spec.ts
- tests/utils/actions/edgeless.ts
related to https://github.com/toeverything/blocksuite/issues/3806
> test: enable slash menu test in edgeless

- packages/blocks/src/components/block-hub.ts
https://github.com/toeverything/blocksuite/assets/3471836/8031ffaf-a4fe-4f00-9ee1-28ecfcda8c62
close #3918
> fix: block hub style

- packages/blocks/src/attachment-block/utils.ts
- packages/blocks/src/image-block/image-block.ts
- packages/blocks/src/image-block/image/image-options.ts
https://github.com/toeverything/blocksuite/assets/18554747/84ec5abe-abe8-4c69-a754-094266828596
> feat: add turn attachment view on image options

- packages/blocks/src/__internal__/utils/selection.ts
- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/attachment-block/utils.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/components/block-selection.ts
https://github.com/toeverything/blocksuite/assets/18554747/881bbeda-6c9c-4033-9166-529f44cb7623
> fix: click to select block element

- packages/blocks/src/database-block/common/columns/base-cell.ts
- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/table/components/cell-container.ts
- packages/blocks/src/database-block/table/components/column-header/column-width-drag-bar.ts
- packages/blocks/src/database-block/table/components/selection.ts
- packages/blocks/src/page-block/text-selection/range-manager.ts
before:
https://github.com/toeverything/blocksuite/assets/15389209/d0885e40-b58d-4b9d-9569-a9722f086b61
after:
https://github.com/toeverything/blocksuite/assets/15389209/ce8bcbf2-6fb9-4dd4-99dc-0d321b3efc3b
> feat(database): update the selection style when modifying the column width

- packages/blocks/src/widgets/drag-handle/drag-preview.ts
- packages/blocks/src/widgets/drag-handle/index.ts
- packages/blocks/src/widgets/drag-handle/styles.ts
- packages/blocks/src/widgets/format-bar/component.ts/paragraph-button.ts
- packages/blocks/src/widgets/format-bar/format-bar.ts
- packages/lit/src/element/widget-element.ts
- tests/drag.spec.ts
> refactor: use LitElement in WidgetElement

- packages/blocks/src/database-block/table/components/selection.ts
before:
https://github.com/toeverything/blocksuite/assets/15389209/3ef16d90-d58a-4c2e-b7e6-752e10721060
after:
https://github.com/toeverything/blocksuite/assets/15389209/db6a4261-a927-4927-88d4-399804adb558
> fix(database): dragging from outside cannot select database block

- packages/blocks/src/page-block/doc/meta-data/meta-data.ts
Related to https://github.com/toeverything/blocksuite/issues/3883 https://github.com/toeverything/blocksuite/pull/3905
> refactor: update linked page styles

- packages/blocks/src/__internal__/content-parser/index.ts
> fix: remove box-shadow when exporting png

- packages/blocks/src/page-block/utils/operations/inline.ts
https://github.com/toeverything/blocksuite/assets/19991141/631be177-be79-46d0-acdd-7117b312bcc4
> fix: clear mock selection when link not confirm

- packages/blocks/src/__internal__/clipboard/utils/pure.ts
- packages/blocks/src/__internal__/content-parser/index.ts
- packages/blocks/src/__internal__/service/json2block.ts
- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/attachment-block/attachment-service.ts
- packages/blocks/src/attachment-block/utils.ts
- allow insert attachment by paste
- fix copy and paste attachment block
https://github.com/toeverything/blocksuite/assets/18554747/5b5389f4-1051-4d4e-a970-0eea3e284103
> feat(page): insert attachment by paste

- packages/blocks/src/widgets/format-bar/format-bar.ts
> fix(page): format-bar should be automatically updated in edgeless mode

- packages/blocks/src/page-block/edgeless/components/notes-status.ts
- packages/blocks/src/page-block/edgeless/components/utils.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
fixed #3945 
This is my first pull request in this repository.
So, I would appreciate any feedback I can receive.
https://github.com/toeverything/blocksuite/assets/38880175/108a5936-2992-43f8-aba2-214aef634546
> fix(edgeless): note index doesn't move with viewport

- packages/blocks/src/database-block/common/columns/number/cell-renderer.ts
- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
- packages/store/src/workspace/workspace.ts
> fix(database): rich-text error when importing snapshot

- packages/blocks/src/image-block/image-block.ts
> fix: image caption selection issue

- packages/blocks/src/page-block/doc/meta-data/meta-data.ts
- packages/global/src/config/icons/text.ts
Due to https://github.com/toeverything/blocksuite/pull/3940
> fix: backlink icon color

- packages/blocks/src/code-block/components/lang-list.ts
- packages/blocks/src/code-block/utils/code-languages.ts
> refactor(page): use property

- packages/blocks/src/widgets/format-bar/components/paragraph-button.ts
> fix(page): list convert using format-bar

- packages/store/src/__tests__/yjs.unit.spec.ts
- packages/store/src/base.ts
- packages/store/src/native-wrapper.ts
- packages/store/src/yjs/proxy.ts
> feat(store): add native wrapper prop type

- packages/blocks/src/database-block/table/components/selection.ts
close: https://github.com/toeverything/blocksuite/issues/3964
> feat(database): prevent `tab` key from focusing next line

- packages/blocks/src/database-block/table/components/selection.ts
close: https://github.com/toeverything/blocksuite/issues/3964
> feat(database): support `shift+tab` key

- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-order-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-order-menu.ts
- packages/phasor/src/surface.ts
fix some presentation mode ui problems
> fix(edgeless): presentation ui

- packages/blocks/src/__internal__/datasource/database-block-datasource.ts
- packages/blocks/src/database-block/database-block.ts
- packages/blocks/src/database-block/kanban/kanban-view.ts
- packages/blocks/src/database-block/table/components/selection.ts
- packages/blocks/src/database-block/table/table-view.ts
fix: deleting view error
fix: when there are two identical views, only one of them has selection
close: #4003
> fix(database): delete view error

- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/components/button.ts
- packages/blocks/src/components/selected-blocks.ts
- packages/blocks/src/database-block/database-block.ts
- packages/blocks/src/list-block/list-block.ts
- packages/blocks/src/page-block/edgeless/components/buttons/tool-icon-button.ts
- packages/blocks/src/page-block/edgeless/components/buttons/toolbar-button.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
- packages/blocks/src/page-block/edgeless/components/zoom/zoom-tool-bar.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
> fix(database): block selected style

- packages/blocks/src/components/tags/styles.ts
> fix: no scrollbar for tags when creating many tags

- packages/blocks/src/data-view-block/data-view-block.ts
- packages/blocks/src/database-block/common/data-view-manager.ts
- packages/blocks/src/database-block/common/header/tools/tools.ts
- packages/blocks/src/database-block/common/header/tools/view-options.ts
- packages/blocks/src/database-block/common/view-source.ts
- packages/blocks/src/database-block/database-block.ts
- packages/blocks/src/database-block/kanban/kanban-view-manager.ts
- packages/blocks/src/database-block/table/table-view-manager.ts
> fix(database): delete view button not work

- packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
> fix(edgeless): after delete auto complete overlay still exists

- packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
> fix(edgeless): fix wrong drag auto complete connector position

- packages/blocks/src/database-block/common/header/tools/add-row.ts
close: https://github.com/toeverything/blocksuite/issues/4059
> fix(database): `New Record` UI

- packages/blocks/src/page-block/text-selection/gesture.ts
fix downstream https://github.com/toeverything/AFFiNE/issues/3678
> fix: selection on db click when container has offset

- packages/blocks/src/page-block/edgeless/components/component-toolbar/add-frame-button.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
- packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/page-block/edgeless/frame-manager.ts
- tests/edgeless/frame.spec.ts
- tests/utils/actions/edgeless.ts
> feat(edgeless): add shortcut for creating frame

- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
> fix(edgeless): fix presentation tooltip

- packages/blocks/src/bookmark-block/components/bookmark-operation-popper.ts
fixed: https://github.com/toeverything/blocksuite/issues/3652
> fix: can not fully show bookmark menu in tiny screen

- packages/blocks/src/database-block/table/clipboard.ts
close: https://github.com/toeverything/blocksuite/issues/4074
> fix(database): execute the browser default behavior when the title column is copied or pasted

- packages/blocks/src/database-block/table/clipboard.ts
Copying rows outside the database behaves the same as copying paragraph blocks.
https://github.com/toeverything/blocksuite/assets/15389209/afdc57de-67df-4adb-90ce-b20c896c5ffe
> feat(database): support copying rows to outside the database

- packages/playground/apps/starter/components/custom-navigation-panel.ts
> fix(playground): custom navigation panel layer index

- packages/blocks/src/page-block/text-selection/gesture.ts
> fix: shift click range after input

- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- tests/clipboard.spec.ts
> fix: unable to copy and paste under multi lines of text selection

- .github/CLA.md
- packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
close #4063 
https://github.com/toeverything/blocksuite/assets/87802698/d34388db-13c2-4bf3-a73d-747efa3a8634
> feat(edgeless): support moving edgeless elements with arrow keys

- packages/blocks/package.json
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/page-block/font-loader/index.ts
- pnpm-lock.yaml
> feat(edgeless): add fontloader

- .vscode/settings.template.json
- packages/blocks/src/attachment-block/components/more-menu.ts
- packages/blocks/src/attachment-block/utils.ts
- packages/blocks/src/widgets/slash-menu/config.ts
- packages/blocks/src/widgets/slash-menu/utils.ts
- tests/attachment.spec.ts
- tests/bookmark.spec.ts
- tests/export.spec.ts
- tests/slash-menu.spec.ts
- remove empty line after insert content by slash
- update attachment option btn width
- add basic test for attachment
> refactor: remove empty line after insert content by slash

- packages/blocks/src/widgets/format-bar/format-bar.ts
> fix: format-bar position not follow edgeless viewport

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-remote-selection.ts
> fix(edgeless): remote selection does not follow new position

- packages/phasor/src/surface.ts
> fix(edgeless): fix cononector not show after refresh on playground

- packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
> fix(edgeless): fix auto complete text inheritance

- packages/blocks/src/components/toast.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/frame/frame-order-menu.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/global/src/utils/misc.ts
> feat(edgeless): support arrow key in presentation

- packages/blocks/src/image-block/image-block.ts
- tests/embed.spec.ts
> fix(page): remove border of image

- packages/blocks/src/__internal__/rich-text/rich-text.ts
- packages/blocks/src/__internal__/utils/filesys.ts
- packages/blocks/src/__internal__/utils/url.ts
- packages/blocks/src/__internal__/utils/url.unit.spec.ts
- tests/database/column.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/3836
The `autoIdentifyLink` still has **many** bugs to handle.
> fix(page): strict check when identity link

- packages/blocks/src/__internal__/content-parser/parse-base.ts
- packages/blocks/src/__internal__/content-parser/parse-notion-html.ts
- packages/blocks/src/components/import-page/import-page.ts
- tests/import.spec.ts
Part of #4184 
- fix: the unexpected highlight color is error
- fix: page link block transform to inline link when importing notion
- fix: directory file has not been imported when importing notion
- fix: need to know if the file is a workspace file when importing notion
> fix: should open the right page after importing notion

- packages/blocks/src/__internal__/datasource/all-page-datasource.ts
- packages/blocks/src/__internal__/datasource/base.ts
- packages/blocks/src/__internal__/datasource/database-block-datasource.ts
- packages/blocks/src/__internal__/datasource/tags-datasource.ts
- packages/blocks/src/database-block/common/base-data-view.ts
- packages/blocks/src/database-block/common/data-view-manager.ts
- packages/blocks/src/database-block/common/data-view.ts
- packages/blocks/src/database-block/common/header/tools/add-row.ts
- packages/blocks/src/database-block/common/header/tools/tools.ts
- packages/blocks/src/database-block/database-block.ts
- packages/blocks/src/database-block/table/table-view.ts
close: https://github.com/toeverything/blocksuite/issues/4164
https://github.com/toeverything/blocksuite/assets/15389209/8608de74-e7d3-406e-a461-93cccd4bbb9f
> feat(database): add row according to the selection

- packages/blocks/src/components/menu/menu.ts
close: https://github.com/toeverything/blocksuite/issues/4075
> fix(database): ui issues when editing database row properties

- packages/blocks/src/components/import-page/import-page.ts
> fix: the page should be created when which is needed

- packages/blocks/src/database-block/common/base-data-view.ts
- packages/blocks/src/database-block/common/data-view.ts
- packages/blocks/src/database-block/common/header/tools/add-row.ts
- packages/blocks/src/database-block/common/header/tools/tools.ts
- packages/blocks/src/database-block/database-block.ts
- packages/blocks/src/database-block/kanban/kanban-view.ts
- packages/blocks/src/database-block/table/table-view.ts
related to: https://github.com/toeverything/blocksuite/pull/4204
> refactor(database): add rows based on selection

- packages/blocks/src/__internal__/content-parser/index.ts
- packages/blocks/src/__internal__/rich-text/virgo/affine-text.ts
- packages/blocks/src/database-block/common/columns/checkbox/cell-renderer.ts
- packages/blocks/src/list-block/list-block.ts
- packages/blocks/src/list-block/styles.ts
- packages/blocks/src/list-block/utils/get-list-icon.ts
- packages/blocks/src/list-block/utils/icons.ts
- packages/editor/src/components/editor-container.ts
- packages/store/src/workspace/store.ts
- tests/database/selection.spec.ts
- enable attachment block flag
- fix https://github.com/toeverything/blocksuite/issues/4222
- fix todo check animation should only play once
- update the todo checkbox size and change color after checked
> fix: typography styles

- packages/blocks/src/__internal__/utils/query.ts
- packages/blocks/src/image-block/image-block.ts
- packages/blocks/src/image-block/image/image-resize-manager.ts
- packages/blocks/src/note-block/utils.ts
- packages/blocks/src/page-block/edgeless/components/buttons/menu-button.ts
- packages/blocks/src/widgets/drag-handle/index.ts
Close #4013 
As below after fixing:
https://github.com/toeverything/blocksuite/assets/17249775/91ce69a1-79fb-484c-82d1-cff15a499ab0
> fix(edgeless): image jitters on resizing in edgeless mode

- packages/blocks/src/__internal__/service/json2block.ts
- packages/blocks/src/__internal__/service/legacy-services/database-service.ts
close: https://github.com/toeverything/blocksuite/issues/3611
https://github.com/toeverything/blocksuite/assets/15389209/e7ff4c10-7a0c-4114-a97f-f52cf6197e6f
> fix(database): preserve column order when copying

- packages/blocks/src/__internal__/datasource/block-renderer.ts
> fix(database): backspace deletes the contents outside the block

- packages/blocks/src/database-block/common/columns/base-cell.ts
- packages/blocks/src/database-block/common/columns/manager.ts
- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/common/header-area/text.ts
- packages/blocks/src/database-block/table/components/cell-container.ts
- packages/blocks/src/database-block/table/components/column-header/column-width-drag-bar.ts
- packages/blocks/src/database-block/table/components/selection.ts
> fix(database): selection styles are not updated in a timely manner

- packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
> fix(database): title column should not be able to change column type

- packages/blocks/src/__internal__/rich-text/reference-node.ts
FIx https://github.com/toeverything/blocksuite/issues/4222#issuecomment-1685734014
> chore: update ref-node styles

- packages/blocks/src/__internal__/content-parser/parse-base.ts
- packages/blocks/src/components/import-page/import-page.ts
- tests/import.spec.ts
> fix: title column error when importing notion database

- packages/blocks/src/__internal__/content-parser/index.ts
- packages/blocks/src/components/import-page/import-page.ts
> fix: can not import when just only csv file

- .github/CLA.md
- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
> fix(edgeless): failed to execute 'exitFullscreen' on 'Document'

- packages/blocks/src/page-block/doc/doc-page-block.ts
> fix: copy title

- packages/store/src/workspace/space.ts
> fix: cannot read properties of undefined (reading 'insert') in yjs

- packages/blocks/src/page-block/edgeless/components/resize/resize-manager.ts
> fix(edgeless): fix a bug where the _shiftKey field wasn't being update correctly

- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
> fix: correct misspelled words

- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
> fix(edgeless): fix typo in EdgelessToolbar tooltip on presentation button

- packages/store/src/__tests__/indexer.unit.spec.ts
- packages/store/src/indexer/search.ts
Fixes: https://github.com/toeverything/blocksuite/issues/4294
> fix: search might not work

- packages/store/src/indexer/search.ts
Related: https://github.com/yjs/yjs/issues/563
> fix(store): force cast blocks to YMap

- packages/blocks/src/widgets/database-convert/styles.ts
> fix(database): style of convert into database modal

- packages/blocks/src/database-block/common/header-area/text.ts
- packages/blocks/src/database-block/table/clipboard.ts
- tests/database/clipboard.spec.ts
- add tests for the title column
> feat(database): support copy and paste of title column

- packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
> fix(edgeless): add condition to prevent moving elements when in editng mode

- packages/phasor/src/elements/connector/connector-element.ts
> fix(edgeless): fix connector stroke color assignment

- packages/blocks/src/database-block/common/columns/link/cell-renderer.ts
- packages/blocks/src/database-block/common/columns/link/components/link-node.ts
> fix(database): link text overflow

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/lit/src/utils/range-synchronizer.ts
> fix: should not sync range to text-selection when it is out of note

- packages/blocks/src/__internal__/rich-text/bracket-complete.ts
- packages/blocks/src/__internal__/rich-text/keyboard.ts
- tests/code.spec.ts
> feat(page): bracket auto complete in code block

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/__internal__/clipboard/page-clipboard.ts
- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- packages/blocks/src/__internal__/content-parser/index.ts
- packages/blocks/src/__internal__/content-parser/types.ts
- packages/blocks/src/__internal__/service/legacy-services/code-service.ts
- packages/blocks/src/__internal__/service/legacy-services/image-service.ts
- packages/blocks/src/__internal__/service/legacy-services/note-service.ts
- packages/blocks/src/__internal__/service/legacy-services/paragraph-service.ts
- packages/blocks/src/__internal__/service/service.ts
- tests/clipboard.spec.ts
- tests/utils/actions/misc.ts
- tests/utils/asserts.ts
> fix: nested list items are lost on pasting

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/phasor/src/elements/connector/connector-element.ts
- packages/phasor/src/surface.ts
close #4308 
Uploading Screen Recording 2023-08-24 at 11.52.06.mov…
> fix(edgeless): refactor yContainer events handling for SurfaceManager 

- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
> feat(edgeless): presentation starts from selected frame

- packages/blocks/src/database-block/table/clipboard.ts
- tests/database/actions.ts
- tests/database/clipboard.spec.ts
before:
https://github.com/toeverything/blocksuite/assets/15389209/30c78183-340a-47e9-ab5e-daf3b28731d2
after:
https://github.com/toeverything/blocksuite/assets/15389209/d5896270-813a-4fa1-b06d-a21bd522fa88
> fix(database): exit the editing state when copying

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
- packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/page-block/edgeless/tool-controllers/eraser-tool.ts
- packages/blocks/src/page-block/edgeless/utils/crud.ts
- tests/edgeless/clipboard.spec.ts
- tests/edgeless/connector.spec.ts
> feat(edgeless): add deleteElements function for deleting elements

- packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
https://github.com/toeverything/blocksuite/assets/48149577/59087554-5ecd-40a2-8384-dc456e646a61
> fix(edgeless): correctly display hover style on moving with arrow key

- packages/blocks/src/page-block/text-selection/gesture.ts
> fix(page): right click may trigger native selection

- packages/blocks/src/__internal__/service/legacy-services/image-service.ts
- packages/blocks/src/__internal__/service/service.ts
> fix: the image type is wrong inexported file

- .github/CLA.md
- packages/blocks/src/page-block/edgeless/components/edgeless-notes-container.ts
> fix(edgeless): image menu state on canvas text editing

- packages/blocks/src/database-block/common/header-area/text.ts
close https://github.com/toeverything/blocksuite/issues/4352
> fix(database): transform page link in title cell

- packages/phasor/src/elements/shape/utils.ts
To close #4366 
https://github.com/toeverything/blocksuite/assets/99816898/8f864aa5-b807-4b98-aded-a4442a93e5be
> fix(edgeless): draw rectangle should not with radius

- packages/blocks/src/components/portal.ts
Close #4369
https://github.com/toeverything/blocksuite/assets/18554747/b097c151-9003-4ac4-aa8e-460d4a41c4c7
> fix(page): remove portal when reference element removed

- packages/blocks/src/__internal__/rich-text/keymap/container.ts
- flip if/else to flat code structure
- skip bracket auto complete when multiple blocks
Recommend turning on "hide whitespace" during review.
> refactor(page): flip if/else

- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
> fix(database): rich-text cell word break

- packages/blocks/src/database-block/kanban/define.ts
> fix(database): default grouping logic

- packages/blocks/src/list-block/list-block.ts
- packages/blocks/src/list-block/styles.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
- packages/blocks/src/widgets/drag-handle/index.ts
https://github.com/toeverything/blocksuite/assets/99816898/e4512eb8-1cc1-412f-b5ed-ef3cb5d4aa4a
> fix(page): selection rect should cover children blocks

- package.json
- packages/blocks/src/__internal__/datasource/all-page-datasource.ts
- packages/blocks/src/__internal__/rich-text/reference-node.ts
- packages/blocks/src/database-block/common/columns/renderer.ts
- packages/blocks/src/database-block/common/data-view.ts
- packages/blocks/src/page-block/edgeless/connector-manager.ts
- packages/blocks/src/widgets/format-bar/format-bar.ts
- packages/global/src/debug.ts
- packages/phasor/src/elements/text/utils.ts
- packages/phasor/src/surface.ts
- packages/store/src/persistence/blob/indexeddb-storage.ts
- packages/store/src/persistence/blob/memory-storage.ts
- packages/store/src/workspace/page.ts
- packages/store/src/workspace/workspace.ts
- packages/virgo/src/utils/delta-convert.ts
Benchmark: https://jsben.ch/5lKjg
> perf: replace spread with Array.from

- packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
> fix(edgeless): edited frame title should not be wrapped during IME input

- packages/blocks/src/page-block/keyborad/keyboard-manager.ts
- tests/selection/block.spec.ts
Revert part of https://github.com/toeverything/blocksuite/pull/4428
Related to https://github.com/toeverything/blocksuite/pull/4434
> fix(page): remove children when selecting list and delete

- packages/blocks/src/components/tooltip/tooltip.ts
- packages/blocks/src/page-block/edgeless/components/utils.ts
> fix(edgeless): make tooltip with shortcut conform to design

- .github/CLA.md
- packages/docs/getting-started.md
> docs: update quick start pnpm install command

- packages/blocks/src/components/tooltip/tooltip.ts
> fix(edgeless): round the triangle of tooltip

- packages/blocks/src/surface-block/surface-model.ts
- packages/store/src/__tests__/migration.unit.spec.ts
- packages/store/src/__tests__/yjs.unit.spec.ts
- packages/store/src/consts.ts
- packages/store/src/schema/utils.ts
- packages/store/src/utils/utils.ts
- packages/store/src/yjs/json.ts
- packages/store/src/yjs/native-wrapper.ts
- packages/store/src/yjs/proxy.ts
> fix: native wrapper

- packages/blocks/src/page-block/const/inline-format-config.ts
- packages/blocks/src/widgets/format-bar/components/background/background-button.ts
- packages/blocks/src/widgets/format-bar/components/inline-items.ts
- packages/blocks/src/widgets/format-bar/format-bar.ts
Fix https://github.com/toeverything/blocksuite/issues/4535
I recommend reviewing each commit individually.
> fix: hide format bar when non text block selected

- packages/docs/flavoured-blocks.md
- packages/docs/workspaces-and-pages.md
> docs: update the page.waitForLoaded guidelines

- packages/blocks/src/__internal__/clipboard/edgeless-clipboard.ts
- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- packages/blocks/src/__internal__/service/legacy-services/attachment-service.ts
- packages/blocks/src/__internal__/service/legacy-services/bookmark-service.ts
- packages/blocks/src/__internal__/service/legacy-services/database-service.ts
- packages/blocks/src/__internal__/service/legacy-services/image-service.ts
- packages/blocks/src/__internal__/service/legacy-services/note-service.ts
- packages/blocks/src/__internal__/service/service.ts
- packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
- packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
> fix: lost content with duplicate note action in edgeless

- packages/block-std/src/event/control/keyboard.ts
- packages/block-std/src/event/dispatcher.ts
Closes: #4546 
Closes: #4544
Closes: #4503
Closes: #4551
> fix: keymap should only be triggered witout composition

- packages/blocks/src/__internal__/rich-text/keymap/container.ts
- packages/blocks/src/__internal__/rich-text/markdown-convert.ts
- packages/blocks/src/__internal__/utils/common-operations.ts
- packages/blocks/src/__internal__/utils/types.ts
- packages/blocks/src/page-block/doc/doc-page-block.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
> fix: cursor after undo of a block markdown convert should after space

- packages/block-std/src/command/index.ts
- packages/blocks/src/page-block/commands/get-next-block.ts
- packages/blocks/src/page-block/commands/get-previous-block.ts
Ensure type safety for context
> feat: improve the type of command system

- packages/blocks/src/database-block/kanban/card.ts
- packages/blocks/src/note-block/keymap.ts
> fix: global select all behavior

- packages/blocks/src/__internal__/content-parser/parse-notion-html.ts
> fix: import notion embed block

- packages/blocks/src/preset/index.ts
> fix: database selection is not registered in edgeless mode

- packages/blocks/src/database-block/kanban/kanban-view.ts
- packages/blocks/src/database-block/table/table-view.ts
> fix(database): database can not scroll in edgeless mode

- packages/blocks/src/database-block/database-block.ts
- packages/blocks/src/database-block/kanban/hotkeys.ts
- packages/blocks/src/database-block/kanban/selection.ts
> feat(database): support using arrow keys to select kanban card

- packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
> feat(edgeless): support auto complete shapes with text focus

- packages/blocks/src/icons/edgeless.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-button.ts
> refactor: use currentcolor to set svg fill

- packages/blocks/src/widgets/drag-handle/config.ts
- packages/blocks/src/widgets/drag-handle/index.ts
- packages/blocks/src/widgets/drag-handle/utils.ts
1. Use PathFinder.
2. Optimize getting hovering block logic in edgeless mode.
3. Extract getDropIndicator() function for the later database block usage.
> refactor: optimize drag handle widget code

- packages/blocks/src/__internal__/service/legacy-services/data-view-service.ts
- packages/blocks/src/__internal__/utils/model.ts
- packages/blocks/src/data-view-block/data-view-block.ts
- packages/blocks/src/data-view-block/data-view-model.ts
- packages/blocks/src/data-view-block/index.ts
- packages/blocks/src/index.ts
- packages/blocks/src/models.ts
- packages/blocks/src/note-block/note-model.ts
- packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-preview.ts
- packages/blocks/src/preset/index.ts
- packages/blocks/src/widgets/slash-menu/utils.ts
- tests/utils/asserts.ts
This reverts commit 030d35f6754f1ebaf1d335256e0bce4a70317fd6.
> revert: remove data-view block (#4627)

- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/code-block/components/lang-list.ts
- packages/blocks/src/components/portal.ts
close #4675, #4676
Extend `PortalOptions`:
```ts
/**
* Whether to close the portal when click away(click outside).
* @default false
*/
closeOnClickAway?: boolean;
```
> feat: add `closeOnClickAway` option for `createSimplePortal`

- tests/clipboard.spec.ts
- tests/edgeless/basic.spec.ts
- tests/edgeless/note.spec.ts
- tests/format-bar.spec.ts
- tests/hotkey.spec.ts
- tests/list.spec.ts
- tests/markdown.spec.ts
- tests/paragraph.spec.ts
- tests/selection/native.spec.ts
- tests/utils/asserts.ts
> fix: add selection test for markdown inline

- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/attachment-block/components/options.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/code-block/components/code-option.ts
- packages/blocks/src/components/portal.ts
- packages/global/src/utils/misc.ts
It is very common to show a popover when hovering over something.
```ts
// Existing implementation
class WebComponent {
private _onHover = () => {
this._hovered = true;
};
private _onHoverLeave = () => {
this._hovered = false;
this._hideAfterDelay();
};
// Need to handle delay manually
private _hideAfterDelay = () => {
if (this._hideTimer) clearTimeout(this._hideTimer);
this._hideTimer = setTimeout(() => {
if (!this._hovered) {
this.hide();
}
this._hideTimer = null;
}, 150);
};
override connectedCallback() {
super.connectedCallback();
this.pageElement.handleEvent('pointerMove', ctx => {
this.show();
});
}
render() {
// Add event listeners
return html`<div
@mouseover=${this._onHover}
@mouseout=${this._onHoverLeave}
></div>`;
}
}
```
```ts
class WebComponent {
constructor() {
// Some hover …
```
> feat: new whenHover API

- tests/database/actions.ts
- tests/database/selection.spec.ts
> test(database): add tests related to kanban selection

- packages/blocks/src/database-block/common/selection.ts
> feat(database): add zod validation for selection

- packages/blocks/src/icons/edgeless.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
related to #4538 
new pen and eraser icon
> feat: new edgeless toolbar icon

- packages/blocks/src/surface-block/surface-block.ts
- packages/playground/apps/default/presets/preset.ts
> fix: playground edgeless bug

- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/components/when-hover.ts
- packages/blocks/src/widgets/image-toolbar/image-options.ts
- packages/blocks/src/widgets/image-toolbar/index.ts
- packages/global/src/utils/misc.ts
Set portal element as floating by default
Recommend to review PR in hide whitespace mode
> refactor: simplify whenHover usage

- packages/blocks/src/attachment-block/components/options.ts
- packages/blocks/src/bookmark-block/components/config.ts
- packages/blocks/src/components/button.ts
- packages/blocks/src/widgets/image-toolbar/image-options.ts
Fix https://github.com/toeverything/AFFiNE/issues/4222
> fix: hide toolbar on read-only mode

- packages/blocks/src/__internal__/utils/virgo.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/components/rich-text/rich-text.ts
- packages/blocks/src/list-block/list-block.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
- packages/virgo/src/components/virgo-line.ts
- packages/virgo/src/services/event.ts
- packages/virgo/src/services/range.ts
- packages/virgo/src/virgo.ts
- tests/clipboard.spec.ts
Close #4700
https://github.com/toeverything/blocksuite/assets/50035259/860e4ae4-f55a-4105-9a0c-93bd729f3362
> fix: auto scroll into view

- packages/blocks/src/page-block/edgeless/components/toolbar/common/slide-menu.ts
> fix: edgeless slide menu horizontal scroll

- packages/blocks/src/components/menu/menu.ts
- packages/blocks/src/database-block/common/detail/field.ts
- packages/blocks/src/database-block/kanban/menu.ts
- packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
- packages/blocks/src/database-block/table/components/menu.ts
> fix(database): case sensitive for menu labels

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
> fix(edgeless): toolbar z-index

- packages/blocks/src/database-block/common/filter/filter-group.ts
- packages/blocks/src/database-block/common/filter/filter-root.ts
> fix(database): structuredClone unable to clone Proxy

- packages/playground/apps/starter/components/custom-navigation-panel.ts
- packages/playground/apps/starter/utils.ts
Fix https://github.com/toeverything/blocksuite/issues/4750
> fix: playground error log

- packages/blocks/src/database-block/common/group-by/define.ts
> fix(database): moving to ungrouped logic is wrong when group by multi-select

- packages/blocks/src/page-block/edgeless/services/tools-manager.ts
- packages/blocks/src/page-block/edgeless/tool-controllers/default-tool.ts
> fix: input element not works in edgeless mode

- packages/blocks/src/page-block/doc/doc-page-block.ts
close: https://github.com/toeverything/blocksuite/issues/4665
> fix(page): add tail paragraph for blocks with rich text

- packages/blocks/src/components/block-hub.ts
- packages/editor/src/utils/editor.ts
> fix(page): prevent dragging the block hub when exceeding the note area

- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/common/header-area/text.ts
> fix(database): replace selected text content when pasting

- packages/lit/src/utils/v-range-provider.ts
> fix: v-range incorrect when select child block

- packages/blocks/src/api/index.ts
- packages/blocks/src/api/transformer/index.ts
- packages/blocks/src/api/transformer/utils.ts
- packages/blocks/src/api/transformer/zip.ts
- packages/blocks/src/database-block/database-model.ts
- packages/blocks/src/index.ts
- packages/blocks/src/page-block/clipboard/adapter.ts
- packages/blocks/src/page-block/clipboard/index.ts
- packages/blocks/src/page-block/clipboard/middlewares/paste.ts
- packages/playground/apps/default/components/quick-edgeless-menu.ts
- packages/playground/apps/starter/components/debug-menu.ts
- packages/store/src/transformer/base.ts
- packages/store/src/transformer/index.ts
- packages/store/src/transformer/job.ts
> fix: database cell wrong id after import from snapshot

- packages/blocks/src/components/rich-text/virgo/nodes/reference-node.ts
> fix(page): cannot find model by element when moving paragraph with AffineReference

- packages/blocks/src/page-block/types.ts
- packages/blocks/src/preset/index.ts
- packages/blocks/src/widgets/remote-selection/remote-selection.ts
> fix: doc remote selection should be updated when resize

- packages/blocks/src/components/menu/menu.ts
- packages/blocks/src/database-block/database-block.ts
> fix(database): dragging from the menu to modal mask should not close the menu

- packages/blocks/src/components/menu/menu.ts
- packages/blocks/src/database-block/common/detail/detail.ts
- packages/blocks/src/database-block/common/detail/layout.ts
- packages/blocks/src/database-block/common/header/tools/expand/index.ts
- packages/blocks/src/page-block/doc/doc-page-block.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/widgets/format-bar/format-bar.ts
> fix(database): can not edit in detail panel

- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
> fix(database): don't use variables outside of class

- packages/blocks/src/database-block/common/detail/detail.ts
- packages/blocks/src/database-block/common/detail/layout.ts
> fix(database): detail panel close button covered by the top bar

- packages/blocks/src/code-block/code-block.ts
Related to https://github.com/toeverything/blocksuite/issues/4138
> fix(page): lang select panel too short

- packages/blocks/src/components/portal.ts
> fix: change portal z-index

- packages/blocks/src/database-block/kanban/kanban-view.ts
> feat(database): show horizontal scroll bar on hover

- packages/blocks/src/attachment-block/attachment-block.ts
Fix https://github.com/toeverything/blocksuite/issues/4724
> fix: update attachment after theme change

- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/code-block/components/lang-list.ts
- packages/blocks/src/components/portal.ts
- packages/blocks/src/components/utils.ts
- packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-card.ts
- packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-panel.ts
Fix https://github.com/toeverything/blocksuite/issues/4880
> refactor(page): update lang menu styles on code block

- packages/blocks/src/components/rich-text/rich-text-operations.ts
- tests/paragraph.spec.ts
To close #4888 
https://github.com/toeverything/blocksuite/assets/99816898/15bab550-f292-4c6c-8c7e-c35a87dcbe09
> fix(page): should not delete children when parent following custom blocks

- packages/blocks/src/page-block/edgeless/connector-manager.ts
- packages/blocks/src/surface-block/utils/math-utils.ts
> fix(edgeless): optimize connector enter tangent

- packages/blocks/src/bookmark-block/components/bookmark-create-modal.ts
- packages/blocks/src/bookmark-block/components/bookmark-edit-modal.ts
- packages/blocks/src/code-block/components/lang-list.ts
- packages/blocks/src/components/button.ts
- packages/blocks/src/components/menu/menu.ts
- packages/blocks/src/database-block/common/columns/link/cell-renderer.ts
- packages/blocks/src/database-block/common/columns/number/cell-renderer.ts
- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/common/columns/text/cell-renderer.ts
- packages/blocks/src/database-block/common/columns/title/cell-renderer.ts
- packages/blocks/src/database-block/common/datasource/block-renderer.ts
- packages/blocks/src/page-block/doc/doc-page-block.ts
> fix(page): don't trigger enter actions when using IME

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/components/resize/resize-manager.ts
- packages/blocks/src/surface-block/elements/text/utils.ts
> fix(edgeless): unexpected text resize behaviour

- packages/blocks/src/page-block/doc/doc-page-block.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/page-block/text-selection/sync-filter.ts
- packages/lit/src/utils/range-manager.ts
- packages/lit/src/utils/range-synchronizer.ts
- packages/lit/src/utils/v-range-provider.ts
- tests/edgeless/frame.spec.ts
> fix(page): unexpected behaviour when sync range and text selection

- packages/blocks/src/database-block/table/components/column-header/styles.ts
> fix(database): drag-handle of column blink when mouse enter right

- packages/blocks/src/page-block/edgeless/components/zoom/zoom-bar-toggle-button.ts
- tests/edgeless/basic.spec.ts
- tests/utils/actions/edgeless.ts
To close #4927 
https://github.com/toeverything/blocksuite/assets/99816898/25cbd055-d50d-48cc-95b2-7e0c8ad608cb
> fix(edgeless): close zoom bar when click blank area

- packages/blocks/src/list-block/styles.ts
- tests/list.spec.ts
close: #4907
https://github.com/toeverything/blocksuite/assets/15389209/9a341a50-d631-4b48-9b35-a119577653eb
> fix(page): display of toggle icon of `list-block`

- packages/blocks/src/components/block-hub.ts
> fix: block hub z-index

- packages/blocks/src/components/rich-text/rich-text-operations.ts
- tests/hotkey.spec.ts
- tests/list.spec.ts
- tests/markdown.spec.ts
- tests/paragraph.spec.ts
- tests/utils/actions/block.ts
> fix(page): delete nested item in the middle should not change the hierarchy of its siblings below

- packages/blocks/src/components/rich-text/rich-text-operations.ts
- tests/list.spec.ts
- tests/paragraph.spec.ts
- tests/utils/actions/edgeless.ts
> fix(page): inconsistent behavior when hard enter in the end of line

- packages/blocks/src/components/rich-text/virgo/nodes/link-node/affine-link.ts
- packages/blocks/src/components/rich-text/virgo/nodes/link-node/link-popup/link-popup.ts
- tests/link.spec.ts
> fix(page): should not display bookmark button in link popup when it not supports

- packages/blocks/src/attachment-block/components/styles.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
- packages/blocks/src/code-block/components/code-option.ts
- packages/blocks/src/components/portal.ts
- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/widgets/image-toolbar/image-options.ts
Set `z-index` for portal manually
Related to https://github.com/toeverything/blocksuite/pull/4882 https://github.com/toeverything/blocksuite/pull/4749 https://github.com/toeverything/blocksuite/pull/4950
> refactor: tweak z-index for popover

- packages/blocks/src/components/rich-text/virgo/hooks.ts
- tests/basic.spec.ts
- tests/format-bar.spec.ts
- tests/utils/actions/misc.ts
- tests/utils/query.ts
> fix(page): inline format should be extended when range is not collapsed

- packages/blocks/src/components/rich-text/rich-text.ts
- packages/blocks/src/database-block/common/header/title.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
before:
https://github.com/toeverything/blocksuite/assets/50035259/ef7e0c57-9d92-4db2-8284-91d8c03087dc
> fix(page): add `enableMarkdownShortcut` and `enableFormat` in `rich-text`

- package.json
- packages/blocks/src/page-block/clipboard/index.ts
- pnpm-lock.yaml
> fix: clipboard selection missing

- packages/blocks/src/page-block/edgeless/tool-controllers/brush-tool.ts
To close #4959 
https://github.com/toeverything/blocksuite/assets/99816898/ee075793-fa78-4e90-8e9d-04e60f94aaf6
> feat(edgeless): support holding shift key to draw straight line

- packages/blocks/src/__internal__/utils/query.ts
> fix(page): press `Backspace` in the start of first line

- packages/blocks/src/__internal__/clipboard/page-clipboard.ts
- packages/blocks/src/database-block/common/columns/base-cell.ts
- packages/blocks/src/database-block/common/header-area/text.ts
- packages/blocks/src/database-block/kanban/controller/drag.ts
- packages/blocks/src/widgets/doc-dragging-area/index.ts
- packages/blocks/src/widgets/format-bar/components/action-items.ts
- packages/blocks/src/widgets/format-bar/components/inline-items.ts
- packages/blocks/src/widgets/format-bar/components/paragraph-button.ts
- packages/blocks/src/widgets/format-bar/format-bar.ts
- tests/bookmark.spec.ts
- tests/clipboard.spec.ts
- tests/database/database.spec.ts
- tests/hotkey.spec.ts
- tests/utils/actions/misc.ts
- tests/utils/asserts.ts
> feat(page): support format-bar in database

- packages/blocks/src/page-block/page-model.ts
- packages/store/src/schema/schema.ts
> fix: useless update data sent when new client joining

- packages/blocks/src/components/rich-text/keymap/container.ts
- tests/hotkey.spec.ts
> fix: improve bracket auto complete

- packages/blocks/src/page-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/eraser/eraser-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-button.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/text/text-tool-button.ts
> feat(edgeless): standardize edgeless toolbar esc behavior

- packages/blocks/src/icons/edgeless.ts
- packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/services/selection-manager.ts
- packages/blocks/src/page-block/edgeless/utils/bound-utils.ts
- packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
- packages/blocks/src/surface-block/renderer.ts
- packages/blocks/src/surface-block/surface-block.ts
- tests/clipboard.spec.ts
- tests/edgeless/basic.spec.ts
- tests/edgeless/frame.spec.ts
- tests/edgeless/note.spec.ts
- tests/edgeless/reordering.spec.ts
- tests/edgeless/shortcut.spec.ts
- tests/utils/actions/edgeless.ts
- tests/utils/actions/misc.ts
- tests/utils/asserts.ts
> feat(edgeless): note auto complete

- packages/lit/src/utils/v-range-provider.ts
Close #5001
before:
https://github.com/toeverything/blocksuite/assets/50035259/ad1b3e6c-a055-44e0-a6b1-f19fd752be97
after:
https://github.com/toeverything/blocksuite/assets/50035259/111109a6-e96b-4322-a8ad-8af6ae157fa2
> fix(page): performance issue from v-range-provider

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/components/resize/resize-handles.ts
- packages/blocks/src/page-block/edgeless/components/resize/resize-manager.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
- packages/blocks/src/page-block/edgeless/utils/text.ts
- packages/blocks/src/surface-block/elements/text/text-element.ts
- packages/blocks/src/surface-block/elements/text/types.ts
- packages/blocks/src/surface-block/elements/text/utils.ts
- tests/edgeless/text.spec.ts
> feat(edgeless): support adjusting canvas text width

- packages/blocks/src/components/button.ts
- packages/blocks/src/widgets/slash-menu/slash-menu-popover.ts
- tests/slash-menu.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/5005
> fix: unexpected hover style on slash menu

- packages/playground/apps/default/components/quick-edgeless-menu.ts
- packages/playground/package.json
- pnpm-lock.yaml
See example: https://shoelace.style/components/dropdown#submenus
> chore(playground): update shoelace and use submenu

- packages/blocks/src/page-block/doc/doc-page-block.ts
- packages/blocks/src/widgets/doc-remote-selection/doc-remote-selection.ts
> fix(page): `remote-selection` make other users can not select text by mouse click

- packages/blocks/src/widgets/edgeless-remote-selection/index.ts
> fix(edgeless): remote selection mispositioning

- packages/lit/src/utils/range-synchronizer.ts
- packages/virgo/src/virgo.ts
- tests/selection/native.spec.ts
> fix(page): failed to delete text spanning three levels

- packages/blocks/src/surface-block/surface-block.ts
> fix(edgeless): viewport move when pen

- packages/blocks/src/database-block/common/columns/date/cell-renderer.ts
- packages/blocks/src/database-block/common/detail/layout.ts
- packages/blocks/src/database-block/kanban/kanban-view.ts
- packages/blocks/src/database-block/table/table-view.ts
close: #5024
close: #5025
close: #5031
> fix(database): zoom bug, date format bug and can't open detail panel in edgeless mode

- packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
https://github.com/toeverything/blocksuite/assets/48149577/a54f6227-2536-43d5-b23d-77f6c72f9ba0
> fix(edgeless): fix frame title when inputting Chinese use Enter key

- packages/blocks/src/__internal__/clipboard/utils/commons.ts
- packages/blocks/src/__internal__/content-parser/index.ts
- packages/blocks/src/__internal__/service/legacy-services/index.ts
- tests/edgeless/auto-complete.spec.ts
registerAllBlocks once instead of calling it every time.
> fix(edgeless): register services

- packages/blocks/src/frame-block/frame-block.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
- packages/blocks/src/page-block/edgeless/frame-manager.ts
- packages/blocks/src/surface-block/surface-block.ts
- tests/clipboard.spec.ts
- tests/edgeless/auto-complete.spec.ts
- tests/edgeless/clipboard.spec.ts
- tests/edgeless/connector.spec.ts
- tests/edgeless/note.spec.ts
- tests/edgeless/selection.spec.ts
- tests/edgeless/shortcut.spec.ts
> fix(edgeless): style frame

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
> fix(edgeless): incomplete content export

- packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/store/src/workspace/page.ts
> fix(edgeless): collaborators unable to view images after upload

- packages/blocks/src/page-block/edgeless/connector-manager.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/page-block/edgeless/utils/query.ts
- packages/blocks/src/surface-block/elements/selectable.ts
- packages/blocks/src/surface-block/surface-block.ts
- packages/blocks/src/surface-block/utils/math-utils.ts
- tests/clipboard.spec.ts
> fix(edgeless): connector not follow image

- packages/blocks/src/page-block/edgeless/components/toolbar/shape/shape-tool-element.ts
fix: #5068 
https://github.com/toeverything/blocksuite/assets/117659326/358f8199-4385-4119-bab5-dfea20a5d15d
> fix(edgeless): position of dragged shape

- packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/image/edgeless-image.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
> fix(edgeless): frame container zindex

- packages/blocks/src/page-block/clipboard/middlewares/paste.ts
> fix: new clipboard will auto merge type for empty paragraph

- packages/blocks/src/note-block/keymap.ts
> fix(page): copy multiple times in list when no text selection

- packages/blocks/src/page-block/keyboard/keyboard-manager.ts
- tests/hotkey.spec.ts
- tests/utils/actions/keyboard.ts
> feat(page): support ctrl-y shortcut for redo

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/surface-block/consts.ts
- tests/edgeless/note.spec.ts
- tests/edgeless/shortcut.spec.ts
- tests/edgeless/text.spec.ts
To close #5107 
https://github.com/toeverything/blocksuite/assets/99816898/69c67cd3-e224-4e0e-a3d9-f31b803d9c80
> fix(edgeless): limit initial zoom ratio

- packages/blocks/src/_common/utils/query.ts
- tests/paragraph.spec.ts
> fix(page): `getPreviousBlock` not works as expected when there are several notes

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
https://github.com/toeverything/blocksuite/assets/99816898/5f800689-a67a-4f37-89e5-d04c515c08a8
> fix(edgeless): keep component toolbar in viewport

- packages/blocks/src/_common/components/rich-text/virgo/nodes/affine-text.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
> feat: inline code ui update

- packages/blocks/src/code-block/code-block.ts
Fix https://github.com/toeverything/AFFiNE/issues/4757
> fix(page): lang list in code block covered by database

- packages/blocks/src/page-block/edgeless/components/component-toolbar/align-button.ts
Fix https://github.com/toeverything/blocksuite/issues/5146
> chore: tweak tooltip

- packages/blocks/src/_common/transformers/zip.ts
- packages/store/src/adapter/markdown.ts
> fix(store): add fallbacks for checking assets mime type

- packages/blocks/src/_common/components/button.ts
- packages/blocks/src/_common/widgets/surface-ref-toolbar/index.ts
- packages/blocks/src/attachment-block/components/options.ts
- packages/blocks/src/attachment-block/components/styles.ts
- packages/blocks/src/bookmark-block/components/bookmark-toolbar.ts
Fix https://github.com/toeverything/blocksuite/issues/4921
Related to https://github.com/toeverything/blocksuite/pull/5013
format bar
> fix(page): format bar styling and simplify button property

- packages/blocks/src/image-block/image-block.ts
> fix(page): failed to insert image as a child of other content block

- packages/blocks/src/_common/components/rich-text/keymap/container.ts
- tests/linked-page.spec.ts
Fix https://github.com/toeverything/blocksuite/issues/2730
https://github.com/toeverything/blocksuite/assets/18554747/7a9256b0-9a4c-4176-a245-0eab0ef7afaa
> feat(page): convert selected text to linked page

- packages/block-std/src/selection/manager.ts
- packages/blocks/src/_common/widgets/format-bar/format-bar.ts
- packages/playground/apps/starter/components/debug-menu.ts
- packages/playground/package.json
- pnpm-lock.yaml
https://github.com/toeverything/blocksuite/assets/10047788/7575d814-3f9a-4bd6-a105-a47642d1f18f
> feat(playground): support share selection poc

- packages/blocks/src/_common/utils/types.ts
- packages/blocks/src/page-block/edgeless/connector-manager.ts
- packages/blocks/src/surface-block/elements/group/group-element.ts
> fix(edgeless): group can't be connected

- tests/slash-menu.spec.ts
- tests/utils/asserts.ts
Reverts toeverything/blocksuite#5191
> revert: fix slash menu flaky test

- packages/blocks/src/_common/widgets/slash-menu/config.ts
- packages/blocks/src/_legacy/clipboard/edgeless-clipboard.ts
- packages/blocks/src/_legacy/content-parser/index.ts
- packages/blocks/src/_legacy/content-parser/parse-markdown.ts
- packages/blocks/src/_legacy/content-parser/parse-notion-html.ts
- packages/blocks/src/_legacy/service/legacy-services/image-service.ts
- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/attachment-block/attachment-model.ts
- packages/blocks/src/attachment-block/utils.ts
- packages/blocks/src/image-block/image-block.ts
- packages/blocks/src/image-block/image-model.ts
- packages/blocks/src/image-block/image/utils.ts
- packages/blocks/src/image-block/ledits/main.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
- packages/blocks/src/page-block/page-model.ts
- packages/editor/src/components/editor-container.ts
- packages/editor/src/utils/editor.ts
- packages/playground/apps/default/preset.ts
- packages/store/src/adapter/assets.ts
- packages/store/src/persistence/blob/types.ts
- packages/store/src/schema/base.ts
- packages/store/src/transformer/assets.ts
- packages/store/src/transformer/job.ts
- packages/store/src/workspace/addon/blob.ts
- packages/store/src/workspace/addon/test.ts
- packages/store/src/workspace/addon/type.ts
- packages/store/src/workspace/page.ts
> feat(store): add gc in blob manager

- packages/blocks/src/_common/widgets/slash-menu/index.ts
Fix https://github.com/toeverything/blocksuite/issues/5197
> fix(page): questionmark with IME should not trigger slash menu

- packages/blocks/src/attachment-block/utils.ts
> refactor: avoid traversing in hasBlob

- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
> fix(edgeless): fix screen ratio not right after presentation

- packages/playground/.env
- packages/playground/vite.config.ts
Use production work by default in the local environment.
> chore(playground): playground default worker url

- packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
- packages/store/src/workspace/page.ts
> fix(edgeless): fix frame not update in collaboration

- packages/blocks/src/bookmark-block/embed.ts
https://github.com/toeverything/blocksuite/assets/18554747/7e224fad-53e7-4e41-8598-2f7dff95095d
> feat(page): support embed tweet in bookmark

- packages/blocks/src/_legacy/clipboard/edgeless-clipboard.ts
- packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
- packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
- packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
- packages/blocks/src/surface-block/elements/group/group-element.ts
- tests/edgeless/group.spec.ts
> fix(edgeless): group copy & paste

- packages/blocks/src/_common/components/rich-text/markdown/block.ts
- tests/code.spec.ts
> fix(page): keep content after converted to code block

- packages/blocks/src/database-block/common/columns/base-cell.ts
- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/table/controller/clipboard.ts
> feat(database): cells support cut operation

- packages/block-std/package.json
- packages/block-std/src/__tests__/command.unit.spec.ts
- packages/block-std/src/command/index.ts
- packages/block-std/tsconfig.json
- packages/block-std/vitest.config.ts
> fix(std): should not re-execute previous commands in the chain before `try`

- packages/editor/src/components/editor-container.ts
Related to https://github.com/toeverything/blocksuite/pull/5158
> chore: remove duplicate code

- packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
Before:
https://github.com/toeverything/blocksuite/assets/9301743/b756ba0b-3bab-4d14-822f-7e4de1465f78
After:
https://github.com/toeverything/blocksuite/assets/9301743/1aa989f5-2e65-4ae8-abd7-c583535ce329
> fix(edgeless): layout shift when switching editor mode

- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
> fix(edgeless): frames update in navigation

- packages/blocks/src/page-block/edgeless/components/auto-connect/edgeless-auto-connect-line.ts
- packages/blocks/src/page-block/edgeless/components/auto-connect/edgeless-index-label.ts
- packages/blocks/src/surface-block/surface-block.ts
- packages/store/src/workspace/page.ts
> fix(edgeless): local xywh update slots

- packages/blocks/src/_common/components/rich-text/rich-text.ts
- tests/code.spec.ts
- tests/selection/native.spec.ts
> fix(page): unexpected scroll in long text

- packages/blocks/src/_common/widgets/slash-menu/config.ts
> fix(page): unable to open link page entry from slash menu

- packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
> fix(edgeless): fix group copy as png

- packages/blocks/src/_common/utils/init.ts
- packages/editor/src/components/simple-affine-editor.ts
- packages/playground/apps/default/main.ts
- packages/playground/apps/default/presets/edgeless-empty.ts
- packages/playground/apps/default/presets/preset.ts
- packages/playground/apps/starter/data/database.ts
- packages/playground/apps/starter/data/empty.ts
- packages/playground/apps/starter/data/heavy-whiteboard.ts
- packages/playground/apps/starter/data/heavy.ts
- packages/playground/apps/starter/data/multiple-editor.ts
- packages/playground/apps/starter/data/pending-structs.ts
- packages/playground/apps/starter/data/preset.ts
- packages/playground/apps/starter/main.ts
- packages/store/src/__tests__/database.unit.spec.ts
- packages/store/src/__tests__/indexer.unit.spec.ts
- packages/store/src/__tests__/schema.unit.spec.ts
- packages/store/src/__tests__/workspace.unit.spec.ts
- packages/store/src/workspace/page.ts
- tests/utils/actions/misc.ts
Also fixes the timing of `page.slots.ready`
> feat(store): support `page.load(callback)`

- packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
close: https://github.com/toeverything/blocksuite/issues/5285
before:
https://github.com/toeverything/blocksuite/assets/15389209/33852ebb-13ff-418f-816d-833051d7e2a3
after:
https://github.com/toeverything/blocksuite/assets/15389209/351c46f7-6515-45cf-b885-20de4834d5be
> fix(page): stale number list index state

- packages/blocks/src/page-block/edgeless/connector-manager.ts
resolve #5183 
before:
https://github.com/toeverything/blocksuite/assets/117659326/7bd2e385-03ac-481a-a0f7-3fe51da12ad7
after:
https://github.com/toeverything/blocksuite/assets/117659326/bb94b72e-2d93-47cc-8f77-f7f85d72f7d9
> feat(edgeless): optimize connector auto align

- packages/blocks/src/surface-block/surface-block.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
> fix(edgeless): group load order

- packages/blocks/src/list-block/utils/get-list-info.ts
> fix(page): support setting index of ordered list

- packages/blocks/src/_common/components/rich-text/virgo/nodes/link-node/link-popup/link-popup.ts
> fix(page): paste not work when trying to create a link in edgeless

- packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
resolve #5113 
https://github.com/toeverything/blocksuite/assets/117659326/1a771c19-8df3-4939-99b5-56f2b48ead6c
> feat(edgeless): copy image by alt drag

- packages/blocks/src/page-block/text-selection/gesture.ts
similar to https://github.com/toeverything/blocksuite/pull/4083
> fix: triple click issue

- packages/blocks/src/page-block/clipboard/index.ts
- packages/blocks/src/page-block/commands/model-crud/copy-selected-models.ts
- packages/blocks/src/page-block/commands/text-crud/delete-text.ts
> fix: delete should happen after copy when cut in new clipboard

- packages/blocks/src/_common/components/rich-text/virgo/nodes/link-node/affine-link.ts
close: #5246
https://github.com/toeverything/blocksuite/assets/15389209/12d4f693-ed8a-4f32-ab9e-236eca8d51ba
> fix(page): link popup unexpectedly disappear when hovering from bottom

- packages/blocks/src/_common/components/rich-text/virgo/nodes/affine-text.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
> feat(page): adjust font weight

- packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
resolve #5334 
https://github.com/toeverything/blocksuite/assets/117659326/8050af47-3f42-4806-a001-dd2725b4cba4
> feat(edgeless): double click for zoom

- packages/blocks/src/code-block/utils/consts.ts
- tests/export.spec.ts
> perf(page): change theme to improve code-block performance

- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-menu.ts
> fix(edgeless): remove fractional digits part of font size

- packages/blocks/src/page-block/doc/doc-page-block.ts
- tests/basic.spec.ts
- tests/edgeless/note.spec.ts
- tests/format-bar.spec.ts
> fix(page): prevent scrolling to bottom of page when clicking on sides of document

- packages/blocks/src/_common/widgets/edgeless-remote-selection/index.ts
- packages/blocks/src/page-block/edgeless/services/selection-manager.ts
> fix(edgeless): duplicated remote cursor

- packages/blocks/src/database-block/database-block.ts
https://github.com/toeverything/blocksuite/assets/18554747/0dad738e-b4b4-4063-949b-91cd3ad9bc15
> fix(page): disable database action in readonly

- packages/blocks/src/attachment-block/attachment-block.ts
> fix(page): attachment download

- packages/blocks/src/_common/components/toggle-switch.ts
> feat(edgeless): add toggle switch component

- packages/blocks/src/_common/widgets/drag-handle/index.ts
To close #5418 
https://github.com/toeverything/blocksuite/assets/99816898/57e352da-873c-49bf-bc1e-8a0ea02dc5a1
> fix(page): make sure closest note inside same editor page when there are multiple editors

- packages/blocks/src/_common/edgeless/note/consts.ts
- packages/blocks/src/page-block/edgeless/components/auto-complete/utils.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
- packages/blocks/src/page-block/edgeless/components/rects/edgeless-hover-rect.ts
- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/page-block/edgeless/utils/note-resize-observer.ts
This reverts commit 7c06e95d988a7bbd6fa06d3aa291dddfc95013e3 (following #5470)
> revert: note style compatibility

- packages/blocks/src/page-block/edgeless/components/auto-complete/utils.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-note-button.ts
- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
- tests/edgeless/note.spec.ts
- tests/utils/actions/edgeless.ts
- tests/utils/asserts.ts
> fix(edgeless): undo not work for note style change

- packages/blocks/src/image-block/image-block.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/image/edgeless-image.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/surface-block/managers/layer-manager.ts
- packages/blocks/src/surface-block/surface-block.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
> fix(edgeless): unable to render image in surface-ref

- packages/blocks/src/page-block/edgeless/components/component-toolbar/more-button.ts
- packages/blocks/src/page-block/edgeless/frame-manager.ts
> fix(edgeless): copy-as-png not work for nested frame

- packages/docs/.vitepress/config.ts
- packages/docs/index.md
- docs: update index desc
- docs: update
> docs: update index desc

- packages/blocks/src/_legacy/content-parser/index.ts
To close #5512 
https://github.com/toeverything/blocksuite/assets/99816898/4154c70e-6d06-44b0-afb9-ae35ef4c92b2
> fix(edgeless): image inside frame cannot be copied as png

- packages/blocks/src/database-block/common/header/tools/view-options.ts
- packages/blocks/src/database-block/common/header/views.ts
> fix(database): edit view modal position is wrong

- packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
close: https://github.com/toeverything/blocksuite/issues/5472
> fix(database): column repeated setting to text type causes an error

- packages/blocks/src/surface-block/managers/layer-manager.ts
- packages/blocks/src/surface-block/surface-block.ts
before:
https://github.com/toeverything/blocksuite/assets/117659326/3887407c-8e83-4b90-babe-d308dc75eaa4
after:
https://github.com/toeverything/blocksuite/assets/117659326/0917ba98-fbd6-4f2d-8e5b-069fc19cb8dd
> fix(edgeless): no connector after refresh page

- packages/blocks/src/_common/adapters/gfm.ts
Remove the type ignore comment
Related to https://github.com/toeverything/blocksuite/pull/5541
See also [this parameters](https://www.typescriptlang.org/docs/handbook/2/classes.html#this-parameters)
> fix: types for this

- packages/store/src/__tests__/block-tree.unit.spec.ts
- packages/store/src/__tests__/yjs.unit.spec.ts
- packages/store/src/reactive/proxy.ts
- packages/store/src/reactive/utils.ts
- packages/store/src/workspace/block/block.ts
The `isLocalProxy` in yjs transaction is not reliable when updates are triggered frequently.
> fix(store): avoid unstable local transaction

- packages/blocks/src/page-block/edgeless/components/notes-toc-panel/toc-panel.ts
> fix(edgeless): define toggle switch error

- packages/blocks/src/_common/components/rich-text/keymap/container.ts
> fix(page): support `shift` in markdown

- packages/blocks/src/bookmark-block/components/bookmark-caption.ts
> fix(page): bookmark caption background style

- packages/blocks/src/page-block/edgeless/components/component-toolbar/align-button.ts
> fix(edgeless): group multi alignment

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/surface-block/surface-block.ts
> fix(edgeless): surface canvas resize effect

- packages/blocks/src/attachment-block/utils.ts
- packages/blocks/src/surface-block/surface-model.ts
- packages/blocks/src/surface-block/surface-transformer.ts
- packages/store/src/__tests__/block-tree.unit.spec.ts
- packages/store/src/schema/base.ts
- packages/store/src/utils/utils.ts
- packages/store/src/workspace/block/block-tree.ts
- packages/store/src/workspace/block/block.ts
- packages/store/src/workspace/page.ts
https://github.com/toeverything/blocksuite/assets/10047788/7d21aec7-68d7-4c97-8c74-4c9f5e206733
> feat(store): add stash and pop for block model

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
> fix(edgeless): update `z-index` style

- packages/blocks/src/_common/widgets/format-bar/components/highlight/highlight-button.ts
- packages/blocks/src/_common/widgets/format-bar/components/paragraph-button.ts
- packages/blocks/src/_common/widgets/format-bar/format-bar.ts
- packages/blocks/src/_common/widgets/format-bar/styles.ts
This pull request includes the following changes:
- Align the paragraph panel of the format bar.
- Add some offset to the hover panels on the format bar.
- Increase the hover delay for the hover panels.
https://github.com/toeverything/blocksuite/assets/18554747/8d8e1d4e-7f8a-4b0d-96fc-7c76c9a41954
> fix: update format bar styles

- packages/blocks/src/database-block/common/detail/layout.ts
> fix(database): detail panel position auto update

- packages/blocks/src/page-block/edgeless/components/toolbar/edgeless-toolbar.ts
> fix(edgeless): ui styling issues

- packages/docs/.vitepress/config.ts
Upstream: https://github.com/vuejs/vitepress/issues/3323
> docs: fix DOMException on encountering {} in markdown

- packages/blocks/src/list-block/utils/get-list-info.ts
> fix(page): reset list index for non-list in between

- packages/blocks/src/surface-block/managers/layer-manager.ts
- packages/presets/tests/edgeless/layer.spec.ts
- packages/presets/tests/utils/edgeless.ts
> fix(edgeless): sort in layer manager init method

- packages/docs/.vitepress/theme/index.ts
- packages/docs/components/code-sandbox.vue
- packages/docs/package.json
- packages/docs/quick-start.md
- pnpm-lock.yaml
> fix: doc site sandbox config

- packages/blocks/src/_common/transformers/html.ts
- packages/blocks/src/_common/transformers/index.ts
- packages/blocks/src/_common/transformers/markdown.ts
- packages/blocks/src/_common/transformers/middlewares.ts
- packages/blocks/src/_common/transformers/utils.ts
- packages/blocks/src/_common/transformers/zip.ts
- packages/blocks/src/_legacy/content-parser/file-exporter/file-exporter.ts
- packages/blocks/src/page-block/clipboard/index.ts
- packages/playground/apps/default/components/quick-edgeless-menu.ts
- packages/playground/apps/starter/components/debug-menu.ts
> feat: export html and markdown transformer

- packages/blocks/src/_common/adapters/markdown.ts
> fix(page): trim end when using slice snapshot

- packages/blocks/src/_common/components/toast.ts
Fix typo in https://github.com/toeverything/blocksuite/pull/4606
> fix: toast font

- packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-group-title-editor.ts
> fix: title editor with max height

- packages/presets/src/fragments/toc-panel/toc-card.ts
- packages/presets/src/fragments/toc-panel/toc-panel-body.ts
To close #5680 
https://github.com/toeverything/blocksuite/assets/99816898/58b49875-30de-4773-a283-806d075dcd73
> feat(presets): support highlight block through TOC

- packages/presets/src/fragments/toc-panel/toc-panel-body.ts
Update style requested by design.
> feat(presets): update TOC highlight style

- packages/blocks/src/embed-github-block/embed-github-block.ts
> fix: style for embed github block

- packages/blocks/src/image-block/utils.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/blocks/src/page-block/widgets/block-hub/components/block-hub.ts
> fix(edgeless): undo/redo on image dragging

- packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
- packages/blocks/src/page-block/edgeless/utils/clipboard-utils.ts
> fix(edgeless): switch to unified clipboard logic

- packages/blocks/src/_common/utils/url.ts
- packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
https://github.com/toeverything/blocksuite/assets/50035259/c166ba01-625d-4cdf-b9ca-cac64f4417c8
> feat(edgeless): support add bookmark by pasting link

- packages/blocks/src/bookmark-block/components/bookmark-caption.ts
- packages/blocks/src/bookmark-block/doc-bookmark-block.ts
- packages/blocks/src/bookmark-block/edgeless-bookmark-block.ts
Fix https://github.com/toeverything/blocksuite/issues/5607
> fix(page): caption input unexpectedly disappears

- packages/blocks/src/surface-block/elements/connector/utils.ts
To fix [TOV-151](https://linear.app/affine-design/issue/TOV-151/the-endpoints-of-the-connector-have-detail-issues)
https://github.com/toeverything/blocksuite/assets/99816898/6462f81d-870f-43b4-bd2b-905f454aa377
> fix(edgeless): wrong connector start endpoint style when rotation

- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
> fix(edgeless): insert bookmark in note block in edgeless mode will trigger unexpected error

- packages/blocks/src/_common/components/rich-text/inline/nodes/reference-node.ts
> fix(page): incorrectly delete behavior when trying to delete reference node

- packages/blocks/src/_common/adapters/markdown.ts
- packages/blocks/src/database-block/common/literal/renderer/date-literal.ts
See https://github.com/toeverything/AFFiNE/actions/runs/7262136823/job/19784924974?pr=5343
> fix: date-fns import

- packages/inline/src/inline-editor.ts
- packages/inline/src/tests/editor.unit.spec.ts
- packages/inline/src/tests/inline-editor.spec.ts
- packages/store/src/__tests__/__snapshots__/transformer.unit.spec.ts.snap
- packages/store/src/reactive/text.ts
- packages/store/src/transformer/json.ts
close: #5753
https://github.com/toeverything/blocksuite/assets/15389209/a76a108a-7957-447c-9df2-e46befbef2d8
> fix: replace `\r` for windows in clipboard

- packages/presets/src/fragments/toc-panel/toc-panel-body.ts
Should have only one highlight mask and reset timeout when user click TOC blocks quickly.
https://github.com/toeverything/blocksuite/assets/99816898/19b39fb5-c544-44c4-84cf-ddeeb3050109
> fix(presets): should have only one highlight mask

- packages/block-std/src/clipboard/index.ts
- packages/blocks/src/_common/adapters/html.ts
- packages/blocks/src/_common/adapters/html.unit.spec.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/code-block/components/code-option.ts
- packages/blocks/src/code-block/utils/high-lighter.ts
> fix(page): code block copy error

- packages/blocks/src/_common/components/rich-text/inline/nodes/reference-node.ts
- packages/blocks/src/_common/components/rich-text/rich-text.ts
- packages/blocks/src/_common/utils/inline-editor.ts
- packages/blocks/src/database-block/common/header-area/text.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-group-title-editor.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-shape-text-editor.ts
- packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
- packages/blocks/src/page-block/utils/callback.ts
- packages/blocks/src/page-block/widgets/linked-page/index.ts
- packages/blocks/src/page-block/widgets/slash-menu/index.ts
- packages/inline/src/components/embed-gap.ts
- packages/inline/src/inline-editor.ts
- packages/inline/src/services/delta.ts
- packages/inline/src/services/range.ts
- packages/inline/src/services/text.ts
- packages/inline/src/tests/utils.ts
- packages/inline/src/utils/embed.ts
- packages/inline/src/utils/guard.ts
- packages/inline/src/utils/index.ts
- packages/inline/src/utils/range-conversion.ts
- packages/playground/examples/inline/test-page.ts
- packages/presets/src/fragments/frame-panel/card/frame-card-title-editor.ts
- Rename slot
- Extract functions for CRUD operations on text into the text service
- Remove unnecessary attributes
> refactor(inline): update slots and extract text service

- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/page-block/widgets/image-toolbar/image-toolbar.ts
Try fix https://github.com/toeverything/blocksuite/issues/5793
before
https://github.com/toeverything/blocksuite/assets/18554747/9b4c1a13-23a9-44c8-bde9-dae0de0f3081
after
https://github.com/toeverything/blocksuite/assets/18554747/af49e36a-3201-42f5-a41d-c9aff4f1359b
> fix(page): limit shift of side panel toolbar

- packages/blocks/src/_common/adapters/markdown.ts
- packages/blocks/src/_common/adapters/markdown.unit.spec.ts
- packages/store/src/adapter/base.ts
> fix(page): parse html tag as plain text

- packages/blocks/src/_common/adapters/notion-html.ts
- packages/blocks/src/page-block/widgets/linked-page/import-page/import-page.ts
Based on #5710.
This closes #5504.
> fix(page): merge empty pages in notion database

- packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
https://github.com/toeverything/blocksuite/assets/99816898/deccb39e-0ede-4655-be1e-4556b8598afe
> fix(edgeless): top level block drag handle position

- packages/blocks/src/_common/components/drag-indicator.ts
- packages/blocks/src/_common/components/file-drop-manager.ts
> fix(page): attachment file drop position

- packages/blocks/src/page-block/edgeless/controllers/tools/default-tool.ts
- packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/surface-block/surface-block.ts
> feat(edgeless): shift selection optimization

- packages/blocks/src/page-block/widgets/doc-dragging-area/doc-dragging-area.ts
- packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
- packages/blocks/src/page-block/widgets/format-bar/format-bar.ts
- packages/presets/src/editors/doc-editor.ts
- packages/presets/src/fragments/page-meta-tags/page-meta-tags.ts
- packages/presets/src/fragments/toc-panel/toc-panel-body.ts
> fix(page): doc-dragging-area and overlay positions after page scroll

- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-shape-button.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-text-menu.ts
- packages/blocks/src/page-block/edgeless/components/panel/color-panel.ts
- packages/blocks/src/page-block/edgeless/components/panel/line-width-panel.ts
- packages/blocks/src/page-block/edgeless/components/panel/one-row-color-panel.ts
closes #5772 
[TOV-263](https://linear.app/affine-design/issue/TOV-263/shape-with-text-toolbar-redesigned)
> feat(edgeless): update shape with text toolbar

- packages/blocks/src/page-block/edgeless/components/text/edgeless-text-editor.ts
- packages/blocks/src/page-block/font-loader/font-loader.ts
- packages/blocks/src/surface-block/elements/text/utils.ts
- tests/paragraph.spec.ts
[TOV-198](https://linear.app/affine-design/issue/TOV-198/fix-the-canvas-text-inconsistency-between-view-and-editing-state)
> fix(edgeless): canvas text inconsistency between view and editing state

- packages/blocks/src/page-block/clipboard/middlewares/paste.ts
> fix(page): set language to be merged when pasting

- packages/presets/tsconfig.json
> fix(presets): emit in tsconfig

- packages/blocks/src/_common/components/rich-text/rich-text.ts
Fix https://github.com/toeverything/blocksuite/issues/5880
> fix(page): unexpected line wrap in code block

- .github/CLA.md
- packages/blocks/src/_common/components/tags/multi-tag-select.ts
This is related to https://github.com/toeverything/AFFiNE/issues/4537 , from affine Repo. 
https://github.com/toeverything/blocksuite/assets/83939820/596e89dc-3824-4a38-9390-583985eaf516
> fix(page): tag value retention

- packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
completing draghandle fixme for surface selection path after #5852
> fix: complete draghandle fixme

- packages/block-std/src/event/control/range.ts
- packages/block-std/src/event/dispatcher.ts
- packages/blocks/src/image-block/doc-image-block.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/page-block/page-service.ts
- tests/paragraph.spec.ts
\cc: @doodlewind @AyushAgrawal-A2
> fix: should not relay on business logic in block std

- packages/blocks/src/__tests__/adapters/html.unit.spec.ts
- packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
- packages/blocks/src/_common/adapters/html.ts
- packages/blocks/src/_common/adapters/notion-html.ts
- packages/blocks/src/page-block/clipboard/index.ts
- tests/database/clipboard.spec.ts
This closes #5829, closes #5877, closes #5897.
> feat(page): general html import

- packages/blocks/src/paragraph-block/paragraph-block.ts
> fix(edgeless): change paragraph block placeholder text color

- packages/blocks/src/code-block/affine-code-line.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/page-block/widgets/image-toolbar/image-toolbar.ts
Fix https://github.com/toeverything/blocksuite/issues/5931
> fix(page): show whitespace when wrap code

- packages/blocks/src/page-block/edgeless/components/auto-complete/auto-complete-panel.ts
- packages/blocks/src/page-block/edgeless/components/auto-complete/utils.ts
https://github.com/toeverything/blocksuite/assets/99816898/d1a4ad31-c0b9-4a62-9748-3a71101b6e8e
> fix(edgeless): auto-complete panel position

- packages/blocks/src/_common/adapters/html.ts
- packages/blocks/src/_common/adapters/image.ts
- packages/blocks/src/_common/adapters/markdown.ts
- packages/blocks/src/_common/adapters/notion-html.ts
- packages/blocks/src/_common/transformers/markdown.ts
- packages/docs/adapter.md
- packages/presets/src/fragments/copilot-panel/utils/markdown-utils.ts
- packages/store/src/adapter/base.ts
> fix(page): add clipboard fallbacks

- packages/blocks/src/paragraph-block/paragraph-block.ts
> fix(page): update heading font weight

- packages/blocks/src/_common/transformers/index.ts
- packages/blocks/src/_common/transformers/middlewares.ts
- packages/blocks/src/image-block/image-service.ts
> feat: expose image proxy url setter

- packages/blocks/src/page-block/edgeless/edgeless-keyboard.ts
- tests/edgeless/selection.spec.ts
> fix(edgeless): clear selection on pressing esc

- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
it will cause affine test fail
\cc @AyushAgrawal-A2
> fix: import use .js postfix

- packages/blocks/src/_common/export-manager/export-manager.ts
- packages/presets/src/editors/affine-doc-editor.ts
To close [TOV-402](https://linear.app/affine-design/issue/TOV-402/pdf导出有问题（长内容导出只有首屏）)
https://github.com/toeverything/blocksuite/assets/99816898/119c7a8d-c3de-49eb-946e-7f5427c65a8f
> fix(page): export long page to png

- packages/blocks/src/_common/consts.ts
- packages/blocks/src/embed-youtube-block/styles.ts
> fix: change video embed card dimensions

- packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
[TOV-406](https://linear.app/affine-design/issue/TOV-406/optimize-the-implementation-effect-of-turning-inline-view-into-card)
> fix(page): change text attribute on converting inline-link to card

- packages/blocks/src/_common/components/embed-card/modal/embed-card-create-modal.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
- packages/blocks/src/page-block/widgets/block-hub/components/block-hub.ts
- packages/blocks/src/page-block/widgets/slash-menu/config.ts
- tests/bookmark.spec.ts
[TOV-385](https://linear.app/affine-design/issue/TOV-385/the-name-of-the-entry-point-for-adding-links-and-the-text-in-the-pop)
> fix: change title/tooltip/description of entry points for adding link

- packages/blocks/src/bookmark-block/styles.ts
- packages/blocks/src/embed-github-block/styles.ts
- packages/blocks/src/embed-youtube-block/styles.ts
[TOV-381](https://linear.app/affine-design/issue/TOV-381/when-the-mouse-hovers-over-these-two-positions-the-cursor-should)
> fix: cursor pointer on hover over card url

- packages/blocks/src/_common/inline/presets/affine-inline-specs.ts
before:
https://github.com/toeverything/blocksuite/assets/50035259/dbd9ddbb-05a8-4ad2-a9f1-b4484c3035c2
after:
https://github.com/toeverything/blocksuite/assets/50035259/49852e33-9847-4e85-82d1-7418e4d372b0
> fix: unexpected spaces in the inline node

- packages/blocks/src/_common/components/embed-card/modal/embed-card-create-modal.ts
- packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
- packages/blocks/src/page-block/widgets/block-hub/components/block-hub.ts
- packages/blocks/src/page-block/widgets/slash-menu/config.ts
[TOV-386](https://linear.app/affine-design/issue/TOV-386/in-the-adding-youtube-and-github-pop-ups-the-strong-validation-for-the)
> fix: `embed-card-create-portal` - remove block specific url validation

- packages/blocks/src/_common/types.ts
- packages/blocks/src/page-block/doc/doc-page-block.ts
- packages/blocks/src/page-block/edgeless/edgeless-page-block.ts
- packages/blocks/src/page-block/widgets/doc-dragging-area/doc-dragging-area.ts
- packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
- packages/blocks/src/page-block/widgets/drag-handle/utils.ts
- packages/presets/src/fragments/doc-title/doc-title.ts
before:
https://github.com/toeverything/blocksuite/assets/54364088/12633a02-cbf2-410b-935e-a94a60548944
after:
https://github.com/toeverything/blocksuite/assets/54364088/22db2e16-a9db-43c4-9dc5-4934594783ec
> fix: dragPreview / dropIndicator / dragEndPos viewport offsets

- packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/image-block/image-block.ts
bug:
https://github.com/toeverything/blocksuite/assets/54364088/4f5af9a4-e76d-4bb8-8f73-f2d2bb7a8ca5
> fix(edgeless): incorrect dragStart in surface

- packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
- packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
- packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
bug:
https://github.com/toeverything/blocksuite/assets/54364088/826ee4a7-4a6b-4d7b-92b5-de2c24c7a696
> fix(edgeless): embed-card toolbar incorrect card styles

- packages/block-std/src/clipboard/index.ts
- packages/blocks/src/_common/adapters/html.ts
- packages/blocks/src/_common/adapters/utils.ts
> fix(page): empty clipboard because of transient activation

- packages/blocks/src/_common/icons/edgeless.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/note/edgeless-note.ts
> feat(edgeless): show a arrow button when a note was clipped

- packages/blocks/src/_common/configs/quick-action/config.ts
bug: https://github.com/toeverything/blocksuite/pull/5998#issuecomment-1894850393
> fix(page): linked page should show new title

- packages/blocks/src/_common/components/embed-card/embed-card-style-popper.ts
- packages/blocks/src/bookmark-block/doc-bookmark-block.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/playground/apps/default/components/quick-edgeless-menu.ts
- packages/playground/apps/default/main.ts
- packages/playground/apps/default/utils/providers.ts
- packages/playground/apps/starter/components/debug-menu.ts
- packages/playground/apps/starter/data/index.ts
- packages/playground/apps/starter/main.ts
- packages/playground/scripts/hmr-plugin/index.ts
@regischen 
I did a regex search and removed all occurrences. sorry for the oversight.
> fix: add .js postfix

- packages/inline/src/inline-editor.ts
- packages/inline/src/services/range.ts
Before:
https://github.com/toeverything/blocksuite/assets/50035259/9c3fa4c8-a434-4af9-983e-1b4617803f47
After:
https://github.com/toeverything/blocksuite/assets/50035259/0850afc7-c9a9-480f-9724-ca591f1d5a3d
> feat(inline): support for relative position correction in collaborative scenarios

- packages/presets/src/editors/affine-doc-editor.ts
- packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
- tests/image.spec.ts
- tests/selection/block.spec.ts
> fix: remove link panel from affine-doc-editor

- packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
[TOV-373](https://linear.app/affine-design/issue/TOV-373/bookmark-缩放的角标)
[TOV-374](https://linear.app/affine-design/issue/TOV-374/image-缩放的角标)
> feat(edgeless): add mouse styles on note, image, embed-* & bookmark block scaling

- packages/blocks/src/_common/components/hover/controller.ts
- packages/blocks/src/_common/components/tooltip/tooltip.ts
- packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/bookmark-block/doc-bookmark-block.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/embed-figma-block/embed-figma-block.ts
- packages/blocks/src/embed-github-block/embed-github-block.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
- packages/blocks/src/page-block/widgets/format-bar/format-bar.ts
- packages/blocks/src/page-block/widgets/image-toolbar/image-toolbar.ts
- packages/blocks/src/page-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
- packages/lit/src/utils/range-binding.ts
- tests/format-bar.spec.ts
- tests/link.spec.ts
[TOV-417](https://linear.app/affine-design/issue/TOV-417/blocks-with-their-own-floating-menu-should-not-display-the-format)
closes #6013 
https://github.com/toeverything/blocksuite/assets/54364088/b2c679e2-5ce9-4e37-af7e-4e9da2c18bfb
> fix(page): show only one toolbar at a time

- packages/blocks/src/image-block/doc-image-block.ts
close #6045
close #6036
close #5912
https://github.com/toeverything/blocksuite/assets/15389209/cba9a391-8230-4700-974e-43742f76961c
> fix: don't delete image when deleting in caption

- packages/block-std/src/event/base.ts
- packages/block-std/src/event/control/clipboard.ts
- packages/block-std/src/event/control/keyboard.ts
- packages/block-std/src/event/control/pointer.ts
- packages/block-std/src/event/control/range.ts
- packages/block-std/src/event/dispatcher.ts
- packages/block-std/src/event/state/source.ts
- packages/lit/src/element/block-element.ts
- tests/edgeless/selection.spec.ts
Closes: https://github.com/toeverything/blocksuite/issues/6052
> fix: event scope source type

- packages/blocks/src/_common/utils/model.ts
- packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
> fix: card-view linked page display in backlink

- packages/blocks/src/page-block/edgeless/utils/note.ts
To fix [TOV-452](https://linear.app/affine-design/issue/TOV-452/新-note-创建的时候没有进入文字的激活状态，需要点击后才能添加文字。)
https://github.com/toeverything/blocksuite/assets/99816898/3c9ad066-e651-4f9a-8e44-7a40181d6513
> fix(edgeless): should focus at note after creating it

- packages/blocks/src/page-block/doc/doc-page-block.ts
> fix: unexpected cursor position after clicking page outside

- packages/block-std/src/clipboard/index.ts
- packages/blocks/src/_common/adapters/attachment.ts
- packages/blocks/src/_common/adapters/index.ts
- packages/blocks/src/page-block/clipboard/index.ts
> feat(page): support pasting files as attachment

- packages/blocks/src/bookmark-block/components/bookmark-card.ts
- packages/blocks/src/embed-github-block/embed-github-block.ts
- packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
bug:
https://github.com/toeverything/blocksuite/assets/54364088/30ac9537-03a8-4ef1-9142-8de1a599abe2
> fix: card banner images should not be draggable

- packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
FIx [TOV-445](https://linear.app/affine-design/issue/TOV-445/白板group-copyandpaste-失灵)
> fix: group paste bug

- packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
Bug:
https://github.com/toeverything/blocksuite/assets/54364088/d2d3a321-e657-450a-acc9-a66dcb7db3dc
> fix(edgeless): prevent native selection on drag select in edgeless

- packages/blocks/src/surface-ref-block/surface-ref-block.ts
> fix: surface ref should not contenteditable

- packages/blocks/src/surface-block/surface-block.ts
> fix(edgeless): should rerender when new element was added or removed

- README.md
- packages/docs/.vitepress/config.ts
- packages/docs/.vitepress/theme/index.ts
- packages/docs/blog/crdt-native-data-flow.md
- packages/docs/blog/design-philosophy.md
- packages/docs/blog/document-centric.md
- packages/docs/blog/index.md
- packages/docs/guide/component-types.md
- packages/docs/guide/data-synchronization.md
- packages/docs/guide/overview.md
- packages/docs/guide/selection.md
- packages/docs/index.md
- packages/inline/README.md
- docs: move blog
- docs: reorg blog scaffold
> docs: reorg blog scaffold

- packages/blocks/src/page-block/edgeless/components/note-slicer/index.ts
Update style and expand dividing line clickable area.
> feat(edgeless): optimize note slicer

- packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
[TOV-507](https://linear.app/affine-design/issue/TOV-507/notes-scales-bug-it-will-effect-the-drag-handle-on-page-mode)
> fix: drag-handle note-scale in page mode

- packages/blocks/src/_common/adapters/html.ts
Fix https://github.com/toeverything/blocksuite/issues/6042
> fix: support export scaled images in html

- packages/blocks/src/list-block/utils/get-list-icon.ts
- packages/blocks/src/list-block/utils/icons.ts
[TOV-508](https://linear.app/affine-design/issue/TOV-508/bullet-list-style-update)
closes #6136
> fix(page): bullet list style update

- packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
- packages/blocks/src/_common/adapters/markdown.ts
- packages/framework/store/src/adapter/context.ts
This closes #6043, closes #6016.
> fix(page): markdown export list early closing issue

- packages/blocks/src/page-block/edgeless/components/toolbar/template/builtin-templates.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/presets/src/__tests__/edgeless/template.spec.ts
- Add basic test for template
- Fix surface-ref slot is not disposed correctly
> fix(edgeless): template and surface-ref bug

- packages/blocks/src/note-block/note-block.ts
- packages/blocks/src/page-block/widgets/drag-handle/drag-handle.ts
- packages/blocks/src/page-block/widgets/drag-handle/utils.ts
[TOV-523](https://linear.app/affine-design/issue/TOV-523/hold-optionalt-for-windows-drag-and-drop-to-copy-imagelinks)
> feat(edgeless): support copy by option + drag

- packages/blocks/src/surface-block/managers/edit-session.ts
- packages/presets/src/fragments/outline-panel/outline-panel.ts
https://github.com/toeverything/blocksuite/assets/99816898/3c34a2ac-0636-4649-b8eb-298caf3c099e
> feat(presets): store outline settings in session

- packages/blocks/src/image-block/image-block.ts
- packages/blocks/src/image-block/utils.ts
before:
https://github.com/toeverything/blocksuite/assets/54364088/5b59d767-0510-439b-964b-9ee25c2e6063
after:
https://github.com/toeverything/blocksuite/assets/54364088/a2bf0e1b-734a-45a2-9fa1-b24d8a70140a
> fix(page): should be able to convert embed image card to image block

- packages/blocks/src/note-block/note-block.ts
- packages/blocks/src/page-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/blocks/src/page-block/widgets/drag-handle/utils.ts
- packages/blocks/src/page-block/widgets/format-bar/format-bar.ts
> fix: hide format-bar / component-toolbar while dragging

- packages/blocks/src/_common/inline/inline-manager.ts
> fix: can not render link node with bold style

- packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
> fix: link-popup input background color in dark mode

- packages/blocks/src/synced-block/synced-block.ts
- packages/playground/apps/default/main.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/data/utils.ts
- packages/playground/apps/starter/main.ts
- packages/playground/apps/starter/utils/editor.ts
- packages/playground/apps/starter/utils/workspace.ts
Bug:
https://github.com/toeverything/blocksuite/assets/54364088/2c960f35-76a6-4515-b4fe-af2ef201b4ae
> fix: linked & synced starter examples should work

- packages/blocks/src/_common/components/rich-text/hooks.ts
- packages/framework/inline/src/services/event.ts
- packages/framework/inline/src/services/hook.ts
> fix: should not extend attributes when composing

- packages/blocks/src/__tests__/adapters/html.unit.spec.ts
- packages/blocks/src/_common/adapters/hast.ts
- packages/blocks/src/_common/adapters/html.ts
https://github.com/toeverything/AFFiNE/issues/5705
Closes #5983.
> fix(page): flat p and div nodes inside list

- packages/blocks/src/attachment-block/attachment-transformer.ts
- packages/blocks/src/image-block/image-transformer.ts
- packages/framework/store/src/transformer/assets.ts
> fix(page): clipboard payload does not have assets

- packages/blocks/src/_common/components/rich-text/rich-text.ts
Ref: https://github.com/toeverything/AFFiNE/issues/5814
> fix(page): normalize newline characters

- packages/docs/index.md
- packages/framework/inline/src/components/v-text.ts
Subject: Resolve Word Break Issue in Table Layout
This pull request addresses and resolves the word break issue identified in [@AFFiNE#5676](https://github.com/toeverything/AFFiNE/issues/5676). Previously, the table layout experienced undesired breaks between words. With this update, the issue has been rectified, and the table now breaks words appropriately.
Link to Issue:
[@AFFiNE#5676](https://github.com/toeverything/AFFiNE/issues/5676)
Before
After
> fix(inline): line break issue

- .commitlintrc.json
- packages/framework/block-std/src/selection/variants/text.ts
- packages/framework/lit/src/utils/range-manager.ts
> fix(lit): `textSelectionToRange` result incorrect when selection is reversed
