toeverything/blocksuite

packages/blocks/src/__tests__/database/database.unit.spec.ts
packages/framework/store/src/__tests__/indexer.unit.spec.ts
packages/framework/store/src/__tests__/workspace.unit.spec.ts
packages/framework/store/src/indexer/search.ts

refactor: avoid requestIdleCallback in nodejs

---

packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-tool-button.ts

close [TOV-413](https://linear.app/affine-design/issue/TOV-413/add-shortcut-keys-to-the-connectors-hovertips)

fix(edgeless): change connector toolbar tip

---

packages/blocks/src/_common/adapters/markdown.ts
packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
packages/blocks/src/_common/components/embed-card/modal/embed-card-edit-modal.ts
packages/blocks/src/_common/types.ts
packages/blocks/src/_common/utils/model.ts
packages/blocks/src/_specs/_specs.ts
packages/blocks/src/embed-loom-block/embed-loom-block.ts
packages/blocks/src/embed-loom-block/embed-loom-model.ts
packages/blocks/src/embed-loom-block/embed-loom-service.ts
packages/blocks/src/embed-loom-block/embed-loom-spec.ts
packages/blocks/src/embed-loom-block/index.ts
packages/blocks/src/embed-loom-block/styles.ts
packages/blocks/src/embed-loom-block/utils.ts
packages/blocks/src/index.ts
packages/blocks/src/models.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/component-toolbar.ts
packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts
packages/blocks/src/page-block/edgeless/components/toolbar/note/note-menu.ts
packages/blocks/src/page-block/edgeless/controllers/clipboard.ts
packages/blocks/src/page-block/edgeless/utils/query.ts
packages/blocks/src/page-block/widgets/slash-menu/config.ts
packages/blocks/src/surface-block/edgeless-types.ts
packages/blocks/src/surface-ref-block/portal/generic-block.ts
tests/utils/asserts.ts

Changes:
- Implemented embed-loom (doc & edgeless)
- Added loom option in slash-menu & edgeless-toolbar

feat: add support for embed loom

---

packages/blocks/src/_common/components/hover/when-hover.ts

Fix https://github.com/toeverything/blocksuite/issues/6241

fix: tooltip flickers when the mouse is moved slightly

---

packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/page-block/edgeless/components/component-toolbar/change-embed-card-button.ts
packages/framework/global/index.d.ts
packages/framework/store/src/workspace/store.ts
packages/playground/apps/default/utils/workspace.ts
packages/playground/apps/starter/data/synced.ts
packages/playground/apps/starter/utils/workspace.ts
packages/presets/src/__tests__/utils/setup.ts

Changes:
- Added `enable_synced_doc_block` flag in awareness store flags. This is enabled for playground environment.
To-Do
- Add this flag in AFFiNE and enable for canary.

feat: limit entry to synced doc block using awareness store flag

---

packages/blocks/src/page-block/doc/doc-page-block.ts
tsconfig.json

fix: cursor cannot be moved as expected in firefox

---

packages/blocks/src/frame-block/frame-block.ts
packages/blocks/src/frame-block/frame-model.ts
packages/blocks/src/page-block/edgeless/components/block-portal/frame/edgeless-frame.ts
packages/blocks/src/page-block/edgeless/components/text/edgeless-frame-title-editor.ts
packages/blocks/src/page-block/edgeless/edgeless-page-service.ts
packages/blocks/src/page-block/edgeless/frame-manager.ts
packages/blocks/src/page-block/edgeless/type.ts
packages/blocks/src/surface-block/element-model/base.ts
packages/blocks/src/surface-block/managers/connector-manager.ts

close [TOV-431](https://linear.app/affine-design/issue/TOV-431/frame-内的-frame-无法通过标题点击移动)

fix(edgeless): inner frame hittest

---

packages/blocks/src/_common/configs/text-format/utils.ts
packages/framework/inline/src/services/event.ts

fix: failed to select from empty line and unexpected format result in empty line

---

packages/blocks/src/_common/embed-block-helper/helper.ts

[TOV-479](https://linear.app/affine-design/issue/TOV-479/youtube-video-title-always-loading)

fix: resolve `this` error in LinkPreviewer

---

packages/blocks/src/_common/components/tags/styles.ts

close: #6198
https://github.com/toeverything/blocksuite/assets/15389209/8c90ac6a-09a6-4995-96be-de1d4a92bc62

fix(database): select column Popup position

---

packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts

[AFF-611](https://linear.app/affine-design/issue/AFF-611/combine-the-title-and-the-open-icon-as-a-unified-button)
[AFF-612](https://linear.app/affine-design/issue/AFF-612/change-hoverselect-status-for-pages-cardembed-view)
[AFF-617](https://linear.app/affine-design/issue/AFF-617/caption-function-is-not-working)

fix: synced doc toolbar & caption bug

---

packages/blocks/src/_common/configs/text-format/utils.ts

https://github.com/toeverything/blocksuite/issues/6220#issuecomment-1956467709

fix: unexpected format result when in block selection and empty line

---

packages/blocks/src/page-block/edgeless/components/toolbar/connector/connector-tool-button.ts
packages/blocks/src/page-block/edgeless/components/utils.ts

fix(edgeless): modify connector tip

---

packages/blocks/src/page-block/edgeless/type.ts
packages/blocks/src/surface-block/element-model/shape.ts
tests/edgeless/shape.spec.ts

To fix #6295 
https://github.com/toeverything/blocksuite/assets/99816898/6c09faad-b8f6-4bf6-832c-ec7320c3462d

fix(edgeless): cannot add text in hollow shape

---

packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/utils.ts

https://github.com/toeverything/blocksuite/assets/27926/f76dc01e-1692-4053-aef7-1fa5a7c9a57f

fix(edgeless): width or height should not be negative

---

packages/framework/global/package.json
packages/framework/global/src/exceptions/code.ts
packages/framework/global/src/exceptions/index.ts
packages/framework/global/src/utils/assert.ts
packages/framework/lit/src/element/lit-host.ts
packages/framework/store/src/schema/error.ts
packages/playground/apps/default/utils/workspace.ts

feat: add standard error types and handler

---

packages/blocks/src/_common/components/embed-card/embed-card-caption.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/blocks/src/database-block/common/header/title.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
packages/blocks/src/root-block/page/page-root-block.ts
packages/blocks/src/root-block/root-service.ts
packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
packages/framework/block-std/src/event/control/clipboard.ts
packages/framework/block-std/src/event/control/keyboard.ts
packages/framework/block-std/src/event/control/pointer.ts
packages/framework/block-std/src/event/control/range.ts
packages/framework/block-std/src/event/dispatcher.ts
packages/framework/block-std/src/event/index.ts
packages/framework/block-std/src/event/state/index.ts
packages/framework/lit/src/utils/range-binding.ts
packages/presets/src/fragments/doc-title/doc-title.ts
tests/basic.spec.ts
tests/database/database.spec.ts
tests/edgeless/selection.spec.ts
tests/link.spec.ts
tests/paragraph.spec.ts

refactor: no longer manually control the activation status of the event dispatcher

---

packages/framework/inline/src/__tests__/inline-editor.spec.ts
packages/framework/inline/src/services/event.ts
packages/framework/inline/src/utils/embed.ts

fix(inline): failed to delete embed node using backspace

---

.github/CLA.md
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts

fix(page): update code theme by page theme

---

packages/blocks/src/root-block/edgeless/controllers/tools/brush-tool.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/brush/index.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/brush/utils.ts
packages/blocks/src/surface-block/element-model/brush.ts
packages/framework/block-std/src/event/state/pointer.ts

https://github.com/toeverything/blocksuite/assets/20479050/090727e4-7cba-4f47-8d8f-3feed5e30caf

feat(edgeless): add pressure support for brush mode

---

packages/blocks/src/root-block/widgets/linked-doc/config.ts
packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts

feat(page): batch import

---

.eslintrc.cjs
packages/blocks/src/_common/adapters/html.ts
packages/blocks/src/_common/adapters/markdown.ts
packages/blocks/src/_common/adapters/notion-html.ts
packages/blocks/src/attachment-block/components/options.ts

This pull request adds `no-constant-binary-expression` lint rule, and fixes related logics.

fix: binary expression logic errors

---

examples/angular-basic/package.json
examples/preact-basic/package.json
examples/react-basic/package.json
examples/react-sqlite/package.json
examples/vue-basic/package.json

Test in https://stackblitz.com/github/toeverything/blocksuite/tree/flrande/chore/stackblitz/examples/vue-basic

chore(examples): add stackblitz config

---

packages/presets/src/editors/editor-container.ts
packages/presets/src/editors/page-editor.ts

fix(presets): editor should can be selected in readonly mode

---

.commitlintrc.json
packages/blocks/src/paragraph-block/paragraph-block.ts
tests/paragraph.spec.ts

fix(blocks): heading style should not influence children

---

.eslintrc.cjs
package.json
packages/blocks/src/database-block/common/datasource/database-block-datasource.ts
packages/blocks/src/root-block/widgets/slash-menu/config.ts
packages/framework/store/src/adapter/base.ts
pnpm-lock.yaml
tests/selection/block.spec.ts
tests/selection/native.spec.ts

Should reduce some performance wasting

fix: add no-useless-spread and fixes related codes

---

packages/blocks/src/root-block/widgets/format-bar/components/config-renderer.ts
packages/blocks/src/root-block/widgets/format-bar/config.ts
packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
packages/blocks/src/root-block/widgets/index.ts
packages/playground/apps/starter/utils/editor.ts
packages/presets/src/fragments/copilot-panel/copilot-panel.ts

Add Ask AI button in format-bar after #6433

fix: add ask ai in format-bar

---

packages/blocks/src/root-block/edgeless/components/toolbar/template/overlay-scrollbar.ts
packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts

fix(edgeless): use custom scrollbar for template panel

---

packages/blocks/src/root-block/commands/block-crud/get-selected-blocks.ts
packages/presets/src/__tests__/utils/setup.ts

fix(page): flat blockSelections to return consistent flat mode SelectedBlocks

---

packages/framework/block-std/src/selection/manager.ts
packages/framework/store/src/yjs/awareness.ts

Closes: [BS-165](https://linear.app/affine-design/issue/BS-165/whiteboard-出现其他用户光标)

fix: remote cursor shouldn't display on other docs

---

packages/blocks/src/list-block/list-block.ts
packages/blocks/src/list-block/styles.ts
packages/blocks/src/paragraph-block/paragraph-block.ts
tests/image.spec.ts

fix(blocks): inconsistent space between nested blocks

---

packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
packages/blocks/src/root-block/widgets/drag-handle/utils.ts
tests/edgeless/note.spec.ts

Closes: [BS-56](https://linear.app/affine-design/issue/BS-56/白板上，note-合并的功能坏了)

fix(edgeless): drag note to merge after a list item

---

packages/framework/inline/src/components/v-line.ts

fix(inline): v-line is not fully adapted for horizontal scrolling

---

packages/blocks/src/_common/export-manager/export-manager.ts

Quick fix. Close [BS-158](https://linear.app/affine-design/issue/BS-158/shared-之后，-insert-framegroup-的内容下载后为空).

fix(edgeless): group element to image

---

packages/blocks/src/_common/export-manager/export-manager.ts
packages/blocks/src/embed-youtube-block/embed-youtube-block.ts

feat(page): export the embed YouTube in the print mode

---

packages/presets/src/editors/edgeless-editor.ts
packages/presets/src/editors/page-editor.ts

related to https://github.com/toeverything/AFFiNE/pull/6075

fix(presets): editor should await host update complete

---

packages/blocks/src/_common/utils/query.ts
packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
tests/edgeless/auto-complete.spec.ts
tests/edgeless/note.spec.ts

To fix [BS-43](https://linear.app/affine-design/issue/BS-43/白板project-management图很难输入文字)
https://github.com/toeverything/blocksuite/assets/99816898/3824cb4d-627d-4b65-8f81-4f0f622b52ec

fix(edgeless): optimize edgeless note focus logic

---

packages/blocks/src/root-block/widgets/page-dragging-area/page-dragging-area.ts

related to https://github.com/toeverything/AFFiNE/pull/6070 and TOV-671

fix(blocks): drag area not handle viewport position correctly

---

packages/blocks/src/_common/adapters/html.ts
packages/blocks/src/_common/adapters/markdown.ts
packages/blocks/src/_common/adapters/notion-html.ts

fix(page): do not assert on parent

---

tsconfig.json

build: add sourcesContent into source maps

---

packages/blocks/src/_common/configs/quick-action/config.ts
packages/blocks/src/_common/utils/render-linked-doc.ts
packages/blocks/src/root-block/commands/model-crud/get-selected-models.ts
packages/blocks/src/root-block/keyboard/keyboard-manager.ts
packages/blocks/src/root-block/widgets/format-bar/config.ts
tests/format-bar.spec.ts
tests/utils/actions/keyboard.ts
tests/utils/query.ts

fix: create linked doc from block selection loss data

---

examples/angular-basic/angular.json
examples/angular-basic/src/app/app.config.ts
examples/angular-basic/src/app/sidebar/sidebar.component.ts

close #6431
Note that adding `changeDetection: ChangeDetectionStrategy.OnPush,` in `editor-container.component.ts` doesn't work.
Thanks @andantonyan for the hint!

fix(examples): angular compat and list reactivity

---

packages/presets/src/fragments/copilot-panel/copilot-panel.ts

fix(presets): fragment import suffix

---

.eslintrc.cjs
examples/preact-basic/tsconfig.json
examples/react-basic-next/tsconfig.json
examples/react-basic/.eslintrc.cjs
examples/react-basic/tsconfig.json
examples/react-sqlite/.eslintrc.cjs
examples/react-sqlite/tsconfig.json
examples/solid-basic/tsconfig.json
examples/vanilla-indexeddb/tsconfig.json
examples/vue-basic/tsconfig.json
packages/presets/vitest.config.ts
tsconfig.json

https://caniuse.com/?search=es2022
Dependency of #6526.

build: switch to es2022 targets

---

package.json
packages/blocks/package.json
packages/blocks/src/root-block/clipboard/adapter.ts
packages/blocks/src/root-block/clipboard/utils.ts
pnpm-lock.yaml

Reverts toeverything/blocksuite#6526

revert: bson for clipboard mime

---

packages/blocks/src/database-block/table/group.ts

close: https://github.com/toeverything/blocksuite/issues/6559

feat(database): focus to title column when click `New Record` button

---

packages/blocks/src/database-block/kanban/controller/hotkeys.ts

close: https://github.com/toeverything/blocksuite/issues/6044

feat(database): supports Tab key to focus to the next field in Kanban view

---

packages/blocks/src/database-block/table/components/menu.ts
packages/blocks/src/database-block/table/components/row.ts
packages/blocks/src/database-block/table/controller/selection.ts
packages/blocks/src/database-block/table/group.ts

fix(database): incorrect insertion and focus position

---

packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
packages/blocks/src/database-block/common/header-area/text.ts

close: https://github.com/toeverything/blocksuite/issues/6213

fix(database): select all text in the rich-text cell by press Ctrl+A or Cmd+A

---

packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-menu.ts
packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts

feat(edgeless): connector keep only one shortcut key L

---

packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
packages/blocks/src/root-block/edgeless/components/auto-complete/utils.ts

Closes: BS-98
https://github.com/toeverything/blocksuite/assets/27926/323eca92-d0ef-4387-8690-b4ff7221d2bb

fix(edgeless): auto complete panel position

---

packages/blocks/src/root-block/widgets/slash-menu/config.ts

Fix https://github.com/toeverything/blocksuite/issues/6568

fix(page): should not remove empty line when canceling insertion

---

packages/blocks/src/database-block/kanban/controller/drag.ts

close: https://github.com/toeverything/blocksuite/issues/5957
close: OPE-149

fix(database): cannot move Kanban card when text-field was selected last

---

packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
packages/blocks/src/surface-block/managers/edit-session.ts
packages/presets/src/__tests__/edgeless/last-props.spec.ts

fix(edgeless): connector default color

---

packages/blocks/src/root-block/edgeless/components/connector/connector-handle.ts
packages/blocks/src/surface-block/managers/connector-manager.ts
packages/blocks/src/surface-block/utils/math-utils.ts

fix(edgeless): connector indicator style

---

packages/blocks/src/database-block/kanban/controller/drag.ts
packages/blocks/src/database-block/table/components/column-header/column-renderer.ts
packages/blocks/src/database-block/table/components/column-header/database-header-column.ts
packages/blocks/src/database-block/table/controller/drag.ts
packages/blocks/src/database-block/table/controller/selection.ts
packages/blocks/src/database-block/utils/drag.ts
packages/blocks/src/database-block/utils/frame-loop.ts

close: https://github.com/toeverything/blocksuite/issues/4773
close: BS-245
table selection:
https://github.com/toeverything/blocksuite/assets/17165520/54440d5e-9df8-4f6b-a16c-6fff74841046
kanban drag:
https://github.com/toeverything/blocksuite/assets/17165520/50351a1e-edbf-442d-8c77-c9efe55af508

feat(database): supports auto-scroll during horizontal dragging

---

packages/playground/apps/default/utils/collection.ts

Close #6603
When setting up the room manually, collaboration between documents will be based on the broadcast-channel (unless the room id is valid). If you want to collaborate via websocket, click on the collaboration button in the top left corner (it will initialize a room and set a valid room id).

fix(playground): fallback to broadcast channel when failed to connect websocket

---

packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
packages/blocks/src/root-block/clipboard/middlewares/paste.ts
packages/playground/apps/starter/data/database.ts

fix(database): the first render should not have an empty YText

---

packages/blocks/src/database-block/table/components/column-header/vertical-indicator.ts

fix(database): table width adjustment is not correct under edgeless

---

packages/blocks/src/root-block/widgets/pie-menu/config.ts
packages/blocks/src/root-block/widgets/pie-menu/utils.ts

fix(edgeless): pie menu update shape overlay

---

packages/blocks/src/root-block/edgeless/utils/tool-overlay.ts

This pr is merged but not updated in the code base.. 👀https://github.com/toeverything/blocksuite/pull/6622

fix(edgeless): code not updated #6622

---

packages/blocks/src/surface-block/element-model/base.ts
packages/presets/src/__tests__/edgeless/surface-model.spec.ts

fix(edgeless): empty element like group or brush should have correct deserializedXYWH

---

packages/playground/vite.config.ts

Reverts toeverything/blocksuite#6654

revert: build: manual split chunks #6654

---

packages/blocks/src/attachment-block/embed.ts

fix(blocks): pdf preview

---

packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/root-block/edgeless/utils/hotkey-utils.ts
tests/edgeless/shortcut.spec.ts
tests/utils/actions/edgeless.ts

Close https://github.com/toeverything/blocksuite/issues/6585
https://github.com/toeverything/blocksuite/assets/123532141/b70d1c8a-ef22-47aa-941f-d4f8b8e50c42

feat(edgeless): shift + s to toggle between shapes

---

packages/blocks/src/root-block/widgets/format-bar/format-bar.ts

fix(edgeless): click on the whiteboard throw error when the format-bar is active

---

packages/blocks/src/root-block/edgeless/edgeless-root-service.ts

Related to #6652
Sorry, the previous PR did not correctly resolve the conflict.

fix(edgeless): remove redundant variables

---

packages/blocks/src/_common/components/ai-item/ai-sub-item-list.ts
packages/blocks/src/_common/components/ai-item/types.ts
packages/blocks/src/root-block/clipboard/index.ts
packages/blocks/src/root-block/index.ts
packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
packages/playground/apps/default/specs-examples/ai/actions.ts
packages/playground/apps/default/specs-examples/ai/request.ts
packages/playground/apps/default/specs-examples/ai/spec.ts
packages/playground/apps/default/specs-examples/index.ts
packages/presets/src/ai/ai.ts
packages/presets/src/ai/config/builder.ts
packages/presets/src/ai/copilot-client.ts
packages/presets/src/ai/entries/format-bar/config.ts
packages/presets/src/ai/entries/format-bar/format-bar-ai-button.ts
packages/presets/src/ai/entries/format-bar/setup-format-bar.ts
packages/presets/src/ai/entries/slash-menu/setup-slash-menu.ts
packages/presets/src/ai/entries/space/setup-space.ts
packages/presets/src/ai/index.ts
packages/presets/src/ai/types.ts
packages/presets/src/ai/utils.ts

refactored some parts so that affine could adapt the ai functions a bit easier.
Actions in format bar is far from complete.
Also some functions like "replace" seems not working properly.

feat(presets): ai actions in format bar

---

packages/blocks/src/surface-block/element-model/connector.ts

fix(edgeless): update path in local connector

---

packages/blocks/src/root-block/edgeless/components/text/edgeless-frame-title-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-group-title-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
packages/framework/block-std/src/view/utils/range-manager.ts

fix(edgeless): exclude canvas editor when sync range and selection

---

packages/framework/inline/src/__tests__/inline-editor.spec.ts
packages/framework/inline/src/components/v-line.ts

fix(inline): select line when triple click

---

packages/presets/src/ai/copilot-client.ts
packages/presets/src/ai/provider.ts

message in url should be encoded

fix(presets): ai message should be encoded

---

packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts

https://github.com/toeverything/blocksuite/assets/27926/a6672aee-d012-4a31-b433-d7b31084f24a

fix(presets): should stop propagation pointerdown events

---

packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
packages/presets/src/ai/entries/space/setup-space.ts

fix: should not trigger ai panel when composing

---

.github/CLA.md

agreement of contributor license

chore: update CLA

---

packages/playground/apps/default/specs-examples/ai/provider.ts
packages/playground/apps/default/specs-examples/ai/request.ts
packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/actions/text.ts
packages/presets/src/ai/copilot-client.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/messages/iframe.ts
packages/presets/src/fragments/copilot-panel/chat/logic.ts

feat(presets): ai images

---

packages/playground/apps/default/specs-examples/ai/request.ts
packages/presets/src/ai/actions/text.ts
packages/presets/src/ai/copilot-client.ts

Related to [#6523](https://github.com/toeverything/AFFiNE/pull/6523)

chore(presets): sync ai create message interface parameters

---

packages/presets/src/ai/chat-panel/chat-panel-input.ts

Close [AFF-819](https://linear.app/affine-design/issue/AFF-819/对话框用中文输入法打英文一个回车就寄了)

fix: check isComposing

---

packages/playground/apps/default/specs-examples/ai/copilot-client.ts
packages/playground/apps/default/specs-examples/ai/provider.ts
packages/playground/apps/default/specs-examples/ai/request.ts
packages/playground/package.json
packages/presets/package.json
packages/presets/src/ai/_common/icons.ts
packages/presets/src/ai/actions/handler.ts
packages/presets/src/ai/actions/index.ts
packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/chat-panel/chat-panel-input.ts
packages/presets/src/ai/chat-panel/chat-panel-messages.ts
packages/presets/src/ai/chat-panel/index.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/entries/format-bar/config.ts
packages/presets/src/ai/index.ts
packages/presets/src/ai/provider.ts
packages/presets/src/ai/utils/selection-utils.ts
pnpm-lock.yaml

- remove copilot client from presets
- chat panel use new chat/history related abstractions

refactor(presets): remove copilot client from presets

---

packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts

https://github.com/toeverything/blocksuite/assets/27926/415bd07f-02f1-42a5-8ffe-18cb6b446e0b

fix(blocks): ai panel position

---

packages/blocks/src/_common/adapters/index.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/framework/block-std/src/clipboard/index.ts
packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/messages/image.ts
packages/presets/src/ai/messages/index.ts
packages/presets/src/ai/utils/event-source.ts
packages/presets/src/ai/utils/image.ts

feat(presets): ai create an image

feat(presets): ai create an image

---

packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
packages/blocks/src/_common/adapters/notion-html.ts

fix(page): support notion plain table import

---

packages/blocks/src/_common/components/rich-text/hooks.ts
packages/blocks/src/_common/components/rich-text/markdown/block.ts
packages/framework/inline/src/__tests__/utils.ts
packages/framework/inline/src/components/v-line.ts
packages/framework/inline/src/services/event.ts
packages/framework/inline/src/services/range.ts
packages/framework/inline/src/utils/guard.ts

fix(inline): delete backward not works in the start of line in firefox

---

packages/playground/vite.config.ts

build: further split chunks

---

packages/blocks/src/bookmark-block/components/bookmark-card.ts

before:
https://github.com/toeverything/blocksuite/assets/50035259/0e2dea38-9d34-4bdc-b225-d85aef58a379

fix(blocks): do not log error when parse url hostname

---

packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
packages/blocks/src/root-block/edgeless/controllers/tools/copilot-tool.ts
packages/blocks/src/root-block/edgeless/services/selection-manager.ts
packages/framework/block-std/src/selection/variants/surface.ts

https://github.com/toeverything/blocksuite/assets/27926/6daf82f7-9612-45a9-8c42-e25e824bfb46

fix(edgeless): selection issue with copilot tool

---

packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts

Remove the deconstruct of filename.

fix(page): import markdown file title

---

packages/presets/src/ai/chat-panel/chat-panel-messages.ts

Fix https://linear.app/affine-design/issue/TOV-808/没有内容的历史记录列表展示很怪

fix: filter wrong data

---

packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
packages/presets/src/ai/chat-panel/actions/mindmap.ts
packages/presets/src/ai/chat-panel/chat-panel-messages.ts

Fix: https://linear.app/affine-design/issue/BS-270/插入的内容样式不适配
https://linear.app/affine-design/issue/AFF-821/chat-panel-插入不到最新-selection-的位置

fix(presets): insert and replace

---

packages/blocks/src/root-block/edgeless/controllers/tools/copilot-tool.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
packages/blocks/src/root-block/edgeless/services/tools-manager.ts
packages/blocks/src/root-block/edgeless/utils/viewport.ts
packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts
packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/zoom-toolbar.ts

Closes: AFF-868
https://github.com/toeverything/blocksuite/assets/27926/7a7f9edb-b9c0-4d0a-866b-0abe0b469ab8

fix(blocks): optimize copilot tool user experience

---

packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/messages/wrapper.ts
packages/presets/src/ai/utils/html.ts

fix(presets): should preprocess html

---

packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/chat-panel/actions/text.ts
packages/presets/src/ai/chat-panel/chat-panel-input.ts
packages/presets/src/ai/chat-panel/chat-panel-messages.ts
packages/presets/src/ai/chat-panel/index.ts

Fix:
https://linear.app/affine-design/issue/AFF-906/chat-panel-user-select-none-滥用
https://linear.app/affine-design/issue/AFF-882/chat-panel-response-核对

fix: chat bug

---

packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts

https://github.com/toeverything/blocksuite/assets/27926/e77e9d91-1ac0-497f-ad6a-25a2bcf983bc

feat(presets): create an image from user input

---

packages/blocks/src/__tests__/adapters/html.unit.spec.ts
packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
packages/blocks/src/_common/adapters/html.ts
packages/blocks/src/_common/adapters/markdown.ts

fix(page): add caption when exporting

---

packages/blocks/src/root-block/edgeless/components/utils.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/presets/src/ai/actions/edgeless-response.ts

Allow insertion of images with left-top as origin.

fix: image insertion position

---

packages/blocks/src/index.ts
packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/utils.ts
packages/blocks/src/surface-block/element-model/base.ts
packages/blocks/src/surface-block/element-model/mindmap.ts
packages/blocks/src/surface-block/index.ts
packages/blocks/src/surface-block/middlewares/group.ts
packages/blocks/src/surface-block/middlewares/mindmap.ts
packages/blocks/src/surface-block/mini-mindmap/surface-block.ts
packages/blocks/src/surface-block/surface-model.ts
packages/presets/src/__tests__/edgeless/group.spec.ts
packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/utils/edgeless.ts

- Fix group & mindmap issue
- Add expand action
- Naming

feat(edgeless): expand mindmap action

---

packages/blocks/src/attachment-block/attachment-service.ts
packages/blocks/src/attachment-block/utils.ts
packages/blocks/src/root-block/widgets/slash-menu/config.ts

https://github.com/toeverything/blocksuite/assets/99816898/c651449e-5de5-43d1-941e-8364873610e2

fix(blocks): video attachments can not be embed

---

packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/ai-panel.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/entries/edgeless/index.ts
packages/presets/src/ai/entries/format-bar/config.ts

revise action list based on AFF-946
added new actions:
- continueWriting
- writeStory

fix(presets): review action list items

---

packages/blocks/src/root-block/widgets/edgeless-copilot-panel/config.ts
packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/entries/edgeless/index.ts
packages/presets/src/ai/entries/format-bar/config.ts

fix(presets): review action list

---

packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts

https://github.com/toeverything/blocksuite/assets/27926/84f4583b-c2d0-439e-9d9e-5086dc377a6e

fix(blocks): should reset scroll top while retrying

---

packages/framework/store/src/transformer/job.ts

fix(store): fix export snapshot error

---

packages/blocks/src/surface-ref-block/portal/note.ts

- Fix the infinite rendering loop of surface-ref.
- The rendering height of note-block in surface-ref

fix(edgeless): surface-ref rendering

---

packages/blocks/src/_common/utils/button-popper.ts
packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
packages/blocks/src/root-block/edgeless/components/buttons/tool-icon-button.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
packages/blocks/src/surface-block/element-model/mindmap.ts
packages/framework/global/index.d.ts
packages/framework/store/src/store/store.ts
packages/playground/apps/default/utils/collection.ts
packages/playground/apps/starter/utils/collection.ts

fix(edgeless): refine mindmap
fix: focus mind map node using keyboard
fix: shape text editor
fix: toolbar button
fix: mindmap button state
fix: mindmap auto complete button title

fix(edgeless): refine mindmap

---

packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts

fix(blocks): line break in reference node

---

packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
packages/blocks/src/root-block/widgets/element-toolbar/add-frame-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/add-group-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/index.ts

Mindmap node cannot be added to other group.

fix(edgeless): prevent mindmap node from adding to other group

---

packages/playground/apps/default/specs-examples/ai/provider.ts
packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/utils/image.ts

deps: https://github.com/toeverything/AFFiNE/pull/6709 https://github.com/toeverything/AFFiNE/pull/6712

feat(presets): add seed to image generation

---

packages/presets/src/ai/entries/format-bar/format-bar-ai-button.ts

fix(presets): ai panel bottom padding

---

packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts

https://github.com/toeverything/blocksuite/assets/27926/23e76c48-421c-44ec-b44f-2e8795009570

fix(blocks): block portal should be `display: block` in firefox

---

packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/utils/viewport.ts

Closes: [BS-278](https://linear.app/affine-design/issue/BS-278/白板yuan素拖动，因为滚屏产生的位置移动没有被考虑)
https://github.com/toeverything/blocksuite/assets/27926/ad01e074-a8be-4bc0-b3a1-f2efd7c582e3

fix(edgeless): support for moving elements by scroll wheel

---

packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts

Closes: [TOV-829](https://linear.app/affine-design/issue/TOV-829/选中-frame-里的图后，图生图失败)
https://github.com/toeverything/blocksuite/assets/27926/82c0b00b-434e-4995-8071-57e7df5799dd

fix(blocks): missing elements when frames are selected

---

packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/utils/edgeless.ts

fix(presets): mindmap expand

---

packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/actions/handler.ts
packages/presets/src/ai/ai-panel.ts

To fix [AFF-1006](https://linear.app/affine-design/issue/AFF-1006/edgeless-ai-panel-执行-action-时需要更新-ai-panel-config)

fix: update ai panel config when handle action

---

packages/presets/src/ai/chat-panel/chat-panel-messages.ts
packages/presets/src/ai/chat-panel/index.ts
packages/presets/src/ai/provider.ts

fix(presets): add user change logic for chat panel

---

packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/messages/error.ts

To fix:
[TOV-835](https://linear.app/affine-design/issue/TOV-835/ai用量限制的话术拼写错误)
[TOV-841](https://linear.app/affine-design/issue/TOV-841/change-tone需要capitalized)

fix: ai error and change tone typo

---

packages/blocks/src/_common/components/ai-item/ai-item.ts
packages/blocks/src/_common/components/ai-item/styles.ts
packages/blocks/src/_common/components/ai-item/types.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/entries/format-bar/config.ts

feat(presets): add beta flags for some actions

---

packages/blocks/src/image-block/index.ts
packages/presets/src/ai/chat-panel/actions/actions-handle.ts
packages/presets/src/ai/chat-panel/chat-panel-messages.ts

fix(presets): insert below in chat
fix: export image-selection

fix(presets): fix insert below in chat

---

packages/framework/sync/src/awareness/impl/broadcast.ts
packages/playground/apps/default/utils/collection.ts
packages/playground/apps/starter/utils/collection.ts

fix(playground): generate random doc id for the starter entry

---

packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
tests/linked-page.spec.ts

Close BS-293
Close AFF-917
Close #6346

fix(blocks): reference node not update as expected

---

packages/blocks/src/_common/components/ai-item/styles.ts

fix(edgeless): ai panel text layout

---

packages/framework/block-std/src/event/dispatcher.ts
packages/presets/src/ai/messages/text.ts

fix(blocks): use passive listeners to improve wheel event

---

packages/blocks/src/root-block/edgeless/controllers/tools/copilot-tool.ts
packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts
packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts
packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/entries/format-bar/config.ts

1. Insert below the dotted box when no element is selected
2. Aligning the leftmost element
https://github.com/toeverything/blocksuite/assets/27926/0e3b3283-b040-49dc-ae69-b8a80f1d6890

fix(presets): optimize insertion position, left alignment

---

packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
packages/presets/src/ai/messages/error.ts

fix(presets): update error message

---

packages/blocks/src/embed-html-block/embed-html-block.ts

Closes: [TOV-843](https://linear.app/affine-design/issue/TOV-843/添加-esc-退出提醒，在-iframe-全屏时)
https://github.com/toeverything/blocksuite/assets/27926/e2a72011-e3b6-4a45-977f-7f0adb2ef227

feat(blocks): add esc tip when iframe is fullscreen

---

packages/blocks/src/embed-html-block/embed-html-block.ts
packages/blocks/src/embed-html-block/styles.ts

refactor(blocks): add fullscreen wrapper to iframe

---

packages/blocks/src/index.ts
packages/blocks/src/surface-block/index.ts
packages/blocks/src/surface-block/mini-mindmap/index.ts
packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/actions/types.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts
packages/presets/src/ai/messages/_common/generating-placeholder.ts
packages/presets/src/ai/messages/mindmap.ts

- Focus mind map after generation complete
- Expand mind map directly without showing the ai panel

fix(edgeless): focus on mindmap after generate

---

packages/blocks/src/paragraph-block/paragraph-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
packages/blocks/src/root-block/edgeless/frame-manager.ts
packages/blocks/src/root-block/root-model.ts
packages/blocks/src/root-block/root-service.ts
packages/framework/block-std/src/view/element/block-element.ts
packages/presets/src/editors/edgeless-editor.ts
packages/presets/src/fragments/doc-title/doc-title.ts

Fix memory leak when switching between two modes

fix: memory leak

---

packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
packages/blocks/src/root-block/widgets/ai-panel/type.ts
packages/presets/src/ai/actions/doc-handler.ts
packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/actions/edgeless-response.ts
packages/presets/src/ai/ai-panel.ts
packages/presets/src/ai/entries/edgeless/panel-config.ts
packages/presets/src/ai/messages/mindmap.ts
packages/presets/src/ai/messages/slides-renderer.ts
packages/presets/src/ai/messages/wrapper.ts

[AFF-966](https://linear.app/affine-design/issue/AFF-966/inline，chat-ai-的报错改动)

feat: update ai panel error state

---

packages/blocks/src/_common/components/rich-text/rich-text.ts
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/data-view-block/columns/rich-text/cell-renderer.ts
packages/blocks/src/database-block/columns/rich-text/cell-renderer.ts
packages/blocks/src/database-block/columns/title/text.ts
packages/blocks/src/database-block/components/title/index.ts
packages/blocks/src/list-block/list-block.ts
packages/blocks/src/paragraph-block/paragraph-block.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-frame-title-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-group-title-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
packages/presets/src/fragments/doc-title/doc-title.ts
packages/presets/src/fragments/frame-panel/card/frame-card-title-editor.ts

Close #6773
before:
https://github.com/toeverything/blocksuite/assets/50035259/e8197af0-898d-464b-8460-c7a425d3371d
after:
https://github.com/toeverything/blocksuite/assets/50035259/837a3f7e-5b8c-4bc7-be59-29d383e7ae8c

fix(blocks): support config the vertical scroll container of rich-text

---

packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts

Likes the `generate an image` action, it also allows user input.

fix(presets): improve make it real action

---

packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-element.ts

Close #6984
https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent#touchend

fix(blocks): fix undefined of touchend

---

packages/blocks/src/__tests__/adapters/html.unit.spec.ts
packages/blocks/src/_common/adapters/html.ts

fix(page): unknown code language in html adapter

---

packages/blocks/src/_common/utils/button-popper.ts
packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
packages/blocks/src/root-block/widgets/ai-panel/type.ts
packages/presets/src/ai/ai-panel.ts
packages/presets/src/ai/ai.ts
packages/presets/src/ai/entries/format-bar/format-bar-ai-button.ts

Close AFF-1024
- Improve ai-pannel position and size of block element in edgeless mode
Before:
After:

fix(edgeless): improve ai-panel position

---

packages/blocks/src/_common/inline/presets/affine-inline-specs.ts
packages/blocks/src/_common/inline/presets/nodes/affine-text.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
packages/blocks/src/code-block/affine-code-line.ts
packages/framework/inline/src/components/v-text.ts
packages/framework/inline/src/utils/attribute-renderer.ts
packages/playground/examples/inline/test-page.ts

Close #6986
https://github.com/toeverything/blocksuite/assets/50035259/a425bc24-b87e-45c3-90e9-cf02d339c61f

fix(blocks): support overlapping of inline styles

---

packages/blocks/src/embed-figma-block/embed-figma-model.ts

regex from https://www.figma.com/developers/embed
https://github.com/toeverything/blocksuite/assets/99816898/5eccf6f7-2093-435f-85c6-17db2ea7acd9

fix(blocks): update figma url regex

---

packages/blocks/src/_common/utils/button-popper.ts

fix(blocks): firefox dose not support ComputedStyleMap

---

packages/blocks/src/_common/components/file-drop-manager.ts
packages/blocks/src/attachment-block/attachment-service.ts
packages/blocks/src/image-block/image-service.ts
packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/utils/viewport.ts

https://github.com/toeverything/blocksuite/assets/27926/522bbee8-439e-4cdb-b2e3-04d341117e10

fix(blocks): coordinate conversion should consider the offset of the viewport

---

packages/blocks/src/root-block/edgeless/controllers/clipboard.ts

fix(edgeless): fix caption missing when paste image in edgeless mode

---

packages/presets/src/ai/messages/_common/generating-placeholder.ts

chore(presets): replace loading icon of ai generation

---

packages/blocks/src/_common/components/ai-item/styles.ts
packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts

To fix [AFF-1060](https://linear.app/affine-design/issue/AFF-1060/action-panel-宽度)

fix: ai action panel scroll bar and width

---

packages/blocks/src/index.ts
packages/blocks/src/root-block/root-service.ts
packages/blocks/src/surface-block/consts.ts
packages/blocks/src/surface-block/index.ts

refactor(edgeless): use public cdn for font by default

---

packages/blocks/src/root-block/widgets/element-toolbar/add-frame-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/add-group-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-image-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-text-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/index.ts

refactor(blocks): buttons on element toolbar

---

packages/presets/src/ai/ai.ts

fix(presets): missing of ai space entry in edgeless

---

packages/presets/src/ai/actions/doc-handler.ts
packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/ai-panel.ts
packages/presets/src/ai/chat-panel/actions/action-wrapper.ts
packages/presets/src/ai/chat-panel/actions/chat-text.ts
packages/presets/src/ai/chat-panel/actions/text.ts
packages/presets/src/ai/messages/text.ts

[BS-308](https://linear.app/affine-design/issue/BS-308/chat-ai-heading-1-6-的大小问题)

feat: support custom heading size with text renderer

---

packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
packages/blocks/src/root-block/widgets/slash-menu/styles.ts

Close AFF-1052
Fix category conatiner of slash menu can not scroll.

fix(blocks): slash category menu can not scroll

---

packages/blocks/package.json
packages/presets/package.json
pnpm-lock.yaml

To remove button's inner shadow

chore: bump theme version

---

packages/blocks/src/database-block/data-view/common/detail/field.ts

fix(database): number cell alignment

---

packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts

- impl toggle with css only
- adjust transition duration
- adjust trigger area

chore(edgeless): toggle presentation toolbar with css instead

---

packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
packages/blocks/src/root-block/edgeless/components/toolbar/frame/frame-order-button.ts

fix(edgeless): don't hide presentation toolbar if frame/setting menu opened

---

packages/framework/sync/src/blob/impl/indexeddb.ts
packages/playground/apps/_common/components/quick-edgeless-menu.ts

https://github.com/toeverything/blocksuite/assets/27926/36582b96-6be0-4acf-818e-80fe1a8e7299
https://github.com/toeverything/blocksuite/assets/27926/8b12acc7-0d6a-4cf1-ab38-423481c82b8f

fix(sync): should await Blob arrayBuffer

---

packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts

fix(blocks): delete redundant divier on embed card buttons

---

packages/blocks/src/database-block/data-view/view/presets/table/controller/drag-to-fill.ts

fix(database): drag to fill icon moving with cursor

---

packages/blocks/src/root-block/clipboard/adapter.ts
packages/blocks/src/root-block/clipboard/utils.ts
packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts

This closes [BS-323](https://linear.app/affine-design/issue/BS-323).

feat(edgeless): copy and paste blobs in edgeless

---

packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts

https://github.com/toeverything/blocksuite/assets/27926/199954d0-cfdb-432a-bc29-9ae76fa8508a
https://github.com/toeverything/blocksuite/assets/27926/495528c7-b224-4949-83c1-f7249ccf56c4

fix(blocks): should update layout icon when changing mindmap layout

---

packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts

Error when throw if ai panel is destroyed before hiding

fix(blocks): should clear auto update for aipanel on disconnect

---

packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts

[AFF-1170](https://linear.app/affine-design/issue/AFF-1170/退格键无法关闭ai输入框)

feat: support delete to hide ai input when no input content

---

packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts

fix(blocks): fix typo

---

packages/blocks/src/root-block/widgets/format-bar/format-bar.ts

Duplicates https://github.com/toeverything/blocksuite/pull/1678
Closes https://github.com/toeverything/blocksuite/issues/7184
https://github.com/toeverything/blocksuite/assets/26658144/3cc9c5ce-581c-4f6d-b427-ce9e88b22b49

fix(blocks): prevent default on pointer down with format bar

---

packages/presets/src/ai/chat-panel/actions/copy-more.ts
packages/presets/src/ai/chat-panel/chat-panel-messages.ts

Fix https://linear.app/affine-design/issue/BS-414/ai-报错的时候，应该提供-retry-按钮

fix(presets): add retry when ai error

---

packages/blocks/src/_common/components/button.ts

related https://github.com/toeverything/blocksuite/pull/7132

fix(blocks): icon button alignment

---

packages/blocks/src/_common/transformers/middlewares.ts

This closes https://linear.app/affine-design/issue/BS-289.

fix(edgeless): replace id when surface ref import

---

packages/blocks/src/embed-linked-doc-block/commands/insert-link-by-quick-search.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts

Closes: [BS-349](https://linear.app/affine-design/issue/BS-349/快捷键插入-linked-doc)

feat: at new linked doc with @

---

packages/presets/src/ai/actions/doc-handler.ts

fix(presets): no context in inline ai

---

packages/blocks/src/_common/utils/render-linked-doc.ts
packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
packages/framework/store/package.json
packages/framework/store/src/__tests__/doc.unit.spec.ts
packages/framework/store/src/store/collection.ts
packages/framework/store/src/store/doc/block-collection.ts
packages/framework/store/src/store/doc/doc.ts
packages/presets/src/ai/messages/text.ts
pnpm-lock.yaml

Closes: [BS-412](https://linear.app/affine-design/issue/BS-412/不共享的readonly模式支持)

feat: local readonly for doc

---

packages/blocks/src/root-block/edgeless/components/panel/scale-panel.ts
packages/blocks/src/root-block/edgeless/components/panel/size-panel.ts
packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
packages/blocks/src/root-block/widgets/element-toolbar/index.ts
packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
packages/blocks/src/surface-block/managers/connector-manager.ts
tests/edgeless/connector.spec.ts
tests/utils/actions/edgeless.ts

Closes: [BS-421](https://linear.app/affine-design/issue/BS-421/添加-quick-connect-功能)
* Add `quick connect` button on the element toolbar

feat(blocks): add quick connect button to element toolbar

---

packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts

Close BS-396, AFF-1028
-  The positioning reference element of `ai-panel` will ignore the child blocks.
- Add the `data-state` attribute to the `affine-ai-panel-widget`so that we can write CSS rules based on its state in AFFiNE side.
- Fix ai-panel position edge case in edgeless mode, like

fix(presets): ai panel position issues

---

packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts

https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt

feat(blocks): add center peek button to embed card toolbar

---

packages/blocks/src/root-block/edgeless/utils/viewport.ts
packages/blocks/src/surface-block/canvas-renderer/renderer.ts
packages/blocks/src/surface-block/managers/connector-manager.ts
tests/edgeless/connector.spec.ts

Closes: [BS-185](https://linear.app/affine-design/issue/BS-185/connector-在调整窗口大小时会错位)

fix(blocks): canvas flickering issue when resizing window

---

packages/blocks/src/root-block/clipboard/middlewares/paste.ts
packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
packages/blocks/src/root-block/root-service.ts

two cases:
- paste internal link into doc as page reference
- paste internal link into edgeless as linked doc card

feat(blocks): paste affine link as linked ref

---

packages/blocks/src/root-block/commands/text-crud/delete-text.ts
tests/hotkey.spec.ts

This closes https://linear.app/affine-design/issue/BS-315.

fix(blocks): merge blocks when cut

---

packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts

feat: readonly synced doc

---

packages/blocks/src/__tests__/adapters/html.unit.spec.ts
packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
packages/blocks/src/__tests__/utils/create-job.ts
packages/blocks/src/_common/adapters/mix-text.ts
packages/blocks/src/_common/adapters/notion-html.ts
packages/blocks/src/_common/transformers/html.ts
packages/blocks/src/_common/transformers/markdown.ts
packages/blocks/src/code-block/clipboard/index.ts
packages/blocks/src/root-block/clipboard/index.ts
packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.spec.ts
packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
packages/framework/block-std/src/clipboard/index.ts
packages/framework/store/src/adapter/base.ts
packages/playground/apps/_common/components/debug-menu.ts
packages/presets/src/ai/_common/markdown-utils.ts
packages/presets/src/ai/messages/mindmap.ts
packages/presets/src/ai/utils/markdown-utils.ts
packages/presets/src/fragments/copilot-panel/chat/logic.ts
packages/presets/src/fragments/copilot-panel/utils/markdown-utils.ts

Closes: [BS-42](https://linear.app/affine-design/issue/BS-42/use-job-in-adapter)

feat: add job in adapter

---

packages/blocks/src/_common/components/filterable-list/index.ts
packages/blocks/src/_common/components/filterable-list/styles.ts
packages/blocks/src/root-block/widgets/code-language-list/index.ts
tests/code.spec.ts

fix(blocks): language list z index

---

packages/blocks/src/_common/components/filterable-list/index.ts
packages/blocks/src/_common/components/hover/controller.ts
packages/blocks/src/_common/components/tooltip/tooltip.ts
tests/code.spec.ts

related to https://github.com/toeverything/blocksuite/pull/7245
https://github.com/toeverything/blocksuite/assets/123532141/593769b5-8a9d-4003-bdae-e071ed728f33

refactor(blocks): hover controller

---

packages/blocks/src/root-block/page/page-root-block.ts
tests/image.spec.ts
tests/selection/block.spec.ts

fix(blocks): add extra height to page mode

---

packages/blocks/src/root-block/edgeless/components/block-portal/frame/edgeless-frame.ts
packages/presets/src/__tests__/edgeless/frame.spec.ts

Fix [BS-437](https://linear.app/affine-design/issue/BS-437/frame-标题缩放时错位)

fix: nested frame title

---

packages/blocks/src/root-block/widgets/slash-menu/index.ts

Close [BS-502](https://linear.app/affine-design/issue/BS-502/%E8%BF%9E%E7%BB%AD%E8%BE%93%E5%85%A5-%E4%BC%9A%E6%9C%89%E6%80%A7%E8%83%BD%E9%97%AE%E9%A2%98)
https://github.com/toeverything/blocksuite/assets/20479050/45d3863a-2cf4-4ab2-b30b-82aa8c625a77
https://github.com/toeverything/blocksuite/assets/20479050/3d31d5cc-e080-4b89-8581-a340caa9ee20

fix(blocks): debouce slash menu popover

---

packages/presets/src/ai/chat-panel/chat-panel-input.ts

Closes: [BS-416](https://linear.app/affine-design/issue/BS-416/ai-chat-输入框最大高度和样式问题)
https://github.com/toeverything/blocksuite/assets/27926/c1e3d688-7719-492c-88be-0521872d3752

fix(presets): chat input max-height

---

packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/_common/embed-block-helper/helper.ts
packages/blocks/src/_common/utils/helper.ts
packages/blocks/src/_common/utils/index.ts
packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/bookmark-block/bookmark-service.ts
packages/blocks/src/bookmark-block/utils.ts
packages/blocks/src/embed-github-block/embed-github-block.ts
packages/blocks/src/embed-github-block/embed-github-service.ts
packages/blocks/src/embed-github-block/utils.ts
packages/blocks/src/embed-loom-block/embed-loom-block.ts
packages/blocks/src/embed-loom-block/embed-loom-service.ts
packages/blocks/src/embed-loom-block/utils.ts
packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
packages/blocks/src/embed-youtube-block/embed-youtube-service.ts
packages/blocks/src/embed-youtube-block/utils.ts

Close [BS-313](https://linear.app/affine-design/issue/BS-313/%E5%88%9B%E5%BB%BA-bookmark%EF%BC%8C%E5%9C%A8%E5%8A%A0%E8%BD%BD%E6%97%B6%EF%BC%8Cundodelete-%E6%8A%A5%E9%94%99)

fix(blocks): bookmark block error on undo or delete while loading

---

packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
tests/slash-menu.spec.ts

[BS-516](https://linear.app/affine-design/issue/BS-516/unexpected-hover-style-in-slash-menu)

fix(blocks): slash menu unexpected hover style

---

packages/blocks/src/_common/components/filterable-list/index.ts

[BS-518](https://linear.app/affine-design/issue/BS-518/filterable-list-unexpected-hover-style)

fix(blocks): filterable list unexpected hover style

---

packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts

fix(edgeless): align panel not work

---

packages/blocks/src/_common/components/peekable.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts

fix(blocks): affine-embed-synced-doc-block peek on dblclick

---

packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
packages/blocks/src/root-block/widgets/edgeless-auto-connect/edgeless-auto-connect.ts
packages/framework/block-std/src/view/element/widget-element.ts

Rewrite auto-connect component as a widget

refactor(edgeless): rewrite auto-connect component as a widget

---

packages/blocks/src/paragraph-block/styles.ts

👉 [BS-338](https://linear.app/affine-design/issue/BS-338/修改-heading-样式)

style(page): adjust heading font-weight and letter-spacing

---

packages/blocks/src/root-block/edgeless/components/panel/card-style-panel.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts

Closes: [BS-520](https://linear.app/affine-design/issue/BS-520/切换-attachment-的-card-style-时，toolbar-状态没更新)

fix(blocks): should update card style on attachment toolbar

---

packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts

Closes: [BS-512](https://linear.app/affine-design/issue/BS-512/%E6%96%B0%E7%9A%84-edgeless-text-%E9%87%8C%E8%BE%93%E5%85%A5-%E4%B8%8D%E5%BA%94%E8%AF%A5%E6%BF%80%E6%B4%BB-%E2%8C%98-k-%E5%BC%B9%E7%AA%97)

chore: fix @ shortcut in edgeless text

---

packages/framework/inline/src/services/event.ts
packages/framework/inline/src/utils/transform-input.ts

This closes #6039, closes https://github.com/toeverything/AFFiNE/issues/6935.

fix(inline): spell checker

---

packages/blocks/src/root-block/clipboard/middlewares/paste.ts

Closes: [BS-491](https://linear.app/affine-design/issue/BS-491/page-mode-%E7%B2%98%E8%B4%B4%E9%93%BE%E6%8E%A5%E8%AF%86%E5%88%AB%E5%90%8E%EF%BC%8C%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%8C%89%E6%92%A4%E9%94%80%E5%BA%94%E6%81%A2%E5%A4%8D%E6%99%AE%E9%80%9A%E6%96%87%E6%9C%AC%EF%BC%8C%E7%AC%AC%E4%BA%8C%E6%AC%A1%E6%8C%89%E6%92%A4%E9%94%80%E5%9C%A8%E6%92%A4%E9%94%80%E7%B2%98%E8%B4%B4)

fix: linked doc paste can undo as normal link text

---

packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts

Closes: [BS-522](https://linear.app/affine-design/issue/BS-522/element-toolbar-上-more-menu-有多余的-dividers)

fix(blocks): remove redundant dividers on more button

---

packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/assets.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-menu.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mixins/tool.mixin.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
packages/blocks/src/root-block/edgeless/components/toolbar/tools.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/surface-block/element-model/connector.ts

closes [AFF-1250](https://linear.app/affine-design/issue/AFF-1250/611-ui-issues)

fix(edgeless): adjust edgeless toolbar ui, add tooltips, replace icons

---

packages/blocks/src/_common/components/menu/menu.ts

[BS-532](https://linear.app/affine-design/issue/BS-532/database-error-on-menu-search)
https://stackoverflow.com/questions/64873647/dom-error-while-using-classlist-add-method

fix(database): error on menu search

---

packages/blocks/src/attachment-block/attachment-service.ts
packages/blocks/src/embed-linked-doc-block/commands/insert-link-by-quick-search.ts
packages/blocks/src/image-block/image-service.ts
packages/blocks/src/root-block/edgeless/components/toolbar/link/link-tool-button.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
packages/blocks/src/root-block/edgeless/controllers/tools/brush-tool.ts
packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
packages/blocks/src/root-block/edgeless/controllers/tools/frame-tool.ts
packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
packages/blocks/src/root-block/edgeless/controllers/tools/text-tool.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
packages/blocks/src/root-block/index.ts
packages/blocks/src/root-block/root-service.ts
packages/blocks/src/root-block/widgets/element-toolbar/add-frame-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
packages/playground/apps/_common/mock-services.ts
packages/presets/src/ai/actions/edgeless-response.ts

Add telemetry service for tracking events.
fix AFF-1154
remaining issues
- note object created by AI is not being tracked

feat(blocks): add element creation events for edgeless

---

packages/blocks/src/data-view-block/data-view-block.ts
packages/blocks/src/data-view-block/view-source.ts
packages/blocks/src/database-block/data-view/common/view-source.ts
packages/blocks/src/database-block/data-view/data-view.ts
packages/blocks/src/database-block/data-view/view/data-view-manager.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/database-block/view-source.ts
packages/framework/global/src/utils/slot.ts

fix(database): view not found

---

packages/blocks/src/root-block/root-service.ts

- Change edgeless editor viewport to 100% before inserting card
- Select the card after adding it to edgeless editor
- Replace `_getMode` api with `docModeService.getMode`

fix: insert card viewport and selection in edgeless editor

---

packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
packages/blocks/src/surface-block/managers/connector-manager.ts

https://github.com/toeverything/blocksuite/assets/27926/fedd6cb3-1a76-4f56-b0df-22502ceefdad
https://github.com/toeverything/blocksuite/assets/27926/00f072e4-7503-4674-94d5-bd08a42f9925

fix(blocks): source position when creating a quick connection on a triangle

---

packages/blocks/src/edgeless-text/edgeless-text-model.ts
packages/blocks/src/edgeless-text/index.ts
packages/blocks/src/index.ts
packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts
packages/presets/src/ai/actions/edgeless-handler.ts
packages/presets/src/ai/entries/edgeless/actions-config.ts

[BS-551](https://linear.app/affine-design/issue/BS-551/新的-edgeless-text-不支持作为-ai-输入了)

feat: edgeless text as ai action input

---

packages/blocks/src/surface-block/element-model/utils/shape/ellipse.ts
packages/blocks/src/surface-block/utils/math-utils.ts

Closes: [BS-422](https://linear.app/affine-design/issue/BS-422/优化-connector-连接-ellipse，寻找最近的点)
https://github.com/toeverything/blocksuite/assets/27926/fd60a45c-71f6-4dba-9b77-b5fd033017c8

fix(blocks): find the closest point on ellipse

---

packages/blocks/src/database-block/data-source.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts

fix(database): duplicate column behavior

---

packages/presets/src/ai/actions/edgeless-handler.ts

[BS-525](https://linear.app/affine-design/issue/BS-525/edgeless-text-toolbar-上-ask-ai-的按钮的功能应该是-向-ai-询问这个-edgeless-text)

fix: edgeless text should support ai text actions

---

packages/blocks/src/root-block/clipboard/middlewares/paste.ts
packages/blocks/src/root-block/edgeless/components/toolbar/link/link-dense-menu.ts
packages/blocks/src/root-block/edgeless/components/toolbar/link/link-tool-button.ts
packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/root-block/root-service.ts
packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
packages/blocks/src/root-block/widgets/format-bar/config.ts
packages/blocks/src/root-block/widgets/linked-doc/config.ts

chore(blocks): linked doc created events

---

packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/overlay-factory.ts
packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/types.ts
packages/blocks/src/root-block/edgeless/components/toolbar/eraser/eraser-tool-button.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mixins/toolbar-button-with-menu.mixin.ts
packages/blocks/src/root-block/edgeless/components/toolbar/presentation-toolbar.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts
packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/framework/block-std/src/view/element/block-element.ts
tests/utils/actions/edgeless.ts

feat(edgeless): drag to add edgeless template

---

packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts

fix(edgeless): drag to create custom-size shape should be disabled when dragging a shape
fix(edgeless): replace toolbar shadow with theme variable

fix(edgeless): toolbar related ui issues

---

packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/overlay-factory.ts
packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/types.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts
packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
tests/utils/actions/edgeless.ts

- add shape with shortcut "S"
- if press while dragging, change shape

feat(edgeless): add shape shortcut in toolbar

---

packages/presets/package.json

Fix ai preset export path error in packages.json

fix(presets): ai export path error

---

packages/blocks/src/surface-block/managers/connector-manager.ts
tests/edgeless/clipboard.spec.ts
tests/edgeless/connector.spec.ts

Closes: [BS-424](https://linear.app/affine-design/issue/BS-424/connector-endpoint-吸附优化)
https://github.com/toeverything/blocksuite/assets/27926/9fd5594f-fcca-46b8-af4f-464c098145c3

fix(blocks): auto snap to neighboring point

---

packages/blocks/src/bookmark-block/styles.ts
packages/blocks/src/edgeless-text/edgeless-text-block.ts
packages/blocks/src/edgeless-text/edgeless-text-service.ts
packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts
packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts

https://github.com/toeverything/blocksuite/assets/50035259/fff6bc1e-2eb5-4f0e-bb13-2cfbe311829c

feat(edgeless): add min width for link card in edgeless text

---

packages/blocks/src/_common/components/doc-mode-service.ts
packages/playground/apps/_common/mock-services.ts

https://github.com/toeverything/blocksuite/assets/50035259/2b12cb00-4b0d-4b89-a255-34c65948aea8

fix(playground): can not change mode

---

packages/playground/apps/default/utils/collection.ts
packages/playground/apps/starter/utils/collection.ts

fix(playground): flags from params need to be converted

---

packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts

fix(edgeless): drag to create custom-size shape should be disabled when dragging a shape
fix(edgeless): replace toolbar shadow with theme variable

fix(edgeless): resolve the conflict of drag-and-drop to create shapes, modify toolbar shadow

---

packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
tests/edgeless/note.spec.ts

https://github.com/toeverything/blocksuite/assets/50035259/1d160198-2a71-485e-95eb-6cfdad90bb71

fix(edgeless): need to delete first block in note when it has children

---

packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/index.ts
packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
packages/blocks/src/surface-block/element-model/mindmap.ts
packages/blocks/src/surface-block/element-model/utils/mindmap/layout.ts

Mind map `balanced` layout should render the nodes in clockwise direction.

fix: mind map balance layout

---

packages/blocks/src/_common/components/peekable.ts
packages/playground/apps/default/utils/editor.ts
packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts

feat(blocks): peek view api enhancements

---

packages/blocks/src/_common/embed-block-helper/helper.ts
packages/blocks/src/_common/embed-block-helper/types.ts
packages/blocks/src/embed-figma-block/embed-figma-schema.ts
packages/blocks/src/embed-figma-block/embed-figma-spec.ts
packages/blocks/src/embed-github-block/embed-github-schema.ts
packages/blocks/src/embed-github-block/embed-github-spec.ts
packages/blocks/src/embed-html-block/embed-html-schema.ts
packages/blocks/src/embed-html-block/embed-html-spec.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-schema.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-spec.ts
packages/blocks/src/embed-loom-block/embed-loom-schema.ts
packages/blocks/src/embed-loom-block/embed-loom-spec.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-schema.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-spec.ts
packages/blocks/src/embed-youtube-block/embed-youtube-schema.ts
packages/blocks/src/embed-youtube-block/embed-youtube-spec.ts
packages/blocks/src/index.ts
packages/blocks/src/schemas.ts

fix: split embed view and schema for web worker compatibility

---

packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
packages/blocks/src/root-block/edgeless/utils/viewport.ts
packages/blocks/src/surface-block/surface-block.ts

Fix embed edgeless doc does not render things.
Related [BS-562](https://linear.app/affine-design/issue/BS-562/edgeless-%E7%9A%84-embed-veiw-%E6%9C%AA%E6%B8%B2%E6%9F%93%E5%86%85%E5%AE%B9%E6%88%96%E8%80%85%E6%B8%B2%E6%9F%93%E4%B8%8D%E5%85%A8)

fix: embed edgeless block resizing

---

packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
tests/edgeless/connector.spec.ts
tests/utils/actions/edgeless.ts

Closes: [BS-640](https://linear.app/affine-design/issue/BS-640/快捷键无法调用曲线)

fix(blocks): default mode in connector tool

---

packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts

chore(edgeless): add embedSyncedDoc to splitElements function

---

packages/blocks/src/_common/utils/scroll-container.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/column-header.ts

fix: firefox does not support element.computedStyleMap

---

packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/bookmark-block/styles.ts

fix(blocks): bookmark should not has min-width when it is in surface

---

packages/blocks/src/surface-block/element-model/mindmap.ts
packages/blocks/src/surface-block/surface-model.ts

Fixes [BS-673](https://linear.app/affine-design/issue/BS-673/%E9%80%9A%E8%BF%87-affine-ai-%E5%88%9B%E5%BB%BA%E7%9A%84%E6%80%9D%E7%BB%B4%E5%AF%BC%E5%9B%BE%E5%88%9D%E5%A7%8B%E5%B1%95%E7%A4%BA%E5%BC%82%E5%B8%B8)

fix(edgeless): legacy mind map rendering

---

packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts

Related to [BS-639](https://linear.app/affine-design/issue/BS-639)

fix(edgeless): edgeless toolbar disappear when hide toolbar in presentation setting

---

packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts

Fixes [BS-658](https://linear.app/affine-design/issue/BS-658/edgeless-mode-下标记为隐藏不显示的内容，在-embed-后显示在了文档中)

fix: should not render edgeless only block in embed view

---

packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/index.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/mindmap.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/diamond.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/ellipse.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/rect.ts
packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/triangle.ts
packages/blocks/src/surface-block/canvas-renderer/renderer.ts
packages/blocks/src/surface-block/rough/canvas.ts

Fixes [BS-647](https://linear.app/affine-design/issue/BS-647/%E8%80%81%E6%95%B0%E6%8D%AE%E7%9A%84-shape-%E5%9C%A8-beta-canary-%E4%B8%8A-scribbled-%E7%9A%84%E5%BD%A2%E7%8A%B6-%E4%B8%8D%E7%94%9F%E6%95%88)

fix: scribbled style shape rendering

---

packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
packages/blocks/src/edgeless-text/edgeless-text-model.ts
packages/blocks/src/note-block/note-model.ts

fix(edgeless): disable sync doc in edgeless text

---

packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
packages/presets/src/__tests__/edgeless/layer.spec.ts

Fixes [BS-685](https://linear.app/affine-design/issue/BS-685/edgeless-copy-paste-error)

fix(edgeless): edgeless portal does not render new added blocks

---

packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
packages/blocks/src/root-block/widgets/slash-menu/utils.ts

https://github.com/toeverything/blocksuite/pull/7431#discussion_r1654673642

refactor(blocks): clean code in reference popup

---

packages/blocks/src/divider-block/divider-block.ts
packages/blocks/src/root-block/keyboard/keyboard-manager.ts
packages/framework/block-std/src/view/utils/range-binding.ts

Close BS-652
https://github.com/toeverything/blocksuite/assets/50035259/3e663b76-49bb-4c06-b50f-5bac382dc3e3

fix: edgeless selection may disappear when typing on edgeless text

---

packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts

fix(edgeless): need to clear selection when focus out in edgeless text

---

packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup-more-menu-popup.ts

Close [BS-506](https://linear.app/affine-design/issue/BS-506/dropdown-menu-ui-bug)

fix(blocks): reference more menu ui issues

---

packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts

Close [BS-692](https://linear.app/affine-design/issue/BS-692/html-toolbar-responsive-design)

refactor(blocks): fullscreen html toolbar responsive design

---

packages/blocks/src/root-block/widgets/linked-doc/index.ts
packages/framework/store/src/store/store.ts
packages/playground/apps/default/utils/collection.ts
tests/edgeless/text.spec.ts

fix(edgeless): should not trigger linked doc widget in canvas text

---

packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-menu.ts

before:
https://github.com/toeverything/blocksuite/assets/50035259/eff12f79-c2b0-48e1-b102-77e1587c2f17

fix(edgeless): drag text from toolbar should not change edgeless tool

---

packages/blocks/src/database-block/data-view/common/data-stats.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-stats-cell.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-stats.ts
packages/blocks/src/database-block/data-view/view/presets/table/group.ts
packages/blocks/src/database-block/data-view/view/presets/table/stat-ops.ts

Close [BS-290](https://linear.app/affine-design/issue/BS-290/database-block-%E7%BB%9F%E8%AE%A1%E5%9C%A8-group-%E4%B8%8B%E6%9C%89%E9%97%AE%E9%A2%98)

fix(database): statistics wrong calculation under groups

---

packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts
packages/framework/inline/src/components/v-text.ts

Close BS-730
Close BS-722
Before:
https://github.com/toeverything/blocksuite/assets/50035259/c5a59ecf-3534-451b-8206-c86b750ccb1f

fix(edgeless): edgeless text shake when dragging

---

packages/blocks/src/index.ts
packages/blocks/src/surface-block/element-model/mindmap.ts
packages/blocks/src/surface-block/index.ts
packages/presets/src/__tests__/edgeless/group.spec.ts

New created mindmap should layout automatically.

fix(edgeless): new created mind map should layout automatically

---

packages/framework/block-std/src/view/utils/range-binding.ts
tests/selection/native.spec.ts

Closes: [BS-460](https://linear.app/affine-design/issue/BS-460/%E7%A9%BA%E7%99%BD%E7%82%B9%E5%87%BB%E5%90%8E%E5%94%A4%E8%B5%B7-toolbar%EF%BC%9A%E7%A9%BA%E7%9A%84%E5%9C%B0%E6%96%B9%E7%82%B9%E5%87%BB%E5%90%8E%E4%B8%8D%E5%BA%94%E8%AF%A5%E5%87%BA%E7%8E%B0-toolbar)

fix: filter invalid range in range binding

---

packages/playground/apps/starter/main.ts
packages/playground/apps/starter/utils/collection.ts

fix(playground): starter page collaboration sometimes fails

---

packages/playground/examples/provider/main.ts
packages/playground/examples/store/main.ts

fix(examples): missing meta initialization

---

packages/blocks/src/_common/components/toolbar/menu-button.ts
packages/blocks/src/_common/components/toolbar/toolbar.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
packages/blocks/src/_common/styles.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts

Closes: [BS-723](https://linear.app/affine-design/issue/BS-723/create-link)

chore(blocks): refine link creation panel

---

packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
tests/link.spec.ts

Closes: [BS-724](https://linear.app/affine-design/issue/BS-724/edit-link)

chore(blocks): refine link editing panel

---

packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/attachment-block/components/rename-model.ts
packages/blocks/src/attachment-block/components/styles.ts

Closes: [BS-778](https://linear.app/affine-design/issue/BS-778/attachment-editing-panel)

chore(blocks): refine attachment editing panel

---

packages/blocks/src/_common/components/embed-card/modal/embed-card-caption-edit-modal.ts
packages/blocks/src/_common/components/embed-card/modal/embed-card-create-modal.ts
packages/blocks/src/_common/components/embed-card/modal/embed-card-edit-modal.ts
packages/blocks/src/_common/components/embed-card/modal/styles.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
packages/blocks/src/_common/styles.ts
packages/blocks/src/attachment-block/components/styles.ts

Closes: [BS-771](https://linear.app/affine-design/issue/BS-771/linked-web-card-view-模式下的-editing-panel) [BS-786](https://linear.app/affine-design/issue/BS-786/通过-slash-menu-创建-link-时，弹出的面板)

chore(blocks): refine linked web editing panel

---

packages/framework/inline/src/components/v-text.ts

fix(inline): word wrap

---

packages/blocks/src/root-block/widgets/format-bar/config.ts

Closes: [BS-827](https://linear.app/affine-design/issue/BS-827/format-bar-上-database-和-linked-doc-显示按钮优化)

fix(blocks): database button is not displayed when inline text in a single block is selected

---

packages/blocks/src/database-block/data-view/view/presets/table/components/cell-container.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/row.ts
packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts

fix(database): readonly mode

---

packages/framework/inline/src/services/event.ts
tests/edgeless/edgeless-text.spec.ts

fix(inline): selection state should not affect the external when handling input events

---

packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
packages/blocks/src/paragraph-block/styles.ts

[BS-822](https://linear.app/affine-design/issue/BS-822/link-%E6%96%87%E6%9C%AC%E5%AD%97%E4%BD%93%E5%A4%A7%E5%B0%8F%E5%8F%98%E5%B0%8F%E4%BA%86)

fix(blocks): link inside inline code rendering issue

---

packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
packages/blocks/src/database-block/data-source.ts
packages/framework/store/src/schema/base.ts
packages/framework/store/src/store/doc/block.ts
packages/presets/src/fragments/copilot-panel/copilot-panel.ts
packages/presets/src/fragments/outline-panel/body/outline-panel-body.ts

@donteatfriedrice We need to add some tests for toc feature. It's broken in master branch but we didn't know it.

refactor(store): remove `childrenUpdated` slot

---

packages/blocks/src/root-block/clipboard/middlewares/paste.ts
tests/format-bar.spec.ts

This solves https://github.com/toeverything/blocksuite/pull/7526#discussion_r1671398684 .

fix(blocks): no delete when duplicate

---

packages/blocks/src/root-block/clipboard/middlewares/paste.ts

fix(blocks): only apply delta when link delta indeed transformed

---

packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/attachment-block/attachment-service.ts
packages/blocks/src/bookmark-block/bookmark-service.ts
packages/blocks/src/image-block/image-block.ts
packages/blocks/src/image-block/image-service.ts
packages/blocks/src/note-block/note-service.ts
tests/attachment.spec.ts
tests/bookmark.spec.ts
tests/embed-synced-doc.spec.ts
tests/linked-page.spec.ts
tests/utils/actions/misc.ts
tests/utils/asserts.ts

[BS-868](https://linear.app/affine-design/issue/BS-868/无法拖拽-embed-block-到白板)

fix: cannot drag embed block to edgeless surface

---

packages/presets/src/blocks/_common/utils.ts
packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
packages/presets/src/blocks/ai-chat-block/components/ai-chat-messages.ts
packages/presets/src/blocks/ai-chat-block/components/chat-block-peek-view.ts
packages/presets/src/blocks/ai-chat-block/components/chat-images.ts
packages/presets/src/blocks/ai-chat-block/components/date-time.ts
packages/presets/src/blocks/ai-chat-block/components/text-renderer.ts
packages/presets/src/blocks/ai-chat-block/components/user-info.ts
packages/presets/src/blocks/ai-chat-block/styles.ts

[BS-565](https://linear.app/affine-design/issue/BS-565/支持-ai-chat-block-在-center-peek-中展示)

feat: ai chat block peek view

---

packages/blocks/src/database-block/data-view/common/detail/detail.ts
packages/blocks/src/database-block/data-view/view/data-view-manager.ts
packages/blocks/src/database-block/data-view/view/presets/kanban/kanban-view-manager.ts
packages/blocks/src/database-block/data-view/view/presets/table/table-view-manager.ts
packages/blocks/src/database-block/detail-panel/block-renderer.ts

feat(database): supports switch row in detail panel

---

packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts

fix: sentry-32b8bbd881c248f9b8999ab107c0e53c

---

packages/framework/block-std/src/view/utils/inline-range-provider.ts

fix: sentry-6262b0c9961440f48e6ce51bcfcc48a2

---

packages/blocks/src/_common/components/rich-text/rich-text.ts

fix: sentry-641833b93aae4d5dbc9b082ba683cd37

---

packages/blocks/src/_common/components/rich-text/keymap/container.ts
packages/blocks/src/root-block/widgets/linked-doc/index.ts
packages/framework/inline/src/services/range.ts
packages/framework/inline/src/utils/keyboard.ts

fix: sentry-9f4e9a3875764645b679494374e9efa9

---

packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/column-header.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/vertical-indicator.ts

refactor(database): remove floating of Add Column button

---

packages/blocks/src/_common/inline/inline-manager.ts

fix: sentry-0070623f211c46dca1c1d51c7289eebc

---

packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts

fix: sentry-fb712c6acac24da49c2c8e12ca76d1cc

---

packages/blocks/src/_common/components/rich-text/keymap/container.ts

fix: sentry-f3c0a23a58d6436c8800fe0ef1e82af3

---

packages/framework/inline/src/components/v-element.ts
packages/framework/inline/src/utils/query.ts

fix: sentry-9195c66b2b7040d29a48686028276c00

---

packages/blocks/src/_common/adapters/markdown.ts
packages/blocks/src/_common/transformers/html.ts
packages/blocks/src/_common/transformers/markdown.ts
packages/blocks/src/_common/transformers/zip.ts
packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
packages/blocks/src/root-block/edgeless/services/template.ts
packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts
packages/framework/block-std/src/clipboard/index.ts
packages/framework/global/src/exceptions/code.ts
packages/framework/global/src/utils/assert.ts
packages/framework/store/src/adapter/base.ts
packages/framework/store/src/transformer/job.ts
packages/playground/apps/_common/components/debug-menu.ts
packages/playground/apps/_common/components/quick-edgeless-menu.ts
packages/presets/src/__tests__/main/snapshot.spec.ts
packages/presets/src/ai/_common/markdown-utils.ts
packages/presets/src/ai/utils/markdown-utils.ts
tests/utils/actions/misc.ts

fix: sentry-6a2f3a9e9d2749989a0f09f59cf7cd63

---

packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/link-popup.ts

fix: sentry-cd0c7d20a0344fc188e0c2b525477c7b

---

packages/blocks/src/surface-block/middlewares/group.ts

fix: sentry-28d48c8551684e83b29ad33e9aec3dda

---

packages/blocks/src/root-block/page/page-root-block.ts
packages/blocks/src/root-block/widgets/page-dragging-area/page-dragging-area.ts

fix: sentry-358a172f7ed44c719ab06435e38990c4

---

packages/blocks/src/_common/components/rich-text/hooks.ts
packages/blocks/src/_common/components/rich-text/markdown/block.ts
packages/framework/inline/src/__tests__/utils.ts
packages/framework/inline/src/services/range.ts

fix: sentry-d0bcc6c3bb54414fad524432d8ce6796

---

packages/framework/global/src/exceptions/code.ts
packages/framework/inline/src/services/range.ts
packages/framework/inline/src/utils/range-conversion.ts

fix: sentry-1b8b363715d2464eba86353fe25aa5c3

---

packages/blocks/src/database-block/database-block.ts

fix(database): show toast when copying database is successful

---

packages/blocks/src/surface-ref-block/surface-ref-portal.ts

fix: sentry-53881c0c3ae544958efadc65cabbbc15

---

packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts

fix: sentry-939ef1e6227f4366aa8a200e0afce1ab

---

packages/blocks/src/_common/components/date-picker/date-picker.ts
packages/blocks/src/database-block/data-view/column/presets/date/cell-renderer.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/styles.ts

fix(database): date format and date picker bugs

---

packages/blocks/src/database-block/data-source.ts

fix(database): moving row to the last row causes an error

---

packages/framework/block-std/src/view/element/widget-element.ts

fix: sentry-d03e2cc2290244249e559f3635730f4f

---

packages/blocks/src/surface-block/utils/xywh.ts

fix: sentry-1e39ac90d7cd43a39ea5641cc7f41f82

---

packages/blocks/src/root-block/edgeless/edgeless-root-block.ts

fix: sentry-7316baf8a74b4e288b68b5df6923e538

---

packages/blocks/src/_common/components/hover/controller.ts

fix: sentry-7eef49fc158047afbdd58c3d7f938718

---

packages/blocks/src/root-block/edgeless/components/note-slicer/index.ts

fix: sentry-679fa35ab00641519ad5b320af75e18b

---

packages/blocks/src/root-block/edgeless/edgeless-root-service.ts

fix: sentry-32c6665e453645e6a70423188286a670

---

packages/blocks/src/edgeless-text/edgeless-text-block.ts
packages/blocks/src/root-block/widgets/edgeless-zoom-toolbar/zoom-toolbar.ts

fix: sentry-542c34afc8224886bb19e20305cc1dbf

---

packages/blocks/src/root-block/widgets/linked-doc/index.ts

fix: sentry-52f51d2f2f864327ac86a1ea18dad2ae

---

packages/blocks/src/root-block/edgeless/edgeless-root-block.ts

fix: sentry-2b573590e6444fa5b8b1cd3c70a3ed02

---

packages/blocks/src/database-block/data-view/view/presets/kanban/cell.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/cell-container.ts
tests/database/column.spec.ts
tests/database/selection.spec.ts
tests/utils/actions/misc.ts

refactor(database): entering edit mode require two clicks

---

packages/blocks/src/surface-block/surface-block.ts

fix: sentry-062c8071874045229c52f85c420431fb

---

packages/blocks/src/root-block/edgeless/utils/snap-manager.ts

fix: sentry-0ef51299013e4632893ee6497c63906b

---

packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts

fix: sentry-4cfe1a4f5e824901952bb2268cfb1b61

---

packages/blocks/src/code-block/code-block.ts

fix: sentry-f2c9dd110faa4ee497aaad2dbfe9a894

---

packages/framework/block-std/src/view/element/block-element.ts

fix: sentry-1613db193b764bbface70676eacaf936

---

packages/blocks/src/_common/utils/query.ts

fix: sentry-6ae660f640864ca08e213727ab073f02

---

packages/blocks/src/_common/utils/selection.ts

fix: sentry-df5b7c6737764805bb06ba6f753f28f1

---

packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts

fix: sentry-c7c75ff148074f60a1ccf83de025145c

---

packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts

fix: sentry-b9a8fbe476bb42af8a24c73572e85e04

---

packages/blocks/src/_common/components/rich-text/rich-text-operations.ts

fix: sentry-a9663f0a1ad445f9baa3b4b6340686ad

---

packages/blocks/src/edgeless-text/edgeless-text-block.ts
tests/edgeless/edgeless-text.spec.ts

fix: edgeless text can not add max width

---

packages/blocks/src/list-block/list-block.ts
packages/blocks/src/list-block/styles.ts
tests/list.spec.ts

fix(blocks): always render blocks to make them selectable

---

packages/blocks/src/_common/utils/event.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/widgets/page-dragging-area/page-dragging-area.ts
packages/presets/src/__tests__/utils/common.ts
tests/edgeless/basic.spec.ts
tests/utils/actions/edgeless.ts

Close: [BS-797](https://linear.app/affine-design/issue/BS-797/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E7%99%BD%E6%9D%BF%E5%8F%8C%E6%8C%87%E7%BC%A9%E6%94%BE)
Use `pinch` event to zoom for edgeless editor.

feat(edgeless): pinch to zoom for edgeless editor

---

packages/blocks/src/_common/edgeless/note/consts.ts
packages/blocks/src/note-block/note-edgeless-block.ts
tests/edgeless/note.spec.ts

fix(edgeless): can not select text cross multi blocks

---

packages/blocks/src/_common/transformers/middlewares.ts

This closes [BS-826](https://linear.app/affine-design/issue/BS-826)

fix(edgeless): surface ref copy & paste

---

packages/blocks/src/database-block/data-view/common/ast.ts
packages/blocks/src/database-block/data-view/logical/typesystem.ts
packages/blocks/src/database-block/data-view/view/data-view.ts
packages/blocks/src/database-block/data-view/view/presets/kanban/controller/selection.ts
packages/blocks/src/database-block/utils.ts
packages/blocks/src/database-block/view-source.ts
packages/framework/global/src/exceptions/code.ts

refactor(database): replace Error with BlockSuiteError

---

packages/framework/store/src/reactive/text.ts

```ts
class Text {
// ...
get length() {
return this._yText.length;
}
}
```
```ts
class Text {
private _length$: Signal<number>;
// ...
get length() {
return this._length$.value;
}
}
```

chore(store): signal based Text length

---

packages/blocks/src/_common/adapters/html.ts
packages/blocks/src/_common/adapters/markdown.ts
packages/blocks/src/_common/adapters/notion-html.ts
packages/blocks/src/_common/adapters/utils.ts
packages/blocks/src/_common/export-manager/export-manager.ts
packages/presets/src/ai/utils/image.ts

This fixes sentry-ff49256c5f7f40dbb32ec05e75e37266.

refactor(blocks): handle fetching errors in adapters

---

packages/blocks/src/_common/components/toolbar/menu-button.ts
packages/blocks/src/root-block/edgeless/components/color-picker/button.ts
packages/blocks/src/root-block/edgeless/components/color-picker/color-picker.ts
packages/blocks/src/root-block/edgeless/components/color-picker/styles.ts
packages/blocks/src/root-block/edgeless/components/color-picker/utils.ts
tests/edgeless/color-picker.spec.ts

Closes [BS-938](https://linear.app/affine-design/issue/BS-938/添加测试用例)

chore: add basic tests for color picker

---

packages/blocks/src/surface-block/element-model/shape.ts

See https://github.com/toeverything/blocksuite/pull/7585#pullrequestreview-2201988995

fix(blocks): color may be undefined

---

packages/blocks/src/database-block/components/title/index.ts

fix(database): switching to edgeless mode causes an error with the title

---

packages/blocks/src/database-block/data-view/common/detail/detail.ts

fix(database): adjust the center peek margin

---

packages/framework/inline/src/utils/transform-input.ts

This closes [BS-897](https://linear.app/affine-design/issue/BS-897)

fix(inline): spell checker itself will delete text

---

packages/blocks/src/database-block/data-view/view/presets/table/controller/hotkeys.ts
packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts

fix(database): cell selection doesn't support multiple cells with keyboard

---

packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
tests/paragraph.spec.ts

fix(blocks): update block split role

---

packages/blocks/src/root-block/edgeless/components/color-picker/button.ts
packages/blocks/src/root-block/edgeless/components/color-picker/color-picker.ts

* no need to use `styleMap` wrapper in `computed`
* improve wheel event

chore(blocks): improve color picker

---

packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-element.ts

fix: sentry-501276eeb3104b0d82e8b505869c0651

---

packages/framework/store/src/reactive/text.ts

fix: sentry-7b824a26ad3343298da8332e56f2ce89

---

packages/blocks/src/paragraph-block/paragraph-block.ts

fix: placeholder display when ime input

---

packages/blocks/src/root-block/edgeless/controllers/clipboard.ts

[BS-1012](https://linear.app/affine-design/issue/BS-1012/添加拓展-edgeless-clipboard-的方式)
related: [BS-1005](https://linear.app/affine-design/issue/BS-1005/chat-block无法被copy-paste到别的文档中，duplicate全篇文档后，可以center-peek)
Maintain a block config array in the edgeless clipboard controller
```
type BlockCreationFunction = (
snapshots: BlockSnapshot[],
oldIdToNewIdMap: Map<string, string>
) => Promise<string[]> | string[];
interface BlockConfig {
flavour: string;
createFunction: BlockCreationFunction;
}
private _blockConfigs: BlockConfig[] = [];
```
support more types of block creation by expanding the block config array and customize the props that need to be inherited.
```
registerBlock(flavour: string, createFunction: BlockCreationFunction) {
this._blockConfigs.push({
flavour,
createFunction: …
```

feat: support registering edgeless clipboard block

---

packages/blocks/src/frame-block/frame-block.ts
packages/blocks/src/surface-block/managers/layer-manager.ts
packages/presets/src/__tests__/edgeless/frame.spec.ts

Fixes [BS-865](https://linear.app/affine-design/issue/BS-865/edgeless-frame-will-make-the-content-covered-when-setting-a-color)

fix: frame index

---

packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts

fix(edgeless): toolbar nav next button's size should be 20*20

---

packages/blocks/src/database-block/data-view/common/group-by/define.ts
packages/blocks/src/database-block/data-view/common/group-by/renderer/boolean-group.ts
packages/blocks/src/database-block/data-view/view/presets/kanban/group.ts
packages/blocks/src/database-block/data-view/view/presets/table/group.ts

feat(database): support group by checkbox column

---

packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
packages/blocks/src/database-block/data-view/data-view.ts

fix(database): prevent reference popup in database block

---

packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/utils/text.ts

Fixes [BS-954](https://linear.app/affine-design/issue/BS-954/shape-编辑状态下，文本的z-index-高于了-底部-toolbar-的层级)

fix: edgeless text editor mount place

---

packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/root-block/edgeless/utils/consts.ts
tests/edgeless/edgeless-text.spec.ts
tests/linked-page.spec.ts
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-add-linked-doc.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-drag.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-init.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-link-to-card.json

[BS-750](https://linear.app/affine-design/issue/BS-750/bug-edgeless-text-的最小尺寸限制无效)
before:
https://github.com/user-attachments/assets/923369d9-1231-4594-9d07-d5c0cbda6712

fix(edgeless): embed block has min width in edgeless text and update note min width

---

packages/framework/block-std/src/gfx/surface/element-model.ts

Fixes [BS-325](https://linear.app/affine-design/issue/BS-325/shape-text-undoredo-没有渲染)

fix: text does not render when undo/redo

---

packages/presets/src/blocks/ai-chat-block/ai-chat-model.ts
packages/presets/src/blocks/ai-chat-block/components/ai-chat-messages.ts
packages/presets/src/blocks/ai-chat-block/components/text-renderer.ts
packages/presets/src/blocks/ai-chat-block/components/user-info.ts
packages/presets/src/blocks/ai-chat-block/types.ts

fix: 
[BS-1005](https://linear.app/affine-design/issue/BS-1005/chat-block无法被copy-paste到别的文档中，duplicate全篇文档后，可以center-peek)
[BS-990](https://linear.app/affine-design/issue/BS-990/避免centerpeek中发起的会话，等待ai返回时，页面失去响应)

fix: optimize text renderer and update ai chat block model

---

packages/blocks/src/root-block/edgeless/components/note-slicer/index.ts
packages/blocks/src/root-block/root-service.ts

chore(blocks): add event for split note

---

packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts

[BS-1041](https://linear.app/affine-design/issue/BS-1041/copy-as-png-not-work)

fix: remove copy as png entry temporarily

---

packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts

fix(blocks): source may be undefined on connector

---

packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts

fix(blocks): source and target may be undefined on connector

---

packages/blocks/src/note-block/note-edgeless-block.ts

[BS-962](https://linear.app/affine-design/issue/BS-962/收起的-note-在编辑态下存在奇怪的-hover-样式，该样式问题源于-active-和非-active-状态下-note-尺寸的差异：)

fix: note collapse content

---

packages/blocks/src/_common/styles.ts
packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts

Upstream: https://github.com/toeverything/design/pull/122

chore(blocks): update panel overlay shadow style

---

packages/blocks/src/surface-ref-block/surface-ref-block.ts

This closes [BS-1039](https://linear.app/affine-design/issue/BS-1039)

fix(edgeless): support referencing surface in different pages

---

packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/framework/block-std/src/event/control/pointer.ts
packages/framework/block-std/src/event/dispatcher.ts
packages/framework/block-std/src/event/utils.ts
packages/presets/src/__tests__/utils/common.ts
tests/edgeless/basic.spec.ts
tests/utils/actions/edgeless.ts

Close [BS-1042](https://linear.app/affine-design/issue/BS-1042/双指手势可以移动画板)
- add `pan` event
- move viewport based on `pan` event
- refactor dual pointer event process

feat(edgeless): move viewport by dual touch pan

---

packages/blocks/src/note-block/note-edgeless-block.ts

[BS-1057](https://linear.app/affine-design/issue/BS-1057/去掉-edgeless-note-hover-状态)

feat: remove edgeless note hover background

---

packages/blocks/src/_common/components/embed-card/modal/embed-card-caption-edit-modal.ts
packages/blocks/src/_common/components/embed-card/modal/embed-card-create-modal.ts
packages/blocks/src/_common/components/embed-card/modal/embed-card-edit-modal.ts
packages/blocks/src/_common/components/embed-card/modal/styles.ts
packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts

* fix button background color when it is disabled
* fix input border color when it is out of focus

fix(blocks): input and button style on edit modal

---

packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts

feat: handle copilot error

---

packages/blocks/src/_common/components/button.ts
packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts

Close issue [BS-907](https://linear.app/affine-design/issue/BS-907).
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/22d9985e-1a49-41df-a2af-ca8dbecf5e6f.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/22d9985e-1a49-41df-a2af-ca8dbecf5e6f.mov">录屏2024-08-07 00.04.53.mov</video>

feat: show tooltip whether text length overflows in at menu

---

packages/blocks/src/edgeless-text/edgeless-text-block.ts
packages/blocks/src/frame-block/frame-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/surface-block/managers/layer-manager.ts
packages/framework/block-std/src/gfx/index.ts
packages/framework/block-std/src/gfx/viewport-element.ts
packages/framework/block-std/src/view/element/gfx-block-component.ts
packages/presets/src/__tests__/edgeless/frame.spec.ts
packages/presets/src/__tests__/edgeless/layer.spec.ts
tests/edgeless/basic.spec.ts

Add `gfx-viewport` element, it binds edgeless viewport and apply it as CSS transform. It also provide rendering optimization that hides the blocks outside the viewport automatically.

fix: edgeless performance regression

---

packages/framework/block-std/src/range/range-binding.ts

fix: select won't cross image

---

packages/blocks/src/edgeless-text/edgeless-text-service.ts

Before:
https://github.com/user-attachments/assets/e02b2490-7b14-4047-adb0-07da8615c1c1

fix(edgeless): can not add bookmark in empty edgeless text

---

packages/blocks/src/root-block/edgeless/services/tools-manager.ts

Related to https://github.com/toeverything/blocksuite/pull/7871

fix(blocks): should check editing state in pointerdown event

---

packages/blocks/src/code-block/styles.ts

fix: code block css

---

packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
tests/fragments/frame-panel.spec.ts

[BS-976](https://linear.app/affine-design/issue/BS-976/frame-panel-改用-render-spec-portal-渲染)

refactor: using renderSpecPortal to render frame preview

---

packages/blocks/src/root-block/widgets/element-toolbar/index.ts

Closes [BS-903](https://linear.app/affine-design/issue/BS-903/edgeless-toolbar-位置问题)

fix(blocks): element toolbar position

---

package.json
packages/blocks/src/data-view-block/data-view-block.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-connector-label-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-frame-title-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-group-title-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
packages/blocks/src/surface-block/surface-block.ts
packages/blocks/src/surface-ref-block/portal/note.ts
packages/framework/block-std/src/range/consts.ts
packages/framework/block-std/src/range/index.ts
packages/framework/block-std/src/range/range-binding.ts
packages/framework/block-std/src/range/range-manager.ts
packages/framework/block-std/src/view/element/block-component.ts
packages/framework/block-std/src/view/element/consts.ts
packages/framework/block-std/src/view/element/index.ts
packages/framework/block-std/src/view/element/widget-component.ts
packages/framework/store/src/store/doc/block-collection.ts
packages/framework/store/src/store/doc/block/index.ts
packages/framework/store/src/store/doc/block/sync-controller.ts
packages/framework/store/src/store/doc/consts.ts
packages/framework/store/src/store/doc/doc.ts
packages/framework/store/src/store/doc/index.ts
packages/framework/store/src/store/doc/query.ts

fix: circular dependencies

---

packages/affine/shared/src/utils/event.ts

Maybe cancel previous animation frame that will be better.

chore(blocks): cancel previous animation frame

---

packages/blocks/src/database-block/data-source.ts

fix(database): adding a column didn't trigger view refresh

---

packages/blocks/src/root-block/widgets/linked-doc/index.ts

Related PR https://github.com/toeverything/blocksuite/pull/7914

chore: rebase linked doc IME fix

---

packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
tests/edgeless/basic.spec.ts

Close [BS-1096](https://linear.app/affine-design/issue/BS-1096/[frame-and-group-improvement]-frame-和-group-进入选中态-border-改为-2px)

chore(edgeless): adjust selected rect border width

---

packages/blocks/src/surface-ref-block/portal/note.ts

Closes [BS-1162](https://linear.app/affine-design/issue/BS-1162/httpstoeverythingsentryioissues5694794681)
https://toeverything.sentry.io/issues/5694794681

fix(blocks): sentry 5694794681

---

packages/affine/components/src/toolbar/menu-button.ts
packages/blocks/src/root-block/edgeless/components/color-picker/button.ts

Closes [BS-1161](https://linear.app/affine-design/issue/BS-1161/safari-兼容性)

fix(blocks): use CustomEvent instead of ToggleEvent

---

packages/framework/block-std/src/gfx/viewport-element.ts
tests/edgeless/presentation.spec.ts
tests/utils/actions/edgeless.ts

[BS-1086](https://linear.app/affine-design/issue/BS-1086/frame-present-时不渲染-note)

fix: edgeless note not rendering when presentation

---

packages/presets/src/fragments/outline/body/outline-panel-body.ts
packages/presets/src/fragments/outline/card/outline-preview.ts
packages/presets/src/fragments/outline/outline-panel.ts
packages/presets/src/fragments/outline/outline-viewer.ts
packages/presets/src/fragments/outline/utils/scroll.ts
tests/fragments/outline.spec.ts

- **Update animation**, previous animation has scroll issue after opening outline viewer panel.
- **Update gap of indicators**
- **Fix heading highlight issue**
https://github.com/user-attachments/assets/c6256dfa-0eaf-43e1-a810-4b22376be921

chore(presets): update outline-viewer animation

---

packages/blocks/src/database-block/data-view/common/properties.ts

Before
https://github.com/user-attachments/assets/94bd1260-5e69-4099-8a3e-d1b53978cd47
After
https://github.com/user-attachments/assets/42fda71d-62a9-4023-8a0f-530a3efcc67d

fix(blocks): watch signal for properties setting view

---

packages/blocks/src/bookmark-block/bookmark-block.ts
packages/blocks/src/bookmark-block/bookmark-edgeless-block.ts
packages/blocks/src/bookmark-block/bookmark-service.ts
packages/blocks/src/bookmark-block/bookmark-spec.ts
packages/blocks/src/bookmark-block/components/bookmark-card.ts

- rewrite edgeless bookmark block

refactor: rewrite edgeless bookmark block

---

packages/blocks/src/root-block/widgets/linked-doc/index.ts

This PR merge this [commit ](https://github.com/toeverything/blocksuite/pull/7942) from branch 0.16.1 to master.

fix(blocks): linked doc popover is not singleton

---

packages/blocks/src/code-block/code-block-config.ts
packages/blocks/src/code-block/code-block-service.ts
packages/blocks/src/code-block/code-block-spec.ts
packages/blocks/src/code-block/code-block.ts
packages/blocks/src/root-block/widgets/code-language-list/components/lang-button.ts

Close [BS-1218](https://linear.app/affine-design/issue/BS-1218/code-block在affine里炸了)

refactor(blocks): code-block get supported langs in config

---

packages/blocks/src/root-block/edgeless/components/color-picker/color-picker.ts
packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts

[BS-862](https://linear.app/affine-design/issue/BS-862/bug-修复-hex-input-复制问题)

fix: template and color picker input copy past

---

packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts

Fixes [BS-1069](https://linear.app/affine-design/issue/BS-1069/优化：mind-map-回车键的行为的调整)
Fixes [BS-829](https://linear.app/affine-design/issue/BS-829/优化：选中-mind-map-节点的情况下的键盘输入行为)

fix: hotkey behaviour on mind map

---

packages/blocks/src/edgeless-text/edgeless-text-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/surface-block/canvas-renderer/renderer.ts
packages/framework/block-std/src/gfx/viewport-element.ts

- Edgeless text infinite loop update width @doouding 
- Optimize first viewport element rendering @doouding
- Edgeless content shift on first entering edgeless mode @doouding
- Optimize canvas renderer to avoid looply calling rAf @doouding

fix: 0.16.1 patch

---

packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts

Fixes [PD-1284](https://linear.app/affine-design/issue/PD-1284/优化：删除节点之后需要选择相邻节点)

fix: should focus on other node when deleting mind map node

---

packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/embed-figma-block/embed-edgeless-figma-block.ts
packages/blocks/src/embed-figma-block/embed-figma-block.ts
packages/blocks/src/embed-figma-block/embed-figma-spec.ts
packages/blocks/src/embed-github-block/embed-edgeless-github-block.ts
packages/blocks/src/embed-github-block/embed-github-block.ts
packages/blocks/src/embed-github-block/embed-github-spec.ts
packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts
packages/blocks/src/embed-html-block/embed-edgeless-html-block.ts
packages/blocks/src/embed-html-block/embed-html-block.ts
packages/blocks/src/embed-html-block/embed-html-spec.ts
packages/blocks/src/embed-linked-doc-block/embed-edgeless-linked-doc-block.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-spec.ts
packages/blocks/src/embed-loom-block/embed-edgeless-loom-bock.ts
packages/blocks/src/embed-loom-block/embed-loom-block.ts
packages/blocks/src/embed-loom-block/embed-loom-spec.ts
packages/blocks/src/embed-synced-doc-block/components/embed-synced-doc-card.ts
packages/blocks/src/embed-synced-doc-block/embed-edgeless-synced-doc-block.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-spec.ts
packages/blocks/src/embed-youtube-block/embed-edgeless-youtube-block.ts
packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
packages/blocks/src/embed-youtube-block/embed-youtube-spec.ts
packages/framework/block-std/src/view/element/gfx-block-component.ts
tests/edgeless/clipboard.spec.ts
tests/embed-synced-doc.spec.ts

Rewrite all embed blocks in edgeless mode. Including the following blocks:
- embed-figma-block
- embed-github-block
- embed-html-block
- embed-linked-doc-block
- embed-loom-block
- embed-synced-doc-block
- embed-youtube-block

refactor: rewrite edgeless embed blocks

---

packages/blocks/src/root-block/widgets/edgeless-auto-connect/edgeless-auto-connect.ts

Fixes [BS-1277](https://linear.app/affine-design/issue/BS-1277/edgeless-toc-note排序永远只可以提到最顶上，不可自由排序)

fix: rerender label when notes' order changes

---

packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
packages/blocks/src/surface-block/managers/connector-manager.ts

Fixes [BS-831](https://linear.app/affine-design/issue/BS-831/bug：单字母快捷键激活-connector-无法精准连接-mind-map-子节点)

feat: allow to connect element inside group

---

packages/affine/model/src/blocks/embed/linked-doc/linked-doc-model.ts
packages/blocks/src/_common/components/doc-mode-service.ts
packages/blocks/src/_common/components/embed-card/type.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-linked-doc-block/utils.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts

Like the affine-reference model.
* add `ReferenceInfo` to `EmbedLinkedDocModel`

feat(blocks): extend linked doc model

---

packages/blocks/src/database-block/data-view/common/detail/detail.ts
packages/blocks/src/database-block/data-view/common/detail/field.ts
packages/blocks/src/database-block/data-view/common/group-by/renderer/base.ts
packages/blocks/src/database-block/data-view/common/group-by/setting.ts
packages/blocks/src/database-block/data-view/view/presets/kanban/card.ts
packages/blocks/src/database-block/data-view/view/presets/kanban/cell.ts
packages/blocks/src/database-block/data-view/view/presets/kanban/group.ts
packages/blocks/src/database-block/data-view/view/presets/kanban/header.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/column-renderer.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-stats-cell.ts
packages/blocks/src/database-block/data-view/view/presets/table/components/column-stats.ts

fix(database): add some SignalWatcher

---

packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-popup.ts
packages/affine/components/src/toolbar/index.ts
packages/affine/components/src/toolbar/types.ts
packages/affine/components/src/toolbar/utils.ts
packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/root-block/configs/index.ts
packages/blocks/src/root-block/configs/toolbar.ts
packages/blocks/src/root-block/index.ts
packages/blocks/src/root-block/root-config.ts
packages/blocks/src/root-block/widgets/element-toolbar/config.ts
packages/blocks/src/root-block/widgets/element-toolbar/more-menu/button.ts
packages/blocks/src/root-block/widgets/element-toolbar/more-menu/config.ts
packages/blocks/src/root-block/widgets/element-toolbar/more-menu/context.ts
packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
packages/blocks/src/root-block/widgets/format-bar/config.ts
packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts

improve more menu capabilities on block toolbar
* inline link toolbar
* attachment-options
* element-toolbar
* embed-card-toolbar
* format-bar
* surface-ref-toolbar

feat(blocks): improve more menu capabilities on block toolbar

---

packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts

Fixes [PD-1214](https://linear.app/affine-design/issue/PD-1214/拖拽非根节点，建议去掉对齐效果)

fix: alignment on dragging mind map nodes

---

packages/blocks/src/database-block/config.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/database-block/index.ts
packages/blocks/src/index.ts
packages/blocks/src/root-block/root-config.ts

* make database options configurable
* add `Copy link to block` button to options on AFFiNE side

feat(blocks): add options config in database

---

packages/presets/src/blocks/ai-chat-block/ai-chat-edgeless-block.ts

[BS-1281](https://linear.app/affine-design/issue/BS-1281/chat-block-缺少-layer-功能，无法放置到顶层)

fix(presets): ai chat block could not be brought to front

---

packages/affine/components/src/caption/captioned-block-component.ts
packages/blocks/src/embed-synced-doc-block/embed-edgeless-synced-doc-block.ts

Closes [BS-1263](https://linear.app/affine-design/issue/BS-1263/embed-模块的caption功能点击后无效)

fix(blocks): use createRef instead of query

---

.gitignore
packages/affine/components/src/peek/peekable.ts
packages/affine/components/src/rich-text/inline/presets/nodes/link-node/affine-link.ts
packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-node.ts

Fix:
https://toeverything.sentry.io/issues/5706682010/events/e309eb762b06433db5e898431fecf4f1/
https://toeverything.sentry.io/issues/5697414344/events/25c089fdbd864b11a72db1651e4150d6/
https://toeverything.sentry.io/issues/5697415720/events/a5b844e1d2074b509b95a5cb17917890/

fix: sentry issues

---

packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts

This closes https://github.com/toeverything/AFFiNE/issues/8016

fix(blocks): broken link in notion subdoc

---

packages/blocks/src/database-block/data-view/view/presets/table/consts.ts
packages/blocks/src/database-block/data-view/view/presets/table/row/row-select-checkbox.ts
packages/blocks/src/database-block/data-view/view/presets/table/row/row.ts

fix(database): adjust checkbox icon size

---

packages/blocks/src/_common/utils/url.ts
packages/blocks/src/root-block/clipboard/middlewares/paste.ts
packages/blocks/src/root-block/edgeless/clipboard/clipboard.ts

part of [BS-1254](https://linear.app/affine-design/issue/BS-1254/增加-block-reference-的埋点)

chore(blocks): add block type to telemetry LinkedDocCreated event

---

packages/affine/block-surface/src/index.ts
packages/affine/block-surface/src/renderer/elements/group/consts.ts
packages/affine/block-surface/src/renderer/elements/group/index.ts
packages/affine/block-surface/src/renderer/elements/group/utils.ts
packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-group-title-editor.ts

Close [BS-1305](https://linear.app/affine-design/issue/BS-1305/[ui]-frame-和-group-标签-ui-更新), [BS-1326](https://linear.app/affine-design/issue/BS-1326/[group]-group-selection-选中改为实线)

chore(edgeless): update group title styles

---

packages/blocks/src/edgeless-text-block/edgeless-text-block.ts

fix(edgeless): height of edgeless text block

---

packages/affine/components/src/rich-text/inline/presets/markdown.ts
packages/affine/components/src/rich-text/inline/presets/nodes/latex-node/latex-editor-menu.ts
packages/affine/components/src/rich-text/inline/presets/nodes/latex-node/latex-node.ts
packages/affine/model/src/blocks/edgeless-text/edgeless-text-model.ts
packages/affine/model/src/blocks/index.ts
packages/affine/model/src/blocks/latex/index.ts
packages/affine/model/src/blocks/latex/latex-model.ts
packages/affine/model/src/blocks/note/note-model.ts
packages/blocks/package.json
packages/blocks/src/_specs/group/edgeless.ts
packages/blocks/src/_specs/preset/edgeless-specs.ts
packages/blocks/src/_specs/preset/page-specs.ts
packages/blocks/src/_specs/preset/preview-specs.ts
packages/blocks/src/latex-block/latex-block.ts
packages/blocks/src/latex-block/latex-service.ts
packages/blocks/src/latex-block/latex-spec.ts
packages/blocks/src/latex-block/styles.ts
packages/blocks/src/root-block/widgets/slash-menu/config.ts
packages/blocks/src/schemas.ts
pnpm-lock.yaml
tests/hotkey.spec.ts
tests/slash-menu.spec.ts
tests/utils/asserts.ts

https://github.com/user-attachments/assets/53bc7068-9cb9-44b4-ad6a-977ddf76702e

feat(blocks): latex block in page mode

---

packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts
tests/database/column.spec.ts

related https://github.com/toeverything/blocksuite/pull/7786

fix(database): drag fill handle not working

---

packages/blocks/src/root-block/widgets/slash-menu/config.ts

Close [BS-1211](https://linear.app/affine-design/issue/BS-1211/list的slash-menu没有插入frame-group的选项)

fix(blocks): slashmenu miss frame group items in sub list

---

packages/affine/block-surface/src/element-model/mindmap.ts
tests/edgeless/mindmap.spec.ts
tests/utils/actions/edgeless.ts

close [BS-1352](https://linear.app/affine-design/issue/BS-1352/mindmap删除后undo，提示shape不存在xywh)
https://github.com/user-attachments/assets/e3ef3ff4-c65c-45fb-9ead-1e954485212a
https://github.com/user-attachments/assets/9279d155-00df-42fa-a931-e7342f627c04

fix(edgeless): root of mindmap may be invalid during delting

---

packages/affine/data-view/src/core/common/group-by/helper.ts
packages/affine/data-view/src/view-presets/table/table-view.ts
tests/database/selection.spec.ts

fix(database): unable to add group in kanban view

---

packages/blocks/src/root-block/edgeless/components/toolbar/presentation-toolbar.ts
tests/edgeless/presentation.spec.ts

[BS-1344](https://linear.app/affine-design/issue/BS-1344/presentation-esc-建议直接改成退出，不再退出全屏)

feat: exit presentation when press esc on presentation

---

packages/affine/data-view/src/core/common/stats/checkbox.ts
packages/affine/data-view/src/core/common/stats/index.ts
packages/affine/data-view/src/core/common/stats/type.ts
packages/affine/data-view/src/view-presets/table/stats/column-stats-column.ts

feat(database): specialize the checkbox statistics

---

packages/affine/shared/src/utils/zod-schema.ts
packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
packages/blocks/src/root-block/edgeless/components/auto-complete/utils.ts
packages/playground/apps/starter/data/heavy-whiteboard.ts
tests/edgeless/auto-complete.spec.ts

Close issue [BS-1222](https://linear.app/affine-design/issue/BS-1222).
Remove custom props logic of auto complete panel.

feat: remove custom props logic of auto complete panel

---

packages/affine/data-view/src/core/view-manager/single-view.ts

fix(database): the row icon is missing

---

packages/affine/components/src/toast/create.ts

Fix: [BS-1340](https://linear.app/affine-design/issue/BS-1340/[bug]-toast-的位置不固定)

fix: toast position incorrect when page scrolled

---

packages/affine/components/src/context-menu/menu.ts

https://github.com/user-attachments/assets/62933827-e942-470f-b0ac-09865e4d0244

fix(database): cursor text on first menu item

---

packages/affine/data-view/src/core/common/stats/any.ts
packages/affine/data-view/src/core/common/stats/checkbox.ts

fix(database): statistics NaN on empty rows

---

packages/blocks/src/_common/transformers/middlewares.ts

https://github.com/user-attachments/assets/9d176306-00ef-4764-8e7b-95c95f8c3a3a
https://github.com/user-attachments/assets/afe27aa7-daa6-41ed-837b-3f8078f1d044

fix(blocks): surface-ref of frame miss after paste

---

packages/presets/src/__tests__/edgeless/surface-ref.spec.ts
packages/presets/src/__tests__/snapshots/edgeless/surface-ref.spec.ts/surface-ref.json
packages/presets/src/__tests__/utils/misc.ts

test(blocks): add surface-ref import test

---

packages/blocks/src/root-block/edgeless/components/toolbar/brush/brush-menu.ts

Add `SignalWatcher` to brush menu.

fix: brush menu does not react to thickness and color change

---

packages/blocks/src/root-block/widgets/ai-panel/components/generating-placeholder.ts

Fix: [PD-1372](https://linear.app/affine-design/issue/PD-1372/loading-dark-mode-color-error)

fix: generating placeholder style

---

packages/affine/components/src/peek/controller.ts
packages/affine/components/src/peek/index.ts
packages/affine/components/src/peek/service.ts
packages/affine/shared/src/services/doc-mode-service.ts
packages/blocks/src/data-view-block/data-view-block.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/index.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-preview-block.ts
packages/blocks/src/root-block/root-service.ts
packages/playground/apps/default/utils/editor.ts

```ts
// old:
std.getService('affine:page').peekViewService
// new:
std.getOptional(PeekViewProvider)
```

feat: add peek view extension

---

packages/blocks/src/embed-linked-doc-block/embed-edgeless-linked-doc-block.ts

Closes [BS-1322](https://linear.app/affine-design/issue/BS-1322/在白板上插入-linked-doc，显示异常)

fix(blocks): should use cardStyle for rendering

---

packages/affine/data-view/src/view-presets/table/header/database-header-column.ts

- Added `hide in view` in the context menu

feat(database): easy access to property visibility

---

packages/affine/block-surface/src/element-model/mindmap.ts
packages/affine/block-surface/src/element-model/utils/mindmap/index.ts
packages/affine/block-surface/src/element-model/utils/mindmap/utils.ts
packages/blocks/src/root-block/edgeless/tools/default-tool.ts

Next step should be removing the `layout` and `applyStyle`  methods.

refactor(edgeless): extract ui utils from mindmap model

---

packages/affine/data-view/src/view-presets/table/header/column-header.ts

fix(database): remove infinity raf

---

packages/affine/model/src/blocks/frame/frame-model.ts
packages/blocks/src/root-block/edgeless/frame-manager.ts

- add `addChildren` method for frame model
- ~~fixed signal emit twice when add a child to frame model~~

chore(edgeless): impl addChildren for frame model

---

packages/affine/data-view/src/widget-presets/views-bar/views.ts

refactor(database): change the maximum width of the view title to 200px

---

packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
packages/blocks/src/_common/embed-block-helper/styles.ts
packages/blocks/src/embed-figma-block/embed-figma-block.ts
packages/blocks/src/embed-figma-block/styles.ts
packages/blocks/src/embed-github-block/embed-github-block.ts
packages/blocks/src/embed-github-block/styles.ts
packages/blocks/src/embed-html-block/embed-edgeless-html-block.ts
packages/blocks/src/embed-html-block/embed-html-block.ts
packages/blocks/src/embed-html-block/styles.ts
packages/blocks/src/embed-linked-doc-block/embed-edgeless-linked-doc-block.ts
packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/blocks/src/embed-linked-doc-block/styles.ts
packages/blocks/src/embed-loom-block/embed-loom-block.ts
packages/blocks/src/embed-loom-block/styles.ts
packages/blocks/src/embed-synced-doc-block/embed-edgeless-synced-doc-block.ts
packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
packages/blocks/src/embed-youtube-block/styles.ts
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-drag.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-link-to-card.json

Fixes [BS-1368](https://linear.app/affine-design/issue/BS-1368/当调整-scale-时，bookmark-linked-doc-synced-doc-的-caption-位置问题)

fix: embed series block style

---

packages/blocks/src/_common/transformers/middlewares.ts

Closes: [BS-381](https://linear.app/affine-design/issue/BS-381/%E5%B8%A6-embed-view-%E7%9A%84-note-%E5%A4%8D%E5%88%B6%E6%97%B6%EF%BC%8C%E5%8F%AA%E5%A4%8D%E5%88%B6%E4%BA%86-embed-%E7%9A%84%E9%83%A8%E5%88%86)

fix: paste synced doc

---

packages/affine/components/src/portal/helper.ts

fix(blocks): portal is not Interactive in affine's modal

---

packages/blocks/src/edgeless-text-block/edgeless-text-block.ts

<a href="https://app.graphite.dev/media/video/8ypiIKZXudF5a0tIgIzf/02ce1487-c3ae-449c-8957-09815376da8c.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/8ypiIKZXudF5a0tIgIzf/02ce1487-c3ae-449c-8957-09815376da8c.mov">Screen Recording 2024-09-16 at 18.00.12.mov</video>

fix(blocks): unable to get selectedRect correctly

---

packages/blocks/src/__tests__/adapters/notion-text.unit.spec.ts
packages/blocks/src/_common/adapters/index.ts
packages/blocks/src/_common/adapters/notion-text.ts
packages/blocks/src/root-block/clipboard/index.ts

This closes [BS-1210](https://linear.app/affine-design/issue/BS-1210)

fix(blocks): pasting a single line from notion

---

packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
packages/presets/src/fragments/frame-panel/frame-panel.ts
tests/fragments/frame-panel.spec.ts

[BS-1414](https://linear.app/affine-design/issue/BS-1414/frame-preview-在切换模式后渲染内容异常)

fix: frame preview should update correctly after mode switched

---

.changeset/odd-jeans-march.md
packages/affine/block-surface/src/index.ts
packages/affine/block-surface/src/utils/mindmap/utils.ts

chore: update exported mindmap utils
chore: changeset

chore: update exported mindmap utils

---

packages/affine/block-embed/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/affine/widget-scroll-anchoring/src/scroll-anchoring.ts

Closes [AF-1393](https://linear.app/affine-design/issue/AF-1393/完善-blockelement-定位)

chore: improve block/element status detection

---

packages/blocks/src/__tests__/adapters/html.unit.spec.ts
packages/blocks/src/_common/adapters/html.ts
packages/blocks/src/root-block/widgets/linked-doc/import-doc/import-doc.ts

This closes [BS-1291](https://linear.app/affine-design/issue/BS-1291)

fix(blocks): pasting multiple times when span nested in p

---

packages/affine/components/src/rich-text/inline/presets/markdown.ts
tests/latex/inline.spec.ts
tests/utils/actions/keyboard.ts

Before:
https://github.com/user-attachments/assets/be29c918-b139-425e-8048-7bd140163ad8

fix: should not add space when toggle latex using markdown shortcut

---

packages/docs/guide/quick-start.md

docs: update css entry

---

packages/affine/components/src/rich-text/inline/presets/nodes/affine-text.ts
packages/affine/components/src/rich-text/inline/presets/nodes/link-node/affine-link.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-node.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-popup.ts

part of [BS-1445](https://linear.app/affine-design/issue/BS-1445/点击-affine-link-时识别应用内链接，以触发应用内跳转)

feat: affine-link supports in-app jumps

---

.changeset/odd-owls-push.md

Fix bugs and improve experience:
- fix slash menu and @ menu issues with IME [#8444](https://github.com/toeverything/blocksuite/pull/8444)
- improve trigger way of latex editor [#8445](https://github.com/toeverything/blocksuite/pull/8445)
- support in-app link jump [#8499](https://github.com/toeverything/blocksuite/pull/8449)
- some ui improvements [#8446](https://github.com/toeverything/blocksuite/pull/8446), [#8450](https://github.com/toeverything/blocksuite/pull/8450)

chore: release patch version

---

packages/blocks/src/database-block/database-block.ts

fix(database): disable database block full-width in edgeless mode

---

packages/affine/components/src/peek/peekable.ts

fix: do not enable shift-click center peek in edgeless

---

packages/affine/block-embed/src/embed-synced-doc-block/embed-synced-doc-block.ts

Closes [BS-1498](https://linear.app/affine-design/issue/BS-1498/linked-doc-的-preview-视图会在每次查看时发生滚动（embed-view）)
* improve `embed-synced-doc-block` experience
* turn off smooth scaling
* cache bounds

fix: turn off smooth scaling and cache bounds

---

packages/affine/block-embed/src/embed-linked-doc-block/embed-edgeless-linked-doc-block.ts
packages/affine/block-embed/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/affine/block-embed/src/embed-linked-doc-block/embed-linked-doc-config.ts
packages/affine/block-embed/src/embed-linked-doc-block/index.ts

feat: add EmbedLinkedDocBlockConfig for overriding embed-linked-doc

---

packages/blocks/src/__tests__/adapters/html.unit.spec.ts
packages/blocks/src/_common/adapters/hast.ts
packages/blocks/src/_common/adapters/html.ts

This closes [BS-1255](https://linear.app/affine-design/issue/BS-1255).

fix(blocks): pasting elements with css inline style

---

packages/affine/shared/src/utils/model/get-content-block.ts
tests/bookmark.spec.ts
tests/edgeless/edgeless-text.spec.ts
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-finial.json
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-note-empty.json
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-note-not-empty.json

fix: press backspace at the start of first line when edgeless text exist

---

packages/blocks/package.json
packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
packages/blocks/src/_common/adapters/markdown.ts
packages/playground/apps/_common/components/debug-menu.ts
yarn.lock

[BS-1563](https://linear.app/affine-design/issue/BS-1563/latex-markdown-导入支持)
[BS-1562](https://linear.app/affine-design/issue/BS-1562/latex-markdown-导出支持)

feat: markdown adapter with latex

---

packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
packages/blocks/src/_common/adapters/notion-html.ts

related [BS-1467](https://linear.app/affine-design/issue/BS-1467/notion-html-导入优化)

feat: support notion block equation html import

---

packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
packages/blocks/src/_common/adapters/notion-html.ts

[BS-1569](https://linear.app/affine-design/issue/BS-1569/callout-block-导入为-quote-block)

feat: support notion callout block to blocksuite quote block

---

packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
packages/blocks/src/_common/adapters/notion-html.ts

part of [BS-1610](https://linear.app/affine-design/issue/BS-1610/toggle-list-导入)

fix: import notion toggle list as toggle bulleted list

---

packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
packages/blocks/src/_common/adapters/notion-html.ts

part of [BS-1581](https://linear.app/affine-design/issue/BS-1581/notion-equation-导入)

feat(blocks): support to import notion html inline equation

---

packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
packages/blocks/src/_common/adapters/markdown.ts
packages/blocks/src/_common/adapters/utils.ts
packages/blocks/src/_common/transformers/index.ts
packages/blocks/src/_common/transformers/markdown.ts
packages/blocks/src/_common/transformers/middlewares.ts

[BS-1619](https://linear.app/affine-design/issue/BS-1619/embed-linked-doc-card-及-inline-doc-reference导出)

feat: add docLinkMiddleware for linked doc export

---

packages/affine/components/src/context-menu/button.ts
packages/affine/components/src/context-menu/input.ts
packages/affine/components/src/context-menu/menu-renderer.ts
packages/affine/components/src/rich-text/inline/presets/nodes/latex-node/latex-editor-menu.ts
packages/affine/components/src/rich-text/inline/presets/nodes/latex-node/latex-node.ts
packages/affine/data-view/src/widget-presets/tools/presets/table-add-row/add-row.ts
packages/affine/shared/src/theme/css-variables.ts
packages/blocks/src/bookmark-block/styles.ts
packages/blocks/src/frame-block/frame-block.ts
packages/blocks/src/latex-block/styles.ts
packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-importing-placeholder.ts
packages/blocks/src/root-block/widgets/ai-panel/components/generating-placeholder.ts

This PR combins `unsafeCSS`, `cssVar`and `cssVarV2` to `unsafeCSSVar` and `unsafeCSSVarV2`

refactor: combine unsafeCSS and cssVar

---

packages/affine/components/src/peek/controller.ts
packages/affine/components/src/peek/index.ts
packages/affine/components/src/peek/type.ts
packages/blocks/src/data-view-block/data-view-block.ts
packages/blocks/src/database-block/database-block.ts

feat(blocks): add abort controller to peekviewservice

---

packages/affine/block-surface/src/utils/mindmap/utils.ts
packages/blocks/src/root-block/edgeless/gfx-tool/default-tool.ts
packages/presets/src/__tests__/edgeless/mini-mindmap.spec.ts
tests/edgeless/mindmap.spec.ts

Fixes [BS-1519](https://linear.app/affine-design/issue/BS-1519/mind-map-的节点拖拽表现非常诡异)

fix: mind map dragging issue

---

packages/affine/data-view/src/core/common/detail/detail.ts
packages/affine/model/src/blocks/database/database-model.ts
packages/blocks/src/data-view-block/data-view-block.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/database-block/detail-panel/block-renderer.ts
packages/blocks/src/database-block/detail-panel/note-renderer.ts
packages/framework/store/src/reactive/text.ts

feat(database): title cell open center peek

---

packages/affine/shared/src/services/drag-handle-config.ts
packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
packages/blocks/src/root-block/widgets/drag-handle/helpers/preview-helper.ts
packages/blocks/src/root-block/widgets/drag-handle/watchers/edgeless-watcher.ts
packages/blocks/src/root-block/widgets/drag-handle/watchers/legacy-drag-event-watcher.ts
packages/blocks/src/root-block/widgets/drag-handle/watchers/pointer-event-watcher.ts
packages/framework/block-std/src/event/control/pointer.ts
packages/framework/block-std/src/event/control/range.ts
packages/framework/block-std/src/event/dispatcher.ts
packages/framework/block-std/src/event/state/dnd.ts
packages/framework/block-std/src/event/state/index.ts
packages/framework/global/src/types/index.ts
packages/framework/store/src/store/collection.ts
tests/attachment.spec.ts
tests/bookmark.spec.ts
tests/drag.spec.ts
tests/playwright.config.ts
tests/utils/actions/drag.ts

Migrate drag handle to new dnd strategy

feat: add new dnd

---

packages/affine/data-view/src/widget-presets/tools/presets/search/search.ts

Close [BS-1458](https://linear.app/affine-design/issue/BS-1458/database-移动端-搜索按钮可以被激活)

chore(blocks): disable database search in mobile

---

packages/blocks/src/root-block/widgets/keyboard-toolbar/index.ts
packages/framework/global/src/types/index.ts
packages/framework/store/src/store/collection.ts

Close [BS-1690](https://linear.app/affine-design/issue/BS-1690/toolbar-的-feature-flag)

chore(blocks): add feature flag for keyboard toolbar

---

packages/affine/components/src/context-menu/group.ts
packages/affine/components/src/context-menu/menu-renderer.ts
packages/affine/data-view/src/widget-presets/views-bar/views-view.ts

close: BS-1666, BS-1667, BS-1668, BS-1669

refactor(database): menu ui

---

packages/blocks/src/edgeless-text-block/commands/insert-edgeless-text.ts
packages/blocks/src/edgeless-text-block/edgeless-text-block.ts
tests/edgeless/edgeless-text.spec.ts
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-add-linked-doc.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-drag.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-init.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-link-to-card-min-width.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-link-to-card.json
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-finial.json
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-note-empty.json
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-note-not-empty.json

Close [BS-922](https://linear.app/affine-design/issue/BS-922/修改-edgeless-text-padding)
Close [BS-1633](https://linear.app/affine-design/issue/BS-1633/bug-输入连续空格不会自动增宽-edgeless-text-的宽度)

fix(edgeless): edit behavior in edgeless text

---

packages/affine/components/src/rich-text/format/delete-text.ts
packages/affine/shared/src/commands/index.ts
packages/affine/shared/src/commands/model-crud/clear-and-select-first-model.ts
packages/affine/shared/src/commands/model-crud/index.ts
packages/affine/shared/src/commands/model-crud/retain-first-model.ts
packages/blocks/src/code-block/clipboard/index.ts
packages/blocks/src/root-block/clipboard/index.ts
packages/blocks/src/root-block/clipboard/middlewares/paste.ts
packages/blocks/src/root-block/commands/index.ts
packages/blocks/src/root-block/widgets/format-bar/config.ts

This closes [BS-1613](https://linear.app/affine-design/issue/BS-1613), closes #8150

fix(blocks): del selected in paste handler not paste middleware

---

packages/affine/components/src/peek/type.ts
packages/affine/model/src/consts/doc.ts
packages/blocks/src/database-block/database-block.ts

feat(blocks): add dbid/rowid to peek view

---

packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
packages/blocks/src/_common/adapters/notion-html.ts

[BS-1580](https://linear.app/affine-design/issue/BS-1580/导入-text-block-时，会丢失-inline-element-之间的空格)

fix(blocks): notion html inline element import

---

packages/affine/components/src/rich-text/format/utils.ts
packages/affine/shared/src/commands/index.ts
packages/affine/shared/src/commands/model-crud/duplicate-selected-model.ts
packages/affine/shared/src/commands/model-crud/index.ts
packages/blocks/src/root-block/commands/index.ts
packages/blocks/src/root-block/utils/misc.ts
packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts
packages/blocks/src/root-block/widgets/keyboard-toolbar/icons.ts
packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-tool-panel.ts
packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-toolbar.ts
packages/blocks/src/root-block/widgets/keyboard-toolbar/styles.ts
packages/blocks/src/root-block/widgets/slash-menu/config.ts
packages/blocks/src/root-block/widgets/slash-menu/utils.ts

Close [BS-1620](https://linear.app/affine-design/issue/BS-1620/keyboard-toolbar-actions), [BS-1623](https://linear.app/affine-design/issue/BS-1623/移动端keyboard-tool-panel功能)

feat(blocks): impl functions of mobile keyboard toolbar

---

packages/blocks/src/_common/adapters/notion-html.ts
packages/framework/store/src/adapter/context.ts

[BS-1659](https://linear.app/affine-design/issue/BS-1659/对于空行的处理)

fix(blocks): should clean global context when leave table node

---

packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts
packages/blocks/src/root-block/widgets/keyboard-toolbar/icons.ts
packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-toolbar.ts
packages/blocks/src/root-block/widgets/keyboard-toolbar/styles.ts

Close [BS-1733](https://linear.app/affine-design/issue/BS-1733/size-of-icons-are-not-consistent-in-keyboard-toolbar)

fix(blocks): size of icons are not consistent in keyboard toolbar

---

packages/affine/shared/src/services/theme-service.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-menu.ts

Fix issue [BS-1737](https://linear.app/affine-design/issue/BS-1737).

fix(edgeless): switching shape style and color, the preview does not change in time

---

packages/affine/block-embed/src/common/embed-block-element.ts
packages/affine/components/src/caption/captioned-block-component.ts
packages/affine/components/src/caption/index.ts
packages/affine/components/src/caption/styles.ts
packages/blocks/src/bookmark-block/bookmark-block.ts

Fix issue [BS-1186](https://linear.app/affine-design/issue/BS-1186).
After:

fix(page): bookmark block selected style

---

packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
packages/blocks/src/root-block/edgeless/gfx-tool/copilot-tool.ts
packages/blocks/src/root-block/edgeless/gfx-tool/default-tool.ts
packages/blocks/src/root-block/edgeless/gfx-tool/eraser-tool.ts
packages/blocks/src/root-block/edgeless/gfx-tool/pan-tool.ts
packages/framework/block-std/src/gfx/index.ts
packages/framework/block-std/src/gfx/tool/tool-controller.ts
packages/framework/block-std/src/gfx/tool/tool.ts
packages/framework/block-std/src/scope/block-std-scope.ts
packages/framework/global/src/exceptions/code.ts
packages/framework/global/src/exceptions/index.ts
tests/edgeless/pan.spec.ts
tests/utils/actions/drag.ts

- Fixed right click error
- Make controller an optional extension
- Fixed pan tool and copilot tool

fix(edgeless): allow right click of tool controller

---

packages/blocks/src/code-block/code-block-service.ts

[AF-1608](https://linear.app/affine-design/issue/AF-1608/ai-code-block-颜色模式错误)

fix(blocks): code block should update highlight when theme changed

---

packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/attachment-block/attachment-spec.ts
packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/attachment-block/embed.ts
packages/blocks/src/attachment-block/index.ts
packages/blocks/src/attachment-block/utils.ts

Closes: [BS-1742](https://linear.app/affine-design/issue/BS-1742/对附件类型，支持自定义渲染模版)

feat: attachment embedded view supports configurable

---

packages/blocks/src/attachment-block/attachment-block.ts
packages/blocks/src/attachment-block/attachment-edgeless-block.ts
packages/blocks/src/attachment-block/components/options.ts
packages/blocks/src/attachment-block/embed.ts
packages/blocks/src/attachment-block/index.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts

Closes: [BS-1507](https://linear.app/affine-design/issue/BS-1507/attachment-card-view-添加切换为-pdf-embed-view-的功能)

feat: add view toggle menu to toolbar of attachment block

---

packages/playground/apps/_common/components/attachment-viewer-panel.ts
packages/playground/apps/_common/components/pdf/types.ts
packages/playground/apps/_common/components/pdf/worker.ts
packages/playground/apps/_common/mock-services.ts
packages/playground/apps/default/utils/editor.ts
packages/playground/apps/starter/utils/editor.ts
packages/playground/package.json
packages/playground/vite.config.ts
yarn.lock

Closes: [BS-1726](https://linear.app/affine-design/issue/BS-1726/在-blocksuite-playground-添加-pdf-viewer-panel)
https://github.com/user-attachments/assets/0de7053f-1bdd-49f4-a5d5-0d04ea6f7d0a

feat: add pdf viewer to playground

---

packages/blocks/src/root-block/edgeless/utils/common.ts

@doouding This code snippet was missing after PR #8471, which was first added in PR #8529.

fix: tidy up after multiple images uploaded

---

packages/affine/shared/src/services/edit-props-store.ts

Fix issue [BS-1546](https://linear.app/affine-design/issue/BS-1546).

fix: typeError: f._def.innerType.shape[e] is undefined

---

packages/affine/block-surface/src/surface-block.ts
packages/blocks/src/edgeless-text-block/edgeless-text-block.ts
packages/blocks/src/frame-block/frame-block.ts
packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
packages/framework/block-std/src/gfx/viewport-element.ts
packages/framework/block-std/src/view/element/gfx-block-component.ts

This continues https://github.com/toeverything/blocksuite/compare/edgeless_perf_debug?expand=1

fix: edgeless crash on mobile safari

---

packages/blocks/src/root-block/page/page-root-block.ts
packages/blocks/src/root-block/widgets/page-dragging-area/page-dragging-area.ts
tests/format-bar.spec.ts
tests/selection/native.spec.ts

Close [BS-1457](https://linear.app/affine-design/issue/BS-1457/点击侧面空白处会滚动页面)

fix: improve drag area

---

packages/affine/data-view/src/core/sort/eval.ts

fix(database): sorting of checkbox

---

packages/affine/data-view/src/core/component/tags/multi-tag-select.ts

fix(database): can't create tag by clicking

---

packages/blocks/src/database-block/components/title/index.ts

fix(database): textarea of the title has unexpected line breaks

---

packages/affine/components/src/context-menu/menu-renderer.ts
packages/affine/data-view/src/core/common/properties.ts
packages/affine/data-view/src/widget-presets/quick-setting-bar/sort/root-panel.ts
packages/affine/data-view/src/widget-presets/tools/presets/search/search.ts
packages/affine/data-view/src/widget-presets/tools/presets/view-options/view-options.ts

fix(database): toolbar icon color

---

packages/affine/data-view/src/property-presets/number/cell-renderer.ts

fix(database): number overflow

---

packages/affine/data-view/src/core/filter/literal/define.ts

feat(database): add placeholder for filter

---

packages/blocks/src/database-block/properties/title/text.ts

fix(database): support for pasting linked doc into title cell

---

packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts

Fix issue [BS-1375](https://linear.app/affine-design/issue/BS-1375).

fix: the shape will turn black for a moment when dragging from the toolbar

---

packages/affine/block-embed/src/embed-linked-doc-block/embed-linked-doc-block.ts
packages/affine/block-embed/src/embed-linked-doc-block/index.ts
packages/affine/block-embed/src/embed-linked-doc-block/utils.ts
packages/affine/components/package.json
packages/affine/components/src/rich-text/inline/presets/nodes/index.ts
packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-node.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-popup.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/utils.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
yarn.lock

Closes: [BS-1780](https://linear.app/affine-design/issue/BS-1780/添加了mode-参数后为什么linked-doc不能embed了？)

fix: unable to switch to embed view when other pages link with mode

---

packages/affine/data-view/src/core/group-by/default.ts
packages/affine/data-view/src/core/property/types.ts
packages/affine/data-view/src/core/sort/eval.ts
packages/affine/data-view/src/core/statistics/any.ts
packages/affine/data-view/src/core/statistics/types.ts
packages/affine/data-view/src/core/view-manager/cell.ts
packages/affine/data-view/src/core/view-manager/single-view.ts
packages/affine/data-view/src/property-presets/checkbox/define.ts
packages/affine/data-view/src/property-presets/date/define.ts
packages/affine/data-view/src/property-presets/image/define.ts
packages/affine/data-view/src/property-presets/multi-select/define.ts
packages/affine/data-view/src/property-presets/number/define.ts
packages/affine/data-view/src/property-presets/progress/define.ts
packages/affine/data-view/src/property-presets/select/define.ts
packages/affine/data-view/src/property-presets/text/define.ts
packages/affine/data-view/src/view-presets/kanban/define.ts
packages/affine/data-view/src/view-presets/kanban/kanban-view-manager.ts
packages/affine/data-view/src/view-presets/kanban/kanban-view.ts
packages/affine/data-view/src/view-presets/table/stats/column-stats-column.ts
packages/affine/data-view/src/view-presets/table/table-view-manager.ts
packages/affine/data-view/src/view-presets/table/table-view.ts
packages/blocks/src/database-block/data-source.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/database-block/properties/link/define.ts
packages/blocks/src/database-block/properties/rich-text/define.ts
packages/blocks/src/database-block/properties/title/define.ts
packages/blocks/src/database-block/utils/title-doc.ts

feat(database): support sorting for linked doc

---

packages/blocks/src/root-block/widgets/drag-handle/watchers/legacy-drag-event-watcher.ts

Close [BS-1588](https://linear.app/affine-design/issue/BS-1588/editor-拖动的时候会触发插入的-ui)

chore(blocks): disable dragging in mobile

---

packages/affine/block-list/src/list-block.ts
packages/affine/block-paragraph/src/paragraph-block.ts
packages/blocks/src/edgeless-text-block/edgeless-text-block.ts
tests/edgeless/align.spec.ts
tests/edgeless/edgeless-text.spec.ts
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-add-linked-doc.json
tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-init.json
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-finial.json
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-note-empty.json
tests/snapshots/edgeless/edgeless-text.spec.ts/press-backspace-at-the-start-of-first-line-when-edgeless-text-exist-note-not-empty.json

Close [BS-1811](https://linear.app/affine-design/issue/BS-1811/edgeless-text-修改垂直padding或行高)

fix(edgeless): disable list and paragraph padding in edgeless text

---

packages/blocks/src/database-block/properties/title/define.ts

fix(database): root block might not exist in AFFiNE

---

packages/framework/inline/src/components/v-line.ts
packages/framework/inline/src/services/render.ts

Close [BS-1735](https://linear.app/affine-design/issue/BS-1735/空paragraph双击会进入一个奇怪的状态，打字打不了)
Close [BS-1807](https://linear.app/affine-design/issue/BS-1807/code-block-复制粘贴错误)

fix(inline): triple click in v-line

---

packages/affine/block-surface/src/index.ts
packages/affine/block-surface/src/utils/mindmap/layout.ts
packages/affine/block-surface/src/utils/mindmap/utils.ts
packages/affine/model/src/elements/mindmap/mindmap.ts
packages/affine/model/src/elements/mindmap/style.ts
packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
packages/blocks/src/root-block/edgeless/gfx-tool/default-tool-ext/mind-map-ext.ts
packages/framework/block-std/src/gfx/surface/element-model.ts

- Fixed mind map node text
- Stash mind map tree before do the mind map layout to prevent frequently write into yjs
- Stash mind map tree when enter the editing mode

fix: mind map text layout

---

packages/affine/shared/src/utils/model/checker.ts
packages/blocks/src/_common/configs/quick-action/config.ts
packages/blocks/src/_common/utils/render-linked-doc.ts
packages/blocks/src/root-block/clipboard/middlewares/copy.ts
packages/blocks/src/root-block/keyboard/keyboard-manager.ts
packages/blocks/src/root-block/widgets/format-bar/config.ts
packages/framework/block-std/src/clipboard/index.ts
packages/framework/store/src/store/doc/doc.ts
tests/snapshots/format-bar.spec.ts/create-linked-doc-from-block-selection-with-format-bar.json

fix(database): use copy logic when creating a linked doc

---

packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts

Close [BS-1856](https://linear.app/affine-design/issue/BS-1856/editor-toolbar-的-issue-处理)

chore(blocks): adjust and remove some actions from keyboard-toolbar

---

packages/blocks/src/_common/components/button.ts
packages/blocks/src/root-block/widgets/linked-doc/config.ts
packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
packages/blocks/src/root-block/widgets/linked-doc/styles.ts

fix(blocks): update at menu popover styles

---

packages/affine/block-embed/src/embed-figma-block/embed-figma-block.ts
packages/affine/block-embed/src/embed-html-block/embed-html-block.ts
packages/affine/block-embed/src/embed-loom-block/embed-loom-block.ts
packages/affine/block-embed/src/embed-youtube-block/embed-youtube-block.ts
packages/blocks/src/image-block/components/page-image-block.ts
packages/blocks/src/image-block/image-edgeless-block.ts
packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts

Close [BS-1640](https://linear.app/affine-design/issue/BS-1640/image-标签加上-lazy-属性)

feat(blocks): add lazy loadding to image and iframe

---

packages/blocks/src/database-block/properties/link/cell-renderer.ts
tests/database/column.spec.ts

refactor(database): link cell icon

---

packages/affine/data-view/src/core/property/types.ts
packages/affine/data-view/src/property-presets/checkbox/cell-renderer.ts
packages/affine/data-view/src/property-presets/checkbox/define.ts
packages/affine/data-view/src/view-presets/table/cell.ts
packages/affine/data-view/src/view-presets/table/consts.ts
packages/affine/data-view/src/view-presets/table/header/styles.ts
packages/affine/data-view/src/view-presets/table/header/vertical-indicator.ts
packages/affine/data-view/src/view-presets/table/row/row.ts
packages/affine/data-view/src/view-presets/table/stats/column-stats-column.ts
packages/affine/data-view/src/view-presets/table/table-view-manager.ts

refactor(database): table ui

---

packages/blocks/src/database-block/components/title/index.ts

fix(database): update title on composition end

---

packages/affine/block-embed/package.json
packages/affine/block-list/package.json
packages/affine/block-paragraph/package.json
packages/affine/block-surface/package.json
packages/affine/components/package.json
packages/affine/data-view/package.json
packages/affine/shared/package.json
packages/affine/widget-scroll-anchoring/package.json
packages/blocks/package.json
packages/presets/package.json
yarn.lock

should resolve the cssVar2 type issue

chore(blocks): bump theme

---

packages/affine/components/src/context-menu/menu-renderer.ts
packages/affine/data-view/src/core/filter/literal/define.ts
packages/affine/data-view/src/widget-presets/quick-setting-bar/filter/condition-view.ts
packages/affine/data-view/src/widget-presets/tools/presets/filter/filter.ts
packages/affine/data-view/src/widget-presets/tools/presets/search/search.ts
packages/affine/data-view/src/widget-presets/tools/presets/sort/sort.ts
packages/affine/data-view/src/widget-presets/tools/presets/view-options/view-options.ts
packages/affine/data-view/src/widget-presets/tools/tools-view.ts
packages/affine/data-view/src/widget-presets/views-bar/views-view.ts

refactor(database): add reference counting to the popup target

---

packages/affine/block-surface/src/managers/connector-manager.ts

Closes: [BS-1954](https://linear.app/affine-design/issue/BS-1954/blocksuiteerror-val-does-not-exist)

fix(edgeless): connector endpoint may be null

---

packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
packages/blocks/src/_common/adapters/notion-html.ts

[BS-1860](https://linear.app/affine-design/issue/BS-1860/notion-zip-import-failure)

fix(blocks): notion html import nested list with nested paragraph

---

packages/affine/data-view/src/view-presets/table/pc/menu.ts
packages/affine/data-view/src/view-presets/table/pc/row/row.ts

fix(database): row selection is incorrect when clicking the row options button

---

packages/blocks/src/root-block/edgeless/components/color-picker/styles.ts

Closes: [BS-1968](https://linear.app/affine-design/issue/BS-1968/[ui]-color-picker-%E8%BE%93%E5%85%A5%E6%A1%86%E9%A2%9C%E8%89%B2%E5%BA%94%E8%AF%A5%E4%B8%BA%E7%99%BD%E8%89%B2%EF%BC%8C%E7%99%BE%E5%88%86%E5%8F%B7%E9%81%AE%E6%8C%A1)

fix: background color and width of input in color picker

---

packages/affine/components/src/peek/type.ts
packages/blocks/src/database-block/database-block.ts

fix(blocks): peek db doc should also pass the dbs doc id

---

packages/blocks/src/effects.ts
packages/blocks/src/root-block/widgets/element-toolbar/add-frame-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/add-group-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-image-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
packages/blocks/src/root-block/widgets/element-toolbar/effects.ts
packages/blocks/src/root-block/widgets/element-toolbar/index.ts
packages/blocks/src/root-block/widgets/element-toolbar/more-menu/button.ts
packages/blocks/src/root-block/widgets/element-toolbar/release-from-group-button.ts

This PR moves all `edgeless element toolbar` related side effects into a separate file.

refactor(edgeless): extract side effects of edgeless element toolbar

---

packages/affine/data-view/src/widget-presets/views-bar/index.ts
packages/affine/data-view/src/widget-presets/views-bar/views-view.ts
packages/blocks/src/database-block/database-block.ts
packages/blocks/src/database-block/utils/current-view.ts

feat(database): store current view id in local-storage

---

packages/blocks/src/database-block/components/title/index.ts

fix(database): multiple spaces in the title are displayed as a single space

---

packages/affine/block-list/src/adapters/index.ts
packages/affine/block-list/src/adapters/plain-text.ts
packages/affine/block-list/src/index.ts
packages/affine/block-paragraph/src/adapters/index.ts
packages/affine/block-paragraph/src/adapters/plain-text.ts
packages/affine/block-paragraph/src/index.ts
packages/affine/shared/src/adapters/index.ts
packages/affine/shared/src/adapters/plain-text/block-adapter.ts
packages/affine/shared/src/adapters/plain-text/delta-converter.ts
packages/affine/shared/src/adapters/plain-text/index.ts
packages/affine/shared/src/adapters/plain-text/type.ts
packages/affine/shared/src/adapters/type.ts
packages/blocks/src/__tests__/adapters/plain-text.unit.spec.ts
packages/blocks/src/_common/adapters/extension.ts
packages/blocks/src/_common/adapters/index.ts
packages/blocks/src/_common/adapters/markdown/markdown.ts
packages/blocks/src/_common/adapters/plain-text/block-matcher.ts
packages/blocks/src/_common/adapters/plain-text/delta-converter/inline-delta.ts
packages/blocks/src/_common/adapters/plain-text/plain-text.ts
packages/blocks/src/_specs/common.ts
packages/blocks/src/code-block/adapters/plain-text.ts
packages/blocks/src/divider-block/adapters/plain-text.ts
packages/playground/apps/_common/components/debug-menu.ts

[BS-1855](https://linear.app/affine-design/issue/BS-1855/migrate-plain-text-adapter)

refactor: migrate plain text adapter to extension

---

packages/blocks/src/__tests__/adapters/plain-text.unit.spec.ts
packages/blocks/src/_common/adapters/plain-text/block-matcher.ts
packages/blocks/src/_common/adapters/plain-text/delta-converter/inline-delta.ts
packages/blocks/src/latex-block/adapters/index.ts
packages/blocks/src/latex-block/adapters/plain-text.ts
packages/blocks/src/latex-block/index.ts

[BS-2038](https://linear.app/affine-design/issue/BS-2038/补齐-latex-plain-text-adapter)

feat(blocks): add plain text block adapter for latex

---

packages/affine/block-surface/src/renderer/elements/mindmap.ts
packages/affine/block-surface/src/renderer/overlay.ts
packages/affine/block-surface/src/utils/mindmap/layout.ts
packages/affine/block-surface/src/utils/mindmap/utils.ts
packages/affine/model/src/elements/mindmap/mindmap.ts
packages/affine/model/src/elements/mindmap/utils.ts
packages/blocks/src/_specs/preset/edgeless-specs.ts
packages/blocks/src/root-block/edgeless/gfx-tool/default-tool-ext/ext.ts
packages/blocks/src/root-block/edgeless/gfx-tool/default-tool-ext/mind-map-ext/drag-utils.ts
packages/blocks/src/root-block/edgeless/gfx-tool/default-tool-ext/mind-map-ext/indicator-overlay.ts
packages/blocks/src/root-block/edgeless/gfx-tool/default-tool-ext/mind-map-ext/mind-map-ext.ts
packages/blocks/src/root-block/edgeless/gfx-tool/default-tool.ts
packages/framework/sync/src/doc/impl/broadcast.ts
packages/presets/src/__tests__/edgeless/group.spec.ts

- Fix the issue that mind map node may have circular reference
- Rewrite mind map drag logic, calculate the draggable area only when drag start

fix: mind map circular reference issue & can't not drag existing mind map

---

packages/blocks/src/_common/components/ai-item/ai-item-list.ts
packages/blocks/src/_common/components/ai-item/ai-item.ts
packages/blocks/src/_common/components/ai-item/ai-sub-item-list.ts
packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
packages/blocks/src/root-block/widgets/ai-panel/type.ts
packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts
packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts

Ask AI on edgeless mode:
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/1218afba-466f-4570-afd4-679b6b09cc8d.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/1218afba-466f-4570-afd4-679b6b09cc8d.mov">录屏2024-12-06 09.54.52.mov</video>
Ask AI on page mode:
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/58d19705-f646-4957-8628-15845b47222b.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/58d19705-f646-4957-8628-15845b47222b.mov">录屏2024-12-06 09.52.51.mov</video>

feat(blocks): show input directly after the user clicks ask ai

---

packages/blocks/src/root-block/widgets/linked-doc/styles.ts

fix(blocks): linked popover style issue

---

packages/playground/apps/_common/components/collab-debug-menu.ts
packages/playground/apps/_common/components/docs-panel.ts
packages/playground/apps/_common/components/starter-debug-menu.ts

https://github.com/user-attachments/assets/cbcaf7c3-052a-4595-8a40-709b0d869375

feat(playground): outside click to close docs panel

---

packages/blocks/src/_specs/preset/mobile-patch.ts

This PR fixed that page root widgets were added to edgeless mode incorrectly in mobile patch extension.

fix(presets): incorrectly adding page root widgets to edgeless

---

packages/affine/block-embed/src/embed-linked-doc-block/embed-linked-doc-block.ts

Closes: [BS-2069](https://linear.app/affine-design/issue/BS-2069/card-view-的-style-设置失效了)

fix: switch card view style does not work

---

packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/link-popup.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-alias-popup.ts
packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-popup.ts
packages/affine/components/src/toolbar/menu-button.ts
packages/affine/shared/src/services/telemetry-service/index.ts
packages/affine/shared/src/services/telemetry-service/link.ts
packages/affine/shared/src/services/telemetry-service/telemetry-service.ts
packages/blocks/src/_common/components/embed-card/modal/embed-card-edit-modal.ts
packages/blocks/src/root-block/edgeless/components/color-picker/button.ts
packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts

Closes: [BS-2052](https://linear.app/affine-design/issue/BS-2052/增加埋点)

feat(blocks): add event tracking for linked doc

---

packages/blocks/src/__tests__/adapters/html.unit.spec.ts
packages/blocks/src/_common/adapters/html-adapter/block-matcher.ts
packages/blocks/src/database-block/adapters/html.ts

[BS-2057](https://linear.app/affine-design/issue/BS-2057/补齐-database-html-block-adapter)

feat(blocks): support database html block adapter

---

packages/affine/block-embed/src/common/adapters/utils.ts
packages/affine/block-embed/src/embed-linked-doc-block/adapters/html.ts
packages/affine/block-embed/src/embed-linked-doc-block/adapters/index.ts
packages/affine/block-embed/src/embed-linked-doc-block/adapters/markdown.ts
packages/affine/block-embed/src/embed-linked-doc-block/adapters/plain-text.ts
packages/affine/block-embed/src/embed-synced-doc-block/adapters/html.ts
packages/affine/block-embed/src/embed-synced-doc-block/adapters/index.ts
packages/affine/block-embed/src/embed-synced-doc-block/adapters/markdown.ts
packages/affine/block-embed/src/index.ts
packages/blocks/src/__tests__/adapters/html.unit.spec.ts
packages/blocks/src/_common/adapters/html-adapter/block-matcher.ts
packages/blocks/src/_common/adapters/html-adapter/delta-converter/inline-delta.ts
packages/blocks/src/_common/adapters/markdown/block-matcher.ts
packages/blocks/src/_common/adapters/markdown/delta-converter/inline-delta.ts
packages/blocks/src/_common/adapters/plain-text/delta-converter/inline-delta.ts
packages/blocks/src/root-block/adapters/html.ts

[BS-2063](https://linear.app/affine-design/issue/BS-2063/补齐-embed-linked-and-synced-doc-html-block-adapter)

feat(blocks): support embed linked doc and synced doc html block adapter

---

packages/affine/components/src/context-menu/menu-renderer.ts

fix(database): adjust padding for mobile menu to accommodate safe area insets

---

packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
packages/blocks/src/root-block/widgets/element-toolbar/lock-button.ts
tests/edgeless/lock.spec.ts
tests/utils/actions/edgeless.ts

Close [BS-1994](https://linear.app/affine-design/issue/BS-1994/锁：测试)

test(edgeless): edgeless element lock feature tests

---

packages/affine/block-embed/src/embed-synced-doc-block/embed-synced-doc-block.ts
packages/affine/block-embed/src/embed-synced-doc-block/styles.ts

feat(blocks): responsive ui for embed doc

---

packages/affine/shared/src/services/telemetry-service/telemetry-service.ts
packages/affine/shared/src/services/telemetry-service/types.ts
packages/blocks/src/root-block/widgets/element-toolbar/lock-button.ts

Close [BS-2002](https://linear.app/affine-design/issue/BS-2002/锁：埋点)

chore(edgeless): telemetry for edgeless lock feature

---

packages/affine/data-view/src/core/detail/detail.ts

fix(database): adjust detail panel layout for better responsiveness

---

packages/blocks/src/root-block/widgets/element-toolbar/more-menu/config.ts

Close [BS-1995](https://linear.app/affine-design/issue/BS-1995/单独删除frame的按钮，以及调整frame层级的入口)

fix(edgeless): add index reorder buttong for frame block

---

packages/framework/block-std/src/event/control/pointer.ts

fix(std): edge case on pointer controller

---

packages/blocks/src/image-block/image-block.ts

Close [BS-1959](https://linear.app/affine-design/issue/BS-1959/image-block-禁止打开)

chore(blocks): disable image peekview on mobile

---

packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
packages/blocks/src/root-block/widgets/linked-doc/styles.ts

fix(blocks): at menu styles

---

packages/framework/block-std/src/event/control/pointer.ts

This PR fixed that try get `EditorHost` before rendering in the rect polling of pointer controller.
```ts
// before eidtor rendering, get `EditorHost` will throw a error
class BlockStdScop {
constructor(options: BlockStdOptions) {
this._getHost = () => {
throw new BlockSuiteError(
ErrorCode.ValueNotExists,
'Host is not ready to use, the `render` method should be called first'
);
};
// ...
}
// so this line will throw a error
if (!this._dispatcher.host) return;
```

fix(std): undefined editor during rect polling on mobile

---

packages/blocks/src/root-block/widgets/drag-handle/middleware/copy-embed-doc.ts
packages/blocks/src/root-block/widgets/drag-handle/watchers/drag-event-watcher.ts

Closes: [BS-2013](https://linear.app/affine-design/issue/BS-2013/相同yuan素（主要是-linked-doc）拖拽后变成移动)

fix: should copy embed doc when dnd

---

packages/blocks/src/root-block/widgets/drag-handle/middleware/surface-ref-to-embed.ts
packages/blocks/src/root-block/widgets/drag-handle/watchers/drag-event-watcher.ts

Closes: [BS-2016](https://linear.app/affine-design/issue/BS-2016/[page-to-page]inserted-frame-或者-group，跨文档拖拽应该是插入-link-to-block)

feat: should insert bookmark when drop frame and group

---

packages/blocks/src/root-block/widgets/drag-handle/watchers/drag-event-watcher.ts

Closes: [BS-2011](https://linear.app/affine-design/issue/BS-2011/白板上-note-的拖拽-indicator-不跟随)

fix: note dnd preview

---

packages/blocks/src/_common/adapters/html-adapter/delta-converter/html-inline.ts
packages/blocks/src/_common/transformers/html.ts
packages/blocks/src/_common/transformers/markdown.ts
packages/blocks/src/_common/transformers/middlewares.ts

fix(blocks): doc link import/export handling

---

packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts

Fix issue [BS-2105](https://linear.app/affine-design/issue/BS-2105).

fix(blocks): focus ai input after position updated

---

packages/blocks/src/database-block/data-source.ts
packages/blocks/src/database-block/database-block.ts

Close [BS-1931](https://linear.app/affine-design/issue/BS-1931/database-%E7%BC%96%E8%BE%91%E7%A6%81%E7%94%A8)

chore(blocks): set readonly to database on mobile

---

packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts

Close [BS-2120](https://linear.app/affine-design/issue/BS-2120/toolbar-添加一个图片附件上传的入口)

chore(blocks): add image file upload entries to keyboard toolbar

---

packages/blocks/src/root-block/clipboard/index.ts
packages/blocks/src/root-block/clipboard/middlewares/paste.ts
tests/clipboard/clipboard.spec.ts

Closes: [BS-2001](https://linear.app/affine-design/issue/BS-2001/希望添加选中文字后粘贴链接的能力)
<a href="https://app.graphite.dev/media/video/8ypiIKZXudF5a0tIgIzf/49b4497b-2df3-42db-bfa0-a82d0e26093e.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/8ypiIKZXudF5a0tIgIzf/49b4497b-2df3-42db-bfa0-a82d0e26093e.mov">Screen Recording 2024-12-17 at 16.59.57.mov</video>

feat(blocks): supports pasting a URL from clipboard to automatically create a link from selection

---

packages/framework/block-std/src/gfx/viewport.ts

See the `get offsetWidth` row in following recording on low end device:

perf(std): add cache for gfx viewport

---

packages/blocks/src/root-block/widgets/drag-handle/watchers/drag-event-watcher.ts

Closes: [BS-2167](https://linear.app/affine-design/issue/BS-2167/从侧边栏上往白板上拖拽-doc，无法插入到白板上（除了-note）)

fix: drag doc from affine to edgeless

---

packages/affine/shared/src/services/telemetry-service/telemetry-service.ts
packages/affine/shared/src/services/telemetry-service/types.ts
packages/blocks/src/attachment-block/utils.ts
packages/blocks/src/root-block/edgeless/utils/common.ts

Part of: [AF-1678](https://linear.app/affine-design/issue/AF-1678/添加埋点)

chore(blocks): add event tracking for attachment upload

---

packages/affine/components/src/context-menu/menu-renderer.ts
packages/affine/components/src/context-menu/menu.ts

feat(database): add global menu open listener

---

packages/affine/data-view/src/core/group-by/define.ts
packages/affine/data-view/src/core/group-by/renderer/string-group.ts
packages/affine/data-view/src/core/group-by/trait.ts
packages/affine/data-view/src/core/group-by/types.ts
packages/affine/data-view/src/core/view-manager/single-view.ts

fix(database): string group name update

---

packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts
packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
packages/blocks/src/root-block/widgets/linked-doc/mobile-linked-doc-menu.ts
packages/blocks/src/root-block/widgets/linked-doc/styles.ts
packages/blocks/src/root-block/widgets/linked-doc/utils.ts

Close [BS-2169](https://linear.app/affine-design/issue/BS-2169/新的-menu-不支持移动端)

fix(blocks): mobile at menu rendering

---

packages/playground/tsconfig.json
packages/playground/vite.config.ts
packages/tests-legacy/e2e/slash-menu.spec.ts
packages/tsconfig.json

This PR was created automatically by GitHub Actions to sync affine/blocksuite to blocksuite/packages.

chore: sync affine blocksuite to packages
