- packages/blocks/src/root-block/edgeless/components/panel/size-panel.ts
> fix(edgeless): size panel width

- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
The tagClicked slot is missing on the edgeless page service. An error is thrown when trying to listen to that slot in AFFiNE.
> fix: add missing slot in edgeless service

- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
When editor unmonted, the return value of `listenToThemeChange` is undefined.
> fix: check disposable if exists

- packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
- packages/blocks/src/note-block/commands/focus-block-end.ts
- packages/blocks/src/note-block/commands/focus-block-start.ts
- packages/blocks/src/note-block/keymap-controller.ts
- packages/blocks/src/note-block/note-service.ts
- tests/paragraph.spec.ts
- tests/selection/native.spec.ts
> feat(blocks): optimize the experience of switching selected blocks using ArrowUp and ArrowDown

- packages/blocks/src/bookmark-block/components/bookmark-card.ts
> fix: only display hostname in bookmark

- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/utils/editor.ts
- packages/presets/src/editors/editor-container.ts
The default demo's 'View in Edgeless' did not work because of two reasons:
1. The editorContainer's "mode" property lacked reactive to editorModeSwitch's emit.
2. The top-right quickEdgelessMenu's "mode" property lacked reactive to editorModeSwitch's emit. (for back to page mode)
So I fill in these two lacks.
Besides, "editorContainer's mode property's reactivity to mode change in PageRootService" is an inherent behavoir with regard to the stable PageRootService, so I move this realization into the EditorContainer class to avoid redundant outer configs.
before(default demo):
https://github.com/toeverything/blocksuite/assets/6285483/0f1526c3-80e5-41a0-a2ca-8ee5b1883437
after(default demo):
https://github.com/toeverything/blocksuite/assets/6285483/087ffc19-0c5b-4c50-8623-55e0c22b1c84 …
> fix: jumping to edgeless-editor by "View in Edgeless" in the default demo

- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/services/tools-manager.ts
close #6498 
close [BS-203](https://linear.app/affine-design/issue/BS-203/windows-client-edgeless-%E6%94%AF%E6%8C%81-shift-%E6%BB%9A%E5%8A%A8-=-%E6%A8%AA%E5%90%91%E6%BB%9A%E5%8A%A8)
> fix(edgeless): horizontal pan with mouse under the windows system

- packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
- packages/blocks/src/_common/components/embed-card/embed-card-toolbar.ts
- packages/blocks/src/root-block/edgeless/components/component-toolbar/change-attachment-button.ts
- packages/blocks/src/root-block/edgeless/components/component-toolbar/change-embed-card-button.ts
- packages/blocks/src/root-block/edgeless/components/component-toolbar/change-image-button.ts
- packages/blocks/src/root-block/edgeless/components/component-toolbar/more-button.ts
- packages/blocks/src/root-block/edgeless/utils/query.ts
[AFF-747](https://linear.app/affine-design/issue/AFF-747/remove-the-reload-button-of-toolbar-in-both-card-view-and-embed-view)
Remove synced/linked doc reload button.
Move embedded link blocks reload button to more button popup menu.
> feat: move embed reload button

- packages/playground/apps/_common/components/docs-panel.ts
Modification(destination):
1. Click deleteDoc button will not trigger the click callback for doc-switching.
2. Switch to a default doc only after deleteing the editor's current doc.
3. Do not show deleteDoc button when there's only one doc left.
before:
https://github.com/toeverything/blocksuite/assets/6285483/9aa756b1-3b8a-438d-8e7e-3a2389712638
after:
https://github.com/toeverything/blocksuite/assets/6285483/9a67cd9c-13b0-4f41-ad62-9ab94d1c47c8
> fix: deletion behavior in DocsPanel component

- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
- Bounds of shapes copied should have rotation applied
- Background of copied image  should be transparent
> fix(edgeless): copyAsPng on shape with rotation has cutoff edges

- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
https://github.com/toeverything/blocksuite/assets/27926/d39f883f-7345-4aa0-a3da-538a21063a04
> fix(edgeless): connector missing c and x shortcuts

- packages/blocks/src/_common/components/rich-text/rich-text.ts
- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/common/datasource/block-renderer.ts
- packages/blocks/src/database-block/common/header/title.ts
- packages/framework/inline/src/inline-editor.ts
Avoid unnecessary contenteditable assignments
before:
after:
> fix(database): slow first rendering of the Database Block

- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/common/header-area/text.ts
> fix(database): group as Database cannot keep inbound link

- packages/blocks/src/_specs/_specs.ts
- packages/blocks/src/database-block/common/base-data-view.ts
- packages/blocks/src/database-block/common/data-view.ts
- packages/blocks/src/database-block/common/detail/field.ts
- packages/blocks/src/database-block/common/detail/layout.ts
- packages/blocks/src/database-block/data-view.ts
- packages/blocks/src/database-block/database-block.ts
- packages/blocks/src/database-block/kanban/card.ts
- packages/blocks/src/database-block/kanban/group.ts
- packages/blocks/src/database-block/kanban/kanban-view.ts
- packages/blocks/src/database-block/kanban/menu.ts
- packages/blocks/src/database-block/table/components/menu.ts
- packages/blocks/src/database-block/table/components/row.ts
- packages/blocks/src/database-block/table/controller/hotkeys.ts
- packages/blocks/src/database-block/table/group.ts
- packages/blocks/src/database-block/table/table-view.ts
- packages/blocks/src/root-block/types.ts
- packages/blocks/src/root-block/widgets/index.ts
- packages/blocks/src/root-block/widgets/inner-modal/inner-modal.ts
close: https://github.com/toeverything/blocksuite/issues/6337
close: AFF-732
close: BS-146, BS-207
By default it will fit over the entire `document.body`.
Can be overridden externally.
example:
```ts
{
schema: RootBlockSchema,
service: PageRootService,
view: {
component: literal`affine-page-root`,
widgets: {
[AFFINE_INNER_MODAL_WIDGET]: literal`${unsafeStatic(AFFINE_INNER_MODAL_WIDGET)}`,
},
},
setup: function(slots) {
slots.widgetConnected.on(({ component }) => {
if (component instanceof AffineInnerModalWidget) {
component.setTarget(() => {
return document.body.querySelector('.xxx') ?? document.body;
});
}
});
},
}
```
> fix(database): incorrect position of detail panel

- packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
Related to #6579 
https://github.com/toeverything/blocksuite/assets/27926/8f121f67-bbf9-464d-8495-9f6ffd544f83
> fix(edgeless): auto complete panel position when zooming in and out

- .github/CLA.md
- packages/blocks/src/root-block/edgeless/utils/tool-overlay.ts
**Problem**
Now, when you select a `triangle`, a `rect` is drawn under the cursor
> fix(edgeless): general shape for triangle

- packages/presets/package.json
- packages/presets/src/copilot-client.ts
- packages/presets/src/index.ts
- pnpm-lock.yaml
Doc: https://app.affine.pro/workspace/af3478a2-9c9c-4d16-864d-bffa1eb10eb6/YFIow1zJM_zmIQaRcGHiz
Provide Client to communicate with AI backend for debugging. These code would be migrated into Affine side or removed.
Example
```ts
const copilotClient = new CopilotClient();
const sessionId = await copilotClient.createSession({
workspaceId: 'starter',
docId: '1',
action: false,
model: 'Gpt4TurboPreview',
promptName: '',
});
await copilotClient.textToText('hello', sessionId);
await copilotClient.textToText('tell me a joke', sessionId);
await copilotClient.textToText('tell me another joke', sessionId);
await copilotClient.getAnonymousHistories('starter');
```
cc/ @Flrande  @doouding
> feat: copilot client

- packages/blocks/src/root-block/edgeless/components/component-toolbar/component-toolbar.ts
- packages/blocks/src/root-block/edgeless/components/connector/connector-handle.ts
- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- tests/edgeless/selection.spec.ts
> fix(edgeless): selection when all elements are connectors

- packages/blocks/src/root-block/edgeless/components/component-toolbar/change-connector-button.ts
`connector component toolbar` should follow the order on the `edgeless-toolbar`:
> fix(edgeless): connector modes display order issue

- packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
https://github.com/toeverything/blocksuite/assets/123532141/b507b3a2-32b9-49de-a228-d63f22b80edb
It was using window.length instead of inlineRange.length
> fix(database): soft enter removes next character

- .github/CLA.md
- packages/blocks/src/root-block/edgeless/components/panel/font-family-panel.ts
- packages/blocks/src/root-block/edgeless/components/panel/font-weight-and-style-panel.ts
- packages/blocks/src/surface-block/consts.ts
- packages/blocks/src/surface-block/elements/shape/types.ts
- packages/blocks/src/surface-block/elements/text/utils.ts
- packages/blocks/src/surface-block/utils/font.ts
**Basic moments**
- Created `CanvasTextFontFamiliesNames` for maps each font family to its name for easier reference.
- Changing the rendering of the buttons to use the `options` property, which contains all available font families, instead of hardcoded values.
These changes improve code readability and maintainability by reducing repetition and centralizing font family names in one place.
> feat(edgeless): font family panel refactoring

- packages/blocks/src/surface-block/managers/connector-manager.ts
- packages/blocks/src/surface-block/utils/curve.ts
- tests/edgeless/clipboard.spec.ts
Curve cannot be selected in the area outside the current dotted box.
https://github.com/toeverything/blocksuite/assets/27926/12b2cf69-1efd-4c8b-bf5f-9f08df0c2a82
> fix(edgeless): curve path bounding box

- packages/blocks/src/paragraph-block/paragraph-block.ts
IME sometimes break because of placeholder (not reproduced in firefox)
import snapshot: 
[doc_home.bs (1).zip](https://github.com/toeverything/blocksuite/files/14941593/doc_home.bs.1.zip)
before:
https://github.com/toeverything/blocksuite/assets/50035259/bf255c9a-437d-4801-8f04-acaadd8d02e7
after:
https://github.com/toeverything/blocksuite/assets/50035259/2171375d-7475-4437-a64b-92f1af23ad24
> fix(blocks): the IME sometimes break because of placeholder

- packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
> fix(blocks): copilot panel needs to fill the width of the host

- packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
- packages/blocks/src/root-block/widgets/ai-panel/components/discard-modal.ts
- packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts
- packages/presets/src/ai/actions/edgeless-handler.ts
- packages/presets/src/ai/actions/edgeless-response.ts
When need to close the ai panel directly, call panel.hide(). 
When need to confirm with the user and do some callback processing before closing the panel, set discardCallback to the panel and call panel.discard()
> fix: edgeless copilot discard modal

- packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
> fix(blocks): should not show copilot panel when no element is selected

- packages/playground/apps/default/specs-examples/ai/provider.ts
- packages/presets/src/ai/actions/types.ts
- packages/presets/src/ai/provider.ts
- packages/presets/src/ai/slides/template.ts
abstract unsplash api through new `PhotoEngine` service.
Pending merge until we have a remote api defined in affine server @darkskygit 
https://app.graphite.dev/github/pr/toeverything/AFFiNE/6574/fix-core-provide-photoengine
> refactor(presets): add photo engine to AIProvider

- packages/blocks/src/_common/components/ai-item/types.ts
- packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
- packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
- packages/presets/src/ai/actions/edgeless-handler.ts
- packages/presets/src/ai/actions/handler.ts
- packages/presets/src/ai/ai-panel.ts
- packages/presets/src/ai/entries/edgeless/panel-config.ts
- packages/presets/src/ai/provider.ts
Added predefined `AIError` that will be throw by implementations of AIProvider's actions.
There are two types of errors for now: 
- PaymentRequiredError: reported if affine server returns 402 error
- GeneralNetworkError: all other errors
For callers of these actions, they will be required to handle these errors and render error prompt accordingly.
I have updated error handling logic & template in AIPanel in this PR.
> feat(presets): error handling

- packages/presets/src/editors/edgeless-editor.ts
> fix(blocks): page movement due to scrolling into view

- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
> fix(blocks): element toolbar should not be displayed when in copilot tool

- packages/blocks/src/_common/components/ai-item/ai-item-list.ts
- packages/blocks/src/_common/components/ai-item/styles.ts
- packages/blocks/src/index.ts
- packages/blocks/src/root-block/widgets/ai-panel/components/discard-modal.ts
- packages/blocks/src/root-block/widgets/ai-panel/components/state/answer.ts
- packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
- packages/presets/src/ai/actions/consts.ts
- packages/presets/src/ai/actions/edgeless-response.ts
- packages/presets/src/ai/ai-panel.ts
- packages/presets/src/ai/entries/edgeless/actions-config.ts
- packages/presets/src/ai/entries/edgeless/panel-config.ts
- packages/presets/src/ai/utils/editor-actions.ts
Add copy config to AIPanelAnswerConfig:
```
export interface CopyConfig {
allowed: boolean;
onCopy: () => boolean | Promise<boolean>;
}
```
When an action response can be copied, can config it in finishStateConfig, different types of actions can be configured with different copy behaviors, which need to be implemented according to the specific type:
```
finishStateConfig: {
responses: buildDefaultResponse(panel),
actions: [],
copy: {
allowed: true,
onCopy: () => {
return copyTextAnswer(panel);
},
},
},
```
For example, for rich text response, copy rich text content to clipboard:
```
export const copyTextAnswer = async (panel: AffineAIPanelWidget) => {
const host = panel.host;
if (panel.state !== 'finished' || !panel.answer) {
return false;
}
const previewDoc = await markDownToDoc(host, …
```
> feat: support copy ai answer and fix ui issues

- packages/blocks/src/list-block/list-block.ts
Fix https://github.com/toeverything/blocksuite/issues/6697
This pull request fixes the list number prefix expires by listening to the `blockUpdated` event.
https://github.com/toeverything/blocksuite/assets/18554747/ec8d6ce0-0a85-42b0-9114-081d40aebc29
- Not work when reordering blocks by drag handle
https://github.com/toeverything/blocksuite/assets/18554747/d4e659b9-f0cc-4140-b0d1-dd0633743f28
- Not work in some cases of undo/redo
https://github.com/toeverything/blocksuite/assets/18554747/3a7e08de-5450-480d-8dab-1fe19486d374
> fix(blocks): update list number prefix when updating a block

- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
- packages/blocks/src/root-block/widgets/ai-panel/components/divider.ts
- packages/blocks/src/root-block/widgets/index.ts
- packages/presets/src/ai/actions/edgeless-handler.ts
- packages/presets/src/ai/ai-panel.ts
- packages/presets/src/ai/entries/edgeless/panel-config.ts
- packages/presets/src/ai/messages/text.ts
Support auto-scroll to bottom when generating answer.
ai-answer-text element now support config maxHeight, when set maxHeight, the element will be scrollable.
```
export const createTextRenderer: (
host: EditorHost,
maxHeight?: number
) => AffineAIPanelWidgetConfig['answerRenderer'] = (host, maxHeight) => {
return (answer, state) => {
return html`<ai-answer-text
.host=${host}
.answer=${answer}
.state=${state}
.maxHeight=${maxHeight}
></ai-answer-text>`;
};
};
```
When want the element to have a maximum height and can automatically scroll to the bottom, pass in maxHeight when calling createTextRenderer. 
```
createTextRenderer(host, 320);
```
When no need the maximum height and want to render all content, do not pass in maxHeight.
```
createTextRenderer(host);
```
> fix(presets): auto scroll answer text to bottom when generating

- packages/presets/src/ai/actions/handler.ts
our used model does not support vision + text at the moment (except chat)
> fix(presets): should not send attachments when multiple blocks selected

- packages/presets/src/ai/messages/text.ts
- packages/presets/src/ai/utils/selection-utils.ts
To fix [AFF-922](https://linear.app/affine-design/issue/AFF-922/包含-database-的-ai-actions-直接显示非-database-操作内容的结果)
> fix(presets): filter out non text content in text preview

- .github/workflows/pr-title-lint.yml
This pull request fixes an issue with bash escape in the PR title linting workflow.
This PR adds an intermediate environment variable to prevent command injection and ensures the PR title is properly checked using commitlint.
Credits to @random-dudde with https://github.com/toeverything/AFFiNE/pull/6640
> fix: bash escape by ` in PR title linting

- packages/blocks/src/root-block/widgets/edgeless-copilot-panel/toolbar-entry.ts
> fix: copilot selection rect should be considered zoom

- packages/blocks/src/_common/adapters/utils.ts
If in the AFFiNE desktop client, it should be necessary to determine the domain name of the AFFiNE.
> fix(blocks): should not go proxy when it is an onsite image

- packages/blocks/src/embed-github-block/styles.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
- packages/blocks/src/root-block/widgets/slash-menu/styles.ts
> fix(blocks): github icon dark mode

- packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/framework/global/index.d.ts
- packages/framework/store/src/store/store.ts
- packages/playground/apps/default/utils/collection.ts
- packages/playground/apps/starter/utils/collection.ts
- tests/edgeless/lasso.spec.ts
- tests/edgeless/shortcut.spec.ts
Add `enable_lasso_tool` feature flag
> chore(edgeless): add lasso tool feature flag

- packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
To fix:
[AFF-927](https://linear.app/affine-design/issue/AFF-927/⌘z-撤回出现的输入框-bug)
[AFF-956](https://linear.app/affine-design/issue/AFF-956/copy-的文字不会进入-ai-input，会直接生成一个-block)
[AFF-960](https://linear.app/affine-design/issue/AFF-960/ai-panel-键盘导航导致编辑器移动)
> fix: ai panel input keyboard behavior

- packages/presets/src/ai/entries/edgeless/actions-config.ts
> fix(presets): move find actions to the last of generate group

- packages/framework/block-std/src/view/element/lit-host.ts
https://github.com/toeverything/blocksuite/blob/ddb1941db8f1d4e127a785dd833f105383df7327/packages/framework/block-std/src/event/dispatcher.ts#L319-L322
Add `tabindex = 0` to make sure `editor-host` is focused when clicking empty space in the edgeless. Otherwise, the `relatedTarget` would be an element outside the host which is not correct.
> fix: focusout event should focus at host when click empty space in edgeless

- packages/blocks/src/index.ts
- packages/presets/src/ai/actions/edgeless-handler.ts
- packages/presets/src/ai/actions/edgeless-response.ts
- packages/presets/src/ai/actions/handler.ts
- packages/presets/src/ai/entries/format-bar/config.ts
- packages/presets/src/ai/provider.ts
- packages/presets/src/ai/utils/selection-utils.ts
Added `Generate an image`, `Brainstorm ideas with mind map` and `Generate presentation` to doc mode.
When invoked in Doc mode, an event will be emitted in requestRunInEdgeless
<a href="https://app.graphite.dev/media/video/T2klNLEk0wxLh4NRDzhk/e3994078-1123-4a13-ab5b-9634ced3da6c.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/T2klNLEk0wxLh4NRDzhk/e3994078-1123-4a13-ab5b-9634ced3da6c.mp4">Kapture 2024-04-27 at 16.18.38.mp4</video>
> feat(presets): add edgeless actions to doc mode

- packages/blocks/src/database-block/data-view/column/presets/number/cell-renderer.ts
close https://github.com/toeverything/blocksuite/issues/6676
- Use browser default behavior for undo and redo for editing number cell
- Aligned numbers to the right, enhancing place value representation.
> fix(database): can't undo in number cell

- packages/blocks/src/database-block/data-view/view/presets/kanban/controller/selection.ts
https://github.com/toeverything/blocksuite/assets/123532141/583422d7-d390-435e-908b-803bd2757443
> fix(database): cant move to next kanban card if next group is empty

- packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
- packages/blocks/src/root-block/widgets/ai-panel/components/discard-modal.ts
- packages/blocks/src/root-block/widgets/ai-panel/components/state/generating.ts
- packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
To close [AFF-907](https://linear.app/affine-design/issue/AFF-907/给-ai-panel-添加-esc-键快速中止生成)
> feat: pressing escape to stop ai generating

- packages/presets/src/ai/actions/edgeless-handler.ts
- packages/presets/src/ai/entries/edgeless/actions-config.ts
Closes: [TOV-823](https://linear.app/affine-design/issue/TOV-823/explain-image持续跳error，无法成功)
> fix(presets): explain image action missing picture

- packages/blocks/src/root-block/widgets/edgeless-copilot/index.ts
- packages/presets/src/ai/actions/edgeless-handler.ts
- packages/presets/src/ai/entries/edgeless/actions-config.ts
Closes: [AFF-1008](https://linear.app/affine-design/issue/AFF-1008/图生图：当选区中没有-content-时，允许用户输入-prompt)
> fix(blocks): allow users to enter prompt words when content is missing

- .github/CLA.md
- packages/blocks/src/_common/edgeless/note/consts.ts
- packages/blocks/src/_common/utils/index.ts
- packages/blocks/src/_common/utils/zod.ts
- packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
- packages/blocks/src/surface-block/elements/shape/consts.ts
example: _packages/blocks/src/\_common/consts_:
The example shows that when creating a zod scheme, there are repetitions of values from the array. Such use leads to an unguaranteed schema change when changing the values of this array.
This can be avoided using createZodUnion utility
+simplification of the code
+ensuring an up-to-date scheme
> feat: create zod union

- packages/blocks/src/database-block/data-view/view/presets/table/controller/drag-to-fill.ts
- Dont show in the initial load
- Check if focus cell data is undefined
> fix(database): edge-cases for drag to fill

- packages/presets/src/ai/chat-panel/actions/actions-handle.ts
Fix https://linear.app/affine-design/issue/AFF-1001/create-as-a-page-之后，未识别-markdown-格式
> fix: wait new host to insert markdown

- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
Close issue #6963
Shrink the maximum boundary of `element-toolbar-widget` to above the `edgeless-toolbar`.
> fix(edgeless): improve element toolbar bottom position

- package.json
- packages/blocks/src/_specs/spec-builder.ts
- packages/blocks/src/_specs/spec-provider.ts
- packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
- packages/blocks/src/surface-ref-block/portal/note.ts
- packages/framework/global/src/exceptions/code.ts
- packages/framework/store/src/schema/error.ts
Spec builder is a feature for users to build specs easier.
```ts
const specInstanceA = SpecProvider.getInstance().getSpec('affine:doc');
specInstanceA.setup('affine:paragraph', setupA);
specInstanceA.setup('affine:paragraph', setupB);
const specInstanceB = SpecProvider.getInstance().getSpec('affine:doc');
specInstanceA !== SpecInstanceB; // true
// usage
const renderedViewA = this.host.renderSpecPortal(doc, specInstanceA.value)
const renderedViewB = this.host.renderSpecPortal(doc, specInstanceB.value)
```
> feat: add spec builder

- packages/presets/src/ai/chat-panel/chat-panel-input.ts
Fix https://linear.app/affine-design/issue/AFF-1029/chat-panel-需要支持图片粘贴事件
> fix(presets): chat input support image paste

- packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
Removal of kerning information stored in the font for better matching of display and measurement of "text" width when switching to editing mode and back.
> feat(edgeless): remove the kerning information stored in a font

- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
- tests/edgeless/resizing.spec.ts
- tests/edgeless/rotation.spec.ts
- tests/utils/asserts.ts
Fix incorrect cursor style of the selected rectangle due to mismatched coordinates.
> fix(edgeless): incorrect cursor style of selected rect

- packages/framework/store/src/__tests__/schema.unit.spec.ts
- packages/framework/store/src/store/doc/block-collection.ts
- packages/framework/store/src/store/doc/doc.ts
- packages/framework/store/src/store/space.ts
If we throw errors in transactions of Y.Doc, the yjs data flow will be destroyed. So we log out the error to protect the data. 
We should also avoid to throw error directly in yjs event observers.
> fix: catch error in ydoc transaction and doc getter

- packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
- packages/blocks/src/root-block/edgeless/utils/text.ts
- packages/blocks/src/surface-block/managers/edit-session.ts
> fix(edgeless): text element issue

- packages/blocks/src/_common/utils/button-popper.ts
- packages/presets/src/ai/entries/format-bar/format-bar-ai-button.ts
- packages/presets/src/ai/entries/format-bar/setup-format-bar.ts
- Fix inline ai pannel can not popup in edgeless.
https://github.com/toeverything/blocksuite/assets/20479050/781774de-8887-42e4-aa28-389df01dd19f
- Imporve position of inline ai pannel in edgeless (AFF-1024)
> fix(edgeless): imporve ai pannel position in edgeless

- packages/blocks/src/_common/components/utils.ts
- packages/blocks/src/_common/utils/selection.ts
- packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
- packages/blocks/src/root-block/widgets/linked-doc/index.ts
- packages/blocks/src/root-block/widgets/slash-menu/index.ts
> fix(blocks): getCurrentNativeRange should not throw an error when the range count is 0

- packages/blocks/src/root-block/widgets/ai-panel/components/state/input.ts
Do not allow user to enter consecutive spaces.
> fix(blocks): should trim textarea value

- packages/presets/src/ai/actions/edgeless-handler.ts
- packages/presets/src/ai/entries/edgeless/actions-config.ts
Closes: [BS-296](https://linear.app/affine-design/issue/BS-296/make-it-real：支持空选状态)
https://github.com/toeverything/blocksuite/assets/27926/bd5610a1-ebaf-4228-ad09-0a73809e9486
> feat(presets): list make it real action when selection is empty

- packages/blocks/src/_specs/_specs.ts
- packages/blocks/src/root-block/types.ts
- packages/blocks/src/root-block/widgets/ai-panel/ai-panel.ts
- packages/blocks/src/root-block/widgets/viewport-overlay/viewport-overlay.ts
To fixed [TOV-834](https://linear.app/affine-design/issue/TOV-834/激活-ai-panel-后需要将-focus-保持在-ai-panel)
Before, when ai-panel opened and has generated some content, if user click or drag outside of the ai panel, the selection will be changed, then the response actions will be wired, for example, insert below or replace the wrong blocks.
https://github.com/toeverything/blocksuite/assets/99816898/a8c1d89b-0058-4bd8-85ca-75cd624dcca4
Now can lock the viewport when ai-panel opened by calling affineViewportOverlayWidget.lock().
https://github.com/toeverything/blocksuite/assets/99816898/958ab7b7-07a9-440c-8129-3fcf192881a3
> fix: avoid selection change when ai-panel display

- packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
- packages/blocks/src/root-block/edgeless/components/auto-complete/utils.ts
- packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
- packages/blocks/src/root-block/edgeless/components/presentation/edgeless-navigator-black-background.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/frame/navigator-setting-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/text/text-tool-button.ts
- packages/blocks/src/root-block/edgeless/controllers/tools/note-tool.ts
- packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/edgeless/utils/hotkey-utils.ts
- packages/blocks/src/root-block/remote-color-manager/remote-color-manager.ts
- packages/blocks/src/root-block/root-service.ts
- packages/blocks/src/root-block/widgets/pie-menu/config.ts
- packages/blocks/src/root-block/widgets/pie-menu/utils.ts
- packages/blocks/src/surface-block/managers/edit-session.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
- packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
- packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
- packages/presets/src/fragments/frame-panel/header/frames-setting-menu.ts
- tests/utils/actions/edgeless.ts
Unify typed local storage with session storage 
```typescript
const SessionPropsSchema = z.object({
viewport: z.union([
z.object({
centerX: z.number(),
centerY: z.number(),
zoom: z.number(),
}),
z.object({
xywh: z.string(),
padding: z
.tuple([z.number(), z.number(), z.number(), z.number()])
.optional(),
}),
]),
templateCache: z.string(),
remoteColor: z.string(),
showBidirectional: z.boolean(),
});
const LocalPropsSchema = z.object({
presentBlackBackground: z.boolean(),
presentFillScreen: z.boolean(),
presentHideToolbar: z.boolean(),
});
```
If we want to record another field in local storage, just config it in LocalPropsSchema. Then it's done.
We got typed interface and the field will stored in localStorage.
Same for sessionStorage.
> feat(blocks): unify session and local storage

- packages/blocks/src/_common/utils/button-popper.ts
- packages/blocks/src/root-block/edgeless/components/buttons/menu-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/add-group-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/release-from-group-button.ts
- tests/edgeless/element-toolbar.spec.ts
Closes: [BS-301](https://linear.app/affine-design/issue/BS-301/修复-element-toolbar-上-buttons-tooltip-的位置)
Don't use the same state in different poppers.
https://github.com/toeverything/blocksuite/assets/27926/4c769cd1-c123-4f42-ba41-aa6f20631911
https://github.com/toeverything/blocksuite/assets/27926/63356262-1043-4828-bba6-c63de4901561
> fix(blocks): tooltip should be hidden after clicking the button

- packages/presets/src/ai/actions/edgeless-handler.ts
- packages/presets/src/ai/entries/format-bar/format-bar-ai-button.ts
Close AFF-1024
- fix incorrect position of `ai-panel` toggled by edgeless copilot action of doc block in edgeless mode, such as Make-It-Real.
https://github.com/toeverything/blocksuite/assets/20479050/cff6f8ed-8aad-4226-8754-5efcfc131df3
https://github.com/toeverything/blocksuite/assets/20479050/044099fa-6e21-4a05-94fd-ef51ac6636a0
> fix(edgeless): incorrect position of make-it-real

- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
- tests/edgeless/group.spec.ts
Fix https://linear.app/affine-design/issue/BS-314/group-复制粘贴失败
> fix(blocks): fix paste group with connector in it

- packages/blocks/src/_common/utils/event.ts
- packages/blocks/src/root-block/edgeless/components/auto-connect/edgeless-index-label.ts
- packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/root-block/widgets/edgeless-remote-selection/index.ts
- packages/blocks/src/surface-block/canvas-renderer/renderer.ts
- packages/blocks/src/surface-block/grid.ts
- packages/blocks/src/surface-block/managers/layer-manager.ts
- packages/blocks/src/surface-block/managers/layer-utils.ts
- packages/blocks/src/surface-ref-block/surface-ref-portal.ts
- packages/presets/src/__tests__/edgeless/layer.spec.ts
- split first blocks rendering into multiple parts
- move edgeless label update logic into `edgeless-index-label` component
- remove unecessary code from portal
- simplify layer `zIndex` property
> perf(edgeless): slice first block rendering to multiple parts

- packages/blocks/src/image-block/components/page-image-block.ts
- packages/blocks/src/image-block/image-resize-manager.ts
This pull request removes the height property from the image css style. No matter how the browser window size changes, images can keep in shape with their original aspect ratio.
Close affine-design/issue/BS-304.
| Before      | After |
| ----------- | ----------- |
| <img width="200" alt="截屏2024-05-14 17 10 31" src="https://github.com/toeverything/blocksuite/assets/12724894/cecace88-7475-4af4-b13f-a5a6e2df5ffa">| <img width="186" alt="截屏2024-05-14 17 10 43" src="https://github.com/toeverything/blocksuite/assets/12724894/b0eab4dd-f42a-488b-84a0-0a5a0b109ec9">|
The height property was removed from two different places in the code base:
1. In the `ImageBlockPageComponent` class, it was removed from the `style` of  resizable image container div.
2. In the `ImageResizeManager` class, it was …
> fix: browser window resize causes image deformation

- packages/blocks/src/root-block/edgeless/components/connector/connector-handle.ts
- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
- tests/edgeless/element-toolbar.spec.ts
Closes: [AFF-1077](https://linear.app/affine-design/issue/AFF-1077/移动-connector-端点时，toolbar-应该关掉)
> fix(blocks): element toolbar should be hidden when resizing element

- packages/blocks/src/_common/components/rich-text/rich-text.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/divider-block/divider-block.ts
- packages/blocks/src/list-block/list-block.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
- packages/framework/inline/src/inline-editor.ts
- packages/presets/src/ai/messages/text.ts
- Move `<style>` to static property to avoid style recalculation on each instance.
- Set initial `contenteditable` to the inline editor container to avoid later recalculation
> perf: avoid recalculate style

- packages/blocks/src/_common/components/embed-card/embed-card-caption.ts
- tests/image.spec.ts
Close #7024
- Use <textarea></textarea> for multiple lines input and wrapping. 
- Use display: inline-table to make the height of the textarea fit the content.
> fix(blocks): embed-car-caption overflow

- packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
> fix(edgeless): create popper on null element

- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/code-block/code-model.ts
- packages/blocks/src/code-block/components/code-option.ts
- tests/code.spec.ts
- tests/format-bar.spec.ts
This Pull Request moves the `wrap` property from temporary state to persistent data model. When user refreshes the web browser, the code block warp style keeps.
Fix affine-design/issue/BS-297.
- In `code-block.ts`, the `_wrap` private state variable has been removed, and all references to it have instead been directed to `this.model.wrap`.
- A `setWrap` function has been added to handle updating the `wrap` property in the block model, which can be persisted in database.
Test this change by creating a code block in document and toggle the `wrap` icon. Check if this modifies the wrap state in the model and updates the UI accordingly. Refresh the browser, the code block warp styles keeps.
---
> fix: the code block wrap state shoud be persisted in database

- packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-portal-base.ts
- packages/blocks/src/root-block/edgeless/components/block-portal/frame/edgeless-frame.ts
Lit allows users to override the `scheduleUpdate` method to change the rendering timing of elements, which is particularly suitable for rendering a large number of elements in batches to prevent blocking the main thread.
> refactor(edgeless): better rendering control using lit scheduleUpdate

- packages/blocks/src/embed-figma-block/embed-figma-service.ts
- packages/blocks/src/embed-github-block/embed-github-service.ts
- packages/blocks/src/embed-loom-block/embed-loom-service.ts
- packages/blocks/src/embed-youtube-block/embed-youtube-service.ts
- packages/framework/block-std/src/spec/spec-store.ts
The old implementation relies on the loading order of specs, assuming that the root spec comes before the embed spec
> fix(blocks): root service maybe undefined when service mounted

- packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
- packages/blocks/src/_common/adapters/markdown.ts
> feat(page): support table rich-text in markdown adapter

- packages/blocks/src/paragraph-block/paragraph-block.ts
- tests/paragraph.spec.ts
- the placeholder will be visible, only if the selection is text selection and collapsed
- add e2e test
Fix affine-design/issue/BS-312.
|  Before  | After |
|  ----  | ----  |
| ![截屏2024-05-17 19.02.32.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/54123270-fe12-4004-b99b-80d87196d106.png) | ![截屏2024-05-17 19.04.14.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/b09fbb99-9a5b-4d1d-9637-3175a5c21efc.png)|
Test the paragraph block in various states like editing, selecting, etc. Ensure the placeholder visibility is as expected.
---
> fix: selecting multiple blocks and dragging will show multiple placeholders

- packages/framework/block-std/src/__tests__/command.unit.spec.ts
- packages/framework/block-std/src/command/manager.ts
- packages/framework/block-std/src/command/types.ts
Add `exec` to allow executing a single command without calling `chain`.  Usage is shown below.
```TypeScript
const result = this.std.command.exec('getBlockIndex');
console.log(result.blockIndex);
```
> feat(std): add exec method to CommandManager

- packages/blocks/src/surface-block/element-model/utils/shape/ellipse.ts
Closes: [TOV-879](https://linear.app/affine-design/issue/TOV-879/旋转-ellipse-时，connector-endport-没有跟随变化)
https://github.com/toeverything/blocksuite/assets/27926/8930c19d-d317-40f3-8897-7eb00120487a
> fix(blocks): connector endpoint should follow rotation of ellipse

- packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
- tests/edgeless/shape.spec.ts
- tests/utils/actions/edgeless.ts
https://github.com/toeverything/blocksuite/assets/27926/6b594dc2-43db-48e4-9643-1e6e5fe02520
https://github.com/toeverything/blocksuite/assets/27926/021d457f-dd3d-40c1-8b40-888eff18fd1b
> fix(blocks): should reset shape text when text is empty

- packages/framework/store/src/store/doc/block.ts
https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/embed-synced-doc-block/embed-synced-doc-spec.ts#L16
Some blocks have undefined default props, causing the default values ​​to be set over and over again, creating an dead loop.
> fix(store): dead loop on set default props

- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
https://linear.app/affine-design/issue/BS-323
> fix(edgeless): note blocks not ordered because of missing images

- .github/workflows/browser-compatibility.yml
- .github/workflows/canary-release.yml
- .github/workflows/lint.yml
- .github/workflows/pr-title-lint.yml
- .github/workflows/release.yml
- .github/workflows/size-report.yml
- .github/workflows/test.yml
- package.json
You'll even get an error if you have pnpm 9.1.2 but the field is set to 9.1.1. We really don't need this field.
https://github.com/nodejs/corepack/issues/95#issuecomment-1889553265
> chore: remove package manager in package json since its wont support range

- packages/blocks/src/root-block/edgeless/controllers/tools/note-tool.ts
- tests/edgeless/note.spec.ts
Close [AFF-778](https://linear.app/affine-design/issue/AFF-778/incorrect-minimal-width-limit-when-creating-note-block-on-edgeless)
> fix(edgeless): use minimum note width and height

- packages/blocks/src/database-block/columns/rich-text/define.ts
- packages/blocks/src/database-block/data-view/column/manager.ts
- packages/blocks/src/database-block/data-view/column/presets/checkbox/define.ts
- packages/blocks/src/database-block/data-view/column/presets/date/define.ts
- packages/blocks/src/database-block/data-view/column/presets/number/define.ts
- packages/blocks/src/database-block/data-view/column/presets/progress/define.ts
- tests/database/column.spec.ts
- Let's add date cell conversions later.
> feat(database): add more cell conversions

- packages/blocks/src/root-block/edgeless/frame-manager.ts
Duplicate a frame with linked doc card inside, only canvas shape cloned successfully and the linked doc card is lost. 
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/ae663813-7493-4503-99d8-9317d2601f15.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/ae663813-7493-4503-99d8-9317d2601f15.mov">录屏2024-05-27 14.38.43.mov</video>
There is a whitelist in function `getBlocksInFrame` which only allow `affine:image` and `affine:frame` bypass causes this issue. Using `instanceof EdgelessBlockModel` instead of the enum whitelist will be a better solution.
---
> fix: frame duplicate lost linked doc card

- packages/blocks/src/frame-block/frame-model.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
- packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/blocks/src/root-block/edgeless/components/block-portal/frame/edgeless-frame.ts
- packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
- packages/blocks/src/root-block/edgeless/components/text/edgeless-frame-title-editor.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/edgeless/frame-manager.ts
- packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
- packages/blocks/src/surface-block/grid.ts
- packages/blocks/src/surface-block/managers/layer-manager.ts
- packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.spec.ts
- packages/framework/block-std/src/view/utils/range-binding.ts
- tests/edgeless/frame.spec.ts
- set `display: none` on the blocks outside the viewport
- remove `will-change` cause' it brings additional layerizing overhead
- reduce unnecessary selection update
After landing this, we should have a good enough performance baseline. The next step is to build a performance metrics tool.
> perf: reduce the edgeless rendering overhead

- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
- packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
- packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts
- packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
- tests/edgeless/clipboard.spec.ts
- tests/utils/actions/edgeless.ts
- Refactor the logic of `getCopyElements` and `prepareClipboardData` in the clipboard, split into several atomic functions so they can be easily reused in copy, clone and duplicate scenarios
- Use `instanceof EdgelessBlockModel` assert instead of enum `isXXBlock` assert
- Add several e2e tests for copy group and frame cases
> refactor: add common clone elements logic for copy, clone, duplicate scenes

- packages/blocks/src/_common/components/block-caption.ts
- packages/blocks/src/_common/components/index.ts
- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/code-block/code-model.ts
- packages/blocks/src/code-block/styles.ts
- packages/blocks/src/embed-figma-block/embed-figma-block.ts
- packages/blocks/src/embed-github-block/embed-github-block.ts
- packages/blocks/src/embed-html-block/embed-html-block.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-loom-block/embed-loom-block.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
- packages/blocks/src/image-block/image-block.ts
- packages/blocks/src/root-block/widgets/code-toolbar/config.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- tests/code.spec.ts
- tests/format-bar.spec.ts
- tests/image.spec.ts
This PR
- Adds caption for code block
- Moves the `embed-card-caption` component to `block-caption-editor` which can be used with any block with a `caption` prop
Closes: [AFF-1138](https://linear.app/affine-design/issue/AFF-1138/add-caption-function-for-code-block)
> feat(blocks): add caption for code block

- packages/blocks/src/_common/components/notification-service.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/utils/editor.ts
```ts
notify(notification: {
title: string | TemplateResult;
message?: string | TemplateResult;
accent?: 'info' | 'success' | 'warning' | 'error';
duration?: number; // give 0 to disable auto dismiss
}): void;
```
> feat(blocks): add notify method to NotificationService

- packages/blocks/src/_common/components/rich-text/rich-text.ts
- packages/blocks/src/code-block/code-block.ts
- packages/blocks/src/data-view-block/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/columns/rich-text/cell-renderer.ts
- packages/blocks/src/database-block/columns/title/text.ts
- packages/blocks/src/database-block/components/title/index.ts
- packages/blocks/src/list-block/list-block.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
- packages/presets/src/fragments/doc-title/doc-title.ts
When switching modes, if there is an embed syncd block in the page, the following occurs:
https://github.com/toeverything/blocksuite/assets/27926/e4b921e4-5182-4db9-a246-ee391d95a6a7
> fix(blocks): lazy get viewport element on rich-text

- packages/blocks/src/_common/components/rich-text/rich-text.ts
- packages/blocks/src/_common/utils/render-linked-doc.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/styles.ts
- packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
- packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
- packages/blocks/src/specs/edgeless-specs.ts
- packages/blocks/src/specs/index.ts
- packages/blocks/src/surface-ref-block/portal/note.ts
- tests/embed-synced-doc.spec.ts
Closes: [BS-177](https://linear.app/affine-design/issue/BS-177/embedded-doc-in-edgeless-mode-should-be-under-readonly-mode-without)
> fix(blocks): toolbar should not be displayed in synced doc block

- packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
- packages/blocks/src/surface-block/element-model/group.ts
- packages/blocks/src/surface-block/managers/connector-manager.ts
Closes: [BS-431](https://linear.app/affine-design/issue/BS-431/group-connect-group), [AFF-1184](https://linear.app/affine-design/issue/AFF-1184/connector-可以连接-group-和-group-内的yuan素)
* Allow groups connect other groups 
* Allow groups connect elements within other groups
* Allow elements within groups connect other groups
* Highlight groups
> feat(blocks): support connections between groups

- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
- packages/blocks/src/surface-block/commands/reassociate-connectors.ts
- packages/blocks/src/surface-block/surface-service.ts
Closes: [BS-432](https://linear.app/affine-design/issue/BS-432/linked-doc切换形态时，connector要保持连接)
* Support re-associate connectors when switch mode
> feat(blocks): support connecting different linked doc formats

- tests/edgeless/connector.spec.ts
Related to: [BS-95](https://linear.app/affine-design/issue/BS-95/connector-可以连接-group-和-group-内的yuan素) #7192
> chore: add test cases for groups connections

- packages/blocks/src/surface-block/commands/reassociate-connectors.ts
Closes: [BS-465](https://linear.app/affine-design/issue/BS-465/linked-与-synced-频繁切换时，进行-undoredo-操作，connectors-会丢)
> fix(blocks): reassociate connectors

- packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
- packages/blocks/src/_common/configs/quick-action/config.ts
- packages/blocks/src/_common/utils/block-props.ts
- packages/blocks/src/_common/utils/render-linked-doc.ts
- packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
- packages/blocks/src/root-block/edgeless/utils/connector.ts
- packages/blocks/src/root-block/keyboard/keyboard-manager.ts
- packages/blocks/src/root-block/widgets/drag-handle/utils.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
- packages/blocks/src/root-block/widgets/format-bar/config.ts
- packages/blocks/src/root-block/widgets/image-toolbar/utils.ts
- packages/blocks/src/surface-block/element-model/base.ts
- packages/blocks/src/surface-block/element-model/connector.ts
- packages/blocks/src/surface-block/element-model/group.ts
- tests/edgeless/linked-doc.spec.ts
- tests/format-bar.spec.ts
- tests/utils/actions/edgeless.ts
This pull request support edgeless mode to create linked doc. Find more details in [THIS RFC](https://app.affine.pro/workspace/af3478a2-9c9c-4d16-864d-bffa1eb10eb6/XUmNieqGMKDs525xNqY8G).
There are two way to create a linked doc in edgeless editor:
- The first way, select a single note and click the `Turn into linked doc` menu item. The content of the selected note will become a independant document.
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/029fa907-26a5-4063-9fb2-0409931ab291.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/029fa907-26a5-4063-9fb2-0409931ab291.mov">录屏2024-06-03 18.52.41.mov</video>
- The second way, select …
> feat(edgeless): support edgeless mode create linked doc

- packages/blocks/src/_common/adapters/utils.ts
- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
Closes: [BS-467](https://linear.app/affine-design/issue/BS-467/edgeless-下导出图片时，html2canvas-中的-blob-图片会使用-proxy)
> fix(blocks): no proxy required to fetch blob

- packages/presets/src/ai/actions/doc-handler.ts
- packages/presets/src/ai/actions/edgeless-handler.ts
Close [BS-310](https://linear.app/affine-design/issue/BS-310/edgeless%E4%B8%8B%EF%BC%8C%E9%87%8D%E6%96%B0%E5%AF%B9doc%E6%96%87%E6%9C%AC%E4%BD%BF%E7%94%A8ai-aciton%E4%BC%9A%E4%BD%BF%E5%BE%97%E9%80%89%E5%8C%BA%E4%B8%A2%E5%A4%B1)
Clear selection after discarding the edgeless AI action, which is consistent with the AI action behaviors of other edgeless elements.
- Edgeless element selection behavior with edgeless ai action:
https://github.com/toeverything/blocksuite/assets/20479050/375bd4a7-38ed-4462-bf17-78e22c7ed67c
- Doc text selection behavior with edgeless  ai action (**Before**):
https://github.com/toeverything/blocksuite/assets/20479050/3a6de2a7-c670-4980-b65e-f4aeacd04d83
- Doc text selection behavior with edgeless  ai action (**After**): …
> fix(presets): clear selection after ai panel close in edgeless mode

- packages/blocks/src/_common/components/notification-service.ts
- packages/blocks/src/_common/configs/quick-action/config.ts
- packages/blocks/src/_common/utils/render-linked-doc.ts
- packages/blocks/src/root-block/keyboard/keyboard-manager.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
- packages/blocks/src/root-block/widgets/format-bar/config.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/utils/editor.ts
This pull request adds support for page and edgeless mode to create a linked documents using a specific doc title entered by the user. 
https://github.com/toeverything/blocksuite/assets/12724894/68e7ee42-1c0f-449d-9832-2a80134589dd
- Add a prompt pop-up window for users to enter the title of the linked document.
- In page mode, use the first heading block content as pop-up input autofill value and default document title.
> feat(page): add prompt pop-up for users to input linked doc title

- packages/presets/src/ai/chat-panel/chat-panel-messages.ts
[BS-470](https://linear.app/affine-design/issue/BS-470/新增的-image-actions-在-chat-panel-的显示)
> fix(presets): new image actions should display in chat panel

- packages/blocks/src/_common/components/notification-service.ts
- packages/blocks/src/_common/configs/quick-action/config.ts
- packages/blocks/src/_common/utils/render-linked-doc.ts
- packages/blocks/src/root-block/keyboard/keyboard-manager.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
- packages/blocks/src/root-block/widgets/format-bar/config.ts
- packages/framework/block-std/src/view/element/lit-host.ts
This pull request adds a notify toast after linked doc created. Users can click the `undo` button on the toast to revert the change that created the linked document.
- Add the notify toast both in page mode and edgeless mode
- When user edit or undo or switch doc, close the notify toast
- Clear all observers when toast closed
[Related PR in AFFiNE](https://github.com/toeverything/AFFiNE/pull/7162)
https://github.com/toeverything/blocksuite/assets/12724894/3a9c21d7-4d40-408a-978e-455c6370ef68
---
> feat(page): add notify toast after linked doc created

- packages/blocks/src/surface-block/element-model/connector.ts
- packages/blocks/src/surface-block/utils/curve.ts
Closes: [BS-475](https://linear.app/affine-design/issue/BS-475/优化-curve-intersects)
* Extract some util functions from https://github.com/Pomax/bezierjs (MIT)
* Fix curve intersects
We might consider importing `bezierjs`.
https://github.com/toeverything/blocksuite/assets/27926/ba912cf7-9cc8-442f-b331-46b825d848cf
https://github.com/toeverything/blocksuite/assets/27926/9b391caf-616e-4634-8d18-0df03d92e79c
> fix(blocks): curve intersects

- packages/blocks/src/surface-block/canvas-renderer/renderer.ts
* Specifying the actual size gives better results and more consistent behavior across browsers.
* Make sure the main canvas and the offscreen canvas or layer canvas are the same size.
* It is not recommended to set width and height to 100%.
Related to #7205
> perf(blocks): improve canvas rendering when resizing the window

- .github/workflows/browser-compatibility.yml
- .github/workflows/canary-release.yml
- .github/workflows/lint.yml
- .github/workflows/pr-title-lint.yml
- .github/workflows/release.yml
- .github/workflows/size-report.yml
- .github/workflows/test.yml
- package.json
Enable corepack again since pnpm finally won't throw error when version mismatch.
https://github.com/pnpm/pnpm/releases/tag/v9.2.0
> ci: enable corepack again

- packages/blocks/src/_common/components/hover/controller.ts
- packages/blocks/src/_common/components/tooltip/tooltip.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/default/default-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/lasso/lasso-tool-button.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
Close BS-327
- Refine tooltip visual effect
https://github.com/toeverything/blocksuite/assets/20479050/dc078ea2-475b-4560-9935-4dbec57f5b2f
https://github.com/toeverything/blocksuite/assets/20479050/6dd62885-b28b-4b64-95c3-a3e4dd301827
- Fix edgeless tool bar button size (40x43.33 -> 40x40)
> fix(blocks): refine tooltip visual effect

- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
https://github.com/toeverything/blocksuite/assets/27926/28931ae3-bc3f-4990-aedd-499e3351c737
> fix(blocks): edgeless-root-block's sub-elements should not be selected on safari

- packages/blocks/src/_common/components/filterable-list/index.ts
- packages/blocks/src/_common/components/hover/controller.ts
- packages/blocks/src/root-block/widgets/code-language-list/components/lang-button.ts
- packages/blocks/src/root-block/widgets/code-language-list/index.ts
Related to https://github.com/toeverything/blocksuite/pull/7245 https://github.com/toeverything/blocksuite/pull/7246
The `HoverController` is unsuitable here since the lang list should not disappear when the user hovers out.
> fix: code-language-list widget disappear

- packages/blocks/src/_common/components/filterable-list/index.ts
- packages/blocks/src/_common/components/hover/controller.ts
- packages/blocks/src/root-block/widgets/code-language-list/components/lang-button.ts
- packages/blocks/src/root-block/widgets/code-language-list/index.ts
- packages/blocks/src/root-block/widgets/code-toolbar/components/code-toolbar.ts
- packages/blocks/src/root-block/widgets/code-toolbar/index.ts
- packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
- packages/blocks/src/root-block/widgets/image-toolbar/index.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
- tests/slash-menu.spec.ts
This pull request adds the HoverController functionality to toolbar widgets.
The HoverController improves the user experience by preventing the widgets from disappearing when they are active.
```ts
class {
private _hoverController = new HoverController(this, () => {})
override connectedCallback() {
super.connectedCallback();
this._hoverController.setReference(this.blockElement);
// ⬇️ Prevent abort in some condition
this._hoverController.onAbort = () => {
// If activated, don't close it.
if (this._isActivated) return;
this._hoverController.abort(); // default abort action
return;
};
}
}
```
You need to specify the length of the transition explicitly.
```ts
class {
private _hoverController = new HoverController(this, () => {}, {
transition: { duration: 100, in: {}, out: {} },
// …
```
> feat(blocks): add new `onAbort` API to HoverController

- packages/blocks/package.json
- packages/blocks/src/_common/inline/presets/nodes/affine-text.ts
- packages/blocks/src/paragraph-block/styles.ts
- packages/presets/package.json
- pnpm-lock.yaml
Close https://github.com/toeverything/blocksuite/issues/7099, Close https://github.com/toeverything/blocksuite/issues/6086,  [BS-322](https://linear.app/affine-design/issue/BS-322/update-mono-fonts), [BS-108](https://linear.app/affine-design/issue/BS-108/inline-code-block-update)
- Bump theme to update font to `IBM Plex Mono`
> refactor(blocks): update code font

- packages/blocks/src/_common/components/file-drop-manager.ts
- packages/blocks/src/attachment-block/attachment-service.ts
- packages/blocks/src/image-block/image-service.ts
- packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-block-portal.ts
- packages/blocks/src/root-block/edgeless/components/connector/connector-handle.ts
- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/root-block/edgeless/components/resize/resize-manager.ts
- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/utils/query.ts
- packages/blocks/src/root-block/edgeless/utils/viewport.ts
- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
- packages/blocks/src/surface-block/element-model/connector.ts
- packages/blocks/src/surface-block/managers/connector-manager.ts
- packages/blocks/src/surface-block/utils/point-location.ts
- packages/presets/src/ai/actions/edgeless-response.ts
Closes [BS-454](https://linear.app/affine-design/issue/BS-454/connector-resize-and-rotate)
Related to #6704
In the connectors scenario, just recalculate `source.position` and `target.position`.
Extract independent functions to resize elements.
> Maybe we can move these into their servies.
https://github.com/toeverything/blocksuite/assets/27926/ace30ee4-9b77-4962-8e49-8ada544ada63
> fix(blocks): connectors resize and rotate

- packages/blocks/src/edgeless-text/edgeless-text-model.ts
- packages/blocks/src/edgeless-text/edgeless-text-service.ts
- packages/blocks/src/paragraph-block/paragraph-block.ts
- packages/blocks/src/root-block/edgeless/components/block-portal/edgeless-text/edgeless-edgeless-text.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
https://github.com/toeverything/blocksuite/assets/50035259/722b3466-32b7-4726-a15a-ab414e6ca448
In addition, the text field of the edgeless text model has been removed.
> feat(edgeless): add default color and editing border for edgeless text

- packages/blocks/src/_common/components/ai-item/types.ts
- packages/blocks/src/_common/components/doc-mode-service.ts
- packages/blocks/src/_common/components/index.ts
- packages/blocks/src/_common/types.ts
- packages/blocks/src/_common/utils/render-linked-doc.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/index.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/index.ts
- packages/blocks/src/root-block/page/page-root-service.ts
- packages/blocks/src/root-block/root-service.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/playground/apps/_common/components/custom-chat-panel.ts
- packages/playground/apps/_common/components/debug-menu.ts
- packages/playground/apps/_common/components/quick-edgeless-menu.ts
- packages/playground/apps/_common/mock-services.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/utils/editor.ts
- packages/presets/src/__tests__/edgeless/surface-ref.spec.ts
- packages/presets/src/ai/chat-panel/chat-panel-messages.ts
- packages/presets/src/ai/entries/slash-menu/setup-slash-menu.ts
- packages/presets/src/editors/editor-container.ts
- packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
- packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
This refactor introduces a new `DocModeService` to get document mode, set or toggle mode and observe mode changes. You can also get or set sepcific document mode by pass through id, not only the current document mode.
- The old `editorModeSwitch` slot only support manipulating current doc, can not change other doucment mode.
- The old `editorModeSwitch.on` only react to `editorModeSwitch.emit` which is not strict equal to mode change.
- Explicitly calling the `setMode` function should be more intuitive than emitting an event.
- Introduced `DocModeService` to manage document mode, which can be overwritten by upper business logic (eg. in playground or affine)
```typeacript
interface DocModeService {
setMode: (mode: DocMode, docId?: string) => void;
getMode: (docId?: string) => DocMode; …
```
> refactor: add DocModeService for doc mode get, set, toogle and observe change

- packages/presets/src/ai/messages/text.ts
Closes: [AFF-1088](https://linear.app/affine-design/issue/AFF-1088/chat-%E5%9B%9E%E7%AD%94-%E5%88%86%E5%89%B2%E7%BA%BF%E4%B8%8E%E9%80%89%E5%8C%BA%E9%94%99%E4%BD%8D)
> fix(presets): refine style of divider and focus outline in chat panel

- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
- packages/blocks/src/list-block/styles.ts
Closes: [BS-508](https://linear.app/affine-design/issue/BS-508/note-中-inline-yuan素超出后宽度后：)
> fix(blocks): inline link text overflow in note

- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
Pass selectedElements as the `elements` property to the <edgeless-more-button> component. Make sure the menu for more buttons triggers a re-render after selected elements changes.
> fix: more button do not re-render after selected elements changed

- packages/blocks/src/root-block/edgeless/components/toolbar/eraser/eraser-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mixins/toolbar-button-with-menu.mixin.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/presentation-toolbar.ts
- packages/framework/block-std/src/view/element/block-element.ts
Tool buttons in edgeless toolbar may destroy and re-mount, so it's better to dispose the hot-key events when it disconnected.
> fix(edgeless): bind shortcuts in toolbar should dispose when tool disconnected

- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
This pull request fixes an issue where the slash menu was not ignoring composing events.
Before
https://github.com/toeverything/blocksuite/assets/18554747/a5da4c83-3412-4e04-b02e-30971277dc86
After
https://github.com/toeverything/blocksuite/assets/18554747/def918aa-2649-4d30-a178-04789fef7cee
> fix: ignore composing event in slash menu

- packages/blocks/src/_common/components/hover/controller.ts
- packages/blocks/src/_common/components/hover/when-hover.ts
- packages/blocks/src/_common/inline/presets/nodes/link-node/affine-link.ts
- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-node.ts
- Prevents responding to hover state changes if the host element is disconnected from the DOM.
- Use current event flag to ignore expired event.
- Add a new property `enterDelay` with a value of 500ms to the constructor of the hover controller in link and refernce scenes.
> fix: add a 500ms delay time before showing the hover toolbar

- packages/presets/package.json
- packages/presets/src/index.ts
Remove the default export of the AI preset, as it causes global type declaration conflicts in AFFiNE side.
> chore: remove ai preset export by default

- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
Use `doc.deleteBlock` instead of `deleteElements` to delete selected note element.
In function `deleteElements`,  the value get immediately from `service.surface.getConnectors` is outdated after modify the connector data. Because the `_elementToConnector` map is updated in the event thrown by Y.js, which is a  asynchronous process. 
@doouding @Saul-Mirone Maybe we should have a better way to update the `_elementToConnector` map.
> fix: keep connectors after note converted to linked doc

- packages/blocks/src/_common/utils/render-linked-doc.ts
To fix [AFF-1278](https://linear.app/affine-design/issue/AFF-1278/linked-doc-margin或line-height错误)
related issue: 
https://github.com/toeverything/blocksuite/pull/7178
```
private _renderWithWidget(content: unknown) {
const style = styleMap({
position: 'relative',
...this.blockContainerStyles,
});
return html`<div style=${style} class="affine-block-component">
${content}
${this.useCaptionEditor
? html`<block-caption-editor .block=${this}></block-caption-editor>`
: nothing}
<affine-block-selection .block=${this}></affine-block-selection>
</div>`;
}
```
Because the margin style setting of the block container is now changed to inline style, the original selector weight is not enough.
> fix(blocks): linked doc card custom style

- packages/blocks/src/_common/edgeless/mindmap/index.ts
- packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
- packages/blocks/src/root-block/edgeless/components/text/edgeless-connector-label-editor.ts
- packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
- packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/connector/index.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/group/utils.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/rect.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/utils.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/text/index.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/text/utils.ts
- packages/blocks/src/surface-block/consts.ts
- packages/blocks/src/surface-block/element-model/base.ts
- packages/blocks/src/surface-block/element-model/mindmap.ts
- packages/blocks/src/surface-block/element-model/shape.ts
- packages/blocks/src/surface-block/element-model/utils/mindmap/style.ts
- packages/blocks/src/surface-block/managers/layer-manager.ts
- packages/framework/global/index.d.ts
- packages/framework/store/src/store/store.ts
- packages/playground/apps/default/utils/collection.ts
- packages/playground/apps/starter/utils/collection.ts
- packages/presets/src/__tests__/edgeless/group.spec.ts
- Mindmap style and issue
- Shape text rendering
- Add extra `padding` and `shadow` yfield
The shape text always shifts when entering the editing mode. The reason is that the text is rendering on `ideographic` baseline not `alphabetic` which is used in CSS rendering. So, to align with the DOM rendering, the baseline has changed to `alphabetic` and the start vertical position is the ascent and line gap of the font.
> fix: mindmap issue

- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
- tests/edgeless/clipboard.spec.ts
In a cut behavior, the deleted elements should be absolutely equal to the copied elements.
https://github.com/toeverything/blocksuite/assets/12724894/3644b3a5-b0fd-4357-9fc5-50235737e080
> fix(edgeless): cut behaviour does not completely delete elements

- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
Add `docModeService.onModeChange` to observe doc mode change and trigger card component re-render.
After Fixed:
https://github.com/toeverything/blocksuite/assets/12724894/92948b65-4f22-47bf-a963-0fadce034fdd
> fix(page): component not re-render when linked doc mode changes

- packages/blocks/src/root-block/edgeless/components/block-portal/frame/edgeless-frame.ts
- tests/edgeless/frame.spec.ts
- Note/DOM block can be selected or edit inside frame
> fix(edgeless): note inside frame can be edited

- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
Closes: [BS-560](https://linear.app/affine-design/issue/BS-560/%E9%80%9A%E8%BF%87-edgeless-text-%E6%96%87%E6%A1%A3%E5%90%8E-%E9%9D%A2%E6%9D%BF%E9%A3%9E%E4%BA%86)
> chore: fix at in legacy canvas text

- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
Closes: [BS-513](https://linear.app/affine-design/issue/BS-513/%E6%8F%92%E5%85%A5%E7%9A%84%E5%88%9B%E5%BB%BA%E7%9A%84doc%E6%9C%89%E6%A6%82%E7%8E%87%E6%A0%B7%E5%BC%8F%E9%94%99%E8%AF%AF)
> fix: embed linked doc empty style

- packages/blocks/src/root-block/widgets/slash-menu/config.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
- packages/blocks/src/root-block/widgets/slash-menu/styles.ts
- tests/slash-menu.spec.ts
Related: [BS-570](https://linear.app/affine-design/issue/BS-570/slash-menu-%E4%BC%98%E5%8C%96%E6%94%B9%E8%BF%9B)
refine styles:
- remove red background color of `Delete` item when hover it
- change background color of icon  to background color of menu
Bug fix:
- When the mouse hovers over a menu item, and the keyboard is used to navigate the menu options, the current hover item flickers.
https://github.com/toeverything/blocksuite/assets/20479050/a61a4df1-ed66-4370-8f53-1ef3609c1aee
https://github.com/toeverything/blocksuite/assets/20479050/aa5f9c1a-0283-4397-ad2f-622d98bcae9e
> chore(blocks): refine slash menu style

- packages/blocks/src/_common/components/embed-card/type.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/blocks/src/bookmark-block/bookmark-spec.ts
- packages/blocks/src/embed-figma-block/embed-figma-block.ts
- packages/blocks/src/embed-figma-block/embed-figma-spec.ts
- packages/blocks/src/embed-github-block/embed-github-block.ts
- packages/blocks/src/embed-github-block/embed-github-spec.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-spec.ts
- packages/blocks/src/embed-loom-block/embed-loom-block.ts
- packages/blocks/src/embed-loom-block/embed-loom-spec.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-spec.ts
- packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
- packages/blocks/src/embed-youtube-block/embed-youtube-spec.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
- packages/blocks/src/root-block/page/page-root-spec.ts
- packages/blocks/src/root-block/types.ts
- packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
- packages/blocks/src/root-block/widgets/index.ts
- tests/bookmark.spec.ts
- tests/utils/query.ts
Closes: [BS-493](https://linear.app/affine-design/issue/BS-493/edgeless-%E4%B8%8A%E5%B5%8C%E5%A5%97-linked-doc-%E5%90%8E-toolbar-%E6%98%BE%E7%A4%BA-bug), [BS-492](https://linear.app/affine-design/issue/BS-492/edgeless-%E4%B8%8A%E5%B5%8C%E5%A5%97-linked-doc-drag-handler-bug)
Move `embed-card-toolbar` to root blocks widgets container. The previous implementation made it difficult to control the z-index between widgets.
drag handler show above toolbar
toolbar overflow error
> refactor(blocks): move embed card toolbar to root widget container

- packages/blocks/src/_common/components/block-component.ts
- packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
- packages/blocks/src/_common/embed-block-helper/styles.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/styles.ts
- packages/presets/src/editors/editor-container.ts
- tests/embed-synced-doc.spec.ts
Fix issue [BS-581](https://linear.app/affine-design/issue/BS-581).
- If the selected element is an embed block, the selection mask is hidden and the card border is hightlighted.
- Remove useless `_editing ` state and related logic, causing embed document card to now is readonly.
- Single click to select the embed document card and a floating toolbar appears.
- Modify CSS styles.
- Add e2e tests.
The new UI interaction works like:
https://github.com/toeverything/blocksuite/assets/12724894/094e1a0d-986c-4a10-9331-321d7fd10600
> feat(page): modify UI interaction of embed doc card according to the design draft

- packages/blocks/src/_common/components/utils.ts
- packages/blocks/src/root-block/widgets/edgeless-copilot-panel/index.ts
- packages/blocks/src/root-block/widgets/format-bar/styles.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
- packages/blocks/src/root-block/widgets/slash-menu/styles.ts
Related: [AF-928](https://linear.app/affine-design/issue/AF-928/ask-ai-出现在底部的时候-menu-弹出位置不对#comment-33f1e925)
Considering the space occupied by the scrollbar, adjust the padding of the menu to make it symmetric on both sides, which also ensure the correct pop-up position of the submenu.
The affected components include:
- Edgeless Mode Ask AI panel
- Slash Menu
- Page Mode Ask AI panel ( [PR on AFFiNE side](https://github.com/toeverything/AFFiNE/pull/7287) )
> fix: refine padding with scrollbar

- packages/blocks/src/_common/components/doc-mode-service.ts
- packages/blocks/src/index.ts
- packages/blocks/src/root-block/root-service.ts
- packages/playground/apps/_common/components/docs-panel.ts
- packages/playground/apps/_common/components/quick-edgeless-menu.ts
- packages/playground/apps/_common/mock-services.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/utils/editor.ts
Support seperated doc mode in playground and persistent the data in localStorage.
https://github.com/toeverything/blocksuite/assets/12724894/7e719b00-4114-4032-af9f-38aa07d170c3
---
> feat: support seperated doc mode in playground

- packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
- packages/blocks/src/__tests__/utils/create-job.ts
- packages/blocks/src/_common/adapters/markdown.ts
- packages/blocks/src/_common/transformers/index.ts
- packages/blocks/src/_common/transformers/middlewares.ts
- packages/framework/store/src/transformer/job.ts
Closes: [BS-665](https://linear.app/affine-design/issue/BS-665/%E6%94%AF%E6%8C%81-embed-synced-doc-%E7%9A%84-markdown-%E5%AF%BC%E5%87%BA)
This PR adds support for exporting synced documents using `embedSyncedDocMiddleware` with `MakrdownAdapter`.
```ts
const job = new Job({
collection,
middlewares: [embedSyncedDocMiddleware('content')],
});
const adapter = new MarkdownAdapter(job);
// Do what you want to exporting here using markdown adapter
const content = adapter.fromSliceSnapshot({snapshot});
```
There is a output example that export `doc -> synced doc -> nested synced doc`
```md
Hello, I' m Doc
// Begin: Embed synced doc block, export all content of synced doc
Hello, I'm Synced Doc
// Begin: Nested embed synced doc block, just export it's title
Nested Doc
// End: Nested embed synced …
```
> feat: add markdown export from synced doc block

- packages/blocks/src/_common/utils/render-linked-doc.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/styles.ts
Fix [BS-624](https://linear.app/affine-design/issue/BS-624).
- Add `isEmptyDoc` and `isEmptyNote` utils
- Remove `syncedDoc.addBlock('affine:paragraph')` side effects, cause there are no need to do this in rendering lifecycle.
- Add observer to `blockUpdated`.
> fix: embed linked doc failed to load after created

- packages/blocks/src/_common/components/embed-card/embed-card-more-menu-popper.ts
- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup-more-menu-popup.ts
- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
- packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
Fix issue [BS-628](https://linear.app/affine-design/issue/BS-628).
If linked document references itself:
- Disable open this doc button 
- Disable open in more menu 
- Disable embed view button
> fix: disable embed view button if linked document references itself

- packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
Closes: [BS-656](https://linear.app/affine-design/issue/BS-656/card-view-%E7%82%B9%E5%87%BB%E5%90%8E%EF%BC%8C-%E5%8F%AF%E8%83%BD%E4%BC%9A%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0-%E5%BD%93%E5%89%8D%E7%9A%84%E7%8A%B6%E6%80%81%EF%BC%9A-toolbar-%E4%B8%8A%E6%B2%A1%E6%9C%89%E5%AF%B9%E5%BA%94%E7%9A%84%E6%BF%80%E6%B4%BB%E6%A0%B7%E5%BC%8F)
This issue happen on re-render editor but selection is not changed in AFFiNE side.
Before:
After:
> fix(blocks): model of embed card toolbar changed back to the root

- packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
- packages/blocks/src/surface-block/element-model/group.ts
- packages/blocks/src/surface-block/element-model/mindmap.ts
- tests/edgeless/linked-doc.spec.ts
- tests/utils/actions/edgeless.ts
Fix issue [BS-625](https://linear.app/affine-design/issue/BS-625).
- Add `SerializedMindmapElement ` typescript interface.
- Override `propsToY` in class ` MindmapElementModel` to transfer serialized object to `Y.Map`.
- Add e2e test of create linked doc from mindmap.
https://github.com/toeverything/blocksuite/assets/12724894/ef01a5c4-3b61-4211-b6ee-974d848cb9fa
> fix: create linked doc from mindmap

- packages/blocks/src/database-block/columns/title/text.ts
When the title is set to readonly, `inlineEditor` will set `eventSource` to `contenteditable=false`, causing editing functionality issues.
> fix(blocks): database title affect the global contenteditable

- packages/blocks/src/root-block/widgets/format-bar/config.ts
Fix issue [BS-607](https://linear.app/affine-design/issue/BS-607).
Support create linked doc from text selection.
https://github.com/toeverything/blocksuite/assets/12724894/a86c4d8e-bb2b-4fab-9768-ea99a296b1a6
> fix: can not create linked doc from text selection

- packages/blocks/src/root-block/edgeless/components/text/edgeless-connector-label-editor.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- tests/edgeless/connector.spec.ts
Closes: [BS-678](https://linear.app/affine-design/issue/BS-678/connector-添加-entermod-enter-快捷键)
* `Enter`: enter the label editing state
* `Ctrl-Enter` | `Cmd+Enter` | `Escape`:  exit label editing state and select current connector
> feat(blocks): connector supports shortcut keys for label editing

- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/components/embed-synced-doc-card.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/root-block/root-service.ts
- packages/framework/store/src/store/meta.ts
Fix issue [BS-603](https://linear.app/affine-design/issue/BS-603).
- get `updatedDate` from doc meta data.
- Add observer for `docMetaUpdated` slot, thus the updated time on embed card can be refresh automatically.
- Use `toLocaleString` to show updated date.
https://github.com/toeverything/AFFiNE/pull/7344
https://github.com/toeverything/blocksuite/assets/12724894/eebf9a71-1961-4b81-8afd-f60c12420b13
> fix: doc update time outdated

- packages/blocks/src/embed-synced-doc-block/styles.ts
- tests/embed-synced-doc.spec.ts
Closes: [BS-588](https://linear.app/affine-design/issue/BS-588/embed-view%E4%B8%ADblock%E6%B2%A1%E6%9C%89%E5%85%A8%E9%83%A8%E7%A6%81%E6%AD%A2%E7%BC%96%E8%BE%91) and [BS-601](https://linear.app/affine-design/issue/BS-601/%E5%BE%80synced-block%E9%87%8C%E9%9D%A2%E6%8B%96%E5%86%85%E5%AE%B9%E7%BB%99%E5%87%BA%E4%BA%86%E8%99%9A%E5%81%87%E7%9A%84%E5%8F%AF%E7%BC%96%E8%BE%91%E6%89%BF%E8%AF%BA).
Add `pointer-events: none` to the synced editor host to prevent active and selected status triggered by pointer events.
> fix: bs-588 disable editable contents in synced block

- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-linked-doc-block/styles.ts
- packages/blocks/src/embed-linked-doc-block/utils.ts
Fix issie [BS-663](https://linear.app/affine-design/issue/BS-663). Add error card style for linked doc card.
Loading Card:
| Light Mode   | Dark Mode  |
|  ----  | ----  |
| <img width="1761" alt="截屏2024-06-27 15 09 41" src="https://github.com/toeverything/blocksuite/assets/12724894/e1646dee-30c5-4a4a-a3fa-73fc7ca3bc94">|<img width="1661" alt="截屏2024-06-27 15 10 08" src="https://github.com/toeverything/blocksuite/assets/12724894/0b8553cd-aaa1-4e60-831f-d7319ea9e301">|
| <img width="1784" alt="截屏2024-06-27 15 09 22" src="https://github.com/toeverything/blocksuite/assets/12724894/0ea69b59-ecca-491b-8ad0-b8c1cda3c032">|<img width="1660" alt="截屏2024-06-27 15 10 16" src="https://github.com/toeverything/blocksuite/assets/12724894/0d93a059-eb1f-4da8-86cc-a47f1a0d93a6">|
Error Card:
| Light Mode …
> fix: error linked doc card view UI

- packages/blocks/src/_common/components/filterable-list/index.ts
- packages/blocks/src/_common/components/portal.ts
- packages/blocks/src/code-block/styles.ts
- packages/blocks/src/root-block/widgets/code-language-list/components/lang-button.ts
- packages/blocks/src/root-block/widgets/code-language-list/index.ts
- packages/blocks/src/root-block/widgets/code-toolbar/components/code-toolbar.ts
- packages/blocks/src/root-block/widgets/code-toolbar/index.ts
- packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
- packages/blocks/src/root-block/widgets/image-toolbar/index.ts
- packages/framework/block-std/src/view/element/lit-host.ts
Create a new stacking context at the `editor-host`, allowing popups to use it as the parent context instead of `body`.
- editor-host
- code-block
- language-list-btn-portal *
- code-toolbar-portal *
- image-block
- image-toolbar-portal *
- lang-list
- code-more-menu *
- image-more-menu *
- All items marked with "*" will share the same stacking context at `editor-host`
[BS-667](https://linear.app/affine-design/issue/BS-667/code-and-image-block-popover-z-index-issues-in-affine)
[BS-635](https://linear.app/affine-design/issue/BS-635/center-peek-%E4%B8%AD%E7%9A%84-code-block-%E4%B8%8D%E6%98%BE%E7%A4%BA-toolbar-%E7%AD%89-widget)
https://github.com/toeverything/blocksuite/assets/123532141/6bfdff21-4d3f-4fb1-afd2-09b9ceb32130
https://github.com/toeverything/blocksuite/assets/123532141/1182f012-db …
> fix(blocks): code block and image block pop-over z-index issues in affine

- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/specs/utils/spec-builder.ts
- tests/embed-synced-doc.spec.ts
Closes: [BS-644](https://linear.app/affine-design/issue/BS-644/%E6%9C%AA%E5%A4%84%E7%90%86%E5%A4%9A%E5%B1%82%E5%B5%8C%E5%A5%97%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%88%E5%8F%AA%E4%B8%8B%E9%92%BB%E4%B8%80%E5%B1%82%EF%BC%89)
Add a state to control the depth of nested synced block.
@akumatus We may need a better solution to communicate between editors.
> fix: bs-644 nested synced doc can have one depth at most

- packages/blocks/src/root-block/widgets/slash-menu/index.ts
Remove <kbd>Shift</kbd> in slash menu trigger detection.
According to https://en.wikipedia.org/wiki/Keyboard_layout, there are some keyboard layouts that require the <kbd>Shift</kbd> key to input a slash character.
This case can not be easily tested by playwright since keyboard layout managered by system.
Before (test AZERTY):
https://github.com/toeverything/blocksuite/assets/20479050/224e2907-5b99-4c73-8568-af2ff9b3c8e4
After (test QWERT and AZERTY):
https://github.com/toeverything/blocksuite/assets/20479050/6f45912a-6c79-439d-ae81-d5c73c0e1274
> fix(blocks): support azerty keyboard layout for slashmenu

- packages/blocks/src/root-block/widgets/slash-menu/config.ts
- packages/blocks/src/root-block/widgets/slash-menu/index.ts
- tests/slash-menu.spec.ts
Closes:  #7451
Use the `beforeInput` event instead of the `keyDown` event, as the latter cannot capture the actual input character when IME are active. For example, when pressing <kbd>/</kbd> with Sogou IME, the actual character input is `、`, but at this time `event.key` is equal to `Process`.
After using the `beforeInput` event, there is no need to check whether various modifier keys are pressed, such as in non-English keyboard layouts, like the French keyboard (`Shift + Slash = /`) and the German keyboard (`Shift + 7 = /`).
However, in the new implementation with Chinese IME actived, pressing<kbd> \ </kbd> key also tirgger slash menu becasue of `、` inputed.
> fix(blocks): ime compatibility of slash menu

- packages/blocks/src/_common/components/rich-text/keymap/container.ts
- packages/framework/inline/src/services/range.ts
- tests/hotkey.spec.ts
Close [BS-648](https://linear.app/affine-design/issue/BS-648/cursor-unexpectedly-moves-out-of-code-block-when-using-up-arrow-key)
> fix: cursor moves out of blocks with multiple lines when using arrow keys

- packages/blocks/src/_common/utils/render-linked-doc.ts
Set `isNoteContentEmpty` after `filterTextModel` logic, which is more accurate to the content displayed.
|   | Page  | Edgeless  | 
|  ----  | ----  | ----  |
| Linked Page  | <img width="1035" alt="截屏2024-07-02 10 45 38" src="https://github.com/toeverything/blocksuite/assets/12724894/f38cac45-4e28-452b-81f3-f3426287a17c"> |<img width="867" alt="截屏2024-07-02 10 46 11" src="https://github.com/toeverything/blocksuite/assets/12724894/1cb52983-3978-4b37-99fa-661ba19fcf79"> |
| Linked Edgeless | <img width="978" alt="截屏2024-07-02 10 47 40" src="https://github.com/toeverything/blocksuite/assets/12724894/c847712c-4a5d-44a4-9554-fbc4c2fa29a9">|<img width="941" alt="截屏2024-07-02 10 47 50" src="https://github.com/toeverything/blocksuite/assets/12724894/b4a0ff74-309b-4194-9857-d46d6e83e330">|
> fix: empty linked doc display

- examples/pnpm-lock.yaml
- examples/react-indexeddb/src/editor/provider/provider.ts
- examples/react-sqlite/package.json
- examples/react-sqlite/src/editor/provider/provider.ts
- examples/vanilla-indexeddb/src/main.ts
- examples/vue-basic/package.json
Following #7455, this PR fixes following examples:
- `react-indexeddb`
- `react-sqlite`
- `vanilla-indexeddb`
The `react-sqlite` fix requires rolling back to `1.10.2`.
> fix(examples): provider init pattern and sqlite deps

- examples/angular-basic/package.json
- examples/preact-basic/package.json
- examples/react-basic-next/package.json
- examples/react-basic/package.json
- examples/react-indexeddb/package.json
- examples/react-sqlite/package.json
- examples/react-websocket/package.json
- examples/solid-basic/package.json
- examples/svelte-basic/package.json
- examples/vanilla-indexeddb/package.json
- examples/vue-basic/package.json
- packages/docs/guide/quick-start.md
Remaining examples that are not compatible with StackBlitz yet:
* `react-basic-next`
* `angular-basic`
> docs: switch to stackblitz for online examples

- packages/blocks/src/root-block/edgeless/controllers/tools/shape-tool.ts
Dragging area is null when switch to edgeless mode firstly.
https://github.com/toeverything/blocksuite/assets/20479050/df5cbceb-0f44-4e5a-9db4-a9dbc9d7c448
> fix(edgeless): dragging area of shape tool is null

- packages/blocks/src/edgeless-text/edgeless-text-service.ts
- packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts
- packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
- packages/blocks/src/root-block/edgeless/components/presentation/edgeless-navigator-black-background.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/common/observe-last-props.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-dense-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/present/navigator-setting-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/presentation-toolbar.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/edgeless/utils/hotkey-utils.ts
- packages/blocks/src/root-block/remote-color-manager/remote-color-manager.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
- packages/blocks/src/root-block/widgets/pie-menu/config.ts
- packages/blocks/src/surface-block/managers/edit-session.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/presets/src/fragments/bi-directional-link/bi-directional-link-panel.ts
- packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
- packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
- packages/presets/src/fragments/frame-panel/header/frames-setting-menu.ts
Support memory for style changes to edgeless text and optimize some naming in `EditPropsStore`.
Before:
https://github.com/toeverything/blocksuite/assets/50035259/cd9656c9-b79c-427a-98db-dc0484ec4295
After:
https://github.com/toeverything/blocksuite/assets/50035259/cbfb6c45-7768-4f73-9952-88714c25d89b
> feat(edgeless): support using last props for edgeless text

- packages/blocks/src/_common/components/rich-text/rich-text.ts
As described here https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#value.
> `If the pressed key is the B key, the returned value is the string "b". However, if the Shift key is pressed at the same time (so shiftKey is true), the returned value is the string "B"`
This means that when using the rich-text component you are unable to redo since pressing `ctrl + shift + z` makes `e.key == 'Z'`.
It also means that after pressing `CapsLock` pressing `ctrl + z` to undo doesn't work since `CapsLock` makes e.key be uppercase 'Z'.
Simple fix by accepting either lowercase or uppercase `Z`.
> fix(blocks): rich-text can't redo since pressing shift causes e.key to be uppercase

- packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
- tests/edgeless/shape.spec.ts
closes BS-747
Before:
https://github.com/toeverything/blocksuite/assets/20479050/d74d02e6-ef1c-472d-ab61-903dc693d091
After:
https://github.com/toeverything/blocksuite/assets/20479050/a93866e2-6d9b-43a8-bf8f-c499e53e47b2
> fix(edgeless): exit shape text editing by pressing Escape

- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
- tests/edgeless/mindmap.spec.ts
closes [BS-739](https://linear.app/affine-design/issue/BS-739/%E6%89%93%E5%BC%80mindmap%E8%8F%9C%E5%8D%95%E5%90%8E%EF%BC%8C%E6%97%A0%E6%B3%95%E9%80%89%E4%B8%AD%E4%BB%BB%E4%BD%95yuan%E7%B4%A0)
Before:
https://github.com/toeverything/blocksuite/assets/20479050/387b6a8f-851f-4ca8-bd1c-3eaa58ada9fe
After:
https://github.com/toeverything/blocksuite/assets/20479050/735ff196-72d9-4acf-8688-40d26e63ce21
> fix(edgeless): elements should be clickable after opening mindmap menu

- packages/blocks/src/database-block/data-view/view/presets/table/components/row.ts
[BS-756](https://linear.app/affine-design/issue/BS-756/database-%E7%BC%96%E8%BE%91%E6%96%87%E6%9C%AC%E9%A1%B9%E6%97%B6%EF%BC%8C%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95%E5%BC%B9%E5%87%BA%E4%BD%8D%E7%BD%AE%E4%B8%8D%E5%AF%B9)
> fix(database): popup menu wrong position when cell is in editing state

- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
Now when changing `readonly` the `edgeless-element-toolbar-widget` does not hide
> fix(edgeless): rerender `edgeless-element-toolbar-widget` when `readonly` changes

- packages/blocks/src/__tests__/common/string.unit.spec.ts
- packages/blocks/src/_common/utils/string.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
- tests/bookmark.spec.ts
- tests/slash-menu.spec.ts
closes [BS-774](https://github.com/toeverything/blocksuite/pull/7519)
- Use max common length of substring to sort query result of slash menu
- substring matching socre function and unit tests
```ts
/**
* Calculate the score of the substring match.
* s = [0.5, 1] if the query is a substring of the name
* s = (0, 0.5) if there exists a common non-maximal length substring
* s = 0 if there is no match
*
* s is greater if the query has a longer substring.
*/
export function substringMatchScore(name: string, query: string);
```
> chore(blocks): sort query result of slash menu by substring score

- packages/blocks/src/_common/components/button.ts
Fix issue [BS-793](https://linear.app/affine-design/issue/BS-793).
| Before | After |
| --- | --- |
|
> fix: icon button flex-shrink and text-overflow

- packages/blocks/src/_common/adapters/html.ts
- packages/blocks/src/root-block/clipboard/index.ts
- packages/blocks/src/root-block/clipboard/middlewares/paste.ts
- tests/clipboard.spec.ts
This closes #6366, closes BS-139.
This PR merges part of snapshot to the `fromPointState.model`. The first snapshot is deleted after being merged to the `fromPointState.model`, so the snapshot could probably be an empty array.
We delete snapshot from snapshots instead of block from blocks mainly because that if blocks are deleted immediately after they are created will cause errors as operations in `connectcallback` does not have any corresponding blocks attached.
> fix(blocks): preserve block ids when pasting

- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
[BS-783](https://linear.app/affine-design/issue/BS-783/edgeless-more-button-error-when-add-new-block)
> fix(blocks): edgeless more button error

- packages/blocks/src/_common/components/button.ts
- packages/blocks/src/_common/inline/presets/nodes/reference-node/reference-popup.ts
- packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts
- packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- tests/utils/actions/linked-doc.ts
Fix issue [BS-721](https://linear.app/affine-design/issue/BS-721).
Cause we have css style like:
```
:host([hover='false']) {
background: transparent;
}
```
If the `hover` is used as boolean attribute binding, the attribute will be added or removed based on the boolean value. Which means `host([hover='false'])` style will never happened to work.
- Make the `hover` attribute treated as a string
- Use standard attribute binding instead of boolean attribute binding or property binding
> fix: hover style of icon button

- packages/blocks/src/image-block/utils.ts
When adding images using slash menu, there's always an error from "fetchImageBlob" function.
The reason is that uploaded status was set before the image uploading process was completed, as shown in the snapshot below. 
Considering there is a "setImageUploaded(blockId);" in the subsequent "finally" block, the same code in "try" block before upload was removed to solve.
> fix: image uploaded status was set unexpectedly

- packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-image-button.ts
Closes: [BS-769](https://linear.app/affine-design/issue/BS-769/为-image-element-toolbar-添加下载入口)
> feat(blocks): add download button on attachment and image toolbar

- packages/blocks/src/_common/components/toolbar/menu-button.ts
- packages/blocks/src/_common/components/toolbar/separator.ts
- packages/blocks/src/_common/components/toolbar/toolbar.ts
- packages/blocks/src/_common/components/toolbar/utils.ts
- packages/blocks/src/_common/styles.ts
- packages/blocks/src/_common/utils/button-popper.ts
- packages/blocks/src/root-block/edgeless/components/panel/font-weight-and-style-panel.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/present/frame-order-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/present/navigator-setting-button.ts
- packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
- packages/blocks/src/root-block/widgets/image-toolbar/styles.ts
- packages/blocks/src/root-block/widgets/image-toolbar/utils.ts
- packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
- packages/presets/src/fragments/outline-panel/card/outline-card.ts
- packages/presets/src/fragments/outline-panel/header/outline-panel-header.ts
Closes: [BS-743](https://linear.app/affine-design/issue/BS-743/image-toolbar)
You can check the latest status in https://github.com/toeverything/blocksuite/pull/7513.
> refactor(blocks): refine image toolbar

- packages/blocks/src/image-block/components/page-image-block.ts
- packages/blocks/src/image-block/image-block.ts
Related: [BS-798](https://linear.app/affine-design/issue/BS-798/%E5%8F%AA%E8%AF%BB%E6%A8%A1%E5%BC%8F%E4%B8%8B%E6%97%A0%E6%B3%95%E5%8F%8C%E5%87%BB%E6%94%BE%E5%A4%A7%E5%9B%BE%E7%89%87)
- bypass click event handler when shift key is pressed so that the image can be peek
- check readonly for some key like `Backspace`
PS: Since peek view service is implemented in AFFiNE side, so the e2e test is not included in this PR
> fix(blocks): image can not be peek by shift click

- packages/blocks/src/_common/components/toolbar/icon-button.ts
- packages/blocks/src/_common/components/toolbar/menu-button.ts
- packages/blocks/src/_common/components/toolbar/toolbar.ts
- packages/blocks/src/_common/components/utils.ts
- packages/blocks/src/root-block/widgets/format-bar/components/config-renderer.ts
- packages/blocks/src/root-block/widgets/format-bar/components/highlight/highlight-button.ts
- packages/blocks/src/root-block/widgets/format-bar/components/paragraph-button.ts
- packages/blocks/src/root-block/widgets/format-bar/config.ts
- packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
- packages/blocks/src/root-block/widgets/format-bar/styles.ts
- tests/format-bar.spec.ts
Closes: [BS-741](https://linear.app/affine-design/issue/BS-741/format-bar)
> chore(blocks): refine format bar

- packages/playground/examples/store/main.ts
- packages/playground/examples/store/schema.ts
Close: #7509
There are some issues in the store example:
- The demo miss a `role: root` model (`todo:container`  need a parent)
- The todolist rendering is always one item behind. See the comment below.
> fix(examples): missing root model and incorrect rendering order

- packages/blocks/src/root-block/widgets/index.ts
- packages/blocks/src/root-block/widgets/slash-menu/index.ts
allows affine to overwrite functions easier.
> chore(blocks): expose insertContent utility

- packages/blocks/src/_common/configs/quick-action/config.ts
- packages/blocks/src/root-block/clipboard/index.ts
- packages/blocks/src/root-block/commands/model-crud/copy-selected-models.ts
- packages/blocks/src/root-block/commands/model-crud/draft-selected-models.ts
- packages/blocks/src/root-block/commands/model-crud/index.ts
- packages/blocks/src/root-block/root-service.ts
- packages/blocks/src/root-block/widgets/format-bar/config.ts
- packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
- packages/framework/block-std/src/clipboard/index.ts
- tests/format-bar.spec.ts
- tests/utils/query.ts
Closes: [BS-814](https://linear.app/affine-design/issue/BS-814/在-format-bar-上-添加-more-menu-button)
Adds `more` menu button on the format-bar.
* copy
* duplicate
* delete
> feat(blocks): add more menu button on format bar

- packages/blocks/src/_common/components/utils.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/slash-menu/index.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
Fix issue [BS-792](https://linear.app/affine-design/issue/BS-792).
- Make the `createKeydownObserver` only observe keydown event, not coupled with query parsing logic.
- Use `getQuery` to get the latest query results.
> refactor: keydown observer and get query

- packages/blocks/src/_common/components/rich-text/rich-text-operations.ts
- packages/blocks/src/code-block/code-block.ts
- packages/framework/inline/src/services/text.ts
- packages/framework/store/src/__tests__/collection.unit.spec.ts
- packages/framework/store/src/yjs/awareness.ts
- tests/basic.spec.ts
- tests/code.spec.ts
- tests/paragraph.spec.ts
Fix [BS-821](https://linear.app/affine-design/issue/BS-821/playground-%E5%88%87%E6%8D%A2readonly%E5%90%8E%EF%BC%8C%E4%BE%9D%E7%84%B6%E5%8F%AF%E4%BB%A5%E7%BC%96%E8%BE%91%E6%AE%B5%E8%90%BD)
https://github.com/toeverything/blocksuite/assets/20479050/805588a5-cf82-4ae3-bc61-a9f19d996f23
https://github.com/toeverything/blocksuite/assets/20479050/1d6c1ca2-25c9-4dbc-a2fd-b73e5509c3a9
https://github.com/toeverything/blocksuite/assets/20479050/70868516-ff2f-4065-a5e7-9d18553aa7d3
https://github.com/toeverything/blocksuite/assets/20479050/9ffa6580-b2e8-47d0-975e-46762896f58a
> fix(blocks): paragraph and code block can be inputed after switching to readonly

- packages/blocks/src/database-block/data-view/column/base-cell.ts
- packages/blocks/src/database-block/data-view/common/component/overflow/overflow.ts
- packages/blocks/src/database-block/data-view/utils/uni-component/render-template.ts
- packages/blocks/src/database-block/data-view/utils/uni-component/uni-component.ts
- packages/blocks/src/database-block/data-view/view/data-view-base.ts
- packages/blocks/src/database-block/data-view/view/presets/table/components/cell-container.ts
- packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/column-header.ts
- packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/database-header-column.ts
- packages/blocks/src/database-block/data-view/view/presets/table/components/row.ts
- packages/blocks/src/database-block/data-view/view/presets/table/controller/selection.ts
- packages/blocks/src/database-block/data-view/view/presets/table/group.ts
- packages/blocks/src/database-block/data-view/widget/views-bar/views.ts
- packages/blocks/src/database-block/data-view/widget/widget-base.ts
- packages/blocks/src/database-block/database-block.ts
- tests/database/database.spec.ts
- tests/utils/actions/click.ts
Fix [BS-821](https://linear.app/affine-design/issue/BS-821/playground-%E5%88%87%E6%8D%A2readonly%E5%90%8E%EF%BC%8C%E9%83%A8%E5%88%86block%E4%BB%8D%E5%8F%AF%E4%BB%A5%E8%A2%AB%E7%BC%96%E8%BE%91)
- Wrap some database components with `SignalWatcher` to react to the change of `doc.readonly`
- Add e2e tests for readonly mode database
https://github.com/toeverything/blocksuite/assets/20479050/809837f5-1e1b-41b8-bb8f-60b1921993a6
https://github.com/toeverything/blocksuite/assets/20479050/da4b0c7a-ee0f-4dea-8145-175a9e3f5a63
> fix(blocks): signal based readonly mode of database

- packages/blocks/src/list-block/list-block.ts
- packages/blocks/src/list-block/styles.ts
- packages/blocks/src/list-block/utils/get-list-icon.ts
- tests/list.spec.ts
Fix [BS-821](https://linear.app/affine-design/issue/BS-821/playground-%E5%88%87%E6%8D%A2readonly%E5%90%8E%EF%BC%8C%E9%83%A8%E5%88%86block%E4%BB%8D%E5%8F%AF%E4%BB%A5%E8%A2%AB%E7%BC%96%E8%BE%91)
> fix(blocks): can click todo list in readonly mode

- packages/blocks/src/paragraph-block/paragraph-block.ts
- packages/framework/store/src/__tests__/block.unit.spec.ts
- packages/framework/store/src/schema/base.ts
- packages/framework/store/src/store/doc/block.ts
Add signal props for model.
This pr automatically add a signal version property for every prop
```ts
declare const model: BlockModel<{ name: string }>;
assert(typeof model.name$.value === 'string'); // true
model.name = 'hello';
assert(model.name$.value === 'hello'); // true
assert(model.yBlock.get('prop:name') === 'hello'); // true
model.name$.value = 'world';
assert(model.name === 'world'); // true
assert(model.yBlock.get('prop:name') === 'world'); // true
model.yBlock.set('prop:name', 'blocksuite');
assert(model.name$.value === 'blocksuite'); // true
```
> feat(store): add signal props for model

- packages/blocks/src/_common/components/toolbar/menu-button.ts
- packages/blocks/src/_common/inline/presets/nodes/link-node/link-popup/styles.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-button.ts
- packages/blocks/src/root-block/widgets/format-bar/config.ts
- packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
* Set `min-width` and `max-width` for the link
* Set `min-width` only when `data-size` attribute is turned on
* Unify the minimum width of the more menu
* <img width="445" alt="Screenshot 2024-07-12 at 20 19 04" src="https://github.com/user-attachments/assets/cc331f56-3285-475d-a121-41d61ca72a1b">
* <img width="283" alt="Screenshot 2024-07-12 at 20 19 59" src="https://github.com/user-attachments/assets/ae6859b7-5aba-485a-a8df-c30a32c25780">
* <img width="507" alt="Screenshot 2024-07-12 at 20 19 19" src="https://github.com/user-attachments/assets/2e787ab0-250a-4ce1-87cc-04e09a59f43c">
* <img width="346" alt="Screenshot 2024-07-12 at 20 17 16" src="https://github.com/user-attachments/assets/f90599ce-1b26-44bf-b268-55eae94f8945">
* <img width="280" alt="Screenshot 2024-07-12 at 20 18 36" …
> fix(blocks): improve menu width

- packages/blocks/src/_common/components/ai-item/styles.ts
- packages/blocks/src/database-block/data-view/view/presets/table/components/column-header/number-format-bar.ts
Fix [BS-698](https://linear.app/affine-design/issue/BS-698/%E6%94%B9%E6%8E%89and%E9%80%89%E6%8B%A9%E5%99%A8)
Using regex to find & selector.
```
css`(?:[\s\S]|[\n])[^`]*&(?:[\s\S]|[\n])[^`]*`
```
This regular expression is designed to match a specific pattern in text, commonly used in processing CSS or similar textual data. Let's break down the expression to understand it better:
1. `css``: This part specifies that the regular expression should start matching text with "css`".
2. `(?:[\s\S]|[\n])`: This is a non-capturing group (indicated by `?:`), which matches any single character, including whitespace and newline characters. `[\s\S]` means to match any whitespace or non-whitespace character, essentially matching all characters, while `[\n]` explicitly matches a newline character. The …
> fix(blocks): remove & selector

- packages/blocks/src/root-block/clipboard/middlewares/paste.ts
- tests/clipboard.spec.ts
``` html
// clipboard data:
<paragraph aaa>
<image>
// paste to: (| is cursor)
<paragraph |bbb>
// before
<paragraph aaa>
<image>
// after
<paragraph aaabbb>
<image>
```
> fix: paste end with image will lose the focus line text

- packages/framework/store/src/__tests__/block.unit.spec.ts
- packages/framework/store/src/indexer/base.ts
- packages/framework/store/src/indexer/search.ts
- packages/framework/store/src/schema/base.ts
- packages/framework/store/src/schema/schema.ts
- packages/framework/store/src/store/doc/block/index.ts
- packages/framework/store/src/store/doc/block/sync-controller.ts
- packages/framework/store/src/store/doc/block/types.ts
- packages/framework/store/src/store/doc/doc.ts
- packages/framework/store/src/store/doc/index.ts
- packages/framework/store/src/utils/utils.ts
Extract sync controller from block.
Block will provide features more than create model. It will also provide states and crud API in the future.
This will also make the logic easier to understand.
> refactor(store): extract sync controller from block

- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
Close [BS-767](https://linear.app/affine-design/issue/BS-767/safari%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%AD%EF%BC%8Cedgeless-note%E5%9C%A8%E7%99%BD%E6%9D%BF%E4%B8%8A%E4%B8%8D%E6%98%BE%E7%A4%BA)
In Safari, If a custom element does not explicitly set its size, then its `offsetWidth` and `offsetHeight` are 0, which make the following computation error
https://github.com/toeverything/blocksuite/blob/4d01083bbc2a6f179ce28bf4f3f9062e33367a15/packages/blocks/src/root-block/edgeless/utils/viewport.ts#L338-L345
https://github.com/toeverything/blocksuite/blob/4d01083bbc2a6f179ce28bf4f3f9062e33367a15/packages/blocks/src/root-block/edgeless/utils/viewport.ts#L77-L87
PS: This behavior is different from chrome. I think it may be a bug of Safari
https://github.com/user-attachments/assets/8d4fd257-0be0-498a-8 …
> fix(edgeless): offsetWidth of edgeless root is zero in Safari

- packages/blocks/src/root-block/edgeless/edgeless-block-model.ts
- packages/blocks/src/surface-block/element-model/base.ts
- packages/framework/block-std/package.json
- packages/framework/block-std/src/index.ts
- packages/presets/src/blocks/ai-chat-block/ai-chat-model.ts
Edgeless related entities should be exported under the `block-std/edgeless` scope.
> refactor(std): add block-std/edgeless scope

- packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
- packages/blocks/src/root-block/index.ts
- packages/blocks/src/root-block/page/page-root-spec.ts
- packages/blocks/src/root-block/types.ts
- packages/blocks/src/root-block/widgets/index.ts
- packages/blocks/src/root-block/widgets/linked-doc/config.ts
- packages/blocks/src/root-block/widgets/linked-doc/index.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/linked-doc/styles.ts
- packages/blocks/src/root-block/widgets/slash-menu/config.ts
- packages/blocks/src/specs/group/edgeless.ts
- packages/blocks/src/specs/group/page.ts
- packages/framework/block-std/src/spec/spec-store.ts
- packages/framework/block-std/src/spec/type.ts
Close issue [BS-863](https://linear.app/affine-design/issue/BS-863).
Related PR in [AFFiNE](https://github.com/toeverything/AFFiNE/pull/7554).
- Add `config` field to `BlockSpec` to allows personalized block customization.
```typescript
interface BlockSpec {
schema: BlockSchemaType;
view: BlockView<WidgetNames>;
config?: BlockConfig;
}
// get config by falvour
this.std.spec.getConfig(this.flavour)
```
- Add `linkedWidget` config in `RootBlockSpec`
- Refactor `linked-doc-popover` to support customization
- `getMenus` returns an observable array
- Add `commands` field to `BlockSpec` and encapsulated `insertLinkedNode` into a command
- Refactor `linked-doc-popover` to adapt to more scenarios
> feat: linked menu support configuration

- packages/playground/apps/_common/components/custom-frame-panel.ts
- packages/playground/apps/_common/components/custom-outline-panel.ts
- packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
- packages/presets/src/fragments/frame-panel/card/frame-card-title-editor.ts
- packages/presets/src/fragments/frame-panel/card/frame-card-title.ts
- packages/presets/src/fragments/frame-panel/card/frame-card.ts
- packages/presets/src/fragments/frame-panel/frame-panel.ts
- packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
- packages/presets/src/fragments/frame-panel/header/frames-setting-menu.ts
- packages/presets/src/fragments/frame-panel/index.ts
- packages/presets/src/fragments/index.ts
- packages/presets/src/fragments/outline-panel/body/outline-notice.ts
- packages/presets/src/fragments/outline-panel/body/outline-panel-body.ts
- packages/presets/src/fragments/outline-panel/card/outline-card.ts
- packages/presets/src/fragments/outline-panel/card/outline-preview.ts
- packages/presets/src/fragments/outline-panel/header/outline-panel-header.ts
- packages/presets/src/fragments/outline-panel/header/outline-setting-menu.ts
- packages/presets/src/fragments/outline-panel/index.ts
- packages/presets/src/fragments/outline-panel/outline-panel.ts
- tests/fragments/frame-panel.spec.ts
Close: [BS-585](https://linear.app/affine-design/issue/BS-585/更新affine侧lit自定义yuan素的写法)
- remove `registerXXXComponet` and use `customElement(xxx)` for `affine-frame-panel` and `affine-outline-panel`
- Rename 
- `frame-panel-xxx` -> `affine-frame-panel-xxx`
- `outline-panel-xxx` -> `affine-outline-opanel-xxx`
> refactor(presets): remove frame and outline panel register function

- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/embed-figma-block/embed-figma-block.ts
- packages/blocks/src/embed-html-block/embed-html-block.ts
- packages/blocks/src/embed-loom-block/embed-loom-block.ts
- packages/blocks/src/embed-youtube-block/embed-youtube-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
- packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
- packages/framework/block-std/src/event/control/pointer.ts
- packages/framework/block-std/src/event/dispatcher.ts
- packages/framework/block-std/src/event/state/pointer.ts
- packages/presets/src/__tests__/utils/common.ts
This PR enables multi-pointer event support. The previous implementation did not consider multi-pointer inputs, such as those from touchscreen devices, which resulted in discontinuous pointer inputs.
- **Decoupled Custom Pointer Event Creation Logic**: The logic for creating pointer-based custom events has been decoupled from the previous implementation in the `PointerControl` class. This change involves the separation into different controllers:
- `PointerEventForward`: Forward `pointerXXX` events.
- `ClickController`: Manages `xxxClick` events.
- `DragController`: Manages `dragXXX` events.
- `PinchController` *(new)*: Manages `pinch` events.
- **Support for Multiple Pointers**:
- Enhanced the handling of previous events to support multiple pointers.
- Introduced a new class …
> feat(std): multi pointers control support

- packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
Closes: [BS-870](https://linear.app/affine-design/issue/BS-870/surface-ref-toolbar)
> chore(blocks): refine surface ref toolbar

- packages/blocks/src/root-block/edgeless/utils/bound-utils.ts
This closes [BS-824](https://linear.app/affine-design/issue/BS-824).
> fix(edgeless): discard group like model from calculating bound

- packages/blocks/src/edgeless-text/edgeless-text-block.ts
- packages/blocks/src/frame-block/frame-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-preview-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
- packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
- packages/blocks/src/root-block/widgets/surface-ref-toolbar/utils.ts
- packages/blocks/src/specs/preset/edgeless-specs.ts
- packages/blocks/src/specs/utils/spec-builder.ts
- packages/blocks/src/surface-block/surface-block-void.ts
- packages/blocks/src/surface-block/surface-block.ts
- packages/blocks/src/surface-block/surface-spec.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/presets/src/__tests__/edgeless/surface-ref.spec.ts
- Rewrite `surface-ref` block with `renderSpecPortal`
- `SpecBuilder` should append `setup` function on cloned spec rather than the original one.
> refactor: rewrite surface-ref with renderSpecPortal

- packages/blocks/src/root-block/widgets/format-bar/components/config-renderer.ts
Closes: [BS-982](https://linear.app/affine-design/issue/BS-982/这个双线是设计还是-bug)
> fix(blocks): redundant dividers should be filtered out

- packages/blocks/src/root-block/widgets/element-toolbar/change-group-button.ts
- tests/utils/actions/edgeless.ts
> fix(blocks): change group button style

- packages/blocks/src/_common/adapters/html.ts
- packages/blocks/src/_common/adapters/markdown.ts
> fix(blocks): skip to break when undefined before getting assets name

- packages/blocks/src/_common/components/utils.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
- tests/linked-page.spec.ts
- tests/utils/actions/click.ts
Close issue [BS-500](https://linear.app/affine-design/issue/BS-500) and [BS-708](https://linear.app/affine-design/issue/BS-708).
- Do not abort if user press `cmd + v`
- Add listener to `paste` event and process as user input
- Abort if query is `null`, which is an unexpected situation
- Remove assertExists
- Add e2e tests
---
> fix: linked doc popover closes when paste text

- packages/playground/apps/_common/components/custom-outline-viewer.ts
- packages/presets/src/fragments/outline/body/outline-panel-body.ts
- packages/presets/src/fragments/outline/card/outline-preview.ts
- packages/presets/src/fragments/outline/outline-panel.ts
- packages/presets/src/fragments/outline/outline-viewer.ts
- tests/fragments/outline.spec.ts
What changes:
- responsive height of outline viewer ([BS-988](https://linear.app/affine-design/issue/BS-988/ui-bug-响应式没处理),  [BS-989](https://linear.app/affine-design/issue/BS-989/630-ui-issues))
- Fix indicator highlight issue ([BS-994](https://linear.app/affine-design/issue/BS-994/点击-toc-里的-headings-之后，联动高亮不变))
- Update scrollbar style and hover style ([BS-986](https://linear.app/affine-design/issue/BS-986/ui-bug-滚动条坏了), [BS-989](https://linear.app/affine-design/issue/BS-989/630-ui-issues))
- Hide heading of edgeless only note in outline viewer ([BS-992](https://linear.app/affine-design/issue/BS-992/quick-toc-建议隐藏-hidden-content))
- Add more e2e test
> chore: update outline viewer style

- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/root-block/edgeless/utils/consts.ts
- packages/blocks/src/root-block/edgeless/utils/query.ts
Related [BS-957](https://linear.app/affine-design/issue/BS-957/ui-chat-block-的最小尺寸，以及内容压缩)
The implementation should be updated after [BS-1009](https://linear.app/affine-design/issue/BS-1009/支持显式设置最小宽高) completed.
> feat: limit AI Chat block width and height

- packages/blocks/src/surface-block/element-model/utils/mindmap/utils.ts
Closes [BS-917](https://linear.app/affine-design/issue/BS-917/typeerror-cannot-read-properties-of-null-reading-children)
> fix: sentry-77acd79e678f4d8dbee1248ef0648da1

- packages/framework/store/src/index.ts
According to TypeScript 5.5 Announcment [Simplified Reference Directive Declaration Emit](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#simplified-reference-directive-declaration-emit):https://github.com/toeverything/blocksuite/pull/7787/files
> Reference directives are no longer synthesized. User-written reference directives are no longer preserved, unless annotated with a new preserve="true" attribute.
https://github.com/toeverything/blocksuite/blob/9afdb19e6b3f30414ae210ddbcae6c00365c1d62/packages/framework/store/src/index.ts#L1
This line will be removed in build artifact (after https://github.com/toeverything/blocksuite/pull/7762), which make type check failed in AFFiNE side. 
([AFFiNE PR: bump blocksuite](https://github.com/toeverything/AFFiNE/pull/7680); …
> fix: preserve @blocksuite/global declaration

- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/surface-block/managers/layer-manager.ts
- packages/blocks/src/surface-block/mini-mindmap/surface-block.ts
- packages/framework/global/src/exceptions/code.ts
Fix issue [BS-893](https://linear.app/affine-design/issue/BS-893).
- Remove `!` non-null assertion operator
- Init `_viewport` and other properties in constructor
> fix: cannot read properties of undefined (reading 'viewportUpdated')

- packages/blocks/src/root-block/edgeless/components/color-picker/button.ts
- packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
- packages/blocks/src/root-block/edgeless/components/panel/stroke-style-panel.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/brush/brush-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
Closes [BS-1020](https://linear.app/affine-design/issue/BS-1020/当没有启用-color-picker-时，在-edgeless-toolbar-上-transparent-缺失)
> fix(blocks): missing transparent button when color picker is not enabled

- packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
Closes [BS-942](https://linear.app/affine-design/issue/BS-942/typeerror-cannot-read-properties-of-undefined-reading-id)
> fix(blocks): old source or target data may be undefined on connector

- packages/blocks/src/_common/components/utils.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
- packages/framework/store/src/transformer/job.ts
- tests/clipboard.spec.ts
https://github.com/user-attachments/assets/ba1f769f-17bd-4ac0-8efe-1959ad9d8dd2
> fix: paste large content with operational ui

- packages/blocks/src/_common/components/button.ts
- packages/blocks/src/_common/configs/text-conversion.ts
Fix [BS-908](https://linear.app/affine-design/issue/BS-908/slash-menu-ui-bug)
> fix(blocks): text overflow in icon button

- packages/framework/block-std/src/view/utils/inline-range-provider.ts
- tests/selection/native.spec.ts
Fix: [BS-1208](https://linear.app/affine-design/issue/BS-1028/无法向上跨页面拖拽选区)
In the previous implementation, the selection changes would trigger update of inline range of rich text, even though in some cases this range had not changed. It will lead the scroll behavior wired.
Unexpected behavior: `Selection changed -> inlineRangeUpdate -> ScrollToView` for the first dragged `richtext` block
**From top to bottom.** 
https://github.com/user-attachments/assets/82e93da4-a3bf-4f5d-8005-4e0ae15658f9
**From bottom to top**
https://github.com/user-attachments/assets/4d3bf64f-8fa3-4338-bc36-e87df9c20fd9
> fix(std): can not scroll when dragging to selecte

- packages/blocks/src/_common/theme/theme-observer.ts
- packages/blocks/src/root-block/edgeless/components/color-picker/color-picker.ts
- packages/blocks/src/root-block/edgeless/components/color-picker/utils.ts
- packages/blocks/src/root-block/edgeless/components/panel/color-panel.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-tool-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/diamond.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/ellipse.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/rect.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/triangle.ts
- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/utils.ts
- tests/edgeless/color-picker.spec.ts
Closes [BS-1026](https://linear.app/affine-design/issue/BS-1026/优化-color-picker-第一次打开时-ui-问题) [BS-1016](https://linear.app/affine-design/issue/BS-1016/mindmap-和-connector-卡死，缩放失效)
* fix ui update issue when color picker is opened for the first time and lazy listen
* ~~remove `--affine-palette-transparent` and make setting up transparent logic easier~~
* enhance the fallback logic for both `getPropertyValue` and `getColorValue`
> fix(blocks): ui update issue when color picker is opened for the first time

- packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
Closes [BS-1024](https://linear.app/affine-design/issue/BS-1024/通过-auto-complete-创建新yuan素时，背景边框需要同步)
> fix(blocks): connector color when creating new elements via auto complete

- packages/blocks/src/root-block/edgeless/controllers/tools/connector-tool.ts
Closes [BS-911](https://linear.app/affine-design/issue/BS-911/typeerror-cannot-read-properties-of-undefined-reading-id)
> fix(blocks): source my be undefined on connector

- packages/presets/src/fragments/outline/outline-viewer.ts
> fix(presets): disable horizontal scrollbar of outline viewer

- packages/blocks/src/_common/components/ai-item/ai-item-list.ts
- packages/blocks/src/_common/components/ai-item/ai-item.ts
- packages/blocks/src/_common/components/ai-item/ai-sub-item-list.ts
- packages/framework/block-std/src/scope/block-std-scope.ts
- packages/framework/block-std/src/view/decorators/index.ts
- packages/framework/block-std/src/view/decorators/required.ts
- packages/framework/block-std/src/view/element/block-component.ts
- packages/framework/block-std/src/view/element/lit-host.ts
- packages/framework/block-std/src/view/index.ts
- packages/framework/inline/src/components/v-element.ts
- Add `@requiredProperties` decorator for runtime LitComponent property type checking.
- Add some usage examples of this decorator.
- Do not use the `!` non-null assertion operator unless necessary. 
- If the property type is `boolean` or `Array`, you can fill in the default value of `false` or `[]`.
- Be sure to add `@requiredProperties` for property end with `!`.
- Do not use the `!` operator after property with `@query` decorator. The query result for a DOM element probably be null.
If the view layer is refactored by Vue, maybe we don't need this `@requiredProperties`.
> feat: add requiredProperties decorator for runtime LitComponent props type check

- packages/blocks/src/_common/components/toolbar/icon-button.ts
> fix(blocks): active state on icon button

- packages/blocks/src/surface-block/consts.ts
- packages/blocks/src/surface-block/utils/index.ts
- tests/edgeless/basic.spec.ts
[BS-715](https://linear.app/affine-design/issue/BS-715/edgeless-10percent-35percent缩放过于激进)
> fix: step of wheel to zomm viewport is too large

- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-spec.ts
- packages/blocks/src/embed-linked-doc-block/index.ts
- packages/blocks/src/root-block/widgets/linked-doc/index.ts
- packages/framework/block-std/src/spec/spec-store.ts
- Add click handle config for embed linked doc
- Custom click handle in AFFiNE like:
```typescript
{ 
...EmbedLinkedDocBlockSpec,
config: {
handleClick: (e: MouseEvent, host: EditorHost) => {
console.log(e, host);
}
}
},
```
> feat: add click handle config for embed linked doc

- packages/blocks/src/_common/components/utils.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
Fix [BS-1004](https://linear.app/affine-design/issue/BS-974/【ios-safari特供bug】slashmenu-和-menu-无法通过backspace关闭)
use `inlineEditor.slots.onRangeUpdate` instead of `requestAnimationFrame` in `createKeyObserver`, which is used by `slash-menu` and `@ menu` . 
In iOS webkit, using requestAnimationFrame has some timing issues when selection updating.
https://github.com/user-attachments/assets/e337fb8e-29ff-4312-bd81-1359cce40a1c
https://github.com/user-attachments/assets/68dd60f0-8b64-45fd-9ea0-8c72781aec72
> fix(blocks): slash menu and at menu not closed

- packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
> fix(edgeless): limit edgeless toolbar's min-width

- packages/blocks/src/root-block/edgeless/components/color-picker/styles.ts
Closes [BS-1043](https://linear.app/affine-design/issue/BS-1043/ui-bug-颜色面板的圆角应该为-8px)
> chore(blocks): update palette canvas border radius on color picker

- packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
Fixes [BS-880](https://linear.app/affine-design/issue/BS-880/typeerror-cannot-read-properties-of-undefined-reading-getelementbyid)
> fix: copilot mindmap preview rendering error

- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
- tests/edgeless/note/mode.spec.ts
Closes [BS-596](https://linear.app/affine-design/issue/BS-596/edgeless-模式下-image-action-与-image-的间距过大)
* set default spacing to `12px`
* in special cases, the `frame`, `group` and  `shape` has a larger spacing
* fix toolbar below the element
> fix(blocks): spacing between toolbar and elements

- packages/blocks/src/specs/utils/spec-provider.ts
[BS-1011](https://linear.app/affine-design/issue/BS-1011/添加拓展自定义-spec-的方式)
related: [BS-1017](https://linear.app/affine-design/issue/BS-1017/含有chat-block的页面被embed时，embed预览不会渲染chatblock)
extend spec example:
```
const specProvider = SpecProvider.getInstance();
specProvider.extendSpec('edgeless:preview', CustomSpecs);
```
> feat: support extending preview spec

- packages/blocks/src/note-block/note-edgeless-block.ts
- packages/blocks/src/root-block/clipboard/index.ts
- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
- tests/basic.spec.ts
- tests/edgeless/paste-block.spec.ts
- tests/utils/actions/edgeless.ts
- tests/utils/actions/misc.ts
Fix [BS-332](https://linear.app/affine-design/issue/BS-332/bug-长-note-带-image-时报错)
- Update the pasting logic for edgeless note and edgeless-text blocks
- The previous implementation involved manually pasting child blocks, which could lead to potential timing issues. For instance, in the first figure, not all promise function calls in the `forEach` may execute sequentially. For example, pasting
```
<paragraph-1 /> // parent index = 0
<image />       // parent index = 1
<paragraph-2 /> // parent index = 2
```
```
// actual unexpected order, because paste <image /> is time-consuming
<paragraph-1 /> // parent index = 0
<paragraph-2 /> // parent index = 2 <- throw Y doc error 
<image />       // parent index = 1
```
- Update related e2e tests
> fix(edgeless): missing content when pasting edgeless note

- packages/blocks/src/surface-block/canvas-renderer/element-renderer/shape/index.ts
- packages/blocks/src/surface-block/element-model/utils/shape/diamond.ts
- packages/blocks/src/surface-block/element-model/utils/shape/ellipse.ts
- packages/blocks/src/surface-block/element-model/utils/shape/rect.ts
- packages/blocks/src/surface-block/element-model/utils/shape/triangle.ts
- tests/edgeless/shape.spec.ts
Closes [BS-784](https://linear.app/affine-design/issue/BS-784/无背景的shape，无法编辑文本内容)
https://github.com/user-attachments/assets/3bf3779b-a12b-4fcf-a972-b06b9cb6c4e3
> fix(blocks): edit text on shape when it is transprent

- packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
Fixes [BS-736](https://linear.app/affine-design/issue/BS-736/015-beta-release-mindmap-node-doest-support-ime-with-enter)
Fixes [BS-1048](https://linear.app/affine-design/issue/BS-1048/进入-mind-map-的-node-编辑态，shift-enter-应该是软换行)
> fix: mindmap enter key behaviour

- packages/presets/src/fragments/outline/body/outline-panel-body.ts
- packages/presets/src/fragments/outline/outline-panel.ts
- packages/presets/src/fragments/outline/outline-viewer.ts
- packages/presets/src/fragments/outline/utils/scroll.ts
- tests/fragments/outline.spec.ts
Fix [BS-1051](https://linear.app/affine-design/issue/BS-1051/跳转到title后高亮的确是第一个heading，引起误解)
Add highlight for doc title in outline viewer and panel
> fix(presets): doc title not highlight after clicking outline title

- packages/presets/src/fragments/outline/body/outline-panel-body.ts
- packages/presets/src/fragments/outline/card/outline-preview.ts
- packages/presets/src/fragments/outline/outline-viewer.ts
- packages/presets/src/fragments/outline/utils/query.ts
- packages/presets/src/fragments/outline/utils/scroll.ts
- tests/fragments/outline.spec.ts
Close [BS-1052](https://linear.app/affine-design/issue/BS-1052/animation-todo-面板出现和消失动画调整（backlog）)
- refactor `outline-viewer` for better animation, thanks @CatsJuice support
- update  `outline-viewer` open animation
- use smooth scroll to block
https://github.com/user-attachments/assets/d1b0b9fc-a180-4eb6-9e8a-87b8ede9d75e
> chore(presets): update animation of outline viewer

- packages/blocks/src/root-block/widgets/edgeless-remote-selection/index.ts
- tests/edgeless/selection/selection.spec.ts
- tests/utils/asserts.ts
Close [BS-1030](https://linear.app/affine-design/issue/BS-1030/多人协同光标错误的缩放位置)
> fix(edgeless): remote edgeless rect no update

- packages/blocks/src/root-block/types.ts
- packages/blocks/src/root-block/widgets/doc-remote-selection/config.ts
- packages/blocks/src/root-block/widgets/doc-remote-selection/doc-remote-selection.ts
- packages/blocks/src/root-block/widgets/doc-remote-selection/index.ts
- packages/blocks/src/root-block/widgets/doc-remote-selection/utils.ts
Close [BS-993](https://linear.app/affine-design/issue/BS-993/协同用户选择整个block时，不需要显示背景色，只需要显示光标铭牌)
- make the block selection background transparency can be configurable
- make the following blocks remote selection background transparent
- `affine:code`
- `affine:database`
- `affine:image`
- `affine:embed-*`
> feat(blocks): configurable remote block selection bg-transparent

- packages/blocks/src/root-block/clipboard/index.ts
- packages/blocks/src/root-block/clipboard/middlewares/paste.ts
This closes [BS-762](https://linear.app/affine-design/issue/BS-762), closes [BS-1046](https://linear.app/affine-design/issue/BS-1046)
> fix(blocks): image pasting when focusing non-empty block

- packages/affine/shared/src/utils/model.ts
- packages/blocks/src/_common/utils/query.ts
- packages/blocks/src/edgeless-text/edgeless-text-block.ts
- packages/blocks/src/index.ts
- packages/blocks/src/root-block/widgets/drag-handle/drag-handle.ts
- packages/blocks/src/root-block/widgets/drag-handle/utils.ts
- packages/blocks/src/surface-block/surface-block.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/framework/block-std/src/view/element/block-component.ts
- packages/framework/store/src/schema/base.ts
- packages/presets/src/ai/ai-panel.ts
- packages/presets/src/ai/utils/edgeless.ts
- packages/presets/src/ai/utils/editor-actions.ts
- add parent field to `BlockModel`
- rename `parentBlock` to `parentComponent` and refactor the way to get block element from a node
- remove `getNoteId` utils
> refactor: add parent to BlockModel and rename parentBlock

- packages/blocks/src/_common/embed-block-helper/helper.ts
Closes [BS-1075](https://linear.app/affine-design/issue/BS-1075/抓取的-tweet-中-photos-可能是可选)
See https://github.com/FixTweet/FxTwitter/wiki/Status-Fetch-API#embeds
> fix(blocks): photos field is optional in tweet media

- packages/blocks/src/_common/configs/quick-action/config.ts
- packages/blocks/src/embed-linked-doc-block/commands/index.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-config.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-model.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-service.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-spec.ts
- packages/blocks/src/embed-linked-doc-block/index.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
- packages/blocks/src/root-block/keyboard/keyboard-manager.ts
- packages/blocks/src/root-block/page/page-root-spec.ts
- packages/blocks/src/root-block/widgets/format-bar/config.ts
- packages/framework/block-std/src/spec/spec-store.ts
- packages/framework/block-std/src/spec/type.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/utils/editor.ts
- Add commands in `BlockSpec`, which can be easily expanded externally
- Register declared commands in `spec-store`
- Refactor `embed-linked-doc-block` and remove useless service
> feat: add commands to BlockSpec and register commands in spec store

- packages/blocks/src/root-block/widgets/linked-doc/index.ts
Fix [BS-1081](https://linear.app/affine-design/issue/BS-1081/某些键盘布局唤不起link-doc-面板)
- Remove `isControlledKeyboardEvent` detection since inputting `@` or `[` need modified with right <kbd>⌥</kbd> or right <kbd>Alt</kbd>(a.k.a <kbd>AltGr</kbd>) in some keyboard layout, such as France layout.
- Move trigger detection after `inlineRange` updated, because  detecting on the inputed content is better than pressed key
- Add `compositionend` for IME compatibility
https://github.com/user-attachments/assets/538f3846-c19b-4125-a28d-f9747f8ffc5c
https://github.com/user-attachments/assets/e743f59f-ed8a-4986-b91e-eb272196bf18
> fix(blocks): fix IME and keyboard layout issues of linked-doc-popover

- packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
Closes [BS-1163](https://linear.app/affine-design/issue/BS-1163/[bug]：通过端点拖拽新的-shape-时-connector-不显示)
> fix(blocks): should drop alpha value when dragging endpoint

- packages/blocks/src/edgeless-text/commands/index.ts
- packages/blocks/src/edgeless-text/commands/insert-edgeless-text.ts
- packages/blocks/src/edgeless-text/edgeless-text-service.ts
- packages/blocks/src/edgeless-text/edgeless-text-spec.ts
- packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
- packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
- packages/blocks/src/root-block/edgeless/controllers/tools/text-tool.ts
- Refactor `initEdgelessTextBlock` function to `addEdgelessTextBlockCommand`
- Remove the function's dependent parameter `edgeless:EdgelessRootBlockComponent`
> refactor: add edgeless text block command

- packages/blocks/src/_common/edgeless/note/get-last-note.ts
- packages/blocks/src/_common/embed-block-helper/insert-embed-card.ts
- packages/blocks/src/bookmark-block/bookmark-spec.ts
- packages/blocks/src/bookmark-block/commands/index.ts
- packages/blocks/src/bookmark-block/commands/insert-bookmark.ts
- packages/blocks/src/edgeless-text/commands/index.ts
- packages/blocks/src/edgeless-text/commands/insert-edgeless-text.ts
- packages/blocks/src/embed-linked-doc-block/commands/index.ts
- packages/blocks/src/embed-linked-doc-block/commands/insert-embed-linked-doc.ts
- packages/blocks/src/embed-linked-doc-block/commands/insert-link-by-quick-search.ts
- packages/blocks/src/paragraph-block/commands/append-paragraph.ts
- packages/blocks/src/paragraph-block/commands/index.ts
- packages/blocks/src/paragraph-block/paragraph-spec.ts
- packages/blocks/src/root-block/edgeless/components/auto-complete/auto-complete-panel.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/link/link-dense-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/link/link-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
- packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
- packages/blocks/src/root-block/edgeless/controllers/tools/text-tool.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/root-service.ts
- packages/blocks/src/surface-block/commands/reassociate-connectors.ts
- packages/blocks/src/surface-block/surface-spec.ts
- In `RootService`
- Refactor `_getLastNoteBlock ` to `getLastNoteBlock` utils
- Refactor `_insertCard` to `insertEmbedCard` utils
- Refactor `insertLinkByQuickSearch` to `insertLinkByQuickSearch` command
- Refactor `appendParagraph` to `appendParagraph` command
- Refactor `_insertLink` to `insertBookmark` command
- Refactor `_insertDoc` to `insertEmbedLinkedDoc` command
> refactor: separate RootService to commands and utils

- packages/framework/store/src/utils/utils.ts
- packages/playground/apps/_common/components/debug-menu.ts
- packages/playground/apps/_common/components/quick-edgeless-menu.ts
The legacy `Share URL` feature in playground is not maintained to my knowledge.
> chore(playground): remove legacy share url entry

- packages/presets/src/editors/editor-container.ts
> fix(playground): dark mode style inconsistence

- packages/framework/block-std/src/__tests__/editor-host.unit.spec.ts
- packages/framework/block-std/src/__tests__/test-block.ts
- packages/framework/block-std/src/__tests__/test-editor.ts
- packages/framework/block-std/src/__tests__/test-schema.ts
- packages/framework/block-std/src/__tests__/test-spec.ts
- packages/framework/block-std/src/spec/type.ts
- packages/framework/block-std/src/view/element/lit-host.ts
- packages/framework/block-std/vitest.config.ts
- Allow to define the `view.component` in spec as a function which receive a model and return a literal template
> feat: the view component in block spec could be a function

- packages/presets/src/fragments/outline/outline-viewer.ts
This PR remove runtime type check of `AffineEditorContainer`.
Since `AffineEditorContainer` of AFFiNE side is not same as blocksuite site, the following code will throw error in AFFiNE side
```ts
@requiredProperties({
editor: PropTypes.instanceOf(AffineEditorContainer),
})
```
> fix(presets): remove editor runtime type check from outline viewer

- packages/blocks/src/database-block/data-view/view-manager/single-view.ts
- packages/blocks/src/database-block/data-view/widget/tools/presets/filter/filter.ts
When adding a filter, `SingleViewBase` is initialized multiple times, causing it to be unable to set the status through `this.view.filterSetVisible(true);`.
Before
https://github.com/user-attachments/assets/e2fc4a4c-e0c5-4557-9a22-56dfbba6f4d3
https://github.com/user-attachments/assets/dfdc4f51-8278-4911-87bb-39c9af56331b
> fix(blocks): show filter-bar when an filter added

- packages/blocks/src/root-block/edgeless/components/panel/scale-panel.ts
- packages/blocks/src/root-block/edgeless/components/panel/size-panel.ts
- tests/edgeless/note/scale.spec.ts
- tests/utils/actions/edgeless.ts
[BS-866](https://linear.app/affine-design/issue/BS-866/edgeless-input中的内容无法复制)
[BS-779](https://linear.app/affine-design/issue/BS-779/edgeless-复制手动输入的缩放参数后，粘贴到目标时，会原地创建一个-linked-doc)
> fix: scale input copy paste on edgeless

- packages/blocks/src/note-block/keymap-controller.ts
- packages/framework/block-std/src/event/control/keyboard.ts
- tests/edgeless/note/scale.spec.ts
[BS-1226](https://linear.app/affine-design/issue/BS-1226/edgeless-下无法触发-shift-keydown-事件)
edgeless pressShiftKeyUpdated slot never triger, which will cause some functions that depend on this slot to not work properly, such as holding down shift to scale certain elements proportionally, like note and embed synced doc.
> fix: edgeless pressShiftKeyUpdated slot never trigger

- packages/blocks/src/root-block/widgets/doc-remote-selection/doc-remote-selection.ts
fix: [BS-1089](https://linear.app/affine-design/issue/BS-1089/center-peek-的协同选中状态有问题：打开center-peek-后选中状态变成了全选center-peek-视图里的内容)
related: [BS-993](https://linear.app/affine-design/issue/BS-993/协同用户选择整个block时，不需要显示背景色，只需要显示光标铭牌)
> fix: embed block remote selection background should be transparent

- packages/blocks/src/root-block/widgets/doc-remote-selection/doc-remote-selection.ts
During collaboration, the remote cursor is not displayed at the line wrap position. The reason is that in this case, 'range.getClientRects()' returns two 'DOMRect' objects that are not handled in the code.
before:
https://github.com/user-attachments/assets/774ff434-19cd-48da-83ee-b36244902957
after:
https://github.com/user-attachments/assets/29972ae2-6367-4f9f-9ca3-3868dd12c579
> fix(page): remote cursor is invisible at the line wrap position

- packages/blocks/src/surface-block/element-model/mindmap.ts
Fixes [BS-1229](https://linear.app/affine-design/issue/BS-1229/mind-map-雷达-radial-layout-添加新节点后，布局和顺序都是错误的)
> fix: mind map radial layout rules

- packages/blocks/src/_common/export-manager/export-manager.ts
- packages/blocks/src/_common/utils/query.ts
- packages/blocks/src/root-block/edgeless/controllers/clipboard.ts
- packages/blocks/src/root-block/widgets/surface-ref-toolbar/utils.ts
To fix: [PD-1632](https://linear.app/affine-design/issue/PD-1632/edgeless-make-it-real-报错)
The to canvas function is still relied on in some whiteboard-related AI functions like make it real and needs to be fixed before switching to the new to png method.
In this pr, remove edgeless portal query and block query function.
> fix: no need to query portal when convert edgeless block to canvas

- packages/affine/model/src/consts/connector.ts
- packages/affine/model/src/consts/index.ts
- packages/affine/model/src/consts/line.ts
- packages/affine/model/src/elements/connector/connector.ts
- packages/affine/model/src/elements/connector/local-connector.ts
- packages/affine/shared/src/types/index.ts
- packages/affine/shared/src/utils/index.ts
- packages/affine/shared/src/utils/zod-schema.ts
- packages/blocks/src/_common/mind-map/draw.ts
- packages/blocks/src/index.ts
- packages/blocks/src/root-block/edgeless/components/panel/line-styles-panel.ts
- packages/blocks/src/root-block/edgeless/components/panel/line-width-panel.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/brush/brush-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/connector/connector-tool-button.ts
- packages/blocks/src/root-block/edgeless/utils/consts.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-connector-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-shape-button.ts
- packages/blocks/src/surface-block/managers/edit-session.ts
- packages/presets/src/__tests__/edgeless/last-props.spec.ts
- Use `.default()` to set the default value of zod schema.
- Refactor `_lastProps` initialize logic in `edit-session`.
- Move zod schemas to separate `zod-schema` file.
- Move consts to `model/consts` folder.
> refactor: use .default() to set default value of zod schema

- packages/blocks/src/root-block/edgeless/services/tools-manager.ts
- packages/framework/block-std/src/event/dispatcher.ts
1. Introduction of a static variable for active Event Dispatcher management
- Added a static variable _activeDispatcher to identify the currently active event dispatcher.
- Ensures that only one event dispatcher is active at any given time.
2. More accurate determination of the current active element's state
- _isActiveElementOutsideHost and _isEditableElementActive method for better recognition of editable elements outside of current editor host.
- Enhanced conditions for setting the active state in the _setActive method, considering more edge cases
3. Remove deprecated slots.
Fix: 
[BS-713](https://linear.app/affine-design/issue/BS-713/cursor-游离在-edgeless-面板会跟-ai-chat-输入冲突)
[BS-1261](https://linear.app/affine-design/issue/BS-1261/cmd-k-面板搜索时，即使光标不在白板，也会触发白板快捷键) …
> fix: multiple editor event dispatcher active status

- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- tests/edgeless/selection/keyboard.spec.ts
- tests/utils/asserts.ts
[BS-1267](https://linear.app/affine-design/issue/BS-1267/在-edgeless-里面全选复制，粘贴到一篇空白的文档，page-only-的内容也会被一起复制)
> fix(edgeless): select all should not select doc only notes

- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
Fixes [BS-877](https://linear.app/affine-design/issue/BS-877/在-mind-map-子节点上回车创建的-new-node-位置顺序不对)
> fix: new creating mind map node order

- packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
- packages/playground/apps/_common/components/debug-menu.ts
- packages/playground/apps/starter/data/multiple-editor.ts
- packages/playground/apps/starter/utils/editor.ts
- tests/multiple-editors/selection.spec.ts
- tests/utils/actions/edgeless.ts
Fix: [BS-1077](https://linear.app/affine-design/issue/BS-1077/split-view-下编辑器状态冲突)
And:
1. Fix starter playground multiple editors init function.
2. Add a button to toggle multiple editors in playground.
> fix: split view edit status conflict

- packages/blocks/src/root-block/config/editor-settings.ts
- packages/blocks/src/root-block/config/index.ts
- packages/blocks/src/root-block/root-config.ts
- packages/blocks/src/surface-block/managers/edit-session.ts
- packages/framework/global/src/utils/types.ts
- Add `editorSetting` config in root-block
- `lastProps$` is computed from initProps, editorSetting$ and innerProps$
- `initProps` is a defalut value
- `editorSetting$` is a signal passed from AFFiNE
- `innerProps$` is a signal of internal changes in BlockSuite
Test Config in AFFiNE like:
```typescript
config: {
editorSetting: signal({
shape: {
fillColor: '--affine-palette-shape-purple',
}
})
}
```
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/97a2a2d3-2cba-4cf1-98bb-ddafc30f4570.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/97a2a2d3-2cba-4cf1-98bb-ddafc30f4570.mov">录屏2024-08-27 19.36.04.mov</video>
> feat: add editorSetting config

- packages/affine/model/src/elements/brush/brush.ts
- packages/affine/model/src/elements/connector/connector.ts
- packages/affine/model/src/elements/shape/api/diamond.ts
- packages/affine/model/src/elements/shape/api/ellipse.ts
- packages/affine/model/src/elements/shape/api/rect.ts
- packages/affine/model/src/elements/shape/api/triangle.ts
- packages/blocks/src/root-block/edgeless/controllers/tools/default-tool.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/surface-block/element-model/utils/mindmap/utils.ts
- packages/framework/block-std/src/gfx/surface/element-model.ts
- packages/framework/global/src/utils/math.ts
Fixes [BS-1054](https://linear.app/affine-design/issue/BS-1054/mind-map-拖拽同级节点调整顺序的有效触发区域太小)
- rename `expand` to more reasonable `hitThreshold`
- add `responsePadding` on hit test options to allow to expand the elements response area
> feat: expand mind map dragging responsive area

- packages/framework/block-std/src/gfx/index.ts
- packages/framework/block-std/src/gfx/surface/element-model.ts
- Add `gfxContainerSymbol` to mark a model as a container
- Add `GfxContainerElement` interface
- Add `isGfxContainerElm` function to determine whether an element is a container
> feat: add gfx container symbol and interface

- packages/affine/components/src/rich-text/inline/presets/nodes/link-node/affine-link.ts
- packages/framework/inline/src/components/v-text.ts
This PR has NOT been thoroughly tested.
Before
After
https://github.com/user-attachments/assets/600f5e7c-ba87-470d-8c4b-e98901863572
> fix(inline): show point styles in link node

- packages/blocks/src/root-block/widgets/edgeless-auto-connect/edgeless-auto-connect.ts
- tests/edgeless/auto-connect.spec.ts
- tests/utils/asserts.ts
[BS-1283](https://linear.app/affine-design/issue/BS-1283/edgeless-only-note-下的-label-没有跟随-note-移动)
> fix: edgeless auto connect label position

- packages/blocks/src/root-block/edgeless/clipboard/clipboard.ts
- packages/blocks/src/root-block/edgeless/components/note-slicer/index.ts
- packages/blocks/src/root-block/edgeless/components/text/edgeless-text-editor.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/edgeless/tools/eraser-tool.ts
- packages/blocks/src/root-block/edgeless/utils/clipboard-utils.ts
- packages/blocks/src/root-block/edgeless/utils/crud.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-brush-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-menu/config.ts
- packages/blocks/src/surface-block/surface-block.ts
- packages/presets/src/__tests__/edgeless/layer.spec.ts
`surface.edgeless` would be removed after the viewport is migrated under surface.
> refactor(edgeless): remove public usage of `surface.edgeless`

- packages/affine/model/src/elements/group/group.ts
- packages/blocks/src/surface-block/renderer/elements/group/utils.ts
User can edit group name removing the title totally, leaving the input field blank.
Copy-Paste action would deserialize the field into the empty string, not the Y.Text instance and the call of toJson over string type variable would result in "call on undefined" error.
Additionally, the initial fromYProps implementation should consider transforming of the zero length string to the Y.Text instance, because the inline editor expects it to function properly.
https://github.com/user-attachments/assets/d1f84b47-f68f-426b-880e-b5500542c04b
> fix(edgeless): empty group names should not break copy-paste actions

- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/surface-block/managers/connector-manager.ts
- packages/blocks/src/surface-block/surface-block.ts
The `SurfaceContext` is added as boundary between surface block and `EdgelessRootService`.
After removing some legacy deps from surface block to root block, we should be able to migrate surface block to a standalone package.
> refactor(edgeless): remove circular deps from surface to edgeless root

- packages/affine/components/src/toolbar/index.ts
- packages/affine/components/src/toolbar/utils.ts
- packages/blocks/src/attachment-block/components/options.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-menu/button.ts
- packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
- packages/blocks/src/root-block/widgets/format-bar/config.ts
- packages/blocks/src/root-block/widgets/image-toolbar/index.ts
- packages/blocks/src/root-block/widgets/surface-ref-toolbar/surface-ref-toolbar.ts
> fix(blocks): should clone groups when creating a new image toolbar instance

- packages/blocks/src/root-block/widgets/image-toolbar/components/image-toolbar.ts
- packages/blocks/src/root-block/widgets/image-toolbar/index.ts
Closes [BS-1247](https://linear.app/affine-design/issue/BS-1247/image-options-copy-link-to-block-button)
> feat(blocks): configure more menu on image toolbar

- packages/blocks/src/root-block/remote-color-manager/remote-color-manager.ts
- packages/blocks/src/root-block/widgets/doc-remote-selection/doc-remote-selection.ts
- packages/blocks/src/root-block/widgets/format-bar/format-bar.ts
- packages/framework/block-std/src/range/range-binding.ts
- packages/framework/block-std/src/selection/manager.ts
- packages/framework/store/src/yjs/awareness.ts
[BS-1079](https://linear.app/affine-design/issue/BS-1079/同一个页面中的不同-editor-需要区分选区)
1. selection manager adds a unique id identifier. Due to the need to identify selection operations on the same document, a composite ID is required.
```
selectionManager._id = `${this.std.blockCollection.id}:${nanoid()}`;
```
2. The logic for distinguishing between local selection and remote selection needs to be changed. Only the selection in selectionV2 that corresponds to the current editor selection manager ID is considered local selection, while selections from other clients are remote selections. Selections managed by different selection managers of the same client, such as in a split view, are neither local nor remote. However, if multiple windows exist with selections, they will be synchronized …
> feat: each editor instance has its own independent local selection

- packages/affine/model/src/consts/connector.ts
- packages/affine/model/src/consts/line.ts
- packages/affine/model/src/consts/note.ts
- packages/affine/model/src/consts/text.ts
- packages/affine/model/src/utils/enum.ts
- packages/affine/model/src/utils/index.ts
- packages/affine/shared/src/utils/zod-schema.ts
Creates a reverse mapping object to quickly access the enum name by value, which is more efficient for components to use.
> refactor: map enum values to names

- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/shape/shape-draggable.ts
Fix: [BS-1256](https://linear.app/affine-design/issue/BS-1256/split-view-时打开-center-peek-再关闭，无法再激活任意一个-editor，白板快捷键会失效)
Remove some redundant disposable group, because they have been added once in packages/framework/block-std/src/view/element/block-component.ts bindHotkeys funtion.
> fix: some keydown handlers not trigger when multiple editors

- packages/blocks/src/index.ts
https://github.com/toeverything/AFFiNE/pull/7933
`MenuOptions` type is required here.
> chore(blocks): export MenuOptions type

- packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
- packages/blocks/src/root-block/edgeless/components/connector/connector-handle.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/edgeless/frame-manager.ts
- packages/blocks/src/root-block/edgeless/tools/connector-tool.ts
- packages/blocks/src/root-block/edgeless/tools/default-tool.ts
- packages/blocks/src/root-block/font-loader/font-loader.ts
- packages/blocks/src/surface-block/consts.ts
- packages/blocks/src/surface-block/managers/connector-manager.ts
- packages/blocks/src/surface-block/renderer/canvas-renderer.ts
- packages/blocks/src/surface-block/surface-block.ts
This removes the existence of `root-block` in the `block/surface-block`.
> refactor(edgeless): support configuring overlays and elementRenders

- packages/affine/shared/src/services/doc-mode-service.ts
- packages/blocks/src/_common/embed-block-helper/insert-embed-card.ts
- packages/blocks/src/_common/utils/render-linked-doc.ts
- packages/blocks/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/blocks/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/blocks/src/image-block/image-resize-manager.ts
- packages/blocks/src/root-block/widgets/linked-doc/config.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/playground/apps/_common/components/debug-menu.ts
- packages/playground/apps/_common/components/quick-edgeless-menu.ts
- packages/playground/apps/_common/mock-services.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/utils/editor.ts
- packages/presets/src/__tests__/edgeless/surface-ref.spec.ts
- packages/presets/src/editors/editor-container.ts
- packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
- packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
Fix: [BS-1292](https://linear.app/affine-design/issue/BS-1292/无法通过-docmodeservicesetmode-切换-mode)
rename:
before:
```
setMode: (mode: DocMode, docId?: string) => void;
getMode: (docId?: string) => DocMode;
toggleMode: (docId?: string) => DocMode;
onModeChange: (
handler: (mode: DocMode) => void,
docId?: string
) => Disposable;
```
after:
```
/**
* Set the primary mode of the doc.
* This would not affect the current editor mode.
* If you want to switch the editor mode, use `setEditorMode` instead.
* @param mode - The mode to set.
* @param docId - The id of the doc.
*/
setPrimaryMode: (mode: DocMode, docId: string) => void;
/**
* Get the primary mode of the doc.
* Normally, it would be used to query the mode of other doc.
* @param docId - The id of the doc.
* @returns The primary mode of …
```
> chore: add editor mode related service on doc mode service

- packages/affine/block-surface/src/renderer/canvas-renderer.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-preview-block.ts
- packages/blocks/src/root-block/edgeless/utils/panning-utils.ts
- packages/blocks/src/surface-block/mini-mindmap/surface-block.ts
- packages/framework/block-std/src/gfx/controller.ts
- packages/framework/block-std/src/gfx/grid.ts
- packages/framework/block-std/src/gfx/layer.ts
- packages/framework/block-std/src/gfx/viewport.ts
- packages/framework/block-std/src/utils/gfx.ts
All basic edgeless APIs should be moved to `GfxController`. Currently, all edgeless APIs are in EdgelessRootService, and they should be progressively migrated.
Now the edgeless APIs can be accessed through `std.gfx.xxx` .
> feat: add gfx api entry point

- packages/blocks/src/frame-block/frame-block.ts
- packages/blocks/src/root-block/edgeless/components/rects/edgeless-dragging-area-rect.ts
- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/root-block/edgeless/components/text/edgeless-frame-title-editor.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/edgeless/frame-manager.ts
- packages/blocks/src/root-block/edgeless/tools/default-tool.ts
- packages/blocks/src/root-block/edgeless/tools/frame-tool.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/presets/src/__tests__/edgeless/frame.spec.ts
- tests/edgeless/frame.spec.ts
Improved frame UI in the edgeless mode. [BS-1112](https://linear.app/affine-design/issue/BS-1112/[frame-and-group-improvement]-ui-update)
- UI changes:
- Colorize frame title background and reverse text color based on it. [BS-1114](https://linear.app/affine-design/issue/BS-1114/[frame-improvement]-frame-标签文字颜色需要根据-color-picker-选定的颜色自动反色)
- Hide frame title when frame is small or text is empty. [BS-1111](https://linear.app/affine-design/issue/BS-1111/[frame-improvement]-标签的宽度受-frame-宽度的影响，标签内容进行省略处理，缩放直到内容全部省略后消失), [BS-1306](https://linear.app/affine-design/issue/BS-1306/[ui]-使用空格-hack-标签，标签不渲染)
- Highlight frame border when hover frame title. [BS-1110](https://linear.app/affine-design/issue/BS-1110/[frame-improvement]-frame-通过-hover-标签进入-hover-态)
- Mask frame title when hover it. …
> feat(edgeless): update frame ui

- packages/framework/block-std/src/event/dispatcher.ts
- tests/edgeless/basic.spec.ts
- tests/edgeless/pan.spec.ts
- tests/edgeless/presentation.spec.ts
- tests/utils/actions/edgeless.ts
Fix: [BS-1315](https://linear.app/affine-design/issue/BS-1315/bug：edgeless-mode-无法移动)
> fix: edgeless viewport pan and zoom when readonly

- packages/affine/block-surface/src/element-model/mindmap.ts
- packages/affine/block-surface/src/element-model/utils/mindmap/utils.ts
- packages/affine/block-surface/src/managers/connector-manager.ts
- packages/affine/block-surface/src/middlewares/connector.ts
- packages/affine/block-surface/src/renderer/elements/mindmap.ts
This removes `this.pathGenerator` on `MindmapElementModel`.
After landing this PR, `MindmapElementModel` should be available to be moved to the `affine-model` package.
> refactor(edgeless): decouple `ConnectorPathGenerator` from mindmap model

- packages/blocks/src/_common/embed-block-helper/embed-block-element.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
- packages/playground/apps/starter/main.ts
- tests/utils/actions/misc.ts
- tests/utils/declare-test-window.ts
Close: [BS-1289](https://linear.app/affine-design/issue/BS-1289/linked-doc-block有个写死的min-width-450px-：-需要去除最小宽度的限制)
This fix based on `getEditorMode()`. There three cases:
- `edgeless mode > note or edgeless text > embed card`, apply `max-width`,
- `edgeless mode > embed card` no width limit, since the style is overrideed in `renderGfxBlock()`,
- `page mode > embed card` remove `max-width` since the page width may be small like in mobile.
In AFFiNE side, the `getEditorMode()` should be provide in `DocModeService`, related PR: #8110 
Other changes:
- add `mockDocModeService` for editor of playwright test
> fix(blocks): embed card overflow in mobile

- packages/blocks/src/root-block/edgeless/tools/default-tool.ts
Close [BS-1285](https://linear.app/affine-design/issue/BS-1285/group全选时，对齐会对齐group内部yuan素)
This PR changes the behavior of dragging selection that only select top level element in **element tree** in dragging area. See below.
inner elements are also selected
only selected outer elements
> feat(edgeless): only select top level in element tree during drag selecting

- packages/blocks/src/embed-linked-doc-block/commands/insert-link-by-quick-search.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/link/link-dense-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/link/link-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
Closes [BS-1333](https://linear.app/affine-design/issue/BS-1333/需要修复一个-linked-doc-添加行为的埋点逻辑)
> fix(blocks): tracking logic should not be triggered when the result is null

- packages/affine/model/src/elements/group/group.ts
- packages/framework/block-std/src/gfx/surface/element-model.ts
move export `xywh` from `GroupModel` to `GroupLikeModel` for covering mindmap
> fix(edgeless): xywh missing in mindmap serialized data

- packages/blocks/src/root-block/edgeless/utils/text.ts
Closes [BS-1337](https://linear.app/affine-design/issue/BS-1337/[bug]-connector-的-text-文本显示错误)
> fix(blocks): missing text on connector when creating label

- packages/blocks/src/frame-block/frame-block.ts
- packages/presets/src/__tests__/edgeless/frame.spec.ts
Close [BS-1353](https://linear.app/affine-design/issue/BS-1353/externalxywh-is-undefined-when-frame-out-of-viewport-when-enter)
If a frame is out of viewport after enter edgeless editor, the title of frame will be un-clickable when move viewport to the position of frame. The reason is `externalXYWH` is not initialized by `<edgeless-frame-title>` in this case.
https://github.com/user-attachments/assets/2b0e9979-c8cc-4207-843c-65786656f487
https://github.com/user-attachments/assets/fc3875cc-dd7a-46c4-925f-fd01779cb945
> fix(edgeless): externalXYWH is undefined when frame out of viewport after enter edgeless editor

- packages/affine/block-surface/src/element-model/mindmap.ts
- packages/affine/block-surface/src/element-model/utils/mindmap/layout.ts
- packages/affine/block-surface/src/element-model/utils/mindmap/style.ts
- packages/affine/block-surface/src/element-model/utils/mindmap/utils.ts
- packages/affine/block-surface/src/index.ts
- packages/affine/model/src/consts/index.ts
- packages/affine/model/src/consts/mindmap.ts
- packages/affine/shared/src/utils/zod-schema.ts
- packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/assets.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-tool-button.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-mindmap-button.ts
- packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
- packages/presets/src/__tests__/edgeless/group.spec.ts
Close issue [BS-1219](https://linear.app/affine-design/issue/BS-1219).
- Add `MindmapSchema` in `zod-schema`.
- Use signal `style$` instead of state `style`.
- Update import references.
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/69b46171-5258-4377-b94c-841f45025d5a.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/69b46171-5258-4377-b94c-841f45025d5a.mov">录屏2024-09-09 15.24.10.mov</video>
> feat: mindmap remembers last settings

- packages/blocks/src/root-block/widgets/edgeless-auto-connect/edgeless-auto-connect.ts
The auto-connect widget may be get `group` elements unexpectedly, and the following code will throw an undefined error since `xywh$` is not a property of `group`
https://github.com/toeverything/blocksuite/blob/a3f5dd38e71da473f07e51259f4326448ac71b96/packages/blocks/src/root-block/widgets/edgeless-auto-connect/edgeless-auto-connect.ts#L414-L416
PS: Test is difficult to write because the error will also stop 'auto-connect' rendering like expected behavior.
> fix(edgeless): auto-connect get group unexpectedly

- packages/affine/model/src/consts/brush.ts
- packages/affine/model/src/consts/connector.ts
- packages/affine/model/src/consts/index.ts
- packages/affine/model/src/consts/line.ts
- packages/affine/model/src/consts/text.ts
- packages/affine/shared/src/utils/zod-schema.ts
- packages/blocks/src/root-block/edgeless/components/text/edgeless-connector-label-editor.ts
- packages/blocks/src/root-block/edgeless/utils/text.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-text-menu.ts
Close issue [BS-1223](https://linear.app/affine-design/issue/BS-1223) and [BS-1224](https://linear.app/affine-design/issue/BS-1224).
- Add the connector's `labelStyle` in `zod-schema` file.
- Use `edgeless.service.updateElement` instead of `doc.updateBlock`.
- Refactor `pickColor` function.
> fix: text does not remember current settings

- packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
Close issue [BS-1350](https://linear.app/affine-design/issue/BS-1350).
Use `edgeless.service.updateElement` instead of `doc.updateBlock`.
> fix: note radius and shadow settings are not remembered

- packages/blocks/src/root-block/widgets/ai-panel/components/state/error.ts
Use `<affine-tooltip>` component that updates the float position when it might be clipped。
Fix: [BS-1386](https://linear.app/affine-design/issue/BS-1386/[bug]-tooltip-位置错误)
> fix: use affine-tooltip component that will auto update floating position

- packages/affine/model/src/consts/frame.ts
- packages/affine/model/src/consts/index.ts
- packages/affine/shared/src/utils/zod-schema.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
Close issue [BS-1220](https://linear.app/affine-design/issue/BS-1220).
- Add `affine:frame` in `zod-schema`
- Move `FRAME_BACKGROUND_COLORS` to `consts/frame.ts`.
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/f0eff1b4-9add-4670-bd7b-2374fad5d296.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/f0eff1b4-9add-4670-bd7b-2374fad5d296.mov">录屏2024-09-10 16.56.49.mov</video>
> fix: can not remember frame settings

- packages/blocks/src/root-block/edgeless/edgeless-root-preview-block.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/framework/block-std/src/gfx/viewport-element.ts
- packages/presets/src/__tests__/edgeless/surface-ref.spec.ts
- Migrated viewport of `edgeless-root-preview` to `gfx-viewport`. This change will improve the performance of `surface-ref` in doc mode.
- Fixed incorrect viewport of `surface-ref` of group
- Fixed that `EditorHost` of `surface-ref` will re-render repeatedly.
- Fixed viewport of `surface-ref` no update when the position of reference updated.
- Add related tests
> fix(blocks): fix some bugs of surface-ref

- packages/affine/components/src/rich-text/inline/presets/nodes/latex-node/latex-editor-menu.ts
Close [BS-1364](https://linear.app/affine-design/issue/BS-1364/[可优化的]-input-popup-的-ui-抖动)
> fix: latex editor shake

- packages/affine/shared/src/services/quick-search-service.ts
- packages/blocks/src/embed-linked-doc-block/commands/insert-embed-linked-doc.ts
- packages/blocks/src/embed-linked-doc-block/commands/insert-link-by-quick-search.ts
Closes: [BS-1323](https://linear.app/affine-design/issue/BS-1323/粘贴-link-to-block-到-link-弹窗，不符合预期)
> feat: add an optional field params to QuickSearchResult

- packages/affine/model/src/elements/brush/brush.ts
- packages/presets/src/__tests__/edgeless/surface-model.spec.ts
Fixes [BS-1392](https://linear.app/affine-design/issue/BS-1392/brush-设为最细时无法绘制)
Fixes [BS-1347](https://linear.app/affine-design/issue/BS-1347/pen-preview-的渲染快速拖动后，符号变化比较明显)
> fix: brush element lineWidth bug

- packages/blocks/src/root-block/edgeless/components/text/edgeless-connector-label-editor.ts
Closes [BS-1338](https://linear.app/affine-design/issue/BS-1338/[bug]-mindmap-用-connector-连接会-crash)
Should check if text exists after text is reset to undefined
> fix(blocks): text may be undefined when editing connector label

- packages/affine/block-surface/src/element-model/mindmap.ts
- packages/affine/block-surface/src/element-model/utils/mindmap/layout.ts
- packages/affine/block-surface/src/element-model/utils/mindmap/utils.ts
- packages/affine/block-surface/src/renderer/elements/shape/utils.ts
- packages/affine/model/src/consts/text.ts
- packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
- packages/blocks/src/root-block/edgeless/components/text/edgeless-shape-text-editor.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/mindmap-menu.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/edgeless/tools/default-tool.ts
- packages/blocks/src/root-block/edgeless/utils/snap-manager.ts
Fixes [BS-1054](https://linear.app/affine-design/issue/BS-1054/mind-map-拖拽同级节点调整顺序的有效触发区域太小)
Fixes [BS-1317](https://linear.app/affine-design/issue/BS-1317/mind-map-编辑中，undo-需要两次才响应)
Fixes [BS-1284](https://linear.app/affine-design/issue/BS-1284/mind-map-软换行之后，节点没有立刻增加新的行空间)
Fixes [PD-1660](https://linear.app/affine-design/issue/PD-1660/radial-雷达视图在拖拽之后，左右节点不平衡分布了)
Fixes [BS-1334](https://linear.app/affine-design/issue/BS-1334/增加-mind-map-block-级别导入埋点)
Fixes [PD-1214](https://linear.app/affine-design/issue/PD-1214/拖拽非根节点，建议去掉对齐效果)
Fixes [BS-1316](https://linear.app/affine-design/issue/BS-1316/选中节点的时候，快捷键会误触发编辑)
> fix: mind map issues

- packages/presets/src/fragments/outline/body/outline-panel-body.ts
- tests/fragments/outline.spec.ts
Fix: [BS-1406](https://linear.app/affine-design/issue/BS-1406/更改-note-displaymode-需要同步更新-outline-panel)
> fix: should update outline panel notes when changing note display mode

- packages/affine/shared/src/services/index.ts
- packages/affine/shared/src/services/parse-url-service.ts
- packages/affine/shared/src/services/quick-search-service.ts
- packages/blocks/src/database-block/columns/link/cell-renderer.ts
- packages/blocks/src/database-block/columns/title/text.ts
- packages/blocks/src/embed-linked-doc-block/commands/insert-link-by-quick-search.ts
- packages/blocks/src/root-block/clipboard/middlewares/paste.ts
- packages/blocks/src/root-block/edgeless/clipboard/clipboard.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/link/link-dense-menu.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/link/link-tool-button.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/note/note-menu.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/playground/apps/_common/mock-services.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/main.ts
- packages/playground/apps/starter/utils/editor.ts
- tests/clipboard/clipboard.spec.ts
- tests/edgeless/clipboard.spec.ts
- tests/utils/actions/misc.ts
- tests/utils/declare-test-window.ts
Before this, blocksuite used QuickSearchService to extract docId and other information from the url. This pr provides a ParseDocUrlService to handle such requirements.
> feat(blocks): parse url service

- packages/blocks/src/root-block/edgeless/frame-manager.ts
- packages/blocks/src/root-block/edgeless/tools/default-tool.ts
- tests/edgeless/frame/frame-mindmap.spec.ts
- tests/edgeless/frame/frame.spec.ts
- tests/utils/asserts.ts
Closes: [BS-1398](https://linear.app/affine-design/issue/BS-1398/[bug]-拖出-frame-后-mindmap-依然跟随-frame),  [BS-1400](https://linear.app/affine-design/issue/BS-1400/mindmap无法移出frame)
This PR fix mindmap is moved with frame moving when the mindmap has been drag out of frame.
- add workround to avoid multiple container in `FrameManager` for nodes of mindmap.
- The fix can be refactored after #8239
- add frame and mindmap e2e tests
> fix(edgeless): multi parent container of node of mindmap

- packages/framework/inline/src/services/range.ts
Close [BS-1365](https://linear.app/affine-design/issue/BS-1365/创建-inline-latex-的预期行为错误)
Close [BS-1368](https://linear.app/affine-design/issue/BS-1366/[行内-latex]输入完成-latex-后不能继续输入文字)
> fix(inline): filter embed gap in `getTextPoint`

- packages/blocks/src/latex-block/latex-block.ts
Close [BS-1408](https://linear.app/affine-design/issue/BS-1408/[行间-latex]-input-内的删除行为会删掉整个-block)
> fix(blocks): not keep block selection when trigger latex editor

- packages/blocks/src/root-block/edgeless/components/note-slicer/index.ts
- packages/presets/src/fragments/outline/outline-panel.ts
- tests/fragments/outline/outline-panel.spec.ts
- tests/fragments/outline/toc-viewer.spec.ts
- tests/fragments/outline/utils.ts
Fix: [BS-1358](https://linear.app/affine-design/issue/BS-1358/[bug]-使用剪刀切开之后-note-block-不会显示在-frame-toc-里) [BS-1002](https://linear.app/affine-design/issue/BS-1002/使用剪刀后，会触发选区)
Split outline.spec.ts tests into two files.
> fix: should update outline panel notes after slicing note

- packages/affine/shared/src/services/parse-url-service.ts
- packages/blocks/src/database-block/columns/title/text.ts
- packages/blocks/src/root-block/edgeless/clipboard/clipboard.ts
I forgot to return the `mode` field when parse doc url.
In addition, I also modified the implementation of parsing url in clipboard, and now it completely use parsedocurl for parsing.
> feat(blocks): parse doc url with mode

- packages/affine/block-surface/package.json
- packages/affine/model/src/blocks/note/note-model.ts
- packages/affine/model/src/blocks/paragraph/paragraph-model.ts
- packages/affine/model/src/blocks/root/root-block-model.ts
- packages/affine/shared/package.json
- packages/affine/shared/src/services/edit-props-store.ts
- packages/affine/shared/src/theme/theme-observer.ts
- packages/affine/shared/src/utils/zod-schema.ts
- packages/blocks/package.json
- packages/blocks/src/surface-ref-block/index.ts
- packages/presets/src/__tests__/edgeless/last-props.spec.ts
- yarn.lock
Close issue [BS-1411](https://linear.app/affine-design/issue/BS-1411). Remember the color and transparency settings.
What changed?
- Add a `makeDeepOptional` function to make a zod schema deep optional.
- Use `OptionalPropsSchema.parse` instead of `extractProps`, which can ensure the schema of override props.
- Refactor logic of `generateColorProperty`.
- Add `customizer` to process `ZodUnion` color schema merge.
- Add unit tests.
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/baa458c6-ed47-47e1-971d-310184dd891d.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/baa458c6-ed47-47e1-971d-310184dd891d.mov">录屏2024-09-13 15.46.51.mov</video>
> fix: color with transparency does not remember

- packages/blocks/src/root-block/edgeless/components/frame/frame-preview.ts
- packages/playground/apps/_common/components/custom-frame-panel.ts
- packages/playground/package.json
- packages/presets/src/fragments/frame-panel/body/frame-panel-body.ts
- packages/presets/src/fragments/frame-panel/card/frame-card.ts
- packages/presets/src/fragments/frame-panel/frame-panel.ts
- packages/presets/src/fragments/frame-panel/header/frame-panel-header.ts
- packages/presets/src/fragments/frame-panel/header/frames-setting-menu.ts
- packages/presets/src/fragments/frame-panel/utils/drag.ts
- tests/fragments/frame-panel.spec.ts
- yarn.lock
[BS-1425](https://linear.app/affine-design/issue/BS-1425/refactor-frame-panel)
[BS-1414](https://linear.app/affine-design/issue/BS-1414/frame-preview-在切换模式后渲染内容异常)
1. To use editorHost instead of AffineEditorContainer
2. Remove useless slots.
3. Add more e2e tests.
> fix: refactor frame panel to use EditorHost instead of AffineEditorContainer

- packages/blocks/src/edgeless-text-block/edgeless-text-block.ts
Closes [BS-1384](https://linear.app/affine-design/issue/BS-1384/[bug]-edgeless-连接-connector-后缩放会改变位置)
> fix(blocks): height should not be updated when not in editing state

- .github/snapshot-changeset.md
- packages/affine/shared/src/selection/hightlight.ts
- packages/affine/shared/src/selection/image.ts
- packages/affine/shared/src/selection/index.ts
- packages/affine/widget-scroll-anchoring/package.json
- packages/affine/widget-scroll-anchoring/src/effects.ts
- packages/affine/widget-scroll-anchoring/src/index.ts
- packages/affine/widget-scroll-anchoring/src/scroll-anchoring.ts
- packages/affine/widget-scroll-anchoring/tsconfig.json
- packages/affine/widget-scroll-anchoring/typedoc.json
- packages/affine/widget-scroll-anchoring/vitest.config.ts
- packages/blocks/package.json
- packages/blocks/src/effects.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
- packages/blocks/src/root-block/page/page-root-spec.ts
- packages/blocks/tsconfig.json
- packages/framework/block-std/src/gfx/viewport.ts
- packages/framework/block-std/src/selection/variants/block.ts
- packages/framework/block-std/src/selection/variants/cursor.ts
- packages/framework/block-std/src/selection/variants/surface.ts
- packages/framework/block-std/src/selection/variants/text.ts
- yarn.lock
Closes [BS-1318](https://linear.app/affine-design/issue/BS-1318/在-selection-中添加-highlight-type)
* add highlight type selection
* impl scroll anchoring widget
<a href="https://app.graphite.dev/media/video/8ypiIKZXudF5a0tIgIzf/ca7b10f9-a847-456a-9088-7151feeb0e35.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/8ypiIKZXudF5a0tIgIzf/ca7b10f9-a847-456a-9088-7151feeb0e35.mov">Screen Recording 2024-09-17 at 13.25.33.mov</video>
> feat(blocks): add scroll anchoring widget

- packages/blocks/src/root-block/edgeless/tools/default-tool.ts
- packages/blocks/src/root-block/edgeless/utils/clone-utils.ts
- tests/edgeless/frame/clipboard.spec.ts
Close: [BS-1397](https://linear.app/affine-design/issue/BS-1397/[bug]-带有-mindmap-的-frame-使用-alt-拖拽时-frame-会有嵌入的-ui-表现，二次拖拽后才可以把复制的)
Fixed that frame can not be cloned by alt moving when it contains an edgeless container like group or mindmap.
> fix(edgeless): failed to alt clone move frame when it contains container element

- packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
- tests/bookmark.spec.ts
- tests/snapshots/bookmark.spec.ts/embed-figma.json
- tests/snapshots/bookmark.spec.ts/embed-youtube.json
- tests/snapshots/bookmark.spec.ts/horizontal-figma.json
- tests/snapshots/bookmark.spec.ts/horizontal-youtube.json
- tests/utils/ignore.ts
Fix issue [BS-1373](https://linear.app/affine-design/issue/BS-1373).
- Use a temporary constant for `this.focusModel `.
- Add e2e tests for YouTube and Figma view switching scenarios.
> fix: duplication occurs when card view is switched to embed view

- packages/affine/block-embed/src/embed-synced-doc-block/styles.ts
- packages/blocks/src/bookmark-block/styles.ts
Fix: 
[BS-1459](https://linear.app/affine-design/issue/BS-1459/linked-doc-embed-view在edgeless上的padding消失了)
[BS-1460](https://linear.app/affine-design/issue/BS-1460/links-card-view-icon尺寸颜色错误)
> fix: bookmark and synced doc block style

- packages/affine/widget-scroll-anchoring/src/scroll-anchoring.ts
I think this will prevent the scroll event from being interrupted.
When you click affine-reference, the `refereshKey` parameter on the link will be updated.
`href="/workspace/gQux6wXgQWP-KkIC6uUDE/cvygdlykaIR5my9Hp_9nB?mode=page&blockIds=dx2sB9LE_eudTUbWAZ_N6&refreshKey=1-wP1OTe9AajEv6Rdm9X3"`
https://github.com/user-attachments/assets/8c91118a-1704-419b-ac2a-008ed7e624d7
https://github.com/user-attachments/assets/b7a37e1e-db03-4207-90c4-1e743fee2c7a
> fix: better scroll to target

- packages/blocks/package.json
- packages/framework/store/package.json
- packages/framework/store/src/__tests__/assets.unit.spec.ts
- packages/framework/store/src/adapter/assets.ts
- packages/framework/store/src/transformer/assets.ts
- yarn.lock
This pull request enhances the `AssetsManager` to support file type detection. 
Currently, images are named as xxxxx.blob when exporting markdown, which is not user-friendly. This PR improves the export experience by introducing `file-type` to guess the file type.
Before
After
---
Note that the `MemoryBlobSource` used by the playground will preserve the MIME type of the blob, which is different from the BlobSource of AFFiNE. Tweak the `MemoryBlobSource` to test these changes.
```diff
// packages/framework/sync/src/blob/impl/memory.ts
set(key: string, value: Blob) {
+    // this.map.set(key, value);
+    this.map.set(key, new Blob([value]));
return Promise.resolve(key);
}
```
> feat: add file type detection when exporting

- packages/blocks/src/root-block/widgets/edgeless-auto-connect/edgeless-auto-connect.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-note-button.ts
- packages/framework/global/src/types/index.ts
- packages/framework/store/src/store/collection.ts
- packages/playground/apps/starter/utils/collection.ts
- packages/presets/src/fragments/outline/card/outline-card.ts
The `enable_advanced_block_visibility` flag is used to config the visibility related UI and it's false by default.
https://github.com/user-attachments/assets/5890abd3-872d-422c-b144-dcd0631a1735
> feat(edgeless): tweak block visibility ui

- packages/blocks/src/root-block/edgeless/clipboard/clipboard.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/edgeless/services/template-middlewares.ts
- packages/blocks/src/root-block/widgets/element-toolbar/release-from-group-button.ts
- packages/framework/block-std/src/gfx/layer.ts
- packages/presets/src/__tests__/edgeless/frame.spec.ts
- packages/presets/src/__tests__/edgeless/layer.spec.ts
- packages/presets/src/__tests__/edgeless/surface-ref.spec.ts
- tests/edgeless/connector/label.spec.ts
- tests/edgeless/group/group.spec.ts
- tests/edgeless/note/note.spec.ts
- tests/edgeless/text.spec.ts
Close [BS-1399](https://linear.app/affine-design/issue/BS-1399/edgeless-layer-index相关问题)
- Ensure the new edgeless element is always on top after refactoring the `LayerManager.generateIndex()` and `LayerManager.createIndexGenerator()` methods to be type-agnostic. Previously, the block or canvas type was used to determine whether to place a new block in the second-to-last layer.
- Fix incorrect index order of elements after ungrouping.
- Update layer related tests
- Fix some flaky edgeless e2e tests.
https://github.com/user-attachments/assets/6cb57241-9184-44fe-b6a6-49fd51d4cf4f
https://github.com/user-attachments/assets/694552c0-ffc1-45b1-9a96-f0904d9f70d8
remove `xxx` parameter from `generateIndex(xxx)` in the following files:
- …
> refactor(edgeless): make new block element always be on the top

- packages/affine/block-embed/src/common/embed-block-element.ts
- packages/affine/block-embed/src/embed-linked-doc-block/styles.ts
- packages/affine/shared/src/consts/index.ts
- tests/edgeless/edgeless-text.spec.ts
- tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-link-to-card-min-width.json
Close [BS-1439](https://linear.app/affine-design/issue/BS-1439/embed-card-没有最大宽度)
> fix(blocks): set max width to embed-linked-doc-block

- packages/blocks/src/_common/components/utils.ts
- packages/blocks/src/root-block/widgets/linked-doc/index.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/slash-menu/index.ts
- packages/blocks/src/root-block/widgets/slash-menu/slash-menu-popover.ts
- tests/slash-menu.spec.ts
Close: [BS-1444](https://linear.app/affine-design/issue/BS-1444/在linked-doc面板，输入法输入后，面板消失), [BS-1443](https://linear.app/affine-design/issue/BS-1443/中文输入法下，段落开头输入-【【-无法唤起-linked-doc面板), [BS-1442](
https://linear.app/affine-design/issue/BS-1442/中文输入法下，输入-面板显示位置错误)
This PR fixes IME issues of the @ menu and slash menu, including:
- Incorrect positioning of the slash menu popover.
- Can not open the @ menu using `【【`.
- Can not search within the @ menu using IME.
The cause of these issues is that, in Windows Microsoft Pinyin, the inline range is updated when the `compositionend` event is triggered. Consequently, the slot `this.inlineEditor.slots.renderComplete.once` and `inlineEditor.slots.inlineRangeSync.once` are delayed until the next keyboard input. Related PR: #7914 …
> fix(blocks): ime bugs of slash menu and at menu

- packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/link-popup.ts
Closes [BS-1490](https://linear.app/affine-design/issue/BS-1490/修复-link-popover-中按钮的激活态)
> fix: confirm button active style

- packages/presets/src/fragments/outline/card/outline-card.ts
Before (unable to click on the hover popup):
https://github.com/user-attachments/assets/350ab3b5-4611-4728-9fef-4350989be457
After:
https://github.com/user-attachments/assets/92b948b0-ae72-4851-9aff-bd6c4e510ec7
> fix: outline popup ref area

- packages/blocks/src/image-block/image-edgeless-block.ts
[BS-1495](https://linear.app/affine-design/issue/BS-1495/edgeless-旋转图形不沃克)
> fix: edgeless image block rotate

- packages/affine/components/src/rich-text/inline/presets/nodes/link-node/affine-link.ts
- packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/link-popup.ts
- packages/affine/components/src/rich-text/inline/presets/nodes/link-node/link-popup/toggle-link-popup.ts
Closes [BS-1496](https://linear.app/affine-design/issue/BS-1496/当-hover-affine-link-时，-单击-link-popup-上的-open-link-也应该需要判断下站内链接的情况)
When a user opens a link on a link-popup, it is also necessary to identify whether it is an in-app link.
<a href="https://app.graphite.dev/media/video/8ypiIKZXudF5a0tIgIzf/8bc7efee-f158-4fac-815d-39f15139d55e.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/8ypiIKZXudF5a0tIgIzf/8bc7efee-f158-4fac-815d-39f15139d55e.mov">Screen Recording 2024-09-25 at 16.24.35.mov</video>
> fix: improve open link on link popup

- packages/affine/block-embed/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/affine/block-embed/src/embed-linked-doc-block/styles.ts
Close [BS-1497](https://linear.app/affine-design/issue/BS-1497/白板文档出错)
> fix(blocks): incorrect width of embed-linked-doc-block in edgeless

- packages/blocks/src/root-block/widgets/slash-menu/index.ts
- tests/slash-menu.spec.ts
Close [BS-1501](https://linear.app/affine-design/issue/BS-1501/修正代碼區塊中-的響應問題)
> fix(blocks): fix slash menu is triggered in ignored blocks

- packages/blocks/src/edgeless-text-block/edgeless-text-block.ts
Close [BS-1488](https://linear.app/affine-design/issue/BS-1488/typeerror-undefined-is-not-an-object-evaluating-sslots)
> fix(blocks): improve edgeless text block resizing behavior

- packages/blocks/src/_common/components/utils.ts
Close [BS-1531](https://linear.app/affine-design/issue/BS-1531/macos-chrome-无法在menu中使用中文搜索) 
https://github.com/toeverything/blocksuite/blob/3ecef3d1d57dd77314c0b13e02d2bda6efc41911/packages/blocks/src/_common/components/utils.ts#L24-L27
When `compositionend` event is emitted, the node in the current native range is a `ELEMENT_NODE` not a `TEXT_NODE` in MacOS. That will make the searching query of @ menu to be null, and then the menu will be auto-closed.
```
<div contenteditable="true" class=" inline-editor " data-v-root="true">
```
> fix(blocks): can not search in at menu with IME

- packages/presets/src/fragments/outline/outline-viewer.ts
- tests/fragments/outline/toc-viewer.spec.ts
Close [BS-1537](https://linear.app/affine-design/issue/BS-1537/share-page-中-toc-不应该有-[open-in-sidebar]-选项)
> fix(blocks): hide outline panel toggle button when callback is null

- .changeset/perfect-nails-guess.md
- fix(blocks): can not search in at menu with IME. #8481
- fix(std): dispatcher pointerUp calls twice. #8485
- fix(blocks): pasting elements with css inline style. #8491
- fix(blocks): hide outline panel toggle button when callback is null. #8493
- fix(blocks): pasting twice when span inside h tag. #8496
- fix(blocks): image should be displayed when in vertical mode. #8497
- fix: press backspace at the start of first line when edgeless text exist. #8498
> chore: release patch version

- packages/blocks/src/root-block/widgets/code-language-list/components/lang-button.ts
This PR improves the layout of the language list button by aligning the icon properly within the button.
The changes include the addition of a flex display for the icon, ensuring better visual consistency and user experience.
Before
After
> fix: enhance button layout with icon alignment

- packages/affine/block-surface/src/surface-transformer.ts
- packages/affine/model/src/blocks/attachment/attachment-transformer.ts
- packages/affine/model/src/blocks/image/image-transformer.ts
- packages/blocks/src/root-block/edgeless/services/template-middlewares.ts
- packages/blocks/src/root-block/edgeless/services/template.ts
- packages/framework/global/src/env/index.ts
- packages/framework/store/src/adapter/base.ts
- packages/framework/store/src/transformer/base.ts
- packages/framework/store/src/transformer/job.ts
Close #8380
The original process of converting snapshot JSON to blocks was significantly slowed to ensure UI responsiveness. It involved two types of async computations:
* Asynchronously converting snapshots to draft models.
* Asynchronously inserting draft models into the block tree using `doc.addBlock`.
Original import sequence:
```
Convert snapshot node A
Insert block A
Wait for tick
Convert snapshot node B
Insert block B
Wait for tick
Convert snapshot node C
Insert block C
Wait for tick
...
```
Despite `doc.addBlock` being synchronous, a `requestAnimationFrame` interval was added after each block insertion to prevent UI blocking. This resulted in long processing times when pasting thousands of blocks:
https://github.com/user-attachments/assets/3a6379c9-621e-490e-a79f-4377494d5915
This …
> perf: optimize snapshot job handling

- packages/affine/model/src/blocks/frame/frame-model.ts
- packages/blocks/src/root-block/edgeless/frame-manager.ts
- packages/blocks/src/root-block/edgeless/tools/default-tool.ts
This PR removes redundant code related to the container-child element relationship, which is now maintained by the new `TreeManager` after #8239 .
> refactor(blocks): simplify frame manager implementation

- packages/framework/block-std/src/gfx/surface/surface-model.ts
- packages/framework/block-std/src/gfx/tree.ts
- tests/edgeless/group/clipboard.spec.ts
- tests/edgeless/group/group-and-ungroup.spec.ts
- tests/edgeless/group/group.spec.ts
- tests/edgeless/group/release.spec.ts
- tests/edgeless/reordering.spec.ts
- tests/utils/actions/edgeless.ts
- tests/utils/asserts.ts
This PR refactor group test utils with container interface after PR #8239
> refactor: update group test utils using container interface

- packages/blocks/src/root-block/edgeless/components/toolbar/mindmap/basket-elements.ts
- packages/blocks/src/root-block/edgeless/frame-manager.ts
- tests/edgeless/frame/clipboard.spec.ts
- tests/edgeless/frame/frame-mindmap.spec.ts
- tests/edgeless/frame/frame.spec.ts
- tests/edgeless/group/clipboard.spec.ts
- tests/edgeless/group/group-and-ungroup.spec.ts
- tests/edgeless/group/group.spec.ts
- tests/edgeless/group/release.spec.ts
- tests/utils/actions/edgeless.ts
- tests/utils/asserts.ts
This PR is a continuation of PR #8518 and refactors the frame test with container test utils.
- Fix missing children when creating mindmap with toolbar, which lead to `xywh` is `[0, 0, 0, 0]` and fail to get the frame from the actual position of mindmap.
> refactor: update frame test with container test uitls

- packages/blocks/src/__tests__/adapters/html.unit.spec.ts
- packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
- packages/blocks/src/_common/adapters/html.ts
- packages/blocks/src/_common/adapters/markdown.ts
- packages/framework/store/src/adapter/base.ts
- tests/snapshots/clipboard/clipboard.spec.ts/clipboard-copy-nested-items-clipboard.json
- tests/snapshots/clipboard/clipboard.spec.ts/clipboard-copy-nested-items-clipboard2.json
- tests/snapshots/clipboard/list.spec.ts/copy-a-nested-list-by-clicking-button-the-clipboard-data-should-be-complete-clipboard.html
- tests/snapshots/clipboard/list.spec.ts/copy-a-nested-list-by-clicking-button-the-clipboard-data-should-be-complete-clipboard.json
This closes [BS-125](https://linear.app/affine-design/issue/BS-125), closes #6252, possibly closes #8126.
This PR also fixes a bug in markdown when encountering continuous lists with different type.
> fix(blocks): real nested list on html export

- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/widgets/element-toolbar/more-menu/config.ts
- tests/edgeless/frame/frame.spec.ts
- tests/edgeless/frame/selection.spec.ts
- tests/utils/actions/edgeless.ts
- tests/utils/asserts.ts
Close [BS-1579](https://linear.app/affine-design/issue/BS-1579/cmda全选会选到frame内部yuan素)
select shape unexpectly
https://github.com/user-attachments/assets/412115f8-9e89-43fc-b56f-a959ac25b40b
Only select frame because it is the container of the shape
https://github.com/user-attachments/assets/136b073a-4d38-486a-9493-764bcafacca7
> fix(edgeless): cmd a will select element inner frame

- packages/affine/block-embed/package.json
- packages/affine/block-surface/src/index.ts
- packages/affine/components/package.json
- packages/affine/data-view/package.json
- packages/blocks/package.json
- packages/blocks/src/root-block/widgets/element-toolbar/align-button.ts
- tests/edgeless/align.spec.ts
- tests/utils/actions/edgeless.ts
- tests/utils/asserts.ts
- yarn.lock
Close issue [BS-1538](https://linear.app/affine-design/issue/BS-1538).
- Support edgeless tidy up
- Auto arrange
- Auto resize
- Adjust align menu interaction
- Add e2e tests
<a href="https://app.graphite.dev/media/video/sJGviKxfE3Ap685cl5bj/0fb40894-8d04-4e9c-8382-92e4b3524f4f.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/sJGviKxfE3Ap685cl5bj/0fb40894-8d04-4e9c-8382-92e4b3524f4f.mov">录屏2024-10-14 17.44.08.mov</video>
> feat: support edgeless tidy up

- packages/affine/block-surface/src/renderer/elements/shape/utils.ts
- packages/affine/model/src/elements/mindmap/style.ts
- packages/affine/model/src/elements/shape/shape.ts
- packages/framework/global/src/types/index.ts
- packages/framework/store/src/store/collection.ts
- packages/playground/apps/starter/utils/collection.ts
Close [BS-1557](https://linear.app/affine-design/issue/BS-1557/mindmap-改进)
- Disable shadow blur of shape since it reduce the performance of canvas rendering when there are many mindmap. Close [BS-1246](https://linear.app/affine-design/issue/BS-1246/mindmapframe，左右平移巨巨巨巨巨卡)
- Add border to Mindmap style two. Close [BS-1559](https://linear.app/affine-design/issue/BS-1559/mindmap-去掉shadow)
https://github.com/user-attachments/assets/affabb9c-2278-49ff-ae44-e880f550a8f2
https://github.com/user-attachments/assets/757d55b3-8962-44bc-9712-4897235d6814
> perf(edgeless): disable shape shadow blur

- packages/affine/data-view/src/core/common/component/overflow/overflow.ts
https://github.com/user-attachments/assets/49aedca7-4f50-4c4c-aa27-e84b902b794b
close: #8560 
the problem cause is that we render both `add filter` and `{n} more` on `more view`, so the `renderCount` changes every times when recalculate.
first time we calculate it can place 3 items, after render, we can only place 2 items, and we will re-render...
> fix(database): avoid filter bar flickering

- packages/blocks/src/note-block/note-edgeless-block.ts
- tests/edgeless/note/note.spec.ts
- tests/edgeless/selection/selection.spec.ts
- tests/utils/asserts.ts
Fix issue [BS-1582](https://linear.app/affine-design/issue/BS-1582).
According to code in `sync-controller.ts`, if `xywh` has being stashed, the data in `yjs` can not be updated.
https://github.com/toeverything/blocksuite/blob/4493df8ab9f06e4bf52460505d446095a51b65eb/packages/framework/store/src/store/doc/block/sync-controller.ts#L173
> fix: newly created note alignments cannot be stored persistently

- packages/blocks/src/_common/transformers/markdown.ts
- packages/blocks/src/_common/transformers/middlewares.ts
- packages/playground/apps/_common/components/debug-menu.ts
- packages/playground/apps/starter/data/preset.ts
- packages/playground/apps/starter/data/synced.ts
[BS-1625](https://linear.app/affine-design/issue/BS-1625/markdown-transformer-支持多种导入方式)
Modified:
`importMarkdown` -> `importMarkdownToBlock`
New added:
```
type ImportMarkdownToDocOptions = {
collection: DocCollection;
markdown: string;
fileName?: string;
};
type ImportMarkdownZipOptions = {
collection: DocCollection;
imported: Blob;
};
async function importMarkdownToDoc(options: ImportMarkdownToDocOptions): Promise<string>
async function importMarkdownZip(options: ImportMarkdownZipOptions): Promise<string[]>
```
Now the importMarkdownZip function supports importing markdown files with assets, which means it can properly import markdown images.
> feat(blocks): support more markdown transformer api

- packages/framework/block-std/src/gfx/controller.ts
- packages/framework/block-std/src/gfx/identifiers.ts
- packages/framework/block-std/src/gfx/index.ts
- packages/framework/block-std/src/gfx/keyboard.ts
- packages/framework/block-std/src/gfx/tool/tool-controller.ts
- packages/framework/block-std/src/gfx/tool/tool.ts
The `EdgelessToolManager` has been renamed to `GfxToolController`. All the legacy tools will be rewrited using the new infra.
Let's take an example of pan tool.
```typescript
import { BaseTool } from '@blocksuite/block-std/gfx';
// extend the BaseTool
export class PanTool extends BaseTool {
// every tool class should have static toolName
static override toolName = 'pan';
dragStart(e) {
this._lastPoint = [e.x, e.y];
}
dragEnd(e) {
this._lastPoint = null;
}
dragMove(e) {
if (!this._lastPoint) return;
const { viewport } = this._service;
const { zoom } = viewport;
const [lastX, lastY] = this._lastPoint;
const deltaX = lastX - e.x;
const deltaY = lastY - e.y;
this._lastPoint = [e.x, e.y];
this.gfx.viewport.applyDeltaCenter(deltaX / zoom, deltaY / zoom);
}
}
```
Once you finish defining the …
> refactor: edgeless tool manager

- packages/affine/components/src/caption/captioned-block-component.ts
- packages/blocks/src/_common/components/block-zero-width.ts
closes: https://github.com/toeverything/blocksuite/issues/8567, https://github.com/toeverything/blocksuite/issues/8502, https://github.com/toeverything/blocksuite/issues/8466
> fix(database): can't use horizontal scrollbar

- packages/affine/shared/src/consts/index.ts
- packages/blocks/src/edgeless-text-block/edgeless-text-block.ts
- packages/blocks/src/effects.ts
- packages/blocks/src/root-block/edgeless/components/note-slicer/index.ts
- packages/blocks/src/root-block/edgeless/components/presentation/edgeless-navigator-black-background.ts
- packages/blocks/src/root-block/edgeless/components/rects/edgeless-dragging-area-rect.ts
- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/context.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/edgeless-toolbar.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/mixins/tool.mixin.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-spec.ts
- tests/edgeless/edgeless-text.spec.ts
- tests/utils/actions/edgeless.ts
Refactor those built-in component into widget:
- edgeless-selected-rect
- edgeless-dragging-area-rect
- edgeless-navigator-black-background
- edgeless-toolbar
- note-slicer
> refactor: convert built-in component to widget

- .changeset/strange-melons-sell.md
- feat(blocks): add more html transformer apis (#8573)
- feat(blocks): support more markdown transformer api (#8564)
- feat(blocks): add abort controller to peekviewservice (#8558)
- feat: add docLinkMiddleware for linked doc export (#8553)
- fix: mind map dragging issue (#8563)
- fix(database): can't use horizontal scrollbar (#8576)
- fix: note width is less than minimum width after resize and arrange (#8550)
- fix: newly created note alignments cannot be stored persistently (#8551)
- fix: inline range calculation not expected (#8552)
- fix(database): avoid filter bar flickering (#8562)
- fix(database): drag and drop block into database block (#8561)
- fix(blocks): split paragraphs based on newlines (#8556)
- fix(database): incorrect delete row logic (#8544)
- fix: note height less than …
> chore: release version

- packages/blocks/src/_common/components/button.ts
This PR prevents the hover state from being retained after a button is touched on mobile devices by using the `@media (hover: hover)` media query, which detects if the device has hover capability.
The pressed button has hover background
https://github.com/user-attachments/assets/2768a73b-e89f-4227-837e-7a4ef3052322
The pressed button dose not have hover background
https://github.com/user-attachments/assets/e2ec1ac7-5f06-4f9c-91bb-29d1d6ed04aa
> refactor(blocks): remove hover state after button pressed in mobile

- packages/framework/global/src/env/index.ts
- packages/framework/global/src/types/index.ts
- packages/framework/global/src/types/virtual-keyboard.ts
- packages/framework/global/src/utils/disposable.ts
Close [BS-1678](https://linear.app/affine-design/issue/BS-1678/virtualkeyboard-api-类型定义)
- This PR add `VirtualKeyboard` API type declaration.
>https://w3c.github.io/virtual-keyboard/#the-virtualkeyboard-interface
- Add `IS_MOBILE` env variable
> feat: add mobile detection and virtual keyboard support

- packages/affine/components/src/rich-text/effects.ts
- packages/affine/components/src/rich-text/format/index.ts
- packages/affine/components/src/rich-text/format/insert-inline-latex.ts
- packages/blocks/src/root-block/widgets/slash-menu/config.ts
This PR extract the implementation of insert inline equation from slash menu to a new rich-text command named `insertInlineLatex`
> refactor(blocks): extract insert inline latex to command

- packages/affine/components/src/rich-text/format/format-text.ts
- tests/hotkey/hotkey.spec.ts
- tests/snapshots/hotkey/hotkey.spec.ts/use-formatted-cursor-with-hotkey-at-empty-line-bold.json
Close [BS-1697](https://linear.app/affine-design/issue/BS-1697/空段落无法切换bold，进行加粗输入)
https://github.com/user-attachments/assets/ced2d025-e9a1-4f33-89f2-5efa5a84fa26
https://github.com/user-attachments/assets/5a13acf8-5e0f-454b-a5eb-6cef536bc58f
> fix(blocks): can not toggle text style in empty paragraph

- packages/affine/components/src/rich-text/effects.ts
- packages/affine/components/src/rich-text/format/index.ts
- packages/affine/components/src/rich-text/format/text-style.ts
- packages/affine/components/src/rich-text/format/utils.ts
- packages/affine/components/src/rich-text/index.ts
- packages/affine/model/src/blocks/latex/latex-model.ts
- packages/affine/model/src/blocks/surface-ref/surface-ref-model.ts
- packages/blocks/src/database-block/commands.ts
- packages/blocks/src/database-block/database-spec.ts
- packages/blocks/src/database-block/effects.ts
- packages/blocks/src/effects.ts
- packages/blocks/src/image-block/commands/index.ts
- packages/blocks/src/image-block/commands/insert-images.ts
- packages/blocks/src/image-block/effects.ts
- packages/blocks/src/latex-block/commands.ts
- packages/blocks/src/latex-block/effects.ts
- packages/blocks/src/latex-block/latex-spec.ts
- packages/blocks/src/root-block/widgets/index.ts
- packages/blocks/src/root-block/widgets/slash-menu/config.ts
- packages/blocks/src/root-block/widgets/slash-menu/index.ts
- packages/blocks/src/root-block/widgets/slash-menu/utils.ts
- packages/blocks/src/surface-ref-block/commands.ts
- packages/blocks/src/surface-ref-block/effects.ts
- packages/blocks/src/surface-ref-block/surface-ref-spec.ts
- tests/snapshots/latex/block.spec.ts/add-latex-block-using-slash-menu-finial.json
Close [BS-1688](https://linear.app/affine-design/issue/BS-1688/将-slash-menu-中的-action-实现提取并重构为通用的-command，以便在不同组件中复用)
- refactor toggle text style commands to `toggleTextStyleCommand`
- some new intert block commands, which can put the new block before or after current block
- `insertImages`, open a file dialog and insert the selected images
- `insertLatexBlock`, insert a display LaTeX block, may be open input dialog if `latex` parameter not provided
- `insertDatabaseBlock`
- `insertSurfaceRefBlock`
- Simplify slash-menu config implementation
> refactor(blocks): extract some common logics to commands

- packages/blocks/src/_specs/preset/edgeless-specs.ts
- packages/blocks/src/root-block/edgeless/middlewares/base.ts
- packages/framework/block-std/src/gfx/index.ts
- packages/framework/block-std/src/gfx/surface-middleware.ts
- packages/framework/block-std/src/scope/block-std-scope.ts
The previous middleware builder uses an internal class returned by a closure function, which may cause a problem where the DI container cannot parse the extension correctly.
> refactor(edgeless): rewrite surface middleware builder

- packages/blocks/src/root-block/widgets/slash-menu/config.ts
Close [BS-1548](https://linear.app/affine-design/issue/BS-1548/slash-menu中copy和duplicate的icon用错了)
> fix(blocks): fix incorrect copy duplicate icon in slash menu

- packages/blocks/src/edgeless-text-block/edgeless-text-block.ts
Close [BS-753](https://linear.app/affine-design/issue/BS-753/edgeless-text-中的-cardembed-等-block-不应跟着整个-text-变字体颜色字体家族和字重)
Close [BS-1635](https://linear.app/affine-design/issue/BS-1635/bug-edgeless-text-选择对齐的时候会影响-card)
> fix(edgeless): inline style only work on list and paragraph

- packages/affine/block-list/src/commands/dedent-list.ts
- packages/affine/block-list/src/commands/indent-list.ts
- packages/affine/block-list/src/commands/index.ts
- packages/affine/block-list/src/commands/split-list.ts
- packages/affine/block-list/src/effects.ts
- packages/affine/block-list/src/list-keymap.ts
- packages/affine/block-paragraph/src/commands/dedent-paragraph.ts
- packages/affine/block-paragraph/src/commands/indent-paragraph.ts
- packages/affine/block-paragraph/src/commands/index.ts
- packages/affine/block-paragraph/src/effects.ts
- packages/affine/block-paragraph/src/paragraph-keymap.ts
- packages/affine/shared/src/types/index.ts
This PR extracts the checking logic from `indentXXX` methods to `canIndentXXX` methods, enabling the implementation of a stateful UI that indicates the ability to indent paragraphs or lists.
- Extract `indentXXX` and `dedentXXX` checking logics to `canIndentXXX` and `canDedentXXX` commands
- `canIndentParagraph`
- `canDedentParagraph`
- `canIndentList`
- `canDedentLIst`
- Before using `indentXXX`, you should run `canIndentXXX`. For example
```ts
std.command
.chain()
.canIndentParagraph({blockId: 'block-id', inlineIndex: 0}) // the context is optional
.indentParagraph()
.run();
```
> refactor(blocks): extract indent dedent check logics to commands

- packages/framework/inline/src/__tests__/editor.unit.spec.ts
- packages/framework/inline/src/services/attribute.ts
- tests/hotkey/hotkey.spec.ts
- change the behavior of `getFormat` from right delta to left delta when the inline range is collapsed.
- add unit test for `getFormat`
This PR makes it possible to detect the current input text style using `const { textStyle } = std.command.exec('getTextStyle');`.
> fix(inline): get text format from left delta by default when it is collapsed

- packages/affine/block-surface/src/surface-block.ts
- packages/affine/shared/src/services/theme-service.ts
- packages/blocks/src/surface-block/mini-mindmap/surface-block.ts
- packages/blocks/src/surface-ref-block/surface-ref-block.ts
- packages/blocks/src/surface-ref-block/surface-ref-renderer.ts
- packages/playground/apps/starter/utils/editor.ts
Close issue [BS-1474](https://linear.app/affine-design/issue/BS-1474).
- Add `data-theme` on surface ref component
- Always use edgeless theme in `CanvasRenderer`
If edgeless theme is light:
If edgeless theme is dark:
> fix: add data-theme on surface ref component

- packages/blocks/src/root-block/root-config.ts
- packages/blocks/src/root-block/widgets/index.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/index.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-toolbar.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/utils.ts
This PR provide new two config field for mobile keyboard toolbar, `useScreenHeight` and `safeBottomPadding`.
- `useScreenHeight`. It is useful when the editor is used in  a webview widget, where the entire size of visual viewport and window will effected by virutal keyboard and lead the calculation of the height of virtual keyboard not correct.
- `safeBottomPadding`. It is useful when the device has rounded corner screen
> refactor(blocks): provide position controll config for keyboard toolbar

- packages/affine/block-surface/src/commands/auto-align.ts
- tests/edgeless/align.spec.ts
Close issue [BS-1621](https://linear.app/affine-design/issue/BS-1621).
Before:
After:
> fix: scale note and edgeless-text when resize and align elements

- packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-toolbar.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/utils.ts
- Fix keyboard is not opened after blur then focus
- Fix the state of keybaord toolbar not reset after blur
> fix(blocks): reset keyboard toolbar after blur

- packages/affine/widget-scroll-anchoring/src/scroll-anchoring.ts
Closes: [BS-1731](https://linear.app/affine-design/issue/BS-1731/在-chat-panel-中，可能无法获取到-offsetparent，scroll-anchoring-widget-报错)
> fix: use host instead of offsetParent

- packages/blocks/src/__tests__/adapters/notion-html.unit.spec.ts
- packages/blocks/src/_common/adapters/notion-html.ts
[BS-1754](https://linear.app/affine-design/issue/BS-1754/[bug]-database标题错了)
> fix: import notion database with title

- packages/affine/block-embed/src/embed-figma-block/embed-figma-block.ts
- packages/affine/block-embed/src/embed-github-block/embed-github-block.ts
- packages/affine/block-embed/src/embed-html-block/embed-html-block.ts
- packages/affine/block-embed/src/embed-linked-doc-block/embed-linked-doc-block.ts
- packages/affine/block-embed/src/embed-loom-block/embed-loom-block.ts
- packages/affine/block-embed/src/embed-synced-doc-block/embed-synced-doc-block.ts
- packages/affine/block-embed/src/embed-youtube-block/embed-youtube-block.ts
Fix issue [BS-1572](https://linear.app/affine-design/issue/BS-1572).
Set the value of `_cardStyle` at an earlier opportunity, in case the scale calculation uses the old `_cardStyle` value.
> fix: whiteboard is first loaded, size of the linked doc card is scaled to wrong size

- packages/affine/shared/src/services/theme-service.ts
- packages/affine/shared/src/utils/dom/checker.ts
- packages/affine/shared/src/utils/spec/spec-provider.ts
- packages/playground/apps/default/utils/editor.ts
- packages/playground/apps/starter/utils/editor.ts
Fix issue [BS-1762](https://linear.app/affine-design/issue/BS-1762).
After:
> fix: color of canvas element under embed dark theme whiteboard is wrong

- packages/blocks/src/root-block/page/page-root-block.ts
- tests/utils/actions/misc.ts
Close [BS-1734](https://linear.app/affine-design/issue/BS-1734/page-editor-需要撑开整个页面，并且支持点击新建段落)
> fix: add paragraph when last block in note is not empty paragraph

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [BlockSuite Guru](https://gurubase.io/g/blocksuite) to Gurubase. BlockSuite Guru uses the data from this repo and data from the [docs](https://blocksuite.io/) to answer questions by leveraging the LLM.
In this PR, I showcased the "BlockSuite Guru", which highlights that BlockSuite now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if …
> Introducing BlockSuite Guru on Gurubase.io

- packages/blocks/src/root-block/widgets/linked-doc/index.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/linked-doc/styles.ts
Close [BS-1788](https://linear.app/affine-design/issue/BS-1788/激活menu时，设置输入位置背景颜色)
This PR add a mask on the @ menu input arae.
> feat(blocks): add input mask when @ menu inputting

- packages/blocks/src/root-block/edgeless/components/color-picker/styles.ts
Closes: [BS-1773](https://linear.app/affine-design/issue/BS-1773/[bug]-edgeless-单独被设定为-light-mode-时-color-picker-的选中状态颜色错误)
> fix: color of button is actived on color picker

- packages/affine/components/src/portal/portal.ts
- packages/blocks/src/effects.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts
- packages/blocks/src/root-block/widgets/linked-doc/config.ts
- packages/blocks/src/root-block/widgets/linked-doc/effects.ts
- packages/blocks/src/root-block/widgets/linked-doc/index.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/slash-menu/config.ts
- Using `<blocksuite-portal>` to render linked doc popover
- Move side effects of linked doc widget to single file `widgets/linked-doc/effects.ts`
> refactor(blocks): render linked doc popover with blocksuite-portal

- packages/affine/components/src/virtual-keyboard/controller.ts
- packages/blocks/src/root-block/widgets/index.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts
- packages/blocks/src/root-block/widgets/linked-doc/config.ts
- packages/blocks/src/root-block/widgets/linked-doc/effects.ts
- packages/blocks/src/root-block/widgets/linked-doc/index.ts
- packages/blocks/src/root-block/widgets/linked-doc/linked-doc-popover.ts
- packages/blocks/src/root-block/widgets/linked-doc/mobile-linked-doc-menu.ts
- packages/blocks/src/root-block/widgets/linked-doc/styles.ts
- packages/blocks/src/root-block/widgets/slash-menu/config.ts
- packages/framework/global/src/types/index.ts
- packages/framework/store/src/store/collection.ts
- tests/linked-page.spec.ts
This PR introduce mobile @ menu(a.k.a linked doc widget). [(Close BS-1608)](https://linear.app/affine-design/issue/BS-1608/mobile-menu)
https://github.com/user-attachments/assets/1631111d-4a6f-44ef-8c9b-97afd6bc921e
- A new mobile at menu widget
- Fix at menu is triggered by <kbd>backspace</kbd> if previous character is `@`
> feat(blocks): mobile at menu

- packages/affine/components/src/virtual-keyboard/controller.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/index.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-toolbar.ts
- packages/blocks/src/root-block/widgets/linked-doc/index.ts
- packages/blocks/src/root-block/widgets/linked-doc/mobile-linked-doc-menu.ts
- keyboard is not opened when mobile `@` menu is triggered by keyboard toolbar
- mobile `@` menu is not closed after deleting `@`
- page is not scrolled to top when mobile `@` menu trigger by keyboard toolbar
https://github.com/user-attachments/assets/e4e08ec5-00df-4f9b-9179-18ac2b5f890e
> fix(blocks): show keyboard when at menu is triggered by keyboard toolbar

- packages/affine/block-embed/src/common/render-linked-doc.ts
- packages/blocks/src/surface-ref-block/surface-ref-service.ts
In `packages/blocks/src/surface-ref-block/surface-ref-renderer.ts` the method `viewport.setViewportElm` is not called which make the following code throw undefined error.
https://github.com/toeverything/blocksuite/blob/65fbde6782f1d9a2468aaf4bf5a4cf508eb466d5/packages/framework/block-std/src/gfx/viewport.ts#L53-L55
> fix(blocks): surface ref viewport element undefined

- packages/blocks/src/_common/adapters/markdown.ts
- packages/blocks/src/_common/adapters/mix-text.ts
> fix(blocks): only split paragraphs based on newlines

- packages/affine/components/src/rich-text/inline/presets/affine-inline-specs.ts
- packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-config.ts
- packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-node.ts
This PR make the visibility of reference node popup can be configure. Related to [BS-1730](https://linear.app/affine-design/issue/BS-1730/%E7%A6%81%E7%94%A8-block-yuan%E7%B4%A0%E7%9A%84-toolbar)
> chore: configrable visibility of reference node popup

- packages/presets/src/fragments/outline/header/outline-panel-header.ts
[BS-1631](https://linear.app/affine-design/issue/BS-1631/优化一下tooltips文本显示)
> fix(blocks): outline header sorting button tooltip

- packages/affine/block-list/src/list-block.ts
- tests/list.spec.ts
Close [BS-1558](https://linear.app/affine-design/issue/BS-1558/framepreview-渲染没有考虑list-toggled的情况)
This PR fix that a collpased list is not rendered correctly in readonly mode.
> fix(blocks): init collpased state of list

- packages/affine/model/src/elements/connector/connector.ts
Fixes [BS-1694](https://linear.app/affine-design/issue/BS-1694/[bug]-两个yuan素使用-connector-相连接使用-duplicate-会丢失-connector)
> fix(edgeless): connector clone

- packages/affine/model/src/blocks/attachment/attachment-model.ts
- packages/affine/model/src/utils/types.ts
- packages/affine/shared/src/consts/index.ts
- packages/blocks/src/attachment-block/components/options.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-attachment-button.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
* adds `pdf` style to attachment
* not allowed to switch card style when it is pdf
> feat: add pdf style to attachment

- packages/blocks/src/root-block/edgeless/frame-manager.ts
- packages/blocks/src/root-block/edgeless/gfx-tool/frame-tool.ts
- packages/framework/block-std/src/gfx/layer.ts
- tests/edgeless/frame/layer.spec.ts
- tests/edgeless/presentation.spec.ts
Close [BS-1827](https://linear.app/affine-design/issue/BS-1827/%E6%96%B0%E5%BB%BA%E7%9A%84frame%E6%B2%A1%E6%9C%89%E9%BB%98%E8%AE%A4%E7%BD%AE%E5%BA%95)
- `LayerManager.generateIndex(reverse = false)` is introduced that you can generate a bottom index by passing `true` to the parameter`reverse`
- Fix the zindex of a new frame is always `a0` to a bottom index like `Zz`
- Skip the test about frame presentation ordering, since the implementation of it is based on fractional index incorrectly.
> fix(edgeless): new frame should be on the bottom layer

- packages/blocks/src/root-block/widgets/slash-menu/config.ts
Close [BS-1757](https://linear.app/affine-design/issue/BS-1757/中文输入法下触发slashmenu问题)
This PR removes the trigger key `、` from the slash menu to improve the CJK user input experience. For users of Sougo Pinyin on macOS, you can disable the auto-transform from `/` to `、` in the IME settings.
> chore(blocks): remove trigger key '、' from slash menu

- packages/blocks/src/root-block/edgeless/frame-manager.ts
- tests/edgeless/frame/frame.spec.ts
Close [BS-1756](https://linear.app/affine-design/issue/BS-1756/[bug]-frame-拖出选区的时候，选中状态没有随着-frame-的大小实时更新)
Fixed frame outline rendering during frame-tool dragging creation by tracking previous XYWH state.
- Added a `_prevXYWH` property to `FrameOverlay` class to track the previous frame dimensions, and refresh canvas when it changed.
- Added a test to test the matching between color of dragging point and outline overlay.
> fix(edgeless): frame overlay is not updated during dragging a new frame

- packages/affine/data-view/src/property-presets/progress/cell-renderer.ts
> fix(database): prevent the default behavior of arrow keys when a progress cell is focused

- packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
- packages/blocks/src/_common/adapters/markdown.ts
- packages/blocks/src/_common/test-utils/test-utils.ts
When configured with `docBaseUrl`, `markdownAdapter `can convert doc references in snapshot into markdown link, and can also convert markdown link into doc reference.
> feat(blocks): markdown adapter reference serialization and deserialization

- packages/affine/data-view/src/view-presets/table/table-view.ts
This behavior should be disabled to prevent crash on mobile safari (same root cause with #8680):
https://github.com/user-attachments/assets/22a40c9b-5bae-4cf4-8b47-c291d4af881a
Meanwhile, this fix won't affect horizontal scrolling of database block in doc mode.
> fix(database): crash in edgeless on mobile safari

- packages/affine/block-embed/src/embed-linked-doc-block/embed-edgeless-linked-doc-block.ts
- packages/affine/block-embed/src/embed-synced-doc-block/embed-edgeless-synced-doc-block.ts
- packages/affine/block-embed/src/embed-synced-doc-block/embed-synced-doc-block.ts
Close [BS-1907](https://linear.app/affine-design/issue/BS-1907/mode=edgeless的cardview转成embed，丢失了mode信息)
This PR fixed the reference information is missing during edgeless card view conversion. The test will be added to AFFiNE side https://github.com/toeverything/AFFiNE/pull/8887
> fix(edgeless): missing reference info during edgeless card conversion

- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
Instead of setting the `_selectedRect` state, use CSS `border-style: none` to hide the selected rect border when a connector is selected.
> fix(edgeless): connector selected rect width and height is zero

- packages/blocks/src/root-block/edgeless/clipboard/clipboard.ts
- tests/edgeless/paste-block.spec.ts
To fix [BS-1979](https://linear.app/affine-design/issue/BS-1979/从-page-模式复制到-edgeless-模式功能故障)
> fix(blocks): should paste text content as note on edgeless when copy from doc mode

- packages/framework/store/package.json
> fix(store): add shim.d.ts to files

- packages/playground/apps/_common/components/adapters-panel.ts
- packages/playground/apps/_common/components/debug-menu.ts
[BS-1960](https://linear.app/affine-design/issue/BS-1960/bs-playground-实现一个基础导出对比的-panel)
https://github.com/user-attachments/assets/118aa4d8-6361-4d72-a4cf-ed2478144808
> feat(playground): add an adpater panel to playground

- packages/affine/block-list/package.json
- packages/affine/block-list/src/adapters/markdown.ts
- packages/blocks/src/__tests__/adapters/html.unit.spec.ts
- packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
- packages/blocks/src/_common/adapters/html.ts
- yarn.lock
This closes [BS-1947](https://linear.app/affine-design/issue/BS-1947)
> feat(blocks): add support for non consecutive list in adapter

- packages/affine/block-embed/src/common/adapters/plain-text.ts
- packages/affine/block-embed/src/embed-figma-block/adapters/index.ts
- packages/affine/block-embed/src/embed-figma-block/adapters/plain-text.ts
- packages/affine/block-embed/src/embed-figma-block/index.ts
- packages/affine/block-embed/src/embed-github-block/adapters/index.ts
- packages/affine/block-embed/src/embed-github-block/adapters/plain-text.ts
- packages/affine/block-embed/src/embed-github-block/index.ts
- packages/affine/block-embed/src/embed-loom-block/adapters/index.ts
- packages/affine/block-embed/src/embed-loom-block/adapters/plain-text.ts
- packages/affine/block-embed/src/embed-loom-block/index.ts
- packages/affine/block-embed/src/embed-youtube-block/adapters/index.ts
- packages/affine/block-embed/src/embed-youtube-block/adapters/plain-text.ts
- packages/affine/block-embed/src/embed-youtube-block/index.ts
- packages/affine/block-embed/src/index.ts
- packages/blocks/src/__tests__/adapters/plain-text.unit.spec.ts
- packages/blocks/src/_common/adapters/plain-text/block-matcher.ts
- packages/blocks/src/bookmark-block/adapters/index.ts
- packages/blocks/src/bookmark-block/adapters/plain-text.ts
- packages/blocks/src/bookmark-block/index.ts
[BS-2037](https://linear.app/affine-design/issue/BS-2037/补齐-embed-link-block)
> feat(blocks): add plain text block adapter for embed link block

- packages/affine/data-view/src/property-presets/date/cell-renderer.ts
> refactor(database): make Date-Picker component compatible with mobile devices

- packages/blocks/src/_specs/index.ts
- packages/blocks/src/_specs/preset/mobile-patch.ts
- packages/playground/apps/default/utils/editor.ts
This PR provides a mobile patches for better user experience. Close [BS-1824](https://linear.app/affine-design/issue/BS-1824/移动端去除-slash的响应)
- hide inline reference popup
- use `keyboard-toolbar` instead of slash menu and block toolbar widgets
- a new @ menu for mobile
- update paragraph placeholder description
In the setup stage of editor, add this spec patches to editor
```ts
import {  MobileSpecsPatches } from '@blocksuite/blocks';
import { IS_MOBILE } from '@blocksuite/global/env';
if (IS_MOBILE) {
editor.pageSpecs.push(MobileSpecsPatches);
editor.edgelessSpecs.push(MobileSpecsPatches);
}
```
> feat(blocks): provide a mobile spec patches

- packages/affine/shared/src/services/generate-url-service.ts
- packages/affine/shared/src/services/index.ts
- packages/playground/apps/_common/components/docs-panel.ts
- packages/playground/apps/_common/mock-services.ts
- packages/playground/apps/default/utils/editor.ts
Closes: [BS-1961](https://linear.app/affine-design/issue/BS-1961/实现-generatedocurlservice)
In the `Alias` ​​function, we need to copy the link, and need a service that can generate a complete link.
Complementary with `ParseDocUrlService`.
https://github.com/user-attachments/assets/7c5c1927-f942-4f05-9b1f-1f1c1cb6d740
> feat: generate url service

- packages/affine/block-embed/src/embed-linked-doc-block/adapters/index.ts
- packages/affine/block-embed/src/embed-linked-doc-block/adapters/plain-text.ts
- packages/affine/block-embed/src/embed-linked-doc-block/index.ts
- packages/affine/block-embed/src/embed-synced-doc-block/adapters/index.ts
- packages/affine/block-embed/src/embed-synced-doc-block/adapters/plain-text.ts
- packages/affine/block-embed/src/embed-synced-doc-block/index.ts
- packages/blocks/src/__tests__/adapters/markdown.unit.spec.ts
- packages/blocks/src/__tests__/adapters/plain-text.unit.spec.ts
- packages/blocks/src/_common/adapters/markdown/delta-converter/inline-delta.ts
- packages/blocks/src/_common/adapters/plain-text/block-matcher.ts
- packages/blocks/src/_common/adapters/plain-text/delta-converter/inline-delta.ts
- packages/blocks/src/_common/adapters/plain-text/plain-text.ts
- packages/blocks/src/_common/transformers/middlewares.ts
- packages/playground/apps/_common/components/adapters-panel.ts
[BS-2040](https://linear.app/affine-design/issue/BS-2040/补齐-linked-doc-和-synced-doc-plain-text-adapter)
> feat(blocks): add plain text block adapter for linked and synced doc block

- packages/blocks/src/edgeless-text-block/edgeless-text-block.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/common/draggable/draggable-element.controller.ts
- packages/framework/block-std/src/gfx/controller.ts
- packages/framework/block-std/src/gfx/viewport.ts
- packages/framework/block-std/src/scope/block-std-scope.ts
- packages/framework/block-std/src/view/element/lit-host.ts
- tests/edgeless/edgeless-text.spec.ts
Before (`<editor-host>` is detached after switching editor mode, causing significant memory surge for large docs):
After (no detached `<editor-host>`):
> fix: memory leak on switching from doc to edgeless

- packages/blocks/src/root-block/edgeless/gfx-tool/default-tool.ts
- tests/edgeless/align.spec.ts
- tests/edgeless/frame/clipboard.spec.ts
- tests/edgeless/frame/frame-mindmap.spec.ts
- tests/edgeless/frame/frame.spec.ts
- tests/edgeless/frame/selection.spec.ts
Close [BS-2023](https://linear.app/affine-design/issue/BS-2032/[improvement]-框选行为)
- Refined clicking selection on frames:
- If a frame has a title, it can only be selected by clicking the title.
- If a frame does not have a title, it can be selected by clicking anywhere within the frame area.
- Refined dragging selection on frames:
- If a frame is empty, it can be selected if the dragging rectangle intersects with the frame.
- If a frame is not empty, it can be selected only if the dragging rectangle contains the entire frame.
- Refined dragging selection on mindmaps:
- A single node can be selected.
- The entire mindmap can be selected only if the dragging rectangle contains the entire mindmap.
- Tests updated
https://github.com/user-attachments/assets/e3414945-93f9-411a-87f2-c8a3dc033c1 …
> refactor(edgeless): adjust logic of dragging selection

- packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/effects.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/index.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-tool-panel.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-toolbar.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/styles.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/utils.ts
Close [BS-1930](https://linear.app/affine-design/issue/BS-1930/移动端回车后页面不会滚动，需要能够滚动到光标输入位置) [BS-1922](https://linear.app/affine-design/issue/BS-1922/slash-menu-需要一个底部额外的padding) [BS-1923](https://linear.app/affine-design/issue/BS-1922/slash-menu-需要一个底部额外的padding)
- made `affine-keyboard-toolbar` and `affine-keyboard-tool-panel` shadowless
- removed `safeBottomPadding`. It is better to use CSS control the widget style
- fixed auto scroll current block not work
> refactor(blocks): shadowless keyboard toolbar

- packages/framework/block-std/src/view/element/shadowless-element.ts
If a `ShadowlessElement` is rendered inside of a shadowroot node, its styles should  also be appended to the shadowroot, instead of into the document head.
For the moment some styles are defined in ShadowlessElement are considered globally and will be available even if they are not being rendered, because their styles are attached to the document.head on resolving styles. For compatibility, these are not being removed in this PR.
fix BS-2047
> fix(std): shadowless element should inject styles in parent node

- packages/blocks/src/frame-block/frame-block.ts
Before (frame layers are too large and leads to OOM):
After (no layer with excessive size):
> fix(edgeless): large frame crash on ios safari

- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/framework/block-std/src/event/control/pointer.ts
- packages/framework/global/src/utils/math.ts
- tests/edgeless/basic.spec.ts
Improves the calculation of multi-touch gestures and makes them smoother on Android and fixes them on iOS
**master android samsung galaxy s24 chrome:**
https://github.com/user-attachments/assets/5a41d922-bfdd-4743-b445-0cfa69175136
Visible jumps during pan gesture
**current branch with fix android samsung galaxy s24 chrome:**
https://github.com/user-attachments/assets/647bb8e9-0e58-4aaa-bf14-179be74f31a6
Smooth pan gesture with two fingers without jumping
> fix(std): pan and pinch events were calculate relative to only one finger

- packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-node.ts
Closes: [BS-2066](https://linear.app/affine-design/issue/BS-2066/inline-view-改了-alias-之后没有显示-alias-图标)
> fix: should show alias icon when title has alias

- packages/playground/apps/_common/components/docs-panel.ts
> fix(playground): adapt docs panel to dark mode

- packages/framework/block-std/src/gfx/index.ts
- packages/framework/block-std/src/gfx/model/base.ts
- packages/framework/block-std/src/gfx/model/gfx-block-model.ts
- packages/framework/block-std/src/gfx/model/surface/element-model.ts
- packages/framework/block-std/src/gfx/model/surface/surface-model.ts
- packages/framework/block-std/src/utils/tree.ts
Close [BS-1882](https://linear.app/affine-design/issue/BS-1882/锁：infra)
This PR implemented the basic edgeless lock feature.
```ts
export interface GfxCompatibleInterface extends IBound, GfxElementGeometry {
// ......
/**
* Indicates whether the current block is explicitly locked by self.
* For checking the lock status of the element, use `isLocked` instead.
* For (un)locking the element, use `(un)lock` instead.
*/
lockedBySelf?: boolean;
/**
* Check if the element is locked. It will check the lock status of the element and its ancestors.
*/
isLocked(): boolean;
isLockedBySelf(): boolean;
isLockedByAncestor(): boolean;
lock(): void;
unlock(): void;
}
```
> feat(edgeless): impl lock interface for edgeless element and block

- packages/blocks/src/frame-block/frame-block.ts
- packages/blocks/src/root-block/edgeless/clipboard/clipboard.ts
- packages/blocks/src/root-block/edgeless/components/rects/edgeless-selected-rect.ts
- packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/edgeless/frame-manager.ts
- packages/blocks/src/root-block/edgeless/gfx-tool/default-tool.ts
- packages/blocks/src/root-block/edgeless/gfx-tool/eraser-tool.ts
- packages/blocks/src/root-block/edgeless/gfx-tool/lasso-tool.ts
- packages/blocks/src/root-block/edgeless/utils/query.ts
- packages/blocks/src/root-block/widgets/element-toolbar/effects.ts
- packages/blocks/src/root-block/widgets/element-toolbar/index.ts
- packages/blocks/src/root-block/widgets/element-toolbar/lock-button.ts
- packages/framework/block-std/src/gfx/model/surface/element-model.ts
- packages/framework/block-std/src/utils/tree.ts
Close [BS-1926](https://linear.app/affine-design/issue/PD-1926/[improvement]-lock)
This PR introduces an edgeless element locking feature. An element that is locked typically cannot undergo any operations that affect its data, except for unlocking. Operations that clearly do not affect its data, such as copying or linking the locked element, are still permitted. This functionality is mainly implemented by blocking actions at the user interaction level.
- Lock and unlock buttons are added to `edgeless-element-toolbar`
- In mindmap, only the root node can be locked (close [BS-1875](https://linear.app/affine-design/issue/BS-1875/锁：mindmap只能锁根节点)).
- Lock an element will also lock all descendants. （close [BS-1880](https://linear.app/affine-design/issue/BS-1880/锁-锁group和frame会同时锁后代yuan素)） 
- A …
> feat(edgeless): unlock and unlock button

- packages/blocks/src/_common/components/embed-card/modal/embed-card-edit-modal.ts
Closes: [BS-2083](https://linear.app/affine-design/issue/BS-2083/button-disable态样式错误)
> fix(blocks): button styling when disabled on embed card edit popup

- packages/affine/block-embed/src/embed-linked-doc-block/styles.ts
- packages/blocks/src/bookmark-block/styles.ts
close BS-1942, BS-2089
<a href="https://app.graphite.dev/media/video/LakojjjzZNf6ogjOVwKE/004809e0-5e7a-4703-9346-e50c8484bb43.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/LakojjjzZNf6ogjOVwKE/004809e0-5e7a-4703-9346-e50c8484bb43.mp4">CleanShot 2024-12-10 at 11.35.38.mp4</video>
> fix(blocks): hide the thumb for bookmark if its width is less than 375

- packages/affine/components/src/rich-text/inline/presets/nodes/reference-node/reference-popup.ts
- packages/blocks/src/root-block/widgets/element-toolbar/change-embed-card-button.ts
- packages/blocks/src/root-block/widgets/embed-card-toolbar/embed-card-toolbar.ts
Closes: [BS-2065](https://linear.app/affine-design/issue/BS-2065/这里-hovertips-应该显示-linked-doc-的原始完整标题)
> fix(blocks): should show original doc title when hovering title button

- packages/affine/block-embed/src/embed-synced-doc-block/embed-edgeless-synced-doc-block.ts
- tests/linked-page.spec.ts
Closes: [BS-2099](https://linear.app/affine-design/issue/BS-2099/在白板上，插入的-embed-view，在编辑了-alias-之后会丢失信息)
> fix(blocks): missing aliases when converting from embed to card

- packages/blocks/src/root-block/widgets/drag-handle/watchers/drag-event-watcher.ts
drag from an external app and drop to blocksuite will invoking default behavior. for example, dropping an link will open the link in place
> fix(blocks): should prevent default if drop event is handled

- .vscode/extensions.json
This is removed due to https://github.com/vitest-dev/vitest/issues/6714.
> fix: remove vitest extension from recommendation list

- packages/blocks/src/root-block/edgeless/clipboard/clipboard.ts
Closes: [BS-2100](https://linear.app/affine-design/issue/BS-2100/在白板上，为添加了-alias-信息的-linked-doc-创建副本，会丢失-alias-信息)
> fix(blocks): missing aliases when duplicating linked doc block on edgeless

- packages/blocks/src/root-block/widgets/keyboard-toolbar/config.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/index.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/keyboard-toolbar.ts
- packages/blocks/src/root-block/widgets/keyboard-toolbar/styles.ts
Close [BS-2088](https://linear.app/affine-design/issue/BS-2088/ios-移动端-光标会高于键盘toolbar的高度) [BS-1945](https://linear.app/affine-design/issue/BS-1945/标题输入需要有键盘收起按钮) [BS-2113](https://linear.app/affine-design/issue/BS-2113/打开编辑器再回到首页后，底部的-padding-会重置为-0)
- show mobile keyboard toolbar when focus on title
- hide mobile keyboard toolbar when scrolling window
- hide mobile keyboard toolbar when clicking the keyboard button
- hide horizontal scrollbar of keyboard toolbar
> fix(blocks): show keyboard toolbar when focus on title and hide on scrolling

- packages/affine/data-view/src/view-presets/kanban/pc/controller/hotkeys.ts
- tests/database/actions.ts
- tests/database/selection.spec.ts
Fixes #8643
- Fixes a bug where a user can not move the cursor with right and left arrow keys, when editing title of kanban cards
- Added an e2e test case
Ran these test cases, they all pass:
`tests/database/selection.spec.ts`
`tests/database/database.spec.ts`
> fix(database): move cursor in kanban card title by arrow keys

- packages/blocks/src/_common/components/filterable-list/index.ts
- tests/code/crud.spec.ts
Fixes #8565
Language list in code block didn't work as intended in Firefox. This issue was caused by the use of `Infinity` in sorting algorithm which leads to inconsistent behavior across different browsers
**Before (firefox only)**
https://github.com/user-attachments/assets/cb55f472-29fe-4e64-98b6-1039b82be318
**After**
https://github.com/user-attachments/assets/a2c9fcba-16ce-4d3e-a17c-c89f0badcf52
> fix(blocks): inconsistent language list behavior on hover in Firefox

- packages/presets/vitest.config.ts
`yarn run test:unit` should use `headless: false` locally now.
For example, to debug group test, simply use `yarn run test:unit group.spec.ts` now.
> chore: run headless vitest locally by default

- packages/blocks/src/root-block/widgets/keyboard-toolbar/styles.ts
- packages/blocks/src/root-block/widgets/linked-doc/styles.ts
Close [BS-1830](https://linear.app/affine-design/issue/BS-1830/menu-字体错误)
Related: https://stackoverflow.com/questions/32660748/how-to-use-apples-san-francisco-font-on-a-webpage#answer-32660790
>Apple's new system font is not publicly exposed. Apple has started abstracting system font names:
>>The motivation for this abstraction is so the operating system can make better choices on which face to use at a given weight. Apple is also working on font features, such as selectable “6″ and “9″ glyphs or non-monospaced numbers. It’s my guess that they’d like to bring these features to the web, as well.
>>
>Safari and Firefox use SF for -apple-system; Chrome recognizes BlinkMacSystemFont:
> fix(blocks): fix incorrect font family in mobile widgets

- packages/affine/block-embed/src/common/embed-block-element.ts
- packages/blocks/src/attachment-block/attachment-block.ts
- packages/blocks/src/bookmark-block/bookmark-block.ts
Closes: [BS-2012](https://linear.app/affine-design/issue/BS-2012/card-view-和-embed-view-本身不支持拖拽)
> fix: attachment, bookmark and embed blocks should be draggable

- packages/blocks/src/root-block/widgets/drag-handle/watchers/drag-event-watcher.ts
Closes: [BS-2134](https://linear.app/affine-design/issue/BS-2134/preview-not-disappear-when-drag-out-of-editor)
> fix: preview won't disappear after drag end

- packages/affine/shared/src/services/telemetry-service/types.ts
- packages/blocks/src/image-block/index.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/template/template-panel.ts
- packages/blocks/src/root-block/edgeless/components/toolbar/template/template-type.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-service.ts
- packages/blocks/src/root-block/index.ts
- packages/blocks/src/surface-block/mini-mindmap/mindmap-preview.ts
- Exposed `uploadBlobForImage` utility function
- Refactor `createTemplateJob` for reuse
- Exposed `TemplateJob` and `TemplateMiddlewares` APIs
Support issue [BS-2085](https://linear.app/affine-design/issue/BS-2085).
> fix(edgeless): export template job and image upload api

- packages/blocks/src/root-block/widgets/element-toolbar/change-frame-button.ts
- tests/edgeless/frame/frame.spec.ts
Added an ungroup button for frame that only remove frame without deleteing its children
> feat(edgeless): release frame by clicking ungroup button

- packages/blocks/src/root-block/edgeless/frame-manager.ts
- tests/edgeless/frame/frame.spec.ts
Close [BS-2108](https://linear.app/affine-design/issue/BS-2108/选中yuan素创建frame去掉最小尺寸限制，选中创建嵌套frame优化)
This PR fixed the bound of new inner frame is not inside in parent frame.
https://github.com/user-attachments/assets/ffaa5cbb-98b9-4d2c-bc7b-af5c0f2132aa
https://github.com/user-attachments/assets/470d8e3c-4e71-451c-8111-a2ea1b750ea9
> fix(edgeless): new inner frame should be inside parent frame

- packages/affine/block-embed/src/embed-linked-doc-block/styles.ts
- tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-drag.json
- tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-link-to-card-min-width.json
- tests/snapshots/edgeless/edgeless-text.spec.ts/min-width-limit-for-embed-block-link-to-card.json
Close [BS-1777](https://linear.app/affine-design/issue/BS-1777/card在切换为full-width后没有responsively适配)
> fix(blocks): the width of the card view is not fully filled

- packages/framework/block-std/src/event/control/pointer.ts
Closes: [BS-2136](https://linear.app/affine-design/issue/BS-2136/attachementbookmark拖拽到白板后，白板所有拖拽都无法工作)
Closes: [BS-2143](https://linear.app/affine-design/issue/BS-2143/block通过drag-handle拖动位置后，无法输入)
> fix: dnd status error

- packages/affine/shared/src/services/theme-service.ts
> fix(blocks): toolbar color should be light when app theme is light and edgeless theme is dark

- packages/framework/inline/src/consts.ts
Close [BS-1823](https://linear.app/affine-design/issue/BS-1823/收入首行文字时，关闭高亮的定位有问题)
when `anchorOffset===0`, the position of caret during IME inputing is not correcte
https://github.com/user-attachments/assets/089f6c42-cd9b-4ee0-9bff-2db5d1067671
https://github.com/user-attachments/assets/b84544aa-3a9f-412b-91b0-dbb10a0be1e4
> fix(inline): incorrect caret position in safari when using IME

- packages/affine/block-surface/src/renderer/canvas-renderer.ts
- packages/affine/model/src/elements/connector/local-connector.ts
- packages/affine/model/src/elements/mindmap/mindmap.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-block.ts
- packages/blocks/src/root-block/edgeless/edgeless-root-preview-block.ts
- packages/blocks/src/root-block/edgeless/frame-manager.ts
- packages/framework/block-std/src/gfx/grid.ts
- packages/framework/block-std/src/gfx/index.ts
- packages/framework/block-std/src/gfx/layer.ts
- packages/framework/block-std/src/gfx/model/base.ts
- packages/framework/block-std/src/gfx/model/surface/element-model.ts
- packages/framework/block-std/src/gfx/model/surface/local-element-model.ts
- packages/framework/block-std/src/gfx/model/surface/surface-model.ts
- packages/framework/block-std/src/utils/layer.ts
- packages/framework/block-std/src/utils/tree.ts
- tests/utils/actions/edgeless.ts
To define a local element, create a class that extends `GfxLocalElementModel`, and use the `@prop` decorator on any field that you want to track changes for via `localElementUpdated`.
Note: Do **not** use any Yjs data structures, as local elements are intended for local data only. 
Example:
```typescript
import { GfxLocalElementModel, prop } from '@blocksuite/block-std/gfx';
export class LocalTextElement extends GfxLocalElementModel {
get type() {
return 'text'
}
@prop()
accessor text: string = '';
}
```
Once the class is defined, create an instance with `const localText = new LocalTextElement(surfaceModel)`. You can then use its render function to manually render the model.
To watch `@prop` decorated property changes, use `surface.localElementUpdated` to listen for updates.
Add instances …
> feat(edgeless): improve local element support

- packages/blocks/src/root-block/edgeless/gfx-tool/default-tool-ext/event-ext.ts
- packages/blocks/src/root-block/edgeless/gfx-tool/default-tool-ext/ext.ts
- packages/blocks/src/root-block/edgeless/gfx-tool/default-tool-ext/mind-map-ext/mind-map-ext.ts
- packages/blocks/src/root-block/edgeless/gfx-tool/default-tool.ts
- packages/framework/block-std/src/gfx/grid.ts
- packages/framework/block-std/src/gfx/index.ts
- packages/framework/block-std/src/gfx/model/surface/element-model.ts
- packages/framework/block-std/src/gfx/model/surface/surface-model.ts
- packages/framework/block-std/src/gfx/surface-middleware.ts
- packages/framework/block-std/src/gfx/view/view-manager.ts
- packages/framework/block-std/src/gfx/view/view.ts
- packages/framework/block-std/src/scope/block-std-scope.ts
This PR introduces the concept of views for canvas elements. Each canvas element, including those local element added via `addLocalElement`, now has an associated view instance. Views handle logic related to the view layer, such as binding mouse events to elements.
```typescript
const modelView = std.gfx.view.get(model);
view.on('pointerenter', () => {
console.log('mouse entered the element.');
});
```
You don’t need to manually instantiate views for elements. They are automatically managed by the `ViewManager`.
By default, each element's view is an instance of the `GfxElementModelView` class. However, you can define custom view classes for specific element types
```typescript
import { GfxElementModelView } from '@blocksuite/block-std/gfx';
export class ShapeView extends …
```
> feat(edgeless): add views and event support for canvas elements

- packages/affine/block-surface/src/adapters/plain-text/element-adapter/elements/brush.ts
- packages/affine/block-surface/src/adapters/plain-text/element-adapter/elements/connector.ts
- packages/affine/block-surface/src/adapters/plain-text/element-adapter/elements/group.ts
- packages/affine/block-surface/src/adapters/plain-text/element-adapter/elements/index.ts
- packages/affine/block-surface/src/adapters/plain-text/element-adapter/elements/mindmap.ts
- packages/affine/block-surface/src/adapters/plain-text/element-adapter/elements/shape.ts
- packages/affine/block-surface/src/adapters/plain-text/element-adapter/elements/text.ts
- packages/affine/block-surface/src/adapters/plain-text/element-adapter/index.ts
- packages/affine/block-surface/src/adapters/plain-text/element-adapter/type.ts
- packages/affine/block-surface/src/adapters/plain-text/plain-text.ts
- packages/affine/block-surface/src/adapters/type.ts
- packages/affine/block-surface/src/adapters/types/mindmap.ts
- packages/affine/block-surface/src/adapters/utils/mindmap.ts
- packages/affine/block-surface/src/adapters/utils/shape.ts
- packages/affine/shared/src/adapters/plain-text/block-adapter.ts
- packages/blocks/src/_common/adapters/plain-text/plain-text.ts
[BS-2163](https://linear.app/affine-design/issue/BS-2163/补齐-mindmap-plain-text-adapter)
> feat(blocks): add plain text adapter for mind map element

- packages/affine/block-surface/src/renderer/elements/mindmap.ts
Fixes [BS-2030](https://linear.app/affine-design/issue/BS-2030/重叠的-mindmap-连接线没法用-opacity-0-隐藏)
> fix: mind map opacity

- packages/affine/block-surface/src/managers/connector-manager.ts
- packages/affine/block-surface/src/renderer/canvas-renderer.ts
- packages/affine/block-surface/src/renderer/overlay.ts
- packages/blocks/src/root-block/edgeless/utils/tool-overlay.ts
This removes the green spikes during zooming, which is caused by per-render DOM queries in connector manager:
> perf(edgeless): reduce redundant dom query per render

- packages/affine/block-embed/src/embed-synced-doc-block/embed-synced-doc-block.ts
> fix(blocks): fix title and icon display issue in embed synced doc block
